### ISSUE TITLE
Add Node category in the asset store

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-proposals#1355] opened 2020-08-12 16:04 UTC
**Describe the project you are working on:**
2D platformer.

**Describe the problem or limitation you are having in your project:**
Making a FSM for every character, consumes a lot of development time, would be nice if you could download some Generic "Character" Node from the asset store, some generic "Item" and some generic "Enemy" as well, and just edit them for my game.
Would really speed up development.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The asset store should have some Node category, where common solutions to most genres would be made by the comunity into a single custom Node, to be shared on the asset store of Godot.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Just a new category for custom made comunity nodes.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, this is core to the asset store of Godot.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Would really improve the usefulness of the Asset store, and would be much simpler and easier to develop a simple custom node, than a full demo or template for Godot.

**Comment by nonunknown** [comment] 2020-08-12 17:37
I think this is most related to the creator of the asset, rather than asset lib.

**Comment by KoBeWi** [comment] 2020-08-12 20:55
The problem is that usually such elements are very game specific. Character nodes are composed not only of script, but also sprite and colliders. There's little use to download all of it, and character controller scripts are already in the lib.

btw you don't need FSM for everything.

**Comment by willnationsdev** [comment] 2020-08-19 21:17
I feel like this proposal is pretty unnecessary. The revised Asset Library implementation that is being worked on will already support arbitrary tags, so there is nothing stopping someone from putting a `node` tag on the asset. Then people can filter search results by `node` and pull up a list of independently shared nodes to download into their projects (assuming the tag catches on in the community).

**Comment by Calinou** [comment] 2020-09-13 23:36
Closing due to lack of support.

**Closed by Calinou** 2020-09-13 23:36 UTC
Labels: topic:assetlib
