### ISSUE TITLE
per-scene undo

### ISSUE THREAD

**Issue by CrezyDud** [godotengine/godot-proposals#4125] opened 2022-02-26 21:13 UTC
### Describe the project you are working on

hi

### Describe the problem or limitation you are having in your project

i lost a lot of stuff after cutting it from one scene and then some "cannot paste root from same scene" or some weird error

and i couldn't undo because it kept switching scenes until it hit the really low undo limit

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

per scene undo, like with scripts already

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

normal undo shortcut stuff

### If this enhancement will not be used often, can it be worked around with a few lines of script?

i dont think it can be

and it will be very appreciated

### Is there a reason why this should be core and not an add-on in the asset library?

i dont think it can be

**Comment by Calinou** [comment] 2022-02-26 22:44
Duplicate of https://github.com/godotengine/godot-proposals/issues/3714 and/or https://github.com/godotengine/godot-proposals/issues/2109.

PS: When you do not have an idea of *how* to implement a given proposal, you should use the [Discussions](https://github.com/godotengine/godot-proposals/discussions) platform instead. If you keep not following the template, you may be blocked from this repository.

**Closed by Calinou** 2022-02-26 22:44 UTC
