### ISSUE TITLE
Sprite editor

### ISSUE THREAD

**Issue by Happytiger-exe** [godotengine/godot-proposals#7719] opened 2023-09-17 23:04 UTC
### Describe the project you are working on

I am getting used to Godot by making a Geometry Dash clone.

### Describe the problem or limitation you are having in your project

I wanted to use a sprite sheet for the character sprite, platforms and other objects. But after designing the objects and icons, i imported them into godot just to discover the fact that i cant effectevely slice the sprite sheet into separate sprites. I know i can do that when animating a character with the horizontal frames, but i want simple sliced sprites off a spritesheet. No addon helped me yet.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Every respectable game engine has some sort of sprite editor capable of slicing a sprite sheet. For example, unity has the sprite editor.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

select sprite sheet -> inspector -> sprite edit button. new window pops. select the sprite type from single (default) to multiple, then automatic slice button apears. then press button. sprites are sliced automatically, using their size as reference. you should be able to edit sprite sizes yourself as well.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If i would have been smart enough, i would have coded an addon myself, but i am not. Also, everyone will use it, i guarantee you. there's no way all gamedevs, be them indie or professional, prefer using separate png files for their 2D sprites

### Is there a reason why this should be core and not an add-on in the asset library?

Unity has the sprite editor sort of like an add-on. But as i was saying, making it core is no mistake, since its a critical feature for the sprite sheet workflow technique.

**Comment by Calinou** [comment] 2023-09-17 23:08
This was proposed in the past and was rejected: https://github.com/godotengine/godot-proposals/issues/3728

**Comment by JoNax97** [comment] 2023-09-18 01:36
I don't think it's the same thing. This proposal is not asking for a full blown image editor, just a way to define and edit regions inside an externally authored image, that can then be used as if they were separate textures/sprites inside the engine

**Comment by timothyqiu** [comment] 2023-09-18 04:59
Besides using AnimatedSprites, plain Sprite nodes also supports regions: Enable Region > Enabled, then you'll see the Edit Region button. You can also combine texture region with the regular hframes / vframes approach.

**Comment by natiT** [comment] 2023-09-18 09:54
you dont need to animate the spritesheet. You can also use H and V Frames in a simple Spride2D.
Also it sounds a little that you want to look up to the Tilemap/Tileset Editor because there you can select single tiles and draw them.  

Maybe you can be more detailed what exactly you wish to achieve with this.

**Comment by kleonc** [comment] 2023-09-18 20:04
Note there is auto slicing but I think the issue is it doesn't allow e.g. bulk-saving all the found slices as separate AtlasTextures (which then you could drag-drop for using when needed). 

You can e.g.:
1. Set the Sprite2D's `texture` to a spritesheet.
2. Enable region and edit it.
3. Select snape mode to "Auto Slice and pick any found slice by clicking it, the Sprite2D's region will update accordingly.

| 1 | 2 | 3 |
|--------|--------|--------|
|![Godot_v4 1 1-stable_win64_yPuqQyQuUV](https://github.com/godotengine/godot-proposals/assets/9283098/def376d9-e183-4358-bb5c-8538f201ec41)|![kTQ97f1l7l](https://github.com/godotengine/godot-proposals/assets/9283098/c5d4b63b-f509-4174-8595-458ddaba85b0)|![Godot_v4 1 1-stable_win64_tDtlvI9TMM](https://github.com/godotengine/godot-proposals/assets/9283098/fecdb3ab-13bd-4cbe-91db-c1e14b5a923d)|

Note that the region editor itself doesn't allow modifying the (possibly incorrectly) identified slices, you'd need to modify the region manually in such cases.

| 1 | 2 | 3 |
|--------|--------|--------|
|![Godot_v4 1 1-stable_win64_Qs4VS7qMon](https://github.com/godotengine/godot-proposals/assets/9283098/1e80add5-9e30-4961-b7fc-6249deaaee7e)|![Godot_v4 1 1-stable_win64_tv3f0jP10x](https://github.com/godotengine/godot-proposals/assets/9283098/3b133e2b-c722-4aaf-bf7b-34600e52f47e)|![bew9HlES0A](https://github.com/godotengine/godot-proposals/assets/9283098/b1f453bc-0c3f-40dc-87b4-e12e9e83f651)|

---

This region editor is available in other places too, so you can instead e.g.:
1. Create an AtlasTexture resource.
2. Set its `atlas` to a spritesheet and select its region with the region editor (just like for a Sprite2D).
3. Set such **saved** AtlasTexture as Sprite2D's `texture` (with Sprite2D's region disabled as the region is already defined in the texture).

| 1a | 1b | 2 | 3a | 3b |
|-|-|-|-|-|
|![Godot_v4 1 1-stable_win64_6Tw6cNn4pm](https://github.com/godotengine/godot-proposals/assets/9283098/36a9e242-ce02-466a-8137-75340f5965d0)|![Godot_v4 1 1-stable_win64_RB9w4VqxOg](https://github.com/godotengine/godot-proposals/assets/9283098/ff8e9709-dd46-423d-af73-5e2e20a95da9)|![Godot_v4 1 1-stable_win64_MPlv4hXNoH](https://github.com/godotengine/godot-proposals/assets/9283098/a13315ee-4068-4898-b88d-4230c82933b2)|![Godot_v4 1 1-stable_win64_x7YZbw75aD](https://github.com/godotengine/godot-proposals/assets/9283098/f38320ef-9ccf-4c07-af90-51f4bec21fc3)|![Godot_v4 1 1-stable_win64_Qbu2ZYQTZn](https://github.com/godotengine/godot-proposals/assets/9283098/f241af2e-677f-402a-8fac-cb390b2ff727)|

But as mentioned, I don't think currently there's a way to e.g. save all such found auto slices to separate AtlasTexture files at one go. As of now it seems one would need to repeat the region selecting via the region editor manually for each slice.

So seems like the feature is kinda in there but not in a fully useful manner. :thinking:

**Comment by Calinou** [comment] 2024-08-11 15:56
Closing in favor of https://github.com/godotengine/godot-proposals/issues/10415, which is more detailed.

**Closed by Calinou** 2024-08-11 15:56 UTC
Labels: topic:editor, topic:2d
