### ISSUE TITLE
Notes & Todos

### ISSUE THREAD

**Issue by Ashenguard** [godotengine/godot-proposals#4262] opened 2022-03-23 11:52 UTC
### Describe the project you are working on

Any project

### Describe the problem or limitation you are having in your project

Having to make note files, comments and etc... all over the project

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Having an editor-only note file that you can access with a shortcut allows you to write temporary ideas, todos, important guidelines, and ...

It can also have a reminder that you have some todos before you export your game.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It's nothing fancy... Just a hidden text file/tab within the project that you can access from anywhere like the scripts, 2d, and 3d tab

Maybe it can have a Todo format that will remind them to you before you export your project...

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can add note files yourself and probably a plugin to check for todos, But having a simple QOL feature will speed development up

### Is there a reason why this should be core and not an add-on in the asset library?

Take this scenario, You want to interactively update your GridMap in code and you need to memorize all possible orientations or write them down somewhere and have to look for them every time among lots of other unrelated notes in your phone, or your project files or ...! but having a simple tab that you write all of the project-related notes and todos and just check them with one click will help a lot

**Comment by KoBeWi** [comment] 2022-03-23 11:57
This is doable as an addon. In fact, a few such addons already exist (just search TODO in AssetLib, you will likely find something that will work for you).

**Comment by Calinou** [comment] 2022-03-23 14:16
Duplicate of https://github.com/godotengine/godot-proposals/issues/1409. See also https://github.com/godotengine/godot-proposals/issues/602
.

**Closed by Calinou** 2022-03-23 14:16 UTC
