### ISSUE TITLE
Add a way to copy/paste arrays in the inspector

### ISSUE THREAD

**Issue by Coder2195Text** [godotengine/godot-proposals#5270] opened 2022-08-26 21:11 UTC
### Describe the project you are working on

Im making a space game in which there are asteroids and UFO's blah blah blah

### Describe the problem or limitation you are having in your project

My game has to generate asteroids dynamically, therefore Collision Polygons dynamically as well.
But in order to save the PoolVector2Array, I have to make the shape, save it inside some sprite, go inside the scene file and then copy it.
This is very annoying and I want to be able to right click and copy

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add feature to right click on PoolVectorArray, and copy and paste (this should be extended to all Pool<type>Arrays in general

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user right clicks on a Pool<type>Array, a option to copy it will appear, ideally with different coding languages as well

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around by saving the CollisionShape, but accessing the tscn and converting tscn array to i.e c# array isnt convient.

### Is there a reason why this should be core and not an add-on in the asset library?

There isn't even an option to save the pool<type>array somehow, ie copying and/or saving, so adding it will improve the experience

**Comment by YuriSizov** [comment] 2022-08-29 11:37
Duplicate of https://github.com/godotengine/godot-proposals/issues/2951.

**Closed by YuriSizov** 2022-08-29 11:37 UTC
Labels: topic:editor
