### ISSUE TITLE
SVG Idea i just had

### ISSUE THREAD

**Issue by DNDEBUG** [godotengine/godot-proposals#4333] opened 2022-04-02 20:40 UTC
### Describe the project you are working on

Nothing

### Describe the problem or limitation you are having in your project

The Way Godot works with SVG Images

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

load SVG images just as they are and be able to manipulate layers independently on the screen
also this would be really cool for animated icons and HUD and custom menus
![untitled](https://user-images.githubusercontent.com/98880063/161400430-e026b82e-28c6-409c-add1-adc6262e5680.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Load icons.svg
load layer 1 on x=100, y=250
load layer 2 on x=100, y=300
load layer 3 on x=100, y=350 & rotate layer 3 in 90 degrees every 3 seconds
load layer 4 on x=100, y=400 & scale layer 4 in the y axis by 80 pixels if player click on it

also godot could have and option to load svg images from outside the res
so the programmer could easily implement a modding option like
load file from "/mods/icons/icons.svg"

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I believe it can be used a lot for icons and HUD stuff 

### Is there a reason why this should be core and not an add-on in the asset library?

Because the way Godot works with svg images now is kinda dumb ngl

**Comment by Calinou** [comment] 2022-04-02 23:57
Duplicate of https://github.com/godotengine/godot-proposals/issues/2924.

**Closed by Calinou** 2022-04-02 23:57 UTC
