### ISSUE TITLE
Collapse identical messages together in the Output panel

### ISSUE THREAD

**Issue by Pato-desu** [godotengine/godot-proposals#1611] opened 2020-10-05 00:24 UTC
**Describe the project you are working on:**
A game

**Describe the problem or limitation you are having in your project:**
Trying to debug something some messages accumulate on the output and they don't let me see the important one.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Collapse button for the output that activated show each different message and the amount of times printed. That way the output don't keep scrolling and you can see the messages clearly and at what rate they increment. 
(maybe could it work for the debugger too)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Unity has it.
https://youtu.be/vy7WXLArj4U?t=74

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Is cool and simple.

**Comment by Zireael07** [comment] 2020-10-05 06:46
It's been already reported and I believe a PR has been made to fix it. It might be only merged to master, though.

**Comment by Calinou** [comment] 2020-10-05 09:53
Duplicate of https://github.com/godotengine/godot-proposals/issues/898.

**Closed by Calinou** 2020-10-05 09:53 UTC
Labels: topic:editor
