### ISSUE TITLE
Drag and drop a node from the Scene nodes panel, into a the Inspector, to get a NodePath

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#3378] opened 2021-10-02 14:10 UTC
### Describe the project you are working on

Any game type.

### Describe the problem or limitation you are having in your project

Nodes should be draggable from Scene tab into export references.

This is the first result that appears on Google for this: https://github.com/godotengine/godot/issues/2505

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It's inconvenient to have to click the export box, find the node in the new scene browser and select it there, rather than just dragging from the Scene tab.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Disable inspector tab changing when dragging to only change on release click.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's an editor issue.

### Is there a reason why this should be core and not an add-on in the asset library?

It's an editor issue.

**Comment by LightningAA** [comment] 2021-10-02 15:46
See also https://github.com/godotengine/godot-proposals/issues/1048

**Comment by KoBeWi** [comment] 2021-10-02 23:28
See also #1042, because this is duplicate of that proposal. Closing.

**Closed by KoBeWi** 2021-10-02 23:28 UTC
Labels: topic:editor
