### ISSUE TITLE
Importing assets at runtime.

### ISSUE THREAD

**Issue by amoriqbal** [godotengine/godot-proposals#1658] opened 2020-10-13 17:28 UTC
**Describe the project you are working on:**
I am building a simple UI, that runs a script using `OS.execute()`. This script is supposed to generate an image file. The UI (to be implemented in Godot), should run the script, wait for the image to be generated, and then display the generated image as a texture in a `NinePatchRect` node.

**Describe the problem or limitation you are having in your project:**
An application built in Godot, requires all assets to be imported, before the application starts execution. Here, I need to import an image file, that was generated after the program started execution. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
We need two functions in GdScript:
1. import(file_path)
This function should import the file in the `file_path` specified.

2. signal_on_change(file_path)
After this this function is called, if the file at `file_path` is changed, a signal `file_changed` should be fired like `emit_signal("file_changed",file_path)`.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Not sure as to how to implement this. But I love Godot, and am ready to invest the required time, if the proposal is accepted.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
NO!! This feature cannot be worked around with a few lines of code. Once the project has been exported and has started running, it closes it eyes to any new file that is placed in the computer, by an external software. I have tried many solutions, suggested in StackOverflow and the Godot forums. But they have not worked. I have not found ANY workaround.

**Is there a reason why this should be core and not an add-on in the asset library?:**
The inability to import assets during runtime, seems fundamental to Godot and to how the projects are exported. This cannot be fixed with an add-on. `load()` and `preload()` are built-in functions. Going by this logic, `import()` should be a built-in too.

**Comment by Xrayez** [comment] 2020-10-13 17:44
> 1. import(file_path)
>    This function should import the file in the `file_path` specified.

This is suggested in my previous proposal in #1632. 🙂

I guess this proposal conveys the problem with editor not detecting changes at run-time while saving/modifying stuff from within editor plugins, and I recall @Zylann also raised this question before and was curious whether it's possible to do this at run-time (similar use case with generating image files from within the editor).

**Comment by Calinou** [comment] 2020-10-13 17:54
Duplicate of #1632.

**Closed by Calinou** 2020-10-13 17:54 UTC

**Comment by amoriqbal** [comment] 2020-10-13 18:52
Okay... Sorry for the trouble and Thanks!! for the time. :)
