### ISSUE TITLE
Interactive debug console for easy debugging

### ISSUE THREAD

**Issue by Yalchin403** [godotengine/godot-proposals#5280] opened 2022-08-28 10:39 UTC
### Describe the project you are working on

I'm mostly coding different algorithms for FPS games in our company. I usually need elaborate debugging rather than using simple print statements. Having an interactive debug console would help to get the only needed values instead of scrolling through the debug section like we have right now. I'm imagining something similar to debug console available inside VS code

### Describe the problem or limitation you are having in your project

I cannot quickly debug the problems, if I need to quickly take a look at the nested array, I need to use GUI to seek through

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding this feature would lead to quickly and efficiently debugging the problems. Just putting debug breakpoint and using interactive debug console taking a look at target values.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For me, it would be perfect if we can have an interactive debug console. Lets say having the debug section (what we have currently in Godot) and below that there is an interactive debug console waiting for our input. Lets say in our code section we put breakpoint for line 55, once we run it, execution stops at the target line. Lets imagine in line 10 there is a variable `foo = "bar"`, assuming the code doesn't contain any error, and works properly, if we input `foo` in the debug console, we should get "bar" as our return value in the debug console.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think as an alternative for this feature, what we can do is putting some code snippet which enables us to ask for input on the fly. But, I'm inclined to believe that having a nicely builtin debug console would definitely be perfect for all the developers.

### Is there a reason why this should be core and not an add-on in the asset library?

I think being able to debug easily by just the editor itself should be accessible without any add-on. That's how I saw and used most of the editors and IDEs out there till now.

**Comment by Zireael07** [comment] 2022-08-28 13:21
Please add to the title that it's for editor debugger - I was thinking you want this for the game itself, which a couple of assets already do.

**Comment by Calinou** [comment] 2022-08-28 14:52
Duplicate of https://github.com/godotengine/godot-proposals/issues/4473.

**Closed by Calinou** 2022-08-28 14:52 UTC
