### ISSUE TITLE
disable_2d compile argument

### ISSUE THREAD

**Issue by 3top1a** [godotengine/godot-proposals#1653] opened 2020-10-12 20:24 UTC
I'm currently working on a fork of Godot with n-body physics.
My proposal is to have `disable_2d` just like `disable_3d`.
This could cut the compile-time and remove unnecessary bloat from my fork.

in `/scene/3d/SCsub` there is `if env["disable_3d"]:` which disables most 3d nodes.
I would like to see the same in `/scene/2d/SCsub`.

This can't be worked around with a few lines of script or a package as this is a source code proposal.

**Comment by Calinou** [comment] 2020-10-12 20:26
Duplicate of https://github.com/godotengine/godot-proposals/issues/190.

**Comment by Xrayez** [comment] 2021-03-17 20:16
This is not a duplicate of #190.

See recent pull request which aims to resolve this proposal: godotengine/godot#47054.

**Comment by aaronfranke** [comment] 2021-05-24 05:47
Not a duplicate of #190. This is a subset of #190, but not a duplicate. As such, this proposal needs to be solved first (I have a PR open waiting review: https://github.com/godotengine/godot/pull/47054). Re-opening and un-archiving.

**Comment by aaronfranke** [comment] 2021-05-24 05:55
Er, actually, this proposal doesn't fill out the template properly, closing.

**Closed by aaronfranke** 2021-05-24 05:55 UTC
Labels: topic:2d, topic:buildsystem
