### ISSUE TITLE
Add an option to open .blend files in blender

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#5684] opened 2022-10-31 12:38 UTC
### Describe the project you are working on

prototyping with 4.0

### Describe the problem or limitation you are having in your project

Since godot can now directly use blend files I use them that way.
To modify a blend file one currently has to use the OS file explorer or the blender one which can be tedious depending on the number of files, the complexity of the folder hierarchy, etc..

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In a good amount of cases the blend file you want to work on is easy to locate in the editor's filesystem (I have them next to the scenes that uses them).
Adding an option to the RMB context menu to open blend files using the specified blender installation would smooth a bit iteration.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

when right-clicking a blend file in the godot editor's filesystem, the popup menu would feature a new option "open in blender" which would open said file in blender (using the installation specified in the blend import settings).

The menu already contains many options, but this would only add an option for a specific file type.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It would be used often by solo devs.

### Is there a reason why this should be core and not an add-on in the asset library?

It can probably be an addon although I don't know how yet.
It seems to me like a small enough and general enough feature to include in core.

**Comment by Calinou** [comment] 2022-10-31 15:00
Duplicate of https://github.com/godotengine/godot-proposals/issues/328.

**Closed by Calinou** 2022-10-31 15:00 UTC
