### ISSUE TITLE
Typed dictionaries

### ISSUE THREAD

**Issue by Wolfyxon** [godotengine/godot-proposals#6786] opened 2023-05-01 17:30 UTC
### Describe the project you are working on

I'm working on a universal 2D topdown unit AI class with many settings for my game.

### Describe the problem or limitation you are having in your project

I need to export a dictionary variable that will only accept `Node2D` as key and `Node2D` as value. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I'd like to see an option to define the type of key and value for dictionaries. A dictionary with defined key and value type would not accept any other types.
Similar to https://github.com/godotengine/godot/pull/46830

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
var dict: Dictionary[String,int]

dict["some string"] = 1 #correct, key is a String and value is an int

dict["some other string"] = "hi" #error, value is not an int
dict[1] = "Yet another string" #error, key is not a String
dict[load("res://scene.tscn")] = Vector2(10,5) #error, both key and value are wrong
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not really "few lines". That would require constant checking of the dictionary or a separate function that would check the entry before adding it to the dictionary.

### Is there a reason why this should be core and not an add-on in the asset library?

Most advanced programming languages have such an option for dictionaries like Java where you type:
```java
Map<String,Integer> map = new HasMap<>();
```
It would be very useful in vanilla Godot.

**Comment by dalexeev** [comment] 2023-05-01 17:56
* Related: #56.

**Comment by KoBeWi** [comment] 2023-05-01 20:03
Duplicate of #56

**Closed by KoBeWi** 2023-05-01 20:03 UTC

**Comment by dalexeev** [comment] 2023-05-02 02:59
Formally, these are different proposals. #56 deals with the types of individual elements, and this one deals with the types of keys and values.

**Comment by KoBeWi** [comment] 2023-05-02 11:00
Both are about typed Dictionaries. The other one is quite old, but it's discussed in length and covers most of the topic (including syntax: https://github.com/godotengine/godot-proposals/issues/56#issuecomment-1286828010). If this proposal adds anything new, it should be commented in the old one.
