### ISSUE TITLE
Live-preview launched instances from the editor window

### ISSUE THREAD

**Issue by Ev1lbl0w** [godotengine/godot-proposals#3269] opened 2021-09-09 11:44 UTC
### Describe the project you are working on

3D games and prototypes on Godot *(proposal is useful for all types of games really)*

### Describe the problem or limitation you are having in your project

Sometimes it's hard to visualize what's happening in a launched game from the editor. Currently the only tools available for it are the "Remote" tab that displays the scene tree and lets me both view and edit all nodes properties. However, changes made are only visible from the launched instance; the editor provides no "visual feedback" as to what's happening inside the game.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This is very similar to a feature present on Unity:
![image](https://user-images.githubusercontent.com/6501975/132672906-e9d66b5b-80b3-4db3-b2d1-7960404d03f6.png)
The left panel shows the "Game" view, *aka* the content displayed on a game instance; the right panel is the "Scene" view, *aka* the editor view of the game scene. Both of these are in-sync to one another.

The useful aspect of this is, in the editor panel, the developer can have a "meta" perspective of the running game, as well as being able to move the editor camera to better watch objects from an angle not possible from the game instance, which gives a better insight to how the game is running.

Here's a video of that feature in action in Unity:

https://user-images.githubusercontent.com/6501975/132673942-599f0ac4-075c-442d-b458-25788b545d09.mp4

Godot already has the "Remote" tab, allowing to inspect the live scene tree:
![image](https://user-images.githubusercontent.com/6501975/132674792-acbd0681-fd48-46f1-ad95-64e14b4f6dfe.png)
Furthermore, node properties are already updated accordingly:

https://user-images.githubusercontent.com/6501975/132676142-50c174e0-83c2-4a63-b33a-3b2e24ea6ec5.mp4

However, the main editor area isn't doing anything. To modify something on remote, one must select the node in the scene tree, and manually change values in the inspector *(and then focus on the game window to see those changes)*. The main editor is only useful when changing something in a local scene that may be synced with the remote instance, but even then only if "Synchronize Scene/Script Changes" is enabled.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

My proposal is to implement this feature as to complement already existing systems, and improve the development workflow. It's also important for it to be user-friendly, and without disrupting current workflows; and for that I propose this behavior:

- Clicking on the "Remote" tab will change the main editor view to a live preview of the game instance.
    - The editor's full abilities remain; moving the editor camera around, selecting objects, and modifying it's properties from inspector.
    - The editor can be in-sync just by reacting to property changes; no need to be running scripts on editor side.
- While live-previewing, you can also switch back and forth between 2D/3D to inspect both states; in a 2D game this is not very useful, but in a 3D game, this can be used to inspect UI elements as well.
![image](https://user-images.githubusercontent.com/6501975/132679854-248c8817-16ae-4354-a794-b1654111e2ee.png)

- To go back to editing a local scene, either click on the "Local" tab or open a scene, either from current tabs or from somewhere else:
![image](https://user-images.githubusercontent.com/6501975/132678196-1cb950b1-d887-4ff5-a9e7-7d51a3852fe3.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's likely not possible to implement such a feature without modifying engine code.

### Is there a reason why this should be core and not an add-on in the asset library?

This improves core editor functionality.

**Comment by Zireael07** [comment] 2021-09-09 12:10
99% certain this was already proposed but I can't find the other issue now.

**Comment by pycbouh** [comment] 2021-09-09 12:31
Duplicate of https://github.com/godotengine/godot-proposals/issues/1864

**Closed by pycbouh** 2021-09-09 12:31 UTC
