### ISSUE TITLE
Docking tabs anywhere

### ISSUE THREAD

**Issue by Squeeshy123** [godotengine/godot-proposals#2690] opened 2021-05-06 00:56 UTC
### Describe the project you are working on
I'm working on an open world RPG

### Describe the problem or limitation you are having in your project
Managing large files is really annoying when you have the file system only on the sides of the screen. Also this can limit the capacity of plugins because having you only be able to make plugins vertically can be limiting.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Making the tabs also dockable in the output/debugger/audio area (So you can do stuff like putting the output tab in the top right corner or putting the file system in the bottom part of the screen)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
![I can put it ANYWHERE](https://user-images.githubusercontent.com/62818641/117227012-e79dec00-ade3-11eb-9afe-ad1940b64206.PNG)

Like how unreal does it, where I can put the content browser in the top right and the actor palate at the bottom and the output log where the details panel is. Just docking any window anywhere.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It will be inside the engine itself.

### Is there a reason why this should be core and not an add-on in the asset library?
The plugin and add on features do not let you change the behavior of the engine itself.

**Comment by Calinou** [comment] 2021-05-06 01:08
Duplicate of https://github.com/godotengine/godot-proposals/issues/1508.

**Closed by Calinou** 2021-05-06 01:08 UTC
