### ISSUE TITLE
Consider adding a global wind or velocity system . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3309] opened 2021-09-17 07:04 UTC
### Describe the project you are working on

A barbarian game, 2.5D . . .

### Describe the problem or limitation you are having in your project

I have been thinking about way, to add simple or, efficient wind support, and saw in a demo, sort-of what I had in mind, here . . .

![Animation (20)](https://user-images.githubusercontent.com/83387915/133738463-f71d9a91-6189-42d8-8cdb-b690c8448d22.gif)

![Animation (21)](https://user-images.githubusercontent.com/83387915/133738491-4351c745-6e1f-4f79-b583-2f61f91d29fe.gif)

Anyway, was thinking of something like that, one could use an animated texture or, shader to make the wind system bit chaotic . . .

Well, it makes some neat effects, and looks to be POSSIBLE tech, was something like that I had in mind, but with some support for wind or, velocity . . .

Demo - link >> https://www.youtube.com/watch?v=tYibUTZIdig

Looks like it can run on current stuff, having such a system, would allow for some cool effects, pre-programmed or, procedural, that was idea, thanks . . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, something like above, maybe one could select a volume, and pre-bake an animation, or make custom volume . . Or, maybe do other stuff, so program is simple, but if one needs to bake a complex animation, of wind, or fog, one can just store it, as a baked resource, and run it live, perhaps streaming from an SSD or, so . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, sort-of like above, some global wind or, velocity area, where things deform, or 'shear', as the grid moves or, so . . . That was bas. my idea, had it some time ago, might make some nice effect, if nothing else, one could bake complex stuff, and move from say SSD, to memory, in well an optimized way . . . Might be possible to make crazy stuff, IF it was optimized, that was my idea . . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't code this advanced stuff . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Not sure, it might be best as a plug-in, but the core code would be rather small, it'd be the baked stuff that'd take space, so one would only use it when needed or, so . . Thus, keeping project sizes small, unless needed . . .

ps. Might be possible to stuff like waves, earth - quakes, so on, thanks . . . :OO . . .

**Comment by charlesmlamb** [comment] 2021-09-17 07:07
My plan was to use this, for disaster effects and, weather, thinking it might be possible to make something, like this . . .

![2021-09-17 0906](https://user-images.githubusercontent.com/83387915/133739629-393caced-1f42-4c22-8a05-4aded998585b.jpg)

Or, sort-of big explosions or, such . . . .

**Comment by Calinou** [comment] 2021-09-17 07:29
Duplicate of https://github.com/godotengine/godot-proposals/issues/2591.

**Closed by Calinou** 2021-09-17 07:29 UTC
