### ISSUE TITLE
Add dotnet 5 support.

### ISSUE THREAD

**Issue by Kemsekov** [godotengine/godot-proposals#3018] opened 2021-07-20 13:40 UTC
### Describe the project you are working on

I wanna to start new godot project with supported dotnet 5 

### Describe the problem or limitation you are having in your project

Not supported dotnet 5

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

dotnet 5 is awesome. It unifi windows dotnet framework and dotnet core so it must be a logical try to port it into a engine now. According to 
https://github.com/godotengine/godot-proposals/issues/793#issuecomment-623226288
comment it must already in work, but I didn't see anything about dotnet 5 and godot in internet.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

User will choose type of project and there will be .NET 5 that will support its compilers and libraries and also writing code in Visual Studio.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, I am sure many users will be very happy if you implement it so it will be used very much and sadly for you this implementation of .NET 5 will not be few lines of code for you.

### Is there a reason why this should be core and not an add-on in the asset library?

I thing t would be impossible to implement this in assets library because of it’s size.

**Comment by pycbouh** [comment] 2021-07-20 13:42
Duplicate of https://github.com/godotengine/godot-proposals/issues/2333.

**Closed by pycbouh** 2021-07-20 13:42 UTC
