### ISSUE TITLE
Add gradient support in Control node Custom styling

### ISSUE THREAD

**Issue by I7SOD** [godotengine/godot-proposals#1138] opened 2020-06-29 03:00 UTC
**Describe the project you are working on:**
Just Learning

**Describe the problem or limitation you are having in your project:**
I was checking out a project on Control Node styling with buttons and I saw that it didn't support color gradients while another node Line2D does

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Make Gradients available for buttons and other styling options

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
This is a just a proposal that allows gradiented buttons like in the image below since Godot already has a gradient resource

![gradient2](https://user-images.githubusercontent.com/51547693/85968335-c34fd280-b9bc-11ea-9407-6547ebb594d1.jpg)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think so at least from my little knowledge I don't think shaders can be written for control nodes

**Is there a reason why this should be core and not an add-on in the asset library?:**
Custom styling is a core part of the engine ( I guess :D )

**Comment by Calinou** [comment] 2020-06-29 07:51
Duplicate of https://github.com/godotengine/godot-proposals/issues/611 (and https://github.com/godotengine/godot-proposals/issues/604 to an extent).

**Closed by Calinou** 2020-06-29 07:51 UTC
Labels: topic:gui

**Comment by I7SOD** [comment] 2020-06-29 12:43
Oh the proposal is already on board
