### ISSUE TITLE
GDScript 2.0 debug changed name hints

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#5902] opened 2022-12-06 07:51 UTC
### Describe the project you are working on

An FPS.

### Describe the problem or limitation you are having in your project

There’s been so many changes to GDScript in Godot 4.0, it might be helpful if the debugger knew the difference between old syntax references and new replacement names (similar to how it suggests if you’ve referenced a built-in function without the parameters parentheses).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If the user typed `set_as_toplevel()`, instead of an error that the node doesn’t contain this function, perhaps suggest `set_as_top_level` instead. Same goes for types, if using `extends KinemeticBody`, maybe suggest `extends CharacterBody` or `extends AnimatableBody`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would be debug messages, possibly optional toggleable in editor settings (suggest legacy names for nodes and functions).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It would probably be core, unless GDExtension can hook debug messages.

### Is there a reason why this should be core and not an add-on in the asset library?

Not endless GDExtensions can hook debug messages.

**Comment by Zireael07** [comment] 2022-12-06 07:54
99% certain we already have a proposal for it, but my search-fu is failing me

**Comment by Calinou** [comment] 2022-12-06 15:06
Duplicate of https://github.com/godotengine/godot-proposals/issues/3902.

**Closed by Calinou** 2022-12-06 15:06 UTC
