### ISSUE TITLE
Tooltip when mouse cursor over a function

### ISSUE THREAD

**Issue by Heliox01** [godotengine/godot-proposals#6124] opened 2023-01-19 14:45 UTC
### Describe the project you are working on

nothing

### Describe the problem or limitation you are having in your project

nothing

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

instead of opening the documentation you can over fastly the function and see it's description

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

nothing

### If this enhancement will not be used often, can it be worked around with a few lines of script?

nothing

### Is there a reason why this should be core and not an add-on in the asset library?

it's useful

**Comment by Calinou** [comment] 2023-01-19 17:22
Duplicate of https://github.com/godotengine/godot-proposals/issues/1393.

PS: In the future, please use the [Discussions tab of this repository](https://github.com/godotengine/godot-proposals/discussions) if you don't have a concrete technical implementation in mind.

**Closed by Calinou** 2023-01-19 17:22 UTC
