### ISSUE TITLE
Add a way to get whether AnimationTree StateMachine is currently in a Transition

### ISSUE THREAD

**Issue by elXill** [godotengine/godot-proposals#7977] opened 2023-10-03 19:49 UTC
### Describe the project you are working on

3d character controller experiment, checking how animations act, transitions work, etc. in Godot.

### Describe the problem or limitation you are having in your project

There is no way to reliably get if AnimationTree is in transition, or deduct it in any other way. I can't even be sure if xfade and transition are same things.. Does transition instantly happens? Does xfade a synonim for transition? Is transition just a path and xfade is mainly cosmetics? I'm not sure but I sure need some tools to understand..

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a func that turns true while there is an active transition.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just a bool if there is transition going or not; `bool animation_tree.is_transition()` .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I tried calculating it from start and end signals but it only works if there are no looped animations and all animation SwitchModes are At End. So no, not a straight forward way.

### Is there a reason why this should be core and not an add-on in the asset library?

I think this is an essensial feature for working with animation state machine, animation debugging or understanding how engine works.

**Comment by Calinou** [comment] 2023-10-03 20:54
cc @TokageItLab

**Comment by TokageItLab** [comment] 2023-10-03 23:36
Dupe of https://github.com/godotengine/godot-proposals/issues/7885

**Closed by TokageItLab** 2023-10-03 23:36 UTC
Labels: topic:animation
