### ISSUE TITLE
Need a way to create a mesh from a GLSL buffer object

### ISSUE THREAD

**Issue by blackears** [godotengine/godot-proposals#8672] opened 2023-12-17 00:31 UTC
### Describe the project you are working on

A marching cubes implementation that displays MRI volumetric data.

### Describe the problem or limitation you are having in your project

At the moment the only way to create a mesh is by creating an ArrayMesh object and initializing it by passing in Packed*Arrays of various sorts.  The problem with this is that it is very slow - especially since my vertex data is already in a buffer and could in theory be used directly to render a mesh.  In my tests, I'm spending 25% percent of my time running my shader to generate point data and 75% of my time unpacking the point data I generated into a PackedVector3DArray so I can feed it into an ArrayMesh.

```
func generate_mesh():
	var start_time:int = Time.get_ticks_msec()

        #Run generation shader
        ...

	var shader_done_time:int = Time.get_ticks_msec()

	#Get results
	var param_rw_byte_data:PackedByteArray = rd.buffer_get_data(param_buffer_rw, 0)
	var param_rw_int_data:PackedInt32Array = param_rw_byte_data.to_int32_array()
	var num_floats_written:int = param_rw_int_data[0]
	
	var param_w_point_byte_data:PackedByteArray = rd.buffer_get_data(param_buffer_w_point, 0)
	var param_w_point_float_data:PackedFloat32Array = param_w_point_byte_data.to_float32_array()
	
	var param_w_normal_byte_data:PackedByteArray = rd.buffer_get_data(param_buffer_w_normal, 0)
	var param_w_normal_float_data:PackedFloat32Array = param_w_normal_byte_data.to_float32_array()
	
	#Convert data to format Godot can use
	var points:PackedVector3Array
	var normals:PackedVector3Array
	for i in num_floats_written:
		points.append(Vector3(param_w_point_float_data[i * 3], \
			param_w_point_float_data[i * 3 + 1], param_w_point_float_data[i * 3 + 2]))
		normals.append(Vector3(param_w_normal_float_data[i * 3], \
			param_w_normal_float_data[i * 3 + 1], param_w_normal_float_data[i * 3 + 2]))

	var limit_start = 3 * 4090
	var limit = 3 * 4096
	var mesh = create_mesh(points.slice(0, num_floats_written / 3), normals.slice(0, num_floats_written / 3))
	
	var build_mesh_done_time:int = Time.get_ticks_msec()
	
	print("time running shader msec:", (shader_done_time - start_time))
	print("time building mesh msec:", (build_mesh_done_time - shader_done_time))
	
	return mesh

func create_mesh(points:PackedVector3Array, normals:PackedVector3Array)->ArrayMesh:
	if false:
		var colors:PackedColorArray
		for n in normals:
			n = (n + Vector3.ONE) / 2
			colors.append(Color(n.x, n.y, n.z, 1))
	
	# Initialize the ArrayMesh.
	var arr_mesh:ArrayMesh = ArrayMesh.new()
	var arrays = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = points
	arrays[Mesh.ARRAY_NORMAL] = normals

	# Create the Mesh.
	arr_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	return arr_mesh
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Creating some way to allow meshes to be drawn directly from GLSL buffers would make generating meshes like this enormously faster.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't know if the ArrayMesh could be modified to allow for this.  If not, add methods to RenderingDevice to allow for drawing meshes or come up with a new mesh object that can work with buffer objects.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, this requires integration with Vulkan.

### Is there a reason why this should be core and not an add-on in the asset library?

Requires integration into the rendering pipeline.

**Comment by clayjohn** [comment] 2023-12-17 00:58
Duplicate of https://github.com/godotengine/godot-proposals/issues/7209

**Closed by clayjohn** 2023-12-17 00:58 UTC
