### ISSUE TITLE
Improve ' cloth ' and hair simulation . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#2833] opened 2021-06-06 10:39 UTC
### Describe the project you are working on
A Tomb Raider game . .

### Describe the problem or limitation you are having in your project
I'm working on a game, and I need really good cloth simulation . . Here . . .
<img width="304" alt="2021-06-06 1216" src="https://user-images.githubusercontent.com/83387915/120920849-2b289600-c6c1-11eb-8bf1-fc9c52ef2716.png">

I need a cape, a thin one, slender . . That flows down back of a character, and lands, on the floor, or so . . .

![2021-06-06 1219](https://user-images.githubusercontent.com/83387915/120920903-7478e580-c6c1-11eb-81be-5a942000866c.jpg)

I realize it may be very complicated but, I've seen no ' news ' about, improved cloth simulation, in Godot 4, or Godot 4.1 . . I wanted to ask for better cloth sim, esp. in relation to human characters . . It might be ' technically ' impossible, but was wondering if there had been some recent advancements in the area, real-time stuff, and, not sure, total noob . . it might be easy to add, or so, using recent 'algorithms', math . . I'm looking for a really advanced system, where one can assign different stuff, to points on ' softbody ', for instance, some points won't deform, but only sway, ie. will be static, other parts will be more dynamic . .

<img width="482" alt="2021-06-06 1228" src="https://user-images.githubusercontent.com/83387915/120921164-b191a780-c6c2-11eb-9e1a-5b21b1ecef48.png">
Notice, the different nodes have different color, maybe 2 to start with, 4 would be nice, 8 be ' amazing ' . . . .

Idea is, maybe one could make so, one could set ' different ' values, to different parts of the softbody, ie. simulation ' quality ' etc, so some part don't deform, ie. folds in the middle ( the green points . . ), but the one's at the bottom, are more accurately simulated, so one could have ' complex ' softbodies, and optimize the ' distriubtion ' of the simulation . . also, if there were some pre-set one's, like 'sway-nodeform', 'sway-gravity', 'sway-bend-stretch', not sure . . . I realize this may be dumb but, I need this for a game, wanted to ask, sometimes there's some new amazing tech, or 'math' in recent years, that make it possible . . . or, maybe one could have a list of possibilities, like, when one 'paints' the softbody nodes, like

sway On/off
bend On/off
stretch On/off

And, then one can paint different points, as one needs . . Ideally, one would be able to set a custom value, for some points, for stretch, so on, to get a custom simulation, was thinking it might be possibly to optimize it, or so, by having 4 custom pre-sets, that one could use for each softbody . . .

I'm not really sure what to say, guess I'm thinking 'next - gen' cloth sim, been looking for cloth tutorials and, there are very few good one's, seem Godot can do a 'hanging' tapestry, fairly basic, atm . . After some tests, it's 'really' poor, at least the collision shapes I used did a lot of clipping and, it looked really 'bad', so much I'd not use it, as it is, or so . .

It'd also require some 'advanced' KinematicBody collisionshapes, that would work well, for well, human anatomy . . :OO

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I have a project, where I need this stuff, can always just ' animate ' it in Blender, but it won't have physics, or so . . Wanted to ask, since there are some ' wizards ' here and, amazing tech people, that might know the ' tricks ', so on . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, like above, with an option to do much more ' custom ' softbodies, not sure, if possible . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't hard-code this, as solo - dev . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, was hoping it might be possible to make the softbody node more ' robust ' or, flexible, etc . . Thx . . . .

**Comment by zinnschlag** [comment] 2021-06-06 12:00
Duplicate of #2513 ?

**Comment by charlesmlamb** [comment] 2021-06-06 12:56
Ok, made a 'really' cool female Batman, or so . . has a 'small' cape, I'd like to animate really well :OO . . .

<img width="1109" alt="Concept 02" src="https://user-images.githubusercontent.com/83387915/120924932-71d4bb00-c6d6-11eb-86b1-962a00ceb7c7.png">

I'd like to be able to do something like Batman Arkham City cape . .
![2021-06-06 1450](https://user-images.githubusercontent.com/83387915/120924963-a0529600-c6d6-11eb-8d59-65ce5e4ad81f.jpg)

well, it was from 2011, Batman Arkham city, was hoping to get some-thing like . . Made a really cool ' character ', on my tablet, can make it into 3D, but REALLY like it, to have nice cloth sim, maybe like the suggestion above, #2513 <3

![2021-06-06 1454](https://user-images.githubusercontent.com/83387915/120925090-25d64600-c6d7-11eb-8b64-8d0ff527183b.jpg)

Idea is, there are ' folds ' at mid - height but, they aren't simulated, beyond gravity, but near the bottom, the folds are accurately simulated . . So, was thinking, if softbody one could select points and, give them different 'properties', ie. no_fold, fold_sim, etc . . .

might be horribly complicated, but there are some crazy talented people here, might be someone, who could code it, in a few days, etc . . Thx <3 . . .

**Comment by charlesmlamb** [comment] 2021-06-06 13:33
Ok, to keep it short, this is what I need, for the character <3

<img width="860" alt="2021-06-06 1532" src="https://user-images.githubusercontent.com/83387915/120926271-7d2ae500-c6dc-11eb-9216-5f5fe4e8a0bd.png">

I'm sort-of wondering, why softbody doesn't do this, already . . . would look super - nice, and help me ' realize ' my character, in BEST way . . .

**Comment by Calinou** [comment] 2021-06-06 14:03
Duplicate of https://github.com/godotengine/godot-proposals/issues/2513.

**Closed by Calinou** 2021-06-06 14:03 UTC
Labels: topic:3d, topic:physics
