### ISSUE TITLE
Allow to open and edit images in external app

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot-proposals#1131] opened 2020-06-28 12:17 UTC
**Describe the project you are working on:**
On very different projects in which I use some amount of images

**Describe the problem or limitation you are having in your project:**
Now opening images inside Godot causes that this images are opened in inspector dock.
This is a little frustrating because if we want to edit image or see it in full resolution, then every singe image must be opened from external software which take time.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Opening image in external image viewer(nomacs, gwenview) or image editor(gimp, krita) directly from Godot will allow users to spend smaller amount of time on searching and opening files in external programs(Nautilus, Windows Explorer, Nemo).

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

It should just add to menu when clicking at the image a new options:
- Open in image viewer
- Open in image editor

I think, that in options may be created a ordered list of most common image software(to view it and edit), which could be easily edited by user to open a given file in the program it has indicated.

![sfsfsfaf](https://user-images.githubusercontent.com/41945903/43886032-cf0e1914-9bba-11e8-868c-962b4ba096f1.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It should be very often used.
Scripts which modify editor, aren't so popular and this implementation will take more than a few lines of code.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It will help a lot some groups of people which edits a lot of images or want to look at picture with full resolution(which mostly isn't possible with inspector)

**Comment by Calinou** [comment] 2020-06-28 21:31
Duplicate of #328.

**Closed by Calinou** 2020-06-28 21:31 UTC
Labels: topic:editor
