### ISSUE TITLE
Implement Oblique near clipping plane for cameras

### ISSUE THREAD

**Issue by SIsilicon** [godotengine/godot-proposals#1863] opened 2020-11-20 00:30 UTC
**Describe the project you are working on:**
3D portals and reflections.

**Describe the problem or limitation you are having in your project:**
I've found the camera's `frustum` to be pretty useful since its release. It is shown to be able to render reflections without rendering the back (see Jfons' [mirror demo](https://github.com/JFonS/godot-mirror-example)). However that's where the problem rises. When using the frustum mode like this, it can lead to the projected texture to lose detail when viewed from a steep angle or close up. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The solution to this would be to be able to define an oblique near clipping plane for any camera; not just for `frustum` mode. Using this would allow culling away parts of a scene without worrying about viewports size limitations, and shearing.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
`Camera` would be given a new property called `oblique_near_plane`, defined in camera space. The property would be of type `Plane`. The plane _has to_ face away from the camera. After all, it's still the near plane. Every frustum calculation will be given a plane parameter and be modified with code similar to [this](http://www.terathon.com/code/oblique.html) (in the case orthographic projections, [this](https://aras-p.info/texts/obliqueortho.html) can be referenced as well). Optionally the plane can be considered not used by x, y, and z all being zero.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Absolutely not. This can only be implemented in core.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Refer to previous section.

**Comment by SIsilicon** [comment] 2020-11-20 00:38
This can be implemented in both 3.2 and 4.0.

**Comment by Calinou** [comment] 2020-11-20 11:58
Duplicate of https://github.com/godotengine/godot-proposals/issues/501.

**Closed by Calinou** 2020-11-20 11:58 UTC
Labels: archived, topic:rendering
