### ISSUE TITLE
"Save Project As" option in Project menu.

### ISSUE THREAD

**Issue by pajcek11** [godotengine/godot-proposals#1300] opened 2020-08-03 14:25 UTC
**Describe the project you are working on:**
I want to make a checkpoint and branch off my my project into new horizons. So if I get an oopsie woopsie, I can always go back.

**Describe the problem or limitation you are having in your project:**
It takes 20 seconds to make a copy of the project folder and import it into Godot, but that's 10 seconds too long

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
In the Project menu, add an option to duplicate/save-as a project. It would work as a "save As", and you would just change the name. By default, it would be set right next to the original folder.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Add option that pops up a save-as menu, whose default directory is the parent directory of the current project.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I think it might be used often. At least, more often than some other options there.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's ezpz to implement, and it's basic functionality.

**Comment by Calinou** [comment] 2020-08-03 14:57
Duplicate of https://github.com/godotengine/godot-proposals/issues/227.

**Closed by Calinou** 2020-08-03 14:57 UTC
