### ISSUE TITLE
Multiple inheritance (mixins) in gdscript

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#1093] opened 2020-06-20 11:44 UTC
**Describe the project you are working on:**
I am developing gdscript plugins that I am going to support for a long time.

I am convinced that code support requires code purity, as well as keeping the code base as small as possible (without enthusiasm of course), in particular adherence to the DRY principle.

**Describe the problem or limitation you are having in your project:**
Say, I want to have a class A that contains 2 independent code parts:
one part overrides the `add_child` method 
the other part overrides `_to_string` method.

```gdscript
class A:
    extends Node
    func add_child(node, unique):
        #do something

    func _to_string(s):
        #do something else

```
and I also notice that I could reuse these code parts separately for other classes.

but I can't do it easily in gdscript
Using composition also can't solve this problem.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Multiple inheritance, particularly python like mixins, could elegantly solve this problem

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I could have those code parts in 2 different classes (scripts).
and be able to "mixin" them with the main class.
```gdscript
class AddChild:
    extends Node
    func add_child(node, unique):
        #do something

class ToString:
    extends Object

    func _to_string(s):
        #do something else


class A:
    extends ToString, AddChild

#or

class A:
    extends ToString, AddChild, Node
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

no unfortunately.
This is not solved by composition or workaround as elegantly as with mixins.

**Is there a reason why this should be core and not an add-on in the asset library?:**
it should not be implemented as an addon.
Imo it's more logical to have this as a feature of the gdscript language.

**Comment by Calinou** [comment] 2020-06-20 13:05
Duplicate of #758.

**Closed by Calinou** 2020-06-20 13:05 UTC

**Comment by me2beats** [comment] 2020-06-20 15:53
Imo this is not a duplicate.

at least I don’t see how this could solve the problem above.

I quickly googled traits, and I got the impression that they are not able to do everything that python mixins can do

In this case, do I need to rename proposal to emphasize that I mean python-like mixins, not traits?

**Comment by Calinou** [comment] 2020-06-20 16:57
@me2beats Multiple inheritance will probably never be added to GDScript. A trait system is much more likely to be added in the future.

**Comment by me2beats** [comment] 2020-06-20 18:54
Where can I find out the reasons for this decision?
Is it difficult to implement or is it a desire to protect the user from writing confusing code, or is there an assumption that this will be rarely used?
or something else?

**Comment by Calinou** [comment] 2020-06-20 19:44
There have been a few claims here and there that multiple inheritance would be contrary to GDScript's goals of simplicity. Like this part in the documentation: https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_advanced.html#duck-typing

For the record, [GDScript is being rewritten from scratch for Godot 4.0](https://github.com/godotengine/godot/pull/39093).
