### ISSUE TITLE
Add a method to convert a scene to an instanced scene

### ISSUE THREAD

**Issue by TrickMe** [godotengine/godot-proposals#2393] opened 2021-03-03 17:16 UTC
### Describe the project you are working on
Realtime space x4 with procedurally generated galaxy.

### Describe the problem or limitation you are having in your project
I noticed that it is faster to procedurally generate a game scene, while the scene is not in the tree.
So I generate the world out of tree and then add the main node to the tree.

`get_tree().change_scene()` and `get_tree().change_scene_to()` only accept PackedScenes, not nodes.
(or instanced PackedScenes, with nodes like sprites, etc. procedurally added to them)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
solutions:
1
make `get_tree().change_scene()` and `get_tree().change_scene_to()` accept instanced PackedScenes instead of PackedScenes

2
add `get_tree().change_scene_instance()` and `get_tree().change_scene_to_instance()` methods.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
solution 1:
`get_tree().change_scene(newScene.instance())` instead of `get_tree().change_scene(newScene)`
`get_tree().change_scene_to(newScene.instance())` instead of `get_tree().change_scene_to(newScene)`

### If this enhancement will not be used often, can it be worked around with a few lines of script?
add `onready var` and `func` to Autoload "GLOBAL":

```
onready var currentScene:Node = get_node("/root/firstLoadedSceneName")

func change_scene(newScene:Node):
    currentScene.queue_free()
    currentScene = newScene
    get_tree().get_root().add_child(newScene)
```

use in script:

`GLOBAL.change_scene(PackedScene.instance())`

### Is there a reason why this should be core and not an add-on in the asset library?
Although there is an easy workaround, I think it could be beneficial for users and beginners, who generate their game world procedurally.
The change in solution 1 is only to add `.instance()` to the script to update your project to work.

edit:
If a scene is added to the tree, it always has to be instanced first, `change_scene()` seems to be the only exception
So for consistency I encourage solution 1.

**Comment by Calinou** [comment] 2021-03-03 17:18
See also #2367.

**Comment by TrickMe** [comment] 2021-03-03 20:03
Isn't the method to convert a scene to an instanced scene literally `.instance()`?
I'm worrying if the new headline could be misinterpreted.

**Comment by KoBeWi** [comment] 2021-03-03 22:40
Duplicate of #921 (former https://github.com/godotengine/godot/issues/24795)

**Closed by KoBeWi** 2021-03-03 22:40 UTC
Labels: topic:core

**Comment by diablohumastudioadmin** [comment] 2025-04-04 16:27
@KoBeWi you closed #921 because godot were moving proposals out of that repo [https://github.com/godotengine/godot/issues/24795#issuecomment-633720809]. I asume they were being moved here, since url says .../godot-proposals/.... And now in this post you closed it because is a duplicate of #921 

Please reopen it. Is very necesary. 

@TrickMe It is not only usefull to procedurally created scenes. It is also usefull if you want to pass arguments to a scene you want to intantiate (E.g. when you have a game that is setted by a resourse).

I know a workaround is to have a global function to change the scene. And also to have setting resourses globally and access them in _init or _ready. But Still think is a good Idea   

Is not so simple the workaround. If you use cameras, when you add_child(newScene) this is being added before the currentScene is freed because currentScene.queue_free() waits for next free frame. And if both scenes have cameras they will conflict. 

Work around when have cameras in both scenes, involves creating subviewport and subviewpor container before adding newScene and after currentScene is deleted reparend newScene and deleting subvieport and container. 

I have had other issues also. It depends on the need. Many things can be happening (depends on what you have programed) in the _ready func and since both scenes are simultaneausly live they could generate problems and one have to workaround putting the code ind the _init.

**Comment by KoBeWi** [comment] 2025-04-04 18:05
#921 is still open.

**Comment by diablohumastudioadmin** [comment] 2025-04-15 15:38
Thank you for replying. 

Sorry, my mistake. I saw an older version outside of #921 repo. it was #24795 that it was inside of issues. 

And finally repo where change_scene_to_node is on #85762
