### ISSUE TITLE
Make it support for pentablet

### ISSUE THREAD

**Issue by NexushasTaken** [godotengine/godot-proposals#3682] opened 2021-12-17 03:56 UTC
### Describe the project you are working on

*

### Describe the problem or limitation you are having in your project

*

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I mean't to say like...
1. A scroll on mouse to zoom and out in both 2d/3d space
2. To navigate in 3d Space (when i tried to navigate in 3d, the camera is stuck and sometimes the camera doing something really weird) but i can still move around using WASD , in 2d space is fine i can navigate and zoom and out and move.. Heres the clip https://streamable.com/dm19wm

Im playing aroung with godot interface and features, i really like it bcuz its runs too fast,the only problem is the pentablet.. i only use pentablet in my entire life

My pc specs:
Win7 32 bit
Intel Atom CPU N2800 1.86 GHz
2 gb Ram
I use mono version for C#

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

*

### If this enhancement will not be used often, can it be worked around with a few lines of script?

*

### Is there a reason why this should be core and not an add-on in the asset library?

*

**Comment by pycbouh** [comment] 2021-12-17 11:26
Duplicate of https://github.com/godotengine/godot-proposals/issues/196

**Closed by pycbouh** 2021-12-17 11:26 UTC
