### ISSUE TITLE
Show existing methods when connecting signals (including base funcs when no script is attached)

### ISSUE THREAD

**Issue by sampengilly** [godotengine/godot-proposals#752] opened 2020-04-25 13:49 UTC
**Describe the project you are working on:**

Exploring various means of gameplay design/implementation, issue is project agnostic.

**Describe the problem or limitation you are having in your project:**

The problem is two-fold:
1.) When connecting a signal to a node in the editor, specifying an existing method is clunkier than it could be
2.) When connecting a signal to a node in the editor, triggering an existing base method on a node without a script attached appears to not work from my testing

The sum of these is that hooking up signals require scripts to be attached and modified even when the desired outcome is incredibly simple. For example, connecting the `body_entered` signal to the `play()` method of an `AudioStreamPlayer`.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

In the signal connection dialog, replace the method name text input with a dropdown list of all available methods in the node and possibly allow creating a new method as an option. The list of methods should include the methods of the node, and if a script is attached, any methods in the attached script.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Rough mockup, dropdown for existing methods on node + any methods defined in an attached script. Arguments can be specified as usual on the right panel (possibly with required arguments pre-populated for value entry, but that's an additional QoL thing. On that note though I could also foresee a need to show signal parameters and allow configuration of which method parameters they are wired up with)
![image](https://user-images.githubusercontent.com/1129772/80281351-caa0f880-874d-11ea-8ede-217be97deb92.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

It can be worked around in script, but the intention behind it is to avoid needing to write some script for connections that don't need it and to increase the QoL and tooling options available for a gameplay designer to quickly and easily wire up various game events to available methods on other nodes. In the worst case a new script file needs to be created and maintained for a single task that already exists on the node itself.

This is partly inspired by a [Unity Engine talk](https://www.youtube.com/watch?v=raQ3iHhE_Kk), Godot is about 90% of the way there for this type of tooling, the signals system is super powerful, but there are some improvements that can be made to the tooling to take it to the next level.

**Is there a reason why this should be core and not an add-on in the asset library?:**

It's a modification to an existing editor function.

**Comment by Jummit** [comment] 2020-04-25 14:39
Sounds good, but please no dropdown :wink:

**Comment by KoBeWi** [comment] 2020-04-25 15:43
Related:
https://github.com/godotengine/godot/issues/24316
https://github.com/godotengine/godot/issues/9644

**Comment by KoBeWi** [comment] 2020-04-25 15:46
Also duplicate of #239 .-.

**Closed by KoBeWi** 2020-04-25 15:46 UTC

**Comment by sampengilly** [comment] 2020-04-25 23:50
Ah apologies, I tried searching for existing issues on this but came up empty, was searching things with slightly different language
