### ISSUE TITLE
Add a method to rotate around a point

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#235] opened 2019-11-15 15:53 UTC
**Describe the project you are working on:**
A learning project, where I rotate the level around the player.

**Describe the problem or limitation you are having in your project:**
Normally if you want to rotate everything around a certain point, you add a parent node acting as pivot. In my case it's not viable, because the "pivot" is moving and I don't want to move everything with the pivot. So my workaround is this:
```
var trans := global_transform
var parent := get_parent()
parent.remove_child(self)
	
player.get_node("Rotator").add_child(self)
global_transform = trans
player.get_node("Rotator").rotation_degrees += rot
trans = global_transform
player.get_node("Rotator").remove_child(self)
	
parent.add_child(self)
global_transform = trans
```

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It would change the above code into
```
rotate_around(player.global_position, rot)
```
I guess it would help people with similar problem too.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
N/A

**Describe implementation detail for your proposal (in code), if possible:**
A method in Node2D that has the equivalent functionality of the long code above.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
10 lines is more than "few". Maybe.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's impossible to extend base types with plugins.

**Comment by hammeron-art** [comment] 2019-11-15 22:15
You can use Transform math for this:
```
global_transform = player.global_transform * Transform2D().rotated(angle).translated(offset)
```

**Comment by KoBeWi** [comment] 2019-11-16 00:22
> You can use Transform math for this:

Nope, this doesn't work.

**Comment by hammeron-art** [comment] 2019-11-16 01:49
It sure does. I use it all the time.
```
extends Sprite

export(NodePath) var player_path
onready var player = get_node(player_path)

var angle = 0

func _process(delta):
	angle += delta
	var offset = Vector2(32, 0)
	global_transform = player.global_transform * Transform2D().rotated(angle).translated(offset)
```
![GIF](https://user-images.githubusercontent.com/6967786/68986021-05dfe880-07fa-11ea-9354-a6114e725811.gif)

**Comment by KoBeWi** [comment] 2019-11-16 02:13
Eh, care to look at my project?
[NowaSekcja.zip](https://github.com/godotengine/godot-proposals/files/3853714/NowaSekcja.zip)

I'm doing the rotation in LevelRotate.gd. Compare your line with how my original code works. I guess offset might be important here, but I'm not sure what it should be.

**Comment by hammeron-art** [comment] 2019-11-16 05:33
It can be an order of execution issue. The correct order would be: player moves -> level moves -> offset calculation to be used in the next frame. Also, the physics engine changes the player position throws off the system even more.

Anyway, you can do a parent/child relationship like your workaround directly with math. Get a transform that is local to the level from the player and then rotates it.
```
func do_rotation():
	var local = player.global_transform.affine_inverse() * global_transform
	global_transform = player.global_transform * local.rotated(rot * 0.01)
```

**Comment by KoBeWi** [comment] 2019-11-16 13:48
Ok, the last one works. But as you can see, it's some complex math that most users won't even know about. Godot already has some convenience functions, adding a helpful two-liner wouldn't probably hurt. Or at least it could be documented somewhere.

**Comment by hammeron-art** [comment] 2019-11-16 16:25
Some concepts and operations are documented in https://docs.godotengine.org/en/latest/tutorials/math/matrices_and_transforms.html and https://docs.godotengine.org/en/latest/tutorials/3d/using_transforms.html

But I agree, I often want to rotate around a point too and it is a common operation that could be a helper function. However, it should be a method in the Transform2D class then a wrapper in Node2D like others: Transform2D().rotated() and Nore2D.rotate(), Transform2D().translated and Node2D.translate(), etc. Also for Transform and Spatial.

```
Transform2D Transform2D.rotated(Vector2 origin, float, radians)
void Node2D.rotate(Vector2 origin, float, radians)

Transform Transform.rotated_around(Vector3 origin, Vector3 axis, float phi)
void Spatial.rotate_around(Vector3 origin, Vector3 axis, float phi)
```

**Comment by me2beats** [comment] 2021-03-26 23:43
Having similar method for 3D would be also good
(but this also would take axis as an argument)

**Comment by takecare** [comment] 2021-10-03 09:39
> ```
> extends Sprite
> 
> export(NodePath) var player_path
> onready var player = get_node(player_path)
> 
> var angle = 0
> 
> func _process(delta):
> 	player.global_position = get_global_mouse_position()
> 
> 	angle += delta
> 	var offset = Vector2(32, 0)
> 	global_transform = player.global_transform * Transform2D().rotated(angle).translated(offset)
> ```


@hammeron-art isn't there an issue with this approach where if something else changes the player transform it will also impact this sprite's transform? i.e. let's say you scale the player node, won't this sprite end up scaled as well?

**Comment by vand-er** [comment] 2021-12-31 05:23
> > ```
> > extends Sprite
> > 
> > export(NodePath) var player_path
> > onready var player = get_node(player_path)
> > 
> > var angle = 0
> > 
> > func _process(delta):
> > 	player.global_position = get_global_mouse_position()
> > 
> > 	angle += delta
> > 	var offset = Vector2(32, 0)
> > 	global_transform = player.global_transform * Transform2D().rotated(angle).translated(offset)
> > ```
> 
> @hammeron-art isn't there an issue with this approach where if something else changes the player transform it will also impact this sprite's transform? i.e. let's say you scale the player node, won't this sprite end up scaled as well?

var original_scale = self.global_scale
	global_transform = player.global_transform * Transform2D().rotated(angle).translated(offset).scaled(original_scale)

this is what i did to get the scale to the normal size

**Comment by BaddRadish** [comment] 2022-03-31 17:17
this would be such an easy feature to add and would make a LOT of things a LOT easier. i absolutely support this.

**Comment by Calinou** [comment] 2022-04-01 00:31
@BaddRadish Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by Calinou** [comment] 2022-04-21 14:17
We discussed this in a proposal review meeting, and found that this proposal does not have enough community support in its current form to warrant inclusion in core. This may change in the future depending on community support.

**Comment by YuriSizov** [comment] 2022-06-29 17:00
I guess we can close it as not planned and reopen it if we decide to still include it.

**Closed by YuriSizov** 2022-06-29 17:00 UTC
Labels: topic:core

**Comment by joemicmc** [comment] 2023-08-28 15:55
Anybody coming to this issue and using 4.x, it looks like the order of applying transforms matters now (at least in 3D) e.g. 

```transform.rotated(up, angle).translated(offset)```

Will give different behaviour to:

```transform.translated(offset).rotated(up, angle)```

Not sure if this was always the case or not, had this issue bookmarked as reference for rotating around a point and pretty sure I've used as is before (with 3D equivalents).

**Comment by mathphye** [comment] 2023-10-05 20:32
> Anybody coming to this issue and using 4.x, it looks like the order of applying transforms matters now (at least in 3D) e.g.
> 
> `transform.rotated(up, angle).translated(offset)`
> 
> Will give different behaviour to:
> 
> `transform.translated(offset).rotated(up, angle)`
> 
> Not sure if this was always the case or not, had this issue bookmarked as reference for rotating around a point and pretty sure I've used as is before (with 3D equivalents).

That is the expected behavior. As the translation is based on the local axis, and you change the axis with rotation... 
![image](https://github.com/godotengine/godot-proposals/assets/146298448/3af855e5-9fb1-44bf-aef5-3a136789dafb)
