### ISSUE TITLE
Add option to show hidden files/folders also for the filesystem dock

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#6271] opened 2023-02-11 11:52 UTC
### Describe the project you are working on

A tool to define game objects (apples, tree branches, arrows, that sort of stuff). This places the user-generated database in a hidden folder, but there's currently no way to show it in the filesystem dock, and since i'm developing on android, i'd like to use godot's built-in text editor to optionally visualize the files i have in the hidden folders

### Describe the problem or limitation you are having in your project

It's very cumbersome to open text files with no extension on android, and I'd like to use godot' 4 built-in text editor for it, since it supports also opening text files and jsons. I would prefer not compromising on using hidden folders.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a checkbox in editor setting to show hidden folders and files also for the filesystem dock

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it can be worked around by using another application to open text files, but it's immensely less convenient on android

### Is there a reason why this should be core and not an add-on in the asset library?

i don't think it's possible as an addon

**Comment by YuriSizov** [comment] 2023-02-11 13:56
Duplicate of https://github.com/godotengine/godot-proposals/issues/677.

**Closed by YuriSizov** 2023-02-11 13:56 UTC
Labels: topic:editor, platform:android

**Comment by QbieShay** [comment] 2023-02-11 15:25
I don't think it's a duplicate? hidden folders and files are not in the initial proposal

**Comment by Calinou** [comment] 2023-02-11 15:31
> I don't think it's a duplicate? hidden folders and files are not in the initial proposal

Are you referring to files/folders starting with `.`? Non-resource files don't appear in the filesystem dock, but they're not considered "hidden" files by the OS (unless their name starts with `.`, or you toggle the hidden flag on Windows).

**Comment by QbieShay** [comment] 2023-02-11 16:51
I have a folder called `.objdb` in `res://`, i see it if i enable show hidden files in the file dialog, but there's no option for the filesystem doc

**Comment by Calinou** [comment] 2023-02-11 17:00
> I have a folder called `.objdb` in `res://`, i see it if i enable show hidden files in the file dialog, but there's no option for the filesystem doc

This effectively depends on https://github.com/godotengine/godot-proposals/issues/677 being implemented first. There's a comment which mentions there should also be a way to display hidden files when non-resource files are displayed: https://github.com/godotengine/godot-proposals/issues/677#issuecomment-1131867431

Godot never imports hidden files, so it's not possible to have a resource file that is hidden. There are only 3 possible states:

- Visible resource file
- Visible non-resource file ("visible" within the OS file manager, that is)
- Hidden non-resource file

**Comment by QbieShay** [comment] 2023-02-11 17:35
alright. what would be the best way for me to go about this? have a non hidden folder with  just json files inside?

**Comment by Calinou** [comment] 2023-02-11 22:42
> alright. what would be the best way for me to go about this? have a non hidden folder with just json files inside?

Yes, this is likely the best way to go about it for now :slightly_smiling_face:
