### ISSUE TITLE
How to synchronize font and font size across different node types collectively now that DynamicFont is gone

### ISSUE THREAD

**Issue by Overvault-64** [godotengine/godot-proposals#6083] opened 2023-01-11 19:22 UTC
### Describe the project you are working on

Every project that has UI

### Describe the problem or limitation you are having in your project

While being able to add font files directly in theme and theme overrides is (slightly) more comfortable than having to create a `DynamicFont`, in Godot 4 we totally lost the ability to synchronize font settings through different nodes and node types.

Up to Godot 3.5.1, I used a `DynamicFont` - let's say `small.tres`, set my font file, and use it across all my nodes: labels, rtlabels, buttons, lineedits, textedits basically every type of node with text. Changing `font_size` in `small.tres` would reflect across the whole project.

Now `DynamicFont` is gone and you have to manually change `theme_override_font_sizes/font_size` for every single node in your project (with high risk of leaving some behind). The only exception being `Label` nodes thanks to the `LabelSettings` class.

But here's where Type Variations can come in handy.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When explaining how to use type variations, the [documentation](https://docs.godotengine.org/en/latest/tutorials/ui/gui_theme_type_variations.html) states that

> You can select the base type there, which would typically be the name of a control node class (e.g., Button, Label, etc)

This leaves some room to assume that you can set `Control` as base type, and this is partially true.
In fact, if you type "Control" in the base type selection menu and confirm, you won't be creating a new custom type called "Control" (as the given prompt says), but you'd be actually selecting `Control`, though it's not included in the list.

![image](https://user-images.githubusercontent.com/96829602/211893280-b131f245-67e8-48a0-a5b3-eaebb0d2e8bd.png)

A type variation thus made will be available for all control-based, but won't show up in the dropdown menu and you'll have to type it manually in the selector, similarly to what happens if the theme is not set as project-wide.
> Variations appear on the list only if the type variation belongs to the project-wide theme, which you can configure in the project settings. For any other case you have to input the name of the variation manually.

![image](https://user-images.githubusercontent.com/96829602/211898721-8efb934a-e147-48cf-b903-a87e5022b63d.png)
<sub>Side note: since the type variation selector is located right below the theme selector in the node inspector, I'd expect that if a theme is set, its type variations will show up as well, instead of project-wide ones only.</sub>

As it was pointed out to me by @lewiji, this approach can replace the use I made of DynamicFonts.
For example, you could create a "medium size" type with a certain font size. Updating it would reflect in every other control node "tagged" (as you'd do in HTML/CSS) with the `medium size` type variation, no matter if they are labels, lineedits, buttons. If they have text, they will update their font size accordingly.

That being said, I think that `Control` (or even `Node`) should be included in the base type list, so that this process feels more legit and control-based type variations can be picked up quickly in the dropdown menu.

Also, editing those type variations should make nodes update in real time as usual in the editor. To see changes, I have to run the scene (which is not always possible if the scene contains script dependancies) or restart the editor.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Self-explanatory

**Comment by YuriSizov** [comment] 2023-01-11 20:25
> Now DynamicFonts are gone and you have to manually change theme_override_font_sizes/font_size for every single node in your project (with high risk of letting some behind). The only exception being Label nodes thanks to the LabelSettings class.

Every node that has a font property also has a font size property. You don't need a variation for that.

> Can't select Control as a base type in theme's type variations

Base Control doesn't have any theme properties, there is nothing to extend. I'd still say this is probably an oversight, but it's also not expected to be useful to anyone. What you attempt to do here is not how theme type variations are designed to work. You're supposed to extend node's base type, not use some generic variation on every node. So I cannot guarantee you that this would work without issues even if you manage to assign that type.

**Comment by handre-dev** [comment] 2023-01-12 12:59
> Every node that has a font property also has a font size property. You don't need a variation for that.

If I wanted to change their font size individually I could, quote myself, "manually change theme_override_font_sizes/font_size for every single node". Maybe you missed this part (quote myself again):
> While being able to add font files directly in theme and theme overrides is (slightly) more comfortable than having to create a DynamicFont.tres, in Godot 4 we totally lost the ability to synchronize font settings through different nodes and node types.

If there's a solution for that, I'll be happy to stop misusing type variations.

> They do (update in real time). Maybe this has something to do with the fact that you are not using them in the supported way, not sure, since this was never tested.

They don't, even if used in the supported way.

![image](https://user-images.githubusercontent.com/96829602/212071774-bc1a5acd-48d8-4c3c-891c-c5709f00263a.png)
![image](https://user-images.githubusercontent.com/96829602/212071873-4db0c8ac-0a0b-4a9e-a782-f3a6cb3ebb0c.png)
![image](https://user-images.githubusercontent.com/96829602/212072237-75d97431-87e0-47a2-9625-604bad4803f9.png)
![image](https://user-images.githubusercontent.com/96829602/212072269-e9057bc4-f238-4e56-aa05-53b9e40596fd.png)

I have tested them in 3.5.1 and 4.0 beta10, and the editor just doesn't update until project reboot.
I would not have written a single line of this issue without first doing all the relevant tests.

**Comment by YuriSizov** [comment] 2023-01-12 13:17
> If I wanted to change their font size individually I could, quote myself, "manually change theme_override_font_sizes/font_size for every single node". Maybe you missed this part

You misunderstood me. What I'm saying is that you can use the theme to set a particular default font and font size for every control type, and for the entire theme in general. You don't need to override it on individual controls, unless you want to change specific controls.

If I understand correctly, you were using local overrides for theme properties to share the same font resources, which allowed you to change the size in the same place. Yes, you can't do that anymore. For every place where you need to override the size, you need to do it manually, or through a custom solution. We currently don't have a way to share primitive types, same applies for colors for example which you also need to manually update everywhere where you do overrides.

> They don't, even if used in the supported way.

Hmm, that should still work, but I admit I was thinking about a different workflow from your initial description. I have a couple of ideas where the issue might come from, but fixing it should have to wait for 4.1.

**Comment by handre-dev** [comment] 2023-01-12 13:42
> If I understand correctly, you were using local overrides for theme properties to share the same font resources, which allowed you to change the size in the same place. Yes, you can't do that anymore.

Exactly, and it worked so well that I assumed it was intended. When I saw they were gone in Godot 4, I was like yo wtf, I need another solution, and that's when I was informed about the type variation thing.

> For every place where you need to override the size, you need to do it manually

As I said, there is an exception, being LabelSettings, which basically allows you to do the trick. The class description itself encapsulates the philosophy:

> Collection of common settings to customize label text.

That's the key. I've opened a [thread about it](https://github.com/godotengine/godot-proposals/discussions/6074), and this issue actually stemmed from it.
It would be perfect if there was something like a "TextSettings" class, compatible with all the text-equipped nodes that would allow us to edit basic font settings at once across multiple nodes, as with LabelSettings, except it would also work across different node types and not Labels only.

**Comment by YuriSizov** [comment] 2023-01-12 13:47
The problem is that we specifically moved the font size outside of the resource so you could override it quickly, without having to dupe the resource. It was usually a huge problem for users because of how unintuitive it was. So moving it back into a resource would result in reserving this usability improvement.

Now, I don't see why we couldn't have a base font size inside of the font resource **and** a dedicated font size property that would override that base size in resource, if present... I don't think we've considered something like that.

As for `LabelSettings`, we don't agree internally that it was a good solution. It duplicates the existing functionality instead of improving it, and splits the approach to solving the problem into multiple non-compatible paths. So I wouldn't consider anything similar in future.

**Comment by Calinou** [comment] 2023-01-12 16:04
Related to https://github.com/godotengine/godot-proposals/discussions/6074.

**Comment by handre-dev** [comment] 2023-01-14 16:16
> I have tested them in 3.5.1 and 4.0 beta10, and the editor just doesn't update until project reboot.

From further tests, looks like this issue involves theme changes in general, not only type variations. Also, changing scene tab in the editor is enough to apply the changes (no need to reopen the project).

**Comment by YuriSizov** [comment] 2023-01-14 16:54
Ah, yes, global themes don't report their changes well, because they are not directly related to the scene tree. Instead they are used as fallback values. I plan to fix that for 4.1 as well.

**Comment by Overvault-64** [comment] 2023-06-10 13:53
hey @YuriSizov, news on this?

> Now, I don't see why we couldn't have a base font size inside of the font resource **and** a dedicated font size property that would override that base size in resource, if present... I don't think we've considered something like that.

this would still be great

**Comment by YuriSizov** [comment] 2023-06-12 11:11
No work has been done of it yet, sorry.

**Comment by Overvault-64** [comment] 2023-06-12 14:32
> No work has been done of it yet, sorry.

No worries, I'll comment here again in another 4-5 months if it doesn't bother you ahah thanks for your work

**Comment by Overvault-64** [comment] 2023-12-08 12:22
Latest updates had the (I think collateral) effect of fixing some of the problems we discussed here. Just wanted to point them out.

<br>

>Ah, yes, global themes don't report their changes well

Now they do.

<br>

>editing type variations should make nodes update in real time as usual in the editor

What fixed the global themes issue above, also fixed this one I suppose.

<br>

>`Control` should be included in the base type list, so that this process feels more legit

Now it's included and selectable. And yes, it feels legit now.

![image](https://github.com/godotengine/godot-proposals/assets/96829602/31fdff55-65b1-4330-82bf-00f323c54c65)
![image](https://github.com/godotengine/godot-proposals/assets/96829602/7ada8c9f-0f72-4c87-9923-9bf4bae78746)

<br>

All these changes have definitely made my way of using type variations much more viable.

Only hiccup is the type variation selection menu not cooperating.
According to the [docs](https://docs.godotengine.org/en/stable/tutorials/ui/gui_theme_type_variations.html#using-a-type-variation), if a theme is set as project-wide, its type variations should show up in the dropdown menu. This doesn't work for my Control-based variations, so it feels like there's something fixable underneath.

EDIT: While I was writing this, I double-tested selecting Control as base type and it didn't show up anymore. Weird.
![image](https://github.com/godotengine/godot-proposals/assets/96829602/075ed3f7-f644-4a46-b5a7-357a884a48f1)

**Closed** 2023-12-08 14:14 UTC
Labels: topic:editor, topic:gui
