### ISSUE TITLE
Prevent or warn users when creating projects with a "." at the end of the name

### ISSUE THREAD

**Issue by skyace65** [godotengine/godot-proposals#4389] opened 2022-04-12 01:30 UTC
### Describe the project you are working on

Godot Documentation

### Describe the problem or limitation you are having in your project

Godot allows you to create projects with a "." at the end of the project name. This is a problem because on Windows this will cause locations like the `user://` directory of a game to be treated as corrupt and projects will not work properly.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Prevent people from creating project names with a period at the end. I would imagine the amount of projects that would want a "." at the end of the name is very small so it's worth removing. If not at least add a warning.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by Calinou** [comment] 2022-04-12 13:53
Duplicate of https://github.com/godotengine/godot/issues/32330 (this is a bug).

**Closed by Calinou** 2022-04-12 13:53 UTC
Labels: topic:editor
