### ISSUE TITLE
Implement Toasts/Snackbars for progress bars and notices

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-proposals#1831] opened 2020-11-13 18:32 UTC
**Describe the project you are working on:**
Made a [feature proposal](https://github.com/godotengine/godot-proposals/issues/1830) which considered removing the file deletion confirmation

**Describe the problem or limitation you are having in your project:**
The file deletion popup doesn't do its job well, but removing it could cause people to delete files accidentally and not notice what they have done ([As noted by @pycbouh](https://github.com/godotengine/godot-proposals/issues/1830#issuecomment-726896431))

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Implement a "notification" system which is floating and resides on the bottom right of the screen.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Here is a little mock-up I made. The files deleted popup has a little progress bar which denotes when the notification will expire.

![image](https://user-images.githubusercontent.com/14253836/99107290-36906480-25ab-11eb-8e18-478534fdfa02.png)

Note: I am taking a lot of inspiration from KDE's notifications:
![image](https://user-images.githubusercontent.com/14253836/99107592-b61e3380-25ab-11eb-89d4-aae9f6b608f6.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This will be used pretty often and can't really be worked around.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This would be an unusual feature to be in the asset library

---

CC @pycbouh: We discussed the possibility that users would miss the fact that they deleted files. What do you think about this proposal as an improvement on that problem? Do you think this popup system would be too intrusive for users for small actions such as deletion?

**Comment by pycbouh** [comment] 2020-11-13 18:36
I'm not against toasts for these and other actions. They work pretty well, and we can experiment with keeping a history of them. I think they were suggested several times, though, not sure what's the status on that currently or if there was actually a proper proposal.

**Comment by Calinou** [comment] 2020-11-13 18:46
Duplicate of https://github.com/godotengine/godot-proposals/issues/1489.

**Closed by Calinou** 2020-11-13 18:46 UTC
