### ISSUE TITLE
Problem with labels/texts

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#559] opened 2020-03-06 08:20 UTC
**Describe the project you are working on:**
I am learning Godot, I am moving texts/labels and changing their size.
Previously I used other engines in which the feature that I propose here greatly facilitated the task.
Godot does not have this characteristic, I do not know the reason.

**Describe the problem or limitation you are having in your project:**
The reference point of the labels is immutable, this causes any change in size to require new calculations to keep the label centered.
This would not happen if the reference point were editable.
Currently the point is fixed in the upper left corner, you cannot place it in the center or at any other end.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The possibility of being able to locate the reference point in the center or another place will greatly facilitate the task of handling some aspects of the text.

As you can see in the image, Construct 2 allows you to locate the point in the options shown.
![1](https://user-images.githubusercontent.com/19652075/76065207-723e4d80-5f8b-11ea-8c71-eb20f01d8f3e.png)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
If Godot allows you to locate the reference point in the center, all calculations will be made from that point, this avoids having to reposition the text when you change its size or its coordinate, for example.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes, it can be solved using code that places the text centered on an X coordinate, but it is cumbersome.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, to facilitate the task in the management of texts and making it more accessible by not having to download any add-on.

**Comment by Jummit** [comment] 2020-03-06 08:27
Do you mean this?
https://docs.godotengine.org/en/latest/classes/class_label.html#class-label-property-align

**Comment by Torguen** [comment] 2020-03-06 08:34
No !, that is to center the text in the box.
But if you change its scale, it will happen having as reference the upper left point, that is what I mean.

**Comment by Jummit** [comment] 2020-03-06 09:42
Instead of scaling text labels to get a larger font size, use [DynamicFont](https://docs.godotengine.org/en/latest/classes/class_dynamicfont.html)s.

> This trades the faster loading time of BitmapFonts for the ability to change font parameters like size and spacing during runtime.

**Comment by Calinou** [comment] 2020-03-06 10:14
Duplicate of #129.

**Closed by Calinou** 2020-03-06 10:14 UTC

**Comment by Torguen** [comment] 2020-03-06 20:13
Well, it seems that the solution to my problem is to configure "Pivot offset" to the center.
But recently I tried it and I couldn't get the GIF result, I guess I did something wrong.
![GIF](https://user-images.githubusercontent.com/19652075/76119220-4654b380-5fef-11ea-8f57-1a2bb6b1c8f0.gif)
