### ISSUE TITLE
comprehensive logging

### ISSUE THREAD

**Issue by darthLeviN** [godotengine/godot-proposals#6864] opened 2023-05-11 20:46 UTC
### Describe the project you are working on

A godot game with an ingame console.

### Describe the problem or limitation you are having in your project

I wish to directly access the output of print, print_debug and any logs generated by godot in gdscript.

godot's logging is not great. all godot log messages should have a dedicated labeling system. on top of that we should be able to add a hook that captures filtered messages.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Internally all godot engine logs should be labeled with "godot". and also be timestamped. the following methods should be added :

```
OS.register_log_handler([labels, empty for all labels], callback)
OS.register_warning_handler([labels, empty for all labels], callback)
OS.register_error_handler([labels, empty for all labels], callback)
OS.unregister_xxx
OS.is_registered_xxx

// separate print functions for backwards compatibility
print_debug_labled(string, label, args...)
print_labled(string, label, args...)
push_warninig_labeled(string, label, args...)
push_error_labled(string, label, args...)
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

log handlers will have the form below :

```
func log_handler(label, message, timestamp)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No. it's only doable in c++ and there is still no labels or easy to use timstamps.

### Is there a reason why this should be core and not an add-on in the asset library?

I'm not even sure if it can be an asset library.

**Comment by Calinou** [comment] 2023-05-12 00:25
- Duplicate of https://github.com/godotengine/godot-proposals/issues/919, https://github.com/godotengine/godot-proposals/issues/1896 and https://github.com/godotengine/godot-proposals/issues/5937.

**Closed by Calinou** 2023-05-12 00:25 UTC
Labels: topic:core, topic:gdscript
