### ISSUE TITLE
Add engine version number to project.godot file

### ISSUE THREAD

**Issue by Listwon** [godotengine/godot-proposals#4355] opened 2022-04-06 10:12 UTC
### Describe the project you are working on

Any project I'm opening with Godot.

### Describe the problem or limitation you are having in your project

I'm unable to tell which minor version of Godot was used to create the project. Most often than not I'm encountering smaller or larger incompatibilities between the Godot version which was originally used and the version I'm opening the project with now. It's not a problem if I can ask the developer which version he's using (for example in cases I'm helping someone), but that's not always the case.

Editor version is so important that it's already stored in every exported pck package so I'm not sure why it's not stored in project.godot file yet.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add info about the current editor version in autogenerated section of `project.godot` file.

Where and why does it help;
- MRPs - project contains editor version, so you know exactly in which version the problem occured
- open source sample projects or even full games - if you encounter some bugs opening the project with the latest release, you can check if they are present in the original minor version too (developers usually add the info about the major version, like Godot 3, in the README.md, but it's not always sufficient). I remember encountering strange physics bugs in one project, which was originally created in Godot 3.2.3 and I tried to open it in 3.3.x
- your own projects - the same as above, you store the info about the editor version on your repository, so in case of bumping the editor version, you know exactly when you did this, from which version and you are able to look through release notes to see what could break your project (I do this very often with Godot and Unity projects; Unity already stores the editor version in separate file inside ProjectSettings folder; Unreal Engine stores editor version in ProjectName.uproject file).
- migration tools like this PR from qarmin https://github.com/godotengine/godot/pull/51950

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

project_settings.cpp

![obraz](https://user-images.githubusercontent.com/1554127/161948797-0959cf55-439d-42b3-9e7b-fc3e6f25da7d.png)

Output (not the actual output from the code above, because it would be without hash at the end):

![obraz](https://user-images.githubusercontent.com/1554127/161944326-b14289c7-1411-442f-b854-280fc6c12cf5.png)

The actual format is up for discussion. We can store editor version data as separate fields and not the whole string, like this:
```
editor_version_major = 3
editor_version_minor = 4
editor_version_patch = 4
editor_version_hash = "419e713a2"
editor_version_status = "stable"
editor_version_module_config = "mono"
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This enhancement will be used very often.

### Is there a reason why this should be core and not an add-on in the asset library?

This enhancement will be used very often and possibly in the future will be used to show project version on the project list and maybe even showing a warning about the possible incompatibilities.

**Comment by Xananax** [comment] 2022-04-06 11:39
This would be very useful. I currently always redundantly store the version in the accompanying README file, as well as track which version is used for each project through [Hourglass](https://gitlab.com/jwestman/hourglass/), but even doing that, I've been bitten by mismatched versions more than once.

I have a bunch of old prototypes (or even projects) from before that habit that I can't run anymore because I can't remember what they used to run on.

More importantly, working with teams, a consistent source of confusion is someone upgrading Godot unknowingly (through Steam/itch/package manager) and getting unreproproducible errors. Or someone on the team not knowing that we've upgraded and still working in a previous version, and being unable to run the project.

**Comment by mrjustaguy** [comment] 2022-04-06 12:56
It'd be more efficient to use just a single string for versions and stuff due to smaller size it's not hard for an interface to read and separate, so something like:
`created_using_godot_version = "4.0.0 Alpha 7 Mono"` (Created when Project file is Created and never modified)
`last_used_godot_version = "4.0.0 Stable"` (Automatically generated if no errors pop during loading of all the assets)
`last_confirmed_functioning_godot_version = "4.0.0 Custom insert-hash-here"` (User generated, by pressing a button confirming that it works)

**Comment by Calinou** [comment] 2022-04-06 14:20
Related to https://github.com/godotengine/godot-proposals/issues/237.

**Comment by fire-forge** [comment] 2022-04-07 07:06
It would also be nice for the editor to show a warning when trying to open a project from the wrong version, so you don't accidentally open a 3.x project in 4.0 or vice versa. I'm not sure if the warning should be added for minor versions (ex. 3.4 to 3.5) though, as it could be helpful but also might be annoying.

**Comment by Listwon** [comment] 2022-04-07 07:21
> It would also be nice for the editor to show a warning when trying to open a project from the wrong version, so you don't accidentally open a 3.x project in 4.0 or vice versa. I'm not sure if the warning should be added for minor versions (ex. 3.4 to 3.5) though, as it could be helpful but also might be annoying.
I don't think it would be annoying, Unity does this for each PATCH difference, not only minor. But implementing it is outside of the scope of this proposal in my opinion. I'd start with a small step of storing editor version in project file, which is essentially an industry standard at the moment.

**Comment by Zireael07** [comment] 2022-04-07 07:27
I agree we need to store the editor version in the project file. Whether it's a string or ints doesn't matter as long as it's there so as a further step the project manager can tell me I'm trying to open my 4.0 project by mistake!!!

**Comment by lyuma** [comment] 2022-05-13 00:54
I added another companion proposal at #4534 for also including this information into .tscn/.scn, .tres/.res and .import files.

**Comment by aaronfranke** [comment] 2022-06-15 13:09
The way it works as of https://github.com/godotengine/godot/pull/31171 being merged:

* It will automatically save the minor version that it's made in. For example, 4.0, 4.1, 4.2, etc.
* If you want to save the full engine version, you can manually pin to:
  - The patch release, for example 4.0.1
  - The full config, for example 4.0.1.stable.mono (VERSION_FULL_CONFIG)
  - The full build, for example 4.0.1.stable.mono.official (VERSION_FULL_BUILD)
* The way that you pin it is by opening `project.godot` and adding a string to the list. We could make some kind of UI for this in the editor, but I'm not sure what that UI would look like.

Where it's added: https://github.com/godotengine/godot/blob/master/core/config/project_settings.cpp#L96  
Where it's defined: https://github.com/godotengine/godot/blob/master/core/version.h#L57

**Closed** 2022-08-25 18:01 UTC
Labels: topic:editor
