### ISSUE TITLE
move_and_collide rotation for KinematicBody2D/3D.

### ISSUE THREAD

**Issue by SimoneStorai** [godotengine/godot-proposals#587] opened 2020-03-15 13:53 UTC
**Describe the project you are working on:**
2D physics platformer with lots of moving platforms strictly following a scripted pattern of mine.

**Describe the problem or limitation you are having in your project:**
Not being able to rotate KinematicBody2D and detect/apply collisions as well, resulting in my player character (KinematicBody2D) moving fuzzily.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I would like KinematicBody2D/3D to support centrifugal movement (rotation) and collision detection, as that would hugely enhance my game's overall look and playability.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
move_and_collide([...], real_t rotation) (2D)
move_and_collide([...], Vector3 rotation) (3D)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, it cannot. You can only set the transform's global rotation or replace the KinematicBody with a RigidBody entirely, doing both worsens the stuttering effect.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it is core physics related.

**Comment by KoBeWi** [comment] 2020-03-15 18:45
Duplicate of #364

**Closed by KoBeWi** 2020-03-15 18:45 UTC
