### ISSUE TITLE
Implement drag-and-dropping materials from the FileSystem dock to a MeshInstance in the 3D viewport

### ISSUE THREAD

**Issue by addmix** [godotengine/godot-proposals#1938] opened 2020-12-04 19:18 UTC
### Describe the project you are working on

bog-standard multiplayer FPS

### Describe the problem or limitation you are having in your project

Map prototyping is a crawl as is, and applying materials is unintuitive, and slow.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Drag and drop functionality for materials, allow for material files to be dropped onto objects to be applied.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

drag material.tres file onto an appropriate spatial node to assign the material.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This would most likely be used as the main way to assign predefined materials to objects

### Is there a reason why this should be core and not an add-on in the asset library?

This is a core functionality in most other programs, (Unreal, Unity, Blender, etc.) and would be a huge time saver for anyone prototyping areas/maps

**Comment by Jummit** [comment] 2020-12-04 20:17
Here is an addon that assigns the material as the material override:
[material_dropper.zip](https://github.com/godotengine/godot-proposals/files/5645245/material_dropper.zip)

**Comment by addmix** [comment] 2020-12-04 20:56
(https://docs.godotengine.org/en/stable/classes/class_geometryinstance.html#class-geometryinstance-property-material-override) or [Mesh](https://docs.godotengine.org/en/stable/classes/class_mesh.html#class-mesh-method-surface-set-material)?

Probably geometry instance as on a mesh level it might get messy.

**Comment by Calinou** [comment] 2021-03-27 01:11
Duplicate of https://github.com/godotengine/godot-proposals/issues/394.

**Closed by Calinou** 2021-03-27 01:11 UTC
Labels: topic:editor
