### ISSUE TITLE
Add "Sort by last opened" option to "Editor Settings/Text editor/Script list/sort_scripts_by" setting

### ISSUE THREAD

**Issue by PixelTim** [godotengine/godot-proposals#10806] opened 2024-09-22 14:32 UTC
### Describe the project you are working on

Any

### Describe the problem or limitation you are having in your project

I often have lots of opened scripts (approx 50 scripts) and it's hard to find previous opened script

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be easier to navigate through the script list if *Editor Settings/Text editor/Script list/sort_scripts_by* setting would have "Sort by temperature"/"Sort by last opened" options

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When *Editor Settings/Text editor/Script list/sort_scripts_by* is set to "Sort by last opened" the script list will have recently opened scripts in top

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It improves usability of the editor and it is core

**Comment by Mickeon** [comment] 2024-09-22 19:05
This seems to be a duplicate of:
- https://github.com/godotengine/godot-proposals/issues/8125 

I'm consolidating this proposal as a result. Thank you for sharing your thoughts nonetheless. There's even a [PR implementing this](https://github.com/godotengine/godot/pull/83608).

**Closed by Mickeon** 2024-09-22 19:05 UTC
Labels: topic:editor
