### ISSUE TITLE
Improve exported variable organization

### ISSUE THREAD

**Issue by Duroxxigar** [godotengine/godot-proposals#3500] opened 2021-11-05 01:41 UTC
### Describe the project you are working on

Pretty much any game in Godot

### Describe the problem or limitation you are having in your project

It is currently quite cumbersome to organize your exported variables. You need to have the script as a tool script, as well as override _get_property_list and then add some properties there. There is a lot of boilerplate with this. Especially when you need to also override _get and _set as well. And that is so that we can organize our variables with categories and collapsible sections like in this screenshot

![image](https://user-images.githubusercontent.com/16636969/140443655-3086a27d-2595-48ba-bafa-cc7d307a9048.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose that we move this kind of functionality into the new annotations in GDScript 2.0. Not too sure how it works under the hood just yet however.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I propose that the team looks into a more user friendly approach. With GDScript 2.0, we can use the annotations to handle this. This would be the proposed syntax.

```
@export(category=character, section=movement)
var move_speed
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It would be used quite frequently as exporting variables is a pretty common thing to do.

### Is there a reason why this should be core and not an add-on in the asset library?

GDScript exports

**Comment by KoBeWi** [comment] 2021-11-05 01:46
Duplicate of #3451

**Closed by KoBeWi** 2021-11-05 01:46 UTC
