### ISSUE TITLE
Expose various get_X_path methods of OS

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-proposals#2887] opened 2021-06-19 06:51 UTC
### Describe the project you are working on

A tool.

### Describe the problem or limitation you are having in your project

I want to save files in the `.config` folder, but the function that gives me that path on all platforms, `get_config_path`, is not exposed.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Expose `get_config_path`, `get_data_path` and `get_cache_path`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I see two solutions; one would be to add it to the `OS.SystemDir` enum, which could be used like this:

```gdscript
OS.get_system_dir(OS.SYSTEM_DIR_CONFIG)
```

The second would be to just add getter functions like for `get_user_data_dir()`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can, but accommodating every platform is very tedious.

### Is there a reason why this should be core and not an add-on in the asset library?

It's about exposing core functions.

**Comment by Calinou** [comment] 2021-06-19 06:54
Duplicate of https://github.com/godotengine/godot-proposals/issues/2696.

**Closed by Calinou** 2021-06-19 06:54 UTC
