### ISSUE TITLE
Exposing Inertia Tensor to GDScript

### ISSUE THREAD

**Issue by yrk06** [godotengine/godot-proposals#1114] opened 2020-06-24 03:19 UTC
**Describe the project you are working on:**
A VR Exploration game for Godot with physics interactions

**Describe the problem or limitation you are having in your project:**
There is no way to rotate a RigidBody accurately using apply_torque

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The Feature would be to Expose the Moment of Inertia, in order to let rigid body rotations to be more controlled. 
This way, we could use formulas such as `t = I * a` in order to calculate the torque for the desired angular acceleration

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

This could be implemented in a member variable for the RigidBody
A very simple example would be as the formula stated above: `var t = myRigidBody.inertia_tensor * desired_acceleration`

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

It can be worked around, but the script has to consider the object's shapes and also offsets. Besides, the engine already calculate this for the Physics to run.

**Is there a reason why this should be core and not an add-on in the asset library?:**

The fact that the engine is already doing the calculation is the reason that this feature should be in the core and not in the addons

**Comment by Calinou** [comment] 2020-06-24 07:04
See also https://github.com/godotengine/godot/issues/2125 where this was requested a while ago.

**Comment by yrk06** [comment] 2020-06-24 16:59
There is also another kind of related proposal which is godotengine/godot-proposals#945

**Comment by Calinou** [comment] 2020-06-24 17:43
I'll close this as a duplicate of #945 then :slightly_smiling_face:

**Closed by Calinou** 2020-06-24 17:43 UTC
Labels: topic:physics
