### ISSUE TITLE
Limit re-arranging ordering and numbering of sub-resources in tscn files

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#2342] opened 2021-02-24 09:35 UTC
### Describe the problem or limitation you are having in your project
I have to be honest, I'm not exactly sure of the trigger point, but observe the image below. I made a minor tweak to a single property, but as you can see the resources have completely changed IDs, but none were touched in the editor.

When I cross check, nothing has actually changed, all items are there, their locations are the same (i.e. literally nothing has updated any of my nodes in the scene), just the editor has completely re-ordered the numbers, making version control and change management close to impossible.

![image](https://user-images.githubusercontent.com/12863685/108979668-cc478f80-7682-11eb-88a2-ed6e8114f1af.png)

![image](https://user-images.githubusercontent.com/12863685/108979936-12045800-7683-11eb-96e9-d5ef335ac806.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Do not rearrange sub resource and resource ids in a scene file when nothing needs to be changed.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Sorry, I have no idea, I do not know the internals of Godot, but clearly there's a reason for re-ordering but as stated, whatever it is seems to be a bit over-zealous...

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
Change control is paramount. Updating a single property should not result in entire file changes.

**Comment by KoBeWi** [comment] 2021-02-24 11:45
Duplicate of #471

**Closed by KoBeWi** 2021-02-24 11:45 UTC

**Comment by chucklepie** [comment] 2021-02-24 12:20
Thanks. Sorry, I do search for these things prior but nothing ever turns
up. The search facility in github is awful as I don't think it's me 😁

**Comment by chucklepie** [comment] 2021-02-24 12:24
Actually, sorry, how is this a duplicate? That duplicate is about using a
different number scheme for ids. My suggestion is about stopping the entire
file from being rearranged for no reason in the tscn...

**Comment by KoBeWi** [comment] 2021-02-24 12:26
It solves the same problem. You can comment on that proposal with your idea.
