### ISSUE TITLE
Allow using an arbitrary external editor for C#

### ISSUE THREAD

**Issue by dmitsuki** [godotengine/godot-proposals#6407] opened 2023-03-02 19:04 UTC
### Describe the project you are working on

A godot project using mono 

### Describe the problem or limitation you are having in your project

Sometimes I need to use Godot scripts, and generally I use c# scripts. I would like to open C# scripts in a separate editor to GDscripts. Godot already has this functionality, but if you are not using the "built in" dotnet editors, you cannot use this functionality. Because of LSP's,  you can edit C# in any editor, so you should be able to specify an external editor in the same way you do in "external editor." 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If another option is added that is exec command, the same as in the  base editor config, you could specify your own editors if you do not use one of the built in editors for the feature. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a "custom" or "userset" variable to the enum for EditorID's, and have it run a stored configuration. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As far as I know, this cannot be worked around using an editor plugin. 

### Is there a reason why this should be core and not an add-on in the asset library?

This is about making the code editor functionality behave "expectedly." The feature already exist in Godot, but with this specific configuration it seems there was an oversight.

**Comment by Calinou** [comment] 2023-03-02 20:42
Duplicate of https://github.com/godotengine/godot-proposals/issues/5760.

**Closed by Calinou** 2023-03-02 20:42 UTC
Labels: topic:editor, topic:dotnet
