### ISSUE TITLE
Show the highlight on MeshInstance when using arrow keys on keyboard to select it

### ISSUE THREAD

**Issue by chalcosoma** [godotengine/godot-proposals#1043] opened 2020-06-11 23:38 UTC
Edit: edited for clarity

**Describe the project you are working on:**
A 3D spaceship game.

**Describe the problem or limitation you are having in your project:**
(I'm talking about the Godot Editor) 
I have many MeshInstance nodes that I need to change position, rotation, and scale. I'm reusing some meshes and making duplicates so my hierarchy is very messed. When I use arrow keys on my keyboard to navigate, I can't see the MeshInstance highlight that occurs normally if I click instead. It confuses me a lot because for me it is faster to duplicate many meshes to prototype my spaceship models (some of them are huge and have a lot of nodes) and don't rename or order them, so I need to see what is the node selected but it doesn't show the highlight. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I want to see the current MeshInstance highlight when using up and down arrow keys. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Just select the MeshInstance in the editor using up and down and show the highlight (like when I click) it on editor viewport.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I think it is very useful and standard behavior so it needs to exist in the engine. And it will be used very often.

**Comment by Calinou** [comment] 2020-06-12 07:31
Selecting meshes can be slow if they have a lot of materials assigned, so I'm not sure if this is a good idea.

**Comment by chalcosoma** [comment] 2020-06-13 18:00
It does not need to select exactly the mesh. Only show a highlight at the corners as it does when you click to select.

**Comment by Calinou** [comment] 2021-09-01 21:08
Duplicate of https://github.com/godotengine/godot/issues/36291.

**Closed by Calinou** 2021-09-01 21:08 UTC
Labels: topic:editor
