### ISSUE TITLE
Shader interoperability - add GLSL preprocessor (or subset of such or some other GLSL compliant way to do conditional compiling)

### ISSUE THREAD

**Issue by hevonen** [godotengine/godot-proposals#1736] opened 2020-10-27 10:50 UTC
**Describe the project you are working on:**
I'm working on fragment shaders in VSCode with Shadertoy syntax and plugin for instant visual feedback and for editor I prefer (without full game engine overhead). In the end these shaders will run in Godot (as dictated by the project). I'm not Godot developer (or developer in general) but more like an artist working with shader code for a project.

I'd prefer to work on a single shader file that compiles in both Godot and VSCode/Shadertoy.
edit: E.g. feeding uniform floats with default values for Godot and regular floats with matching names for Shadertoy.

**Describe the problem or limitation you are having in your project:**
I found out that Godot doesn't support shader preprocessor so I would need to port the shaders for every test in the engine duplicating files and complicating workflow. If I could detect environment the shader is run in e.g. with TIME/iTime I could declare uniforms/variables (and other execution) to match either. Then my changes inside Godot (for e.g. vertex shader) would work in VSCode and changes inside VSCode (for e.g. fragment shader) would work in Godot.

I would prefer to set these once and then forget them instead of commenting/uncommenting lines for every test in engine or use cpp with #define between VSCode and Godot to generate intermediate files (as then I would lose the back/forth connection).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If Godot would support GLSL preprocessor directives I could have a single file and automated workflow. This would allow compatibility between Godot and Shadertoy. As I'm not a developer I don't know if what I want to do (mainly declaring shader uniforms instead of floats conditionally) is possible some other way - it seems it is not?

In addition this could also allow shader interoperability with other GLSL-style environments apart from Shadertoy.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
It would work like typical GLSL (C) preprocessor or a subset of such allowing #ifdef #else #endif. This would allow me to work around the differences between Shadertoy and Godot.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't know - I'm not a programmer and I have no experience in Godot. But I would like this to be transparent to me.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I guess not, but I'd like it to be transparent to the end user (me) so it at least would seem that Godot supports GLSL preprocessor.

**Comment by Calinou** [comment] 2020-10-27 11:06
Duplicate of https://github.com/godotengine/godot-proposals/issues/944.

**Closed by Calinou** 2020-10-27 11:06 UTC
