### ISSUE TITLE
Let `get_class()` return Variant instead of String

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#2317] opened 2021-02-19 16:14 UTC
### Describe the project you are working on
Reaction game
### Describe the problem or limitation you are having in your project
I cannot get a **class** itself, I get the name of the class as type _String_ and so cannot use `is`. I try to do `if child is _class.get_class():` but the right operand of `is` is not of type class, it is a String.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
One could use the `is` keyword for that.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
`Variant get_class() const`
If one would really need the String of the class, one could just do `str(<Object.>get_class())`.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No.
### Is there a reason why this should be core and not an add-on in the asset library?
Yes, it is very useful.

**Comment by Calinou** [comment] 2021-02-19 16:54
Duplicate of https://github.com/godotengine/godot-proposals/issues/391.

**Closed by Calinou** 2021-02-19 16:54 UTC
