### ISSUE TITLE
ability to turn off tileset tres animations and particle systems in the godot editor at design time

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#1425] opened 2020-08-28 16:21 UTC
**Describe the project you are working on:**
large platform game

**Describe the problem or limitation you are having in your project:**
When in the editor every tile animation (tres file) is playing and every particle is running (perhaps this is the same for non-tilemap tres animations, I don't use them). 

On a very large map, this is crippling performance and editing ability as every single one is running and making the editor too noisy to view. In game I have a game manager that enables/disables everything so not a problem at run time. Particles are sometimes embedded inside nested nodes or scenes and difficult to easily make disabled/not visible.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It would be nice to be able to have the godot editor stop tilemap tres animations from running and optionally not have particle systems being ran unless we really want to see them in the editor. This is more pertinent in large tilemaps where you can have hundreds of animated tiles and particles on the go.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
on/off switch please :)

**Is there a reason why this should be core and not an add-on in the asset library?:**
tilemaps seem to get no love in Godot despite being the most used, adding more functionality will only make it better :)

**Comment by Zireael07** [comment] 2020-08-28 16:26
Related to #942?

**Comment by chucklepie** [comment] 2020-08-28 16:28
How do you people find these :)

I do search before I create. However, I can edit to remove the 'particle' bit and leave the tres to make it a unique suggestion?

**Comment by Zireael07** [comment] 2020-08-28 18:08
I had the advantage of being the creator of the other issue. I think they can both stay, they are only related, not duplicates - but a solution to one will likely fix (or make fixing easier) the other one too.

**Comment by Calinou** [comment] 2020-08-29 00:01
Duplicate of https://github.com/godotengine/godot-proposals/issues/942. (The underlying issue is the same.)

**Closed by Calinou** 2020-08-29 00:01 UTC

**Comment by chucklepie** [comment] 2020-08-29 09:36
Well, I guess I'll try to see if we can update 942 because it doesn't mention animated tres files.
