### ISSUE TITLE
TextEdit should syntax highlight symbols

### ISSUE THREAD

**Issue by BenStigsen** [godotengine/godot-proposals#1420] opened 2020-08-27 15:33 UTC
**Describe the project you are working on:**
Something that requires the `TextEdit` node to highlight symbols

**Describe the problem or limitation you are having in your project:**
The `TextEdit` control node doesn't highlight symbols.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
A new function being added called `add_symbol_color()` or symbols being accepted in `add_keyword_color()`. This could be used to create text editors that highlight symbols related to the game or for programming languages such as Brainfuck.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I'm not sure. Currently I just know that in the Godot Engine source code, all keywords are being added to a dictionary with an associated color, then it's the syntax highlighter that checks if the character is a symbol with `is_symbol()` where currently the only part where the expected return value is `true` is when highlighting ranges.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not as far as I know... I'm currently creating one myself with a `RichTextLabel` and constantly checking what the user input is, to then highlight it with a BBcode.

**Is there a reason why this should be core and not an add-on in the asset library?:**
The `TextEdit` node could be used for many many different projects, but it not being able to syntax highlight symbols makes it more limited.

**Comment by TheDuriel** [comment] 2020-08-27 18:45
There is a discussion on the main repos issue board somewhere. Specifically talking about making a clearer distinction between the TextEditor and the ScriptEditor, and making the latter a proper node. Can't find it anywhere as it was likely offtopic in another issue.

Right now TextEdit has a bunch of the base components of a ScriptEditor, but the vast majority of them needs re implementation in c++ if you were to use it.

**Comment by Airbus5717** [comment] 2020-09-06 02:35
i have a suggestion 
Add the ScriptEditor as a node in so we can use it for our projects

**Comment by Calinou** [comment] 2020-09-06 13:15
@Airbus5717 Doing so would increase the binary size noticeably even though very few people would make use of it.

**Comment by Airbus5717** [comment] 2020-09-06 15:45
hmm godot size is fine 
obv more features bigger size 
i like godot 
or if its possible to make some nodes installed from assets or so ?

**Comment by BenStigsen** [comment] 2020-09-06 15:50
What I don't understand is the difference between the ScriptEditor and TextEditor, I thought the Godot Engine was created with Godot. And all of the features in the TextEditor matches the ones in the ScriptEditor no?

Any wya, it wouldn't make sense to create an entirely new node when (at least from this issue) the only problem is highlighting symbols.

**Comment by Airbus5717** [comment] 2020-09-06 16:17
No there is alot of features in script editor not available in Texteditor node

**Comment by Calinou** [comment] 2020-09-06 16:40
> I thought the Godot Engine was created with Godot.

Indeed, the *editor* is made with Godot :slightly_smiling_face: Not all nodes are exposed to projects though. Some nodes are editor-only to keep export template binary sizes smaller.

**Comment by BenStigsen** [comment] 2020-09-07 06:26
What's the difference between the script editor and TextEdit node?

**Comment by Airbus5717** [comment] 2020-09-07 13:20
Hmm the TextEdit is in godot for projects use as a node 
ScriptEditor is the editor u use for coding godot projects in godot engine 

i am making a general purpose text editor you can look at the code 
https://github.com/Airbus5717/TextEditor

**Comment by Airbus5717** [comment] 2020-09-08 12:28
hmm i think i got it working in GDscript now 
Check here 
https://github.com/Airbus5717/TextEditor

**Comment by BenStigsen** [comment] 2020-10-16 19:18
I have a feeling that adding this would be relatively simple when looking at the C++ code. But I'm not comfortable doing this as I'm not too experienced with C++, and I'm even less experienced when it comes to using SCons and compilers.

**Comment by Calinou** [comment] 2021-08-14 01:49
Duplicate of https://github.com/godotengine/godot/issues/43706 (this is actually a bug).

**Closed by Calinou** 2021-08-14 01:49 UTC
Labels: topic:gui
