### ISSUE TITLE
increment or decrement numerical properties with up and down arrow keys

### ISSUE THREAD

**Issue by SilencedPerson** [godotengine/godot-proposals#3298] opened 2021-09-15 11:29 UTC
### Describe the project you are working on

a game

### Describe the problem or limitation you are having in your project

Often times i end up wishing i could change values with arrow keys, especially when working on notebook without access to numerical keyboard. Small number changes are a pain.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Pressing arrow key should increment or decrement selected numerical property.
I would also welcome same feature with mouse wheel scrolling but that is not as vital when using a notebook.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. User click the property
2. Presses a `Up Arrow key`
3. Selected property gets incremented by 1
4. If the property is a real number, the part behind the floating point stays the same, only the number before it is changed

Modifier keys like `shift `and `alt` could be added for floating point values.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's a major paper cut when working with numbers inside inspector properties

### Is there a reason why this should be core and not an add-on in the asset library?

it's a change to a vital parts of the editor

**Comment by Calinou** [comment] 2021-09-15 15:47
Duplicate of https://github.com/godotengine/godot-proposals/issues/2099.

**Closed by Calinou** 2021-09-15 15:47 UTC
Labels: topic:gui
