### ISSUE TITLE
Add self-contained mode for exported games

### ISSUE THREAD

**Issue by Ryhon0** [godotengine/godot-proposals#3838] opened 2022-01-21 13:40 UTC
### Describe the project you are working on

Simple game that relies on persistent data

### Describe the problem or limitation you are having in your project

Exported games do not have an option to save `user://` data in the same folder as the game executable 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a self-contained mode, just like the editor already has

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If a file named `._sc_` or `_sc_` is present in the directory with the game executable, the `user://` path will be stored in a `data` directory, where the executable is located

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around by using the host filesystem instead of the `user://` path

### Is there a reason why this should be core and not an add-on in the asset library?

To my knowledge, `get_data_path()` cannot be overridden using an add-on

**Comment by Calinou** [comment] 2022-01-21 13:51
Duplicate of https://github.com/godotengine/godot-proposals/issues/2474.

**Closed by Calinou** 2022-01-21 13:51 UTC
