### ISSUE TITLE
Built in Pixel make/ editor

### ISSUE THREAD

**Issue by Cosmic-Whale** [godotengine/godot-proposals#4424] opened 2022-04-21 23:53 UTC
### Describe the project you are working on

Users being able to do pixel art within godot like gamemaker.

### Describe the problem or limitation you are having in your project

Users will be able to easily do pixel art all within godot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Being able to do pixel art all within godot will allow users to not install 3rd party software, and it helps productivity.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Have the user be able to edit an existin sprite by right clicking it and selecting the option to edit it.

If the user wants to create a new sprite right click on the node create a 2d sprite node and be able to edit it or shortcut: crtl + alt + m.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If user does not wants this feature implemented it also can be an editor plugin.

### Is there a reason why this should be core and not an add-on in the asset library?

Ease of use already being there.

**Comment by Cosmic-Whale** [comment] 2022-04-21 23:53
first request so might explaining might be pretty bad.

**Comment by luiq54** [comment] 2022-04-22 06:41
There is already this [plugin](https://github.com/SoloCodeNet/godot-sprite-editor-addon) that lets you make sprites in editor. 
A fully featured art editor is out of scope for godot in my opinion. You can always try external programs like Pixelorama and  Aseprite and they also have accompanying importer plugins to speed up workflow like [this one for pixelorama](https://godotengine.org/asset-library/asset/802) and [this one for aseprite ](https://godotengine.org/asset-library/asset/713)

**Comment by Calinou** [comment] 2022-04-22 12:54
Duplicate of https://github.com/godotengine/godot-proposals/issues/3728.

**Closed by Calinou** 2022-04-22 12:54 UTC
Labels: topic:editor

**Comment by rainlizard** [comment] 2022-04-23 08:01
Strongly recommend Aseprite and the Aseprite Wizard plugin.

The animation and layer system, plus importing a .aseprite file as layers, is really powerful. Having a AnimatedSprite node for each layer gives you a lot of flexibility, easily swapping out limb animations, heads, equipment, whatever, by simply hiding or showing the nodes.

I previously used GameMaker too, but this workflow seems better than any built-in sprite editor.
