### ISSUE TITLE
Copy-Paste keyframes from one track to another

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot-proposals#302] opened 2019-12-13 19:42 UTC
**Describe the project you are working on:**
Creating a level editor

**Describe the problem or limitation you are having in your project:**

tried to copy and paste the keyframes from track A to B , but it is not possible

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

this will speed the development process

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
there is no needed
**Describe implementation detail for your proposal (in code), if possible:**
not code
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
yes, you can do this by editing the .tres file and copying these lines: 
`"times": PoolRealArray( 0.16, 0.32, 0.41, 1.33, 1.43, 1.48, 1.84, 1.9, 1.97, 2.45, 2.52, 2.59, 2.95, 3, 3.08, 3.25, 3.3, 3.39 ),
"transitions": PoolRealArray( 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ),
"update": 0,
"values": [ 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, 0.4, 0.0 ]
`

**Is there a reason why this should be core and not an add-on in the asset library?:**
its a basic feature

**Comment by golddotasksquestions** [comment] 2019-12-14 22:26
This is a duplicate of https://github.com/godotengine/godot/issues/27279

I think it would be worthwhile to discuss what should happen when with the keyframe values, other than their position on the timeline.
Personally I would expect the other values also to be copied into the clipboard, however these values should only be pasted if the track the user tries to paste into is compatible. If the track is of a type that is incompatible with the value data in the clipboard, only the timeline values of the keys are pasted. (for instance if the user tries to copy keys from a scale track into a method track or some other track that does not have Vector2 values)

Also very much related: https://github.com/godotengine/godot/issues/27280

**Comment by Calinou** [comment] 2019-12-14 22:43
@golddotasksquestions We'll keep this proposal open as it was opened on the proposals repository.

**Comment by aXu-AP** [comment] 2022-02-25 19:15
This is something I time to time notice myself wanting. Especially when making walking animations, where you could copy and offset animation from one half to another.

**Comment by YuriSizov** [comment] 2022-07-21 16:02
We've discussed this in a proposal review meeting, and we're fine with the idea. It may be hard to implement for different property types, so if anyone wants to implement it, they need to be careful. We can start with supporting compatible types only, but make sure that the UX is clear regarding where you're copying from and where you're copying too.

**Comment by Calinou** [comment] 2023-01-26 00:35
Closing in favor of https://github.com/godotengine/godot-proposals/issues/3419, which is more detailed.

**Closed by Calinou** 2023-01-26 00:35 UTC
Labels: topic:editor, topic:animation, implementer wanted

**Comment by dant00ine** [comment] 2024-08-11 05:27
One thing that could help the UX pitfall of re-structuring nodes breaking the animation player tracks is to allow changing the reference node for the animation tracks; if it has all the same properties, the keyframes could just be applied to that new node

**Comment by Zireael07** [comment] 2024-08-11 11:30
This is closed, please comment on the other issue
