### ISSUE TITLE
Reworked Inverse Kinematics

### ISSUE THREAD

**Issue by Miniblu858** [godotengine/godot-proposals#746] opened 2020-04-23 21:56 UTC
**Describe the project you are working on:**

Currently unknown, however, it will feature a third person character.

**Describe the problem or limitation you are having in your project:**

As of right now, the IK systems of Godot are barely usable. The only scenarios where IK can be used is when holding a weapon or an action that is unrelated to the player's animation. Yes, this is one of the use cases of IK, however, Godot features no animation mixing for the IK systems. Enabling IK will just override the AnimationTree's animation. This means:
-No IK Foot placement with walk animations
-No IK climbing hand placement
-Head/looking will completely override any breathing animations etc.

All of these have been done in games that were released before even the 2000s, so it makes sense that Godot has these.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

This would allow, for example, walk cycles to be adjusted based on the slope of the floor below. This is a basic feature that is included in every proper 3rd person character since >2000

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Simply an animateable blend slider that blends the IK to the AnimationTree, 1 being fully IK, and 0 being only animation-driven.

EDIT: I want to further add to this. As #750 says, there should be a Mix mode(which is what I explained above) and an Add mode which adds to the existing animation.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No, because of the start() function in the IK node completely overrides the AnimationTree's animation.

**Is there a reason why this should be core and not an add-on in the asset library?:**

As mentioned above, this is a basic feature that is used universally in 3rd person games.

**Comment by Calinou** [comment] 2020-04-24 13:02
> All of these have been done in games that were released before even the 2000s, so it makes sense that Godot has these.

As far as I know, games didn't use IK in the 90s. Animation blending was a thing, but it either relied on multipart models (id Tech 3) or forward kinematics in skeletal animation (id Tech 4, Source).

**Comment by Miniblu858** [comment] 2020-04-24 14:23
Ocarina of time(1998) and other n64 games were able to achieve this.
![Capture](https://user-images.githubusercontent.com/64223696/80222939-a3b4ca80-8658-11ea-9d5b-55c257d07719.JPG)

**Comment by groud** [comment] 2020-04-24 14:51
>  Godot features no animation blending for the IK systems. 

I am not a 3D animation expert, but this video clearly show that this is possible: https://www.youtube.com/watch?v=Q4o_7_Rh510

Honestly, without more details on the proposal and research on your side, this proposal is likely going to be closed...

**Comment by Miniblu858** [comment] 2020-04-24 15:32
> > Godot features no animation blending for the IK systems.
> 
> I am not a 3D animation expert, but this video clearly show that this is possible: https://www.youtube.com/watch?v=Q4o_7_Rh510
> 

I really hope you read my post. In the example you listed, there is no animation on the skeleton, only the IK. The feature I requested is 

> Simply an animateable blend slider that blends the IK to the AnimationTree, 1 being fully IK, and 0 being only animation-driven.

**Comment by groud** [comment] 2020-04-24 15:41
> I really hope you read my post. In the example you listed, there is no animation on the skeleton, only the IK. The feature I requested is

Maybe I misunderstand something in your post, but this clearly show that you can mix an animation (the idle movement) and the IK target : https://youtu.be/Q4o_7_Rh510?t=41

Also, from what I see from the [class reference](https://docs.godotengine.org/en/3.1/classes/class_skeletonik.html), there is an "interpolation" float property in the SkeletonIK node. This pretty looks like what you would need to mix your IK with your animation.

**Comment by Miniblu858** [comment] 2020-04-24 15:51
> Maybe I misunderstand something in your post, but this video clearly show that you can mix an animation (the idle movement) and the IK target in the same skeleton : https://youtu.be/Q4o_7_Rh510?t=41

The idle animation does not play on the bones where IK is enabled.

> Also, from what I see from the [class reference](https://docs.godotengine.org/en/3.1/classes/class_skeletonik.html), there is an "interpolation" float property in the SkeletonIK node. This pretty looks like what you would need to mix your IK with your animation.

The interpolation property may have been intended to work as a animation/IK blender, however it doesn't. All it does is makes the IK take more time to respond to updates in the Target node's transform.

**Comment by groud** [comment] 2020-04-24 15:56
> The interpolation property may have been intended to work as a animation/IK blender, however it doesn't. All it does is makes the IK take more time to respond to updates in the Target node's transform.

Ok, I guess might be a bug. Or maybe I misunderstand what is it supposed to do. 
@AndreaCatania could help us on this ? Is it possible to mix animation with SkeletonIK ?

**Comment by Miniblu858** [comment] 2020-04-24 16:00
I'll try to explain it better. Here is a bone chain using 100% IK (as you can see it is using the target)
![1](https://user-images.githubusercontent.com/64223696/80232442-f8ab0d80-8665-11ea-9b54-68f950401cb2.JPG)
Here is the bone chain using 0% IK (using animation)
![2](https://user-images.githubusercontent.com/64223696/80232453-fd6fc180-8665-11ea-8880-db56fab07149.JPG)

**Comment by NHodgesVFX** [comment] 2020-04-25 04:22
so what you want is additive animation? Instead of IK overriding the animation it adds onto it.  For example like this https://forum.unity.com/threads/adding-ik-to-the-legs-without-affecting-underlying-animation.550930/

**Comment by Miniblu858** [comment] 2020-04-25 07:49
> so what you want is additive animation? Instead of IK overriding the animation it adds onto it. For example like this https://forum.unity.com/threads/adding-ik-to-the-legs-without-affecting-underlying-animation.550930/
> 
> I also opened my own issue for IK and physical bone improvements as I think a couple more features should be added in addition to blending. #750


Yes exactly. Your post also proposes bone constraints which had completely flown over my head when writing my post, but is also extremely important for any good physical animation or IK system.

**Comment by Miniblu858** [comment] 2020-04-25 08:00
Upon further research, I think Godot's IK system needs to be reworked. Apparently in this post https://github.com/godotengine/godot/issues/38183 The IK system has been broken since 3.2.1 - so why include an IK system in the engine if it doesn't work?

**Comment by NHodgesVFX** [comment] 2020-04-25 08:15
Yeah I posted that when I noticed IK was broken. The problem is reduz reworked the skeleton code and it kinda broke IK and some other stuff. https://github.com/godotengine/godot/issues/32637

**Comment by Miniblu858** [comment] 2020-04-25 08:37
> The last version where IK worked was 3.1 unfortunately
> 
> The IK docs were from a past version of Godot that didnt have any built in IK support. Yeah, looking at it now the tutorial seems incomplete?

Looking at all these posts, the IK in godot really needs to be redone.

https://github.com/godotengine/godot/issues/23630
https://github.com/godotengine/godot/issues/38183
https://github.com/godotengine/godot/issues/25544
https://github.com/godotengine/godot/issues/34415
https://github.com/godotengine/godot/issues/38026
https://github.com/godotengine/godot/issues/37095
https://github.com/godotengine/godot/issues/35035

**Comment by AndreaCatania** [comment] 2020-04-26 17:29
This seems like a bug if confirmed.

The IK is using the FABRIK algorithm that does its best when combined with the animation. Its currently possible blend the IK with an animation / pose using the `interpolate` parameter.

Recently, I did a fix that make the `interpolation` parameter work again. Maybe you just need to test a version that includes that: https://github.com/godotengine/godot/pull/37272/files

If it still doesn't work, please open an issue and add a sample project; I'll give it a check.

**Comment by Miniblu858** [comment] 2020-04-27 09:48
> Recently, I did a fix that make the `interpolation` parameter work again. Maybe you just need to test a version that includes that: https://github.com/godotengine/godot/pull/37272/files


Excellent! in newer versions of Godot the interpolation slider is fixed. My proposal still stands, an Add mode and a constraints system would polish this IK system.

**Comment by groud** [comment] 2020-04-27 10:44
Alright, I am closing this issue since the feature is the original post is already there and the bug was fixed.
@Miniblu858 if you wish so, you can open another proposal stating the limitations of the current system and how if could be improved to be "more polished". (unless this is already covered by #750)

**Closed by groud** 2020-04-27 10:44 UTC
Labels: topic:core
