### ISSUE TITLE
Warn if script inheriting tool script isn't tool

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#754] opened 2020-04-26 10:28 UTC
**Describe the project you are working on:**
A complex metroidvania game.

**Describe the problem or limitation you are having in your project:**
I use tool scripts a lot in my project, because they are handy to update a scene based on exported properties. For a particular example, I have a class (with `class_name`) called NPC, which has basic interaction code and uses `tool` for updating sprite based on a variable. However the base NPC is little useful, so each NPC inherits it and provides own interaction code.

My problem is that the inheriting script must be a tool too. I've ran into this multiple times already - when you inherit tool script, the inheriting script must be explicitly tool too or it won't work as such. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I forgot to enable it few times and it caused some confusion, so I thought that a warning when inheriting script doesn't have `tool` keyword would be useful. This way instead of wasting few minutes trying to figure out why the script behaves weird, you could just see that you forgot to make it `tool`.

Alternatively we could make the inheriting script automatically be a tool.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
If a script inherits tool script, warn if it doesn't have `tool` keyword too. It would be a standard warning, so someone could disable it if their action was intended.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Inheriting tool scripts might not be a very common operation, but there's no way to work around my problem.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Impossible to make plugin for this.

**Comment by volzhs** [comment] 2020-04-26 10:56
> Alternatively we could make the inheriting script automatically be a tool.

Vote for this

**Comment by Error7Studios** [comment] 2020-04-29 15:06
Another issue with tool scripts is that if they call a function on a singleton that isn't a tool, you get an error message like:
`res://Main.gd:8 - Invalid call. Nonexistent function 'foo' in base 'Node (my_singleton.gd)'.`

Making the singleton a tool solves the problem, but it's easy to forget to do this, so a warning would be helpful.

Export variable `setget` functions like this will trigger the error above (if the singleton isn't a tool):

```
export(int) var my_num := 1 setget set_my_num

func set_my_num(__num: int) -> void:
	my_num = __num
	MySingleton.foo()
```

**Comment by vnen** [comment] 2020-05-15 21:38
> Alternatively we could make the inheriting script automatically be a tool.

I'm not fond of making stuff automatically, because it would cause the opposite problem: "Why are my scripts being executed in editor since I didn't mark them as `tool`?".

Also, it's not clear from the script perspective what is meant to be executed in the editor or not, so it gets tricky to provide more contextual warnings without being annoying.

**Comment by KoBeWi** [comment] 2020-05-15 21:44
But it's about the case where base script is tool. It makes sense that inheriting should be tool too. It's not that common and it shouldn't confuse anyone.

**Comment by me2beats** [comment] 2021-02-12 07:19
Are there cases when it's useful to have a tool parent class and non-tool child one at all?
Because if not, maybe it is better to raise an error, not just a warning.

**Comment by Jummit** [comment] 2021-02-12 07:44
> Are there cases when it's useful to have a tool parent class and non-tool child one at all?
> Because if not, maybe it is better to raise an error, not just a warning.

I have a plugin where I have a base component that is a tool script, but if the user extends it he does not necessarily need it to be a tool.

**Comment by me2beats** [comment] 2021-02-12 08:08
> I have a plugin where I have a base component that is a tool script, but if the user extends it he does not necessarily need it to be a tool.

Then option B
> Alternatively we could make the inheriting script automatically be a tool

does not seem to be suitable, moreover, it would increase the complexity when reading the code, because you will have to look for the `tool` line not only in current script, but in all parent scripts to check if the script is a tool

So I think warning is a better option

**Comment by PLyczkowski** [comment] 2021-05-15 18:38
> Alternatively we could make the inheriting script automatically be a tool.

^ I support this notion. In all languages if you are inheriting from a class, you are inheriting everything. In GDScript, you inherit everything except one thing - not really intuitive.

In my case I want to generate card descriptions via editor tool from their components. Not really fond of the idea of remembering to write 'tool' on every one - that's the kind of thing inheritance is for.

**Comment by levilindsey** [comment] 2021-07-27 15:34
Is there any way to programmatically check whether a script is marked as a `tool`?

I'm having the same problem, and my first thought was to have the parent `tool` class somehow check the metadata of the child class and assert that it is `tool`.

**Comment by me2beats** [comment] 2021-07-27 17:35
> Is there any way to programmatically check whether a script is marked as a `tool`?
Sound good for a separate feature proposal imo

**Comment by levilindsey** [comment] 2021-07-27 18:34
I started drafting a proposal for this, but then I found that there is already an API for `Script.is_tool()`!

https://docs.godotengine.org/en/stable/classes/class_script.html#class-script-method-is-tool

So I think we have a pretty decent work-around for this:
```
tool
class MyParent
extends Node


var _configuration_warning := ""


func _ready() -> void:
    _validate()


func _validate() -> void:
    var script: Script = get_script()
    while script != null:
        if !script.is_tool():
            _configuration_warning = \
                    "Subclasses of `MyParent` must be marked as `tool`: %s" % 
                    script.get_instance_base_type()
            update_configuration_warning()
            return
        script = script.get_base_script()


func _get_configuration_warning() -> String:
    return _configuration_warning
```

```
class MyChild
extends MyParent
```

However, I still think that this proposal makes a lot of sense, and will be helpful for most folks.

**Comment by levilindsey** [comment] 2021-07-27 19:43
:/ Actually, I think my work-around doesn't actually work, as-is.

Because the child class isn't a `tool`, none of the parent logic actually executes in the editor environment!

I think that updating my example to use `assert(script.is_tool())` might be more useful, since at least we should then notice the problem when running the game.

**Comment by Flavelius** [comment] 2022-03-31 16:29
> :/ Actually, I think my work-around doesn't actually work, as-is.

This is kind of sad funny because it tries to solve a problem while the problem blocks the solution.

My +1 for inheriting tool, as that's what inheritance is for, inheriting functionality and being bound by what requirements are presented. Tool is a declaration of a requirement that should not be broken by godot, it works against the intention of the programmer. Breaking functionality is what should be explicit intention, not the other way round.

**Comment by PrinceMerluza** [comment] 2022-06-27 07:05
> > Alternatively we could make the inheriting script automatically be a tool.
> 
> I'm not fond of making stuff automatically, because it would cause the opposite problem: "Why are my scripts being executed in editor since I didn't mark them as `tool`?".
> 
> Also, it's not clear from the script perspective what is meant to be executed in the editor or not, so it gets tricky to provide more contextual warnings without being annoying.

Hmm, that's a hypothetical scenario but I just had an actual scenario where I'm thinking why isn't my script which I purposely and knowingly inherited from a tool script not a tool script. Imo, it's more confusing not having it automatic. Now I have to keep it in my head that not everything is inherited, and what else could be exceptions in the future of gdscript inheritance.

+1 for automatic child tool unless like the other ones mentioned, there's a use case where inheriting from a tool script and not wanting it to be a tool makes sense.

**Comment by YuriSizov** [comment] 2022-06-27 08:18
There is a use case. Now, I haven't tried this pattern in action, but I had that idea recently, that it might be practical to have two scripts when you need to add editor-only logic to your node. A base script would be a tool script with configuration warnings and property list method, and the extending script, and the one you actually assign to the node, is going to be a normal script.

This is a bit of a trick to work around other Godot limitations. But since a proper fix to those would be to allow per member/method tool declarations, this idea for an automatic solution would still be redundant.

**Comment by Flavelius** [comment] 2022-06-27 10:24
|  to have two scripts

Maybe i don't understand, but does that suggest needing to swap those scripts before building?
But either way, the idiomatic way to separate editor-only logic in c# atleast is to use `#if defines` which are very common. gdscript probably has a similar concept.
In an ideal world, godot would do this in a similar way to unity, expose certain methods baseline to the editor (in unity Reset(), OnDrawGizmos(), OnValidate()) and for more advanced usecases use separate editor-scripts that decorates it. 
But that would entail a few more awesome improvements that are unlikely to be implemented like managed objects always being available for type checks (even without tool) where property getters/setters execute when used etc. (basically the flexibility in unity)

**Comment by Flavelius** [comment] 2022-06-27 16:57
I have to disagree with the last statement. This is basically how inheritance fundamentally works, and especially in c# and rightfully so, else it would break functionality of the one supplying the base (as it currently does). Commonly, all implicit functionality that a base class supplies is expected to work without knowing every detail about it (this is basically every usage of external libraries). The editor here is just another invoker of expected callbacks.

> when you don't remember every little caveat like that

When one designs a class that expects to validate properties or mutate data in some other way to ensure correct execution, it's even worse. Because the resulting problems will only be visible at runtime, addons might not even work and users might not even be aware of their error because all validation feedback is implicitly disabled/hindered too (adding a warning still doesn't make the user aware of the caveats you speak of (in both ways), for that one would have to dive into every source code, so it doesn't directly address this concern; not even speaking of having toggled off warnings or them being drowned inbetween others).
I can see why this might be a problem with gdscript with its reduced functionality and simpler editor feedback/deep inspection functionality, but i'd rather see this being addressed on language level. C# for example has quite some functionality and idiomatic rules for this; for example members can be sealed, virtual (and then are expected to be base-called, but don't need to be) or abstract. This makes it so the base class can take responsibility for exposing certain callbacks/methods to inheritors or leaving it to the inheritor to decide. And this is way stronger (and cleaner) than implicitly causing breakage without feedback. It even violates the open-closed principle because it alters the behaviour of the base class without the base being explicitly designed for that.
I don't want to sound rude, and maybe there are valid reasons to oppose common conventions, in this case i just don't see them, and it contradicts what i learned and applied over decades.

**Comment by YuriSizov** [comment] 2022-06-27 18:04
Well, IMO it shouldn't break the behavior of the base class then. But it shouldn't make the extending class be something that is not declared in its script. What my decades taught me is that hidden behavior is harder to debug and track down. You can't trust the script. You have to consider options which are not present in your code and which you can only be aware of by the merit of prior knowledge.

What if someone else designed the base class? And as such you are not aware that it has editor-specific functionality? Implicit behavior would be a problem for you then, as you would be required to keep that possibility in mind, acquire that knowledge externally.

Which is why a warning is better. It tells you about the problem, instead of acting smartly and creating hidden functionality that you will have to untangle, were something go wrong.

The tool keyword, arguably, is not a part of OOP, of class' properties, so it cannot break OOP principles. It's a meta command for the editor. It's somewhere on the level of a preprocessor macro.

**Comment by Flavelius** [comment] 2022-06-27 19:30
In this case the tool keyword is more than meta info, it is actively dictating behaviour. If it was a preprocessor makro as in your example it would be equally bad, as the preprocessor then would not run, resulting in invalid code/behaviour (as is currently similar behaviour). 

> Which is why a warning is better. It tells you about the problem, instead of acting smartly and creating hidden functionality that you will have to untangle, were something go wrong

If it actually inherited the expected behaviour of the creator of the base class, there would be nothing to untangle as the script ran as intended. You're not inheriting from something random, you're inheriting from a class you know you want to inherit from to gain its functionality/behaviour.

> What if someone else designed the base class?

That is the argument for inheriting the tool behaviour, if you didn't know it required a certain behaviour godot shouldn't unknowingly & implicitly break it for you.
Maybe i'm misunderstanding your phrasing of implicit behaviour, but the way i understand it is that every piece of code that you can't fully audit has potential implicit behaviour; what if the library you're using writes to some log file somewhere, connects to the internet, replaces null-with-empty strings etc. is this actually something the non-conventional tool inheritance solves? I think this is a wholly different issue, if even.

But imagine the opposite, if the author of that library used language features to make this extended behaviour explicitly disable-able _while still keeping parts that are specifically required_; wouldn't that address everyones requirements (virtual/abstract/override)?
Even the alternative of an explicit tool-disabling keyword would be somewhat better. Someone who doesn't want a fully working baseclass could use it to break stuff willingly atleast.
Imo, godot atleast shouldn't implicitly break intended functionality, editor callbacks should be reliable/consistent.
Unity actually has a similar problem with its implicit callbacks; when you have Awake() or Start() etc in a base class, but also in an inheriting class, the base class' methods won't be called. This is why it became common to make those virtual in the base class, unity even does it everywhere in their packages. Meaning they use a language feature to work with this behaviour. If someone wants to break the behaviour of the baseclass, they can override and just not call base.Awake() etc. (even though there's literally no reason to do that).

**Comment by YuriSizov** [comment] 2022-06-27 20:28
All tool keyword does is tell the editor to load file when the scene is edited. That's it. It doesn't change the behavior of the script, only the behavior of the editor. It's not a functional part of the script.

You are right, and I am agreeing with you, that the functionality of the parent class, if it was a tool script, should still work. But I don't think that making the child script implicitly tool is the solution. Because yes, you want the parent functionality to be intact, but you also don't want your own extended functionality to work in a way that you didn't code. Parent class is tool, it should remain tool, it should work. Child class is not tool, was never written to do anything in the editor, it should not be tool. If the child class is intended to run its own logic in the editor, then it should, explicitly, be marked as tool.

This is about the logic beyond the script itself. It's about the meta level which is the editor logic for handling scripts. Ideally, it should load all tool logic from parent classes and should ignore all non tool logic from  child classes. That way the code works exactly as the programmer designed it to work. It works exactly as it is written.

But this is probably not feasible. And if it's not feasible, a warning is our next best solution. I think you want a solution that fits your own use-case, but in a generalized case implicit behavior leads to loss of control over your code. I personally want full control over it.

**Comment by Flavelius** [comment] 2022-06-28 05:49
That sounds understandable from the perspective of a maintainer, but as a user its the same reason why i inherit from EditorPlugin or any Editor type even which i also don't have to decorate with tool as i expect them to implicitly work as required. I only need to know that i can override certain methods to achieve what i want; how is that different to a user supplied class that provides the same? I would also still expect them to work correctly if i inherited my EditorPlugin inherited class. As i mentioned, from my experience (and observations in unity), relying on callbacks to not break is the default expectation. Explicit deactivation is still possible, or even just not inheriting a random class if you don't know that you need its functionality.
The implicitness in my eyes is not what poses the problem as i'm mainly using c# which allows providing indicators for inheritors and making inheritance safer by following good practices. And this may be where, if gdscript had similar features, i can see the problem becoming null.

What do you see as potential issues with inheriting a toolscript of a thirdparty library?

In my years of using unity, in which that is implicitly enabled everywhere and well established practice, i've not seen many cases of it actually destroying projects unrecoverably without users really trying to do unreasonable things. And this is similar to all godot editor interfaces telling you not to free any editor nodes as this will also break things. The possibility is still given to the user and i'd argue exactly because all the editor panels etc. are regular nodes it's what makes it familiar to work with and kind of powerful for extension. Ofcourse that comes with the mentioned downsides, but that's the tradeof of not expecting someone to willingly break the editor. And i've not yet seem someone actually doing that.

There are alternatives though, for example having the mentioned validation or gizmo-drawing callbacks (similar to unity) that are then the only places that are actively invoked at specific events by the editor. This would probably align with your vision of partially exposing tool logic.
For the case of validating propertes or printing log feedback or drawing gizmos these would suffice and with that probably cover most of the usecases anyway.

These, practically are my uses and i'd happily don't care whether godot does everything differently if only basic functionality like this was available as required/desired in any kind of form (that doesn't pose additional expectations on the inheritor of my (addon) classes).
Tool scripts were my workaround, but when things break in godot and my expectations don't align with what i get as result (maybe only as a c# coder) and the place where i find out why is a 2 year old open github issue, it confirms that the current behaviour is atleast not intuitive. I get that it's not changed because people fear potential complications. But potential complications are everywhere where an api provides powerful possibilities if functionality is misused, as mentioned.
Apart from that, the recent poll showed that almost 3/4 use version control, which indicates to me that those who do are somewhat versed in knowing the consequences of working against best practices or what it means to use thirdparty libraries/code.
And yes, c# currently has a share of only ~14%. I can see why that would be a reason to not introduce certain features into the language to bring it on par just to make editor functionality more safe.
There's the argument though that almost half of those who voted have a unity background, which means they know that this works just fine in unity and some like me may expect similarly powerful functionality when it comes to editor extension.

Then again, i also got some feedback in the c# channel, that others do align with your arguments and if they as users think that it's fine, it probably is.
In the end, i myself even likely don't care whether tool actually inherits -if there are alternatives; but a warning is not an alternative in this case, it's different behaviour / altered outcome.

**Comment by YuriSizov** [comment] 2022-06-28 10:17
> its the same reason why i inherit from EditorPlugin or any Editor type even which i also don't have to decorate with tool as i expect them to implicitly work as required.

Is this something special about you using C#? You **do have** to have `tool` in your `EditorPlugin` script, otherwise it's not going to be loaded. We even have a special error message for that case. So it's exactly the same as with user-provided classes, as you call them. In fact, the only time you don't need a tool keyword in your otherwise tool scripts is when you load the script yourself, using `load` or `preload`. For anything that is handled by the editor you need the keyword.

> What do you see as potential issues with inheriting a toolscript of a thirdparty library?

It's simple: user doesn't know that the script/class is tool. They don't even know that it's a thing. They just got an asset and they want to use it. They see that the asset, by some kind of virtue, displays something in the editor as they edit it, but they don't really know why or what makes it do so. Maybe it's just how Godot does it. Maybe the asset's author is a wizard. But they don't know. And don't really care, as they are the user, whose only goal is to use that asset. And add their own logic to it.

Yes, we want the parent logic to still work, and if the parent was tool, then to do its tool things. But we don't want to run user's extended logic in the editor, unless the user wants it to run in the editor. Remember, in this case the user doesn't know about tool mode, they don't use the keyword, and are not familiar with the general concept. They just extend some base class and write their own logic... which now throws dozens of errors because it runs in the editor. User didn't ask it to run in the editor. They are not even aware how to make it run in the editor. With your proposed solution, it just does.

Now the user, instead of simply using the asset, has to learn all about the tool mode, and the best practices to avoid running the code in the editor. Because after the tool mode is enabled, you can only opt-out and only do it at runtime. This is how I see the problem with implicit behavior.

And don't get me wrong, this problem here affects me greatly, as I make a lot of tools and plugins. And after several years I still sometimes forget to add the tool keyword. As do others in the plugin area. And I like having the warning as the solution for this. Or, in case of plugins, a separate keyword, really. (https://github.com/godotengine/godot-proposals/issues/900, also https://github.com/godotengine/godot-proposals/issues/520)

**Comment by Flavelius** [comment] 2022-06-28 10:52
> You do have to have tool in your EditorPlugin script

You're right, looks like i missed this, as the class was created for me by the dialog; so it's just the same there.

>They just got an asset and they want to use it. They see that the asset, by some kind of virtue, displays something in the editor as they edit it, but they don't really know why or what makes it do so. Maybe it's just how Godot does it. Maybe the asset's author is a wizard. But they don't know. And don't really care, as they are the user, whose only goal is to use that asset. And add their own logic to it.

Yes, they shouldn't know about advanced topics to have an addon just working for them.
It seems we're on the same page when it comes to not hindering the execution of the base classes logic if it needs editor integration. 
Something like these special callbacks (OnValidate, OnDrawGizmos etc) could be a way to exclude all other implicit behaviour while still providing hooks for this usecase. They would also be easily disable-able (if really intended) by overriding and not base-calling the ancestor. And because they only provide access to classes themselves and their base inheritance chain where exposed, they don't influence their inheritors. For editor-interface integrations there could even be a separate _editor_notification() that is also only called in editor. This would likely make the tool attribute obsolete for quite some cases.

**Comment by KoBeWi** [comment] 2022-06-28 11:06
> They just extend some base class and write their own logic.

Why would they do that? User downloads a random plugin and extends it. Why?
If the plugin class is supposed to be extended, it either shouldn't be `tool` or the plugin creator should provide instructions on how to use a plugin.

> And don't really care, as they are the user, whose only goal is to use that asset. And add their own logic to it.

If the asset works in the editor, there is no point in adding logic that doesn't work in the editor.

> Now the user, instead of simply using the asset, has to learn all about the tool mode, and the best practices to avoid running the code in the editor.

If the user simply wanted to use the asset, they wouldn't have this problem. Instead they are making unauthorized modifications without knowing what they are doing. In that case, learning more on the subject doesn't hurt.

**Comment by YuriSizov** [comment] 2022-06-28 11:55
> Why would they do that? User downloads a random plugin and extends it. Why?

No, user downloads a plugin that adds a node and has some editor-specific functionality, and then extends its script to add their own, project related functionality. That's exactly how we script built-in nodes.

Whether it is supported or not would depend on a plugin, but I don't see why we wouldn't want it to work like that, since that makes custom nodes equivalent to the built-ins.

**Comment by KoBeWi** [comment] 2022-06-28 12:04
> No, user downloads a plugin that adds a node and has some editor-specific functionality, and then extends its script to add their own, project related functionality.

Still, it would disable this functionality unless your extending script is tool. So not sure when could it be desired.

And if the plugin creator makes a plugin that *can* be extended (i.e. there is such use-case), they should mention in the description how can it be done properly. btw if a user doesn't know about tool scripts and sees a warning, they might be as confused about it.

**Closed** 2024-08-28 11:38 UTC
Labels: topic:editor, topic:gdscript
