### ISSUE TITLE
Expose exporting units for properties to gdscript

### ISSUE THREAD

**Issue by CiberTurtle** [godotengine/godot-proposals#6529] opened 2023-03-18 16:09 UTC
### Describe the project you are working on

A 2D game on a team of non-technical people.

### Describe the problem or limitation you are having in your project

It can be difficult to understand what units a property is in. For export the property `lifetime` could be in seconds or frames/ticks.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This feature would expose the ability to add units to properties to gdscript.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
# for numbers such as int and float
@export_unit('s')
@export var lifetime := 1.

# and for other types such as vectors
@export_unit('px')
@export var offset := Vector2.Zero
```
It would look like how units currently work in the editor, it will just expose this ability to gdscript
![image](https://user-images.githubusercontent.com/58660466/226117035-c8380bc6-b581-4c0f-99ed-e59ffcdc7139.png)

I'm not sure how exporting degrees will work. Maybe the engine could automatically detect `deg` and swap it out for the degree sign `°`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I believe that this would be a very useful feature for people working on teams and for plugin developers.
It can be worked around bu putting the unit in the variable name.

### Is there a reason why this should be core and not an add-on in the asset library?

It is already an ability of the engine. Exposing it to gdscript would be nice.

**Comment by AThousandShips** [comment] 2023-03-18 16:14
Duplicate of #4866

**Comment by Mickeon** [comment] 2023-03-18 16:15
It's already possible to specify units in Godot 4. I have to admit, it's not as explicit as a specific annotation for it, but thus is the nature of PROPERTY_HINT.

**Closed** 2023-03-18 17:12 UTC
