### ISSUE TITLE
Log error when signal is called with incompatible types

### ISSUE THREAD

**Issue by FabriceCastel** [godotengine/godot-proposals#8987] opened 2024-01-29 14:19 UTC
### Describe the project you are working on

A 3d platformer

### Describe the problem or limitation you are having in your project

I implemented the following signal: `signal on_update_letters(word: String, letters: Array[bool])`

Then, I did:

```
var word = "ICY"
var letters = [false, false, false]
EventBus.on_update_letters.emit(word, letters)
```

The component connected to the signal never received the call. Why? Because `letters` wasn't an `Array[bool]`, apparently. Changing that line to `var letters : Array[bool] = [false, false, false]` solved the issue. Chasing this bug down was annoyingly confusing.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If an attempt is made to emit a signal with mismatched types, an error (or at least a warning) should get logged to the console.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

n/a - I'm not familiar enough with the internals tp suggest an implementation

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

Getting errors when incorrectly calling core APIs should live in the core engine

**Comment by AThousandShips** [comment] 2024-01-29 14:28
See also:
* https://github.com/godotengine/godot-proposals/issues/2557
* https://github.com/godotengine/godot-proposals/issues/7891
* https://github.com/godotengine/godot-proposals/issues/8982

This is arguably a duplicate of a bug report:
* https://github.com/godotengine/godot/issues/54333

**Comment by AThousandShips** [comment] 2024-01-29 14:31
Closing as a duplicate of either of:
* #2557
* https://github.com/godotengine/godot/issues/54333

Thank you for your proposal nonetheless, please add your support/thoughts to the relevant proposals 🙂

**Closed by AThousandShips** 2024-01-29 14:31 UTC
Labels: topic:core
