### ISSUE TITLE
Add Skeleton Gizmos

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#2990] opened 2021-07-13 19:29 UTC
### Describe the project you are working on

Tweaking animations

### Describe the problem or limitation you are having in your project

Currently, to change things like rotation, scale, and translation, you need to do so in the inspector, and cannot do it in the editor itself

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When you are in the Skeleton Node, and you select a Bone, the bone should be selected in the editor as if it were a node

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If in the Skeleton Node a Bone is Selected, get the bone in the editor and treat it like a node.
If you click somewhere in the editor that isn't the gizmo, or unselect the bone/node in any way, return to normal node manipulation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, but you can just use the inspector, however that wouldn't come with the ability to manipulate the bones "Locally" as in the inspector, all the bones are only modified in "Global" space.

### Is there a reason why this should be core and not an add-on in the asset library?

It would require changes to the Skeleton node, and possibly the editor to work. This Might be doable as an addon, as a tool, however I don't have enough experience with creating such editor tools, so I don't know if it is, and if it is, how hacky it'd have to be, if at all.

**Comment by Calinou** [comment] 2021-07-13 19:53
Duplicate of https://github.com/godotengine/godot-proposals/issues/584.

**Closed by Calinou** 2021-07-13 19:53 UTC
