### ISSUE TITLE
Add support for classic grey-scale bump maps . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2171] opened 2021-01-24 10:16 UTC
### Describe the project you are working on
A Tomb raider game . . <3

### Describe the problem or limitation you are having in your project
I wanted to do some cool stuff, where I had a bump map, for some big ocean waves, and then smaller waves, on top of the waves, and then another layer . . .
![2021-01-13 1150](https://user-images.githubusercontent.com/61069740/105627030-68883780-5e34-11eb-8ac1-71d7ea7e32bb.png)

That is easy by having several grey-scale images, and using an ADD or, MULTIPLY shader, and could take stuff like ocean graphics, to the next level . . Anyway, bump maps are super-easy to paint, in Blender, and very easy to make tiling, compared to normal maps, so it's a work-flow, that could perhaps make Godot better . . and, if Godot can render normal maps, bump maps should be possible, possibly with an advanced importer, that smoothes or, a shader, that makes them look nicer, or so . . The problem is, bump maps are like, painted in ' steps ', ie. there's a hard step from 0.98 to 0.99 height, like ' stairs ', in the texture . . maybe it is possible, to somehow ' smooth ' these steps, maybe by adding a toggle in importer or, under the ' height map ' / ' bump map ' . . so, the proposal is, add support for bump maps, and maybe add a feature, so they appear smooth, using shaders or, the importer . . <3 for instance, if Godot could import bump maps, and turn them into ' slightly ' smoothed normal maps, that'd be a nice addition . . :O :O . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Bump maps are easy to draw, in Blender, making a tiling bump map texture is super easy, making a normal map tile, is much tougher . . :(( So, either add support for bump maps, or perhaps make an importer, that can turn bump maps, into normal maps, perhaps with a mild smoothing effect, except near the edges ( to keep tiling ) :OO . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I'm not sure, I just wish it was possible to use bump maps in Godot, as they are so easy to make and, modify . . :O . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I don't know, also want to try and ' layer ' bump maps, that's not so easy, with normal maps, but overlaying or, ' ADDING ' bump maps on top, of each other, could create amazing water effect, like waves, with waves on, going up and, down, using shaders . .

### Is there a reason why this should be core and not an add-on in the asset library?
Bump maps have been used for many, many years, could be cool, for games . . . .

**Comment by jasperbrooks79** [comment] 2021-01-24 10:22
Shaders often take a value, form 0 - 1, such as a metalness map, an alpha map, so on . . and, it can do amazing things, with those . .

Bec. bump maps are basically in the same range, it would be easy to add them, mix them, to create some effect, that normal maps can't, or so . . <3 like big waves, with medium waves rising, and falling, using a sine curve on top of big waves and, smaller waves, having another rhytm, or so . . it's basically just multiplying and, adding textures, and COULD look cool, thank you . .

<3

**Comment by jasperbrooks79** [comment] 2021-01-24 10:35
Ideally, if one could work with bump maps, that are easy to make tiling, such as waves, on the ocean, but they have the limitation, that they are in steps . .
<img width="1127" alt="Skærmbillede (945)" src="https://user-images.githubusercontent.com/61069740/105627588-11846180-5e38-11eb-8eac-d5f6af18368e.png">

like, there are plateaus . . if one after adding some bumps maps together, could make a fast shader node or, code, that turned them into normal maps, or an approximation, one would have an amazing system, as normal maps store ' normal ' direction of the surface, and so don't have plateus . . if the conversion was ' dirty ' enough, it could combine bump and, normals into something 'new', and expand on what shaders can do, or so . . .

**Comment by jasperbrooks79** [comment] 2021-01-24 10:56
normal maps look ' smoother ', bec. each pixel has a ' direction ', not just a height . .
![2021-01-24 1154](https://user-images.githubusercontent.com/61069740/105628068-fc5d0200-5e3a-11eb-8e12-cce808061d8a.jpg)

if it was possible, I seen some shaders that basically make 3D objects look like normal maps . . for instance, Blender has a matcap, that sort of ' looks ' like a normal map . . if one could FAST turn a bump map ( or additions of bump maps ) into a normal map, and perhaps smooth it, just a bit, then one could get the best, of both worlds, running in shaders, like magic . . <3 <3

**Comment by jasperbrooks79** [comment] 2021-01-24 12:40
the last part is, to get ' foam ' on the top, of the waves, one would need to calculate a certain ' bump map ' height, where the albedo is changed from water to, white . . it's so much more intuitive to work with bump maps, considering how shaders work, preview a range from 0 - 1, and just add or, subtract, etc etc . . those . .

![2021-01-24 1337](https://user-images.githubusercontent.com/61069740/105630444-92982480-5e49-11eb-9788-7b8836ca3b77.jpg)

it would also look nice with rivers, with animated effects and, lava flow, where one can make bump map ' lava ' bubbles appear, and disappear, but adding, mixing or, multiplying maps, and have them run on different TIME or, using sine curves, to trigger them . . It'd be a big help, to shader beginners, if bump maps worked, in Godot, or so . . Thanks <3 <3 . .

**Comment by jasperbrooks79** [comment] 2021-01-24 13:06
for instance, if you have a brick wall bump map, and you have a ' ripple ' bump map, with an average, of 0.50 grey, then you just subtract 0.5, and then add that to the brick wall, while animating it with a sin curve, to get effect, of there being a ripple, in the wall, or so . .
![2021-01-24 1403](https://user-images.githubusercontent.com/61069740/105631148-3cc57b80-5e4d-11eb-8f34-a8972001dca1.jpg)

![2021-01-24 1404](https://user-images.githubusercontent.com/61069740/105631153-40590280-5e4d-11eb-887b-36b291687b2b.jpg)

Blender's bump maps are default height 0.50, in grey-scale, so it would be easy to mix them, and I'm not sure, require less map, than mixing normal maps <3 . .

**Comment by Calinou** [comment] 2021-01-24 13:27
Duplicate of https://github.com/godotengine/godot-proposals/issues/1625.

**Closed by Calinou** 2021-01-24 13:27 UTC
