### ISSUE TITLE
Button editions work space

### ISSUE THREAD

**Issue by Jeudry** [godotengine/godot-proposals#4685] opened 2022-06-17 16:32 UTC
### Describe the project you are working on

Im working on a senital view game

### Describe the problem or limitation you are having in your project

![image](https://user-images.githubusercontent.com/75742611/174339220-7e47f8cf-8a16-44e4-a95e-14db6c2723ca.png)

My workspace is limited of space in the inspector becacuse of so many and spaced options with the edition of buttons, as you can see in the image.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

make them shorter

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

i have no idea how would it work

### If this enhancement will not be used often, can it be worked around with a few lines of script?

idk what this means

### Is there a reason why this should be core and not an add-on in the asset library?

Because it takes a lot of space, even for high resolution screens, im using 100% screen size

**Comment by Calinou** [comment] 2022-06-17 17:15
Duplicate of https://github.com/godotengine/godot/issues/31133 (this is a bug).

**Closed by Calinou** 2022-06-17 17:15 UTC
