### ISSUE TITLE
Allow the user to export custom Resource subclasses in the editor.

### ISSUE THREAD

**Issue by uzkbwza** [godotengine/godot-proposals#4450] opened 2022-04-26 22:05 UTC
### Describe the project you are working on

Multiple projects, all of which rely on Resources for shared & serializable data.

### Describe the problem or limitation you are having in your project

The incredibly powerful feature to define and export custom resources is hidden behind an enormous UX failure - the user must scroll through an often giant list of every resource that shares the same parent class, because you cannot export your own subclass directly. This is not a problem for any built-in Resource types. For example, here is what you do to export and create a new CurveTexture:

https://user-images.githubusercontent.com/43023911/165398875-99886922-8fe6-4d4d-886f-1d4e2f57a6e3.mp4

And this is what the user must do if they wish to export their own Resource subtype

https://user-images.githubusercontent.com/43023911/165399911-0c253a29-64b0-49c2-bcc4-e16f88644daa.mp4

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow the user to export custom Resources directly.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Exporting a custom Resource would function identically to exporting a built-in Resource.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a UI/UX problem inherent to Godot's editor and will potentially affect any project that uses custom resources. Add-ons are meant to provide additional functionality, not to fix broken features.

**Comment by Calinou** [comment] 2022-04-26 22:27
Duplicate of https://github.com/godotengine/godot-proposals/issues/18.

**Closed by Calinou** 2022-04-26 22:27 UTC
