### ISSUE TITLE
Add a primitive node to a 3D position in the viewport.

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot-proposals#2194] opened 2021-01-28 02:13 UTC
### Describe the project you are working on
3D Game

### Describe the problem or limitation you are having in your project
Adding primitive nodes like lights is a pain since always get inserted at the origin.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Something like Blenders 3D cursor to add a node in a 3d position

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Right click -> Insert node here (or something like that) then select node like when ctrl + a

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
Should be core

**Comment by KoBeWi** [comment] 2021-01-28 09:22
Duplicate of #435

**Closed by KoBeWi** 2021-01-28 09:22 UTC
