### ISSUE TITLE
Make Unique per Duplicate Resource Option

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot-proposals#1036] opened 2020-06-11 14:33 UTC
**Describe the project you are working on:**
I'm working on a 2D platformer, and as part of a design goal, I'm making sure all level editing is done within Godot (using custom-made plugins, Godot's already great features, etc).

I'm working on a pretty interesting plugin called "Handles" which allows you to add custom position and size anchors to any `CanvasItem` node. i.e. For example, you might use these custom handles to make `RectangleShape2D` to scale it from the Top-Left corner instead of the middle.

Anyways, this plugin allows you to set custom position and scale anchors for _any_ `CanvasItem` (no script requirement) node via a custom property in the inspector.

Here's how it looks:
![2020-06-11 10 22 02](https://user-images.githubusercontent.com/4584511/84398074-7a7ed800-abcd-11ea-9b4c-0613a945d875.gif)

As you can see, the `RectangleShape2D` is being scaled from the top-left corner, and the entire top-left's node position is moved (this is done with one handler).

This is all done through one extra property on all `CanvasItem` inspectors:
![image](https://user-images.githubusercontent.com/4584511/84399949-6e941580-abcf-11ea-8464-3cc471ff10ca.png)

**Describe the problem or limitation you are having in your project:**
When I duplicate my top-level Canvas Item, even when I use 'Local to Scene', the RectangleShape2D isn't made unique and, thus, the scaling functionality of my plugin scales all instances of the RectangleShape2D.

I would like to be able to duplicate this StaticBody2D and its collision shape so that I can edit the copies individually without having to "Editable Children", finding the shape and clicking "Make Unique".

Local to Scene does not achieve this, how come? Is this a bug? If not what's the difference between "Local to Scene" checked and "Make Unique"? I'm genuinely curious.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add a checkbox 'Make Unique on Duplicate` under all resources (like "Local to Scene"). If this is checked, then that resource alone would be duplicated every time the instanced scene is duplicated.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Just add a checkbox property called 'Make Unique on Duplicate' under all resources.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
You need to do check "Editable Children" which bloats the Scene tree. There is no way to override the duplicate function to have custom functionality (as far as I know) - I would be happy with a solution that would allow me to override the duplicate functionality on an instanced Scene.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This seems like a pretty common use case, and would be helpful with more frictionless level editing.

**Comment by Zireael07** [comment] 2020-06-11 14:55
IIRC shapes are a special case and are shared for performance reasons. To make them not shared, you click make unique.

**Comment by KoBeWi** [comment] 2020-06-12 10:57
Well, as a workaround, you can manually duplicate the shape inside the instanced scene's `_ready()` method (but the script needs to be `tool`).

btw, rectangle editing improvements might soon be in core: https://github.com/godotengine/godot/pull/37760

**Comment by Lucrecious** [comment] 2020-06-13 12:34
@KoBeWi  Yeah I'd prefer not having to make a tool script. So maybe I'll just write another plugin that allows for custom start up.

The rectangle editing looks cool but it doesn't solve the fundamental issue of wanting to have handles that control properties on different nodes (i.e. the position property on a StaticBody and the extents property on RectangleShape2D.

**Comment by golddotasksquestions** [comment] 2021-04-09 03:06
related/duplicate:
https://github.com/godotengine/godot-proposals/issues/317

**Comment by Calinou** [comment] 2021-05-17 21:20
Duplicate of https://github.com/godotengine/godot-proposals/issues/317.

**Closed by Calinou** 2021-05-17 21:20 UTC
Labels: topic:editor
