### ISSUE TITLE
Export template optimization

### ISSUE THREAD

**Issue by JeffVenancius** [godotengine/godot-proposals#865] opened 2020-05-21 03:01 UTC
**Describe the project you are working on:**
I'm working (more as a hobby) on a virtual console for Godot. 
My theory is that, if you can use the same optimized version of the engine to play any .pck, then you could use only one.
**Describe the problem or limitation you are having in your project:**
Well, this idea came to me as I saw that some .pck files are smallers than the build itself. I'm making a 2D game as well, so it could be usefull to disable 3D from this optimized version(the same way you can on the editor, but for optimizations purposes).
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It could be customizable, and/or the engine could detect exactly the features I've used and then recompile it. For example: The engine could look through my resources and searchs if I've used 3D or not, this node or the other node. If I didn't need that one, etc...
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
If it was automatically, the engine itself has a system that contains all the resources data (though sometimes it won't look if the resource was used on a script). If it was manual, it could be exactly like this:
![image](https://user-images.githubusercontent.com/43701418/82518057-deddd880-9af4-11ea-9019-9462dd463030.png)

But, you know, not for the editor, but for the build that is created when you export your project.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
As I've tried to learn about it, I saw that you would need to enter into the core of the engine. Even with a plugin, you would need to recompile the no-editor build anyway.
**Is there a reason why this should be core and not an add-on in the asset library?:**
As I say above, you would need to recompile the no-editor build in a way that matches what you want. Maybe you can do it with an add-on, but it really would optimize if it was on its core.

**Comment by Calinou** [comment] 2020-05-21 15:41
Duplicate of #726.

**Closed by Calinou** 2020-05-21 15:41 UTC
