### ISSUE TITLE
Remove Godot output text

### ISSUE THREAD

**Issue by kaissouDev** [godotengine/godot-proposals#7135] opened 2023-06-21 16:11 UTC
### Describe the project you are working on

A 2d game 

### Describe the problem or limitation you are having in your project

Hi, when I export my Godot game, I get this message in the output:

     -- Debugging process started --
     Godot Engine v4.0.3.stable.mono.official.5222a99f5 - 
     https://godotengine.org 
     OpenGL API 3.3.0 - Build 31.0.101.2115 -  
     Compatibility - Using Device ..

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like to remove this text from my game, can you correct this problem by adding an option in the editor or something else?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It works by adding an option in the "debug" or "application" tab.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so unless you use hack software to modify the application's properties.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, because I think it would be cool to natively customise the console for our games.

**Comment by Calinou** [comment] 2023-06-21 19:47
Duplicate of https://github.com/godotengine/godot-proposals/issues/4998.

**Closed by Calinou** 2023-06-21 19:47 UTC
Labels: topic:core

**Comment by kaissouDev** [comment] 2023-06-21 20:01
Yes, but how do you export with --quiet please

**Comment by KoBeWi** [comment] 2023-06-21 21:02
`editor/run/main_run_args` in Project Settings.

**Comment by Calinou** [comment] 2023-06-21 21:10
The correct answer is actually this: https://github.com/godotengine/godot-proposals/issues/4998#issuecomment-1601610447
