### ISSUE TITLE
Detachable script text editor

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot-proposals#3237] opened 2021-08-31 06:54 UTC
### Describe the project you are working on

Memories Of Ariandine

### Describe the problem or limitation you are having in your project

I'm sure this has been asked countless times but I cannot find an actual feature proposal here, so, here it comes.

Constantly switching between 3D and Script tags wen writing editor plugins breaks all the work flow, having the script tab on a different window will help. This problem also comes up wen testing gameplay, since if I want to make some translation changes for an object while programming, I have to switch to 3D/2D tab, make the changes, then switch again to script tab, then continue programming.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If you have to make this a couple of times a day there is no problem, but if you have to constantly go trough this process every time a 100+ times every day, this gets annoying, very fast.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just make this section detachable to a window.
![scriptEditor](https://user-images.githubusercontent.com/27329423/131456041-1ab8cbb6-ffd7-40f3-b747-469ebf0451c2.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I wish.

### Is there a reason why this should be core and not an add-on in the asset library?

Can't be in a plugin.

**Comment by amyhaber** [comment] 2021-08-31 09:35
I think multi-screens development could also benefit from this proposal.
But since the editor is built on Godot itself,  so it shares the limitation of lack of multi-windows support (version 3.x).
May Godot 4.0 will make this happen.

**Comment by Janders1800** [comment] 2021-08-31 10:41
Yeah this proposal is more aimed to 4.0, I know that for 3.X is not really worth it.

**Comment by pycbouh** [comment] 2021-08-31 10:57
Duplicate of https://github.com/godotengine/godot-proposals/issues/28

While 4.0 supports multiple windows, we don't plan to overhaul the editor for that just yet. That will come in later 4.x versions.

**Closed by pycbouh** 2021-08-31 10:58 UTC

**Comment by was-games** [comment] 2021-11-09 13:11
This is so much needed. Especially with the outdated VSCode plugin with no one to maintain it.

**Comment by pycbouh** [comment] 2021-11-09 13:49
VS Code plugin works, and it is maintained: https://github.com/godotengine/godot-vscode-plugin
