### ISSUE TITLE
Add thumbnails for 3D scenes to the FileSystem dock

### ISSUE THREAD

**Issue by jocamar** [godotengine/godot-proposals#2493] opened 2021-03-22 18:06 UTC
### Describe the project you are working on

Any 3D project in Godot 3.2/3.3.

### Describe the problem or limitation you are having in your project

In the Godot workflow scenes are often used as reuseable prefabs and props for different objects in the game world. When designing a level I've found it useful to have the filesystem tab on the side open with the large icons so I can drag props to the main scene. This works well in 2D where it's easy to see at a glance what each scene is due to the thumbnails, but in 3D there are no thumbnails for some reason. This is a bit weird considering there are thumbnails for 3D assets like obj files, but not for3D scenes. It's also abit weird for people coming from other game engines who show previews and thumbnails of prefabs in the assets tab, for easy browsing.

Here you can see examples of what I mean, not how the 2D scenes get thumbnails, while the 3D ones do not:

![EwykzR_XAAknkiT](https://user-images.githubusercontent.com/4234276/112036678-d69d6200-8b38-11eb-9e16-4b7e835fd4cb.png)

![EwykMCNW8AUT39M](https://user-images.githubusercontent.com/4234276/112036688-d8672580-8b38-11eb-8478-d6bbfd5e0c7b.jpg)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow the engine to generate thumbnails for 3D scenes as it does for 2D scenes. This can be automatic or maybe have some option for the user to provide a thumbnail for a scene if necessary.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Ideally this would work transparently, as it does for 2D scenes and 3D assets, where the engine would deal with generating the thumbnails in the background. But another option is to provide an option or button somewhere allowing the user to take a snapshot of the viewport and using that as the scene thumbnail.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is core to the engine and cannot be worked around.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a core engine usability feature.

**Comment by Calinou** [comment] 2021-03-22 18:21
File thumbnails for 3D scenes are already supported (try hovering scene tabs in the editor), but the issue is that 3D scene thumbnails are often not very useful due to how they're generated. The current editor camera position is used, which leads to unpredictable results.

My proposed solution is to add a ThumbnailCamera node for both 2D and 3D that can be used to take screenshots in a consistent manner.

**Comment by pycbouh** [comment] 2021-03-22 18:22
Previews are generated for 3D scenes just as they are for 2D scenes. If you don't see that, there may be some issue with your scenes or with the engine.

https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L1389

**Comment by jocamar** [comment] 2021-03-22 18:24
Then maybe this should be submitted as a bug, because I can't get the engine to generate thumbnails for 3D scenes no matter what I do in 3.2.3/3.3.

**Comment by pycbouh** [comment] 2021-03-22 18:27
Yes, it would be a good bug report with a little test project for evaluation.

**Comment by jocamar** [comment] 2021-03-22 18:44
Submitted as a bug report with a sample project (but any godot example project has the same issue to me):
https://github.com/godotengine/godot/issues/47267

**Comment by jocamar** [comment] 2021-03-22 20:06
Regarding the ability to set your own thumbnails, I feel like just using the editor´s camera is more intuitive. I think having an option either on the view or perspective camera options and remembering the transform of the editor viewport camera (the same way that the scene remembers what gizmos you have turned on/off for the scene) would be the simplest way for the user.

![image](https://user-images.githubusercontent.com/4234276/112051375-c6da4980-8b49-11eb-9cfe-017699dcd0e9.png)

**Comment by pycbouh** [comment] 2021-08-18 18:39
> I feel like just using the editor´s camera is more intuitive. 

This already the case, the editor camera is used for generating a preview for the 3D scenes. Since what you report is a bug, and you've reported it, I'll close this proposal in favor of the bug report (https://github.com/godotengine/godot/issues/47267).

**Closed by pycbouh** 2021-08-18 18:39 UTC
Labels: topic:editor, topic:3d
