### ISSUE TITLE
Suggest last saved folder instead of document folder

### ISSUE THREAD

**Issue by skyttedk** [godotengine/godot-proposals#1583] opened 2020-09-29 11:33 UTC
**Describe the project you are working on:**

I'm currently working on my first small mobile game, and several test projects.

**Describe the problem or limitation you are having in your project:**

Even though I mainly work on a single project, I often create separate test projects, to test out different implementations, before merging them into the main project. The "Create New Project" dialog does not remember the last folder where I saved a Project.
It always suggests the user document folder as default:

![image](https://user-images.githubusercontent.com/9749147/94552601-6b449880-0257-11eb-9b09-5b9013e78a8a.png)

Therefore I have to navigate to my project folder every time I create a new project.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The "Create New Project" dialog should suggest the last folder a project was saved, instead of the user document folder

**Comment by Calinou** [comment] 2020-09-29 12:13
Duplicate of https://github.com/godotengine/godot-proposals/issues/1312.

**Closed by Calinou** 2020-09-29 12:13 UTC
Labels: topic:editor
