### ISSUE TITLE
Use physical key for shortcuts inside the Editor

### ISSUE THREAD

**Issue by hakro** [godotengine/godot-proposals#6245] opened 2023-02-06 17:29 UTC
### Describe the project you are working on

Currently, when using shortcuts to select, move, rotate and scale object, we can respectively use Q, W, E and R.

![2023-02-06_18-09](https://user-images.githubusercontent.com/3624853/217038511-c8ca9675-cd0f-48dd-b8f0-3d86145979a5.png)

This works fine when using a QWERTY layout, and it makes sense, since those keys are contiguous, and thus easy to remember and get used to.

However, it not as practical when using other layouts, including AZERTY. The shortcuts become all over the place, and hard to get used to, as they are not aligned with the buttons on the editor, nor do they have a resemblance to the action itself (think G to Grab, S to Scale, R to Rotate)

### Describe the problem or limitation you are having in your project

This is just a minor annoyance, but that can be avoided, when you want to rely on shortcuts and have a keyboard layout that is not QWERTY
I theory, this won't have an impact on people using QWERTY keyboards, but would be useful for other layouts.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I mentioned this to @akien-mga this W.E while in Fosdem, and he suggested using physical keys for the shortcuts instead of the key values, which sounds like a good solution.
That way, the four first letter of the keyboard will always map to the correct actions, regardless of keyboard layout.
This proposal's purpose, is to follow up on that discussion.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Nothing much to say; "just" need to update the shortcuts to use physical key input.
The double quotes around "just", is because I don't know exactly how to do that yet, but I'll definitely have a look to see if it's a quick fix

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This a QoL improvement on the editor.
It could be possible to manually change the shortcuts in the Editor preferences, but some people, including myself, would rather have an out of the box coherent experience

### Is there a reason why this should be core and not an add-on in the asset library?

This is related to the editor, there is no point to have as a separate add-on, if that's even possible.

**Comment by Calinou** [comment] 2023-02-06 17:44
Duplicate of https://github.com/godotengine/godot/issues/11777 (this is considered a bug).

**Closed by Calinou** 2023-02-06 17:44 UTC
Labels: topic:editor, topic:input

**Comment by hakro** [comment] 2023-02-21 11:28
This can now easily be fixed if https://github.com/godotengine/godot/pull/73651 is merged.

Just by adding the p_physical = true parameter here : 

https://github.com/godotengine/godot/blob/662d0b188dc2bd6ca50ea0c3b3b9accb8255acfc/editor/plugins/node_3d_editor_plugin.cpp#L8051

like this : 

`tool_button[TOOL_MODE_SELECT]->set_shortcut(ED_SHORTCUT("spatial_editor/tool_select", TTR("Select Mode"), Key::Q, true));`

However, there is  something wrong with the button tooltip in the editor. It will say : `Select Mode (Q(Physical))`
which is quite confusing an not very user friendly IMHO, especially for non-QWERTY users, where the real shortcut would be `A`

On the tooltip display code, using as_text_keycode() instead of in the as_text() prints `(Unset)`. This is the normal behavior according to the `InputEventKey` documentation which states the following : 

![2023-02-21_12-24](https://user-images.githubusercontent.com/3624853/220332450-c5eb3f64-9304-4007-8a7e-4c0be763d48f.png)

So `as_text_keycode()` only works when an event is received, which is not the case when displaying tooltip.

@Calinou, @EricEzaM, any idea on how to make this more user friendly ?

**Comment by Calinou** [comment] 2023-02-21 15:56
I don't think we can access every keyboard layout out there, so there is no way to display the actual key you should press on your current keyboard layout.
