### ISSUE TITLE
Add thumbnails for imported 3D scenes to complement 3D mesh thumbnails

### ISSUE THREAD

**Issue by kulkalkul** [godotengine/godot-proposals#7205] opened 2023-07-05 11:26 UTC
### Describe the project you are working on

A 3D game with modular assets.

### Describe the problem or limitation you are having in your project

GLTF resources have no thumbnail in FileSystem panel.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Building scenes would be easier if I could see the model I'm using beforehand. Right now I'm using names to differentiate between models, but it is cumbersome when there are lots of them.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

.obj files have thumbnails generated for them. As far as I can see, they are using ArrayMesh in Godot 4.0.3 (the version I'm currently using). So, in theory, it should be easy to adapt that part to .gltf/.glb files as they have their internal meshes. I don't know if there are any edge cases that can make implementing this hard.
![Idle_2023-07-05_14-05-38](https://github.com/godotengine/godot-proposals/assets/1013994/4097904f-4d85-4f0f-bb60-6613b12bf1b8)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know that much about plugins but this requires either custom FileSystem panel or editing existing FileSystem with tricks, which I don't know if possible at all.

### Is there a reason why this should be core and not an add-on in the asset library?

Because .obj already has this feature, so I feel it should be straightforward to implement it for GLTF formats, considering it is preferred format of many of the Godot projects as far as I know. This is a good QoL improvement for 3d asset workflow, that's why I think it should be included in the core.

**Comment by fire** [comment] 2023-07-05 15:07
This is a great idea. Trying to find a list of things to work on for 4.2. This could be one of them. Are you able to assist?

**Comment by Calinou** [comment] 2023-07-05 15:31
Note that this is challenging to implement, as `.obj` is a 3D *mesh* format while glTF is a 3D *scene* format.

Also, an implementation should be able to work with the other imported 3D scene formats including `.blend` and `.fbx`.

**Comment by JoNax97** [comment] 2023-07-05 16:02
Possibly related to #4759? I'm not sure if the same workflow would apply to scenes created from imported files and native scenes.

**Comment by Calinou** [comment] 2023-07-05 16:05
- Duplicate of https://github.com/godotengine/godot-proposals/issues/5076.

**Closed by Calinou** 2023-07-05 16:05 UTC
Labels: topic:editor, topic:import, topic:3d
