### ISSUE TITLE
Improving the apperance of visual script - idea . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3944] opened 2022-02-10 03:57 UTC
### Describe the project you are working on

A simple car - title . . .

### Describe the problem or limitation you are having in your project

I was looking at visual scripts recently, googled it . . I found some visual script systems, where I like the sort-of ' look ' better . . . Point is, everyone says Unreal / Blueprints is the best, I get that, it has the best CODE, sort-of, what it can do . . It's perhaps the most 'powerful' coding system, however, in my opinion, it does not have the best look, ie. appearance . . . Some examples, that I think are better, for navigating, overview, so on . . .

Notice, they have a bit more color, in boxes, this helps readability, etc . . The idea is, to look at this, and think, even if Unreal is best, in terms of code, is the appearance, of other systems better, or, more user-friendly / UX, is better . . .

![2022-02-10 0445](https://user-images.githubusercontent.com/83387915/153333637-5b1bf8e8-dbed-403b-9e79-d12d90d254f3.png)

![2022-02-10 0427](https://user-images.githubusercontent.com/83387915/153333623-86413eec-7771-4783-a6fb-1503740cc16c.jpg)

![2022-02-10 0441](https://user-images.githubusercontent.com/83387915/153333629-85eaa5a7-31c3-4b0c-a8fe-e1a21ecfdadc.png)

![2022-02-10 0442](https://user-images.githubusercontent.com/83387915/153333630-81369d23-615e-4cdb-97ba-932b1cbae43f.png)

![2022-02-10 0443](https://user-images.githubusercontent.com/83387915/153333634-ef0b6ba1-6b24-4865-a728-0243804f80e1.jpg)

![2022-02-10 0444](https://user-images.githubusercontent.com/83387915/153333635-b50ad23a-b0e4-4534-92fc-a0df34f2f575.jpg)

Now, some are a bit exaggerated . . For me, after trying O3DE, I think that was best apperance, of a visual script ever, Unreal is still most ' powerful ', for code, can do anything . . But, I think the apperance, could be better . . I think the examples above are better, and, if possible, I'd like a debate . . Sort-of, Unreal is of course the best, but, is it the best appearance . . . . I disagree, the one's above, are more readable, and, word is, more ' fun ', in a positive way . .

That's why I suggest, one adds a customization tab, perhaps in editor settings, for ' graph edits ', where one can set such things, or, consider it, for the theme editor . . I want the best, more ' fun ', word is, simply relaxed experience . . . I think looking up to Unreal is good, in several ways, I think their UX is sadly, not the best, thx . . . ! :-OO

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Consider, if there are better UX, not copy Unreal, even if they have best reputation, over code, the ' complexity ', or sort-of power, of the coding - system, so on . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, add some customization features, to add more color, or saturation, to the visual script, graph edit . . I think it might be possible to find a better theme, or ' appearance ', that's better than Unreal, though, their coding system, is considered the best, I don't think their UX is the best, O3DE was better, tried it, for a few hours . .

So, if people could find examples, of what they like, maybe one could find, some better UX / UI, say for visual script, thx . . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No way, can't code the engine . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, core, etc . . ? It's basic - level feature, so on . . .

**Comment by charlesmlamb** [comment] 2022-02-10 03:58
Note, I had to try O3DE, to sort-of ' get ' it . . It's a nicer experience, I think there are sort-of themes, that'd make visual script better, question is, where or, how to find them, etc . . .

**Comment by Zireael07** [comment] 2022-02-10 07:48
I think it's effectively a duplicate of your own issue where you want visual script to 'look better'

**Comment by charlesmlamb** [comment] 2022-02-10 13:10
Uhh, no the idea is to look at other visual script systems, and, see if they have a better UI, or so on . . I hear, from some people, about Unreal, how it's the best . . It might be in terms of how powerful it is, but, the UX, or UI is better, in O3DE . . I've tried it, and, it's sort-of more relaxed, the best I ever tried . .

Only asking, that some people, that work with visual script, look to other places than Unreal engine, I think it'd make the engine better, also, other graph edit, etc . . :-OO

**Comment by YuriSizov** [comment] 2022-08-24 16:13
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!

**Closed by YuriSizov** 2022-08-24 16:13 UTC
Labels: archived, topic:editor, topic:visualscript
