### ISSUE TITLE
Autocomplete/Suggest Methods while connecting Signal

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot-proposals#1850] opened 2020-11-17 08:21 UTC
**Describe the project you are working on:**
Doing some UI work for my game.

**Describe the problem or limitation you are having in your project:**
Another UX inconvenience for the list.

While connecting Signals to Methods, I often find that I have to back out of the 'Connect a Signal to a Method' Dialog, because I cannot quite remember the exact naming I used on the Function/Method I'm trying to connect. This means I need to close the Dialog, open the script back up, scroll to the Function I'm working on, memorize the name, go back to the Scene Tree, find the Node, and start connecting the Signal again.

It would be a lot more convenient if the `Receiver Method` input would/could suggest functions or autocomplete the function I am typing.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I am suggesting that on typing in the `Receiver Method:` input field, the input Method would be suggesting/autocompleting functions based on the input characters thusfar. The same way referencing a function inside a script does.

The request isn't aimed at speeding up the connection process exactly (although that might be a nice benefit), it is mainly focused on making sure you don't need to memorize the entire function name before creating a connection to it, as well as leaving no option for spelling, capitalization and style mistakes.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I am not fully sure yet on how this could best be implemented. Perhaps the string inside the `Receiver Method:` input field should be showing greyed out text, which would become 'solid/white' if `Enter` is pressed or focus on the input field is lost, to autocomplete functions in that way.

![image](https://user-images.githubusercontent.com/10502115/99362052-42ce3780-28b3-11eb-8e1b-71c9e4f4a3bc.png)

Perhaps it should (instead/also) show a drop-down underneath the input in which functions can be selected, as is done inside scripts:
![image](https://user-images.githubusercontent.com/10502115/99362128-5f6a6f80-28b3-11eb-9895-a8e0666b8f4a.png)

Another alternative would be to have a drop-down button with all existing functions underneath the Receiver Input. That would mean the 'connect to existing function' and 'connect to new function' would be split up, which might be inconvenient, but it is something to consider.

![image](https://user-images.githubusercontent.com/10502115/99364283-149e2700-28b6-11eb-9654-a30254cde27a.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not really. It's something you'd have to keep in mind during your workflow, to first double check the function name before connecting, but I expect everyone will forget to do that sometimes.

**Is there a reason why this should be core and not an add-on in the asset library?:**
UX improvement on a Core Feature.

**Comment by Calinou** [comment] 2020-11-17 08:56
Duplicate of https://github.com/godotengine/godot-proposals/issues/239.

**Closed by Calinou** 2020-11-17 08:56 UTC
