### ISSUE TITLE
Generate a .txt file of all scenes/funcs/vars not required for min. reproduceable project on error

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot-proposals#1706] opened 2020-10-22 16:24 UTC
**Describe the project you are working on:**
N/A

**Describe the problem or limitation you are having in your project:**
I am trying to create a minimum reproduceable project to report this error:
`Internal Script Error! - opcode #38 (report please).`
I have a complex project right now, and trying to delete scenes, functions, and variables to reduce it down to a minimum example project is causing me a huge headache, because when I delete things I think aren't needed, I find out 20 function calls later that I do in fact need some variable, or function for it to work.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Generate some .txt file with a list of all the variables and functions in every single scene/script that is not required/used up to the point that the error occurs.
This way, the user can look at that file, and delete everything listed in it.
They can then further trim down the required functions by deleting lines that aren't required.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
No idea.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
N/A

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think this is a core issue.
This will make it easier to report bugs and fix them.

**Comment by pycbouh** [comment] 2020-10-22 17:45
> No idea.

Yeah, I think we need a little bit more than that. Your description is very vague and a naïve approach is not very scalable here. What if everything is "required" or "used up" (whatever that means), but the error happens on a 1000th iteration of a loop?

It can be a pain to make a repro project, that is true. But that's what looking for bugs sometimes is. This proposal seems to be too idealistic IMO.

**Comment by Error7Studios** [comment] 2020-10-22 17:58
I said "No idea" because:
1) I have no idea if this is even possible to do.
2) I don't know C++, and therefore can't read Godot's source code and how it works.
3) I don't know if Godot keeps a track of which methods/scenes/vars are used up until a certain point in the project or not

So I don't know what you want me to do.
If this proposal is ridiculous, then I'll close it, but somebody that actually understands how the engine actually works has to determine that and tell me.

**Comment by pycbouh** [comment] 2020-10-22 18:23
> So I don't know what you want me to do.

As I've said, it's way too vague. In place of "No idea" you should describe how that list of code entities must be formed. What do "required" and "used up" mean is a part of that. You can give some examples at least of things that should and shouldn't be marked as "required" or "used up".

It's not ridiculous per se, but it is unfocused. There are plenty of people who know the ins and outs of the engine, but it's hard to give feedback here because there is no concrete idea presented. Depending on how you want this list to be formed it may or may not be possible or useful. If you want somebody else to give you ideas on how this *might* work, then maybe instead of a proposal you should start on IRC or Discord.

Implementation aside, I'm not even sure that this problem of reducing your project to a minimal repro is algorithmically solvable.   Code that was not executed or file that was not used, but was loaded, can affect the program and cause an error. That, and sifting through a list of unused variables and methods and files doesn't sound less of a work than slicing off parts of your code given that you know *where* it breaks, even if *why* is unknown.

**Comment by Calinou** [comment] 2021-11-13 16:13
Closing, as this is not technically feasible to implement as a core feature. Feel free to experiment with this as an add-on, but it's not guaranteed to make it easier to create MRPs for difficult-to-reproduce issues.

**Closed by Calinou** 2021-11-13 16:13 UTC
Labels: topic:editor
