### ISSUE TITLE
Per-project editor settings

### ISSUE THREAD

**Issue by and-rad** [godotengine/godot-proposals#5649] opened 2022-10-24 10:55 UTC
### Describe the project you are working on

Any project with multiple team members with coding responsibilities and some staff fluctuation.

### Describe the problem or limitation you are having in your project

Godot's editor settings are stored in a file outside the project tree on a per-user basis. This is fine for most scenarios, but it requires team members working on code to share their settings files and keep them in sync in order to keep the code base formatted consistently. Inconsistent settings for trailing whitespace and newlines just lead to diff noise, but mixing tabs and spaces for indentation causes script to fail entirely.

These are some of the user-space settings that cause problems if they're set to different values in the same project:

- Text editor indent type
- Text editor indent size
- Trim trailing whitespace on save

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The mental and administrative overhead of having to sync settings manually could be removed if there was a way to store editor settings per project. That way, I would be able to distribute a common set of editor settings to everyone working on the project.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A file storing editor settings exists in the project tree. These settings are read and applied as default settings on top of Godot's hard-coded defaults. The editor settings stored in the user's directory are applied on top of that, taking top precedence. That way, users still have final say over what settings are applied. (Side note: this means that users can still break editor settings consistency, of course. The difference is that it only happens as a result of direct, intentional action by users instead of by accident.)

The .godot directory would be a good place to store the settings file. This would make it very easy to exclude it from version control if the project has no need for it. It doesn't exist by default and is read only if present. The file is created by copying it over from the user directory. Any changes to the editor settings via the Godot editor are always stored in the user's settings file, the way it is now.

There would still be a manual step involved in copying the user's settings file to the project, but it would only happen once, regardless of the number of team members. Restoring settings items to their default values means restoring to the project's settings first and the hard-coded defaults if the item is not present in the file.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is possible to work around it and there are several ways to do so.

- Team members can share their personal editor settings files and keep them in sync that way.
- Onboarding documents cover all the necessary settings and instruct new project members how to apply them.
- Git hooks check the validity of all committed script files and reject them if they don't meet the coding convention.

### Is there a reason why this should be core and not an add-on in the asset library?

The proposal would change core editor functionality.

**Comment by KoBeWi** [comment] 2022-10-24 11:51
Duplicate of #1480

**Closed by KoBeWi** 2022-10-24 11:51 UTC
