### ISSUE TITLE
Confusing Audio looping

### ISSUE THREAD

**Issue by bitboy85** [godotengine/godot-proposals#5606] opened 2022-10-17 15:04 UTC
### Describe the project you are working on

First steps

### Describe the problem or limitation you are having in your project

As a beginner my first try to play an audio files rtesults in looping the audio.
According to the internet its because it is imported with loop enabled.
It confusing in 2 ways:
1. Lopping audio by default is unexpected (for beginners)
2. You have the loop checkbox in the import tap and additionally in the inspector tab. Disabling "loop" in the inspector part does just nothing, but again as beginner, its epexcetd to set object properties in the inspector, not in the import.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

have one place to enable or disable the loop option

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

/

### Is there a reason why this should be core and not an add-on in the asset library?

/

**Comment by KoBeWi** [comment] 2022-10-17 15:24
> Lopping audio by default is unexpected (for beginners)

It's only done for OGG files (and I think MP3), because they are commonly used for music. For sound effects, WAV is more suited.

> Disabling "loop" in the inspector part does just nothing, but again as beginner, its epexcetd to set object properties in the inspector, not in the import.

You get a huge warning when inspecting imported file and clicking it points you to the Import tab.

**Comment by bitboy85** [comment] 2022-10-17 15:38
OK, it depends on the file type.

But why is the loop checkbox in the inspector menu if it doesn't do anything?

**Comment by KoBeWi** [comment] 2022-10-17 15:45
It's just showing properties of the resource.

This was completely reworked in Godot 4. Audio files have a new import dialog and for anything else imported that still opens in the inspector these properties are disabled.

**Comment by Calinou** [comment] 2022-10-17 20:17
Duplicate of https://github.com/godotengine/godot-proposals/issues/3120.

**Closed by Calinou** 2022-10-17 20:17 UTC
