### ISSUE TITLE
Add option to download individual export templates

### ISSUE THREAD

**Issue by alexfreyre** [godotengine/godot-proposals#2517] opened 2021-03-28 15:45 UTC
### Describe the project you are working on
Specific platform applications with Godot. Sometimes only Linux desktop, sometimes only web.

### Describe the problem or limitation you are having in your project
For each version of Godot I have to download the complete package of export templates to work on a certain platform and not publish my project on all platforms.

**General Problem:**

The user is obliged to download the complete package of export templates regardless of whether he only wants to test or publish his project on whatever platform.

**Problem at the time of work:**

The first problem arises when we work targeting only one platform, but we need the templates for the project to work and test it. Example: HTML5, Android, iOS, Paspberry.

**Problem at release time:**

I usually use Godot to target the Linux desktop platform, therefore I don't need to download the full package because I don't need the other platforms often.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
When the users has a project that needs only one platform, then they can download only the template they need.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add the "export_templates" folder, with each template separated inside, in our download repository:

 https://downloads.tuxfamily.org/godotengine/version/export_templates/

### If this enhancement will not be used often, can it be worked around with a few lines of script?
it's outside the editor

### Is there a reason why this should be core and not an add-on in the asset library?
it'can be core nor an add-on.

**Comment by Calinou** [comment] 2021-03-28 16:27
Duplicate of https://github.com/godotengine/godot-proposals/issues/647.

**Closed by Calinou** 2021-03-28 16:27 UTC
