### ISSUE TITLE
Modulate blending modes

### ISSUE THREAD

**Issue by 2plus2makes5** [godotengine/godot-proposals#2834] opened 2021-06-06 11:16 UTC
### Describe the project you are working on
Dungeon crawler

### Describe the problem or limitation you are having in your project
I would like to achieve the old school hit effect with the sprite(2d and 3d) becoming white or red for an instant, it would also be useful in other cases like selecting an option for example.

Here's a famous example:
![Jbxw](https://user-images.githubusercontent.com/35235318/120922932-4056f200-c6cc-11eb-8287-f3cd827a141c.gif)

Or another example from a dungeon crawler
![source](https://user-images.githubusercontent.com/35235318/120922219-21566100-c6c8-11eb-9ed3-b06f9c22c1a4.gif)
 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I think adding blending modes(add, sub ,multiply, mix) to modulate would help achieving cool effects effortless.

EDIT2:
multiply would obviously be the default mode

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
There should be an option that let us choose the blending mode, after all now modulate is already using the multiply mode.
 
### If this enhancement will not be used often, can it be worked around with a few lines of script?
I think blending modes would help achieving many little but common effects easily. 
It is already possible to achieve this with shaders, but it can get clunky especially if the target already has a shader on it like in my case.

 EDIT:
i forgot to say that modifying a parameter in a shader modifies all the sprites with the same shader unless i make it unique for each sprite.

### Is there a reason why this should be core and not an add-on in the asset library?
Modulate is core so i think that its blending modes should be core too, but i'm not against an add-on.

**Comment by Calinou** [comment] 2021-06-06 14:08
Duplicate of https://github.com/godotengine/godot-proposals/issues/470 and https://github.com/godotengine/godot-proposals/issues/1972.

> EDIT:
> i forgot to say that modifying a parameter in a shader modifies all the sprites with the same shader unless i make it unique for each sprite.

[Godot 4.0 will have global and per-instance shader uniforms](https://godotengine.org/article/godot-40-gets-global-and-instance-shader-uniforms)
, which makes it possible to override uniforms with having to make each shader unique.

**Closed by Calinou** 2021-06-06 14:08 UTC

**Comment by 2plus2makes5** [comment] 2021-06-06 14:58
Thanks for the workaround, it's not really perfect for me since i'm working in 3d with billboards but i guess i can adapt, but as someone already pointed in one of the links overbright doesn't work with all colors.
