### ISSUE TITLE
Support authoring code using the WebAssembly Text Format

### ISSUE THREAD

**Issue by 7ombie** [godotengine/godot-proposals#2877] opened 2021-06-18 00:33 UTC
### Describe the project you are working on

Personally, I'm working on a programming language that offers a nicer syntax and simplified concepts and abstractions, compared to the WebAssembly Text Format (WAT). The specifics of my project are not especially relevant to this feature request though, as the request is for WebAssembly support (which my little project would also benefit from).

### Describe the problem or limitation you are having in your project

Cannot integrate with Godot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Provide some means for WebAssembly binaries to directly interact with Godot.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I do not know. I did ask about WAT support on the Godot Discord, initially in the Beginners channel, then in Programming, but got no reply, so came to GitHub to make a feature request, and was directed to fill this form out.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It likely would be used often. Many web developers use the WebAssembly Text Format to directly author programs (preferring it to C and Rust).

### Is there a reason why this should be core and not an add-on in the asset library?

Not that I know of, but I'm not the best person to ask.

Thank you for considering this.

**Comment by 7ombie** [comment] 2021-06-18 00:36
I really just wanted to ask about WAT support. Is it something people could realistically do with Godot? I only filled out the form above because the directions in the README were very specific that I must, and I was worried a bot would close the issue otherwise.

**Comment by Calinou** [comment] 2021-06-18 00:45
Duplicate of https://github.com/godotengine/godot-proposals/issues/147.

**Closed by Calinou** 2021-06-18 00:45 UTC

**Comment by 7ombie** [comment] 2021-06-18 01:07
Sorry. I did search the issues.
