### ISSUE TITLE
godot 3d skeleton gizmo manipulator

### ISSUE THREAD

**Issue by master172** [godotengine/godot-proposals#3185] opened 2021-08-22 12:14 UTC
### Describe the project you are working on

i am working on a 3d fps shooter game but i need  to add character and enemy models i have modeled them but animating them in blender and then exporting to godot is very hard since if there is any problem with a single animation i have to redo it in blender then export it in godot 

### Describe the problem or limitation you are having in your project

since bones are not manipulatable i am not being able to animate in godot i want to animate it in godot since it is a lot easier and i don't have to worry about the animating again and again if the original one doesn't work out correctly

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

currently godot doesn't does not export bones as nodes so its very hard to make 3d games since making animations in blender and then exporting them in godot is very gruesome making animations in  godot is very easy so i suppose that bones should be exported as nodes so we can manipulate them and animate easily currently godot is the top engine for 2d games but not for 3d because of reasons like this we already have addons to help us with this but most of the time they don't work and setting them up is like eating iron nails please help with this

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

we can have bones exported separately and have the bones property in the skeleton key frameable so we don't have to key each and every gizmo of all bones

### If this enhancement will not be used often, can it be worked around with a few lines of script?

this can be done with a addon but it is not convenient especially to beginners 

### Is there a reason why this should be core and not an add-on in the asset library?

this can improve the 3d editor a lot and also it should be a feature in the core since its a demanded feature and not just a addon that we might want in one project and not in the other

**Comment by Zireael07** [comment] 2021-08-22 12:16
Duplicate of #584.

**Comment by Zireael07** [comment] 2021-08-22 13:01
Nope, opening duplicate requests does NOT 'heat up' the issue, and if you did a search on the Godot repo itself before adding, you'd see it's being worked on in...godotengine/godot#45699

**Comment by pycbouh** [comment] 2021-08-22 13:02
Closing as duplicate per previous comments.

**Closed by pycbouh** 2021-08-22 13:02 UTC
