### ISSUE TITLE
An option, or feature to export a set of Godot primitives to Blender . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1461] opened 2020-09-04 13:35 UTC
**Describe the project you are working on:**
A Tomb Raider game . .

**Describe the problem or limitation you are having in your project:**
I like making concept levels in Godot, but I can't move them to Blender, it would be nice if it was possible to export a ' level ' made in Godot, to Blender, to go from concept to finished game, or so . . Here's prototype level I made, it would be nice if one could make a ' scene ', with only meshinstances, and then ' copy ' it to Blender, as an .obj, with materials, and textures in materials . . Here's what I made in Godot . . .

![Skærmbillede (200)](https://user-images.githubusercontent.com/61069740/92244695-83790000-eec3-11ea-8b1b-a013ab6d55f5.png)

Having this feature would make it a breeze, to make levels in Godot, then when it's done, and after testing game, for right size, scale, at run-time, to then replace each lower-poly concept mesh, with more high-quality Blender models . .

![Skærmbillede (199)](https://user-images.githubusercontent.com/61069740/92244789-aa373680-eec3-11ea-818d-69ee2df37d87.png)

One could make the ' terrain ', in a separate scene, and then export meshinstances to Blender, with materials stored in the materials, so one could have a faster work-flow, from prototyping, or so . . It's very nice, to make a level in Godot, and then being able to move the prototype into Blender, improve some of the meshes, and move back, or so . . It's a suggestion, not sure if it's good, but would be nice <3

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It would just make prototyping much more easy, and fun, since it makes sense to ' build ' the level in Godot, and then do the modelling, in Blender, or so . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
A button, in the Import panel, a simple export panel, that exports all the meshinstances, in a scene, the ' environment ' scene, directly into Blender, or so . . Would be nice work-flow, to me . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I'm not sure, it makes sense to ' build ' the level in Godot, as it's a game making software, to me . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
Well, it'd be a nice feature, wouldn't have to support anything other than exporting all the Godot primitives, or .obj mesh into Blender, as a ' single ' scene . . Not sure, seems nice, or so . .

**Comment by jasperbrooks79** [comment] 2020-09-04 13:37
Also, when the prototype is done in Godot, and one has ' played ' the level, one knows it's exactly correct, having this would be nice, it would only have to support .obj export, for nicer prototyping, the fancy modelling, to high-poly, is done in Blender <3 . . . :O :O . .

**Comment by Calinou** [comment] 2020-09-04 14:32
Duplicate of https://github.com/godotengine/godot-proposals/issues/885.

**Closed by Calinou** 2020-09-04 14:32 UTC
