### ISSUE TITLE
Add an option to apply blendshapes and generate a MeshInstance

### ISSUE THREAD

**Issue by Lexpartizan** [godotengine/godot-proposals#24] opened 2019-09-05 04:57 UTC
**Describe the project you are working on:**

I trying make in-game character generator for godot from project MakeHuman. Like Skyrim or Fallout 3-4.
https://github.com/Lexpartizan/Go_MakeHuman_dot/
https://www.youtube.com/watch?v=cPVjNh2Ki4I
I make blend-file with one model with 200+ shapekeys. Importing to Godot.
I need setup blendshapes value and customize the appearance of the character.
I can this and on my github page have godot project with this example.

**Describe how this feature / enhancement will help your project:**

Then applying all shapes and generate MeshInstance without blend_shapes, because file with blendshapes for each character takes up a lot of memory space.

Mesh after import to Godot with all shapekeys- 100 Mb.
But, you need make resource local for different characters.
1 character on screen - 100 Mb video-memory. This is only vertex - memory.
10 character on screen - 1Gb video-memory.
Without blendshapes - 1 character only 2,5 Mb. Zombie rush possible! And each zombie unique. 
AAA-feature with one small function.

And i dont know how make that. I don't even know if this is possible. 
So, this feature request.
I think the character generator is a very important part of many role-playing games and its effective implementation it just depends on whether it is possible to apply shapekeys and get ready a small version of this mesh. Inefficient it is already working and can be used in games with a small number of characters in the frame, for example in fighting games.
I can make this in blender, but for in-game character generator this must be maked via code.
I asked this question on forums, discord, Q&A, etc and did not get an answer.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because this is the basic function for working with the mesh. And other functions to work with blendshape already have.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
That's possible. So I want to know these lines ;-).

Now I have the nerve to ask a question already on a github. Sorry for that. And sorry for my english. I hope you could understand the problems from this vague description.

**Comment by fire** [comment] 2019-09-05 05:31
I'm having a hard time understanding your request. 

1. Are blend shapes are expensive memory wise? We have 4/6/8 gb video cards and smaller amounts for mobile.
2. In 3.1, blend shapes are expensive on the gpu. There's patches incoming for performance and for blend shape freezing if blend shape is unchanged.
3. In a character generator saving the blend shape to a mesh is probably the most efficient way to save memory. At this level you can save each of the meshes directly with the interpolated vertex value.
4. There are special techniques for crowds that Godot doesn't have

**Comment by Lexpartizan** [comment] 2019-09-05 06:15
*I'm having a hard time understanding your request.*
Sorry for this. English not my language.

1. I have 2 Gb videomemory. And many other users too. f it were random access memory, I would not worry. She's cheap. But video cards cost unbelievable money now.
2. Glad to hear that.
3. Thats exactly what i want in this proposal. How to do this in code?

**Comment by nathanwfranke** [comment] 2019-09-05 12:54
If this could be solved with just a few lines of code, why not implement such a function into one of the mesh classes. This would not effect performance at all

**Comment by Lexpartizan** [comment] 2019-09-05 13:01
So you can give me this few lines of code? 
I would be very grateful.
I really need this very much.

**Comment by Lexpartizan** [comment] 2019-09-05 13:04
I think that the engine is already building the surface I need (How else would a 3D model be displayed from a blendshapes?), but I need a function so that I can get the resulting mesh.

**Comment by nathanwfranke** [comment] 2019-09-05 13:04
> So you can give me this few lines of code?
> I would be very grateful.
> I really need this very much.

I am going by the idea that this could be solved by a script. Sorry, I don't actually know how to do it. Good luck though, keep researching

**Comment by fire** [comment] 2019-09-05 13:07
A possible design could be this:

* Limited to non-mobile editor platforms because of problems fetching mesh from the GPU
* Supply the list of blend shape indexes to merge and which ones to copy
* Copy the original mesh
* Take the blend shape at a linear interpolated value between 0 and 1
* Merge all the target blend shapes to one blend shape
* Copy the untouched blend shapes to the mesh instance
* Save the output as another MeshInstance

**Comment by Lexpartizan** [comment] 2019-09-05 13:15
my "research" did not lead to anything. Not my level programming.
However, I did a lot of boring work to translate most of Makehuman project into a Godot. This work relates more to blender and modeling than to programming. And I think that the character generator (open source) would be useful to the whole community, not just me. But I’m stuck with this optimization, which limits this character editor too much. It would be a shame to throw all the work to the dump when you need only a few lines of code, one function.
So I turn to the community for help.
I'm going to go in for clothes for the characters, but that doesn't make sense if two characters eat up all of the available video memory.
Therefore, I VERY need help with this.

**Comment by Lexpartizan** [comment] 2019-09-05 13:20
Merge all the target blend shapes to one blend shape

How make this in godot? 
I know how to do this in theory. I know how to do it in Blender.

But I don’t know how to do this in a godot with code.

**Comment by fire** [comment] 2019-09-05 13:27
https://github.com/godotengine/godot/blob/34d74840396853f561964c3f4f6e56ac63a57640/scene/resources/surface_tool.cpp#L772

This is for the one blend shape and will get the blend shape mesh. Once you have the blend mesh and the original mesh, you can read the vertexes and linear interpolate with the blend value between 0.0 and 1.0.

https://docs.godotengine.org/en/3.1/classes/class_@gdscript.html#class-gdscript-method-lerp

Break up the three components of the position. Use lerp ( target_mesh_float, blend_shape_float, blend_weight ) over all the vertex locations.

**Comment by Lexpartizan** [comment] 2019-09-05 14:04
Thank you, you gave me something to think about. Yeah, that makes sense. Although I still don't understand how to work with vertices. Not my level. So help is still needed.

**Comment by slapin** [comment] 2019-09-06 22:28
Well, it is possible to do just in plain gdscript. See my repository at https://github.com/gamedev-kindness/make-target
This basically shows why things like this are better implemented in engine as C++ - it is very hard to make them run at adequate speeds. It is just a bit too slow.

What you generally do
1. Find vertex differencies between base mesh and blend shapes (see ArrayMesh documentation for details or ping me on discord or look at code in the above repo for reference).
2. Generate texture using UV coordinates as triangle vertices and vertex difference value as color.
3. In viewer apply the difference to vertex coodrinate (multiply by modifier value).

The problem is that there is no way to modify ArrayMesh vertices en masse with sparce indices - i.e. supplying array of indices and array of deltas and modify mesh in one shot in most effective way. I think this is what mostly needed for the solution to succeed.

**Comment by Lexpartizan** [comment] 2019-09-07 08:46
@slapin  
I don't really understand how to generate UV texture and how to work with colors in it. Also, I think the offset and vertex recalculation of each frame in the viewport will have a negative impact on performance. I will try a couple of weeks, looking at Your code, start working with vertices and get some result on my own. But I will definitely address you on discord (especially since You speak Russian). I understand You're working on a similar project.

**Comment by slapin** [comment] 2019-09-07 13:18
You do not need to update every frame, you just update your vertices once
and then work with the result. The texture is just good way to store deltas.
See SIMS4 GDC video about their editor for more in-depth explanation.

**Comment by slapin** [comment] 2019-09-07 13:24
This proposal explains technical dependency to make proper character customization editors: https://github.com/godotengine/godot-proposals/issues/41

**Comment by Lexpartizan** [comment] 2019-09-07 13:57
I have some progress witn that.
I followed @fire 's advice and looked into @slapin 's code. Now I got a Mesh without blendshapes, until I checked how things are with UV textures and normals. But it's a big step for me. And Yes, there are very few lines of code.
I hope that tomorrow a little bit will straighten him out, of commentary and lay here.
I'm only going to save the value of the keys for each character, and when a character appears on scene he generates a mesh for himself, which is not saved anywhere, but simply hangs in memory until the character is removed from the scene.

**Comment by slapin** [comment] 2019-09-07 14:41
Would be nice if #41 would be added to core, that would save a lot of trouble. Please vote for it on the go.
@fire thanks

**Comment by Lexpartizan** [comment] 2019-09-07 15:13
Oh yeah, thank you so much to everyone who helped me with this. Especially, @fire  and @slapin

**Comment by golddotasksquestions** [comment] 2019-09-08 16:18
> And I think that the character generator (open source) would be useful to the whole community, not just me.

Are you aware of this project:
https://github.com/Grumoth/godot-character-creator
https://www.youtube.com/watch?v=uowc04bAKPg&list=PL1x_Sm7RYv5fHdlsmnGPt2hYEh2wI8Cwv&index=1

**Comment by Lexpartizan** [comment] 2019-09-08 19:33
@golddotasksquestions,
No, thanks for information. Good generator! Download and watch his code tomorrow.
I trying  just make Makehuman for Godot.

**Comment by slapin** [comment] 2019-09-09 04:31
The work was done great, especially artistic side. However there are some
shortcomings with this approach:

1. Use of blend shapes prevents it from working with Godot GLES2 renderer.
2. Use of non-uniform bone scale breaks animations

More advanced examples of this approach is Honey Select rig and Unity UMA
rig - they use dedicated bones for non-uniform scaling.
Also, having transforms constantly set might affect performance for larger
skeletons, so keeping transform on many bones (via set_custom_pose)
might be not a good idea if you want many characters. And I seen that games
using this approach usually have 2-3 characters on screen, no more,
so I guess that is quite expensive. Sims4 approach is much less expensive
as characters end up optimal, without extra bones, without (unnecessary)
blend shapes.

However, if your only platform is PC or current gen consoles, you can use
editor like and then process the result and optimize it as additional pass.
You will need to apply bone scale, apply blend shapes to mesh and remove
blend shapes. Also you will need to pack materials.

**Comment by Lexpartizan** [comment] 2019-09-09 17:12
Is there any way to get ArrayMesh with a regular array with vertices, UV coordinates and so on? From them you can build ArrayMesh, but I would just like to read these values. I use MeshDataTool now, but it is too slow. I would like to get a regular array of vertices and work with them. And then create a new ArrayMesh. Now i have 50 different characters on the screen and 60 frames per second. Video Memory consumption= 35 MB. But I want a faster way to create character. 
In addition, there is one small bug. When I use the mesh in the scene, but he's laying there just as the data (I read blendshapes from this) and the screen is not displayed, it still consumes the VideoMemory (VideoMemory, not RAM!), so I should just reset this value.

**Comment by slapin** [comment] 2019-09-09 19:19
See ArrayMesh doc, I write from memory:
surface_get_arrays()
surface_get_blend_shape_arrays() (IIRC)
You don't need meshes to be a part of MeshInstance for this.

**Comment by Lexpartizan** [comment] 2019-09-09 19:25
Yes, i dont use meshes.
This, by the way, gives opportunity not use blendshapes foe GLES2.
surface_get_arrays() - in Mesh doc, not ArrayMesh doc. That's why I didn't find her right away.

**Comment by Lexpartizan** [comment] 2019-09-10 18:36
So slow!
for i in range(size_vertex_arr):
		basis_mesh[Mesh.ARRAY_VERTEX][i].x=lerp (basis_mesh[Mesh.ARRAY_VERTEX][i].x, blendshp["blndshp"][name_shp][0][i].x, value)
		basis_mesh[Mesh.ARRAY_VERTEX][i].y=lerp (basis_mesh[Mesh.ARRAY_VERTEX][i].y, blendshp["blndshp"][name_shp][0][i].y, value)
		basis_mesh[Mesh.ARRAY_VERTEX][i].z=lerp (basis_mesh[Mesh.ARRAY_VERTEX][i].z, blendshp["blndshp"][name_shp][0][i].z, value)
0.5 sec
if 200 blendshapes - 100 sec for each character...

**Comment by slapin** [comment] 2019-09-10 19:11
do you mean generator part or display part?
Generator part is OK to be slow as it is done once per asset.

Anyway, I work on C++ version of generator now, and it is from 100ms to
1sec for character to generate raw shape data without compression
which is basically triangle rasterization on CPU. I think 100ms will be max
time to apply shape using C++ version.
Godot developers said big NO to all ways to optimize this so only way is
engine fork to add this feature.

**Comment by Lexpartizan** [comment] 2019-09-10 19:26
It is very sad. It is interesting how surface  with blendshapes are rendered. Better, as I understand it, the engine builds the surface we need with the help of the GPU. And then it displays. It remains just in time to get this surface ...
In theory, the work has already been done, it remains to find out how to get the result.

Yes, C ++ will allow you to use this with GLES 2, but it doesn’t interest me much.
100 ms for how many vertices and blends?
GDscript 400-500 ms for 1 blendshape and 16000 verts.

**Comment by slapin** [comment] 2019-09-10 20:00
My mesh is 26K triangles, 76 blend shapes. Code is not quite optimized
though. 100ms is for whole mesh.
But do not consider it a final number, it is mid-development.

**Comment by Lexpartizan** [comment] 2019-09-10 20:08
Strong performance. 1000x faster.

**Comment by slapin** [comment] 2019-09-10 20:15
I guess most performance is gained through less cache misses and using
trivial types. The code is identical to software rasterizer and simply
can't be that slow as it ends up when done using GDScript. Quake does that
in real time 60 frames and more  per second, on old P133 @133 MHz.
Why can't i72600K at 3GHz do this at least 10 times faster, mmm? But ok,
lets it not be faster, but why slower?

**Comment by slapin** [comment] 2019-09-10 21:18
Of course usually there is only one optimal way to do a thing, but
unlimited suboptimal ways.

**Comment by Lexpartizan** [comment] 2019-09-11 05:08
I'll have to change my approach. I wanted to generate characters when adding them to the scene. But now I think to save them in files and that the basic shapekeys (emotions, muscularity, fat, thinness) were present in the mesh. The silver bullet failed.
This wrong way, but i dont see another option.

**Comment by Lexpartizan** [comment] 2019-09-11 05:14
> do you mean generator part or display part?
Generator, offcourse.
>Generator part is OK to be slow
1 character generates 1 minute.
10 characters generates 10 minutes. Its long time.

**Comment by slapin** [comment] 2019-09-11 06:34
You need to generate maps for only one, then apply them. Application is
composition of all maps and takes 10 seconds for each character on my side.
Try the sliders in my demo, each slider change applies ALL maps at once.

**Comment by Lexpartizan** [comment] 2019-09-11 08:33
Application is composition of all maps and takes 10 seconds for each character on my side

Its fast. in my simple way 100 seconds. May I contact you in a discord? It is very difficult to understand your algorithm through google translate. I don’t understand how texture can speed up the application of a bunch of modified shape shapes. In Russian it would be easier))

*each slider change applies ALL maps at once.*

But slider change 1 blendshape. So if i change 1 blendshape through vertex, i achieve same speed.
Or you create image for each blendshape once and mixing images?
I dont understand why texture need.

**Comment by slapin** [comment] 2019-09-11 09:01
Texture is needed to propagate changes to all meshes of different
topologies but having same UVs, like male and female.
Textures are also used to propagate changes to clothes (but using cloth
helpers is better for skirts and robes)
Actually you don't need to think of these as textures, it is more a data
array or heightfield of sorts.

**Comment by Lexpartizan** [comment] 2019-09-11 10:41
I realized that the texture stores the difference between the base model and the result of using shapeshakes. I don’t understand what is the gain in performance, because we already have all these blendhapes in the form of arrays.

For the time being, I see such a way out for my game. I generate characters separately (in advance, not in the game itself) and save them using ResourceSaver.
If you need to change a character, upload it to the character editor and save it there again using ResourceSaver. Not good way, but...
It will not work to generate changes on the fly when loading a character, too slowly.

**Comment by slapin** [comment] 2019-09-11 17:16
My solution is more intended at creation of characters using sliders.
C++ version has promising speed, but will take a few weeks to complete
I guess.
If you do not understand the benefits then it is just not for you. See
Sims4 GDC video, maybe you will, but that does not really matter. You
can do the same thing differently depending on constraints. If you
need quick turnaround and have the same topology among your meshes you
can use blend shapes of course, but they have problem of:
1. Require meshes to have the same topology to work, so can't be
transferred to a different mesh.
2. Basically has the same size as mesh itself.
If you aim at PC-likes, these should be no problem for you (except
maybe load times). My solution aims to be universal CPU-based one
aiming at optimal characters and consuming less memory. If our goals
do not match, that is fine, there are solutions for you already
working out there.
The simplest approach you can have is base your work on editor linked
here earlier, but use more advanced rig with modifier bones. Use of
bones saves you from needing to care about clothes much as you can rig
everything to the same skeleton. This approach will use lots of bones,
so you need to plan your modifiers upfront to avoid hitting limits.

**Comment by Lexpartizan** [comment] 2019-10-12 10:59
All, very thanks for help. 
I reached the speed I needed using gdscript.

this code very slow
```
var array = [][]
for i in range(len (array)):
.....for j in range (len (array[i])):
..........array[i][j] = func()
```
this code faster in 50> times:
```
var array = [][]
for i in range (len (array)):
....var temp = array[i]
....for j in range(len (temp)):
........temp[j]= func()
```

You can download my demo on https://github.com/Lexpartizan/Go_MakeHuman_dot

**Comment by GeorgeS2019** [comment] 2021-07-29 10:31
@Lexpartizan @slapin I do not plan to hijack this discussion, but I need feedback!

Recently Aviv shows the pipeline from [Character Creator 3 to Godot.](https://www.youtube.com/watch?v=VgTf3RuZhhQ)  which **preserve the BLENDSHAPEs in godot.**

I seek feedback on 
- limit of using Character creator 3 mesh, skin and shader license in Godot.
- is there challenge of porting shader to godot for making skin realistic. 

Generally, I am interested on blendshape, skin realism for making realistic 3D character in godot.

**Comment by Lexpartizan** [comment] 2021-08-03 14:55
@GeorgeS2019 
Sorry for delay reply.

First, character studio is paid and expensive. That's why I don't want to get involved with him. Secondly, those blendshapes that are available in the godot, as a result, allow only to control the facial expressions of the character, but not to change his face or body. That is, it is not suitable for an in-game character generator, you get only one character, even if it is of high quality.

Yes, i want to realistic skin too.

**Comment by GeorgeS2019** [comment] 2021-08-03 15:19
@Lexpartizan @fire 
Thanks for the support. 

YES! It is time the Godot community gathers interest to support **in-game character generator** with realistic 3D human with **believable skin** and emotion intense facial animation . Impressive work has progressed in [3D avartar](https://github.com/V-Sekai/godot-vrm/issues/11#issue-880886562).
 
The [Character Creator 3 to Godot (Tutorial)](https://www.youtube.com/watch?v=VgTf3RuZhhQ) shows how to preserve facial animation with way to integrate [skeletal animation from Mixamo](https://www.mixamo.com/)

Hopefully more people join in to this discussion so we could properly formulate a Godot proposal.

**Comment by fire** [comment] 2021-08-03 15:48
I wanted to reiterate that Blendshape to Skinned meshes can be done via https://github.com/electronicarts/dem-bones/tree/master/include/DemBones and is used in recent games like TLOU2 (The Last of us 2). This is a recent GDC talk about this.

**Comment by Lexpartizan** [comment] 2021-08-05 05:23
To be honest, I would prefer something like a modifier in a blender called "surface deform" to realistic skin. This would help with clothing for different characters. So that the clothes have a shrinkage on the figure of the character automatically. And a good skin is made even in substance painter, using quite a standard pbr shader. And I would also really like to have lessons on compute shaders published, since I couldn't really understand what it is, but it seems to me that they are able to solve the problem with generating a small mesh from a large one with a bunch of blendshapes. While I'm doing this on the CPU.

**Comment by slapin** [comment] 2021-08-05 06:30
Compute shaders won't help much with generating one mesh from another. As
for baking the geometry you just need to
lerp your 3D coorinates (and only them) to each subsequent weight, but you
better prep your data so that it is not actual
mesh but just geometry data (Meshes are copied to GPU and your mesh will be
too large with all the blend shapes). The Sims4 approach
is not bad for that (see GDC video/presentation). Other approach would be
like Makehuman, where you keep your various transformations
in relation to base mesh you modify (which is master data for whole
system). For clothes there is Makehuman approach (as mentioned, using
master mesh, each vertex relates to 3 master vertices) or KC:D approach
(using shrunk/inflated versions of clothing, shrink or inflate clothing
until it fits
(i.e. no intersections with lower layer). It is for multilayered cloth.
Both are feasible with Godot and can be implemented (both in C++ though due
to
ineffective data structures in gdscript - manipulate array of floats). PoC
code can be done in gdscript for reference.

**Comment by Lexpartizan** [comment] 2021-08-06 05:39
**Compute shaders won't help much with generating one mesh from another.** 
In fact, the blend shapes in GODOT 4 are already processed by the compute shader. So such shaders are very good for processing data arrays.

In this case, it is quite likely that you will be able to solve not only a simple problem in the form of a lerp between the basic forms, but also prepare data, that is, calculate for each vertex of the clothing which triangle of the body it corresponds to. Of course, the data preparation can be calculated in advance and does not need realtime, but the application of this data (when we are already putting clothes on the character using this data) should be quite fast (it is not necessary to do this in every frame, you can generate meshes when loading a level, for example, but it is still very slow on the CPU).

**Comment by slapin** [comment] 2021-08-06 05:50
You will destroy all the performance by fetching/updating anyway. You will
need to have your data well structured so
to apply simple operation on large amount of data and then fetch. But still
it looks like huge overkill for characters.
People do some interesting simulations though...

**Comment by clayjohn** [comment] 2021-08-06 17:03
I know I am late to the party but ``SurfaceTool`` has a ``create_from_blend_shapes`` function already https://docs.godotengine.org/en/stable/classes/class_surfacetool.html#class-surfacetool-method-create-from-blend-shape

However, I see three things that need to be added for this proposal to be fulfilled effectively:
1. The logic needs to take the BlendShapeMode into account (e.g. normalized or relative)
2. The logic needs to allow for a blending amount (so you can bake halfway between 2 blend shapes for example)
3. The option needs to be exposed to an editor button

I'm not convinced that a GPU-based solution would be valuable enough here. Doing it CPU-side should be nearly as fast and much more convenient.

**Comment by Lexpartizan** [comment] 2021-08-09 11:17
@clayjohn Thank you very much! Especially for specifying a link to the code. I will definitely study and try the method from the surface tool.

**Comment by fire** [comment] 2021-08-09 14:53
Here's a sketch of an api.

```C++
Array MeshInstance3D::bake_custom_blendshapes(Map<StringName, float> blends)
void MeshInstance3D::apply_all_blend_shapes() {
    Map<StringName, float> blends;
    // foreach blend shape insert into blends
    Array baked_mesh = bake_custom_blendshapes(blends);
    mesh = baked_mesh
}
```

**Comment by fire** [comment] 2021-10-02 21:54
Status: Broken from 3.x upgrade.

I am working on a Dem Bones module for Godot Engine.

https://github.com/V-Sekai/godot-dem-bones

> Skinning decomposition refers to the family of automated methods to convert any animated mesh sequences to skinning models and bone transformations. The power and usefulness of these methods in game production pipeline is any arbitrary, highly deformable models controlled by complex deformation rigs can be generated offline, and then converted to skinning model for real time replaying in game engines. This solution allows artists using all possible rigging tools without worrying about the performance penalty in the game play. Skinning decomposition can be used to compress animations of blendshapes, muscle simulation or cloth simulation. Independent components of the method can also be used to track bones animation or to solve skinning weights from range of motion (ROM) poses.

> The state-of-the-art skinning decomposition solution was introduced in the SIGGRAPH Asia 2012 technical paper “Smooth Skinning Decomposition with Rigid Bones” by Binh Le and Zhigang Deng. Since then, this method has been implemented in some animation tools for game production, including Hans Godard's skinning converter, Autodesk Maya’s bake deformer, or SideFX Houdini’s skinning converter, to name a few. At EA, we also use this technique in our content pipeline quite successfully since 2015.

**Comment by fire** [comment] 2022-01-06 01:47
Going to poke this and add it to my list.

**Comment by reduz** [comment] 2022-07-21 16:12
In Godot 4, if you dont touch the skeleton or shape keys, then the model is not updated and there is zero performance loss already.
What we could do is optionally make this a two pass process. First process shapekeys, then skeleton. This way, if shapekeys do not change, then they are not updated.

**Comment by akien-mga** [comment] 2024-04-22 11:03
Implemented by https://github.com/godotengine/godot/pull/76725.

**Closed by akien-mga** 2024-04-22 11:03 UTC
Labels: topic:import, topic:3d, topic:animation
