### ISSUE TITLE
Tip to improve GDscript performance

### ISSUE THREAD

**Issue by be-thomas** [godotengine/godot-proposals#5217] opened 2022-08-20 15:10 UTC
### Describe the project you are working on

I was looking at the GDscript code It seems like an interpreted language.

### Describe the problem or limitation you are having in your project

As evident, Interpreted languages are slow

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

We could translate GDScript bytecode to luajit for massive performance improvements.
As we all know luajit is the fastest scripting language it will be pretty much equivalent to C# or may even surpass it when types are specified through ffi.
I know some platforms do not support JIT, but even when the JIT is off (only for platforms which don't support it), it still destroys pretty much any other scripting language in terms of performance.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I suggest a transpiler which works on bytecode level (simpler to implement) or a source to source compiler

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Either we should implement this as an experimental feature or improve the gdscript performance.

### Is there a reason why this should be core and not an add-on in the asset library?

Performance should be built-in from the core of the engine. So this is a must.

**Comment by Zireael07** [comment] 2022-08-20 15:12
GDScript is tailored to Godot itself. 

There's a whole page in the docs explaining why a custom language instead of Python or Lua. Speaking of, there is Lua for Godot plugin, too

**Comment by Calinou** [comment] 2022-08-20 15:14
Duplicate of https://github.com/godotengine/godot-proposals/issues/3069. There are no plans to implement a JIT compiler, as it's not allowed on iOS.

**Comment by be-thomas** [comment] 2022-08-20 15:15
I'm not suggesting to support lua as programming language.
I'm suggesting to translate gdscript behind the scenes to lua, so that the performance improvements are automatically visible.

**Closed by Calinou** 2022-08-20 15:14 UTC

**Comment by be-thomas** [comment] 2022-08-20 15:19
This is so strange, without even understanding & taking up suggestions, the open source project maintainers close the issue.

**Comment by YuriSizov** [comment] 2022-08-20 15:24
> This is so strange, without even understanding & taking up suggestions, the open source project maintainers close the issue.

It was closed as a _duplicate_. You can add to the existing discussion instead of starting a new one.

That said, general suggestions about performance are not useful. Specific use cases should be presented and investigated. The engine does the heavy-lifting, not the scripting language, so optimizations must be discussed with specifics, not in broad terms.

**Comment by Zireael07** [comment] 2022-08-20 16:44
@be-thomas Transpile to LuaJIT isn't likely to be accepted either because of what Calinou said (iOS won't accept LuaJIT either)
