### ISSUE TITLE
[Shader] Allow using structs with uniform

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot-proposals#5960] opened 2022-12-19 12:58 UTC
### Describe the project you are working on

A RPG GAme

### Describe the problem or limitation you are having in your project

I'm making a pallete swap shaders with the following structure:

```
struct BodyPart
{
	float _min;
	float _max;
	float brightness;
	vec4 color;
};
```

I would like to expose an array of this struct for each body part:

`uniform BodyPart parts[5];`

but godot currently doesnt allow that!

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

this will avoid me to destroy this struct and expose each property manually

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
uniform struct BodyPart
{
	float _min;
	float _max;
	float brightness : hint_range(0.1, 5.0, 0.01);
	vec4 color : source_color;
};
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

nope

### Is there a reason why this should be core and not an add-on in the asset library?

you need to modify source code to allow that!

**Comment by clayjohn** [comment] 2022-12-19 16:08
Duplicate of https://github.com/godotengine/godot-proposals/issues/3569

**Closed by clayjohn** 2022-12-19 16:08 UTC
Labels: topic:shaders
