### ISSUE TITLE
When creating a new project, remember the last used path and keep it as the default

### ISSUE THREAD

**Issue by aanishacharyaa** [godotengine/godot-proposals#2968] opened 2021-07-09 16:05 UTC
### Describe the project you are working on

right now when we create a new project, it always ask for the new path and keeps the home/user directory as the default path.It should remember the old path provided before. for example on creating 1st time I create project in home/user/desktop/godot/prooject-name so I choose "home/user/desktop/godot" as path and create prooject-name folder, So if next time I create a new project ... it should remember "home/user/desktop/godot" and keep it as default.

### Describe the problem or limitation you are having in your project

I need to go to file manager and get to choose my Godot projects folder to make a new folder

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

it helps in many ways. Keeping all  folder of Godot and all projects inside. Once we set it 1st time ... next time no need to choose that Godot folder or in other words the projects folder from file manager again and again

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

it is so simple. Just keep recent folder of where the last project created as default directory next time

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it will be used every time a new project will be created 

### Is there a reason why this should be core and not an add-on in the asset library?

because it is very basic functionality and people are used to it

**Comment by LightningAA** [comment] 2021-07-09 17:04
Not sure if you're aware, but there the default project path can be changed in the editor settings.

**Comment by Calinou** [comment] 2021-07-09 18:27
I have a pull request that addresses this tangentially: https://github.com/godotengine/godot/pull/47724

**Comment by aanishacharyaa** [comment] 2021-07-10 03:24
@Calinou  what you are suggesting is creating a default path "$HOME/Documents/Godot" 

That's not what I am suggesting. I am saying...on 1st time running Godot... 

Either user should be asked for default path or 
if user creates a new custom path... Make it default for all new projects afterwards instead of home directory as it is now a days

**Comment by Calinou** [comment] 2021-09-01 14:25
Duplicate of https://github.com/godotengine/godot-proposals/issues/1312.

**Closed by Calinou** 2021-09-01 14:25 UTC
Labels: topic:editor
