### ISSUE TITLE
Add block volumetric fog

### ISSUE THREAD

**Issue by Altair1024** [godotengine/godot-proposals#1755] opened 2020-11-01 13:32 UTC
**Describe the project you are working on:**
Godot 4 experiment for demo

**Describe the problem or limitation you are having in your project:**
i only do grid modeling the result looks sad and not good volumetric fog

video -> https://youtu.be/UctZ4BThrqQ

![image](https://user-images.githubusercontent.com/17591539/97802968-061a0380-1c58-11eb-8756-d7300681172a.png)
the problem of grid modeling is still visible it is impossible to block the fog and it is not convenient through Add Node -> MeshInstance3D -> PlaneMesh

![image](https://user-images.githubusercontent.com/17591539/97803187-7f662600-1c59-11eb-89fd-42093c2f758c.png)

down without MeshInstance 3D looks awful still visible
![image](https://user-images.githubusercontent.com/17591539/97803201-9442b980-1c59-11eb-9bf8-d6c3f9e0aa5d.png)

only need to block volumetric fog without shadow , UE4 is already there too

**Is there a reason why this should be core and not an add-on in the asset library?:**
i thought that @reduz  seems to have forgotten not added block volumetric fog :)

**Comment by SIsilicon** [comment] 2020-11-02 02:34
This is most likely caused by a low, or lack of shadow bias. My Volumetrics plugin has the same problem.
It should be fixable by adding a volume shadow bias control.

**Comment by Calinou** [comment] 2020-11-02 13:39
As a workaround, try making your walls thicker when possible (and make sure they're always solid).

**Comment by Madaraz1024** [comment] 2020-11-02 17:30
> As a workaround, try making your walls thicker when possible (and make sure they're always solid, with an opaque material on both sides).

I'm not sure now checking UE4 volumetric fog test result 
video -> https://youtu.be/qrAJDvhInZU the walls is all right

volumetric fog the result is not clear I'm experimenting now others demo for godot 4 :+1:

**Comment by reduz** [comment] 2020-11-03 14:01
The one in Unreal is a different type of algorithm (extrusion based), which has different kinds of tradeoffs to the one in Godot. IMO the one in Godot looks more realistic, can read from GI, supports all light types and is more physically correct, but has less resolution (which is also technically more correct because of scattering). I want to add temporal supersampling to it to increase the quality, but you will always have the problem of leaks if you specify too much fog fade in the light settings. You need to reduce this value to eliminate the leaks and ensure walls have some thickness.

In any case, the fog effect is not complete yet, so wait closer to the 4.0 release.

**Comment by reduz** [comment] 2020-11-03 14:05
In any case, you will have to wait until there is some documentation written to understand how to use it and work around those use cases.

**Comment by reduz** [comment] 2020-11-03 14:12
Let me clarify a bit more so its more obvious. The one you are using in Unreal may look nice but its physically (and geometrically) incorrect. Look at this frame as an example:

![image](https://user-images.githubusercontent.com/6265307/97995157-eb18d200-1dc4-11eb-8b9b-feaf5f29ce48.png)

The volumetric should follow the path of the light, and here they are incorrect, it should look like this:

![image](https://user-images.githubusercontent.com/6265307/97995294-17cce980-1dc5-11eb-8746-8a1a2014add8.png)

**Comment by SIsilicon** [comment] 2020-11-03 17:38
> > As a workaround, try making your walls thicker when possible (and make sure they're always solid, with an opaque material on both sides).
> 
> I'm not sure now checking UE4 volumetric fog test result
> video -> https://youtu.be/qrAJDvhInZU the walls is all right
> 
> volumetric fog the result is not clear I'm experimenting now others demo for godot 4 👍

I just watched the video. Is that _really_ volumetric fog? It looks more like a god rays post processing effect.

**Comment by reduz** [comment] 2020-11-03 18:18
@SIsilicon it looks like either extrusion based fog, or screen space volumetric fog, neither of which are physically conserving. But it also seems kinda broken so it might be screen space.

**Comment by SIsilicon** [comment] 2020-11-03 18:37
@reduz Huh. I never heard of extrusion based fog before; when I look it up, I don't get any meaningful results either. :/

**Comment by Madaraz1024** [comment] 2020-11-03 19:49
@reduz @Calinou I have already done a demo project I took from an asset from [UE4](https://www.unrealengine.com/marketplace/en-US/product/a5b6a73fea5340bda9b8ac33d877c9e2) the wall size is 0.125m result below screenshot

![2020-11-03_09-59](https://user-images.githubusercontent.com/17591539/98031704-f2bb9380-1e23-11eb-8ed0-4d98678cbda3.png)
![2020-11-03_22-08](https://user-images.githubusercontent.com/17591539/98031714-f818de00-1e23-11eb-889e-4e5c69606723.png)
![2020-11-03_22-13](https://user-images.githubusercontent.com/17591539/98031722-fa7b3800-1e23-11eb-907f-a2e39cdccf24.png)

i'm have already done a demo project  took an asset from UE4 wall size 0.125m,  wall ok size reason volumetric fog visible wall bypasses sad :)

project file [download](https://drive.google.com/file/d/1ppjkthHESlz6sEJEQfiqlzBSGmITcB_Z/view?usp=sharing) 3.5gb

**Comment by Madaraz1024** [comment] 2020-11-03 20:05
wall 0.125m not enough we think how big the size of the wall is not comfortable

if this topic closes but users will be in trouble 4.0 alpha/beta will be released soon there will be problems the wall thinks that the problem is volumetric fog

**Comment by SIsilicon** [comment] 2020-11-03 20:36
I still think a shadow bias could be implemented to reduce this artifact.
Like push the shadow samples one froxel (frustum voxel) away from the camera; even have it configurable.

**Comment by reduz** [comment] 2020-11-04 02:29
@Madaraz1024 check the fog fade property in the directional light, you can change it to adjust this biasing. The problem is that if you make it too small you will get banding. This is what I need to work on next by implementing temporal reprojection to eliminate it.

**Comment by Madaraz1024** [comment] 2020-11-04 06:42
one modeling sponza is good volumetric fog the only problem is grid models the ceilings is still bypassed. https://youtu.be/4NBHcEhit34

**Comment by reduz** [comment] 2020-11-04 13:06
@Madaraz1024 check my message above on how to adjust bias. For grid interiors you always need a some of thickness if you use directional lights though, else shadowmapping, or even SDFGI will leak light. Its the same with most engines because these techniques are approximate. Only with pure raytracing you avoid leaks.

**Comment by Madaraz1024** [comment] 2020-11-04 18:18
two copy meshs copes  well with volumetric fog

![2020-11-04_20-35](https://user-images.githubusercontent.com/17591539/98149546-69b56280-1ede-11eb-8c28-9aad3008a274.png)
![2020-11-04_20-36](https://user-images.githubusercontent.com/17591539/98149554-6ae68f80-1ede-11eb-9917-f847ab64f29c.png)

result great :+1: but not convenient copy meshs wall need thickness not all assets designer modeling the standard always short size accurate, users will submit issues volumetric fog on github alpha 1+ further, etc.
![unknown](https://user-images.githubusercontent.com/17591539/98149665-8fdb0280-1ede-11eb-92ad-1830af4d02d3.png)

**Comment by reduz** [comment] 2021-02-06 15:42
I think most problems in this issue are solved by #45765 so please test again after merged.

**Comment by UnknownS1024** [comment] 2021-02-09 19:32
@reduz 
godot df9c98e, the wall is ok but the problem is the ceiling https://youtu.be/Vw8v_x2EtNo

I added meshinstance the name block_vfog is good but nevertheless the mesh material is visible white needs invisibility example similar `MeshInstance > Geometry > Cast Shadow > Shadow Only`

can add `MeshInstance > Geometry > Cast Shadow > Volumetric Fog Only`

![out](https://user-images.githubusercontent.com/17591539/107415920-ea5ead00-6b24-11eb-86b6-280fb52d0b42.gif)


I think enough volumetric fog is great :)

**Comment by Calinou** [comment] 2021-12-25 23:28
Closing, as the [new FogVolume nodes in `master`](https://github.com/godotengine/godot/pull/53353) allow you to constrain fog to specific areas (by using a positive density value) and exclude fog in specific areas (by using a negative density value).

**Closed by Calinou** 2021-12-25 23:28 UTC
Labels: topic:rendering
