### ISSUE TITLE
Provide export templates for every platform separately

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#2811] opened 2021-06-02 07:21 UTC
### Describe the problem or limitation you are having in your project
The export template was a little large, in Godot 3.3, about 500M+, for me, often I just need the windows and android.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I think maybe split each platform export template, people can download who needs .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
In offical website, user choose their platform export template(s) to local, In the GodotEditor import all templates once.

**Comment by Xrayez** [comment] 2021-06-02 09:31
See #1001.

I think it's possible to split the export templates from `tpz` file and repack it again. While working on [Goost](https://goostengine.github.io/), I couldn't able to compile UWP export templates, but even without those I was able to [install a custom pack of export templates](https://goost.readthedocs.io/en/latest/usage/installation.html#installing-export-templates) in the Godot's editor anyway.

**Comment by pycbouh** [comment] 2021-06-02 10:14
There were talks about it in the context of the built-in template downloader as well, but I guess no proposal was made out of it.

**Comment by Calinou** [comment] 2021-06-02 16:46
Duplicate of https://github.com/godotengine/godot-proposals/issues/647.

**Closed by Calinou** 2021-06-02 16:46 UTC
Labels: topic:buildsystem, topic:editor, topic:export
