### ISSUE TITLE
Search uncommented/commented lines

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#5859] opened 2022-11-27 12:32 UTC
### Describe the project you are working on

An FPS.

### Describe the problem or limitation you are having in your project

I have a lot of commented `print()` lines, and very few uncommented `print()` lines, and when I need to find a `print()` line that isn't uncommented, it takes a long time to find.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Being able to chose to search commented and uncommented lines would make searches easier to find and ignore commented lines left in for debugging.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

An option in the Find/Replace search.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Definitely not.

### Is there a reason why this should be core and not an add-on in the asset library?

It would need to be integrated with the core search functionality.

**Comment by jakebarnwell** [comment] 2022-11-27 12:41
Out of curiosity, does reges search work for you? You can search for something like:
```
#.*print 
```
to find commented-out print statements.

And to find non-commented print statements,
```
\s*print
```

**Comment by elvisish** [comment] 2022-11-27 14:13
> Out of curiosity, does regex search work for you? You can search for something like:
> 
> ```
> #.*print 
> ```
> 
> to find commented-out print statements. (Technically risks a few false positives, but should be close enough.)
> 
> And to find non-commented print statements,
> 
> ```
> \s*print
> ```

I tried that but unfortunately it didn’t bring anything up in search, this is with regular Find and Replace?

**Comment by Calinou** [comment] 2022-11-27 15:30
Duplicate of https://github.com/godotengine/godot-proposals/issues/563.

**Closed by Calinou** 2022-11-27 15:30 UTC

**Comment by elvisish** [comment] 2022-12-01 10:46
> Out of curiosity, does regex search work for you? You can search for something like:
> ```
> #.*print 
> ```
> to find commented-out print statements. (Technically risks a few false positives, but should be close enough.)
> 
> And to find non-commented print statements,
> ```
> \s*print
> ```

Should this work in 3.5?
