### ISSUE TITLE
Add commit/engine version to project.godot

### ISSUE THREAD

**Issue by jordigcs** [godotengine/godot-proposals#6090] opened 2023-01-13 19:19 UTC
### Describe the project you are working on

A 2D RPG game

### Describe the problem or limitation you are having in your project

I've been using the up to date `master` version of the engine for a while now, but have decided to lock my version of the engine to a specific commit. I have custom modules designed for my game that require me to rebuild the engine, but as I also do contributions to the engine, I don't always know which commit I last built my game with.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding the commit/engine version to the project file would help with collaboration, version control, and may even help with detecting regressions (If the previous version can also be stored alongside the current version)

If you use version control for your project, you know exactly what engine version is being currently used by the project, so others easily know what version/commit to use.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When you open a project, the version you're currently using is added to the `project.godot`
`engine_version = v4.0.beta.custom_build [d3fc9d9e4]`
If there's already an `engine_version` defined, the project manager will ask if you want to open a project made with a different version of the engine. If yes, `previous_engine_version` will be set. This way, if there's a regression, you know exactly the interval of commits that need to be checked.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It *could* be a module or editor plugin.

### Is there a reason why this should be core and not an add-on in the asset library?

Improves version control for games made with the engine.

**Comment by YuriSizov** [comment] 2023-01-13 20:04
This is a duplicate of https://github.com/godotengine/godot-proposals/issues/4355, which has been implemented already. See this comment https://github.com/godotengine/godot-proposals/issues/4355#issuecomment-1156451870 for details.

**Closed by YuriSizov** 2023-01-13 20:04 UTC

**Comment by jordigcs** [comment] 2023-01-13 20:22
Oh, don't know how I didn't notice. thanks!
