### ISSUE TITLE
Base class, extended overwrite

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot-proposals#2343] opened 2021-02-24 10:37 UTC
### Describe the problem or limitation you are having in your project
Currently if you wish to write some functions, that can be reused on all nodes/scripts, you're pretty much limited on using a script that contains static functions

Aside from it looking really hacky eg(SomeLibrary.calculate_this())
You cannot make your own rpc functions

Implement a propagate call system for your gui, without having to write the same code

Have all your nodes automatically do the certain behaviors
Like let's say you want a button that automatically emits a sound, well you can do that but you'd have to pretty much repeat the same code on all the other variants of button, and this is pretty much true throughout the node system

Extend base class and have built in child classes inherit it, without either having to modify the godots source code or pretty much writing your own node tree and not being able to reuse built in ones

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I think this feature would allow for a much cleaner code, and lots of possibilities

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`extend_overwrite Node`
`# Now all the built it nodes that inherits from Node will now inherit here`
`# and will error if there's a conflict with a built in child class`

`func rpc_peers(peers : PoolIntArray, args : Array) -> void:`
`    for peer in peers:`
`    rpc_peer(peer, args)`

`func _notification(what : int) -> void:`
`    match what:`
`    NOTIFICATION_INSTANCED : propagate_call("_instanced")`

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Probably not

**Comment by pycbouh** [comment] 2021-02-24 10:41
Duplicate of #1167.

**Closed by pycbouh** 2021-02-24 10:41 UTC
