### ISSUE TITLE
Add the ability for inputs to be available even when the window is not in focus

### ISSUE THREAD

**Issue by Gamemap** [godotengine/godot-proposals#2541] opened 2021-04-01 17:50 UTC
### Describe the project you are working on.
Voice chat 
### Describe the problem or limitation you have in your project.
When the window is in the background, you cannot press a key to activate a function. (In other programs like OBS, you can press a key to activate something).
### Describe the function/enhancement and how it helps overcome the problem or limitation.
Add a boolean value to make an input work only when the window is only in focus or also in the background.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams.
if Input.is_action_pressed("ui_accept", false):       (only if focused window = false)
### If this extension is not used often, can it be bypassed with a few lines of script?
No.
### Is there a reason why this should be core and not an add-on in the asset library?
I think many others creating a program (like a timer or something) would need such a feature as well.

**Comment by Calinou** [comment] 2021-04-01 19:20
Duplicate of https://github.com/godotengine/godot-proposals/issues/1919.

**Closed by Calinou** 2021-04-01 19:20 UTC
