### ISSUE TITLE
Display cell coords at mouse in tilemap editor

### ISSUE THREAD

**Issue by kit-solent** [godotengine/godot-proposals#6806] opened 2023-05-04 02:51 UTC
### Describe the project you are working on

A 2D,  tilemap based, platformer.

### Describe the problem or limitation you are having in your project

The tilemap editor does not display the cell coordinates of the current mouse position.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a display to show the current cell coordinates where your mouse is (like in godot 3)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

<img width="154" alt="image" src="https://user-images.githubusercontent.com/85214318/236098778-b3e256f7-66df-4e8d-bfab-4ba414d1b767.png">

This could work exactly the same as it did in godot 3.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This could probably be worked around with an editor plugin but I think it is useful enough to be an inherent feature.

### Is there a reason why this should be core and not an add-on in the asset library?

Once again this could probably be worked around with an asset library add-on but I think it is useful enough to be an inherent feature.

**Comment by Calinou** [comment] 2023-05-04 05:32
- Duplicate of https://github.com/godotengine/godot-proposals/issues/5792.

**Closed by Calinou** 2023-05-04 05:32 UTC
