### ISSUE TITLE
Documentation website should allow crowd sourced comments like PHP's docs

### ISSUE THREAD

**Issue by Wavesonics** [godotengine/godot-proposals#503] opened 2020-02-21 21:09 UTC
**Describe the project you are working on:**
Nuclear reactor simulation

**Describe the problem or limitation you are having in your project:**
Finding good examples of how to use specific Godot classes and features.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The Godot documentation is getting better and better. But in my opinion, one of PHP's best feature's is it's crowd sourced "cook book" style comments on each item in it's documentation.
Example: https://www.php.net/manual/en/function.strtotime.php

Seeing a simple example of something in use is often the quickest way to understand how it works.

In addition to that, users can post sample code for common use cases, further accelerating everyone's development.

And lastly, users can call out common pit falls, and potential work-arounds.

Simple Stackoverflow style up/down vote can help filter the content for quality.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
We would need a server backend and account system. Possibly leveraging the Asset Libraries account system.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It can't.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It could in theory be a 3rd party site.

**Comment by Calinou** [comment] 2020-02-21 21:31
Duplicate of #481.

**Closed by Calinou** 2020-02-21 21:31 UTC
