### ISSUE TITLE
Add edit option "Rename" in Script Editor

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#2857] opened 2021-06-12 07:06 UTC
### Describe the project you are working on
any
### Describe the problem or limitation you are having in your project
If I rename a field, which occurs often, I have to go through all my scripts accessing it and rename it also there.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
everywhere the field is used, will be replaced by the new name
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Just like in Eclipse, where you can rightclick and select Refactor->Rename
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No
### Is there a reason why this should be core and not an add-on in the asset library?
Yes, it is **very** useful

**Comment by golddotasksquestions** [comment] 2021-06-12 10:04
I agree, I have been looking for this too a number of times.
Currently you would have to rightclick and select "Show in Filesystem", then rightclick on the file that has been highlighted in the FileSystem and select "Rename ..." or press F2.

**Comment by Paulb23** [comment] 2021-06-12 10:09
Duplicate of #899

**Closed by Paulb23** 2021-06-12 10:09 UTC

**Comment by golddotasksquestions** [comment] 2021-06-12 10:43
@Paulb23 
While this might be somewhat related, this is not a duplicate of #899
This proposal is only about renaming the script file in the script list panel. It asks for the same functionality the "Rename ..." has in the File System. #899 is about variables inside a script and elsewhere. It's a lot more complex.
