### ISSUE TITLE
Ability to run the game (debug) inside the editor.

### ISSUE THREAD

**Issue by zevertaix** [godotengine/godot-proposals#4796] opened 2022-07-02 10:44 UTC
### Describe the project you are working on

Create a new tab with the name "debug". All industrial engines have this capability. It is very convenient. In Unity, this tab is called "Game", and when you click the "Play" button, this tab opens with the game running.

### Describe the problem or limitation you are having in your project

Rather inconvenient debugging.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Start debugging directly in the editor.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

-

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No. I think this function will be important and convenient for everyone.

### Is there a reason why this should be core and not an add-on in the asset library?

It's part of the engine, and good practice, I think that's why it should be built into the engine.

**Comment by YuriSizov** [comment] 2022-07-02 11:37
Duplicate of https://github.com/godotengine/godot-proposals/issues/1864.

In future, please use the Discussions tab to open general idea discussions. Proposal Issues require technical implementation description, especially for something as complex as this.

**Closed by YuriSizov** 2022-07-02 11:37 UTC
