### ISSUE TITLE
Godot Editor on iPad

### ISSUE THREAD

**Issue by Drakenroft** [godotengine/godot-proposals#9130] opened 2024-02-19 14:14 UTC
### Describe the project you are working on

/

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

iPad is the most world-wide used tabled platform, it is used from everyone from normal users,artists to advanced users during mobility. It already offer all the tools needed to develop for 3D and 2D the only real missing piece of software missing is a full fledge native Game Engine.
Being Godot Editor basically at the pinnacle of cross-platform support, literally running on every current machine ad OS (i think only arm64 Windows is currectly missing besides iPad), i think Godot should come to iPad too empowering many common users to be able to start and learn game development, like it already happens for Android.
As far as i have understood compiling Godot for iPad at the moment is as simple as:
**_scons p=ios target=editor dev_build=yes arch=arm64_**
But there are minor problemes that comes with it like the impossibility to spawn subprocess on iOS/ipadOS
Thus being said i saw that a youtuber has made Godot Editor run successfully with a "minor" effort
( [](https://www.youtube.com/watch?v=n6Igyjj3QYQ) )

So that's it my feature proposal is to port Godot Editor to iPad, it would for sure it would increase the already extremely large userbase and would also be the first to come to that platform, making possibile in the future to make even "crazier" port like the editor running on Vision Pro which could be extremely interesting

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

/

### Is there a reason why this should be core and not an add-on in the asset library?

/

**Comment by bruvzg** [comment] 2024-02-19 14:25
Duplicate of https://github.com/godotengine/godot-proposals/issues/1061

Also, see https://github.com/godotengine/godot-proposals/issues/8151 (required to actually implement it).

- Godot uses multiple processes to work, and this is impossible to do on non-jailbroken iOS. You can build the editor, and hack it to open specific project (see https://github.com/bruvzg/godot/commit/2b8ae2d397ab25d86d63a8e0de45f52a006f3d88), but it won't have a proper project manager, won't be able to run projects and practically unusable.
- It's won't be accepted to the App Store, since it's capable of running external scripts.

**Comment by KoBeWi** [comment] 2024-02-19 15:50
Closing as duplicate.

**Closed by KoBeWi** 2024-02-19 15:50 UTC
