### ISSUE TITLE
Add support for ++ and -- shorthands in GDScript

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot-proposals#5799] opened 2022-11-17 08:39 UTC
### Describe the project you are working on

Learning GDScript and writing code with a long background coding in C-languages, javascript and php

### Describe the problem or limitation you are having in your project

Being able to quickly add or subtract 1 to a variable is quite common, and in many languages there's a shorthand for this: ++ or --. As in `x++` being the same as `x=x+1`

In GDScript however, this is not supported. There still is the += and -= meaning you can write `x+=1` instead of `x=x+1` but this is still a little more cumbersome to me, and I frequently find my self typing ++ without thinking about it. Only to then be reminded its not supported in GDScript

![Screenshot 2022-11-17 at 09 24 21](https://user-images.githubusercontent.com/17763524/202394659-b5ebcc2d-ad48-4564-a4b3-4cd18d5d4f9c.jpg)

I'm surprised this hasn't been suggested or discussed before as it's such a common thing, but I've found no such issues in this repo or the official gototengine repo

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add support for ++ and -- as implemented in C and other languages in GDScript 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Since this is present in many other languages and relatively simple I'm sure there's a standard way this is implmented in other languages. Maybe even just as a simple macro that replaces the pattern `++` with `+=1` at the end of lines when parsing the code could be good enough in case there are trickier cases of for example `func(x++,x)` to handle.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, as explained above it can easily be worked around. But I think it's quite a small change that would remove a little stumbling block/annoyance for new users learning GDScript with experience working in other languages.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a code GDScript language feature

**Comment by Mickeon** [comment] 2022-11-17 09:34
This was rejected in https://github.com/godotengine/godot-proposals/issues/2869. The reasoning for it can be found in the replies.

**Comment by YuriSizov** [comment] 2022-11-17 09:39
Indeed, this is a duplicate of an already rejected proposal, and at this point we are not ready to reconsider GDScript's features.

**Closed** 2022-11-17 09:39 UTC
