### ISSUE TITLE
Make the script template Godot picks by default editor-wide instead of just per project

### ISSUE THREAD

**Issue by ShawkMusic** [godotengine/godot-proposals#2585] opened 2021-04-11 01:55 UTC
### Describe the project you are working on
n/a
### Describe the problem or limitation you are having in your project
I always want to use the `Empty` script template, but every time I create a new project and create a new script, it defaults back to the `Default` script template for that project and I have to select the `Empty` script template again so Godot defaults to that one for that project. It's just a minor detail but it's really annoying and is one more thing that makes new project creation dreadful in Godot. 
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Godot should either make the script it defaults to editor-wide instead of project-wide (so if I pick a script template on one project it will default to picking that for all projects instead of just the project I picked the script on),
or it should add a setting in the Editor settings to let me disable Godot picking the last script template I used and instead let me choose which script I want it to select by default for every project.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
n/a
### If this enhancement will not be used often, can it be worked around with a few lines of script?
no
### Is there a reason why this should be core and not an add-on in the asset library?
assets arent editor-wide, which is what this needs.

**Comment by KoBeWi** [comment] 2021-04-11 12:40
Duplicate of #1899

**Closed by KoBeWi** 2021-04-11 12:40 UTC
Labels: topic:editor
