### ISSUE TITLE
Allow Signals to continue being sent when mouse is pressed

### ISSUE THREAD

**Issue by MrJoshBowman** [godotengine/godot-proposals#2592] opened 2021-04-12 06:10 UTC
I'm working on a game that allows for grid based selection where I want the user to be able to click and drag the mouse around a grid to select various squares and not just as a box selection.

Currently, from what I've been able to research, once a node is clicked and the `event` registered, no other events or signals can be sent until the mouse is released. The means that if I click inside one square and drag across to another, no `mouse_exited()` or `mouse_entered()` signal is sent until i release the mouse. This limitation is very frustrating, as there isn't even an option to switch this on or off as an option, and means that currently any dragging around a UI using simple signals has to be turned into something else needlessly complex.

I would very much appreciate the option for MouseButton events not to stop other signals from occurring. 

this could be made possible with something like `set_mouse_capture( )` [default: true] which retains the original way things are currently, but set to 'false' allows for the mouse to continue sending signals to other nodes as it moves over them while pressed.

**Comment by Calinou** [comment] 2021-04-12 14:49
Duplicate of https://github.com/godotengine/godot/issues/20881 (this is considered a bug).

**Closed by Calinou** 2021-04-12 14:49 UTC
