### ISSUE TITLE
Expose Make Local option to tool scripts, shortcuts and command palette

### ISSUE THREAD

**Issue by jabcross** [godotengine/godot-proposals#3573] opened 2021-11-19 11:53 UTC
### Describe the project you are working on

A game using Kenney's Space tiles

### Describe the problem or limitation you are having in your project

I want to automate the process of creating the scene that will be converted to a MeshLibrary (to be used with GridMap).

Kenney's Space Kit (https://www.kenney.nl/assets/space-kit) come with FBX, DAE and GLTF files, but they are interpreted as nested scenes by Godot.

![Screenshot from 2021-11-19 08-46-06](https://user-images.githubusercontent.com/6402237/142617811-bcfced45-8dc5-4790-9d3e-71c20c75e0dc.png)

I tried writing a Tool script that automatically brings the mesh to the top level, but I couldn't get anything to work. I could enable Editable Children from code, but not Make Local.

In the end, I had to manually click Make Local for every mesh. There was no shortcut or command palette option.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Expose the Make Local option to script, and allow it to be bound to a shortcut and accessible from the Command Palette.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Could be a Node method intended for use in tool scripts, similar to `set_editable_instance()`.
Also include it in the Command Palette and in as a bindable command in the editor shortcuts.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Can't be worked around.

Automating the importing of asset packs is a very common use case.

### Is there a reason why this should be core and not an add-on in the asset library?

Can't be written as an add-on.

**Comment by KoBeWi** [comment] 2021-11-19 11:56
If you want to set scene as local, set its `filename` property (`scene_file_path` in 4.0) to empty string.

**Comment by jabcross** [comment] 2021-12-09 10:12
> If you want to set scene as local, set its `filename` property (`scene_file_path` in 4.0) to empty string.

Did not know that. Maybe the method should be created anyways, with documentation that explains what it does; it's nice to have some parity between the methods, the right-click dropdown and the bindable editor commands.

**Comment by jabcross** [comment] 2022-01-02 21:14
The above method doesn't seem to work with nested scenes in 3.4. Only the top-level node remains.

**Comment by pycbouh** [comment] 2022-01-12 17:31
This is actually a duplicate of https://github.com/godotengine/godot-proposals/issues/278.

**Closed by pycbouh** 2022-01-12 17:31 UTC
Labels: topic:editor

**Comment by ChristophTheSchmidt** [comment] 2023-08-26 16:35
"Make scene local by code" <-- Maybe this helps to find this topic faster if your searching for a code Make local option

**Comment by plsholdmybeer** [comment] 2024-02-07 12:00
node.filename = ""
works in 3.5.3 to "Make scene local by code" / "make local from code"

**Comment by plsholdmybeer** [comment] 2024-02-07 12:04
func recursive_own_children_to_scene(node):
	for child in node.get_children():
		child.set_owner(get_scene())
		recursive_own_children_to_scene(child)

recursive_own_children_to_scene(node)
node.filename = ""

this works in 3.5.3 to make scene local by code / make local from code
