### ISSUE TITLE
Implement a built-in Editor auto-update functionality

### ISSUE THREAD

**Issue by KraXen72** [godotengine/godot-proposals#2089] opened 2021-01-08 19:13 UTC
Last time i tired out godot, the editor didn't have autoupdate. i checked all the issues in this and the main repo, but i couldn't find anything related to autoupdates. 

if the editor already has autoupdate, please comment it under this issue and close it. thanks.

### Describe the problem or limitation you are having in your project
I have to manually check for editor updates

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
feature: autoupdate. it will remove the need to automatically check for new editor updates

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
proposal: every time you run the editor, it will check github if the editor has a new release. if the editor has an update available, there would be 2 buttons.
- update
- later
update button would replace the popout content with a progress bar an percentage for downloading the new editor release in the background. after it reaching 100%, it would replace all the old editor files with the new files automatically and then show a new popup:
update sucessful.
and a 'launch the editor' button, which would close this popup and launch the updated editor.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
there could be an option in the settings to never check for updates.

### Is there a reason why this should be core and not an add-on in the asset library?
this should be the core since it would update the core editor.

**Comment by pycbouh** [comment] 2021-01-08 19:35
See also #1132, #1458.

You can use Steam or itch Launcher to get automatic updates. It is also considered a dangerous practice to update engine like that, since even small changes can bring incompatibilities or phantom bugs.

**Comment by Calinou** [comment] 2021-01-08 20:07
Duplicate of https://github.com/godotengine/godot-proposals/issues/1132.

**Closed by Calinou** 2021-01-08 20:07 UTC
Labels: topic:editor
