### ISSUE TITLE
Improve the ' theme ' resource so it works a bit better . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2446] opened 2021-03-11 08:09 UTC
### Describe the project you are working on
A Tomb raider project . .

### Describe the problem or limitation you are having in your project
I'm trying to make my own theme, but there are two major bugs . . When I click, to make a ' Theme based on the current theme ', and I use the default Godot theme, it makes an error, in the vertical distance, between nodes, in the node tree, ie. it doesn't 1 - to - 1 recreate the current theme, though it mostly works . . Not sure that's a bug, but if I make a theme, based on the current theme, the font space, or node spacing looks different . .
<img width="617" alt="2021-03-11 0901" src="https://user-images.githubusercontent.com/61069740/110754690-604f5480-8248-11eb-89e3-926a83945772.png">
Notice that the ' same ' list, when making a ' copy ' of the current theme, doesn't match what was, before <3

This happens, after reloading once, at first it looks nice, after one engine re-start, the list is ' different ', and I'm not sure what number it is, that is missing, on the long ' theme editor ' list <3 <3 . . .

Now, the second thing is, the theme editor could be a lot nicer, if one could ' click ' on any element in the engine, and be taken to the ' specific ' part, in the theme editor . . so, if I click the ' 2D ' icon, ' 3D ' icon, ' Script ' icon or, ' Assetlib ' icon, it takes me to that place, in the theme editor, WHILE the theme editor window, is open . . Right now, one has to look through a massive list, where it isn't really clear where to look . .

Anyway, right now the theme editor is so difficult to use, also requires restarts for many things, which makes it feel really slow, sadly . . for instance, changing the opacity of the lines, major, or minor in GraphEdit requires a restart, to see the effect . . Anyway, I hope the ' theme ' editor can get some attention, as right now it's really difficult, and there are a few bugs, not sure if there are more, that makes it tough, to use . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, I'd like a custom theme, where the text, and icons for the 3D, 2D, Script, and Assetlib are bigger, and makes it more clear, that these are very important, for using the engine . . Also, just looks cool . . But, I've looked for the ' right ' place to click, to change that font size, and I simply can't find it . . Maybe it be better, if when theme editor is open, one just ' clicks ' a button, or font, or node, and one is taken to the relevant part, of the theme editor, faster . . :OO Thx

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Make the theme editor more user-friendly, faster and, intuitive, in general . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't change the code, in the theme editor, as a beginner <3

### Is there a reason why this should be core and not an add-on in the asset library?
Not sure, but it's nice to be able to make Godot more custom . . <3 <3 . . .

**Comment by Calinou** [comment] 2021-03-11 10:19
Duplicate of https://github.com/godotengine/godot-proposals/issues/1791.

> When I click, to make a ' Theme based on the current theme ', and I use the default Godot theme, it makes an error, in the vertical distance, between nodes, in the node tree, ie. it doesn't 1 - to - 1 recreate the current theme, though it mostly works . . Not sure that's a bug, but if I make a theme, based on the current theme, the font space, or node spacing looks different . .

This sounds like a bug to report on the [main Godot repository](https://github.com/godotengine/godot)
.

**Closed by Calinou** 2021-03-11 10:19 UTC

**Comment by pycbouh** [comment] 2021-03-11 10:31
> When I click, to make a ' Theme based on the current theme ', and I use the default Godot theme, it makes an error, in the vertical distance, between nodes, in the node tree, ie. it doesn't 1 - to - 1 recreate the current theme, though it mostly works . . Not sure that's a bug, but if I make a theme, based on the current theme, the font space, or node spacing looks different . .

This is because in the current implementation of the theme editor [fonts are not actually copied](https://github.com/godotengine/godot/blob/master/editor/plugins/theme_editor_plugin.cpp#L520-L522).

This is already addressed by my work in https://github.com/godotengine/godot/pull/46593 and https://github.com/godotengine/godot/pull/46808
