### ISSUE TITLE
Add a @tool_button annotation to create inspector buttons for tool scripts

### ISSUE THREAD

**Issue by vpellen** [godotengine/godot-proposals#6430] opened 2023-03-04 23:05 UTC
### Describe the project you are working on

Currently working on some tool scripts to assist with animation, but this is a very general concept.

### Describe the problem or limitation you are having in your project

I want to be able to manually trigger a method call through the node inspector.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A simple annotation that creates a button in the inspector and links it directly to a function call would be a sufficient solution for most basic use cases.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```GDScript
@tool
extends Node2D

@tool_button(increase_size, "Make me bigger!")

func increase_size():
    scale *= 2
```
This is the most simple form I can think of, an annotation with two parameters: a Callable and a String. All this would do is drop a labeled button in the inspector in the same way an `@export`ed variable would show up. Clicking the button would trigger the callable. The label could probably be optional.
You could probably get feature-creepy with this, but I'm trying to think of a minimalist solution that would solve the broadest array of problems. A third optional parameter for an icon, maybe?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There is actually a hack that approximates the necessary functionality: Export a boolean property with a getter that always returns false and a setter which does nothing but trigger a method call. You get a perpetually empty checkbox that triggers a method when clicked. It's not elegant, but it does work:
```GDScript
@tool
extends Node2D

@export var make_me_bigger : bool:
    get:
        return false
    set(b):
        increase_size()

func increase_size():
    scale *= 2
```

### Is there a reason why this should be core and not an add-on in the asset library?

I think there's actually be an add-on somewhere that does something similar to this, but "create a button that triggers a function" is probably a common enough use case for tool script writers that it warrants a single-line annotation.

**Comment by KoBeWi** [comment] 2023-03-05 02:15
Duplicate of #2149

**Closed by KoBeWi** 2023-03-05 02:15 UTC
