### ISSUE TITLE
Support for large models with several textures . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3991] opened 2022-02-18 04:24 UTC
### Describe the project you are working on

A 3D game, cars, etc . .

### Describe the problem or limitation you are having in your project

I need to make some large enemies, for a game, example . . .

![image](https://user-images.githubusercontent.com/83387915/154615311-37a89a01-84ef-4bbc-8a13-e67d41446ac8.png)

I need some sort of system, where a model can have several textures, to allow for something like 4 4K textures, or, 8 . . Right now, it can be done with several materials, problem is, I think that means the object is rendered, sort-of twice . . 

I was thinking, if there was a system, I hear UDIM is never used for game engines, sort-of for movies . . So, got no idea, basically I just need a big model, with detailed textures, that look good at close, medium, and, also in distance . . .

Was thinking, someone here might have some ideas, for making large, even massive 3D models, and, having a large number of textures, without needing several materials, I hear that is not the best way, to make textures, etc . .

I'd like UDIM support, but, what I've been thinking is, something where only the textures on screen, of a model, maybe are rendered . . This is easier for static objects, simply make it a split model, so on . . For big, animated creatures, or so . . It's not that easy, to split a model, so on . . .

I don't know how to do this, wondering if there's some new import format that supports it . . . Ideally, the character, or enemy-boss, the different textures would only be loaded, as needed, ie. texture occlusion, for a complicated model . . Another thing would be texture-LOD, but I think mipmap system does that, automatically . . .

So, asking for support for large, also animated objects, creatures . . That have a large number of textures, or, a few big one's, distributed over the mesh . . This is easy in Blender, since one renders one image, or, renders an animated each frame, not sure it's possible in a game engine, have seen it in some video - games, best example is Chronos in 'God of War 3', hoping to get support, for something like that . . . It was a PS3 title, thinking they might have used some weird optimizations, or so . . .

![image](https://user-images.githubusercontent.com/83387915/154616110-d10dcfb4-102a-4576-b25d-8122e150d71a.png)

That's what I need, got no idea how it was done, or, how it was possible, on a PS3 . . . :-OO

I'm thinking something like UDIM, where parts of the model, sort-of textures are only in memory, or rendered, maybe like occlusion culling . . Some optimized texture occlusion, that supports several textures, on a 3D object . . . Some sort, of dynamic loading, of textures, based on maybe AABB, that are generated, for an object . .

Well, the thing I'm asking for is UDIM support, but, not sure that works for game - engines, could one make something like UDIM, that was better, for game - engines . . . Just need a model, with different textures, perhaps loaded depending on what one sees, similar, to occlusion, also with LOD ( mipmaps ), and, dynamic details, etc . .

As far as I know, texture limit for a model is about 4K, in game engines . . Need something like 4 x 4K textures, or 8, on a single mesh . . Is there a way to add this, for say big bosses, or, animated meshes, so on . . . Thx . . . :-(( 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I don't know what it's called, I'm thinking UDIM, with texture and, distance culling, for the well textures . . . 

I need to make the Midgaard serpent, massive boss, and, a single 4K texture is not enough . . Is there a way to get support, for something like that, maybe UDIM, and, optimize it for game - engines, etc . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, don't really understand why one can't have several materials, on one object, I read it means the 3D object has to be perhaps drawn twice, so it's not ideal . . . Is there a way to do this, maybe make an object with several materials, and, it's converted to some Godot format, that allows for more, or larger textures on a 3D model, that's the only idea I have, hoping there are some 3D, texture experts here, etc . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I got no idea, this is a technical challenge, well, just asking, it might be easy, or, someone here has an idea, thanks . . !

### Is there a reason why this should be core and not an add-on in the asset library?

Well, don't really know, it's for a project, if nothing else, I'd like UDIM support, that'd be the same, perhaps with some texture occlusion, so one only has the textures in memory, of the parts of the creature, that is visible . . . I'd just use different materials, each one having a texture, but, people say it's not the best way, thx . . ! :-OO 

Sorry, if this is bit vague, not sure if someone here knows something, how to do that, was possible on PS3, so, is there some neat way, etc . .

**Comment by Zireael07** [comment] 2022-02-18 11:07
Yes, every material is a draw call. Fortunately for you, draw calls matter less and less on modern hardware.
For your use case of needing 4 4k textures, you might have some luck with AtlasTexture that Vulkan offers (no idea what the max size is, I think 16kx16k?)

Chronos and UDIM pulled some extremely specific and fancy tricks to optimize even further, and since Godot is supposed to be a general engine, I am doubtful those tricks could be pulled off here.

**Comment by charlesmlamb** [comment] 2022-02-18 15:29
Well, the argument is, to be able to have those big enemies, in some way, running fast . . . It is a use - case, in the dev - world, however, it's not seen in that many games . . . I just have need, for a big boss, something that is 300 m long, and, the player can get close to, perhaps, walk on, so on . . 

I'll try, and do my best, using several materials . . Was hoping that might be optimized, I sort-of heard UDIM was better, bec. it lowered draw - calls, while, keeping the same textures, however, was told on a forum, UDIM was mainly used for movies, I got no idea, just want a big - boss, for a game . . .

**Comment by Rodeo-McCabe** [comment] 2022-02-20 17:02
You need "texture masking" (perhaps also known under some other terms). https://www.youtube.com/watch?v=r5R-JSVCRyw

The video is done using Unreal, but this can be done in Godot too. The concepts are the same.

**Comment by Calinou** [comment] 2022-02-20 17:09
Duplicate of https://github.com/godotengine/godot-proposals/issues/651. However, consider that basic detail texturing (with UV2 layout) is already supported within Godot's SpatialMaterial. This allows you to have a secondary texture that overlays the main texture, with a greater or lower scale than the main texture.

**Closed by Calinou** 2022-02-20 17:09 UTC
Labels: topic:rendering, topic:3d
