### ISSUE TITLE
Add more array methods: first_custom, last_custom, count_custom

### ISSUE THREAD

**Issue by SlashScreen** [godotengine/godot-proposals#6889] opened 2023-05-15 23:58 UTC
### Describe the project you are working on

This is not unique to my project, but one project I am working on requires a lot of array traversals searching for elements that satisfy specific conditions. I feel there is a gap in Array functionality (because sort_custom already exists), and this would plug it,

### Describe the problem or limitation you are having in your project

There is no built-in methods to search for the first, last, and to count elements that satisfy custom conditions implemented in a Callable, the way you can filter or sort_custom.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the following methods:
`find_custom(fn:Callable)` will return the index of the first element of an array where the callable fn will return true.
`rfind_custom(fn:Callable)` will return the index of the last element of an array where the callable fn will return true.
`count_custom(fn:Callable)` will return the count of all elements of the array where the callable fn will return true.

I attempted to name the functions to fit the naming style of the rest of the functions in the Array class. However, I do not like it- I would rather name it something like `find_by()`. But my gripes with the Array function naming conventions are beyond the scope of this proposal.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here is a sketch implementation I have already created:
```cpp
int Array::find_custom(const Callable& p_callable, int p_from = 0) const {
	if (_p->array.size() == 0) {
		return -1;
	}

	if (p_from < 0 || size() == 0) {
		return -1;
	}

	const Variant* argptrs[1];

	for (int i = p_from; i < size(); i++) {
		argptrs[0] = &get(i);

		Variant result;
		Callable::CallError ce;

		p_callable.callp(argptrs, 1, result, ce);
		if (ce.error != Callable::CallError::CALL_OK) {
			ERR_FAIL_V_MSG(-1, "Error calling method from 'first_custom': " + Variant::get_callable_error_text(p_callable, argptrs, 1, ce));
		}
		// Return as soon as possible
		if (result.operator bool()) {
			return i;
		}
	}

	return -1;
}

int Array::rfind_custom(const Callable& p_callable, int p_from = -1) const {
	if (_p->array.size() == 0) {
		return -1;
	}

	if (p_from < 0) {
		// Relative offset from the end
		p_from = _p->array.size() + p_from;
	}
	if (p_from < 0 || p_from >= _p->array.size()) {
		// Limit to array boundaries
		p_from = _p->array.size() - 1;
	}

	const Variant* argptrs[1];

	for (int i = p_from; i >= 0; i--) {
		argptrs[0] = &get(i);

		Variant result;
		Callable::CallError ce;

		p_callable.callp(argptrs, 1, result, ce);
		if (ce.error != Callable::CallError::CALL_OK) {
			ERR_FAIL_V_MSG(-1, "Error calling method from 'last_custom': " + Variant::get_callable_error_text(p_callable, argptrs, 1, ce));
		}
		// Return as soon as possible
		if (result.operator bool()) {
			return i;
		}
	}

	return -1;
}

int Array::count_custom(const Callable& p_callable) const {
	int count = 0;
	const Variant* argptrs[1];

	for (int i = 0; i < size(); i++) {
		argptrs[0] = &get(i);

		Variant result;
		Callable::CallError ce;

		p_callable.callp(argptrs, 1, result, ce);
		if (ce.error != Callable::CallError::CALL_OK) {
			ERR_FAIL_V_MSG(0, "Error calling method from 'count_custom': " + Variant::get_callable_error_text(p_callable, argptrs, 1, ce));
		}
		// Increase count if passes
		if (result.operator bool()) {
			count++;
		}
	}

	return count;
}
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, one can simply create a loop to accomplish the same task. But it must be done every time, and could be solved by patching this gap in GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

This adds core Array functionality.

**Comment by AThousandShips** [comment] 2023-08-03 08:33
`count_custom` can so easily be worked around with `reduce` that I don't think it's worth to add

**Comment by maximkulkin** [comment] 2023-09-17 09:46
Duplicate of #6006

**Comment by AThousandShips** [comment] 2023-09-17 09:48
This one is more detailed, so will consolidate here

**Comment by idbrii** [comment] 2023-09-24 15:14
I'd suggested the name `find_custom` to match existing `_custom` functions on a duplicate proposal and @Maran23 [pointed out](https://github.com/godotengine/godot-proposals/issues/6006#issuecomment-1368059997):
            

> I'm in favor of `find_first` as it is more descriptive.
>I know exactly what to expect, namely the **first** element that fits.
>While `find_custom` does not really specify that. And what does `custom` mean in this context anway?
>
>I wonder why the `bsearch` methods were named this way.

>EDIT: The `bsearch` methods are not comparable to this usecase.
They try to find the index of a value via binary search. The `custom` in this context means, that a developer can specify an own comparator for the binary search algorithm, e.g. if the default one is not sufficient.
>There are also other methods like `sort` and `sort_custom` out there, where `sort_custom` lets you specify an own comparator if the default sorting is not sufficient.

I agree that custom doesn't really fit and `find_if` is clearer.

**Comment by BtheDestroyer** [comment] 2023-09-27 04:39
I personally prefer `find_if` since that's taking name to match functionality directly from the C++ STL.

Perhaps `find_first` could be an alternative function which returns the _value_ that was found where `find_if` only returns the index (similar to the C++ STL's `std::find_if` returning an iterator).

```gdscript
var data: Array[Dictionary] = []

static func _is_active(entry: Dictionary) -> bool:
  return entry.get("active")

func get_active_entry_index() -> int:
  return data.find(_is_active)
  
func get_active_entry() -> Dictionary:
  return data.find_first(_is_active)
```

**Comment by SlashScreen** [comment] 2023-09-27 09:27
I'd personally prefer `find_by` and `sort_by`, but I wanted the new functions to match the preexisting `sort_custom`.

**Comment by CsloudX** [comment] 2024-04-20 10:29
For me, I prefer like `filter_first(method:Callable)/filter_last(method:Callable)`(return the first/last element match filter else return return null)

for `first_custom`, I need coding like this:
```
var idx = arr.first_custom(func(i):return i.id==id)
if idx>=0:
	ele = arr[idx]
else:
	ele = null
```
for `filter_first`, coding like this:
```
ele = arr.filter_first(func(i):return i.id==id)
```

**Closed** 2024-09-20 14:15 UTC
Labels: topic:core
