### ISSUE TITLE
Improve Resource-Creation context in inspector

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot-proposals#842] opened 2020-05-15 12:00 UTC
**Describe the project you are working on:**
Idle progress rpg

**Describe the problem or limitation you are having in your project:**
Whenever i want to define a new resource in an "export (Resource) var" field in the inspector, i am greeted by hundreds of Resources. So maybe i want a certain one, i will have to scroll (depending on naming) for a while (luckily i have an unlockeable scrolll-wheel) which costs money and disctracts from the creative process.

This problem gets kind of fixed with https://github.com/godotengine/godot-proposals/issues/18 but even if you can already limit those resources, in an rpg i could quickly still have many Resources for a certain type.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Make it so that when the Resource-context opens, you can type in parts of the Name you are searching for and it will jump to the next name that is the closest to the written.

Here it would buffer the input for a certain amount of time and reset it after the amount of time.

So for example, i would search for a Resource with class_name "R_Item" on open i would type on the keyboard "i" "t" "e" and it would jump to the next closest one.

Here it could also be possible to work with a small search-bar at the top of the context which would limit the options in the inspector. On freeing the search-bar, all options would reappear.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The mockup is focused on rough layout or estimate functionality and is not a specific dictate. Its mainly meant to communicate my idea and not represent the final expectations. As this is mainly about the functionality i didnt bother with the icons.:

On clicking an empty resource field or the context-button in the inspector a context-menu like this would appear:

![image](https://user-images.githubusercontent.com/24807557/82047554-49d17e80-96b3-11ea-8b3d-d3f0634b4067.png)

Now by typing something in the search bar it would automatically limit to the options that had  (i chose the search bar over the implicit typing in the keyboard, as it might be something that people new to godot might miss)

![image](https://user-images.githubusercontent.com/24807557/82047822-c4020300-96b3-11ea-8630-573fe6534426.png)

![image](https://user-images.githubusercontent.com/24807557/82047865-d54b0f80-96b3-11ea-820e-63ec0688be72.png)

The "Edit etc." options are hidden below, in a collapse menu, so they are always available (not just at the very bottom of the context) but hideable. This menu might remember if the user had it open the last time the user was in a resource context (or had it collapsed)

![image](https://user-images.githubusercontent.com/24807557/82048207-8487e680-96b4-11ea-932f-1ab053b943bb.png)

This menu could also just open to the bottom (not pushing into the options)

Mockup-Project:
[Godot proposal resource context.zip](https://github.com/godotengine/godot-proposals/files/4634176/Godot.proposal.resource.context.zip)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
The feature proposal: https://github.com/godotengine/godot-proposals/issues/18 might help to limit this by a lot for most of my cases, but i still think its much better for everyone if the resource context got improved in its useability.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It improves the user experience with Resources by a lot (imo)

**Comment by Jummit** [comment] 2020-05-15 12:45
Note PopupMenu already has a `allow_search` property, which allows to navigate with letter keys.
This is just strangely not enabled on most of the dropdowns in the editor.

**Comment by Calinou** [comment] 2020-05-15 14:01
Duplicate of #43.

**Closed by Calinou** 2020-05-15 14:01 UTC

**Comment by Reneator** [comment] 2020-05-15 15:46
I personally dont think this is a duplicate as its approaching the drop-down menu with a different approach. Questionable why it cant stand by itself...

**Comment by Calinou** [comment] 2020-05-15 19:11
@Reneator We prefer centralizing discussions related to a single *problem* in a single proposal. Feel free to post your mockups in the issue I linked.

**Comment by Reneator** [comment] 2020-05-16 06:12
@Reneator Ok, thank you for the reply/clarification. Befor it, it felt more like a slap to the face. Will do!
