### ISSUE TITLE
Time scale individual for each node

### ISSUE THREAD

**Issue by ghsoares** [godotengine/godot-proposals#3425] opened 2021-10-14 12:33 UTC
### Describe the project you are working on

A fast-paced arcade game

### Describe the problem or limitation you are having in your project

I want to add a feature to my game where I slow down time in a given area, so any body that enters this area it becomes slower than the bodies outside this area. I wanted to be able to override physics time scale and idle time scale, individually for each node.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The feature is two overridable functions: `_get_physics_time_scale` and `_get_idle_time_scale` for any `Node` type. These functions return 1.0 by default, but you can override it to return any time scale. These time scales only impacts the individual node.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In the start of the physics processing of a node (including internal), the engine would call `_get_physics_time_scale`, which stores the returned number in a cached variable internally (let's call it `c_physics_time_scale`). So whenever the function `get_physics_process_delta_time` is called, the returned value is multiplied by `c_physics_time_scale`, so there is no need to call `_get_physics_time_scale` everytime `get_physics_process_delta_time` is called.

The same would work for idle processing, but it would call `_get_idle_time_scale` and store it to `c_idle_time_scale` which is used in `get_process_delta_time`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Nope, there is currently no way to change internal processing behaviour.

### Is there a reason why this should be core and not an add-on in the asset library?

Because requires internal physics and idle processing behaviour change.

**Comment by Zireael07** [comment] 2021-10-14 12:40
Been already suggested and rejected (I can't recall the issue # though), because "you can work around it in scripts" to put it short.

**Comment by pycbouh** [comment] 2021-10-14 12:53
Indeed. Duplicate of https://github.com/godotengine/godot-proposals/issues/2507

**Closed as completed by pycbouh** 2021-10-14 12:53 UTC
Labels: topic:core, archived
