### ISSUE TITLE
Implement a RichTextEdit Control

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#3644] opened 2021-12-08 07:49 UTC
### Describe the project you are working on

NO-GAME application

### Describe the problem or limitation you are having in your project

I wish my user who don't know bbcode syntex can custom a panel to show bbcode.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There was RichTextLabel can show bbcode, and I need a RichTextEdit for edit like Qt's QTextEdit

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Implement a RichTextEdit, it have below methods:
```
set_bbcode(text)
get_bbocde()
set_select_bold(yes:bool)
set_select_underline(yes:bool)
set_select_link_to(url)
...
```
### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know how to implement it by GDScript

### Is there a reason why this should be core and not an add-on in the asset library?

The RichTextEdit show a basic Control

**Comment by Calinou** [comment] 2021-12-08 15:58
Duplicate of https://github.com/godotengine/godot-proposals/issues/1781.

**Closed by Calinou** 2021-12-08 15:58 UTC
Labels: topic:gui
