### ISSUE TITLE
Add support for importing MS Excel .csv files to Godot

### ISSUE THREAD

**Issue by FabPei** [godotengine/godot-proposals#8757] opened 2023-12-31 11:10 UTC
### Describe the project you are working on

A normal game which uses a .csv translation file for its translations.

### Describe the problem or limitation you are having in your project

When creating a .csv file for translations, i use the very common programm Microsoft Excel. When exporting/saving a .csv file with excel and the moving it to a Godot project folder, Godot will throw the error "Returning: ERR_PARSE_ERROR".
If i copy the same content from the MS Excel .csv file to a different data programm such as Google docs (spreadsheets) and then export/save as .csv and move it to Godot, the translation file is imported without any problem.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When trying to import a translation file (.csv), Godot should try to parse the file for an MS Excel variant if there is an error on the first try.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Sadly, i cant provide any code, but here is the solution of Python: https://docs.python.org/3/library/codecs.html
While importing a .csv file to Python, "utf-8-sig" can be used as an argument to load MS Excel exported .csv files.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

While i am quite unsure on the length of this potential feature, i believe there should be other programming languages which already implemented some kind of fix.
I the workload needed is bigger than expected, a simple hint on the official Godot documentation should be a good option to prevent other users experiencing this bug.

### Is there a reason why this should be core and not an add-on in the asset library?

Microsoft Excel is used by more than 99,9% of all user who work on any tabulary data, thus i believe that nearly every user will experience this bug when creating their first translation for their game. This fix could prevent similar bug reports, where users dont know how to fix this issue.

https://github.com/godotengine/godot/issues/86491#issuecomment-1872913849

**Comment by RedMser** [comment] 2023-12-31 17:26
Excel includes a Byte order mark in the CSV which is what breaks the parsing here. [`String::parse_utf8`](https://github.com/godotengine/godot/blob/master/core/string/ustring.cpp#L1809) supports handling the BOM, so should be used here.

**Comment by AThousandShips** [comment] 2023-12-31 17:33
There's indeed something else wrong here, I'm not sure it's as simple as just the bom, unless it's on its own line or something like that, as the processing does handle that character, haven't confirmed but I think using `get_line` or `get_csv_line` works correctly in itself

**Comment by AThousandShips** [comment] 2023-12-31 17:59
As mentioned on the issue, this isn't about BOM at all, the file is in ISO-8859-15, which isn't a supported encoding

**Comment by FabPei** [comment] 2023-12-31 18:19
> As mentioned on the issue, this isn't about BOM at all, the file is in ISO-8859-15, which isn't a supported encoding

I saw your other comment. Maybe instead of a feature proposal, a short notice on the official Godot documentation on translation site would help? https://docs.godotengine.org/en/stable/tutorials/i18n/internationalizing_games.html

**Comment by AThousandShips** [comment] 2023-12-31 18:22
Might be useful, but it's a bit complicated to mark down other programs that doesn't follow standards or behave in strange ways, hard to track

**Comment by FabPei** [comment] 2023-12-31 18:53
Oh it doesnt tell you much, there is the UTF 8 option tho, but i attached the resulting csv file, it still wont get imported.
Here is the Excel overview:
![Screenshot 2023-12-31 194750](https://github.com/godotengine/godot-proposals/assets/80212635/0ee9e6ab-ec17-4813-8e0c-9efbd5da6270)

[GitHub issue UTF 8.csv](https://github.com/godotengine/godot-proposals/files/13801989/GitHub.issue.UTF.8.csv)

I can fully understand your concerns regarding programs, but wouldn't mentioning the most common used program package in the world hinder current and future bugs/issue reports?
Maybe changing "Most spreadsheet editors..." to "Most spreadsheet editors (besides Microsoft Excel)..." would already solve it?

**Comment by AThousandShips** [comment] 2023-12-31 18:57
It's still using colon, so you need to change that, the fact that you can't change that part manually for the import file if it doesn't import, the problem is that it uses the wrong delimiter

**Comment by AThousandShips** [comment] 2024-01-01 11:17
Closing as the underlying issue isn't so much this but the import process in general as described in the bug report, keeping the discussion over there as it's not specific to this particular format as such

**Closed by AThousandShips** 2024-01-01 11:17 UTC
Labels: topic:editor
