### ISSUE TITLE
Reload scene when importing 3d model change

### ISSUE THREAD

**Issue by TerraDev64** [godotengine/godot-proposals#4876] opened 2022-07-14 21:32 UTC
### Describe the project you are working on

A 3D Game where many 3d models gets used.

### Describe the problem or limitation you are having in your project

 When having a scene open, where a Model (Inherited as a scene) is in the scene and changing the model and exporting it as a glb, it says it can be saved. Saving the scene will break the model change.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When importing a asset, either 3d model or something else, the current open scene will reload itself so it also got the new change.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When exporting the changed model to godot. Godot will save the scene and then start importing the change. After that godot will reload the scene, so the new change will be inside of it.

Make it as a setting in the engine settings. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used often because it's the main part of Model working and importing.

### Is there a reason why this should be core and not an add-on in the asset library?

Because it's a basic feature like in Unity

**Comment by Calinou** [comment] 2022-07-14 22:22
Duplicate of https://github.com/godotengine/godot/issues/38853.

**Closed by Calinou** 2022-07-14 22:22 UTC
