### ISSUE TITLE
Default .gd script naming should follow convention

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot-proposals#2521] opened 2021-03-29 05:37 UTC
### Describe the project you are working on
Any Godot Engine project. 

### Describe the problem or limitation you are having in your project
When I attempt to attach a new script to a Node, the script name defaults to the node name that uses PascalCase. (Steam's Godot Engine version as of 2021-03-29)

For Example:
1. Create a MyNode node.
2. Attach a new script.
3. Notice the default name is "MyNode.gd" instead of "my_node.gd" which would be the Godot Engine's documented naming convention. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Instead of creating default gdscript file name using PascalCase, it should be converted to snake_case by default, so we won't have to manually change the name in order to follow [GDscript naming conventions](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_styleguide.html?highlight=Naming#naming-conventions)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
In the Godot Engine source code, parse the Node name into snake_case before populating the GDScript file name's text box.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No. The only way to "fix" this is to break coding conventions and use snake_case for Node names as well.

### Is there a reason why this should be core and not an add-on in the asset library?
Because we both follow and encourage others to follow the standard conventions, without having to make them think and manually "correct" it. :)

**Comment by pycbouh** [comment] 2021-03-29 08:05
Duplicate of https://github.com/godotengine/godot-proposals/issues/1211

**Closed by pycbouh** 2021-03-29 08:05 UTC
