### ISSUE TITLE
Add update engine button

### ISSUE THREAD

**Issue by al1-ce** [godotengine/godot-proposals#2771] opened 2021-05-25 15:15 UTC
### Describe the project you are working on
Godot Project Manager

### Describe the problem or limitation you are having in your project
The problem lies in updating engine. It can be tedious to track all of the engine updates, downloading them, re-doing links, etc. The only real issue with this problem is on people who got engine manually from web-site and not from steam or itch.io, which is the most.
The solution will also help with keeping track on updates, which is may or not be essential.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Proposal solution would be to simply add update button or/and update manager to project manager that will automatically update executable and API (for c# users).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Button when using latest version:
![godotproposallatest](https://user-images.githubusercontent.com/60989682/119520672-2a1f6c80-bd83-11eb-883b-97a4c24460af.png)
Button when update is available:
![godotproposalupdate](https://user-images.githubusercontent.com/60989682/119520684-2d1a5d00-bd83-11eb-96e7-b00b7ef15360.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It's core update.

### Is there a reason why this should be core and not an add-on in the asset library?
It's essential part of software production cycle and should be core update.

**Comment by pycbouh** [comment] 2021-05-25 15:22
Duplicate of #1132.

**Closed by pycbouh** 2021-05-25 15:22 UTC
