### ISSUE TITLE
Remove the section Autoload under Project --> Project Settings --> Filesystem because this has its own tab.

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot-proposals#1082] opened 2020-06-18 19:10 UTC
**Describe the project you are working on:**
Reaction game
**Describe the problem or limitation you are having in your project:**
It's useless that it exists twice.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The project settings would be a tiny little bit clearer.
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![Godot Project Settings without Autoload in Filesystem](https://user-images.githubusercontent.com/60623532/85061960-f9fd4000-b1a7-11ea-9dec-a604771c7f7e.png)
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No
**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes, it's quickly done.

**Comment by Calinou** [comment] 2020-06-19 07:48
Indeed, the Autoload section should be hidden from the list of settings as it has a dedicated tab.

**Comment by hinlopen** [comment] 2020-06-19 08:31
This would fix godotengine/godot#39639 as well

**Comment by Calinou** [comment] 2021-11-05 22:46
Duplicate of https://github.com/godotengine/godot/issues/39639.

**Closed by Calinou** 2021-11-05 22:46 UTC
Labels: topic:editor
