### ISSUE TITLE
Make an anaglyph 3D camera effect . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1907] opened 2020-11-29 14:09 UTC
### Describe the project you are working on
A Tomb raider game, adventure, horror, magic, puzzle . .

### Describe the problem or limitation you are having in your project
I would liked a anaglyph 3D camera node, and someone here kindly helped me make a plug-in, and it's amazing, wonderful . . But, it's also very slow . . I don't know how to contact a particular user here, on the pages, atm . . But, I was thinking if it was possible to improve that plug-in, so instead of ' blending ' the two images, that it made an ' interlaced ' image, where every other line was from one camera, and other line, from the other camera . . I think at 4K, it will be difficult to notice, and could look really good . . Or, add a feature to the plug-in, where it makes the image, in a checker-board interlaced format, like PS4 Pro, or so, to increase performance . . The plug-in is literally amazing, and looks 80 - 90 % as good, as the BEST anaglyph images I've seen, but there's also that, black-and-white images, look REALLY good in anaglyph mode, bec. there's no color problems, from the glasses, color images often looks faded or, 'skewed' towards a greenish-cyan color, atm . .

![2020-11-29 1451](https://user-images.githubusercontent.com/61069740/100543775-6fd6fe80-3252-11eb-94e8-1b75009e999c.jpg)
Checkerboard where, every other line is red camera, other is the cyan camera . .

![2020-11-29 1452](https://user-images.githubusercontent.com/61069740/100543789-7ebdb100-3252-11eb-9a0c-2ab1c565f01e.jpg)

Interlaced, where every other line is from one camera, the red tint camera, and the other is from cyan . .

Also, maybe it could be faster to make a mode, where the image is grey-scale, and so the colors needed to be mixed are only one RGBA channel, since that might lower the computations, from ' blending ' the images, if that could make it faster . . The current plug-in, made by SiSilicon, a user, or mod here, is simply AMAZING, but it runs VERY slow, lowers frame-rate from 144 FPS, to 10 - 20 FPS, for a simple scene . . The 3D effect is rock-solid, already, but the rate at which it lowers the FPS rate, is a bit too much . . I wished to ask, if it was possible the plug-in could be improved, also since 3D glasses for RED-CYAN work on any monitor, right away, and the cost for glasses, is super low, found one pair, for 8 dollars, on a site . . I was hoping maybe some people could get a pair, and experiment with the 3D effect, I think you'll be honestly impressed with the quality . . The big thing is, it looks really nice for color images, but it has no ' color range ' distortion, at all, so when looking at black-and-white images, it looks the same color as, with glasses on and, not glasses on . . I was hoping someone might help make the best possible anaglyph plug-in, the current one is already super-cool, pro 3D effect <3 . . But, so slow, sadly . . :(( also, maybe if others had some good suggestions, I was thinking of making a black-and-white game only, in it, bec. it's super cool . .

Last, I was wondering if one could off-set the ' bland ' colors, when looking at color images, by changing the color range, so the colors that get ' down-graded ', or so, were more bright, ie. blue would look super-blue, red look more faded, or so, so color pictures look 1-to-1, when wearing the glasses . .

<img width="598" alt="Skærmbillede (722)" src="https://user-images.githubusercontent.com/61069740/100544080-9ea1a480-3253-11eb-9210-6afedf318e6d.png">

The problem with anaglyph is that all the pictures, except grey-scale, are a bit skewed, maybe one could off-set that, by boosting the ' faded ' colors, in a color range, to get ' 1-to-1 ' full color range, with the glasses . .

![2020-11-29 1502](https://user-images.githubusercontent.com/61069740/100544117-df99b900-3253-11eb-8354-ffb567947af5.jpg)

Maybe by over-saturating the colors that ' disappear ', one could make it look a bit cooler, or such . . The current plug-in is amazing, and I now fully agree it should be a plug-in, I really hope it can be made faster, perhaps by using inter-lacing . . Another thing that might make it faster, was if every other interlaced line was from one camera, or so . . It's a rock-solid usable plug-in already, but I was hoping there might be added some features, to make it run faster, maybe interlacing is less hard-ware intensive, than blending each pixel, though it gives the best result . .

Thank you, for an amazing plug-in, I was stunned by how it worked, the 3D effect is 80 - 90 % as good, as the best 3D images I've ever seen, without changing any settings, maybe the ' convergence ' value need, to be tweaked . . And, if somebody wants to work on it, would be a good idea if you got some cheap glasses, bec. it's literally mind-blowing, cool, as is . . :O :O

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
It's really cool, that it's a plug-in, but it runs very slow, with even just a few 3D objects, on my nVidia 1050 Ti laptop, old game laptop . . If it could be improved, it'd be amazing, not sure what best optimize tech is, for such things . . <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, the current plug-in is amazing, except for the very hard drop, in performance, my system goes from rock-solid 4K 60 FPS, to maybe 10 - 12 FPS, sometimes 5, could it be optimized, Thank you . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't do this cool stuff, it's super - tough, for a noob coder, I use visual script, and have never made a shader, just done a little testing, in visual shaders, and it was really basic, simple, noob . . Please, help . . <3

### Is there a reason why this should be core and not an add-on in the asset library?
I think it's good, as an downloadable plug-in, since many won't use it, but the current one is such an amazing plug-in, if it could be made to run faster, or so, well it'd be usable right away, for much more users, bec. of the speed, also interlacing on 4K isn't really noticable, when looking at it, AFAIK <3 Thanks <3 <3 . .

So, amazing job so far, but can it be optimized, Thanks . . .

**Comment by jasperbrooks79** [comment] 2020-11-29 14:13
I'm not sure about all this stuff, as a beginner, but maybe over-saturating the colors, that are down-played, could make a nicer image, also checkerboard interlacing might be better, than linear, normal interlacing, at lower resolution . . I was hoping someone could help me make it, but don't know how to contact individual mods here, I think his name was SiSilicon, Thanks . .

Also, if someone had even better ideas for optimizing it, it'd be amazing, I have no idea, sadly . .

**Comment by jasperbrooks79** [comment] 2020-11-29 14:19
last, since screen are wide-screen now, a vertical interlacing might look better, not sure . .
![2020-11-29 1518](https://user-images.githubusercontent.com/61069740/100544485-45874000-3256-11eb-8ae6-ced82cfd6292.jpg)

I hope the plug-in can be optimized, as it's an amazing thing, atm . .

**Comment by jasperbrooks79** [comment] 2020-11-29 14:37
I took an image, of the plug-in demo, and added some textures, it is 1-to-1 as good, as what's in the cinema, right away . . <3

<img width="960" alt="Skærmbillede (724)" src="https://user-images.githubusercontent.com/61069740/100544817-b3346b80-3258-11eb-9b32-07e48886868d.png">

I've never seen a better 3D effect, in any recent movie, or cinema, it ROCKS . .

**Comment by Calinou** [comment] 2020-11-29 14:42
Duplicate of https://github.com/godotengine/godot-proposals/issues/1805.

**Closed by Calinou** 2020-11-29 14:42 UTC
