### ISSUE TITLE
Want to be able to open my original assets with their shell handler

### ISSUE THREAD

**Issue by fire** [godotengine/godot-proposals#912] opened 2020-05-26 22:12 UTC
**Describe the project you are working on:**
3d multiplayer game

**Describe the problem or limitation you are having in your project:**

Want to be able to drag my assets from Godot into Maya. This is a generalization of that.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Be able to right click on the imported resource in the file system (section) and then have an option to open the original file. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Open the filesystem section and and then it uses https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-shell-open to open the absolute path of fbx / gltf / dae / wav / imported resource using the system shell open.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This is a quality of life enhancement.

**Is there a reason why this should be core and not an add-on in the asset library?:**
New developers won't know what an asset library is.

**Comment by Calinou** [comment] 2021-02-26 13:06
Duplicate of https://github.com/godotengine/godot-proposals/issues/328.

**Closed by Calinou** 2021-02-26 13:06 UTC
Labels: topic:editor
