### ISSUE TITLE
Add Type Information and Documentation on Hover in Godot Editor

### ISSUE THREAD

**Issue by sandygk** [godotengine/godot-proposals#8393] opened 2023-11-10 15:43 UTC
### Describe the project you are working on

N/A every project could benefit from this.

### Describe the problem or limitation you are having in your project

The current Godot script editor lacks the feature to quickly view information about variables or functions by hovering over them. This leads to frequent interruptions in the coding flow, as I need to manually search for documentation or recall the specifics of certain elements in my code.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The proposed feature would allow users to hover their cursor over a variable or function in the Godot script editor to display a tooltip. This tooltip would show the type, a brief description, and a link to the relevant documentation. This mirrors the functionality seen in Visual Studio Code and would significantly enhance the efficiency and convenience of coding in Godot, especially for large projects or when learning new aspects of the engine.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Upon hovering over a variable or function, a small, context-sensitive box appears near the cursor. This box would contain:

The type of the variable/function.
A brief description (extracted from Godot's documentation).
A clickable link that takes the user directly to the corresponding documentation page.
For instance, hovering over a Vector2 variable would show its type ('Vector2'), a short description ('A 2D vector used for various calculations'), and a link to the Vector2 documentation in Godot's official docs.

Here is an example with a function:
<img width="517" alt="image" src="https://github.com/godotengine/godot-proposals/assets/6596836/2825d792-4896-45e2-a8e7-e5fcf109bbd7">
 
and another example where the inferred type is displayed, not the type name on the tooltip acts as a link to the documentation:

<img width="402" alt="image" src="https://github.com/godotengine/godot-proposals/assets/6596836/62c40a2c-d854-4612-b155-a9d553d4667f">

The screenshots are from VSCode using the godot-tools extension.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This type of integrated development environment (IDE) feature is not feasible to implement effectively through a script or plugin. Its integration into the core editor is essential for a seamless and native user experience.

### Is there a reason why this should be core and not an add-on in the asset library?

Having this feature as part of the core Godot editor is crucial for providing a consistently efficient development experience.

**Comment by YuriSizov** [comment] 2023-11-10 16:44
Thanks for your suggestion. It's a duplicate of https://github.com/godotengine/godot-proposals/issues/1393, so consolidating.

**Closed by YuriSizov** 2023-11-10 16:44 UTC

**Comment by sandygk** [comment] 2023-11-10 17:12
Oh perfect! Thanks 👍
