### ISSUE TITLE
Make an optional top - bar with ' large ' icons in the editor . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2108] opened 2021-01-12 11:33 UTC
### Describe the project you are working on
A Tomb raider game, with bullets and, many monsters <3

### Describe the problem or limitation you are having in your project
I've been making my own 'custom' look editor, for making visual script, and been trying, to make the editor look, like a classic RPG - action game interface, like this . .
<img width="960" alt="2021-01-12 1217" src="https://user-images.githubusercontent.com/61069740/104308147-823e8c00-54d0-11eb-9b17-e4cac382b67d.png">

So, making a game, ' feels ' like PLAYING a game, a classic RPG or, an action - adventure game . . So far, I've got this, and am VERY happy, with how this is even possible, also a nice, classic look, for visual scripters, no hassle, or so, very clean and, neat . .
![Skærmbillede (860)](https://user-images.githubusercontent.com/61069740/104308242-a69a6880-54d0-11eb-83e4-b4df42618b20.png)

But, there's one thing missing, so it feels like PLAYING a game, to MAKE it, and that's a TOP row, of icons, on the top bar >>
<img width="1457" alt="Skærmbillede (860)" src="https://user-images.githubusercontent.com/61069740/104308409-e5c8b980-54d0-11eb-9b0f-d83eececf38e.png">

So, the idea is, make an OPTION, in the theme settings, to replace the ' 2D, 3D, Script, Assetlib ', with some cool, new icons, for Godot 4 ya ya . . Like, this maybe, something a bit bigger, as an OPTION . .
<img width="1457" alt="Skærmbillede (864)" src="https://user-images.githubusercontent.com/61069740/104308770-77382b80-54d1-11eb-8b38-d8959e476cc4.png">

But, with some Godot specific icons, something really nice . .

Maybe, like this . .>>
![2021-01-12 1227](https://user-images.githubusercontent.com/61069740/104308892-9f278f00-54d1-11eb-8e0f-671af9d95ce1.png)

Because, in many amazing games, there is a ' top ' row of icons, that's why I need it, or ask . . . Like, for character screen, level-up screen, so on, and it's the last detail, that'd make Godot amazing and, just amazing, and it could be a nice ' look ' update, to Godot 4, really hope you can do it, so it's an OPTION in theme settings, and the engine looks pro, really inviting, especially to gamers, geeks and, code - monsters or, - beasts <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
It's just something, that'd complete my user-experience of Godot, and make it ' just ' right, the ' last ' straw or, such . . But, I can't design icons, maybe someone could make a concept or, so, and not sure, but if one could add CUSTOM icons, like short cuts to folders, view-port configurations, and render ( in wire-frame, overlay, so on ), or maybe something, I had not thought of, well it'd make Godot shine, like a star, so, please, really, really like this, to make it ' Perfect ', for me <3 Thanks . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Maybe a new user-interface, at the top, or an option, as a test feature, in the menu settings, to make Godot just, stunning, world - class . . it already is, but we need more, of course <3 Thanks . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't do this, as noob, or beginner, at all . . 

### Is there a reason why this should be core and not an add-on in the asset library?
Well, it would give the amazing Godot 4 a new visual look, set it apart, visually, from older versions, maybe the icons could be small, medium or, large, so different resolution users, could enjoy them, really make the engine pop and, sweat, ya ya . .

Thanks, for your time, need I say, can't wait, can't wait . .

**Comment by jasperbrooks79** [comment] 2021-01-12 11:49
something like this, with option to make it in gold ( Dolby look ) or, silver . .
![2021-01-12 1244](https://user-images.githubusercontent.com/61069740/104310784-94222e00-54d4-11eb-9f24-fb6289715137.jpg)

![2021-01-12 1248](https://user-images.githubusercontent.com/61069740/104310789-96848800-54d4-11eb-8368-341638deee34.jpg)

<3

**Comment by CodeDarigan** [comment] 2021-01-14 01:14
This could be done relatively easy with a Plugin. You wouldn't even remove the original labels, you would just have the bar layered over them. I think a Popup Panel which you can add options too (probably from a list of predefined options or the ability to bind your own custom script).

Some functions may require more editor methods to be exposed (like how play_custom_scene and is_scene_playing worked).

**Comment by jasperbrooks79** [comment] 2021-01-14 04:31
That sounds good, I was thinking maybe add an new ' feature ' or, setting, in ' editor setting ', display ' top bar ' as icons, and icons are like 50 x 50 pixel, so it won't make Godot much larger, but give it a nice, new look for Godot 4, new engine, new look . . <3

**Comment by pycbouh** [comment] 2021-02-04 16:48
Duplicate of #2240

**Closed by pycbouh** 2021-02-04 16:48 UTC
Labels: topic:editor

**Comment by Zireael07** [comment] 2021-02-04 16:50
*facepalm*

Jasper, this is the 2nd or 3rd time you managed to duplicate your OWN issue... I understand being excited, but...
