### ISSUE TITLE
Enforce GDScript static typing with a per-project setting

### ISSUE THREAD

**Issue by Kubulambula** [godotengine/godot-proposals#3862] opened 2022-01-25 13:11 UTC
### Describe the project you are working on

Any project

### Describe the problem or limitation you are having in your project

GDScript in its current state support optional static typing that in Godot 4 has added benefit of slight performance boost.
However from my point of view is the fact that you can catch errors more easily and write safer code even before you run the code for the first time.

But when working with a team not everyone sticks to the agreed static typing or maybe just from drowsiness or lazyness you start writing dynamically typed code thus creating possible errors and edge cases that could be otherwise easily prevented.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In project or editor settings there would be a new option. Static Typing

The setting would have these possible values:

**1. Optional**
- Same as it is now. Nothing would change.

**2. Suggested**
- If there is any line of code, where for example the type of variable cannot be inferred or function does not have specified parameter and return types, Godot will raise a warning that the line is not safe.
- The warning can be ignored like any other.

**3. Mandatory**
- Same as Suggested but now instead of warning Godot will raise an error when trying to run the script.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In project or editor settings there would be a new option. Static Typing

The setting would have these possible values:

**1. Optional**
`func foo(x):`
- This is completely fine as it is now

**2. Suggested**
`func foo(x):` 

- This will raise a warning like:
`The type of argument 'x' is not specified. Fix this by specifying the type: 'x: TYPE' or if this is intended ignore this warning` 

- Also the return type is not specified so the warning could look something like this:
`The return type of function 'foo()' is not specified. Fix this by specifying the return type: 'func foo() -> TYPE:' or if this is intended ignore this warning` 

**3. Mandatory**
- Same as Suggested but will raise error instead.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I believe that this would be at its most as a core feature just like Editor Feature Profiles.

### Is there a reason why this should be core and not an add-on in the asset library?

Every user that wants to write statically typed GDScript would benefit from this.

Teams of developers would find this helpful as it would come in hand with the Editor Feature Profiles, helping commiting a number of people to stick to agreed typing style.
With 4.0 on the way and more teams working with Godot this could make their experience a whole lot smoother.

**Comment by pycbouh** [comment] 2022-01-25 13:26
It seems to be a duplicate of https://github.com/godotengine/godot-proposals/issues/173.

**Closed by pycbouh** 2022-01-25 13:26 UTC
Labels: topic:gdscript
