### ISSUE TITLE
Implement _on_load for Resource class

### ISSUE THREAD

**Issue by jeadhz** [godotengine/godot-proposals#8900] opened 2024-01-17 01:07 UTC
### Describe the project you are working on

A survival game with a moderate amount of items.

### Describe the problem or limitation you are having in your project

There's no built-in way to determine when a `Resource` is manually loaded using `load`, or duplicated with `duplicate`.

The function `_init` doesn't work because when it is called, all `@export` variables don't have their value assigned in the saved resource.

The unique way I found is using `_init` and waiting an idle frame, but it leads to errors and bad code.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It's simple as it sounds
`_on_load`, which should be like an `_init` function, but called after assigning all `@export` vars

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

With this function implemented should be safe to do things that require `@export` variables,

### Simplified example:
Before:
```
# It is made unique with 'duplicate' because each item has its own amount, etc.
var new_item = load("res://my_item.res").duplicate()
initialize_item_defaults(new_item) # This has to be called on each place an Item is duplicated/loaded
```
After, no need to unmaintainable code:
```
class_name Item
@export var amount = 100

var max_amount

func _on_load():
    max_amount = amount 
```

### Another example:
```
@export var item_id = "stone"

func _on_load():
    print("An item was loaded with '%s' id." % item_id)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, but it would result in unstable and repeated code because you have to call the same code on every place the resource is duplicated/loaded.

### Is there a reason why this should be core and not an add-on in the asset library?

Resource usability is out of the box.

**Comment by dalexeev** [comment] 2024-01-17 06:49
* Duplicate of #5994?

**Comment by YuriSizov** [comment] 2024-01-17 09:21
Indeed it is, consolidating.

**Closed** 2024-01-17 09:20 UTC
Labels: topic:core
