### ISSUE TITLE
Visible faces with custom color/texture for ColisionShape

### ISSUE THREAD

**Issue by Coldragon** [godotengine/godot-proposals#1143] opened 2020-06-30 01:45 UTC
**Describe the project you are working on:**
Multiple godot project in 3D that use Area for triggering event

**Describe the problem or limitation you are having in your project:**
- Shape are only thin line, it's hard to see the boundary of my shape when I try to set them in the scene.
- When scene start to be complexe, screen become hard to read and identifing the purpose of each shape is hard because they are all the same color (and thin line). 
- When running the game with "Visible Collision Shape" it become quicly a mess.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Show faces of the ColisionShape with texture/color and mark them Editor Only or not like we can see in the Source Engine.

![image](https://user-images.githubusercontent.com/471393/86070053-f3aa7600-ba7b-11ea-8c91-729113a2e38a.png)

- With color/texture customization it will help gamedesigner to see directly what is the purpose of each area and have a readability of the current scene (Differentiate for example "Ladder", "Spawn", "Damage", "Loose" etc...)
- It help to set their size more precisly because you see where they ends when some of the edge are through a wall or something else.
- The Editor Only will let you draw them at runtime without drawing all the other ColisionShape and let you read the screen precisly

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
- A Checkbox on the Shape (or the Area/Body, need to be questionned) to show the faces. 
- Editor standard Color/Shape faces in Editor Configuration. Shape custom Color/Texture to differentiate it.
- "Editor Only" checkbox to see the shape at runtime without showing every shape with the "Visisble Collision Shape" config.

![image](https://user-images.githubusercontent.com/471393/86072648-4c7d0d00-ba82-11ea-8e4f-bb54d5e75b52.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I'm pretty sure it could be made as an addon but i'm not sure it could overload the current Colision Shape behavior and also the Visible Collision Shape at runtime.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's already in other game engine  and was pretty usefull and could be a good default workflow for 3D in godot

**Comment by Jummit** [comment] 2020-06-30 05:52
I like this, because the current collision shapes are displayed with thin lines, which are hard to see especially when used together with meshes. In 2D the collision shapes are filled. I think this should be an option, as you still want to see what's behind the collision shapes.

**Comment by Calinou** [comment] 2020-06-30 08:14
Duplicate of #906. (Please comment there to request the part about textures.)

**Closed by Calinou** 2020-06-30 08:14 UTC
Labels: topic:editor
