### ISSUE TITLE
Split the AnimationPlayer `play()` method into `start()` and `resume()`

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot-proposals#287] opened 2019-12-06 10:54 UTC
**Describe the project you are working on:**

2d games using a lot of animationplayers

**Describe the problem or limitation you are having in your project:**

Currently `play()` method doesn't adhere to single responsibility principle. If user calls `play()` while there is no animation playing it acts as `start_animation()` where as when user calls it when animation is already playing it acts as `resume_animation()`. This dual behaviour is not desired by users as it requires a condition statement in order to use `start_animation` functionality of `play()`. It is also inconstant across the engine as for example `AudioStreamPlayer` method `play()` method has only singular functionality of `start_playing()`. This is confusing to understand and breaks intuitiveness of the engine. 

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

Splinting `play()` into `start()` and `resume()` as well as splitting `stop()` into `pause()` and `stop()` will give use finer control of the behaviour they would like to see from the method without requiring them to invoke conditional statements. It can be a solid ground for adding the same functionality to other nodes in a future like mentioned earlier `AudioStreamPlayer`

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

This is what happens when user calls `play()` method inside the `_process` function 

![1](https://user-images.githubusercontent.com/30668026/70317239-4b01a400-1815-11ea-8f08-ffb6509b77c0.gif)

With proposed changes this is what will happen when user calls `start()` inside `_process`  function or `input events`. 

![2](https://user-images.githubusercontent.com/30668026/70317410-9ddb5b80-1815-11ea-9130-376a6bac7be3.gif)

**Describe implementation detail for your proposal (in code), if possible:**

No idea but it appears to be feasible as it was proposed in this issue https://github.com/godotengine/godot/issues/34125

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

it can be worked around via using few conditionals to restart animation but it's a pain in to work with and is very undesirable solution that is inconsistent with the way of how other nodes work in the engine. 

**Is there a reason why this should be core and not an add-on in the asset library?:**

Yes. This is very much improvement on faulty and confusing design of core feature. I believe that issue is important enough that should be brought back to main branch prior to 4.0 happening. Ideally in 3.2.1 or similar. Reason for this is that functionality was present in 3.0.6 version of a engine. I would go as far as to call it a bug being a result of untended change to `play()` function between releases.  It was then removed from the engine in 3.1 without any discussion and it would greatly improve the users ability to use those without having impact on existing projects. Any work around people did to gain the functionality discussed here would still work with new functionality. For example conditional that check if animation in playing and reset it would still work. This however would make future projects easier and code base less confusing.

**Comment by golddotasksquestions** [comment] 2019-12-06 11:04
When and where do I define _which_ animation or audio file to play though?
Am I correct to assume `start()`, `resume()`, `stop()`, `pause()` would only take a single string as argument?
like  `start("animation")`, `resume("animation")`, `stop("animation")`, `pause("animation")`
should it not follow that we then also need 
 `start_all()`, `resume_all()`, `stop_all()`, `pause_all()` ?

**Comment by golddotasksquestions** [comment] 2019-12-06 12:05
To clearify, (so that we don't end up in the same situation as in https://github.com/godotengine/godot/issues/34125) would I also be correct to assume that this is the behavior:

`start("animation")`: _only_ starts to play specific animation/video/audio immediately from the beginning = timestamp 0, regardless if they currently play, or stopped, or paused.
`start_all()`: same but for _all_ of the animation/video/audio Player node

`resume("animation")`: _only_ resumes to play specific animation/video/audio immediately _if_ it was previously paused using `pause("animation")` or `pause_all()`
`resume_all()`: resumes playback of _all_ the animation/video/audio of that node are in a "paused" state.

`stop("animation")`: _only_resets timestamp of specific animation/video/audio immediately to "0" and stops the playback. Would also apply to a animation/video/audio in a "paused" state and therefore remove it's paused state.
`stop_all()`: resets timestamp to "0" and stops playback of _all_ animation/video/audio of that node. If any animation/video/audio of that node was in "paused" state, it would remove that state.

`pause("animation")`: _only_stops the playback of specific currently playing animation/video/audio immediately, but does not reset the timestamp.
`pause_all()` : stops the playback of _any_ currently playing animation/video/audio. Returns a warning (?) if called on a node that has no animation/video/audio currently playing?

**Comment by girng** [comment] 2019-12-08 09:43
I'm confused (not because of this issue), but did they change the way `play` works or something? :O

**Comment by golddotasksquestions** [comment] 2019-12-08 13:13
@girng 
Yes. As you can see in the gifs above, play("name") by default started to play the animation immediately in 3.0.6 unless you told Godot to wait, while in 3.1.X your Input does not even seem to register the function call if the animation is still playing. Check https://github.com/godotengine/godot/issues/34125 for more details including Minimal Projects.

I did some more thinking.
For those who want to continue using the 3.1 play("name") behavior, but for some reason don't want to use .is_playing() or .queue(), we could have:

start_if_stopped("name"): only starts playing a specific animation/video/audio from if it is in "stopped" state.

Alternatively we could add .is_stopped() and .is_paused() which would return a bool and check if the animation/video/audio is in the "stopped" state or "paused" state respectively. This would also match the already existing .is_playing()

What do you think @KoBeWi @aaronfranke @fracteed @akien-mga ?

**Comment by KoBeWi** [comment] 2019-12-08 13:25
> is_stopped()

This is basically `not is_playing()`.

> start_if_stopped("name")

Something like `play_if_not_playing()` would be better. Actually, before the new behavior in 3.1 you had to write such method yourself.

**Comment by golddotasksquestions** [comment] 2019-12-08 13:27
> 
> 
>     is_stopped()
> 
> This is basically not is_playing().

No it's not, because it could be also in the "paused" state.

> play_if_not_playing()
The goal of this issue is to bring clarity to the ambiguous "play".

**Comment by aaronfranke** [comment] 2019-12-08 14:37
Disclaimer: I don't currently use AnimationPlayer in my projects. Coming at this from that perspective.

I would imagine that start/stop would be the same as resume/pause except the former set changes the current animation time (or whatever it's called) to the beginning. @golddotasksquestions You are proposing 3 states, what is the difference between a "stopped" state and "paused"?

I don't see the purpose of `start_if_stopped("name")`. Why not just have an if statement with `is_playing` or similar, then run start/resume/pause/stop inside of that?

As for each of those taking arguments for the name, why not have that be separate? Something like `current_animation = "name"` (or if you don't like properties, `set_current_animation("name")`) which is immediately followed by start/resume/pause/stop commands.

If there is a need for multiple animations (again, I don't use this myself, so IDK) then this would be PoolStringArray, and I would imagine there would be prev/next methods.

**Comment by girng** [comment] 2019-12-08 14:56
> Yes. As you can see in the gifs above, `play("name")` by default started to play the animation immediately in 3.0.6 unless you told Godot to wait, while in 3.1.X your Input does not even seem to register the function call if the animation is still playing. Check [godotengine/godot#34125](https://github.com/godotengine/godot/issues/34125) for more details including Minimal Projects.

Aww, I see. Thanks for the link.

I think you made a very **important point**: 
>  If you run play in either _process() or _physics_process() you immediately learned what either of those functions do

 that's really true. I can't imagine calling `.play` on every frame, unless it's inside a state change condition, like [this](https://github.com/ndee85/gBot/blob/master/projectfolder/scripts/gbot.gd#L232). This is akin to putting a `SamplePlayer` in `_process` and calling `.play`.  

 To @golddotasksquestions: 
<details>
  <summary>Click to expand</summary>

> After reading that issue, one thing I've learned  after nearly half a decade bug reporting, is Donald Knuth's premature optimization quote applies similarly to Godot (in the context of suggestions and bug reporting). Changing the minds of lead developers is pretty hard, and we  game developers must learn to adapt  or we'll  be left wasting precious  time that could be spent on our game.  I've seen a plethora of changes  over the years where I would have made an issue about it, but instead, I've adapted and moved on. This is an **_essential_** mindset to have, especially if using an open source program.

</details>

**Comment by KoBeWi** [comment] 2019-12-08 15:12
> I can't imagine calling .play on every frame

And yet there are people that do this. Examples from just googling the problem
https://godotengine.org/qa/19140/animation-not-playing
https://stackoverflow.com/questions/52158088/godot-jumping-animation-just-plays-the-first-frame

I've seen 3 or so similar topics on Reddid. I imagine there were more, but 3.1 stable hit not too long after I started using Godot and such questions stopped appearing. It's just natural for many people. I initially used my animations like this too, but since it didn't work, I switched to the "correct" way of handling animations and didn't even notice when the behavior was changed.

That said, AnimationPlayer could use some changes, but reverting behavior from 3.1 will bring more "angry" people than introducing it did (not to mention that the "problem" was brought up 9 months after this happened...). But of course, if enough people support it, this can be reverted to old behavior.

**Comment by golddotasksquestions** [comment] 2019-12-08 18:56
@aaronfranke 
There used to be exactly just two states for an AnimationPlayer animation: "not playing" and "playing". 
"not playing" is the same as "stopped" is proposed here: animation is not playing and the timestamp is at 0.

Since stop(false) was implemented, we now have 3 states: "not playing", "playing", and "false stop"
stop(false) does not reset the Timestamp of the playing animation.

Could you intuitively guess the difference between "false stop", "not playing" and "playing" if all you read was these names?

These 3 states we have now are nothing else but "paused", "stopped", "playing", so why not work with that?

> I don't see the purpose of start_if_stopped("name"). Why not just have an if statement with is_playing or similar, then run start/resume/pause/stop inside of that?

I absolutely agree with you. 
In 3.0.6 you also just needed two lines of code: First check if the animation is already playing, if not, play. It's dead simple, and on top of that explains the use and purpose of _process() and _physic_process() the first time you try to play an animation in either of these functions without knowing what they do.
I suppose the purpose is just to have 1 line of code instead of 2. You will have to ask akien why he wanted this, I could not find an issue or discussion asking for the change of play() into this behavior, but that's what we have right now.

**Comment by golddotasksquestions** [comment] 2019-12-08 19:24
@KoBeWi 
No doubt these questions come up all the time. I myself reply to them on a regular basis and have tried myself to AnimaitonPlayer.play("name") in the _physics_process() and _process() and wondered why it does not work.
But you are completely missing the point here:
Those threads and questions come up not because play() needed a fix, but because those people (me including) did not understand what _process() and _physics_process() does yet.
So instead of making it easier for them to understand what _process() and _physics_process() does, the 3.1 play() implementation suggests _process() and _physics_process() would not be called every physics tick/frame.
This worse on all fronts because it prolongs the learning process of _process() and _physics_process() and teaches false assumptions that will create learning conflict later on.
The less congruent a system is the harder it is to learn. 
`start_if_not_playing()` or  `start_if_stopped()` would at least be honest and clear about what it does and not work against the learning process of the engine.

**Comment by Feniks-Gaming** [comment] 2019-12-08 19:29
@KoBeWi issue is not as much about reverting the behaviour t 3.0.6 because we agree that this behaviour was limiting the enhancements that 3.1 and 3.2 bring like ability to pause animation etc. Issue is that in current state play() isn't explicitly stating it's purpose. Rather than reverting to 3.0.6 I feel that splitting play is a better route to take it was the direction suggested by @akien-mga in original thread where the issue was raises and I think it would be more beneficial to users. Akien seems to agree as well. 

I think the only disagreement we are having is a time frame of bringing this change. Akien seems to think issue should be resolved in 4.0, my goal is to convince the community that the issue should really be resolved in 3.2.1 or similar update as it is simple small enhancement that will improve a work flow and will fix the unintended behaviour that 3.1 caused to play() function. 

If it wasn't the issue introduced by 3.1 update I would agree that it's worth waiting till 4.0 but since this is new introduced problem we really should fix it sooner than end of 2020 beginning of 2021 when 4.0 will eventually be released.

**Comment by golddotasksquestions** [comment] 2019-12-08 19:37
This is a great chance to make the API for AnimationPlayer, AudioStreamPlayer and VideoPlayer in those core functions the same. 
I doubt akien and the other core devs/contributors want API changes that reach so far to be changed in a maintenance update.
The "paused" functionality of stop(false) would still exist if we would revert play(). 
The change of 3.1 play() is exactly the same as 3.0.6 play() _on_animation_finished(). It removes one line of code. I still think it should be reverted with 3.2. It's a massive mistake on all fronts.

**Comment by KoBeWi** [comment] 2019-12-08 20:20
> 3 states

Stop(true) and stop(false) changes to the same state - "not playing". There's no "third" state, stop(true) just resets the position. It's the same as paused, but the change happens differently.

> Those threads and questions come up not because play() needed a fix, but because those people (me including) did not understand what _process() and _physics_process() does yet.

Really? Default script template literally tells you that:
```
# Called when the node enters the scene tree for the first time.
```
If you change position in `_process`, it keeps changing. So how would anyone think that `play()` will be called once?

IMO most people just expect that play() will "play the animation", not "freeze it at first frame", which is what happened before. Maybe they are coming from other engine, maybe it's just more intuitive. But I really don't think it affects learning what `_process` does. You should know this if you just know how to read.

---

Eh, I should probably reply to the OP too.

> If user calls play() while there is no animation playing it acts as start_animation() where as when user calls it when animation is already playing it acts as resume_animation().

It does what it says - plays.

> This dual behaviour is not desired by users as it requires a condition statement in order to use start_animation functionality of play().

Not all users. I bet there are more users that like the current behavior.
btw, the new behavior was introduced in https://github.com/godotengine/godot/pull/25776. See especially the last comment (looks like the doc didn't get updated in time, heh).

>  It is also inconstant across the engine

Is it? AnimatedSprite works like that.

> AudioStreamPlayer [...] This is confusing to understand and breaks intuitiveness of the engine.

The difference is that if play AudioStreamPlayer in `_process()`, you will get a loud noise that (literally xd) tells you what is wrong. If you use a resetting-play(), your animation "doesn't play". *This* is confusing.

> Splinting play() into start() and resume()

To have Animation**Player** without play()? XD

---

Ok, so here's how I see it. The current default behavior of play() is ok. I already mentioned why. Now, we should have a way to use it in the old way. So either there should be something like `play(reset = false)` or `force_play()`. Also `stop(false)` should become `pause()`.

I can't believe this whole discussion started because resetting animation suddenly requires additional line (which on the other hand means that playing it requires less code, but that seems to be ignored). Moreover, it was never brought up for 9 months, until the release freeze for 3.2 took effect. I don't see requesting this now to be reasonable, it should be for 4.0 if anything. Although the new methods I mentioned can be added for 3.2.1.

**Comment by golddotasksquestions** [comment] 2019-12-08 21:13
> Stop(true) and stop(false) changes to the same state - "not playing". There's no "third" state, stop(true) just resets the position. It's the same as paused, but the change happens differently.

O_O holy sh ... you are right. This is so much worse than I thought. How the hell could anyone sign off on this??? This is absolutely broken.
Not just play, we don't have a regular stop() either anymore!

**Comment by KoBeWi** [comment] 2019-12-09 07:51
> resets the timestamp without actualizing the graphic in the viewport

This is fixed in https://github.com/godotengine/godot/pull/33733

**Comment by AttackButton** [comment] 2019-12-10 00:33
> 
> 
> > I can't imagine calling .play on every frame
> 
> And yet there are people that do this. Examples from just googling the problem
> https://godotengine.org/qa/19140/animation-not-playing
> https://stackoverflow.com/questions/52158088/godot-jumping-animation-just-plays-the-first-frame
> 
> I've seen 3 or so similar topics on Reddid. I imagine there were more, but 3.1 stable hit not too long after I started using Godot and such questions stopped appearing. It's just natural for many people. I initially used my animations like this too, but since it didn't work, I switched to the "correct" way of handling animations and didn't even notice when the behavior was changed.
> 
> That said, AnimationPlayer could use some changes, but reverting behavior from 3.1 will bring more "angry" people than introducing it did (not to mention that the "problem" was brought up 9 months after this happened...). But of course, if enough people support it, this can be reverted to old behavior.

I really like the way the AnimationPlayer acts right now, but the problem is that these days I was testing the Timer start() method, after seeing several people with this difficulty in a youtube video, and it works just like that way you mentioned, having a design exception like this will not lead to the clutter?

```
if timer.is_stopped():
	timer.start()
```

I would like to add this to the docs, but I must first learn how to proceed.

Talking about design, why does the Timer need a check before it start and the AnimationPlayer don't?

Other than that, I really believe we need a `pause()` and` resume()` methods in the AnimationPlayer or something similar.

**Comment by KoBeWi** [comment] 2019-12-10 00:44
> if timer.is_stopped():
	timer.start()

Eh, just disable `one_shot`?

**Comment by AttackButton** [comment] 2019-12-10 15:35
From what I remember, setting `one_shot` was not enough, it keeps restarting each frame. I will test this again in the next days. Anyway, what I'm trying to say is that the Timer works similar to what the others are showing here about the AnimationPlayer. But I prefer how the AnimationPlayer works now, I'm just asking if it is not breaking the design of the engine and telling that implementing the `pause()` and `resume()` is very important to reduce the ambiguity generated by using the `stop(false)` to pause an animation and the `play()` to resume it.

**Comment by KoBeWi** [comment] 2019-12-10 17:36
> From what I remember, disabling one_shot was not enough, it keeps restarting in each frame.

No, what I mean is that you don't need to start it manually, so the whole code becomes unnecessary.

Also as I said, AnimationPlayer now works the same as AnimatedSprite. No one had any problems with that and "asking if it is not breaking the design of the engine" has no practical meaning.

Also `resume()` doesn't fit in the current AnimationPlayer design. I imagine it would continue current animation and error out if there's "no animation playing". I don't see any use for such behavior.

**Comment by AttackButton** [comment] 2019-12-10 23:09
Thanks for your response. About the behavior, this would not change, the AnimationPlayer is working perfectly right now, the problem is in the logic matter, `stop(false)` doesn't mean `pause`.

**Closed** 2023-01-27 10:08 UTC
Labels: topic:core
