### ISSUE TITLE
Add the possibility of multi-user editing of projects over the network

### ISSUE THREAD

**Issue by anunknowperson** [godotengine/godot-proposals#3694] opened 2021-12-19 10:47 UTC
### Describe the project you are working on

A lot of small projects in a team of four people

### Describe the problem or limitation you are having in your project

When working in a team, especially with time constraints, such as in game-jams, it is necessary to be able for all people to make improvements to the project at the same time.
Version control systems like Git are usually used for this. However, they have many disadvantages. Very often there are situations when several people need to work on the same scene/resource/script. However, due to the nature of version control systems, this can be unrealizable. If several people work on the same scene, there will be confusion, and merge conflicts will arise, which in complex scenes it is almost impossible to solve manually in a text editor.
Because of this, there are huge problems with attempts to distribute tasks so as to exclude interactions with one resource by several people. As a result, it will lead to a huge loss of time, and this is very important if it is limited. And some tasks cannot be distributed among the participants at all, for example, if several people are engaged in modeling the environment on a large scene.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

One of the most effective solutions to this problem may be the addition of a real-time multi-user system for working on projects. This will not be a replacement for the version control system, but a very important addition to it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here you can give an example of how this is implemented in Unreal Engine 4/5.
It should be possible to run one editor as a server, for example, starting it with the -server key, and then connect client editors to them. The connection can take place over a local network, to a prepared server via the Internet, or using programs like LogMeIn Hamachi.
All clients must have a copy of the project, for example, cloned from the Git repository. 
One should create a session, and the rest get the opportunity to connect to it. When connecting, the editor version and the project name should be compared.
Further, all participants can make any changes to the project resources. These changes should be transmitted through the server to all other users. Each participant should see where the others are now. In the scene, this can be indicated by a three-dimensional rectangle indicating the position of another participant. In a text editor, these can be cursors of different colors. Above each marker of another user, there should be a text field with his nickname.
![image](https://user-images.githubusercontent.com/54563399/146672070-02323d7e-c6fb-4b52-813d-c4f0b1e0b150.png)

It should be possible to set blocking flags on each resource for convenience in order to avoid problems.
![image](https://user-images.githubusercontent.com/54563399/146672165-ba64b7ef-ac4d-4ace-a0a2-54bede6410af.png)

This function should have its own menus that would allow you to manage the session, see where the other participants are, and inspect the history of changes.
![image](https://user-images.githubusercontent.com/54563399/146672123-0e1e9314-1f99-471c-b5b1-52c8733e92df.png)

When the collaboration is finished, the session can be stopped. the participant who created the session can send changes to the version control system.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This feature will be useful for any teams that want to work effectively together. This cannot be worked around with a few lines of code.

### Is there a reason why this should be core and not an add-on in the asset library?

Theoretically, it is possible to implement this as a plugin, but it will still require major changes to the editor code. Also, if it comes out of the box, it will greatly simplify the use of the engine.

**Comment by Zireael07** [comment] 2021-12-19 10:49
100% sure it was already proposed but can't find it at the moment.

**Comment by anunknowperson** [comment] 2021-12-19 10:50
> 100% sure it was already proposed but can't find it at the moment.

I tried to find it in this repository and using Godot Proportional Finder, but I didn't find anything.

**Comment by Calinou** [comment] 2021-12-19 17:05
Duplicate of https://github.com/godotengine/godot-proposals/issues/851.

**Closed by Calinou** 2021-12-19 17:05 UTC
Labels: topic:editor, topic:network
