### ISSUE TITLE
Add Godot Save/Load System

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#2377] opened 2021-02-28 11:57 UTC
### Describe the project you are working on
Godot UX

### Describe the problem or limitation you are having in your project
Saving game states in Godot can be confusing to beginners, and requires a moderate understanding of the engine mechanics, not to mention it can often be confusing as to how one should implement a save/load system, as there are quite a few possible routes to take, here's a couple of examples:
1) Save game as Scenes 
- Drawbacks: Any children added to the tree have to change their owner to be saved, and Script Variables aren't saved unless export is added upon declaration
- Pros: Very Quick to implement (fairly simple), Can be edited in Godot Editor
2) Save game as Custom Text
- Drawbacks: Takes a while to implement (fairly complex), Prone to bugs, have to implement a system to both save the desired data and to properly load said data, Cannot be edited in Godot Editor
- Pros: You can Save anything you wish or exclude things you don't want to Save
3) Combination of 1 and 2
- Drawbacks: Any children added to the tree have to change their owner to be saved, Takes a while to implement (complex), have to implement a system to determine what is saved and how, and then how to load it, some of it cannot be edited in Godot Editor
- Pros: Better control

Note: there are more ways one can save games in here, these are just a couple that came to mind.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Adding a Function that Saves the root Node (of the entire scene, not the instance if an instance is calling the save function) and all of it's children, and grabs all the Data (variables of all the nodes) that isn't excluded.
The Implementation would be Quite close to 1

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Add a Function savegame and loadgame
savegame would stop all processing after the current frame finishes, find which is the Root node, and it would go over all the children of the root node, including any children added using add_child() or such and it'd save all their variables and connect them to the location of the variable owners in the tree.
loadgame would load the saved scene tree, and set the variables stored to the respective owners of said variables inside the tree

Note: for excluding nodes, they should have an exclude property that is default false, and for variable(s) to be excluded an annotation to exclude should be added to the desired variable(s)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes, option 1 can be implemented in a handful of lines, and a single line for each sub-scene that gets instanced that needs to be saved to change owner to be saved when packing a scene, and every variable that is to be saved has to be declared with export

### Is there a reason why this should be core and not an add-on in the asset library?
Because it is a Very common feature in games, so a Game engine having a Default implementation would be great.

**Comment by pycbouh** [comment] 2021-02-28 12:19
All you need to implement saving and loading is already in the engine. And it's neither of the options you described, probably. You should utilize custom resources, at runtime rely on a global game state for as much as possible, and make your scene initialization data driven and deterministic.

**Comment by Jummit** [comment] 2021-02-28 14:35
Saving games is already possible, and one way is documented [here](https://docs.godotengine.org/en/stable/tutorials/io/saving_games.html). I don't see how this proposal builds upon or improves the existing systems in any way.

**Comment by mrjustaguy** [comment] 2021-02-28 16:05
The Idea is to allow for a quick one-line save game that just saves everything there is to save, with optional support for excluding things one doesn't want to save for whatever reason. 
The reason for implementing it is the fact that like almost everybody wants to save games, and providing a very simple to use approach that does all the work and is suitable for the vast majority of the cases and would "just work"

I Know Saving games is possible, and that there are quite a few ways to do it, and personally the documented approach is not the simplest at all, as that would be using PackedScene to pack the Scene Root (after all the children set owner to said root or else they ain't packed) and using ResourceSaver to save that, and having all declared variables have export upon declaration (unless you don't want the variable saved with the scene)

**Comment by dugramen** [comment] 2021-02-28 17:46
I think the PackedScene method can already do this. I think you can use propagate_call() with set_owner(). That'll go through all the children and descendents and call a method:
`propagate_call( "set_owner", [self] )
`
Then save your scene. And I think explicitly marking variables with "export" is already a good way to distinguish what should and shouldn't be saved.

**Comment by golddotasksquestions** [comment] 2021-02-28 23:30
I agree with the intention of this proposal, not sure about the proposed solution.

Saving and Loading a gamestate is so common is every game, I was really surprised how complicated it is. I was expecting something as user friendly and simple as OP is describing, but as a complete beginner it took me months to figure out how to do this in Godot.

I believe better documentation would help a lot here. Existing methods should be separated into 

1. beginner(simple) 
2. intermediate(medium complex) 
3. pro(most flexible but also most complex)

sections. 
The [existing tutorial ](https://docs.godotengine.org/en/stable/tutorials/io/saving_games.html)seems to be on the pro side, still too complex for me to just read and understand what is going on after using Godot for more than 2 years.

**Comment by DriNeo** [comment] 2021-03-01 09:29
In the docs, the proposed method directly manipulate files like in C, and I'm not saying it is bad, but it can be completed by a more Godot-ish way, using node and resources.

**Comment by pycbouh** [comment] 2021-03-01 09:47
Yes, the docs are not the best on that subject. This is a tracked issue and is being worked on.

**Comment by Bromeon** [comment] 2021-03-01 11:02
I think @pycbouh mentioned something important (emphasis mine):

>And it's neither of the options you described, probably. You should utilize custom resources, at runtime rely on a global game state for as much as possible, and **make your scene initialization data driven and deterministic**.

Typically, you don't want to save the entire scene. It contains a lot of redundancy and transient state (like particles) that is not part of your game logic. What I would do instead is separate the game mechanics from the graphical visualization, and only store logical data. The graphics can then be derived from mechanics, or at least there's only a small amount of state that you need to handle (like animation progress, if really needed for longer animations).

In addition to separating concerns and enabling a reproducible, deterministic game state, saving/loading only essential data will be much faster and lead to smaller savegames than when serializing the entire scene tree.

**Comment by dalexeev** [comment] 2021-03-01 11:20
The save/load mechanism can vary significantly from game to game. A universal "simple" system, firstly, will be useless for advanced users, and secondly, beginners will still have to learn this system. Reading/writing a save file is not the most difficult thing for beginners. Usually it's much more difficult for them to understand when each of the actions should take place. And this issue is not resolved by this proposal.

It seems to me that it will be much more useful to improve and expand the existing save/load documentation (the option with `ConfigFile` is quite simple for beginners). Simple pre-built save/load systems can be added to the Asset Library. But not to the core.

**Comment by mrjustaguy** [comment] 2021-03-01 12:59
You overestimate the Resources used by Saving the Entire scene.
The Project is basically the save system that I proposed (however var declaration needs export to save variable, something that would be preferable if it weren't the case for the proposed integrated system, that should instead just save all vars regardless of export of lack of, and have an optional way to exclude what one doesn't want to be saved, however that feature isn't actually all that important)
[SceneSave.zip](https://github.com/godotengine/godot-proposals/files/6061689/SceneSave.zip)

~2000 nodes in scene, took ~200ms to save, took ~100ms to load, size of saved tscn is only under 500kb, each node has an exported variable which is the number of frames passed since creation. The size could be smaller with a scn, in the example when replacing the format to scn I get under 300kb for the same scenario.

**Comment by Error7Studios** [comment] 2021-03-01 14:57
Related to [#2365](https://github.com/godotengine/godot-proposals/issues/2365), as scenes using tool scripts must be saved/loaded if you want their in-game state to match their in-editor state.

**Comment by mrjustaguy** [comment] 2021-03-01 15:36
I'm not sure how exactly that is related to this.. I mean are you sure that the scene is saved when you use tools and that your loading script doesn't change the loaded scene during start up?

What I'm trying to say is, how would Saving a scene at runtime when a save function is called (so all the nodes in the tree and all the variables of every node are saved into a scn or tscn file) help you? the Scene should normally be saved in the editor with all the data that is needed to replicate it at runtime and it initializes all the scripts when loaded, which is the part where the problem you have probably occurs because the scripts initialize data saying to use picture 0, when the scene saved picture 1, and thus the script changes from the desired picture 1 to the default value of picture 0 because the script didn't get the memo telling it that the value of picture should be 1 and not the default 0.

**Comment by Error7Studios** [comment] 2021-03-01 16:05
> how would Saving a scene at runtime help you?

It wouldn't. The tool scene data needs to be saved in the editor. It loads the data at runtime.
In your proposal, you're talking about something which _"Can be edited in Godot Editor"_.
The saving of tool scene data must be done in the editor as well.

**Comment by mrjustaguy** [comment] 2021-03-01 18:03
Then you misunderstood what my proposal is about. Can be edited in Godot Editor as in, it's TSCN/SCN format, which is what Godot Editor uses to store scenes. The Proposed Save is just ResourceSaver.save("res://example.tscn",scene) where scene is PackedScene.pack(root node) and with a few extra steps to treat all variables as if they were declared with export, and making the root node owner of all other nodes to have them saved.

What you are doing is already saving TSCN/SCN so this wouldn't help you, as your problem lies in the fact that you are upon starting the scene changing it back to what the scripts have as default, so the Scene gives what you expect, however you never get to see the expected result because the scripts change that to what you don't expect because they don't load the separate from the scene data you are using to tell them what they should be, which in turn means the scripts change say the expected picture 1 to picture 0 (default) because they got no input on which picture it should be and hence it changes the picture to the scripted default that isn't the expected picture 1.

Rough Diagram of what your issue probably is:
1. Tool sets Picture to be Human
2. Scene is saved, Game Runs
3. Script is initialized, doesn't custom load data -> Default Picture is Gnome -> Sets Picture to Gnome from Human
4. You see Undesired Result
Which you fixed by loading the data so that the script changes to the right thing and now looks like:
1. Tool sets Picture to be Human
2. Scene is saved, Game Runs
3. Script is initialized, loads custom data -> Data says Picture is Human -> Sets Picture to Human from Human
4. You see Desired Result

So the issue you have is the Script Setting The Picture from your own custom data, and naturally if the script doesn't load the data it just sets to default. if you stop the script from setting Picture at runtime, It'll work just fine.

**Comment by Error7Studios** [comment] 2021-03-01 19:50
> Then you misunderstood what my proposal is about.

We're both talking about saving a `.tscn` file (and in my proposal's case, an additional text file for `tool` nodes).
My proposal was that an extra `tracker` line be added to each child node's section in the `.tscn` file so that a `load()` function can apply changes to nodes in the scene tree _**even after they've been moved or reparented since the `.tscn` file was last saved**_ (currently not possible because the root node's `.tscn` file would have an incorrect child hierarchy).
The `load()` function would work both in the editor and in a running scene.

> So the issue you have is the Script Setting The Picture from your own custom data, and naturally if the script doesn't load the data it just sets to default. if you stop the script from setting Picture at runtime, It'll work just fine.

You have my proposal backwards.
I **_want_** the running scene to keep the in-editor `export` property changes I made for the `tool` node.
By default, the properties all just revert to their initial script values.
That was the entire reason I made the save/load code. I wanted to preserve the in-editor changes in the running scene.

Whatever method of saving/loading is used, a `tool` node's properties still have to be set at runtime if you want to preserve their in-editor state.

**Comment by mrjustaguy** [comment] 2021-03-01 20:14
> I **_want_** the running scene to keep the in-editor `export` property changes I made for the `tool` node.
> By default, the properties all just revert to their initial script values.
> That was the entire reason I made the save/load code. I wanted to preserve the in-editor changes in the running scene.

Yeah you want to in the editor use a tool to set the picture to picture 1, and you want to have the game display picture 1 instead of the default picture 0, and as such the issue lies in your code, not Godot, because your code ignores what the scene has to say about the exported variables by just setting them to the code defaults.

Here's a MRP of what You're essentially doing:
[Test.zip](https://github.com/godotengine/godot-proposals/files/6064198/Test.zip)

Run this unmodified, in editor a=5, when you run, print(a) returns 0. Now comment the script part that says to comment, and run it again, you'll get print(a) to return 5 (or whatever you set a to be in the editor)

**Comment by Error7Studios** [comment] 2021-03-02 02:34
You're right. But the issue arises when the tool node:

1. Is an **instanced** scene
2. Has an `export var` with a `setget` setter func
3. Uses that setter func to set a **non-export var** of a **child** node (like `Label.text` or `Sprite.texture`)
4. Does **not** have editable_children enabled

Unless the body of the setter func is inside an `if is_inside_tree()` block, you get an error when trying to access a var or func:
1. of the parent node (parent will be `null`)
2. of a child node, unless it also has a `tool` script, or the variable is an `export var`  
	(in-editor only; works in running scene) (built-in vars OK)
3. You get spammed with errors every time you hit `ctrl+s` for the reasons above.

For those reasons, I always just use `if is_inside_tree()` with my `tool setget` setter funcs.
I also almost always use it to set non-export vars of children. Those vars get reset when running the instanced scene.

Finally, because `setget` setter funcs of `tool` scripts run before `_enter_tree()`, the setter func code under `is_inside_tree()` blocks gets skipped when the scene runs.

Because of that, my tool scenes always revert to default properties, and I had to implement a save/load system to call the setter funcs manually in the `_ready()` func.

See this example project: [Tool Export Setter Func.zip](https://github.com/godotengine/godot-proposals/files/6065782/Tool.Export.Setter.Func.zip)

So I should have said:
**Non-export** properties of **children** of **instanced** `tool` scenes get reset to default when running the scene.

**Comment by mrjustaguy** [comment] 2021-03-02 09:23
Ok yeah, My proposal would kinda help, as it intends to save all the Non-export variables as if they were export variables, so I guess they're somewhat related after all..

**Comment by rainerdeyke** [comment] 2021-04-24 13:46
A truly correct save/load system would also require saving the state of any running coroutines.  This is not something that can be implemented in GDScript.  Even implementing it in the engine would probably require massive changes.

**Comment by rainerdeyke** [comment] 2021-04-25 10:39
Also: a truly correct save/load system needs to save to save the current position of any sounds that are currently playing.  This probably doesn't matter for sounds effects or music, but it can matter a lot for long voice-overs.

**Comment by Calinou** [comment] 2021-04-25 15:18
Closing due to lack of support and technical feasibility (see the above comments)
.

**Closed by Calinou** 2021-04-25 15:18 UTC
Labels: topic:core
