### ISSUE TITLE
Adding Copy/Paste/Cut options for AnimationTree nodes

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot-proposals#1442] opened 2020-08-31 20:28 UTC
**Describe the project you are working on:**
A 3d third person game.

**Describe the problem or limitation you are having in your project:**
I have to manage multiple animations and re-make the AnimationTree system some times to find the best way. For instance I want to move a BlendSpace2d node into another blending node. However, there is no way to move a node into another without re-making it which is time consuming. It would be good some simple options such as copy, paste, cut, duplicate and similar.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Adding the options when right mouse input is pressed and enable keys such as Ctrl + C, ...

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It is a core and useful feature for general purpose.

**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by Calinou** [comment] 2020-08-31 20:52
Duplicate of https://github.com/godotengine/godot-proposals/issues/955 and https://github.com/godotengine/godot-proposals/issues/106.

**Closed by Calinou** 2020-08-31 20:52 UTC
