### ISSUE TITLE
Improve using C++ in projects

### ISSUE THREAD

**Issue by rares45** [godotengine/godot-proposals#1904] opened 2020-11-28 20:58 UTC
### Describe the project you are working on
A 2D game with lots of items moving by code (GD Script).

### Describe the problem or limitation you are having in your project
Using C++ is way too hard, complicated and poorly documented(both using it and the code). And also the newcomers read about the fact that you can use C++, and then they found how and are disappointed and stick with GD Script.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I thought about this a lot and what I get to is being able to download some c++ builders from the editor itself.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
In the editor, you could download C++ builders, the same way you download the build templates. And these builders would compile the C++ into static libraries(I don't know how they would work on mobile platforms). The use of these builders could be disabled per project in the project settings. I know it could be complicated in implementing these, but this has three huge advantages:
More new contributors could write C++ code this way to check if it works and contributing it to the repo.
Easier to setup and more Unreal game-devs would try this engine.
AI. As I know GD doesn't have machine learning libraries as C++ has and it will be simpler to use.
Feel free to contradict me.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes.

### Is there a reason why this should be core and not an add-on in the asset library?
Not exactly, but the asset should have some little modifications in order to be able to install the builders outside of the project.

**Comment by Calinou** [comment] 2020-11-28 21:17
Duplicate of https://github.com/godotengine/godot-proposals/issues/573.

**Closed by Calinou** 2020-11-28 21:17 UTC
