### ISSUE TITLE
Add an INT_MAX and INT_MIN constant to GDScript

### ISSUE THREAD

**Issue by frozenMustelid** [godotengine/godot-proposals#5368] opened 2022-09-08 00:30 UTC
### Describe the project you are working on

I'm trying to write some savefile handling code, specifically something that will automatically add save slots if enough slots are filled. When starting a new game, you select a slot to put your new file in, and if the "last" slot is filled, another is added.

### Describe the problem or limitation you are having in your project

This system requires some more thorough error checking than an ordinary fixed-slot-count system, or a more PC-standard "select a slot every time you save" system. Since Godot lacks exceptions, and Godot likely won't see them anytime soon (possibly ever), I need some values that indicate an error.

In a dynamically-typed function, a workaround would be to return a string instead of an int, but dynamic typing is inherently less robust than static typing and code robustness is the reason I need to use INT_MAX and INT_MIN for error checking anyways.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The typical way to do error checking without exceptions is to have some special magic values that indicate a problem has occurred. These are usually close to INT_MAX or INT_MIN because when they show up, they're typically so far outside of the normal values that it forces someone to take notice.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

My proposal is for these constants to be in the global namespace like the PI, TAU, INF, and NAN constants.

example code:
```
const GENERAL_ERR                   := INT_MIN
const ERR_1                                  := INT_MIN+1
const DIFFERENT_ERR_TYPE     := INT_MAX
const DIFFERENT_ERR_TYPE_1 := INT_MAX-1

func do_stuff() ->int : 

    var value = func_that_may_fail()
     
     match value:
        GENERAL_ERR:
            handle_this()
        ERR_1:
            handle_that()
        DIFFERENT_ERR_TYPE:
            handle_other()
        DIFFERENT_ERR_TYPE_1:
            handle_which()

        return value
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I doubt anybody has an INT_MAX or INT_MIN constant in their GDScript if they weren't trying to duplicate this programming technique, or needed a bitmask of all 1s or all 1s except the sign bit.

### Is there a reason why this should be core and not an add-on in the asset library?

Adding the constants directly to GDScript would make code that uses them way more elegant than using a Constants singleton that contains the two constants.

In addition, if someone wanted to port the Godot runtime to an old or exotic system (think homebrew) and the int type changed its size as a result, then any code that directly codes in the signed 64-bit integer limits could crash or error out whereas using constants (that could be changed during the runtime porting process) would let the game continue. It's not like numbers past the signed 32-bit integer limits are common, so to have Godot projects fail on this (admittedly exotic and currently hypothetical) system would be a disappointing compatibility issue. After all, the point of runtime environments and bytecode is to be as compatible as possible across any platform that the runtime is ported to.

**Comment by Calinou** [comment] 2022-09-08 00:46
Duplicate of https://github.com/godotengine/godot-proposals/issues/2411.

**Closed by Calinou** 2022-09-08 00:46 UTC
