### ISSUE TITLE
Arm Support

### ISSUE THREAD

**Issue by DogsCodesStudio** [godotengine/godot-proposals#3934] opened 2022-02-08 23:21 UTC
### Describe the project you are working on

A game with multiplayer support that needs dedicated servers

### Describe the problem or limitation you are having in your project

Inability to export to arm based servers such as oracle servers.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

You will be able to export to arm based devices and servers that otherwise would require you to emulate.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

You go to export and click to export like with other exports there are.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It may be able to be done as a export template but may take a long time to do so.

### Is there a reason why this should be core and not an add-on in the asset library?

More and more servers and personal computers are starting to move over to arm and it will play a core part in different type of servers and personal computers.

**Comment by Calinou** [comment] 2022-02-08 23:45
Duplicate of https://github.com/godotengine/godot-proposals/issues/988.

Note that you can already compile your own (desktop or headless/server) Linux export templates for ARM. We just don't provide official binaries for this yet.

**Closed by Calinou** 2022-02-08 23:45 UTC
