### ISSUE TITLE
Disable Button signals on release outside of button

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#3035] opened 2021-07-23 10:54 UTC
### Describe the project you are working on

a game

### Describe the problem or limitation you are having in your project

The standard button has a 'keep pressed outside' option to show a visual only state of the button being depressed.

But there is no property or signal parameter to stop the signal being raised. The net result is you click and hold a button, drag your mouse outside, the button pops back up (if you have it default to off), but when you release the signal is still raised. This goes against how every button in every gui manager works and is counter intuitive. I can't think of a use-case where this is useful behaviour.

I know you can create a custom button class or code around this, but it should be a feature of the Button to not signal pressed when the mouse is outside the button.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a third 'action mode' property of 'button release when focused'.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

As above, do not raise a signal when outside the button if the flag/property is set.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I imagine it is how people would use it often.

### Is there a reason why this should be core and not an add-on in the asset library?

This is how people expect buttons to work, but Godot Buttons do not.

**Comment by chucklepie** [comment] 2021-07-23 11:11
I've just realised this is how it works, so I have a bug I need to trace and raise, which I believe it is caused by how container nodes are nested.

**Comment by Calinou** [comment] 2021-07-23 11:12
Duplicate of https://github.com/godotengine/godot-proposals/issues/2645.

**Closed by Calinou** 2021-07-23 11:12 UTC
