### ISSUE TITLE
make relative paths in ext_resource default

### ISSUE THREAD

**Issue by dpensi** [godotengine/godot-proposals#3060] opened 2021-07-29 16:56 UTC
### Describe the project you are working on

I'm working on this: https://github.com/dpensi/Backpack

More specifically I want to import it without hassle

### Describe the problem or limitation you are having in your project

The `ext_resource` in `.tscn` files is saved as an absolute path. For example in the file BackpackBus.tscn:

`[ext_resource path="res://BackpackBus.gd" type="Script" id=1]`

this means that when I copy the scene into another project, maybe in a subfolder, the editor complains about missing dependencies and I have to manually select the script `BackpackBus.gd` and fix it. For larger "import" this can be very tedious and error prone

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Interestingly, you can manually replace

`[ext_resource path="res://BackpackBus.gd" type="Script" id=1]` with
`[ext_resource path="BackpackBus.gd" type="Script" id=1]` his relative path

this works also if the script attached is in another folder, for example [here](https://github.com/dpensi/Backpack/blob/main/examples/Test.tscn#L3).

The project will still work and , more importantly, you can copy paste the scene into another project, in a subfolder, without getting any errors of missing dependencies from the editor, everything will work.

**Note:** eventually when you press `Play(F5)` the relative path you put by hand will be replaced again with the absolute path. Hence doing this by hand is very annoying 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Instead of saving absolute paths in `ext_resource` the editor could save relative paths and allow user to copy-paste their scenes everywhere without fixing the dependencies.

Hopefully this feature will be easier to implement than an actual modules/dependency handling feature, and can be provided in an useful time. We really need a way, even rudimentary, to handle big projects that require multiple repository or depend on other vendors scenes. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, you can edit the path by hand with a text editor. This of course is not ideal, especially considering that "when you press `Play(F5)` the relative path you put by hand will be replaced again with the absolute path" (my note on my "Describe the feature"

### Is there a reason why this should be core and not an add-on in the asset library?

from here this looks like a case of "why we didn't do this before?" 

But I understand that maybe there are complications that I cannot see

If I have time I'll try to make an add-on. For now, to my knowledge, there are no add-ons that import a project inside another project

**Comment by pycbouh** [comment] 2021-07-29 17:09
Duplicate of https://github.com/godotengine/godot-proposals/issues/2327

**Closed by pycbouh** 2021-07-29 17:09 UTC
