### ISSUE TITLE
List Printing

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#1603] opened 2020-10-03 09:10 UTC
**Describe the project you are working on:**
Not specific to a project, more of a general addition usable for helping debug Arrays and Dictionaries

**Describe the problem or limitation you are having in your project:**
Print when used on an array or a dictionary prints out an often very messy - hard to read set of data

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add a new Print type, a Print Iterate that would get the array/dictionary length and iterate.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
the code would look something like this for an array, and the general idea is the same for a dictionary:
`for length in range(len(array)): print(array[length])`

Example: 
Array [What, is, this, for?]

print(Array) Output: 
[What, is, this, for?]

printlist(Array) Output:
[
What,
is,
this,
for?
]

OR

[What,
is,
this,
for?]

OR no [] at all, any of the 3 would do.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
it can be worked around in 2 lines of code, however for people debugging arrays and dictionaries it'd be just as useful as print tree pretty is for debugging the scene tree.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It makes sense for it to be in the scripting languages as a core feature.

**Comment by Calinou** [comment] 2020-10-03 09:34
Duplicate of https://github.com/godotengine/godot-proposals/issues/538.

**Closed by Calinou** 2020-10-03 09:34 UTC
