### ISSUE TITLE
Custom documentation for projects and plugins

### ISSUE THREAD

**Issue by Boivin92** [godotengine/godot-proposals#489] opened 2020-02-16 16:22 UTC
**Describe the project you are working on:**
Godot W.A.T. (Waiting and Testing), a unit testing framework plugin

**Describe the problem or limitation you are having in your project:**
We cannot add documentation similar to the core engine's one, meaning that ctrl+click on functions or class names does not open up helpful info.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Adding a way to link a script to a markdown file, probably as a resource, would allow all plugins to come bundled with their documentation. It could also be used internally to a project, to keep the documentation files as closely linked to their material as possible, which also means that every deployment would come with the _right_ documentation for it (thanks, Git).

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![image](https://user-images.githubusercontent.com/8545474/74608208-38c1a300-50ad-11ea-82ef-827816316083.png)

We could add a button to the script editor that would open up the documentation resource for this particular script or create it if non-existent. Markdown is easier to write documentation for but I believe it's not something currently supported by Godot so maybe we could settle for BBCode?

To facilitate linking we could setup a standard. The documentation resource should be right next to the script (in the same folder) and have the same name as the script prefixed with "docs_".

exemple: if you have a player script you want to document, you should have a docs_player resource in the same folder.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, because the documentation framework in godot is currently baked in the compilation (as far as I know)

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because there is currently no way to add to the documentation framework, even through a plugin

**Comment by Calinou** [comment] 2020-02-16 17:02
Duplicate of #177.

**Closed by Calinou** 2020-02-16 17:02 UTC
