### ISSUE TITLE
Improve navigation in Texture Region menu with right-click

### ISSUE THREAD

**Issue by nice-shot** [godotengine/godot-proposals#1404] opened 2020-08-23 21:24 UTC
**Describe the project you are working on:**
2D UI Project.

**Describe the problem or limitation you are having in your project:**
I'm using a single sprite texture with several different elements inside of it. Most of the time I'm using the AtlasTexture resource and selecting a region using the Texture Region menu. However, navigating inside this menu is a bit uncomfortable since I can't use the right-click to scroll across the image, instead, I have to drag the scrollbars. I would expect to have the same controls as in the 2D scene view. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If I could navigate the Texture Region menu the same way I could the 2D scene view, it would greatly enhance my efficiency with this tool.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
When the pointer is inside the Texture Region menu, the user can right click and drag to scroll across the image. Exactly how this works in the 2D scene view.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It might be possible to create an alternative menu for Texture Region controls but this seems too complex for such a small change.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This seems like a simple UX quality of life improvement that should be part of the existing menu.

**Comment by Calinou** [comment] 2020-08-23 21:48
Note that panning in the 2D editor is possible with both the middle and right mouse buttons, not just the right mouse button. (In fact, panning with the right mouse button was added in Godot 3.2.)

**Comment by nice-shot** [comment] 2020-08-24 10:52
Good point. In general from a UX perspective I'd expect all 2D editors like the Texture Region to have the same navigation controls as the 2D viewport, so both right and middle mouse button.
Personally clicking the middle mouse button is never comfortable for me so I never use it. Even in programs like blender I always simulate it using alt+left button.
Now that you've mentioned it, it is a bit strange that Godot only simulated the middle mouse button in the 3D viewport and not in 2D...

**Comment by Calinou** [comment] 2020-08-24 12:40
@nice-shot Alt + Left click is already used in the 2D editor to perform a "disambiguated selection" when there are multiple overlying 2D nodes.

**Comment by nice-shot** [comment] 2020-08-24 18:11
I can see `alt+right click` shows a menu for "disambiguated selection" but `alt+left click` doesn't seem to do anything when I try it.
If `alt+left click` is implemented in the 2D editor for scrolling it could be very helpful when using tile maps since right click is used to erase in that and the scroll functionality is disabled. But this is a different issue.
For the suggestion here, if both middle-mouse and right-mouse scrolling could be implemented in the Texture Region Editor it would greatly improve the user experience.

**Comment by Calinou** [comment] 2023-07-13 18:18
- Duplicate of https://github.com/godotengine/godot-proposals/issues/4976.

**Closed by Calinou** 2023-07-13 18:18 UTC
Labels: topic:editor
