### ISSUE TITLE
Automaticly build solution when C# script is changed, instead of notifying the change

### ISSUE THREAD

**Issue by Hamster5295** [godotengine/godot-proposals#6305] opened 2023-02-17 15:46 UTC
### Describe the project you are working on

A game relying on C# script to run

### Describe the problem or limitation you are having in your project

I've using Visual Studio Code to develop. Every time I make changes to the script, Godot show dialog to inform me about that.
i.e. The picture below.
![1](https://user-images.githubusercontent.com/37259613/219697805-0742bec2-5382-498a-8848-75e17b2c6125.png)
That only happens in 4.0, which is annoying and useless, as I've already know that.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Identify it when user change the script manually. Do not show any message about that. It can't be better if it can be configued in the editor settings that whether to build the project after the script change automaticly or not.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When user make changes to the script in external editors, do not show any dialogs to inform them of the change.   
Futher more, a setting section is added to the **Editor Settings -> Dotnet -> Build** to let user decide whether an automatic build should be run after the C# script is changed

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No idea about that as i'm not familiar with the engine code. Sorry! : |

### Is there a reason why this should be core and not an add-on in the asset library?

It would be as usual as breathing when user is using C# to build the game. It's such a convinent function that few C# users can reject, especially those who has been working on Unity, which has already implenmented this function.

**Comment by Calinou** [comment] 2023-02-17 17:59
Duplicate of https://github.com/godotengine/godot-proposals/issues/2920.

**Closed by Calinou** 2023-02-17 17:59 UTC
Labels: topic:editor, topic:dotnet
