### ISSUE TITLE
move_towards_angle

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#7418] opened 2023-07-31 03:01 UTC
### Describe the project you are working on

SpaceShip Game

### Describe the problem or limitation you are having in your project

I would like to smoothly move toward a angle without having to write a wrapper for something that should exists along side lerp, lerp_angle and move_towards

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add move_towards_angle to compliment move_towards like lerp_angle compliments lerp

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

this would be done c++ side but..
```
func move_towards_angle(from:float, to:float, by:float)->float:
    return clamp(lerp_angle(from, to, 1.0), from-by, from+by)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

While this can be worked around with a few lines of script so can move_towards

### Is there a reason why this should be core and not an add-on in the asset library?

The 3 functions it compliments already exists it core.

**Comment by Zireael07** [comment] 2023-07-31 06:43
I think it was already proposed but it's 8am here and I'm still half-asleep so I can't find the #

**Comment by AThousandShips** [comment] 2023-07-31 08:34
Duplicate of https://github.com/godotengine/godot-proposals/issues/2074

**Closed by AThousandShips** 2023-07-31 08:34 UTC
Labels: topic:core
