### ISSUE TITLE
Ability to see raycast3d in game

### ISSUE THREAD

**Issue by MohammadAlkurd** [godotengine/godot-proposals#7837] opened 2023-09-24 13:11 UTC
### Describe the project you are working on

a laser that comes out of a simple gun

### Describe the problem or limitation you are having in your project

making a 3d line for the ray can be tricky because of scales and roations

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

it allows the raycast to be shown in game with a bool

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

this feature already exist in the editor so allowing it to be seen in game shouldn't be different same implementation but in the game

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it can be done by creating a line mesh 

### Is there a reason why this should be core and not an add-on in the asset library?

it is much easier to have it as a built in tool since godot  addons are just scripts / scenes

**Comment by Cykyrios** [comment] 2023-09-24 13:25
This is technically already possible, by enabling visible collision shapes in the debug menu of the editor; this will however show all collision shapes, and not only the raycast.

**Comment by Zireael07** [comment] 2023-09-24 13:36
@Cykyrios That however requires you to use the editor - won't work in production (standalone) builds of the game.

**Comment by smix8** [comment] 2023-09-24 14:03
The RayCast2D and RayCast3D already have debug visuals available on the node.

The issue is that one part of the debug logic checks the editor hint (so disabled outside the Editor) and one part checks the actual SceneTree collision debug flag (which works at runtime) so this should be fixed that it works in any debug build.

**Closed** 2023-11-28 16:51 UTC
Labels: topic:physics, topic:3d
