### ISSUE TITLE
Provide Android debug symbols with each new Godot release

### ISSUE THREAD

**Issue by avnerh1** [godotengine/godot-proposals#3047] opened 2021-07-26 19:47 UTC
### Describe the project you are working on

Escape room game for Android devices

### Describe the problem or limitation you are having in your project

Game crashes, I get the stack trace from Google's Play console, but it cannot be understood without debug symbols

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Whenever a new engine revision is released, also release with it a zip file containing the unstripped versions (with debug symbols) of `libgodot_android.so` and `libc++_shared.so` for all 4 CPUs types (arm, arm64, x86, x86_64).

Details about the process can be found here:
https://support.google.com/googleplay/android-developer/answer/9848633?hl=en#zippy=%2Cupload-files-using-play-console%2Cjava-generate-a-proguard-mapping-file%2Cnative-generate-a-debug-symbols-file

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I upload the zip file to Play console, and then I can understand the stack traces and figure out why my game crashed instead of guessing - especially needed for rare crashes that can't be reproduced easily.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think it will be used by almost all developers of games for Android.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't know about that.

**Comment by Calinou** [comment] 2021-07-26 19:49
Duplicate of https://github.com/godotengine/godot-proposals/issues/1342.

**Closed by Calinou** 2021-07-26 19:49 UTC
