### ISSUE TITLE
Allow binding mouse movement and mouse scrolling

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#8763] opened 2023-12-31 19:17 UTC
### Describe the project you are working on

SpaceShip game

### Describe the problem or limitation you are having in your project

I am using behavior trees and would like to reference mouse input through actions names

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow the following to be bound as a Input Action

- Mouse Move Up
- Mouse Move Down
- Mouse Move Left
- Mouse Move Right

- Mouse Scroll Up
- Mouse Scroll Down
- Mouse Scroll Left
- Mouse Scroll Right

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

They would be bound as MouseMotion events

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No. We can still manually check for mouse input but the point of input actions is so we can bind input for our games.

### Is there a reason why this should be core and not an add-on in the asset library?

InputMouseMotion is already an event so it should be pretty simple to implement.

**Comment by Shadowblitz16** [comment] 2023-12-31 19:58
@Mickeon 
The up, down, left, right are the four cardinal directions on a 2d plane
They can be combined into two axes `x` and `y` and one vector2

Mouse position would probably be read using `Input.get_vector`

**Comment by Mickeon** [comment] 2023-12-31 21:30
No, nothing of this can work in the current implementation of actions. Mouse movement is very, very inconsistent and prone to slight changes. Allowing InputEventMouseMotion events as actions would not benefit anyone the same way you may think they would. 


Depending on the implementation, the associated actions would be triggered either at the slight tilt of the mouse towards the desired direction, or not at all, because the detection is too precise. Neither are good.
Their `strength` value would wildly fluctuate. `strength` also needs to be a value between `0` and `1`, and remapping the mouse "speed" to that range would be very arbitrary.

If you want to have something like this exclusively for your project, you can try binding an InputEvent to an action manually, see the [InputMap](https://docs.godotengine.org/en/stable/classes/class_inputmap.html) documentation.

**Comment by AThousandShips** [comment] 2023-12-31 22:16
Duplicate of https://github.com/godotengine/godot-proposals/issues/3070

**Closed by AThousandShips** 2023-12-31 22:16 UTC
