### ISSUE TITLE
Script Token Information Popup

### ISSUE THREAD

**Issue by TheColorRed** [godotengine/godot-proposals#7376] opened 2023-07-25 23:45 UTC
### Describe the project you are working on

Not really important for the feature...

### Describe the problem or limitation you are having in your project

Not enough info in the script editor

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like to be able to mouse over different keywords/tokens in the script editor and a popup would show (similar to vscode and other editors) that would display the following information:

* data type (float, int, string, MyClass, enum, etc.)
* typedoc (the comment that is prefixed with `##`)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/1571806/cbed1007-9b40-49f2-8473-464733ff2382)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, this is application level.

### Is there a reason why this should be core and not an add-on in the asset library?

Affects the application.

**Comment by RedMser** [comment] 2023-07-26 00:22
Duplicate of #1393

**Closed** 2023-07-26 01:37 UTC
