### ISSUE TITLE
Change the standard Sky contribution from 1 to 0, to avoid blue tint . . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#544] opened 2020-03-02 12:51 UTC
**Describe the project you are working on:**
A Tomb Raider game, also an RTS, like Starcraft . .

**Describe the problem or limitation you are having in your project:**
As a beginner, when I open a new project, the colors are blue, not like in Blender, or like the color of textures, in paint programs . . This is confusing, and makes the game engine look a bit weird, strange . . . I had to go online to figure out what was wrong, and it took about 1 hour, I had also wondered about it many times before, how to fix it . . . It doesn't feel necessary . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
My idea is just to change the sky contribution to color, from 1 to 0, by default, it will make it a lot easier for new Godot users to make the games look exactly as they want, right now one has to search for a long time, to even find it, on pages . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I would ask to change to default sky contribution, in WorldEnvironment, under ambient from 1 to 0, so white looks white, no weird blue tint, for beginners, advanced users can always turn it up, also when out in the sun, things don't look blue, white is white, green is green, so it seems a bit odd, not working . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I think people will find Godot more pretty, and use it more, and advanced users will go in to tweak the settings anyway, and can set it there, as they want :)

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it's just confusing, to beginners, to find it, and it doesn't make any sense, the real world isn't blue, have a tint, like that . . .

![2020-03-02 0935](https://user-images.githubusercontent.com/61069740/75677897-bf20dc00-5c8c-11ea-8358-f5928a17fbaa.jpg)

I've been using Godot for over three months, I think, and I only figured it out today, the engine would make more sense, if things were like in the real world, as a default, in the game . . Don't know if this isn't big enough to be here, but they say online this is where one can make suggestions, the forums aren't the place, right now . . .:( Please help, a beginner . . .

**Comment by groud** [comment] 2020-03-02 12:57
I'll close this as a duplicate of #348, it covers the whole default environment problem (blue tint included).

**Closed by groud** 2020-03-02 12:57 UTC
