### ISSUE TITLE
Emit signal when property value changes

### ISSUE THREAD

**Issue by ismailgamedev** [godotengine/godot-proposals#9048] opened 2024-02-07 17:59 UTC
### Describe the project you are working on

Multiplayer Steam game.

### Describe the problem or limitation you are having in your project

I want to know from the signal which property has changed so that I don't send a package every frame.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A signal to detect which property has changed.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Emit the signal when the player changes property in any way.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It must be in the core of the engine.

### Is there a reason why this should be core and not an add-on in the asset library?

This feature saves us from writing unnecessary code and gives us much more flexibility.

**Comment by AThousandShips** [comment] 2024-02-07 18:01
Duplicate of:
* https://github.com/godotengine/godot-proposals/issues/4867

Consolidating there

**Closed by AThousandShips** 2024-02-07 18:01 UTC
