### ISSUE TITLE
Auto-Format Functionality

### ISSUE THREAD

**Issue by RilDev** [godotengine/godot-proposals#1757] opened 2020-11-01 22:54 UTC
**Describe the project you are working on:** I'm working on a project using scripts.

**Describe the problem or limitation you are having in your project:** There is no auto-format functionality in Godot yet.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:** A PEP 8 style auto-formater would improve the quality of the code base. Here is a link to the docs: [GScript Style Guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:** Ideally, there would be an option to check in the `editor settings` if we would like to auto-format on save, and the possibility to press `ctrl + f` to format the current script at any time.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** This enhancement would be used all the time, by many users!

**Is there a reason why this should be core and not an add-on in the asset library?:** Well, it could be an add-on. But this functionality is so basic that it should definitely included in Godot's core.

**Comment by Calinou** [comment] 2020-11-01 22:55
Duplicate of https://github.com/godotengine/godot-proposals/issues/1200.

**Closed by Calinou** 2020-11-01 22:55 UTC

**Comment by RilDev** [comment] 2020-11-01 22:56
Yes I just noticed it! Thanks for the quick feed-back!
