### ISSUE TITLE
Add a clear way to know when resources are shared, and by how many users

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#5921] opened 2022-12-10 13:38 UTC
### Describe the project you are working on

Various VFX

### Describe the problem or limitation you are having in your project

It happened to me more than once, that because materials are shared resources that need to be made unique, I accidentally modified some and had it influence other scenes, and i discovered this a lot later.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be useful if there was a way for Godot to show clearly that a material is shared across multiple scenes, and have the shared material by default raise a popup any time one of their parameters are changed. Alternatively, the UI should somehow show clearly somewhere that this is a "shared" resource and not a single-use resource.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't have many opinions on how it should be, I just want to stop shooting myself in the foot :D

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's about GodotEngine editor

### Is there a reason why this should be core and not an add-on in the asset library?

Could be prototyped as an addon - maybe someone can pick this up?

**Comment by Calinou** [comment] 2022-12-10 15:15
Duplicate of https://github.com/godotengine/godot-proposals/issues/904.

**Closed by Calinou** 2022-12-10 15:15 UTC

**Comment by KoBeWi** [comment] 2022-12-10 15:16
That proposal doesn't cover this part:

> by how many users

**Comment by Calinou** [comment] 2022-12-10 15:21
> That proposal doesn't cover this part:
>
>> by how many users

I've left a comment in the proposal to point this out
