### ISSUE TITLE
Add an option to the texture import tab to change normal map coordinate systems

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot-proposals#1784] opened 2020-11-06 17:14 UTC
**Describe the project you are working on:**
I'm working on a 3D game with an artist who has never worked with Godot before who lives on the other side of the world (so we're almost never working simultaneously). He uses Maya, which uses a different coordinate system from Godot.

**Describe the problem or limitation you are having in your project:**
The normal maps provided by my artist have a different coordinate setup, resulting in visual errors in the game. I could have him redo all his exports, but it would be much easier if I can fix it myself upon import in the engine. This would also help with importing assets from asset stores.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add an option in the texture import tab to change the coordinate space of the normal map. This way I as a developer can work independently from the artist and fix this issue myself.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
There are three variables (X + or -, Y + or -, Z + or -) for a normal map which each could feature either radio buttons or a dropdown list to switch between the options of each of those. This would be part of the texture import window.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, it currently depends on the artist who delivers the files.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It should ideally be applied on imported textures and not the source files themselves, I wouldn't know how to do that through an add-on.

**Comment by Calinou** [comment] 2020-11-06 17:50
Duplicate of https://github.com/godotengine/godot-proposals/issues/785.

**Closed by Calinou** 2020-11-06 17:50 UTC
