### ISSUE TITLE
Add hyperlink capabilities to Output tab with BBCode

### ISSUE THREAD

**Issue by awardell** [godotengine/godot-proposals#5638] opened 2022-10-22 22:56 UTC
### Describe the project you are working on

A game which uses gdscript

### Describe the problem or limitation you are having in your project

If I print something to the Output using print_debug or print_stack, I am provided with file names and line numbers, but I still need to manually navigate to those lines.

With print_rich I can print a link which appears clickable but is not.

I would love the convenience of such clickable hyperlinks in the output which can navigate me to code, websites, or resources.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be greatly convenient if working clickable hyperlinks could be embedded in the Output panel. They could be used to navigate to a line of code in a script in the same way that clicking on an Error or Warning in the debugger navigates to that line. They could also of course be used to open and navigate to a website url in the user's web browser. Potentially, they could also be used to navigate to a particular resource in the FileSystem tab.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

BBCode links in the Output panel should be clickable and navigate the user.

- If the link url begins with `http`, then it should open the user's web browser and navigate to that url.
- If the link url begins with `res`, then it should determine if the url is to a script or another resource.
  - If the url is to a script ending in .gd, then it should navigate to that script in the Script tab.
  - If the url is to a script ending in .cs, or if the user has an external editor configured for gdscript, then it should navigate to the script in the external editor.
  - If the url to a script ends with a line number after the file extension, then it should jump to that line number after navigating to the script.
  - If the url is to a resource but not to a script, then it should expand to and select that resource in the FileSystem tab.

Examples:
```
print_rich("[url=https://docs.godotengine.org/en/latest/]Click to read the docs![/url]")
print_rich("[url=res://HelloWorld.gd]This one opens in the Script tab[/url]")
print_rich("[url=res://HelloWorld.gd:23]This one also jumps to line 23[/url]")
print_rich("[url]res://HelloWorld.gd[/url]") #Per BBCode, this link's url is displayed
print_rich("[url=res://HelloFromCSharp.cs]This will open in the external editor[/url]")
print_rich("[url=res://BonjourFromParis.png]This will select the resource in FileSystem[/url]")
```

Additionally, print_debug and print_stack should be reworked so that where they print script/line numbers, they use Rich Text to provide hyperlinks which direct to those lines.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I cannot guarantee users would often use hyperlinks with print_rich, but users would often receive the benefit when they use print_debug and print_stack. As far as I know, there is not a simple workaround to achieve this other than deliberately using push_warning, which is bad form for something which should not be a warning.

### Is there a reason why this should be core and not an add-on in the asset library?

Rich Text in Output is already supported in core via print_rich, but the hyperlinks don't work, subverting user expectation. This feature would also improve workflow for all users of Godot via print_debug and print_rich in an unobtrusive way.

**Comment by awardell** [comment] 2022-10-22 22:59
Low priority of course! But I didn't find anyone already suggesting this, and I thought it was worth suggesting.

**Comment by Calinou** [comment] 2022-10-22 23:43
Duplicate of https://github.com/godotengine/godot-proposals/issues/1628.

**Closed** 2022-10-22 23:43 UTC
Labels: archived, topic:editor, usability

**Comment by awardell** [comment] 2022-10-23 00:18
@Calinou I didn't find the other proposal when I searched for related keywords. Sorry about that! Thanks for your work.

My proposal's scope seems somewhat larger than the one it's a duplicate of. Do you think that the specificities of this proposal warrant suggesting in that proposal? Do they belong somewhere else? Namely opening web urls, navving the FileSystem, and having print_debug and print_stack also clickable.

**Comment by Calinou** [comment] 2022-10-23 15:36
> My proposal's scope seems somewhat larger than the one it's a duplicate of. Do you think that the specificities of this proposal warrant suggesting in that proposal? Do they belong somewhere else? Namely opening web urls, navving the FileSystem, and having print_debug and print_stack also clickable.

The proposals are very close to each other, so I'd prefer to have both consolidated into a single proposal. Implementing clickable URLs should be easy if the rest is implemented.

Having `print_debug()`/`print_stack()` will automatically happen if valid script paths are printed. Built-in script paths probably can't be made to work here.

**Comment by awardell** [comment] 2022-10-23 20:26
>Built-in script paths probably can't be made to work here.

I'm unsure what you mean by built-in here

**Comment by Calinou** [comment] 2022-10-23 22:25
> I'm unsure what you mean by built-in here

A built-in script is a script that is not saved to a `.gd` file, but saved within a scene instead (`.tscn` or `.scn`).
