### ISSUE TITLE
Add more information for points in the 2D curve editor

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot-proposals#2902] opened 2021-06-22 20:21 UTC
### Describe the project you are working on
Various VFX and tech art

### Describe the problem or limitation you are having in your project
When doing precision work with curves, it's hard to have precise values

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Show the selected point exact values in the curve editor
![Screenshot_2021-06-22_22-20-26](https://user-images.githubusercontent.com/7917475/122993839-12e69580-d3a8-11eb-8795-7ddf37d96c92.png)
For example, it's really hard to select exactly zero in this curve.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Start by exposing the point array, then add a field at the top of the curve editor with the exact X Y values of the point

### If this enhancement will not be used often, can it be worked around with a few lines of script?
The built-in curve editor cannot be changed otherwise

### Is there a reason why this should be core and not an add-on in the asset library?
See above

**Comment by Calinou** [comment] 2021-06-22 20:31
> Start by exposing the point array

I think someone looked into doing this and said it was difficult to do. Gradient exposes points, but see how many issues it causes…

**Comment by QbieShay** [comment] 2021-06-22 20:37
Oh? I wasn't aware of issues with the exposed colors for the gradient.

Then that can be skipped and just the editor part should be done i think. it's useful :D (but please above the editor and not inside, otherwise you have to pan out like in unreal because the info covers the points)

**Comment by Calinou** [comment] 2021-06-22 21:43
> (but please above the editor and not inside, otherwise you have to pan out like in unreal because the info covers the points)

I would prefer if we made the display consistent with how it's done in the animation bezier editor.

**Comment by QbieShay** [comment] 2021-06-23 07:20
Oh sorry @Calinou , i just meant to put the info about the point above of where the curve is drawn instead of inside the canvas where the curve is drawn

**Comment by Xrayez** [comment] 2021-06-23 09:55
Duplicate of #48.

**Closed** 2022-05-17 18:00 UTC
Labels: topic:editor
