### ISSUE TITLE
Add the ability to move the Skeleton bones in the editor

### ISSUE THREAD

**Issue by anunknowperson** [godotengine/godot-proposals#2891] opened 2021-06-20 07:55 UTC
### Describe the project you are working on
Third-person shooter game
### Describe the problem or limitation you are having in your project
I want to animate a 3D character with a Skeleton imported from a third-party program. But I can't do that, because I can only manage the bones by directly changing their transformation matrix in the Skeleton inspector window, which is very inconvenient.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I think we need to add the ability to move the Skeleton bones in the Viewport.
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
When you select the Skeleton bone in the Viewport, a 3D gizmo should appear. This will greatly simplify the animation of complex characters.
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, you can't get around it with a couple of lines of code.
### Is there a reason why this should be core and not an add-on in the asset library?
This would be useful in any large 3D project. It will also increase the flexibility of the animation system.

**Comment by Zireael07** [comment] 2021-06-20 08:11
I believe this is being worked on...#45699 ?

**Comment by anunknowperson** [comment] 2021-06-20 08:19
Well, then that's fantastic.

**Comment by Calinou** [comment] 2021-06-20 09:51
Duplicate of https://github.com/godotengine/godot-proposals/issues/584.

**Closed by Calinou** 2021-06-20 09:51 UTC
