### ISSUE TITLE
Make it simpler for "Optimizing a build for size "

### ISSUE THREAD

**Issue by luffah** [godotengine/godot-proposals#1199] opened 2020-07-15 10:01 UTC
**Describe the project you are working on:**
Using the code of the game of tutorial to create 'your first game'.

**Describe the problem or limitation you are having in your project:**
Built size is too big. That cause issue on distribution and overload the internet.

I read the doc : Optimizing a build for size 
and the proposal is similar to "please recompile Godot to optimize the output build of you game".

This method seems problematic for distributing the engine and make the downloaded version of Godot looks like a demo version.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Alternatives (setting this by others ways) :
- add simple "Optimizing a build for size" feature (input to enable disable options) that doesn't ask to use scons at Godot compilation,  integrated to the project loader and customizable in project options.
- OR distribute a godot installer (gui) (that fetch the sources and recompile only what is need) to switch easily between presets
- OR distribute a godot compiler tool (a cli usable from exporter) aside of godot that (only) manage optimization

**Comment by Calinou** [comment] 2020-07-15 13:39
Duplicate of #1001.

**Closed by Calinou** 2020-07-15 13:39 UTC
