### ISSUE TITLE
TileSet > Physics > Collision shape editing: add option/mode allow snap to integer pixel (instead of half)

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot-proposals#6308] opened 2023-02-17 19:08 UTC
### Describe the project you are working on

A platformer with tilemap

### Describe the problem or limitation you are having in your project

I can snap tile collision shapes at half pixel, but not integer pixels, requiring extra precision to avoid falling mid-pixel each time.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow the user to snap to integer/full pixel with an extra button/dropdown in the TileSet Physics collision shape edit area.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Besides this toggle:

![image](https://user-images.githubusercontent.com/1067772/219764453-ff588abb-097a-4e34-a13a-6e23051f00ab.png)

we could add extra options:

a. There could be a second icon near Snap to half-pixel to Snap to (integer/full) pixel.

b. Or to avoid redundancy, we could replace the Snap to half-pixel toggle with an enum dropdown with 3 modes: no snap, snap to half, snap to full pixel.

c. Or, like Inkscape, we could have a global snap toggle, and then a second button that details the behavior: snap to half or snap to full pixel, only relevant when the first one is active (this could be a toggle or a dropdown)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

TileSet window is built-in

In addition, if we reuse the collision shape editor elsewhere than tileset, it will benefit from the new option everywhere

**Comment by Calinou** [comment] 2023-02-17 21:50
- Duplicate of https://github.com/godotengine/godot-proposals/issues/5847 (you can set the snap interval to 1 px in this case).

**Closed by Calinou** 2023-02-17 21:50 UTC
Labels: topic:editor, topic:2d

**Comment by nklbdev** [comment] 2023-02-25 13:53
Please take a look at my small [plugin](5d916e7b3754a6fc23d7a17c27f45c6e9c5e1590). Maybe it helps to add custom vertex snapping in future

**Comment by hsandt** [comment] 2023-02-26 13:04
> Please take a look at my small [plugin](5d916e7b3754a6fc23d7a17c27f45c6e9c5e1590). Maybe it helps to add custom vertex snapping in future

The link was going to an invalid commit, but I found the repo anyway: https://github.com/nklbdev/godot-4-tile_set_polygon_snapper

I suppose that for the implementation, they may get inspiration from the equivalent Godot 3 feature. But it's good to have this solution for the time being, I see it's already in the Asset Library so I'll try it when I need to edit polygons again!

**Comment by nklbdev** [comment] 2023-02-26 14:08
Oh, I'm sorry.

And be careful: I just renamed the repository:
https://github.com/nklbdev/godot-4-tile-set-polygon-snapper
