### ISSUE TITLE
add reflection probe support as an option to subviewport camera

### ISSUE THREAD

**Issue by djmaesen** [godotengine/godot-proposals#4813] opened 2022-07-05 04:06 UTC
### Describe the project you are working on

FPS

### Describe the problem or limitation you are having in your project

since render layers arent going to be implemented anytime soon, im using the 2 camera setup with a subviewport to render weapon models in godot 4.
however weapons in a subviewport dont get the data from reflection probes, only world environment reflection data. even when u check the visual instance layer of the weapons in the reflection probe setup.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

add option to enable reflection data in subviewport camera, this way weapon viewmodels get correct reflections.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

i assumed checking visualinstance layer for the weapons in the reflection probe would pass the reflection data to the weapon models. it doesnt as of now.
i know reflection probe data shouldnt be added by default to a subviewport. but maybe an option in the gui to do so?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

this will give better results in second camera rendering

**Comment by Calinou** [comment] 2022-07-05 15:27
Duplicate of https://github.com/godotengine/godot/issues/62358. Please don't create proposals for issues that haven't been properly triaged as bugs yet.

**Closed by Calinou** 2022-07-05 15:27 UTC
