### ISSUE TITLE
Add Interfaces to GDScript

### ISSUE THREAD

**Issue by SeremTitus** [godotengine/godot-proposals#8677] opened 2023-12-17 10:43 UTC
### Describe the project you are working on

A Godot project with a good amount of classes sharing the same methods but different implementation and a contractual way to ensure the methods are implemented might be helpful

### Describe the problem or limitation you are having in your project

Class Inheritance, does not  force methods are reimplemented and does not allow multiple inheritance

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

provides a contractual agreement that a class implementing a interface has all its classes

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here is an example on who it could work (each part could be in different files)
```gdscript
interface Damageable
var health: float = 100.0
func take_damage(amount)
func heal(amount)

interface Collects
var items:Array
func take_item(item)

class_name player
implements Damageable
implements Collects
#or implements Damage, Collects
var health: float = 10.0
var items:Array = []
func take_damage(amount):
   pass
func heal(amount)
   pass
func take_item(item)
   pass
```
- Parse error can catch for methods and variables not implemented
- If two interfaces implemented in the same class have the same method name with similar arguments types that is okay, but if different argument types that lead to error (at least untill gdscript has method overloading )... same for variables
- I think argument names should be ignored only type should be considered and also number of arguments
- To check if a class implements  a interface the "is" key word can be used
```gdscript
if obj_1 is Damageable:
  obj_1.take_damage(5.0)

```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

**Comment by AThousandShips** [comment] 2023-12-17 10:46
Duplicate of https://github.com/godotengine/godot-proposals/issues/6416

**Closed by AThousandShips** 2023-12-17 10:46 UTC
