### ISSUE TITLE
Add DLSS 2.0 support

### ISSUE THREAD

**Issue by Harutami** [godotengine/godot-proposals#2239] opened 2021-02-04 01:21 UTC
### Describe the project you are working on
I am working on a 3D Horror Game World with 2K textures

### Describe the problem or limitation you are having in your project
As the GPU Market tends to shift to AI up- and downscaling, games will tend to have GLSS in the future more likely. So first of all why shouldn't Godot have it, but everyone else? 2. It gives pretty much every game a major performance boost. 3. Even AMD will soon announce their FidelityFX driver, which will have their so called Super Resolution.

![graph](https://user-images.githubusercontent.com/58604290/106831096-96207c80-668f-11eb-9b72-a48ef8201341.png)
@ https://techengage.com/best-gaming-graphics-cards-gpus/ 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
DLSS helps games with bad performance on higher settings in an immense way. It would overcome some of the limitations Developers get with considering the Hardware of Players.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I personally don't know. NVIDIA for example has a DLSS beta program or you need to consultate a NVIDIA Developer to talk it out.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I don't think it can be worked around as it is from the companys themselves

### Is there a reason why this should be core and not an add-on in the asset library?
You could see DLSS as an Rendering enhancement and I don't think changing the rendering as an add-on is such a good idea. I don't know how big the program itself is, so if it is too big for Godot (in terms of Volume Space) then it could be added the same way as the Android Build Template.

Thanks for reading :)

**Comment by volzhs** [comment] 2021-02-04 02:22
accroding to [wikipedia](https://en.wikipedia.org/wiki/Deep_learning_super_sampling#:~:text=DLSS%202.0%20works%20as%20follows,the%20training%20of%20the%20network.)

### DLSS 2.0 works as follows:[14]

- The neural network is trained by Nvidia using "ideal" images of video games of ultra-high resolution on supercomputers and low resolution images of the same games. The result is stored on the video card driver. It is said that Nvidia uses DGX-1 servers to perform the training of the network.[15]
- The Neural Network stored on the driver compares the actual low resolution image with the reference and produce a full high resolution result. The inputs used by the trained Neural Network are the low resolution aliased images rendered by the game engine, and the low resolution, motion vectors from the same images, also generated by the game engine. The motion vectors tell the network which direction objects in the scene are moving from frame to frame, in order to estimate what the next frame will look like.[16]

**Comment by mrjustaguy** [comment] 2021-02-04 07:49
DLSS 2.0 Cannot be added to the game engine.. It has to be implemented on a Game by Game basis, and is not general enough to work on a Game engine basis. DLSS 3.0 or further maybe when the AI gets more general, or efficient enough that the AI training for the game can take place on local hardware instead of needing very powerful Servers to do so.

**Comment by Harutami** [comment] 2021-02-04 11:27
> DLSS 2.0 Cannot be added to the game engine (or any game engine really).. It has to be implemented on a Game by Game basis, and is not general enough to work on a Game engine basis. DLSS 3.0 or further maybe when the AI gets more general, or efficient enough that the AI training for the game can take place on local hardware instead of needing very powerful Servers to do so.

I am sorry to say but DLSS 2.0 is not per game basis. It's per Engine. See: https://developer.nvidia.com/dlss

![Screenshot_20210204_122710](https://user-images.githubusercontent.com/58604290/106886560-51730080-66e4-11eb-84ab-a80df1630a97.jpg)

**Comment by mrjustaguy** [comment] 2021-02-04 12:40
Ok my bad, I was under the impression that DLSS 2.0 was still not general enough and that it too needed a per-game training.

**Comment by Calinou** [comment] 2021-02-04 15:21
DLSS is a proprietary library, we can't integrate it officially in Godot. Since this *must* be done as a third-party effort, I'll close this as godot-proposals is only meant to discuss features to be added to core Godot.

**Closed by Calinou** 2021-02-04 15:21 UTC
Labels: topic:rendering

**Comment by mahdisml** [comment] 2021-06-02 00:27
> 
> 
> DLSS is a proprietary library; [we can't integrate it officially in Godot](https://docs.godotengine.org/en/latest/about/faq.html?highlight=faq#will-insert-closed-sdk-such-as-fmod-gameworks-etc-be-supported-in-godot). Since this feature _must_ be implemented as a third-party effort, I'll close this as godot-proposals is only meant to discuss features to be added to core Godot.
> 
> > Even AMD will soon announce their FidelityFX driver, which will have their so called Super Resolution.
> 
> When (and only when) AMD makes this solution public, it should be discussed in a separate proposal. We'll need to see if it's actually open source-friendly, because GPUOpen solutions have historically not always been open source (see [RadeonRays 2.0 vs 4.0](https://gpuopen.com/radeon-rays/)).

https://github.com/godotengine/godot-proposals/issues/2809

**Comment by tonymacx86PRO** [comment] 2023-01-07 17:31
Add DLSS now! Its is already open source https://github.com/NVIDIA/DLSS

**Comment by Calinou** [comment] 2023-01-07 18:31
> Add DLSS now! Its already open source [NVIDIA/DLSS](https://github.com/NVIDIA/DLSS)

It's under a proprietary EULA: https://github.com/NVIDIA/DLSS/blob/main/LICENSE.txt

**Comment by MikeZTM** [comment] 2023-09-28 00:10
> > Add DLSS now! Its already open source [NVIDIA/DLSS](https://github.com/NVIDIA/DLSS)
> 
> DLSS is still under a proprietary EULA: https://github.com/NVIDIA/DLSS/blob/main/LICENSE.txt Its full source code is also not publicly available – you have to dynamically link against a proprietary DLL to implement DLSS in an engine. (The DLSS 3 SDK is also not publicly released yet as of writing.)
> 
> Only NIS (NVIDIA's spatial upscaler, equivalent to FSR 1.0) is open source. Since FSR 1.0 is already present in 4.0.beta, I don't see much point in adding NIS. In general, FSR 1.0 is considered to look slightly better in practice while also being faster. NIS goes for a more conservative approach but ends up being more expensive, making it a less "bang for buck" spatial upscaler.
> 
> There are already plans to integrate FSR 2.0 in future 4.x releases.

https://github.com/NVIDIAGameWorks/Streamline

They have an open-source wrapper for both XeSS and DLSS and it's MIT licensed so should be compatible.
I think implementing this is benefiting a lot of users as it's quite inefficient to run FSR2 on NVIDIA and Intel GPUs. Starfield already generating a lot of noise on that front and it's pretty clear future game developer will facing same issue from PC audience.

**Comment by Calinou** [comment] 2023-09-28 00:17
> They have an open-source wrapper for both XeSS and DLSS and it's MIT licensed so should be compatible.

The wrapper is MIT-licensed, but the DLSS library is not (its source code isn't even available). Compiling your own version of Streamline also has limited functionality (namely, no DLSS Frame Generation):

> As of SL 2.0.0, it is now possible to recompile all of SL from source, with the exception of the DLSS-G plugin. The DLSS-G plugin is provided as prebuilt DLLs only. We also provide prebuilt DLLs (signed) for all other plugins that have source. Most application developers will never need to rebuild SL themselves, especially for shipping; all of the pieces needed to develop, debug and ship an application that integrates SL and its features are provided in the pre-existing directories bin/, include/, and lib/. Compiling from source is purely optional and likely of interest to a subset of SL application developers. For developers wishing to build SL from source, see the following sections.

There are other issues I can see with Streamline:

- It only supports Windows. DLSS can be made to work on native Linux applications – even though there are no such applications as of writing, the compiled DLSS libraries do have Linux ports.
- It looks difficult to build from source and integrate into another buildsystem (in our case, SCons).
- It doesn't support FSR, although we have our own implementation now, so it's not really an issue.

Also, remember that DLSS still requires you to inform NVIDIA of your game's release if it's a commercial project. FSR has no such restriction.

**Comment by MikeZTM** [comment] 2023-09-28 00:38
> The wrapper is MIT-licensed, but the DLSS library is not (its source code isn't even available). Compiling your own version of Streamline also has limited functionality (namely, no DLSS Frame Generation). Quoting from Streamline's README:
> 
> > As of SL 2.0.0, it is now possible to recompile all of SL from source, with the exception of the DLSS-G plugin. The DLSS-G plugin is provided as prebuilt DLLs only. We also provide prebuilt DLLs (signed) for all other plugins that have source. Most application developers will never need to rebuild SL themselves, especially for shipping; all of the pieces needed to develop, debug and ship an application that integrates SL and its features are provided in the pre-existing directories bin/, include/, and lib/. Compiling from source is purely optional and likely of interest to a subset of SL application developers. For developers wishing to build SL from source, see the following sections.
> 

It's better than nothing and DLSS-G plugin can be added by game developer without help from engine, though maybe not optimal in that case.

> * It only supports Windows. DLSS can be made to work on native Linux applications – even though there are no such applications as of writing, the compiled DLSS libraries do have Linux ports.

As far as I know, currently all Linux DLSS enabled title are running through proton and using an open source NVAPI implementation to pass through the data to Linux native DLSS binaries. I understand this limitation and the wish to have native Linux port of games, but if this wine passthrough thing could help more gamer to leave Windows I still think it is a good idea to have it than not.
And things may change if Intel actrully honor their open-source claim of XeSS or NVIDIA helping streamline to get native Linux support. Or even better, AMD stop their insane action and allow adding FSR2 support to Streamline.

> * It looks difficult to build from source and integrate into another buildsystem (in our case, SCons).

That's a valid issue. But I think as Streamline isn't changing a lot maybe it could be kept as a separate blob build. 

> * It doesn't support FSR, although we have our own implementation now, so it's not really an issue.

It doesn't support FSR2 for reasons and I think everyone agrees that we don't want a Starfield situation happens on game developers. I hope AMD could let it support FSR2 so no more complains. And adding streamline support on top of FSR2 implementation is quite straightforward.

> Also, remember that DLSS still requires you to inform NVIDIA of your game's release if it's a commercial project. FSR has no such restriction.
That's on game developer. You don't need to inform NVIDIA or Intel for using Streamline. Since developer need to get DLSS/XeSS SDK blobs from them anyway, they should follow what EULA that came with those files.

**Comment by mrjustaguy** [comment] 2023-09-28 07:36
Oh where do I start...

1. AMD isn't blocking FSR2 integration into streamline, that's a myth. They just aren't supporting it, but they cannot block it as they're releasing FSR2 under an MIT license.
2. Starfield situation has nothing to do with this, the game barely got shipped even after all the delays, thanks to AMD. It's a classic Bethesda game, what the hell did everyone expect? Also why would AMD (that did quite a bit of work for Bethesda's engine side to get it shippable) bother pushing their competitor's tech when they cannot use it themselves, and their alternative works on everything? It's a waste of their recourses
3. DLSS is an absolute QA Nightmare. That is why Game devs are not implementing DLSS and just going FSR2, no AMD blocking it like everyone (except MLID) is suggesting. Jedi survivor took ages to get DLSS support because of QA, heck, Fortnite, Epic's UE5 showcase, temp lost their DLSS support when they ported it to UE5 BECAUSE of QA.
4. It's a bad idea for this project to have to deal with support over all the bug reports for every single DLSS version upgrade that breaks something, it's a fairly well known issue that DLSS tends to get better at one thing, only to totally royally mess up something it did well before (hence the serious QA issues with DLSS, and why most of the time Nvidia has to shill out some resources to push their tech, or hope for often buggy mod support)

DLSS is not even close to being a low-hanging fruit, nor a priority given it's only for Nvidia users, and we already have a good enough upscaling tech thanks to AMD that also works for Nvidia users.
Should Nvidia decide to open up DLSS, both in terms of licensing and remove the vendor lock, and should they figure out how to stabilize it, that's when it can be seriously considered for integration...


And before somebody tries to call me an AMD shill, I've ran nothing but Nvidia for the last 22 years of my life and I've only like 2 months ago switched for the first time in my life to AMD, as I was not keen on getting screwed over by Nvidia and their insane price premium and getting a significantly worse product (240€ for RX6600 vs 300€ for RTX3050 in my region at the time of purchase)
I'm just going for what is the Better deal for me, and weighing in the risk of stuff breaking (big part of the reason why it took such an insane deal relative to Nvidia to make me make the switch was the risk of issues with my massive catalogue of software)

**Comment by Zireael07** [comment] 2023-09-28 19:06
If DLSS is known to be buggy, why integrate it?

**Comment by MikeZTM** [comment] 2023-09-28 19:10
> If DLSS is known to be buggy, why integrate it?

It definitely bring more benefits than being buggy.

Plus this is not only for DLSS, you got XeSS for free from integrating Streamline.

FSR is also buggy yet still got integrated. This is under-utilizing on Intel and NVIDIA hardware.

**Comment by mrjustaguy** [comment] 2023-09-28 20:13
I'm sorry, Devs supporting FSR but not DLSS is absolutely no evidence to suggest DLSS is blocked and that's the ONLY evidence that I've seen for it, while there's plenty of evidence that's been piled on against those accusations.

Look at it from their perspective. You have to QA only one tech instead of 2, so let's go with the one more people can use.
Proof this is the case: Fortnite UE5 port temporarily removed DLSS support due to QA, Jedi survivor got it in a patch much later down the line, Starfield announced DLSS support incoming, Starfield's day 1 DLSS mod plagued by numerous image quality issues, AMD officially stated (around gamescom, a few months late from their initial poor quality responses) that they do NOT block competing technology, only ask for it to get a priority boost over others in the games they Sponsored.

It needs to be open source with a compatible license to Godot to be officially integrated, so yes Open source with compatible license is very important and just because AMD users (don't forget Intel here now.. they don't have specialized/optimized hardware for DLSS too) wouldn't benefit from DLSS now doesn't mean they couldn't in the future get proper hardware acceleration if were open sourced.
To my knowledge only available Godot Compatible Upscaling tech is Nvidia's NIS which is just crappier FSR1 in every way, FSR1 which is already quite crappy as it's a spatial upscaling tech, and FSR2, and all the upscaling available that made sense is in Godot.
I don't think XeSS is not compatible license, and DLSS is absolutely not a compatible license, so this discussion is pointless until that changes

**Comment by MikeZTM** [comment] 2023-09-28 21:15
Streamline is MIT licensed so it is definitely compatible.

Intel does have dedicated hardware for XeSS. They have better int8 throughput and XMX unit for discrete GPUs.

for the QA thing. All machine learning AI stuff have this problem but you can not avoid them forever. It’s bring more benefits than troubles and it should be up for game developers to decide not the engine.

**Comment by mrjustaguy** [comment] 2023-09-29 10:00
streamline is MIT, but none of the tech that we'd need it for that we haven't implemented is compatible, That's the problem.

RDNA3 afaik has int8 too but I'm not sure how that's relevant.

I mean everything can be awful for QA, the problem with DLSS (maybe XeSS too, though never heard of this type of issue with that yet) is that every single version "Upgrade" often comes with a massive downgrade in some other region, which is a well known issue, and why techpowerup's DLSS dll library is so useful for tinkering, for switching out which version you are using to fix issues by going to older (or newer) versions for a game till you find one that works best.
This simply isn't even nearly as true for any other tech, as there usually there is much less change going on from version to version, and where there's a massive change it's typically much better tested for regressions and such.

I know, hence Temporarily removed, but non the less removed due to QA, plenty of devs just gonna go "No thanks" to all that work.

DLSS-XeSS-FSR2 all have more or less identical performance (especially DLSS & FSR2), and better quality depends.
I don't get that hypothetical at all, and even less how that's relevant.

They're called drivers, Anything that isn't optimized is underutilized and Godot does have intentional decisions that are "unoptimized" in the name of open source.
The wrapper doesn't work around the license if you have no legal way to test if it works.

How does only Supporting FSR which everyone supports but not being able to support DLSS equate to making an experience unusable for an Nvidia user?
Honestly this whole DLSS-FSR-XeSS discussion is kind of dumb, as in a blind test very very few users would be able to tell which tech they're using, and heck, many don't even know they're using any of those technologies.. So many times you'll hear people thinking that their Consoles are running their games at 4k, when they're running anywhere between 720p and 4k often upscaled using FSR2 these days, depending on the game and the DRS range..

**Comment by MikeZTM** [comment] 2023-09-29 13:45
@mahdisml 
It's pretty clear the quality difference is night and day and FSR2 is barely better than not having FSR2 while DLSS/XeSS is much more detail due to less historical pixel wasted in the sample pass and less mistakes lead to less artifacts. At 4k performance mode DLSS have less artifact than quality mode FSR2. 

This is not hypothetical, it's real and since you never really look into those techniques you never believe this is what happening.
You are fooled by AMD's marketing since their int8 is 2xFP32 while Intel have XMX unit for 8xFP32 and NVIDIA have Tensor Core for 8x FP32 throughput. Those unit are dedicated unit just share power budget with shader (and some dispatch overhead) and are really efficient on running the complex ML kernel to improve quality.

DLSS/XeSS is a must have feature not something you could argue. This is basically unfair since AMD lacking such hardware is dragging NVIDIA and Intel users, especially for those who have weak GPU that could really benefit from those features.

It's always up to developer to choose if they want to enable these feature (and include the blobs) or not. You can not do the decision for them. And please stop opensource gating Streamline: Godot support DX12 and that's not open source anyway.

**Comment by mrjustaguy** [comment] 2023-09-29 16:31
I happen to have been testing FSR2 integration in Godot, and I can say right away, I'd rather play at 720p FSR2 to 1440p vs 1080p bilinear to 1440p, so clearly it's better compared to just dropping native res, though I'd only ever use DLSS/FSR/XeSS/TSR/TAAU only as a last resort anyhow.

Your assumption is wrong. I've been following these techniques since they came out. Also how am I fooled by AMD's marketing if I stated they support something that they do, and it's just not as good as the competition which I never claimed it was?
If I were really fooled by marketing I'd have gone for the 7600 instead of the 6600.

I can argue that DLSS/XeSS is not a must have feature. Argument is to hell with Upscaling and optimize your games.
I'm never said DLSS/XeSS arent generally visually superior, I'm just saying that the gap isn't that large and that FSR2 is a good Compromise. Supports like every GPU from Maxwell+ and GCN+, Does a fairly good job, and is fairly straight forward and compatible with Godot.

Yes.

DX12 is a requirement for Platform Support (Console) while DLSS and XeSS are not a requirement for ANYTHING.
And by all means, if you want go ahead and implement Streamline into Godot. It'll get accepted or rejected on it's merits, like anything else. My point is that there is little point in wasting time of the people who are capable of implementing it and have other things to work on.

I just stated a fact, my mind set is to hell with any upscaling, but the point I made is that plenty of people just don't care as it's good enough to be successfully fooling them. Also you are ALWAYS under utilizing your hardware, and there's always tradeoffs to be made between things like - Simplicity, Performance, Quality, Flexibility, Size, Compute Usage, Memory Usage, Maintainability. You Cannot get the best of everything.

You started dramatizing this whole thing really, most of the time the discussion is kept civil though there are some proposals that can be controversial.
I'm not denying Nvidia and Intel users something because it doesn't benefit me. They've done the work to make it hard for Godot to get proper support...
I also didn't make a mistake switching to AMD, and it remains to be seen but so far it's been one of the best decisions I've made in the last couple of years by far.. and you telling me that one feature is important and that I've made a mistake based on your are using your stuff for without consideration for what My use case is.. well a bad way of assessing things. I've examined all the options and their pros and cons.
I picked the RX 6600 because of Adrenalin software (Per app Display setting overrides, an actual feature I'm using all the time now that Nvidia doesn't support) and price-perf was better vs Nvidia no matter what way you slice it, even if you compare Native AMD vs DLSS Nvidia as if it were apples to apples, which I don't, I want Upscaling as far away from my gaming experience as possible which is already making DLSS a null feature for me, if it weren't for the poor Game support (I have 2 games that Support DLSS right now, and they ain't very demanding, every actually demanding game I've got has no Upscaling support whatsoever)
To 3050 users any upscaling would be a godsend if they're trying to run at 4k, it'd just be better if they had DLSS, but FSR will get the job done too, so...

Optimization is a relative term. What are you optimizing for? Godot is Optimizing for ease of use and maintaining, and highly portable design over Performance, unless the Performance difference is Massive, which here isn't the case.
No one is doing this to match AMD, and I'm honestly baffled by how you got to that conclusion.
If you had made this comparison with Ray Tracing I'd have understood the point.. for DLSS support this comparison makes no sense to me. Everyone Equally benefits from FSR2.. But to keep to the comment, I'd go with whatever suits me and my goals best, naturally, which would be Vulkan due to being less limiting. I'd also ahem ahem, Go with Ray Tracing if it were viable now (as it'd be much simpler to make good graphics with it instead of hassling with poorly faking things with Raster), It's just not to any extent that makes sense to me, and it's sadly a tech that is still a decade from actually being usable IMHO.

**Comment by MikeZTM** [comment] 2023-09-29 16:42
@mrjustaguy
I clearly claimed FSR2 is better than not having it. And you don't need to bring up linear scaling to convince me. I'm fully aware of that and never said we shouldn't include FSR2.

I still hate to call FSR2/DLSS upscaling due to they are not doing any upscale anyway.
Since you should have already got background about FSR2, you should already know they are more resembling a downscale procedure. FSR2 is no different than DLSS in that front and it's important as an optimization method due to free 2x performance.

If bringing better image to lower mess is that not important for you then sure this could be ignored.

FSR2 is just like a variant of DLSS with less quality. But this quality difference is making DLSS/XeSS not a tradeoff of image quality anymore.
Quality mode DLSS can match downscaling image by SMRE/PSNR. Not saying that measure is perfect, but good enough for a comparison.

**Comment by mrjustaguy** [comment] 2023-09-29 17:01
you said it's barely better than not having it, that's what I commented on.

Upscaling is exactly what it's doing if you're not running Native by definition as it's adding pixels that didn't exist in the image before. and if it were free 2x performance, there'd be no reason to not use it and you wouldn't care which one you're using for that reason, but it's not as image quality suffers the lower you go.

Upscaling shouldn't be used for that, totally agree there, However excuses matter if they're legit. Like for example I'm making a game on an IGPU that has no RT support, my excuse for not making a AAA blockbuster Path traced masterpiece is that I don't have the ability to make it.

I cannot say I understand what you're trying to say here.

I don't see any game dev being called an Nvidia shill because they only support DLSS, I do however hear it a ton about AMD, and occasionally even Intel which I personally find a bit funny.. and besides, smaller devs got different expectations vs AAA studios that have the resources to do this, or when they don't support something that their Engine does like was the case with Star Wars.

**Comment by MikeZTM** [comment] 2023-09-29 17:08
Wait a second.
You do know that FSR2/DLSS is cherry-picking pixels from historical frames to fill in the gap between lower render resolution and output resolution right?

They are not magickly generating pixels and with good enough frame rate the result can be quite good or even better than native due to more pixels got reused and becomes super sampling.

**Comment by mrjustaguy** [comment] 2023-09-29 17:14
yeah. and that still fits in the definition of Upscaling.

I know it's not magic.. though DLSS 1 was just generating pixels based on input data as if I remember right it didn't take temporal data, just had to be trained on all the scenes at ultra high res, which is why it had such insanely horrible artifacts and was just AI doing educated guess work, though I may be wrong about this, as I didn't bother going into DLSS 1 when It was indisputable garbage that's worse than simple interpolation and sharpening (essentially NIS and FSR1)

**Comment by MikeZTM** [comment] 2023-09-29 17:19
You are absolutely correct about DLSS 1 as far as I know.
CAS beat DLSS1 in most cases, as DLSS1 is just an oil paint filter 99% of the time.

I still don't think that's **Up**scaling when you have more than native pixels to work with. Those pixels got wasted in traditional render and reusing them is just a clever way of render -- such innovation was always happening though out the 3D gaming era.

**Comment by mrjustaguy** [comment] 2023-09-29 17:25
by dictionary definition it is Upscaling, but Reconstruction works too.

**Comment by MikeZTM** [comment] 2023-09-29 17:39
Anyway I still think Streamline is worth the consideration as it really could help low end NVIDIA
/Intel GPU or iGPU. And the work left here is most likely related to devops instead of heavy engine changes since the FSR2 support is already exist.

**Comment by ikonnow** [comment] 2023-10-28 17:31
Hello, I'm interested in this proposal and I wonder what is the current status of it. I noticed that in the SDK v3.5, support for Linux kernel 2.6.32 and newer is mentioned (https://developer.nvidia.com/rtx/dlss/get-started#sdk-requirements). Does this mean that Godot will be able to use DLSS on Linux platforms soon? Thank you for your work and attention.

**Comment by Calinou** [comment] 2023-10-31 08:13
> Hello, I'm interested in this proposal and I wonder what is the current status of it. I noticed that in the SDK v3.5, support for Linux kernel 2.6.32 and newer is mentioned ([developer.nvidia.com/rtx/dlss/get-started#sdk-requirements](https://developer.nvidia.com/rtx/dlss/get-started#sdk-requirements)). Does this mean that Godot will be able to use DLSS on Linux platforms soon? Thank you for your work and attention.

As mentioned above, DLSS 2.x and later has had native Linux support for a long time (even if no Linux-native games currently support DLSS 2). The issue is that we can't integrate proprietary libraries in core, so it must be a community extension.

**Comment by BuyMyMojo** [comment] 2024-06-27 04:39
With the addition of [The Compositor](https://github.com/godotengine/godot/pull/80214) in 4.3 would it be viable to create extensions now instead of an engine fork or would the compositor still need to be expanded in the future to support this?

**Comment by mrjustaguy** [comment] 2024-09-14 11:01
There is no reliable way exposed to properly control camera jitter outside of core atm. 
https://github.com/godotengine/godot-proposals/issues/2779#issuecomment-2316081120
once that gets resolved I don't see any more problems

**Comment by johnlogostini** [comment] 2026-03-13 02:53
Though this is not a PR yet, and still in an early form, NVIDIA has officially added DLSS to their fork of Godot that they released at GDC today. I can link their source code, and it's all under MIT not DLSS itself, but the Godot interface is. I have been playing with it today, and it's fairly solid, barring a few graphical glitches.

Source Code: https://github.com/NVIDIA-RTX/godot/tree/nvidia-pt-dlss
Build: https://drive.google.com/file/d/1f_wyA4mCG9Bsiev9PgyKbI7Bq2Q5HhzT/view?usp=sharing

# Raw Image 100%
<img width="2560" height="1369" alt="Image" src="https://github.com/user-attachments/assets/8603e6c1-03b6-4f7c-9a1a-6f74b980b3b3" />

# TAA 100%
<img width="2560" height="1369" alt="Image" src="https://github.com/user-attachments/assets/c4b1f95c-013d-40f3-8e1d-0c39c986d1e3" />

# MSAA 2X 100%
<img width="2560" height="1369" alt="Image" src="https://github.com/user-attachments/assets/0bdf1d6d-4d60-4d7d-b95f-a5434aff2a3f" />

# MSAA 8X 100%
<img width="2560" height="1369" alt="Image" src="https://github.com/user-attachments/assets/1ad27c62-a8be-4ffe-bf1a-e681b65487c1" />

# FSR 1.0 100%
<img width="2560" height="1369" alt="Image" src="https://github.com/user-attachments/assets/fa5ae5c4-092a-46ff-904d-637fdb08e5b1" />

# FSR 1.0 50%
<img width="2560" height="1369" alt="Image" src="https://github.com/user-attachments/assets/27a7980a-4814-4573-b3e9-a9cab0c83c3f" />

# FSR 2.2 100%
<img width="2560" height="1369" alt="Image" src="https://github.com/user-attachments/assets/b31fe36f-e584-4a3a-81a1-7cb4515becaf" />

# FSR 2.2 50%
<img width="2560" height="1369" alt="Image" src="https://github.com/user-attachments/assets/cb5265bc-999f-4e85-a34e-4559d17d2600" />

# DLSS 100%
<img width="2560" height="1369" alt="Image" src="https://github.com/user-attachments/assets/49544f26-24ae-4d44-bed3-4f7555e19fa6" />

# DLSS 50%
<img width="2560" height="1369" alt="Image" src="https://github.com/user-attachments/assets/3bf54ca9-0190-4e48-b34d-d1c09b5b0076" />
