### ISSUE TITLE
Add in-editor playback/live preview for running scenes

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot-proposals#1864] opened 2020-11-20 14:29 UTC
**Describe the project you are working on:**
3D FPS

**Describe the problem or limitation you are having in your project:**
Unable to inspect graphically how the game is working outside the gameplay view

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add the ability to see how the nodes are behaving in the scene editor while the game is running. Juan said that once the vulkan integration were done it would be feasible to implement. https://github.com/godotengine/godot/pull/13354

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Sync the scene editor view with the game play in order to see objects moving / interacting / being deleted / etc in the editor to let the dev inspect if everything is working fine

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No script can do this

**Is there a reason why this should be core and not an add-on in the asset library?:**
The scene editor is core to the engine

**Comment by Calinou** [comment] 2020-11-20 14:45
Isn't the editor camear replication sufficient for this? https://github.com/godotengine/godot/pull/27742

**Comment by jcostello** [comment] 2020-11-20 14:56
@Calinou that its a helpful feature but for example im working in on a 3d shooter. It would be helpfull if I can play and in the meantime look at the editor to see everything from another perspective to see for example how the enemies are behaving. Do you think im missing  something to do that with the current features of godot 3.2.x?

**Comment by KoBeWi** [comment] 2020-11-20 21:22
Well, you could add a second camera/viewport to your game that would be monitoring enemies (something like split-screen). I think what is missing is being able to override specific camera. It only works for the main camera, so you'd need some special setup.

**Comment by jcostello** [comment] 2020-11-21 01:37
@KoBeWi yeah the idea would be to have this as default. Doing a split screen only for debugging sound like a lot of work in order to have it move also

**Comment by Zireael07** [comment] 2021-07-13 10:09
@timothyqiu: Not all properties can be inspected in the remote tree/running game - I often discover that Materials or Meshes aren't. IIRC there's an issue open for that already.

**Comment by timothyqiu** [comment] 2021-07-13 10:18
@Zireael07 Yeah, it's a bug if not shown. I fixed some cases that dynamically created resources not shown for 3.x in https://github.com/godotengine/godot/pull/44657, but I'm not sure if it covers all the causes why the property is not shown 🤣

**Comment by Calinou** [comment] 2021-07-13 13:10
> Sidenote: I need the wireframe rendering mode for this test. If I haven't google it already, I wouldn't know that the wireframe mode is somewhat available in the game view in Godot 3.x, but even then, it's kind of a trick rather than an 'officially supporred' functionality.

This makes me think the live scene editing should probablhy sync its debug draw mode with the running project.

**Comment by MickL** [comment] 2021-11-21 18:05
Opening a new window using fullscreen on macOS will leave the editor and go back to the desktop. This has two downsides:

1. You are not able to see the output / debugger
2. It gets you out of the flow / focus that you have with the fullscreen mode (and is kind of annoying)

Video: https://youtu.be/kZI56d0ddHo

Therefore I would highly appreciate if it is possible to run the game / scene within the editor, as Unity does.

**Comment by geekley** [comment] 2021-11-24 00:05
A simple feature that would help as a first step towards this is improving the Project Camera Override mode to optionally allow to **select remote objects by clicking them in game window**.
I imagine this would be simple enough that it could even be back-ported to current editor versions with just a tool script.

As a native editor feature, here's some alternative ways this toggle could be implemented:
1. As a button next to the "Project Camera Override" icon (maybe only visible when it's enabled); or
2. As a menu checkbox option when you right-click the "Project Camera Override" icon; or
3. Automatically enabled when both "Project Camera Override" is enabled and "Remote" is selected in the scene tree view

Of course, 2 or 3 would require an appropriate tooltip in "Project Camera Override" button to help discover the feature.

A "live preview" mode like Unity's is still ideal, but this simple feature would help a lot as a stopgap, because at least selecting one among multiple similar-named objects for inspection would be much easier.

**Comment by Zireael07** [comment] 2021-11-24 08:29
Project camera override AFAICT has nothing to do with this proposal...

**Comment by bodamat** [comment] 2022-07-15 22:10
Would be good to have the option to change something in the remote tree by editor window also then only in the inspector. To move and see it visually is much easier than just in numbers. It shouldn't also remember the changes, the remote tree should work like this now. 
It also will help to have 2 tabs: 1st is an editor with an open scene and 2nd is a game tab. As we see the layout of these tabs in the Unity picture above, will be also so convenient for making mobile games, especially in a vertical orientation.
This feature shouldn't replace running the game in the window. It would be better to have 2 different options like in Unreal.

**Comment by Norrox** [comment] 2022-07-16 08:16
As @Sosasees wrote in the other thread. Important to have the game window setting toggable in the settings if users want it in a tab or stand alone 🙂

**Comment by geekley** [comment] 2022-07-16 19:18
> Project camera override AFAICT has nothing to do with this proposal...

@Zireael07 My idea is a different method for achieving the same intent: better editor integration with running game by letting you select things in game window. I suggested it because it's (presumably) simpler to implement considering Godot's way of doing things. Project camera override is currently the closest thing we have to this feature request, since it allows the editor to navigate the running scene freely in game window. The only problem is that it doesn't allow selecting when enabled. If it did, you'd have a way to pick runtime-instantiated nodes by clicking, which isn't possible now, since remote nodes don't appear visually in the editor.
This would be equivalent of Unity's Scene View when play mode is enabled (you can click to select runtime-instantiated objects).

Sure, it's not ideal, but I suggested because it would be easier to implement and help a lot to at least have SOME way to do this.
It's not *quite* what this proposal is asking, but it would be a step in that direction.
Intention is somewhat close enough (though you'd use game window instead of scene editor):
> Add the ability to see how the nodes are behaving in the scene editor while the game is running

**Comment by Zireael07** [comment] 2022-07-17 12:00
Yeah, I agree completely that SOME way to do this is needed (even more urgently as it seems people are dropping Unity for Godot more and more often)

**Comment by xahon** [comment] 2022-07-21 16:21
@Zireael07 I agree. Personally I'm dropping unity right now in favor of godot

**Comment by HgGamer** [comment] 2022-07-25 10:02
Live scene view is one of the most missing features in the engine I think.

**Comment by Calinou** [comment] 2022-07-25 13:00
@HgGamer Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by BrandonGillis** [comment] 2022-10-04 18:06
Hello, any news on implementing this feature ? Is there any blocker in the Core that make this issue resolving not possible at the moment ?

**Comment by Calinou** [comment] 2022-10-04 18:13
> Any news on implementing this feature ? Is there any blocker in the Core that make this feature not possible at the moment ?

Implementing this with "in-process" running is probably not going to happen, as it's very difficult to do right and has many implications (e.g. game process crashing would also crash the editor).

I think the only way to implement this while following the Godot philosophy is to perform fake embedding. In other words, spawn a borderless window that matches the 3D viewport's size and is automatically hidden when the editor window isn't focused anymore. This way, the game process remains entirely separate from the editor.

**Comment by BrandonGillis** [comment] 2022-10-04 18:27
> > Any news on implementing this feature ? Is there any blocker in the Core that make this feature not possible at the moment ?
> 
> Implementing this with "in-process" running is probably not going to happen, as it's very difficult to do right and has many implications. For example, the game process crashing would also crash the editor, leading to possible data loss.
> 
> I think the only way to implement this while following the Godot philosophy is to perform [fake run embedding](https://github.com/vitorbalbio/GodotFakeEmbedded). In other words, spawn a borderless window that matches the 3D viewport's size and is automatically hidden when the editor window isn't focused anymore. This way, the game process remains entirely separate from the editor like it is currently. This is non-trivial to do correctly, as you need to move/resize the window when the editor dock is resized.
> 
> The alternative way to do this without sharing process space is to [implement an IPC mechanism and send the running project's image to the editor](https://github.com/godotengine/godot/pull/29136). While you don't need to perform window manipulation anymore, there's a lot of complexity involved:
> 
> * You need to render the running project without spawning a window for it (off-screen rendering).
> * You need to send the image to the editor at a high enough framerate, without noticeable compression artifacts. Even then, the lower framerate as a result of streaming data can make performance testing misleading.
> * You need to send all inputs (mouse and keyboard, [gamepad forwarding isn't needed](https://github.com/godotengine/godot/issues/16832)) to the running project.

I don't really know the internals of godot core, but at the moment there's already the ability to see nodes remotely. Wouldn't it be faisible to use that remote node tree that is synced, to build a new "remote scene" inside the editor ?

**Comment by neikeq** [comment] 2022-10-05 12:06
Here and in other engines I keep hearing the suggestion about running the game on a separate process and then displaying its image in the editor somehow. But I don't see any explanation on how the editor tools (Inspector, Scene Tree, Animation Dock, and a long etc) would interact with the game. Making them work with the game via IPC sounds like a huge increase in complexity. Even then I'm not sure if the result would be desirable; for example, our current remote scene tree and remote inspector have very noticeably low refresh rates. Would an implementation via IPC be able to achieve high refresh rates?

From my perspective, the two solutions I know are:

- **Running the game in the editor process like Unity does.** It would require a lot of work and changing bad code practices (e.g.: I don't know if singletons are compatible with this). Even then there are downsides we likely can't solve, like potentially crashing the editor, which might be more likely in our case than in Unity.
- **Embedding the editor tools in the running game.** This is the solution I gravitate towards for its simplicity. It would still require refactoring editor code to make sure it works in game mode (it likely shouldn't overwrite any project files/scenes/resources).

**Comment by BrandonGillis** [comment] 2022-10-05 12:20
In my opinion, if it's done via IPC like the current remote node tree it wouldn't be that bad if the refresh rate is slow. The purpose of this feature for the majority of users (if I'm not wrong) is to make debugging easier.

For a first implementation, I think it would still be beneficial to the user even if the refresh rate is not that good.

I could be wrong though as this is a personal opinion, in that case maybe we could redefine a more indepth scope about what's expected with this feature

**Comment by Calinou** [comment] 2022-10-05 16:14
> Would an implementation via IPC be able to achieve high refresh rates?

https://github.com/godotengine/godot/pull/29136 only refreshed at 10 Hz. I'm not sure how high it could have been bumped in theory, but I think going above 30 Hz will prove challenging.

**Comment by BrandonGillis** [comment] 2022-10-05 17:08
> **Describe the project you are working on:** 3D FPS
> 
> **Describe the problem or limitation you are having in your project:** Unable to inspect graphically how the game is working outside the gameplay view
> 
> **Describe the feature / enhancement and how it helps to overcome the problem or limitation:** Add the ability to see how the nodes are behaving in the scene editor while the game is running. Juan said that once the vulkan integration were done it would be feasible to implement. [godotengine/godot#13354](https://github.com/godotengine/godot/pull/13354)
> 
> **Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:** Sync the scene editor view with the game play in order to see objects moving / interacting / being deleted / etc in the editor to let the dev inspect if everything is working fine
> 
> **If this enhancement will not be used often, can it be worked around with a few lines of script?:** No script can do this
> 
> **Is there a reason why this should be core and not an add-on in the asset library?:** The scene editor is core to the engine

If I'm not mistaken the initial proposal was to sync the remote scene in the editor.

> Sync the scene editor view with the game play in order to see objects moving / interacting / being deleted / etc in the editor to let the dev inspect if everything is working fine

When reading your answers it looks like you speak about rendering the "running game" inside the editor, which is not the same as syncing the scene in the editor.

Remote node tree are already synced to the editor, the only missing pieces is rendering these remote nodes inside an editor scene to have a visual feedback of these remote nodes.

**Comment by jcostello** [comment] 2022-10-05 18:24
As the OP

> > **Describe the project you are working on:** 3D FPS
> > **Describe the problem or limitation you are having in your project:** Unable to inspect graphically how the game is working outside the gameplay view
> > **Describe the feature / enhancement and how it helps to overcome the problem or limitation:** Add the ability to see how the nodes are behaving in the scene editor while the game is running. Juan said that once the vulkan integration were done it would be feasible to implement. [godotengine/godot#13354](https://github.com/godotengine/godot/pull/13354)
> > **Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:** Sync the scene editor view with the game play in order to see objects moving / interacting / being deleted / etc in the editor to let the dev inspect if everything is working fine
> > **If this enhancement will not be used often, can it be worked around with a few lines of script?:** No script can do this
> > **Is there a reason why this should be core and not an add-on in the asset library?:** The scene editor is core to the engine
> 
> If I'm not mistaken the initial proposal was to sync the remote scene in the editor.
> 
> > Sync the scene editor view with the game play in order to see objects moving / interacting / being deleted / etc in the editor to let the dev inspect if everything is working fine
> 
> When reading your answers it looks like you speak about rendering the "running game" inside the editor, which is not the same as syncing the scene in the editor.
> 
> Remote node tree are already synced to the editor, the only missing pieces is rendering these remote nodes inside an editor scene to have a visual feedback of these remote nodes.
> 
> Video example of unity : https://youtu.be/lXunqoE3GPo
> 
> As we can see, on the left side we have the running game, and inside the editor we can see the "nodes" being modified in the scene.

As the OP I can confirm that this is the proposal original intention

**Comment by TheBricktop** [comment] 2022-10-11 15:45
>     * **Embedding the editor tools in the running game.** This is the solution I gravitate towards for its simplicity. It would still require refactoring editor code to make sure it works in game mode (it likely shouldn't overwrite any project files/scenes/resources).

I think this is a winner in terms of achievieing the aforementioned function and avoiding too making too much changes to the core editor.

**Comment by YuriSizov** [comment] 2022-10-11 18:30
> Remote node tree are already synced to the editor, the only missing pieces is rendering these remote nodes inside an editor scene to have a visual feedback of these remote nodes.

Remote tree is only _inspected_ in the editor. That "only thing missing" is pretty much the most complex part. It's practically the same as running the entire game/playing scene in the editor, which is not a trivial task. If you want to interact with your playing scene from the editor's rendered viewport, then it must be executed in the editor environment. And creating some kind of dumb copy of the remote scene tree that would be "display only" and void of any logic is probably a way harder task than that.

**Comment by Aiden-Potter** [comment] 2023-05-10 09:47
We need play in editor!!!
Runtime object selection,will accelerate game devlopment.

**Comment by Calinou** [comment] 2023-05-10 16:26
@Aiden-Potter Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by Calinou** [comment] 2023-07-06 12:11
Closing in favor of https://github.com/godotengine/godot-proposals/issues/7213, which provides a more detailed technical implementation.

**Closed by Calinou** 2023-07-06 12:11 UTC
Labels: topic:editor

**Comment by Mohammad9760** [comment] 2024-08-09 06:23
@Calinou 
do you get paid to just close issues that are not solved???

**Comment by sosasees** [comment] 2024-08-09 07:33
GitHub has two kinds of closed issues:
- closed for solved
  , which has a checkmark icon
- closed for not planned
  , which has a strikethrough icon

this issue is "closed for solved" but it should be "closed for not planned"

**Comment by timothyqiu** [comment] 2024-08-09 07:52
@sosasees While GitHub claims that "close as not planned" encompasses scenarios involving duplicate issues, it sounds more like a rejection.

Personally, I believe that using "close as not planned" will create more confusion :P

**Comment by Calinou** [comment] 2024-08-09 16:16
We stopped using "close as not planned" recently because its UI on GitHub is really confusing, and GitHub is unlikely to change it in significant ways anytime soon.

Instead, we use "close as resolved" and apply an `archived` label as we did before the "close as not planned" feature was implemented on GitHub.

It's too bad as the concept behind "close as not planned" is great, but the execution makes it unusable in public projects in practice.

**Comment by sosasees** [comment] 2024-08-09 18:23
so "close as not planned" is unusable because it can be understood in 2 ways:
- based on the name, i think it means
the issue is closed because the maintainers either don't want to solve it or they think it's not an actual issue that the project has
- according to GitHub's documentation, it means
the issue is closed because it was already reported by someone else

**Comment by timothyqiu** [comment] 2024-08-10 03:01
FYI: According to [GitHub](https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/), these cases should all use "Close as not planned":

1. Won't fix
2. Can't reproduce
3. Duplicated
4. Stale

**Comment by sosasees** [comment] 2024-08-10 10:41
the fact that we needed this discussion is a testament to how confusing "close as not planned" is

**Comment by sommerper** [comment] 2026-05-08 13:15
I don't understand why this issue was closed in favor of https://github.com/godotengine/godot-proposals/issues/7213 They are not the same at all.

**Comment by poyribn** [comment] 2026-05-08 22:38
The other Issue implemented this Feature in the Game Window.
You can change the Camera to free Mode and enable Select Mode to select the Object you want.

This is a bit different from Unity but it does the same Thing. I forgot the Details of why that is but i still remember that Godot has to do it in the Game Window and not directly in the Editor because of technical Limitations.

**Comment by KoBeWi** [comment] 2026-05-08 22:43
Now that Game tab exists, an alternative is unlikely to be implemented.

**Comment by ltade** [comment] 2026-09-04 13:08
> Now that Game tab exists, an alternative is unlikely to be implemented.

Game tab is not an alternative to this feature, those features can co-exist.

in fact unity by default already does both of those things - both embedded game and scene editor (which is synced up with the game) can be accessed side by side, in same unity window.

**Comment by KoBeWi** [comment] 2026-09-04 13:11
What would this feature bring that Game view doesn't already?

**Comment by ltade** [comment] 2026-09-04 13:19
> What would this feature bring that Game view doesn't already?

This feature would give better scene editor experience. 
Game view/tab is not scene editor, its a game, so the fact that now it can be embeded in godot window, improves only game access experience, not scene editor experience.
So, completely different features in my mind.

**Comment by KoBeWi** [comment] 2026-09-04 13:24
https://github.com/godotengine/godot/pull/122510 adds editing capabilities to Game view (2D-only, 3D will come in a follow-up).

**Comment by ltade** [comment] 2026-09-04 13:33
> [godotengine/godot#122510](https://github.com/godotengine/godot/pull/122510) adds editing capabilities to Game view (2D-only, 3D will come in a follow-up).

Thats interesting, but counter productive i think.
why make game view be also edit when it should be meant to just display and control the game, one problem is that editor inputs and game inputs will clash.
scene editor should be for scene editing and game view should be for game.
i think scene editor syncing with game would is useful mainly for easier debugging and visually inspecting nodes.

**Comment by KoBeWi** [comment] 2026-09-04 14:07
> easier debugging and visually inspecting nodes.

Both are already possible. Like, you can move the camera anywhere in the scene, click any node and inspect it.

And it's not like editor syncing would fix any of the existing shortcomings, because it would be implemented similar to the existing live debugging. The game would literally have to run inside the editor to make a meaningful difference. See #9142 for a related proposal.
