### ISSUE TITLE
File system dock feature / enchancement 

### ISSUE THREAD

**Issue by Puveil229** [godotengine/godot-proposals#5499] opened 2022-09-26 21:16 UTC
### Describe the project you are working on

A 2D simple RPG game to learn

### Describe the problem or limitation you are having in your project

The file system dock doesn't show files that are important for the game development

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like the file system dock allows to see all types of files, and I think, that the godot editor should be able to edit plain text files like .txt or .json

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

You can see all the files in the file system dock and you can open them and edit the plain text files like .txt or .json

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know, but i didn't find the way

### Is there a reason why this should be core and not an add-on in the asset library?

This is a very useful to program, because it allows you to have more control

**Comment by Calinou** [comment] 2022-09-26 21:24
Duplicate of https://github.com/godotengine/godot-proposals/issues/677.

PS: In the future, please use the [Discussions tab](https://github.com/godotengine/godot-proposals/discussions) for proposals that don't have a concrete technical implementation.

**Closed by Calinou** 2022-09-26 21:24 UTC
