### ISSUE TITLE
Display README files in the FileSystem dock

### ISSUE THREAD

**Issue by MaxLap** [godotengine/godot-proposals#3217] opened 2021-08-28 17:26 UTC
### Describe the project you are working on

I'm learning the Godot engine by looking at demos.

### Describe the problem or limitation you are having in your project

You have no indication that a README file exists in demo projects. And if you know about it, the only way to view the README.md (or other extensions) is to open the root directory in a File Manager.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Show README files in the FileSystem dock and allow opening them.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Files named "README", with any extension should be displayed in the FileSystem dock. Trying to open it would, ideally, open it in the scripting tab. Even if right now, there is no special handling for the format, just showing plain text would be enough.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You want the basic tools to help people learn to be built-in so they can help newcomers with as little friction as possible. This also encourages authors to write more/better READMEs, they need to be easily accessible and discoverable.

### Is there a reason why this should be core and not an add-on in the asset library?

New users, like me, are not even aware that such important files are hidden there. So I've opened some demos, couldn't understand what was going on, and I had no clue there was a readme explaining some details, or giving reference material.

If the README is more visible/reacheable, it will also encourage authors of demos to write more explanations to it.

**Comment by KoBeWi** [comment] 2021-08-28 19:51
> And if you know about it, the only way to view the README.md (or other extensions) is to open the root directory in a File Manager.

You can also open it from within Script Editor. It has support for any text file, but it's a bit hidden.

**Comment by MaxLap** [comment] 2021-08-28 20:18
I see what you mean. Script Editor > File > Open... > Change the "all recognized" to "all files". Then it appears.

And that's when you know there is a README file to look for.

So opening the file is already supported, that's great. Just need the tweaks to make it easier to discover that the file exists.

**Comment by Calinou** [comment] 2021-08-28 21:12
Duplicate of https://github.com/godotengine/godot-proposals/issues/677.

**Closed by Calinou** 2021-08-28 21:12 UTC
Labels: topic:editor

**Comment by MaxLap** [comment] 2021-08-29 14:14
Respectfully, I disagree that this is a duplicate of #677. #677 is about unsupported files, where as here text files are supported but not shown in the dock. Also, having to possibly toggle a button to see the README would again go against the idea of making it easily discoverable for users.

**Comment by Calinou** [comment] 2021-08-29 14:37
> where as here text files are supported but not shown in the dock

The TextFile resource is no longer exposed in 4.0: https://github.com/godotengine/godot/pull/51845
