### ISSUE TITLE
Expose built-in EditorProperties

### ISSUE THREAD

**Issue by Atlinx** [godotengine/godot-proposals#3053] opened 2021-07-28 19:38 UTC
### Describe the project you are working on

GDScript plugin.

### Describe the problem or limitation you are having in your project

Whenever I want to create a custom inspector that utilizes an existing EditorProperty (such as the EditorPropertyNodePath, which displays UI for assigning NodePaths) I must rewrite the EditorProperty completely from scratch or have to traverse the scene tree to hijack an existing instance of the built-in EditorProperty.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The engine should expose built-in EditorProperties, allowing plugin developers to easily use existing EditorProperties without reimplementing them or hijacking existing instances of them. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I'm not too familiar with how Godot exposes classes so I can't say for sure how this will be implemented. If anyone knows a possible solution feel free to comment so I can edit my proposal to include it.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This cannot be worked around with GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

This cannot be worked around with GDScript.

**Comment by pycbouh** [comment] 2021-07-28 19:42
Duplicate of https://github.com/godotengine/godot-proposals/issues/1761, https://github.com/godotengine/godot-proposals/issues/300

**Closed by pycbouh** 2021-07-28 19:42 UTC
