### ISSUE TITLE
Enter commands to a dedicated server

### ISSUE THREAD

**Issue by Gamemap** [godotengine/godot-proposals#3833] opened 2022-01-19 23:10 UTC
### Describe the project you are working on

Multiplayer game with dedicated server.

### Describe the problem or limitation you are having in your project

After starting the server over the command line I want to run commands (e.g. ban, restart, etc.) in the console.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Type a command in the output terminal and press enter.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

You enter a command and press Enter, Godot stores the entered text in a variable and you can read the variable e.g. in the process function.
---
In this example `/stop` would be saved into the variable.
![grafik](https://user-images.githubusercontent.com/71942164/150232517-3a514e3a-09b4-4baa-9f89-e1aa3012d0f4.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

I think this in an important to run commands from the server and not only from clients.
(e.g. If you accedently removed your admin status you can change it back with the console)

**Comment by Calinou** [comment] 2022-01-19 23:11
Duplicate of https://github.com/godotengine/godot-proposals/issues/2322.

**Closed by Calinou** 2022-01-19 23:11 UTC
