### ISSUE TITLE
Add pointers in gdscript

### ISSUE THREAD

**Issue by kaissouDev** [godotengine/godot-proposals#7212] opened 2023-07-06 09:56 UTC
### Describe the project you are working on

I'm working on a 2.5D game

### Describe the problem or limitation you are having in your project

In my 2.5d game, I'd like to control memory without using c++ or c#, totally natively.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The addition of pointers will allow you to control memory as you wish without using other languages that require compilers, but I'd like this feature to be optional, as it is in C#.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Example:

``` var a = 12 
     var *ptr_a = &a
      
     print(ptr_a)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, I don't think that's possible.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, perhaps using c++ language with gdextention or c#.

**Comment by dalexeev** [comment] 2023-07-06 11:54
See also:

* #2817
* #3497
* #4990

**Comment by Calinou** [comment] 2023-07-06 12:13
Duplicate of https://github.com/godotengine/godot-proposals/issues/2817 and/or https://github.com/godotengine/godot-proposals/issues/3497.

**Closed by Calinou** 2023-07-06 12:13 UTC
Labels: topic:gdscript
