### ISSUE TITLE
Add support for mouse back and forward buttons in the editor

### ISSUE THREAD

**Issue by MattRix** [godotengine/godot-proposals#1702] opened 2020-10-22 04:10 UTC
**Describe the project you are working on:**

Making an indie game with Godot

**Describe the problem or limitation you are having in your project:**

The back and forward buttons on a mouse do not work on in the editor to go back and forward

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Supporting mouse back and forward buttons 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

The back and forward mouse buttons would act just like pressing alt+left and alt+right do right now

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Not that I know of? Maybe installing a program like autohotkey in the OS, I suppose. 

**Is there a reason why this should be core and not an add-on in the asset library?:**

It is a core usability feature

**Comment by Calinou** [comment] 2020-10-22 10:27
Duplicate of https://github.com/godotengine/godot-proposals/issues/954.

**Closed by Calinou** 2020-10-22 10:27 UTC
