### ISSUE TITLE
Allow controlling fog blend mode / Add support for dark fog

### ISSUE THREAD

**Issue by jcandres** [godotengine/godot-proposals#8732] opened 2023-12-27 11:27 UTC
### Describe the project you are working on

A retro 3D dungeon crawler.

### Describe the problem or limitation you are having in your project

Fog in Godot 4 is difficult to art direct. Besides other changes, fog is now additive. That removes de possibility of using fog with a dark color (using pure black removes the fog), which is very useful for faking darkness in unlit scenes. This is particularly handy since fog is well integrated in the renderer and materials have built in options for fog interaction.
Also, additive fog also modifies the brightness of the scene making it harder to pick colors when accuracy is needed. For example matching fog color with the horizon's color takes a lot of trial and error.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a checkbox or a dropdown list to choose fog blend mode in WorldEnvironment. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No. Writing a custom shader using depth buffer is trivial but I believe this change needs to operate on an engine level to allow for materials to use the `disable_fog` flag.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by Calinou** [comment] 2024-01-01 15:00
> Besides other changes, fog is now additive. That removes de possibility of using fog with a dark color (using pure black removes the fog), which is very useful for faking darkness in unlit scenes.

I can't reproduce this on 4.2:

![image](https://github.com/godotengine/godot-proposals/assets/180032/368fe856-3c58-4a07-bdd3-ab9d855bce34)

Fog also applies to unshaded materials in 4.x, regardless of the rendering method used. You can disable fog on a per-material basis using the **Disable Fog** property in BaseMaterial3D or `shader_mode fog_disabled` in ShaderMaterial.

The fog blending formula is the same as in 3.x, it's just that fog is exponential instead of having a fixed begin/end distance: https://github.com/godotengine/godot-proposals/issues/4619

**Comment by Calinou** [comment] 2024-05-16 17:41
Closing, as this is already implemented as of 4.2.1 (possibly earlier, I don't recall the fog blend mode actually being changed).

If you need further control on fog appearance, see https://github.com/godotengine/godot-proposals/issues/8743.

**Closed by Calinou** 2024-05-16 17:41 UTC
Labels: topic:rendering, topic:3d
