### ISSUE TITLE
Focus the filter field when pressing `Ctrl + F` in the scene tree

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#7252] opened 2023-07-09 19:15 UTC
### Describe the project you are working on

prototype

### Describe the problem or limitation you are having in your project

![image](https://github.com/godotengine/godot-proposals/assets/71937306/ce340052-2d2b-4a8c-af56-ef71a5e0c278)

this `Filter Nodes` thing is cool I wish pressing `Ctrl + F` (the usual search shortcut) would give it the focus.

Current workflow:
 1. click this LineEdit
 2. type

Proposed workflow:
 1. Ctrl + F
 2. type

This works for the FileSystem's own filter thing.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

see above

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

press Ctrl + F, start typing

### If this enhancement will not be used often, can it be worked around with a few lines of script?

used often

### Is there a reason why this should be core and not an add-on in the asset library?

doesn't make sense

**Comment by Calinou** [comment] 2023-07-09 23:32
- Duplicate of https://github.com/godotengine/godot-proposals/issues/3666 (which covers this case among many others).

**Closed by Calinou** 2023-07-09 23:32 UTC
Labels: topic:editor, usability
