### ISSUE TITLE
Allow cyclic references

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-proposals#460] opened 2020-02-10 05:55 UTC
**Describe the project you are working on:**
- Networking packet system
- Celestial bodies, script hierarchy

**Describe the problem or limitation you are having in your project:**

Use Case: Packets
---
Static constructor wrappers are impossible to make due to `Parser Error: Using own name in class file is not allowed (creates a cyclic reference)`

Consider the following code

```py
extends Packet
class_name PacketPing

var message: String

static func create(message: String) -> PacketPing:
	var packet: PacketPing = PacketPing.new() # Cyclic reference
	
	packet.message = message
	
	return packet

# We may need multiple initializers that do completely different things
#static func from_bytes(bytes: PoolByteArray) -> PacketPing:
```

It is impossible to make a static packet constructor wrapper for this since PacketPing refers to itself

Use Case: Scripts in a hierarchy
---
![image](https://user-images.githubusercontent.com/14253836/74123222-988eea00-4b93-11ea-8575-ddfd9f8fa963.png)
```py
extends Node
class_name CelestialBody

var mass: float
var radius: float

# Check if we are orbiting another CelestialBody
func is_orbiting() -> bool:
	return get_parent() is CelestialBody # Cyclic reference
```

What I don't understand: Cyclic references work fine in almost every other programming language
---
<details>
  <summary>Cyclic references that work fine in 5 of the most popular programming languages</summary>

**C#**:
```csharp
public class A
{
    public static A Create()
    {
        return new A(); // This works fine!
    }
}
```
**Java**:
```java
public class A {
    public static A create() {
        return new A(); // This works fine!
    }
}
```
**C++**:
```cpp
class A {
public:
    static A create()
    {
        return A(); // This works fine!
    }
};
```
**JavaScript**:
```js
function A() {
		this.create = () => new A(); // This works fine!
}
```
**Python**:
```python
class A:
    @classmethod
    def create(cls):
        return A() # This works fine!
```
**PHP**: It should be noted that cyclic references actually do not work in PHP
</details>

---

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Cyclic references are completely valid for good code. It is needed to make named, static, wrapped constructors.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
GDScript code samples above would run without errors since cyclic references should be valid

**Describe implementation detail for your proposal (in code), if possible:**
Cyclic references cannot be implemented without changing the scripting engine

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, right now there is no good way to work around cyclic references. `is` operator can be worked around by comparing the script with `load()`

**Is there a reason why this should be core and not an add-on in the asset library?:**
This can not be worked around with an addon. Cyclic references are a core part of the scripting engine

**Comment by Calinou** [comment] 2020-02-10 08:35
Related to https://github.com/godotengine/godot/issues/21461.

**Comment by SlothDevLlama** [comment] 2020-02-11 11:51
I had the same issue yesterday.
One thing for now which can work is:

Overriding the get_class() function and use that to check if itself is of a certain type. Not sure if performance is well for this but at least I could get rid of cyclic reference warnings while keeping most of my types.

**Comment by vnen** [comment] 2020-02-13 20:58
I think this can be closed, since we will solve this anyway and there's already an issue being tracked in the main repository.

**Comment by nathanwfranke** [comment] 2020-02-13 23:04
Isn't that issue about a specific problem related to `class_name` and `is`? This proposal is general for all cyclic examples

**Comment by nathanwfranke** [comment] 2020-02-13 23:06
Closing for now, Superseded by godotengine/godot#21461

**Comment by Xrayez** [comment] 2020-02-17 23:12
Another instance of (future) cyclic references which can happen while serializing GDScript instances: godotengine/godot#33137 (currently just errors out without crashing at least). 😛

**Comment by nathanfranke** [comment] 2020-05-26 09:49
@akien-mga Re-open this since we are migrating to proposals?

**Comment by vnen** [comment] 2020-05-26 14:09
There's no need to reopen, the issue is already tracked in the main repo as a bug.

**Comment by nathanfranke** [comment] 2020-05-27 10:18
From that issue:
> Certain uses of `class_name` can produce cyclic errors in situations where there are no cyclic references

So isn't that unrelated?

**Comment by vnen** [comment] 2020-05-27 11:46
@nathanfranke the issue evolved from the initial description to cover all cases. Don't worry, what's in this proposal will also be allowed.

**Comment by Xrayez** [comment] 2020-10-27 19:21
@vnen I suggest to re-open this proposal to prevent further duplicate feature requests, see previous #595, #1629, #1737.

**Comment by nathanfranke** [comment] 2020-10-28 00:26
I agree. Why are we closing thousands of issues in the main repository for being proposals, but keeping obscure ones like godotengine/godot#21461

**Comment by cgbeutler** [comment] 2021-08-16 19:48
Question: Does this mean that prior to 4.0 I need to be careful of circular refs in C#?

**Comment by rossunger** [comment] 2022-01-28 04:32
In case this is helpful for anyone, I've been using a hacky workaround instead of the "is" or "as" keywords...
I compare get_script().get_path() against the filename of the script.
This is the only way I found to stop cyclic dependency errors.
Is there any chance that a get_script_name() function might make it's way into godot 3? 
I'm looking forward to switching to godot 4 but until then, gotta use the hacks.

**Comment by Shadowblitz16** [comment] 2022-03-25 04:33
Does 4.0 have this? If so can we get a backport to v3.4.5 along side custom resource exports?

**Comment by nathanfranke** [comment] 2022-11-18 23:14
Should be resolved as of https://github.com/godotengine/godot/pull/67714

**Closed** 2022-11-18 23:14 UTC
Labels: topic:core, topic:gdscript

**Comment by Lilith-In-Starlight** [comment] 2022-12-22 19:37
Will this be backported for 3.x?

**Comment by YuriSizov** [comment] 2022-12-22 19:54
@Lilith-In-Starlight This is not a change that can be backported. It needs to be redone completely for a 3.x branch, and that's unlikely, unfortunately.
