### ISSUE TITLE
GDScript user friendly (in-place) string interpolation

### ISSUE THREAD

**Issue by fguillen** [godotengine/godot-proposals#7522] opened 2023-08-18 10:33 UTC
### Describe the project you are working on

Any kind of project. Especially when writing `print` sentences for quick debugging. But valid to any place where string interpolation is needed.

### Describe the problem or limitation you are having in your project

The actual string interpolation implementation is cumbersome.

When writing debugging `print` sentences I find myself confused because I want to write something quick and without too much thought. At the end is a debugging code, I want it dirty and quick because it will be deleted. 

Instead I have to stop and think about the combination of characters to format my variables. Then creating an array at the end of the string with the variables themselves in the appropriate order. If latter I have to modify the string sentence I very probably will break the array variables order. It is confusing for me. And not friendly.

Many modern languages have in-place variable interpolation, which is much user friendly. I would love GDScript also to have it :)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Use any of the modern languages implementation:

- [Python](https://www.programiz.com/python-programming/string-interpolation)
- [C#](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated)
- [Ruby](http://ruby-for-beginners.rubymonstas.org/bonus/string_interpolation.html)

So instead of this:

```
print("My name is: %s and I live in %s since %d years" % [name, country, years])
```

I can write this:

```
print("My name is: %{name} and I live in %{country} since %{years} years")
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Explained above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I would love to write my self a Utils static function to do this for me. But I don't think this is possible without a proper way to send the `bind` to the function so the function can access to local variables from the caller.

### Is there a reason why this should be core and not an add-on in the asset library?

It is a very used functionality, and I don't see the way it can be done if it is not implemented in the core.

**Comment by fguillen** [comment] 2023-08-18 11:18
I think is duplicated :?

- https://github.com/godotengine/godot-proposals/issues/157

**Comment by AThousandShips** [comment] 2023-08-18 12:39
Duplicate of #157

**Closed by AThousandShips** 2023-08-18 12:39 UTC
Labels: topic:gdscript
