### ISSUE TITLE
Godot 4.0 Classic Fog officially supported extension for retro games?

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#6203] opened 2023-01-29 22:18 UTC
### Describe the project you are working on

Retro first-person 3D horror game.

### Describe the problem or limitation you are having in your project

The old fog from Godot 3.x was useful as an artistic tool, particularly for walking simulators, horror games and first-person shooters. The fog in 4.0 is designed to be much more like realistic fog and no longer has a the harsh cutoff curves to allow for creative use of fog as a retro aesthetic (not intended to be realistic at all).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A reimplementation of the old 3.x fog as an extension, specifically for the aesthetic used by retro-styled games rather than realistic modern fog as a visual effect.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I would imagine it would be the old code from the WorldEnvironment in 3.x, forked as an extension.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Maybe, but I wouldn't know where to start.

### Is there a reason why this should be core and not an add-on in the asset library?

I think it should be an officially supported extension for 4.0

**Comment by elvisish** [comment] 2023-01-29 22:19
Perhaps these could be also considered within this context:
https://github.com/godotengine/godot-proposals/issues/3429
https://github.com/godotengine/godot/pull/66030
https://github.com/godotengine/godot-proposals/issues/5079

**Comment by clayjohn** [comment] 2023-01-29 22:23
Duplicate of https://github.com/godotengine/godot-proposals/issues/4619

**Closed by clayjohn** 2023-01-29 22:23 UTC

**Comment by elvisish** [comment] 2023-01-29 22:48
> Duplicate of #4619

Well, this was specifically about supporting it as an extension.

**Comment by clayjohn** [comment] 2023-01-29 23:06
> Well, this was specifically about supporting it as an extension.

Sorry, I missed that when reading your post. 

That being said, this isn't something that can be made into an extension, you are requesting a change in the internal scene shader. Also, this is a place for making proposals for changes to the engine hence the last question ``Is there a reason why this should be core and not an add-on in the asset library?``

**Comment by elvisish** [comment] 2023-01-29 23:07
> > Well, this was specifically about supporting it as an extension.
> 
> Sorry, I missed that when reading your post.
> 
> That being said, this isn't something that can be made into an extension, you are requesting a change in the internal scene shader. Also, this is a place for making proposals for changes to the engine hence the last question `Is there a reason why this should be core and not an add-on in the asset library?`

Ah, I didn't realize proposals weren't for extensions, no problem.
