### ISSUE TITLE
Display quick documentation with code completion hints in the script editor

### ISSUE THREAD

**Issue by knadoor** [godotengine/godot-proposals#1573] opened 2020-09-26 09:21 UTC
**Describe the project you are working on:**
Experimenting with using Visual Studio Code as external editor.

**Describe the problem or limitation you are having in your project:**
Using Visual Studio Code as the auto-completion hints describe what a function does rather than just display a list of functions to choose from which is how the Godot editor behaves currently.
![current](https://user-images.githubusercontent.com/8476589/94337332-04439b80-002d-11eb-8a41-2dea993b4386.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Especially when you can't remember what a function is supposed to do, yes you can look it up in the documentation, however it would be more convenient to have the auto-completion hints text showing, similar to the godot-tools extension does in Visual Studio Code. This will make the experience of using the internal editor better.
![suggestion](https://user-images.githubusercontent.com/8476589/94337357-348b3a00-002d-11eb-9731-3c35921a27ac.png)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
For each function that appears in the auto-complete dropdown, full hints are displayed. This would be derived from the Godot documentation which is how the godot-tools is working.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No. The only alternative is to use the external editor, however the suggestion is about making the experience using the internal editor better.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is an editor enhancement.

**Comment by Calinou** [comment] 2020-09-26 15:29
Duplicate of https://github.com/godotengine/godot-proposals/issues/408.

**Closed by Calinou** 2020-09-26 15:29 UTC
Labels: topic:editor
