### ISSUE TITLE
Make it possible to replace the default Godot icon.

### ISSUE THREAD

**Issue by pajcek11** [godotengine/godot-proposals#1244] opened 2020-07-23 17:55 UTC
**Describe the project you are working on:**
Exporting a finished project to Windows

**Describe the problem or limitation you are having in your project:**
Even with the [proposed solution](https://docs.godotengine.org/en/stable/getting_started/workflow/export/changing_application_icon_for_windows.html), to which a whole wiki page is dedicated, setting an icon with rcedit is at best annoying, and at the worst it doesn't work at all. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
When the rcedit hack inevitably fails 85% of the time and on 50% of computers that I tried, then a "default" Godot icon is displayed. That means that there is some fallback icon in there. I'm sure that that one can be easily replaced by whatever icon anyone wants, and all that without having to rely on third party hack fixes that might or might not be supported in the future by the maker.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
You already have a directory navigation textbox in the export screen. Just reroute the .ico file to be the "fallback" icon instead of the Godot icon. EzPz

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It will be used by literally everyone. The rcedit bug thread is a wasteland of failed attempts to fix it and make it work. And the mere existence of the wiki link that I mentioned is proof enough that there is obviously a problem.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Icons are, like, the most "core" thing ever.

**Comment by groud** [comment] 2020-07-23 18:25
> I'm sure that that one can be easily replaced by whatever icon anyone wants, and all that without having to rely on third party hack fixes that might or might not be supported in the future by the maker.

Well, if it was so easy to do, be ensured that this problem would have been fixed a long time ago... 🙄 

With Windows, the icon needs to be added at compilation time directly in the binary, That's why it's pretty difficult to change the icon afterward. There's is no simple way to solve the problem, unless by asking user to compile the export template themselves, which would take minutes and would definitely make the user experience worse. That's why we use an external tool to change the icon on windows for now. 

An ideal solution would be to have a library able to modify the binary directly like rcedit does, but I don't think anyone found one compatible with Godot's license.

**Comment by Calinou** [comment] 2020-07-23 18:29
Duplicate of https://github.com/godotengine/godot-proposals/issues/1097 (the underlying problem is the same).

**Closed by Calinou** 2020-07-23 18:29 UTC
