### ISSUE TITLE
Add the ability to blit CanvasItems to the CanvasItem behind it

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1901] opened 2020-11-28 04:32 UTC
### Describe the project you are working on
Image Editor Plugin

### Describe the problem or limitation you are having in your project
I want to use ColorRects as canvas items to draw image layers
but I need to be able to merge them down

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add blit function to canvas item in which it draws to the canvas item's behind it with correct blending and shaders

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Basicly it would just be as simple as `blit()` with no parameters.
Blitting would blit to a image if it's a TextureRect with a ImageTexture

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It would be used for image and texture manipulation also idk

### Is there a reason why this should be core and not an add-on in the asset library?
Its allows for easily blitting to surfaces with canvas items

**Comment by clayjohn** [comment] 2020-11-28 07:13
I think the new CanvasGroup feature should solve this. https://github.com/godotengine/godot/pull/43167

You can't blit to a canvasitem per se. You can only blit to Viewports. But I think the CanvasGroup can be used to achieve the effect you are looking for.

**Comment by Shadowblitz16** [comment] 2020-11-28 20:14
well I need to be able to merge them down and keep the changes

**Comment by jonbonazza** [comment] 2020-11-29 05:34
CanvasGroup will remove the need to merge them down. It solves your actual problem but in a different way than what you proposed.

**Comment by Shadowblitz16** [comment] 2020-11-29 19:54
@jonbonazza  in what way doesn it remove the need to merge them down?
I am using them for image editing layers so I need to blit it onto the layer below and delete it

**Comment by Calinou** [comment] 2021-01-31 02:56
Duplicate of https://github.com/godotengine/godot-proposals/issues/401 (implemented by https://github.com/godotengine/godot/pull/43167).

**Closed by Calinou** 2021-01-31 02:56 UTC
Labels: topic:rendering

**Comment by Shadowblitz16** [comment] 2021-02-01 00:56
@Calinou  this is more to do with images not textures
