### ISSUE TITLE
The secret behaviour of buttons 

### ISSUE THREAD

**Issue by cloa513** [godotengine/godot-proposals#3572] opened 2021-11-19 11:52 UTC
### Describe the project you are working on

A button based Sudoku- some buttons are the numbers. Some are the controls for the game. 

### Describe the problem or limitation you are having in your project

Unexpected behaviour of created buttons. I set the background color  and font of a button by a using a Stylebox and the mouse was over it so it flickered to the default image of StyleBox_hovered I guess there is no information on Godot about what was happening. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

You have one Print line or caution into the debug which says "hover and focus signals are activated by default for button and cause a default Stylebox  for each to trigger for mouse input"

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Print ("hover and focus signals are activated by default for button and cause a default Stylebox  to happen for each to mouse triggers")

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes but it is so little programmer work to implement. 

### Is there a reason why this should be core and not an add-on in the asset library?

There shouldn't be secret behavior of functions used in gdscript.

**Comment by pycbouh** [comment] 2021-11-19 11:56
Duplicate of https://github.com/godotengine/godot-proposals/issues/3566.

**Closed by pycbouh** 2021-11-19 11:56 UTC
