### ISSUE TITLE
Remove `rect_` prefix from Control node properties (for compatibility with Node2D)

### ISSUE THREAD

**Issue by LotsaBugs** [godotengine/godot-proposals#2043] opened 2020-12-29 07:54 UTC
### Preface
This is not so much an actual proposal, but rather an invitation for discussion.
Seeing that there seems to be demand for renaming `translation` to `position` for 3D nodes for consistency with 2D nodes, I would like to point out a frustrating issue I have come across in my own projects regarding `Node2D` and `Control` nodes.

### Describe the project you are working on
(Applies to any project)

### Describe the problem or limitation you are having in your project
The fact that there exists 2 different property names between `Control` nodes `Node2D` nodes for the same thing can be a real headache.
`Control`: `rect_scale`, `rect_position`, `rect_global_position`
`Node2D`: `scale`, `position`, `global_position`

The problem arises when you are setting up your project to use (for example) `TextureRects` for displaying images, but then later decide to use `Sprite` nodes instead, to make use of the `z_index` property in `Node2Ds`. 
(adding a `z_index` property to `Control` nodes is another topic of debate)

Now all of your code that had previously been written with `rect_*` needs to be edited to remove the `rect_` prefix for the code to work. (Or vice-versa when converting from `Node2D` to `Control` nodes).
This is annoying at best.

There are workarounds, such as using the `_set_position(...)`, `get_position()`, `_set_size(...)`,  and `get_size()` etc.,  functions, which both `Control` and `Node2D` share, but this is not the first thing that comes to mind to a new user, especially because of the fact that there is no autocomplete for these setter/getter functions. The user has to copy/paste the names of these functions from the documentation to use them.

Another workaround which I've used is to create a function which checks the type of the node (`Control` or `Node2D`), and uses the relevant property name to get/set it.
But now you have a new set of functions that you have to remember to use in order to avoid this problem.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Simply remove the `rect_` prefix for properties of `Control` nodes, so that they match the names of `Node2D` nodes.
That way, the code doesn't break if you later decide to switch to using a different type of node in your scene.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
(See above)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This would be used in any project that makes heavy use of `Node2D` and `Control` nodes.

### Is there a reason why this should be core and not an add-on in the asset library?
This would be a change to the built-in property name of `Control` nodes.

### Note
There may be a good reason for why `Control` nodes use a `rect_` prefix for everything, but I'm not aware of it.
This seems like an unnecessary differentiation between `Node2D` nodes with no obvious benefit, but I would like to hear your thoughts.

**Comment by pycbouh** [comment] 2020-12-29 09:21
While Controls and Node2Ds are both CanvasItems and represent flat imagery, I don’t think that “What if you replace a Control with a Node2D” is a completely valid use case. Those are parts of two different systems and are not exactly interchangeable in practice, even if by happenstance they sometimes can replace one another.

I am not entirely against the rename however, but `rect_postion` and `rect_size` specifically make sense because there is a Rect binding the Control and Rects have those two properties. So those are named like that because they are the properties of Control’s Rect and this matches the naming scheme in Godot for inner entities of objects, Every other `rect_` property just expands on that idea.

**Comment by KoBeWi** [comment] 2020-12-30 01:19
The thing is that `rect_position` is not a "real" property. Controls operate on margins (offsets in 4.0) and this is what is serialized in the scene. `rect_position` is more like a convenience property for easier positioning of the controls, but it's not exactly the same as in Node2D. Although from user stand-point they aren't much different 🤔

**Comment by LotsaBugs** [comment] 2020-12-30 12:09
> rect_postion and rect_size specifically make sense because there is a Rect binding the Control and Rects have those two properties

> Controls operate on margins (offsets in 4.0) and this is what is serialized in the scene.

I see, thank you for the explanations.

> Those are parts of two different systems and are not exactly interchangeable in practice, even if by happenstance they sometimes can replace one another.

I'll give an example of how I encountered the `position`/`rect_position` problem.
Imagine I have a character scene set up like this:

`KinematicBody2D`
- `CollisionShape2D`
- `TextureButton`

Let's say I'm using the `TextureButton` for 2 purposes: 
1) Displaying the character's image
2) Detecting `mouse_entered`, `mouse_exited`, and `pressed` events.

This is probably not what `Control` nodes are meant to be used for, but it seems to work nicely.

Having objects be able to interact with the mouse is really useful.
Alternatively, I could give the object an `Area2D`, and also create a `Cursor` object which follows the mouse, give it an `Area2D`, and listen for a collision signal on the `Cursor` object, but using a `TextureButton` seems simpler.

Is there a reason why I shouldn't mix `Node2D` and `Control` nodes in this way?
Is it an issue of performance or something else?

**Comment by Calinou** [comment] 2022-05-15 01:02
Duplicate of https://github.com/godotengine/godot-proposals/issues/3125.

**Closed by Calinou** 2022-05-15 01:02 UTC
Labels: topic:gui
