### ISSUE TITLE
Predict projectile path

### ISSUE THREAD

**Issue by toxicrecker** [godotengine/godot-proposals#2985] opened 2021-07-12 12:07 UTC
### Describe the project you are working on

I am working on a 2d angry birds game.

### Describe the problem or limitation you are having in your project

 I want to predict bird's path trajectory before the bird is launched (something like [this](https://ibb.co/y05MKWs)). However, i still didn't achieve this and i find it very difficult to achieve as a newbie.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A function to predict path in Rigid Bodies will be really useful for this.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A function to predict path of Rigid Bodies, something like `predict_path(Vector2 launch_velocity)`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It shouldn't be easy to implement an accurate path predictor, especially a newbie like me so I doubt that it can be worked around with a few lines of script

### Is there a reason why this should be core and not an add-on in the asset library?

This is a great feature for a game engine to have, people might need it often.

**Comment by Calinou** [comment] 2021-07-12 12:08
Duplicate of https://github.com/godotengine/godot-proposals/issues/740.

**Closed by Calinou** 2021-07-12 12:08 UTC
Labels: topic:physics
