### ISSUE TITLE
Suggest snake_case script names by default to match GDScript style guide

### ISSUE THREAD

**Issue by regakakobigman** [godotengine/godot-proposals#1440] opened 2020-08-31 14:52 UTC
**Describe the project you are working on:**
N/A
**Describe the problem or limitation you are having in your project:**
When creating a new script for a node, the create node dialog will name the script after the node, which is usually in PascalCase.
![Three nodes named Main, SkeletonIK, and HTTPRequest](https://i.imgur.com/FIwZbTD.png)
![Default script name for Main is Main.gd](https://i.imgur.com/eiLjKaI.png)
![Default script name for SkeletonIK is SkeletonIK.gd](https://i.imgur.com/BifPC70.png)
![Default script name for HTTPRequest is HTTPRequest.gd](https://i.imgur.com/6GlwdI8.png)
This is OK, but it would be better to suggest snake_case script names that follow the GDScript style guide by default.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
If the suggested script names were converted from PascalCase to snake_case, they would fit the style guide, and would rarely have to be modified by users.
New default script name examples, in snake_case:
![New default script name for Main is main.gd](https://i.imgur.com/8tqgS7s.png)
![New default script name for SkeletonIK is skeleton_ik.gd](https://i.imgur.com/J7RoyVd.png)
![New default script name for HTTPRequest is http_request.gd](https://i.imgur.com/jMbXa2w.png)
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
In [`editor\script_create_dialog.cpp:108`](https://github.com/godotengine/godot/blob/2cfc5b8680bf7c1f75b02f83f7ecc26d1e49021f/editor/script_create_dialog.cpp#L108):
Change:
![](https://i.imgur.com/jhLzINH.png)
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It's easy to change the name yourself, but it would be easier for users if the default name didn't have to be changed every time you create a script.
**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a small quality of life change that makes it easier for users to follow the style guide.

**Comment by Calinou** [comment] 2020-08-31 14:54
Duplicate of https://github.com/godotengine/godot-proposals/issues/1211.

**Closed by Calinou** 2020-08-31 14:54 UTC
