### ISSUE TITLE
Add get_main_screen_editor() to EditorInterface

### ISSUE THREAD

**Issue by thecaptaincarrot** [godotengine/godot-proposals#2943] opened 2021-07-01 04:12 UTC
### Describe the project you are working on
Creating a map editor plugin for a Metroidvania which involves a new Main Screen editor Control and a new dock which is only relevant when the new Main Screen is opened and focused

### Describe the problem or limitation you are having in your project
When any other editor is focused, the plugin dock is not only not relevant, but should be hidden to prevent misclicks that may have unforeseen and unintended consequences.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Literally it's just a get function for the current open main screen.  returns "2D", "3D", "Script", "AssetLib", or the string name of any additional main screens added through plugins

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
tool
extends EditorInterface

func get_main_screen_editor():
    return main_sceen_editor
    #returns a string with the name of the focused editor

### If this enhancement will not be used often, can it be worked around with a few lines of script?
As far as I can tell, there is no easy work around.  If there is, I'd love to hear about it.

### Is there a reason why this should be core and not an add-on in the asset library?
This seems like such a basic function when there's already a setter, I was convinced I was just stupid for not being able to find it.

**Comment by pycbouh** [comment] 2021-07-01 10:08
> As far as I can tell, there is no easy work around. If there is, I'd love to hear about it.

If you only need to know when it changes, there is a signal already, `main_screen_changed` on the `EditorPlugin`.

```gdscript
func _enter_tree() -> void:
	connect("main_screen_changed", self, "_on_main_screen_changed")

func _on_main_screen_changed(main_screen: String) -> void:
	# Do something.
```

Getting the initial value is [a fair bit trickier](https://github.com/pycbouh/godot-time-tracker/blob/master/addons/time-tracker/plugin.gd#L76-L118). This code needs to be called in your plugin's `_enter_tree` (when activated as the editor is already running) as well as on `ready` of the editor's base GUI control (when activated by default with the editor starting up):

```gdscript
	# Try to find controls immediately (it will fail if not ready yet).
	_on_editor_base_ready()

	# Also connect to the ready signal, so that it is correctly detected then.
	var editor_base = get_editor_interface().get_base_control()
	editor_base.connect("ready", self, "_on_editor_base_ready")
```

-----
That said, this is a duplicate of #2081.

**Closed by pycbouh** 2021-07-01 10:08 UTC
Labels: topic:editor, topic:plugin

**Comment by kzTCP** [comment] 2025-07-15 17:04
Once you press any button, its name must show up in the console. `Godot 3.x`
```

var _main_screen_editor: String = ""
# changes when you select a scene or script in a scene
func _on_main_screen_editor_btn_toggled(button_pressed: bool, btn_name: String):
	if not button_pressed: return 
	_main_screen_editor = btn_name
	print("name: ", btn_name)
	

func get_main_screen_editor() -> String: 
	return _main_screen_editor


func _listen_to_main_screen_editor():
	
	var base = interface.get_base_control()

	var sub_base: VBoxContainer
	# get fist VBoxContainer
	for node in  base.get_children():
		if node is VBoxContainer:
			sub_base = node
			break;	

	var top_bar: HBoxContainer = sub_base.get_children()[0]

	var center_container: HBoxContainer = top_bar.get_children()[2]
	
	for b in center_container.get_children():
		
		var btn = b as ToolButton
		
		btn.connect(
			"toggled", self, "_on_main_screen_editor_btn_toggled", [btn.name]
		)


func _enter_tree():

	_listen_to_main_screen_editor()

```
