### ISSUE TITLE
Drag Shape faces into place individually, without the opposite face also moving

### ISSUE THREAD

**Issue by AhNesh** [godotengine/godot-proposals#3345] opened 2021-09-24 16:59 UTC
### Describe the project you are working on

A 3D game that uses areas to trigger events.

### Describe the problem or limitation you are having in your project

Its difficult to place an `Area` and size its `CollisionShape`'s `Shape` to fill the space I want. I have to find the middle of the where I want the `Area`, then change the shapes extents to fill the area. This is because changing the size of the `Shape` extends it in both directions.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

What if in the scene you could drag the `Shape`'s faces (or vertices) and that face "changes position"? So essentially, you drag the one face to where you want it, then you drag the opposite face to where you want it. To fill an enclosed room with an `Area` would be to drag each face to each wall, the floor, and the ceiling.

I have not worked with 2D, but I assume `Shapes` do the same there, and that this would be useful in 2D as well.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

On `BoxShape`, you currently can drag 3 of the faces, which changes it's extents. Instead you could drag all faces, which would change the extent and move the parent node accordingly.

Here I have an `Area` with a `BoxShape`:
![image](https://user-images.githubusercontent.com/33862238/134710971-77aff6f0-606e-4e97-992a-324a8437eaa5.png)

Here I have dragged the far right face to increase the shapes size. Its still touching the box.
![image](https://user-images.githubusercontent.com/33862238/134711176-e4c9b346-3001-4f7a-a0b6-4da2b98f3cfb.png)

What actually happened is that I increased the Z extent by 1 and increased the `Area` Z transform by 1.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think it can be worked around with script because you need to be able to grab and drag the faces of the `Shape`.

### Is there a reason why this should be core and not an add-on in the asset library?

I think this would improve the workflow of working with `Area`s (and just `Shape`s in general) for everyone.

**Comment by Calinou** [comment] 2021-09-24 18:07
Duplicate of https://github.com/godotengine/godot-proposals/issues/452.

**Closed by Calinou** 2021-09-24 18:07 UTC
