### ISSUE TITLE
Add Bezier to line 2D

### ISSUE THREAD

**Issue by TheConceptBoy** [godotengine/godot-proposals#5905] opened 2022-12-06 17:04 UTC
### Describe the project you are working on

Project that uses Line 2D as decorative cables.

### Describe the problem or limitation you are having in your project

To create smooth curves, I need to manually paint all the subdivisions to create a convincing curve.

https://user-images.githubusercontent.com/52581279/205976089-c99658bc-1321-455a-a613-4fe7e5c82f9f.mp4

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

adding bezier curve handles to Line2D much like the Path2d offers with the same flexibilities like doing mirrored, inverted or free handles.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I suppose looking at Path2D will how necessary code.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Seems like for drawing lines, it'd be pretty essential.

### Is there a reason why this should be core and not an add-on in the asset library?

Line2D is already core

**Comment by Calinou** [comment] 2022-12-06 17:12
Duplicate of https://github.com/godotengine/godot-proposals/issues/1106.

**Closed by Calinou** 2022-12-06 17:12 UTC
