### ISSUE TITLE
Add gizmo-free object manipulation (like in Blender)

### ISSUE THREAD

**Issue by ScribbleFen** [godotengine/godot-proposals#1927] opened 2020-12-02 21:03 UTC
### Describe the project you are working on
Pet-raising/-breeding sim like Chao Garden, 3d shoot-em-up like Defender (2002), fantasy-based terrain-editing and resource gathering game like Deep Rock Galactic--this applies to any of the projects I want to work on in Godot, really

### Describe the problem or limitation you are having in your project
Coming from blender, gizmos are cumbersome and inconvenient for manipulating an object.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Manipulating objects with keyboard shortcuts and typing instead of clicking on and dragging gizmos is faster and more streamlined, and also makes for an easier transition for Blender users.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Originally requested in 2016 with issue https://github.com/godotengine/godot/issues/3995 I also did a bit of prototyping it in at https://github.com/ScribbleFen/godot/tree/blender-like-transform-2 
For anyone who's not familiar with Blender and would like to read my own description of it:

To transform an object (or group of objects) rather than messing with gizmos, you just make your selection then hit one of the transform keys:
g - grab (move, translate)
r - rotate
s - scale
then move the mouse around as you would, and finally hit enter or left-click to confirm the change (or Esc or right-click to cancel). And if you change your mind, changing the transform type is also just one keypress away--just hit the relevant key and the transform type will change, and it will even transfer the mouse movement over as well (so if you hit g, move the object 5 units, but then you hit s, the position will be reset so instead of having it be moved by 5 units, it will be scaled by 5 units). You can also lock the transformation to any axis (by pressing x, y, or z) or plane (by pressing alt + whichever axis is perpendicular). 

There's also the additional functionality of being able to type in values by which to modify something, so if you know you want to move something -5 units along the x axis, you can just click the object, press x, then type -5, and it will move it to -5 x (relative to its initial position before you started transforming) instead of setting its position based on your mouse movement (and you can backspace to delete the value you typed in if you want to go back to moving it with the mouse). I find this useful as well, but it isn't _as_ important, and it also might be a bit more difficult to add in.

Examples:

The user presses (in order) and actions occur:

    G, X, 5, Enter - the noded selected is translated in axis X by +5 units;
    R, Y, -90, Enter - the node is rotated along Y axis 90 degress counterclockwise;
    S, Alt+Z, 2, Enter - the node is scaled by 200% in axis X and Y (all but Z).

This is mainly for 3d object manipulation, but can also apply to 2d object manipulation, or even shader or visual script graph node manipulation--basically anything where you need to move something around, instead of holding down the mouse button to move something around, you just press a key and start moving your selection around with the mouse.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not sure how you'd add this functionality in outside of core editing.

### Is there a reason why this should be core and not an add-on in the asset library?
It seems to me like a relatively small and simple change to the core, it would gave a major boost to UX and is applicable to virtually every kind of project, and I don't know if it would be as simple to try and override the default object manipulation functionality from outside the core programming.

**Comment by Calinou** [comment] 2020-12-02 22:52
Duplicate of https://github.com/godotengine/godot-proposals/issues/1215.

**Closed by Calinou** 2020-12-02 22:52 UTC
