### ISSUE TITLE
Add a `Node.node_added` signal/method to detect the addition of children and subchildren nodes

### ISSUE THREAD

**Issue by ghsoares** [godotengine/godot-proposals#2544] opened 2021-04-02 00:42 UTC
### Describe the project you are working on
A project based of components added to a node

### Describe the problem or limitation you are having in your project
In my project, a custom node can have multiple components that describes it's behaviour, each component can be added as the direct child or subchild of this node. I need a way to easily tell this node that a child or subchild node was added, even if not inside tree yet, something that `SceneTree.node_added` cannot do.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The easiest way I could think to tell the node that a direct/indirect child node was added, was to use some signal or virtual method. Something like `Node.node_added(node: Node, parent: Node)`. This could be the same to when a direct/indirect child node was removed, something like `Node.node_removed(node: Node, prevParent: Node)`, the second parameter of the signal/method would be the previous parent of the removed node. It's more interesting to be a virtual method, so it could be called even when is not added to the tree yet.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Let's say that I have this tree:
![image](https://user-images.githubusercontent.com/43936806/113367302-036c2900-9332-11eb-9955-37648608111d.png)
And in some point, a node called Node6 is added to Node5, and I want to tell the Node1 that this new node was added, then from SceneTree would call a notification, signal or method to tell the parents and grandparents that this node was added. The same would be if this node was removed from the tree.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I'm not sure if there's a better way to do this, but it would be a nice addition to the engine IMO.

### Is there a reason why this should be core and not an add-on in the asset library?
Because it requires to modify the core structure of a Node, to be able to add this behaviour.

**Comment by Calinou** [comment] 2021-04-02 13:00
Duplicate of https://github.com/godotengine/godot-proposals/issues/627?

**Comment by ghsoares** [comment] 2021-04-02 15:26
@Calinou It's not duplicate, this issue talks about the node of a group is added in the tree, my proposal talks about the node that is added to another node as child/subchild, the use cases from this proposal and mine are different.

**Comment by Xrayez** [comment] 2021-04-02 23:24
Closely related to #724 (*this* proposal suggests adding a method as an alternative), but could be considered a duplicate for organization purposes. The use cases seem to be different, though.

> It's more interesting to be a virtual method, so it could be called even when is not added to the tree yet.

See my proposed solution to this (and current workaround): godotengine/godot#43729.

**Comment by Shadowblitz16** [comment] 2021-07-03 00:13
C# can't override add_child or remove_child and I would like to use a signal like this for laying out children in a grid.

**Comment by cloewen8** [comment] 2021-11-08 04:10
I have a use case for this. I'm working on an inventory system. It works by having items directly parented to it. When an item is "picked up" I need to invoke a method in the item. My current workaround is to call this method manually. It would be great to have the inventory do this automatically using `node_added`, so I know it is always called.

**Closed** 2022-02-04 09:13 UTC
Labels: topic:core
