### ISSUE TITLE
Add a snapping grid to TileMap polygon editors

### ISSUE THREAD

**Issue by ygypt** [godotengine/godot-proposals#6287] opened 2023-02-14 19:21 UTC
### Describe the project you are working on

2D Platformer

### Describe the problem or limitation you are having in your project

When creating a physics layer for a tilemap with a high resolution, for instance 512x512, you are left to tediously zooming in and lining up each pixel with no guidelines, no pixel position counter, and no grid snapping. this results in very choppy and inconsistent movement if you don't line up the collision boxes the the exact pixel.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A custom snapping size that allows any width and height to be used regardless of resolution. For instance snapping to the nearest 64 pixels on a 512 grid (effectively an 8x8 grid).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just as it does in the canvas editor, a button to turn snapping on and off, and two fields to enter grid snapping values for X and Y

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It improves the out-of-the-box experience of TileMaps. It is a very intuitive and expected behavior and I am surprised that it doesn't yet exist

**Comment by dalexeev** [comment] 2023-02-14 19:40
Duplicate of #5847.

**Closed** 2023-02-14 19:41 UTC
Labels: topic:editor, topic:2d, usability
