### ISSUE TITLE
Improve sub-resource inspector (use same as at root-level)

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot-proposals#1873] opened 2020-11-23 10:40 UTC
**Describe the project you are working on:**
Data-reliant game (skills, items etc)

**Describe the problem or limitation you are having in your project:**
Assigning resources to resources displays a different inspector to what is shown when the resource is at root level. This makes it impossible to assign scripts or collapse the unecessarily by-default-expanded 'Resource' section.

![grafik](https://user-images.githubusercontent.com/8841352/99952648-41ec4880-2d80-11eb-90e7-28f1b2353bb1.png)

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Having the same inspector for subresources would allow collapsing the 'Resource' section and assign scripts, which is necessary currently to work around the inability to export custom resource types in c#.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Every sub-resource can be created as its own root-resource, but that unecessarily clutters the project with files that are mostly only being used in one place anyway. 
But maybe it can be fixed with a few lines of script instead.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It should be default as it improves working with subresources for anyone using them.

**Comment by Calinou** [comment] 2020-11-23 13:10
Folding was probably disabled in subresources by default to avoid confusion over what will be folded when you click.

**Comment by Flavelius** [comment] 2020-11-23 14:34
I can see the folding problem in godot's case, it's usually what indentation solves though.
In unity it's pretty readable and they solve it only via indenting and foldouts, but anything that makes it more useful in godot is welcome.

**Comment by Calinou** [comment] 2020-11-23 14:45
@Flavelius We can't indent subresources too much due to the limited width of the inspector. Otherwise, property names will be cut early, making them difficult to distinguish from each other.

**Comment by Flavelius** [comment] 2020-11-23 15:16
As for the cutting off: I personally can't imagine a case where more than 3 layers deep nesting of custom resources (that are not external) would be somewhere near common/managable, so in my mind this is a somewhat non-issue. And, the case where labels are cut off must be considered anyway (as they could have been even at root level). 
The good thing is that godot already solves this by providing the full description of properties on mouseover.
Additionally the inspector panel is resizable to also accommodate for that.
While the first point is based on assumptions, i think the value of using indentation to distinguish them is high, as it also follows a common pattern of visually communicating nesting.
Taking this as base i think atleast can allow the option of also nesting the full inspector, where improvements of one also implicitly benefit the other, instead of having to maintain separate configurations.
An example of this is the Odin inspector extension for unity which is considered a huge usability improvement (it allows nesting of full inspectors; even opening them as separate popout).
I don't have alot of insight into the internals though, it's just something i would appreciate to see as a user.

**Comment by Serenitor** [comment] 2020-11-25 00:37
I utilize nested resources as well and find myself frequently being confused by the non-fold-able Resource section of sub-resources. When you have lots of sub-resources, these sections can take up a lot of the space and I've hardly ever had to use them. Visual communicating of sub-resources is due for improvement.

**Comment by Calinou** [comment] 2020-12-02 17:08
I just noticed there's an open bug report about this: https://github.com/godotengine/godot/issues/23759

I'm still not 100% sure if this is a bug or intended behavior, but I'll close this in favor of the bug report.

**Closed by Calinou** 2020-12-02 17:08 UTC
Labels: topic:editor
