### ISSUE TITLE
Feature: Preset scenes(+script) that can be instanced in your game like the many node functionalities you have

### ISSUE THREAD

**Issue by Manlibhar** [godotengine/godot-proposals#2552] opened 2021-04-05 12:51 UTC
### Describe the project you are working on
I am working on a top-down RPG with turn-based combat

### Describe the problem or limitation you are having in your project
Slow to build a prototype or minimum viable product, must follow and adapt many youtube tutorials from the ground up.

### Describe the feature/enhancement and how it helps to overcome the problem or limitation
Just like you have templates and demos, if you had a community-driven library of self-contained functioning scenes that can be instanced into your current scene, this would allow beginners to quickly make prototypes of what they are envisioning as well as allowing experts to share and benefit from other's contributions.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
A third button: pre-made community scenes:
![image](https://user-images.githubusercontent.com/50682411/113574660-71f00600-9614-11eb-98d5-943a709174c4.png)

You click it: which leads to a list of premade scenes that you can drag and drop to build a prototype in mins to play around with and understand.
![image](https://user-images.githubusercontent.com/50682411/113574934-02c6e180-9615-11eb-8f09-8043b6551064.png)

Ideally, it would have categories like players, enemies, environment, projectiles etc.
You have premade nodes, so why not premade scenes? It's the next logical step up and benefits everyone.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I think this feature could add a lot of value, the problem with templates is they make mixing and matching a pain. I want the enemy of this demo, not the whole project. 

### Is there a reason why this should be core and not an add-on in the asset library?
Everyone is a beginner when they use Godot, templates let them try other's projects. premade scene instances help them build their game at the scene level.

**Comment by pycbouh** [comment] 2021-04-05 13:05
Duplicate of #2320. See the discussion there, but note that this is highly unlikely to be implemented in this way. Use AssetLib instead.

**Closed by pycbouh** 2021-04-05 13:05 UTC
