### ISSUE TITLE
Suggestion to add a simple 'audio' generator, for very simple effects . . 

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#4359] opened 2022-04-07 03:34 UTC
### Describe the project you are working on

A 2.5D game, with barbarians . .

### Describe the problem or limitation you are having in your project

I have been thinking about the new noise system, that is imo. a nice addition, got to thinking, maybe there could be a place, for a simple audio effect generator, mostly procedural . . It's about the balance, between the engine well not being a creative software, but, also what then could be added, within those lines . . .

For many users, learning to use audio programs can be difficult, then again, Godot is not supposed to do that . . However, after looking at the new noise procedural system, got to thinking, is there anything, at all, that makes sense, to add, and, I'd say two things . . 1. A very simple audio generator system, and, perhaps a post-proc system, from what I know, Godot is already getting a really good post - proc system, and, that is mostly done . .

However, one thing, theoretically, one could add, was a VERY simple audio generator, or very simple chip, perhaps very low complexity sample system, the idea is, to make something very simple, and user - friendly, not to add something, that basically belongs in other programs . . Why, bec. making audio is very difficult, and, helping the users make it, would add to the engine, here's an example of how simple I'm thinking, perhaps, even more . . 

This is, sort-of too much, or so . .

![image](https://user-images.githubusercontent.com/83387915/162112853-ba2bccd6-e92f-4288-91c4-a32fabf129b6.png)

Or, notice the one, in the middle, with some simple buttons, I know this is a bad example . .

![image](https://user-images.githubusercontent.com/83387915/162112963-c9a1fe35-408b-4cda-b495-ba4f09d482f4.png)

Here's the one I was thinking, bit simpler . .

![image](https://user-images.githubusercontent.com/83387915/162113043-27db2e59-d4d7-4773-812d-1296c9a40383.png)

WHY add this, the point is, to make it simpler to make simple effects, or, very basic audio, or so . . This would save new users time, adding at least SOME sound to a game, and, make it more accessible to add very simple audio, or, effects . .

Then, to think about, if something like this could be in the engine, at all, I'd add something like a simple keyboard, piano, and, allow users to make low - density tracks, again, not really going into what other programs do, etc . .

The idea is to make it a. simple, and, b. user-friendly . . To allow new users, to quickly, also simply, to add some basic sound, and, that's it . .

Again, this is prob. too many keys, can't find a good example, but, something like this, but simpler . .

![image](https://user-images.githubusercontent.com/83387915/162113644-37797945-8d5b-42a4-83d4-2565dfc0f75c.png)

I think it makes sense, in the idea, having a very simple audio generator, or so . . Would help new users add SOME sound, also, get an understanding of how audio works, and, giving them a perhaps boost, or, at least help . . Also, so moving to bigger audio - programs make sense, and, new users can just quickly make some sound, or effects . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, adding a very simple audio engine, or effects 'generator' . . That way, totally new users could add stuff, perhaps to their first jam titles, and, there'd be 'something', or, audio . . Beyond a very simple piano, some simple sounds, and, a way to have say 4 tracks, or maybe 8, and, support for very low sized samples, it's something I guess for other programs . . .

So, the idea is to have something, so one can make very simple sounds, and, it should be focused, on user-friendliness, not complexity, also, fast to add, so on . . .

Closest thing, I can think of, is a simple SEGA / Nintendo sound, maybe with some settings, very user-friendly, as well, as intuitive . . It won't generate very 'good' audio, or effects, just allow new users to add something, without having to learn other programs, and, help them learn audio, sort-of how it works in Godot, and, VERY basic stuff, etc . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just got to thinking, after the new noise texture system, that one could also add a very simple audio generator, where the goal is to help new users, or perhaps more experienced users, to just add 'something', very simple, also teach them audio, in the most basic way, and, help them learn how audio works, in Godot ? . . 

An example, of the quality I'm thinking about . .

Again, this is too complex . .

https://www.youtube.com/watch?v=TKz9reRwbD4

Imagine, if new users could make SOMETHING like that, or effects, in their first jam projects . .

The perhaps question is, how much should be made in Godot, and, what should be made in other programs . . The idea, is user-friendly, and, fast . . So, perhaps new users can just make their first few projects, and, then have SOMETHING, after that, it's for other programs, so maybe something like 8 - 16 preset sounds, a 20 - 30 key keyboard, and, a simple tracker, where one can add notes, maybe 4 tracks . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not really, it'd also give Godot an 'official' sound, though, it'd be so simple, also, bec. it'd be VERY user-friendly, it would prob. not be used for much, except beginners, that can't make audio, or, perhaps advanced users, that just want some quick sounds, or, prototype effects . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it's just an idea, and, it'd be funny if Godot had it's own sort-of 'sound', like say SEGA, arcade stuff, Nintendo . .

The idea is just to make it simple, also accessible . . After that, one needs other programs, but, one could add that, and, it'd help new users, also more experienced users, to make perhaps prototype sounds, or, quick effects, etc . . .

**Comment by fire-forge** [comment] 2022-04-07 07:02
There is an addon called [GodotSFXR](https://godotengine.org/asset-library/asset/1195) that adds sound effect generators. I haven't used the addon myself, but I saw a video of it from GameFromScratch on YouTube and it looks pretty good for retro sound effects.

**Comment by charlesmlamb** [comment] 2022-04-07 07:49
Thanks, also, been thinking, so many people make amazing additions, to the engine, saw new noisetexture, gonna stop making suggestions for some time, and, just see what other people do, and, needless to say, download the latest version, so, gonna take a break, everything looks better, than I hoped, for Godot 4, etc . .

10 / 10 :-)) . .

**Comment by Calinou** [comment] 2022-04-07 17:13
Duplicate of https://github.com/godotengine/godot-proposals/issues/3394.

**Closed by Calinou** 2022-04-07 17:13 UTC
