### ISSUE TITLE
Change the layout of the editor and expand the functionality of the bottom contextual panel.

### ISSUE THREAD

**Issue by SilencedPerson** [godotengine/godot-proposals#2853] opened 2021-06-11 16:05 UTC
### Describe the project you are working on
irrelevant to the proposal

### Describe the problem or limitation you are having in your project
The Scene Tree Panel and filesystem menu are both too small but there is not enough space for them to be in one column, when put side by side they take up too much screen space from the 2D/3D editor/ script editor and the filesystem is the least used part of the editor until it suddenly isn't when the user starts doing level design or some other drag and drop heavy task. On top of that, bottom context panel sometimes feels too cramped.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The bottom contextual panel should house the filesystem which would significantly free up space for the scene tree and other parts of the engine.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
(Please ignore the different theme for now, that is not part of this proposal)

The bottom contextual panel would be removed from the space between left and right docks and under the 2D/3D editor and instead overlaid on top. User would have ability to resize it to their liking. The filesystem could also be minimized with keyboard shortcut CTRL+SPACE for example.
![image](https://user-images.githubusercontent.com/82024211/121711869-58b77a00-cadb-11eb-880d-e7acf35f5141.png)
![image](https://user-images.githubusercontent.com/82024211/121711887-5e14c480-cadb-11eb-830c-e4e844ef5d8e.png)
![image](https://user-images.githubusercontent.com/82024211/121713838-8ef5f900-cadd-11eb-8af3-28fa01075d72.png)

This was sorta stolen from UE5.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
This proposal cover the UI and UX of the editor, as far as i know, this cannot be done with plugin.

**Comment by Calinou** [comment] 2021-06-11 16:17
Duplicate of https://github.com/godotengine/godot-proposals/issues/1508.

**Closed by Calinou** 2021-06-11 16:17 UTC
Labels: topic:editor
