### ISSUE TITLE
Add the ability to drag and drop text in the script editor with the mouse

### ISSUE THREAD

**Issue by Looky1173** [godotengine/godot-proposals#3488] opened 2021-10-31 08:34 UTC
### Describe the project you are working on

This feature is not tied to a particular/specific use case of the Godot engine as it would benefit all users who make use of the built-in script editor.

### Describe the problem or limitation you are having in your project

To rearrange text in the script editor one has to select it, copy it, move the cursor to the desired location, and finally paste it. This can become quite cumbersome to do especially for people who are limited to (primarely) using one hand to navigate the editor/engine.

> Plus there are users, like me, who only have 1 fully working hand, so we try and minimize the need to swap between mouse and keyboard as doing that is slow.

The quote above is from [this proposal](https://github.com/godotengine/godot/issues/17881) that has been closed as this repository became the centralized way to propose Godot features/enhancements, and hasn't been reopened since. This shows that this problem concerns accessibility too and should be seriously considered.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

To overcome the problem above, a feature that allows users to select, drag, and drop text withing the editor should be added. It is a standard feature present in most text editors therefore it would benefit all users. Furthermore, such a feature would enhance the core experience of the built-in script editor and would make the Godot engine more accessible.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here is a GIF from the [original closed issue](https://github.com/godotengine/godot/issues/17881) that demonstrates this feature:
![peek 2018-03-31 09-19](https://user-images.githubusercontent.com/5276727/38160342-d4118fc0-34c4-11e8-8ce8-a203d5ecd494.gif)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This would be a core feature of the Godot engine and, as far as I'm aware, cannot be worked arround. Besides, it most likely would be used on a regular basis by the majority of users who use the built-in script editor.

### Is there a reason why this should be core and not an add-on in the asset library?

This feature is about improving the usability and accessibility of the built-in script editor, thus it should be core.

**Comment by Calinou** [comment] 2021-10-31 14:04
Duplicate of https://github.com/godotengine/godot-proposals/issues/176.

**Comment by Looky1173** [comment] 2021-10-31 15:28
@Calinou With all due respect, I believe this is not a duplicate of the linked issue, That proposal is asking for the implementation of a signal that would fire off when text/media is dragged into an input node. It has nothing to do with the built-in script editor and is quite ambigous. Therefore, I think this issue should be reopened.

**Comment by Calinou** [comment] 2022-01-11 19:07
This was implemented in `master` by https://github.com/godotengine/godot/pull/55294, closing. (This can't be easily backported to `3.x` without a complete rewrite of the feature.)

**Closed by Calinou** 2022-01-11 19:07 UTC
Labels: topic:editor, topic:gui

**Comment by ConteZero** [comment] 2022-02-05 19:03
> This was implemented in `master` by [godotengine/godot#55294](https://github.com/godotengine/godot/pull/55294), closing. (This can't be easily backported to `3.x` without a complete rewrite of the feature.)

A backport to 3.x is available in this pull request
https://github.com/godotengine/godot/pull/55355
