### ISSUE TITLE
Add Ambient Energy to SDFGI

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#4916] opened 2022-07-19 06:06 UTC
### Describe the project you are working on

Night

### Describe the problem or limitation you are having in your project

SDFGI goes full on pitch black which is undesirable.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding Ambient Energy, separate from the Sky reads it's doing, to allow for adding a minimum amount of light that will illuminate objects even when there is little to no GI light, to avoid having a fully pitch black screen in poorly lit areas

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a new settings to SDFGI:
1) Ambient Color (What color for the energy added to be, default White)
2) Ambient Energy (How much to add, 0 results in current behavior, default probably 0.05, to avoid ever having GI be pitch black)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, attempts to use other methods to give a minimum amount of light such as Reflection Probes failed (SDFGI just got overriden by them)

### Is there a reason why this should be core and not an add-on in the asset library?

SDFGI is core, and this problem is with it

**Comment by Calinou** [comment] 2022-07-19 16:25
Duplicate of https://github.com/godotengine/godot/issues/55104.

**Closed by Calinou** 2022-07-19 16:25 UTC
Labels: topic:rendering, topic:3d
