### ISSUE TITLE
Add a Vector2/3/4 constructor that takes a single scalar value

### ISSUE THREAD

**Issue by D0V4HKIIN** [godotengine/godot-proposals#11248] opened 2024-11-28 08:13 UTC
### Describe the project you are working on

A large procedurally generated world. (quite unrelevant to the feature)

### Describe the problem or limitation you are having in your project

writing Vector3(0, 0, 0,) is cumbersome

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A constructor that takes a single argument.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
var v1 = Vector3(sqrt(2))
# equivalent
var s = sqrt(2)
var v2 = Vector3(s,s,s)
# or
var v3 = Vector3.ONE * sqrt(2)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around by writing a function that takes a single argument and returns a vector initialized with that value

```
func vector(a: float):
    return Vector3(a, a, a)
```

But again, this is cumbersome

### Is there a reason why this should be core and not an add-on in the asset library?

Making this an add-on totally would make this more cumbersome. Also i don't see any reason why it shouldn't be core.

**Comment by AThousandShips** [comment] 2024-11-28 09:29
See also:
* https://github.com/godotengine/godot-proposals/issues/4822

**Comment by KoBeWi** [comment] 2024-11-28 11:16
> writing Vector3(0, 0, 0,) is cumbersome

That's just `Vector3()` though.

**Comment by D0V4HKIIN** [comment] 2024-11-28 12:34
> > writing Vector3(0, 0, 0,) is cumbersome
> 
> That's just `Vector3()` though.

seems like i over simplified my example, `Vector3(someVariable, someVariable, someVariable)` is cumbersome and `Vector3.ONE * someVariable` is weird

**Comment by D0V4HKIIN** [comment] 2024-11-28 12:37
i have updated the original post for a better example

**Comment by Mickeon** [comment] 2024-11-28 19:45
Isn't this proposal a duplicate of https://github.com/godotengine/godot-proposals/issues/3884? Should it not be consolidated?

**Comment by Calinou** [comment] 2024-11-28 21:51
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/3884.

**Closed by Calinou** 2024-11-28 21:51 UTC
Labels: topic:gdscript
