### ISSUE TITLE
I would like to being able to set a default path for scripts and scenes

### ISSUE THREAD

**Issue by Axeltherabbit** [godotengine/godot-proposals#876] opened 2020-05-23 13:25 UTC
**Describe the problem or limitation you are having in your project:**
Every time I create a new script or scene I have to manually set the path of the file otherwise it's written on "res://",I often forget about it and I have to move the files around.
I usually like to organize my project with many folders an I like my scripts and scenes in separated folders like "res://scripts" and "res://scenes"

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it's a basic feature that would not change the engine but improve the UI

**Comment by KoBeWi** [comment] 2020-05-23 22:06
Why not just create scripts/scenes from filesystem dock? You have easy access to all directories there.

**Comment by Calinou** [comment] 2020-05-23 22:07
Duplicate of #576.

**Closed by Calinou** 2020-05-23 22:07 UTC
Labels: topic:editor

**Comment by Zireael07** [comment] 2020-05-24 08:44
Note that the older issue is only about scenes, this is about scripts, too.
