### ISSUE TITLE
Allow Use of HTML and CSS for UI/UX design

### ISSUE THREAD

**Issue by IoneGod** [godotengine/godot-proposals#2211] opened 2021-01-31 16:53 UTC
### Describe the project you are working on
Just thinking about Godot UI

### Describe the problem or limitation you are having in your project
The Godot UI is fairly new and still going through lots of changes and can sometimes be buggy or just hard to use and also requires a lot of tweaking sometimes

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I think Html and Css should be added or other fairly old stable means of UI design. Also the use of html and Css solves the problems of having to tweak a lot because there is a lot of documentation, you would mostly be doing what someone has done. And also there would be a better way of handling responsiveness.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There would be something like an **_`HtmlContainer`_** node that has a path to some html file. The html file could then link to some css file too. Sincerely I haven't thought about the scripting because I don't know if `Gdscript` or `C#` can be used with Html and Css. But I think it would be okay if each clickable Html element was linked to like a specific Gdscript or C# function which it then calls when clicked or hovered or some other event something like 

 ```html
<script src="myscripts.gd"></script>
<script src="myscripts.cs"></script>
<button type="button" onclick="clicked">Click Me!</button
```
Inside myscripts.gd ->
```gdscript
func clicked():
  print("Clicked")
```
I didn't also think about limitations for people who use bootstrap. But I think it should be fine.
I haven't thought about dynamic rendering but there is always `jinja` for things like that.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I am not sure if there is a simple work around but I made a few google searches to be somewhat sure there wasn't already a work around. Either way I think it would be used often.

### Is there a reason why this should be core and not an add-on in the asset library?
I don't think it can be an add-on, well the powers of Godot never cease to amaze me.

**Comment by pycbouh** [comment] 2021-01-31 17:00
See also #305, #812 and some other proposals and issues.

There are currently no plans to support such behavior, because there is very little benefit in it, apart from superficial familiarity. Godot's UI system is powerful as it is, but it does take getting used to to be able to utilize its power. But this is not a unique situation for this type of software and trying to apply a system designed for something else is not a good idea.

There are some pet projects by community members trying to merge HTML/CSS/box and flex model into Godot UI system, but there is nothing production ready yet. That said, this can totally be an addon if someone strongly desires to use HTML and CSS. But learning Godot would be a better choice in the end.

**Comment by IoneGod** [comment] 2021-01-31 17:09
I totally agree that the Godot UI system is powerful. Notwithstanding I saw something related to this in Unity last year by Brackeys, But this used xml instead of html. I think it was in the asset store. Like I said I haven't thought about the limitations I just think html and css is more mature and adds some extra powers and gives room to people who just want to write text based UI. And also some level of responsiveness which is possible in Godot but a tardy bit harder to achieve than in the Html-Css context

**Comment by IoneGod** [comment] 2021-01-31 17:13
I also agree it should be an add-on though. But it requires some kind of merging with gdscript to work. Either way the Godot community knows best. I am just happy to be contributing in some way.

**Comment by Calinou** [comment] 2021-01-31 17:22
Duplicate of https://github.com/godotengine/godot-proposals/issues/960.

**Closed by Calinou** 2021-01-31 17:22 UTC
Labels: topic:gui

**Comment by pycbouh** [comment] 2021-01-31 17:26
> Like I said I haven't thought about the limitations I just think html and css is more mature and adds some extra powers and gives room to people who just want to write text based UI.

Keep in mind that this maturity comes from rendering engines being very advanced and clever, after years of development and with tons of hacks and tricks. And for us to have a similar level of support for the web standard would require either a lot of work or embedding an existing rendering engine, neither of which is worth it for a game engine.

**Comment by pycbouh** [comment] 2021-01-31 17:30
> Duplicate of https://github.com/godotengine/godot-proposals/issues/960.

Well not exactly, my proposal was specifically not for a UI replacement, but more like for text markup.

**Comment by IoneGod** [comment] 2021-01-31 17:41
Oh I get it you already proposed this that's why you had so much insight into this. But I also didn't specify a UI replacement just an addition to the control nodes like an HTML container node but either way it's nice knowing something related is already on ground

**Comment by r3ndd** [comment] 2023-02-13 15:39
> ...or embedding an existing rendering engine, neither of which is worth it for a game engine.

It is not immediately obvious why this statement is true, and no justification was provided. There are featureful, lightweight web rendering engines like Ultralight packaged as SDKs which are *specifically designed* for desktop applications and games, so clearly they have a differing opinion. Considering it would be possible to configure Godot to be compatible with such an SDK if the user provided it (but without actually including it in the Godot release), it seems like a viable option to add, since, as you describe, it would allow developers to use a mature UI rendering engine with years of development that may also be more familiar to them.

**Comment by YuriSizov** [comment] 2023-02-13 16:29
> It is not immediately obvious why this statement is true, and no justification was provided.

Godot has a built-in, efficient and native solution, that tested and is within our control. Embedding a third-party library would not be free, as no matter how lightweight it claims to be, it's still a lot of new code, without our reach or control, which aims to solve the exact same problem that is already solved by the engine. And the matter of not being within our control is a big no-no in general (and the reason we don't use Bullet for physics anymore, as one example). Relying on 3rd party libraries means we wouldn't be able to fix issues in a timely manner, while still taking responsibility before our users to support the system.

That said, as mentioned multiple times in this thread, where there is a will there is a way, and a module or an extension is possible to achieve what you need if you truly believe in it.
