### ISSUE TITLE
Make the animationplayer capable of recording objects / make animationrecorder node . . <3

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2208] opened 2021-01-31 05:59 UTC
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
I'm watching Metal Gear Solid 4, and it has many amazing cut-scenes, with a ' live ' camera . . Resident Evil 5 had the same, they sort of put ' mo - cap ' on a camera, and put that into a game . . That is very difficult to emulate, with a normal key-frame animation, but I was wondering if one could make the animationplayer node capable of recording things ' live ', maybe at 30 FPS, or even 60 FPS . . so, one could control camera movement with the mouse and, zoom and, focus levels with buttons, like ' W-S ' and, ' E - D ', to get something like this . .

https://www.youtube.com/watch?v=hK9Ie3Fp7yg

So, if one could move an object, live, like a box, or the camera, so on . . and, then RECORD that movement, in say 4 FPS, 8 FPS, 16 FPS, 30 FPS, 60 FPS . . and, then the animationplayer ' stores ' a key-frame, at each interval, then one can play it back . . then, one could make some ' fairly ' good virtual cameras, IF one could control where camera LOOKS with the mouse, and ZOOM levels, with two buttons ( since real cameras, today, have a zoom in, zoom out button, often ) and, FOV or, focus point . .

Basically, I'm asking if animationplayer could be made in such a way, it can record movements, so if I move a box around, on the screen, in a weird way, it record that, at say 10 FPS, 20 FPS, and stores that in an animationplayer, live . . it's mostly for stuff like cameras, to imitate the ' virtual ' cameras we have today, or so <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I was thinking, I would like a ' good ' virtual camera, that ' looks ' like it's been held, by a real person recording it, live . . that requires an expensive virtual camera, which one can buy, but I don't think I'd need more, than if I could control the camera with the mouse, to make jitter and, random motions, and have two buttons, to control zoom in, zoom out . . it would also mean, I should be able to configure the short-cut buttons, so I can control a slider, live . . for instance, so I can set TWO buttons, one for zoom in, other for zoom out, or set mouse - scroll, less comfortable, to zoom in or, out . .

I really only just need the animationplayer to be able to record, whatever I'm doing on screen, live . . so, if I record this . .

![2021-01-31 0652](https://user-images.githubusercontent.com/61069740/106375953-f8783500-6390-11eb-9f68-1488ebda5780.gif)

It ' writes ' keyframes, at some FPS, live . . it'd make cinematic cameras, but also some other stuff, easier . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Sort of, like ' animationplayer ' can also record, at maybe 4 FPS ( stores 4 keyframes, each second ), 8 FPS, 16 FPS, 30, FPS, 60 FPS, 120 FPS <3 . . also, so keys can be set to sort of, add or, subtract to a value, like FOV, zoom, so on, like sliders or, so . . . <3

![2021-01-31 0656](https://user-images.githubusercontent.com/61069740/106376013-72102300-6391-11eb-95c6-f23956ad8fd3.jpg)

it would also be useful for some other stuff, but I can't think of it now . . like, ' reverse keyframing ', or ' back keyframing ' <3, or so  . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Well, I can't re-program the engine, and can't do that, at all . . <3

### Is there a reason why this should be core and not an add-on in the asset library?
just add a button, to animation player, so you ' record ' stuff on screen, and you can select what stuff you want to record, like camera angle, rotation and, the ' zoom ' value, live . . then, one could make very good ' cinematic ' camera stuff, fast, and dirt - cheap, in Godot <3 . . also, people might start using it, for many other things . . or, select the objects you want to record, and auto - make the keyframe tracks, say position, rotation, scale, FOV, more . . :O :O <3 . . .

also, if one could first record say, camera rotation, then add to recording, by recording one more time, for zoom or, angle . . then, one could make amazing animations, using the mouse or, keyboard . .
![2021-01-31 0701](https://user-images.githubusercontent.com/61069740/106376113-43df1300-6392-11eb-8af2-af9cf3901348.gif)

and, one would be able preview it, live, in Godot, in the exact lighting settings, etc etc . . cheap pre-viz, on any computer <3 <3 . . . :OO . . .

**Comment by jasperbrooks79** [comment] 2021-01-31 06:07
I hope it makes sense, so if one could first record say, x-axis movement, controlled by the mouse, and y axis, then one could record one MORE time, from another viewport, to get z - axis, using only the mouse and, a slider . . maybe if one could have two buttons set aside, maybe page up and, page down, for controlling an ' axis ', like FOV, then one could make some really amazing animations, that could be replayed with linear interpolation, for many FPS, or pretty low FPS, for bezier stuff . .

it'd turn Godot, into a, if you NEED it, mouse controlled movie studio or, prod. center <3 . .

**Comment by jasperbrooks79** [comment] 2021-01-31 07:23
I updated the messages, this is the last part, it's done <3 . . no, more . . :DD <3 <3 

Thx . . .

**Comment by Calinou** [comment] 2021-01-31 17:25
Duplicate of https://github.com/godotengine/godot-proposals/issues/169.

**Closed by Calinou** 2021-01-31 17:25 UTC
Labels: topic:animation, topic:editor
