### ISSUE TITLE
Make relevant sections have a temporary and subtle highlight when jumping in the documentation 

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#7813] opened 2023-09-23 10:21 UTC
### Describe the project you are working on

stuff

### Describe the problem or limitation you are having in your project

When clicking a link that takes me to a property or method in the docs, I always find myself having to parse the screen to find the relevant info in busy pages (that is, all of them).

This big amount of text is painful to go through (even more so considering I can't really practically increase the docs font size), and I constantly fail to remember the rule that "the thing you have to look at is at the top of the screen". (not to mention that it's not always the case, and that pretty often your eyes are looking at where you click).

[simplescreenrecorder-2023-09-23_12.10.33.webm](https://github.com/godotengine/godot-proposals/assets/71937306/c6277c32-5217-4063-abaa-636f3135793a)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

one way to improve the experience a bit would be to show a rectangular highlight, that would gently flash to bring your attention to the data you've been taken to.
It would be subtle (as to not hurt anyone's eyes) and temporary (to not leave the docs in a "dirty" state).

It would happen when you jump to a method, variable or enum definition (am I missing something?) not a whole class page.
It would happen when you jump from docs but also when getting there from Ctrl+Clicking something in code, and right-clicking a property in the inspector.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://github.com/godotengine/godot-proposals/assets/71937306/304963cd-8c66-4363-9d5c-5184ee800b72

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it will be used all the time

### Is there a reason why this should be core and not an add-on in the asset library?

it's about the integrated docs

**Comment by KoBeWi** [comment] 2023-09-23 13:04
Duplicate of #2248

**Closed by KoBeWi** 2023-09-23 13:04 UTC
