### ISSUE TITLE
Implement a way to allow renaming and moving script files outside of Godot without breaking the project

### ISSUE THREAD

**Issue by Kopkako** [godotengine/godot-proposals#4598] opened 2022-05-28 00:54 UTC
### Describe the project you are working on

Any project that uses an external code editor/IDE.

### Describe the problem or limitation you are having in your project

When working on games in Godot and using an external code editor or IDE such as Rider or Visual Studio (for C# development) or Visual Studio Code for (GDScript development), I run into this problem:

- I rename a script file from within the code editor
*or*
- I move a script file to a different location, from within the code editor

When I switch back to Godot, my project is now broken, because Godot does not realize what just happened and can not find the script files that have been previously attached to nodes.

I realize that you can "just move/rename things from within Godot".
However, this is not a good solution: Modern code editors/IDEs such as Rider allow for rapid refactoring that automatically moves potentially hundreds of files (in larger projects) to different locations at once, or does deep renaming of classes and file names, automatically.

These features are essential for any larger projects and have become completely ingrained to my workflow, having used Unity with Rider for several years before switching to Godot recently. It provides huge benefits for medium to large projects.

Even when working on small prototypes, I have managed to break my entire project by doing simple refactoring like this, and it is currently one of the biggest frustrations I have when developing with Godot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I realize that Godot does not use *meta files* like Unity and thus has no internal system to prevent this from happening, currently. I do not know how this could be overcome, as I don't know the editor internals well enough, but I sure hope it is possible.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This could potentially also be implemented "from the outside" as a Rider or Visual Studio plugin?

### Is there a reason why this should be core and not an add-on in the asset library?

This should be core IMO because it affects everyone working on non-trivial games with Godot and an external editor, which should be a significant percentage of overall users.

**Comment by Mickeon** [comment] 2022-05-28 09:42
While I love the idea, I'm struggling to think of a way this could actually be feasible, unless there's a callback from these IDEs that Godot could answer to...? I'm no expert on this.

**Comment by Calinou** [comment] 2022-05-28 10:44
Duplicate of https://github.com/godotengine/godot-proposals/issues/2430

**Closed by Calinou** 2022-05-28 10:44 UTC
Labels: topic:core

**Comment by Byteron** [comment] 2022-05-28 12:53
> Adding refactoring functionality to the script editor is being tracked in #899.

@Calinou I believe this was referring to renaming files, not variables / classes. And unless the build-in script editor gains *massive* improvements to C# tooling, using the build-in editor with C# simply is not an option.

Hence I think this should stay open, and should definitely be addressed.
Working on larger projects with C# without being able to rename files from within the external IDE makes life harder for everyone involed and should definitely be supported.

**Comment by YuriSizov** [comment] 2022-05-28 13:21
> Hence I think this should stay open, and should definitely be addressed.

This was closed because https://github.com/godotengine/godot-proposals/issues/2430 is a better, well-defined solution for the problem, not because #899 exists.

Furthermore, we prefer to keep proposal _issues_ for actual practical suggestions with implementation detail. For general discussion and looking for a solution please use _discussions_.
