### ISSUE TITLE
Add C-like block syntax support to GDScript

### ISSUE THREAD

**Issue by dmitryuck** [godotengine/godot-proposals#1940] opened 2020-12-05 14:43 UTC
### Describe the project you are working on
Any project

### Describe the problem or limitation you are having in your project
GDScript uses python-like syntax

### Describe the feature/enhancement and how it helps to overcome the problem or limitation
Add to GDScript c-like scope definitions along with python-like

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
To make this code also valid in GDScript

```
func some_function(param1, param2) {
    var local_var = 5

    if param1 < local_var {
        print(param1)
    } elif param2 > 5 {
        print(param2)
    } else {
        print("Fail!")
    }

    for i in range(20) {
        print(i)
    }

    while param2 != 0 {
        param2 -= 1
   }

    var local_var2 = param1 + 3

    return local_var2
}
```
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
Extend GDScript

**Comment by Jummit** [comment] 2020-12-05 14:53
Why is python-like syntax a limitation?

**Comment by dmitryuck** [comment] 2020-12-05 15:01
Not a limitation, it's different

**Comment by pycbouh** [comment] 2020-12-05 15:04
Yes, but how does being different justify this change? Plus, making optional syntax is an awful idea. Terse and constricted works much better when constant arguments about which way to format code is better. We have enough inconsistent parts already.

**Comment by dmitryuck** [comment] 2020-12-05 15:52
as far as I know, the only python has such block syntax, and coders who are used to C# or JS..., wouldn't choose python because of this difference, GDS focuses primarily on them. Really optimized and performable GDS have to be a choice for non-python devs

**Comment by pycbouh** [comment] 2020-12-05 16:02
Syntax, in this case, has nothing to do with performance...

**Comment by Calinou** [comment] 2020-12-05 16:06
Duplicate of https://github.com/godotengine/godot-proposals/issues/1555 which has been rejected already.

**Closed by Calinou** 2020-12-05 16:06 UTC
Labels: topic:gdscript
