### ISSUE TITLE
Additional mouse support (Editor*)

### ISSUE THREAD

**Issue by SuperDIMMaX** [godotengine/godot-proposals#1287] opened 2020-08-01 04:31 UTC
**Describe the project you are working on:**
Any? - Editor*
**Describe the problem or limitation you are having in your project:**
Mouse button support and severals adds.
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Many mouse have extra button and work as - in browser, file maneger - back - forward.
And Mouse wheel if selected ScrollBar in editor not... working? 
![image](https://user-images.githubusercontent.com/22836285/89093807-4ef6bd80-d3c6-11ea-8dc2-8ad6a6337b12.png)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
back - forward in editor
Selectable ScrollBar with mouse wheel support
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Often. can`t
**Is there a reason why this should be core and not an add-on in the asset library?:**
Expected behavior for users.

**Comment by Calinou** [comment] 2020-08-01 12:13
> Many mouse have extra button and work as - in browser, file maneger - back - forward.

Duplicate of https://github.com/godotengine/godot-proposals/issues/954.

> And Mouse wheel if selected ScrollBar in editor not... working?

This is intended. Otherwise, you could end up accidentally modifying properties while scrolling in the inspector.

**Closed by Calinou** 2020-08-01 12:13 UTC
