### ISSUE TITLE
Run arguments per game instance

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot-proposals#5521] opened 2022-09-30 08:40 UTC
### Describe the project you are working on

Multiplayer world building game

### Describe the problem or limitation you are having in your project

When using `Debug -> Run multiple instances -> 3` it's impossible to define different run arguments per instance of the game.
It would be the best if we could for example define `--server` argument for the first instance and `--client` arguments for other instances

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In `Project Settings -> Editor -> Run` instead of one field `Main Run Args` there should be 4 fields, one per each application instance

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![instance_args](https://user-images.githubusercontent.com/6129594/193229211-c533d748-e46f-4b66-b768-f2ed503c5fa7.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not in an obvious way

### Is there a reason why this should be core and not an add-on in the asset library?

Ability to run multiple app instances is core feature of the editor, this proposal is small quality of life improvement for it

**Comment by KoBeWi** [comment] 2022-09-30 11:05
Duplicate of #522
It has a WIP implementation that is already usable (just needs polishing): https://github.com/godotengine/godot/pull/65753

**Closed by KoBeWi** 2022-09-30 11:05 UTC

**Comment by kubecz3k** [comment] 2022-09-30 11:40
hah had notion I had seen some discussion about it but could not find it in any way with key words like 'run arguments' 'run args'... I guess the title could be more explicit
