### ISSUE TITLE
Add `add tab` button in `TabContainer`

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#2289] opened 2021-02-14 20:00 UTC
### Describe the project you are working on
plugins

### Describe the problem or limitation you are having in your project
I need Add tab "+" button in TabContainer like Godot Editor scene tabs have:
![tabs1](https://user-images.githubusercontent.com/16458555/107886610-a7d11200-6f22-11eb-8a92-a606ec65a962.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Adding `add tab` button in `TabContainer` would solve the problem

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. new propery:
`bool show_add_tab` -> `true` to show add tab button, `false` to hide it

2. new signal:
`int add_button_pressed`
This button should do nothing, only emit the signal.
User should connect to the signal and add a child control with `add_child()` when the signal is fired/triggered.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It seems this is doable using `Tabs`, but isn't trivial if you want it to work like in Godot scene tabs.

### Is there a reason why this should be core and not an add-on in the asset library?

Add-a-tab button is a common UX solution for adding tabs. A lot of apps use it.

**Comment by pycbouh** [comment] 2021-02-14 20:03
A duplicate of a more general proposal #2250

**Closed by pycbouh** 2021-02-14 20:03 UTC
