### ISSUE TITLE
Godot Building System Needs To Be Rewritten

### ISSUE THREAD

**Issue by NotRabug50** [godotengine/godot-proposals#7359] opened 2023-07-23 19:36 UTC
### Describe the project you are working on

I am working on RPG game where you can fight and talk with enemies and I want to release it for android too

### Describe the problem or limitation you are having in your project

The Android build system clearly gives the code and assets in the game and you can easily modify and change the code

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

You can use .pck files to store assets or code in the game for Android build

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

You can make it mandatory or add a feature to the render window like "pack game assets", "pack game code", etc.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

absolutely not. because you guys probably need to rewrite the android build system

### Is there a reason why this should be core and not an add-on in the asset library?

because this is a big problem (i think)

**Comment by Calinou** [comment] 2023-07-23 20:32
- Duplicate of https://github.com/godotengine/godot-proposals/issues/6675. (This does *not* require rewriting the build system from scratch.)

**Closed by Calinou** 2023-07-23 20:32 UTC
