### ISSUE TITLE
Node Export Hint Syntactic Sugar

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot-proposals#1681] opened 2020-10-17 17:25 UTC
**Describe the project you are working on:**
I'm working on a platformer that relies heavily on the Entity-Component design pattern, which, I feel, is largely Godot's conceptual inspiration for Scenes and Nodes.

**Describe the problem or limitation you are having in your project:**
My project uses a lot of `NodePath` export variables to access other Nodes' signals. It's very common to do something like this for almost all scripts:
```
extends Node

export(NodePath) var _node_path := NodePath()

onready var _node := get_node_or_null(_node_path) as NodeTypeIWant
```

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I think an export hint that acts as syntactic sugar for accessing nodes would be really useful.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Since 4.0 is moving over to annotations for export hints, it seems pretty simple to do something like:
```
@export_node_in_tree(Node2D) var _sprite_node := null
```

The inspector controls would look exactly the same as the `NodePath` control, and allow you to pick an item in the tree, however, if the script it on a node is in the scene tree, the node path gets translated into a node and cached if possible. If that's not possible, the exported variable just returns null.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This will be used often. I can't really think of many reasons to export a `NodePath` if it's not going to be used to access a node in the scene tree either, so why not streamline the process for the programmer?

**Is there a reason why this should be core and not an add-on in the asset library?:**
This should be in core because the main purpose of exporting a `NodePath` is to access a `Node` in the scene tree later.

The issue with attaching Node access to the `NodePath` export variables is that the `NodePath` is really only useful in the editor while the actual node is what we really want when the game is loaded. Moreover, in code, it's far more likely you have access to a node instance rather than it's relative NodePath to another node.

What we actually want to do it set a `NodePath` for the editor but then Godot should automatically lazily cache the actual Node when the export variable is accessed for `get`.

**Comment by Zireael07** [comment] 2020-10-17 18:24
Oh heck yes please! Accessing other nodes happens fairly common and using a dummy group is not always a good idea especially if I change things around in the editor, I often forget to update groups

**Comment by KoBeWi** [comment] 2020-10-17 20:44
Duplicate of #1048

**Closed by KoBeWi** 2020-10-17 20:44 UTC
Labels: topic:editor
