### ISSUE TITLE
Stop Editor from using GPU when 3d viewport is not visible ( like editing scripts)

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot-proposals#5754] opened 2022-11-09 18:07 UTC
### Describe the project you are working on

A 3d game.

### Describe the problem or limitation you are having in your project

When editing scripts for an opened scene, it seems that the editor keeps GPU usage even if the 3d viewport is not visible. This causes high battery usage on a mobile device which could be avoided. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The editor should stop using GPU if the 3d viewport is not visible like when we are editing scripts.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When all scenes are closed we can edit scripts without the editor using GPU. This should be the behavior when  the 3d viewport is not visible even if the scene tab is opened in the editor.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is a core feature.

### Is there a reason why this should be core and not an add-on in the asset library?

It is a core feature.

**Comment by Calinou** [comment] 2022-11-09 18:22
Duplicate of https://github.com/godotengine/godot/issues/39758 (this is a bug).

**Closed by Calinou** 2022-11-09 18:22 UTC

**Comment by jcarlosrc** [comment] 2022-11-09 18:31
I cannot see it as a direct duplicate but I hope it gets solved. Current Godot 4 Beta 4 still uses GPU even if the 3d viewport is not visible at all in the editor. Thanks.
