### ISSUE TITLE
C#: Allow project source files to be separated into a sub project folder.

### ISSUE THREAD

**Issue by Avantir-Chaosfire** [godotengine/godot-proposals#2646] opened 2021-04-24 17:06 UTC
### Describe the project you are working on
Small C# game

### Describe the problem or limitation you are having in your project
C# project are all forced under the root project directory, making the directory messy, hard to distinguish what is Visual Studio and what is Godot. Would only become worse with multiple projects (is that even possible with the current setup?).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Allow C# projects to exist in subdirectories of the Godot project directory.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
n/a

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not necessary, just improves project organization.

### Is there a reason why this should be core and not an add-on in the asset library?
It can't be an add-on. It is core. (Why do I have to answer these irrelevant template questions?)

### Actual details:

Credit to https://github.com/godotengine/godot/issues/28290

Currently all C# projects are forced to be in the root project folder meaning the default namespace will always be that folder and most code is put into sub folders. When that happens your src, code, project, scripts, etc... subfolder where you store your scripts and other source code now is forced to be added into the namespace path eg.: ProjectName.Scripts which ideally despite scripts not needing namespaces, you would want your scripts on the root namespace which is just ProjectName.

I was messing around with jetbrains console project and realized there's a feature that allows you to set this in the sln file. For instance:

```
Microsoft Visual Studio Solution File, Format Version 12.00
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ConsoleApplication6", "ConsoleApplication6\ConsoleApplication6.csproj", "{D7E527AF-F5E5-45A0-AAE6-B4C46ED0347D}"
EndProject
Global
    GlobalSection(SolutionConfigurationPlatforms) = preSolution
        Debug|Any CPU = Debug|Any CPU
        Release|Any CPU = Release|Any CPU
    EndGlobalSection
    GlobalSection(ProjectConfigurationPlatforms) = postSolution
        {D7E527AF-F5E5-45A0-AAE6-B4C46ED0347D}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
        {D7E527AF-F5E5-45A0-AAE6-B4C46ED0347D}.Debug|Any CPU.Build.0 = Debug|Any CPU
        {D7E527AF-F5E5-45A0-AAE6-B4C46ED0347D}.Release|Any CPU.ActiveCfg = Release|Any CPU
        {D7E527AF-F5E5-45A0-AAE6-B4C46ED0347D}.Release|Any CPU.Build.0 = Release|Any CPU
    EndGlobalSection
EndGlobal
```

Now you could try manually editing this to your project sln, but building in editor complains if you move the .mono, .csproj to the sub folder.

### Suggestion:
Allow c# projects to have a sub folder inside the project folder with the same name be the root of our project. This would make separating the c# much cleaner and organize the code base better.

Just a simple checkbox asking if the project source be in a subfolder ProjectName\ProjectName and when enabled the editor will look in that folder for the source as the root rather than the root project folder.

**Comment by Calinou** [comment] 2021-04-24 17:18
Related to/duplicate of https://github.com/godotengine/godot-proposals/issues/1141 ?

**Comment by GeorgeS2019** [comment] 2021-04-29 19:27
@Avantir-Chaosfire  we are discussing this topic within the GodotXUnit .  The main branch with multiple c# projects => Addon c# csproj.  Folder Test has additional c# csproj.  Then there is the main c# csproj at the root directory.   The hack branch attempts to have only one c# csproj.   The solution is not optimal, at least there are people attempting to improve that at the GodotXunit issues.

**Comment by raulsntos** [comment] 2023-06-14 11:32
Multiple C# projects are now supported in both 4.x and 3.x. A new setting has been introduced in 4.0 (`dotnet/project/solution_directory`) and 3.6 (`mono/project/solution_directory`) to allow specifying a custom path for the `.sln`, this setting should allow you to follow the recommended [multi-project directory structure](https://gist.github.com/davidfowl/ed7564297c61fe9ab814).

Here's an example of how a multi-project solution could look like:

```
MainFolder
├── ProjectName.sln
├── src
│ ├── ProjectName  (Godot project)
│ │ ├── ProjectName.csproj
│ │ ├── project.godot
│ ├── ProjectName.AnotherDotnetProject
│ │ ├── ProjectName.AnotherDotnetProject.csproj
```

Since this is already supported, I'll close this proposal as resolved.

**Closed by raulsntos** 2023-06-14 11:32 UTC
Labels: topic:editor, topic:dotnet

**Comment by p10tr3k** [comment] 2023-09-20 22:30
> Multiple C# projects are now supported in both 4.x and 3.x. 

Just trying to have multi-project solution and I don't think it is working. I can add new projects to solution, but if I add new cs class in editor the solution is recreated and all my changes in it are lost.

**Comment by ChadNedzlek** [comment] 2023-10-04 01:23
I don't think the resolution matches the issues request.  I want all the C# files in one folder, away from all the godot stuff (the scenes, the time maps, etc).  The "solutio_directory" essentially only lets you move the solution "up" to parent directories.  The csproj is still stuck living next to all the other godot stuff.

I'd really like to be able to put all the C# stuff in one directory _inside_ the godot project (after all, it's useless outside of it), and have it be isolated from the rest of the stuff, something like 
```
MainFolder
├── project.godot
├── ... other godot resources ...
├── scripts
| ├── ProjectName.sln
| ├── ProjectWithAllTheNodeScripts
|  | ├── ProjectWithAllTheNodeScripts.csproj
| ├── HelperProject
|  | ├── HelperProject.csproj
```

I played around with the setting, and I couldn't get anything like this (I _really_ want the C# code to be isolated into a single directory that doesn't contain a bunch of other stuff under it).

Essentially what seems possible now is the inverse of what this issue what asking for.  Instead of letting the source files being separated into a sub folder, the godot stuff is now required to be a sub folder of the solution?

**Comment by dreadicon** [comment] 2024-08-13 15:19
Just chiming in here, while this is technically something that can be worked around, it is a colossal pain (cost us about a week of dev) if the project isn't planned or this unexpected limitation is not made known ahead of time.

Further, there seems to be some possible issues with Node and Resource objects defined outside the Godot Project folder, which is again counter to C#/.NET coding philosophy and practices. 

We did in fact consider recompiling the .NET godot module over complying with the hard-coded path string, it was that bad. The best thing about Godot over Unity (besides license) is how un-opinionated it generally is, and supportive of conventional code practices. Code-first, as it were. This is opposite, tightly binding Godot's structure arbitrarily to a monolithic project, defined by a hard-coded and counter-intuitive Godot-csharp project co-location. It may be intuitive for those coming from godot script oriented development, but that's not who the csharp support is for, fundamentally.

It's a minor thing that would have saved us a ton of work. I understand if the issue of Node/Resources defined outside the primary CS project is more complex, but at least the fundamental structural issue should be resolved within the next release or so; there's just no reason not to, as it's just changing how a couple of files are found based on a user setting.

If interested as to why this was such a pain, first the fact that this was a hard requirement at all took a day or two to puzzle out; every CS platform I've ever worked with had no opinions about where in your greater project the code should be other than under the .sln. Once we figured that out, we had to sync up the team so that the whole project could be refactored (moved into a sub-folder as the project was in the git root folder) without trampling anyone's work, which took time for people to wrap things up, leaving some of us with little to do in the mean time. Finally, after being moved, a number of links, references, etc broke. After all was said and done, we lost a week of dev.

**Comment by VoidEssy** [comment] 2025-03-23 02:28
After fruitlessly searching for "Godot C# Multi-Project Setup" I'll admit, I'm a bit shocked at how hard and painful it is to get multiple assemblies to run in Godot.

What in practiceshould be as trivial as 
1. Create your first C# Script in Godot so it creates the SLN.
1. Right Click. In Solution Explorer (VS, Should work same in Rider)
1. Add
1. New Project
1. ClassLibrary
1. Add your code
1. Reference your code via Add Reference in your Node Extended Code
At least In regular C# / .NET Development and In Unity.

Turns into nightmare, some recommend manually mapping and remapping the assemblies, using anything but the default path it sets (outside of the Godot Project for some reason) will work as along as you CTRL + SHIFT + B the whole thing before you try building it in Editor. Nesting the C# Project/Assembly will thought result in errors like.
`cs0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute C:\GodotProjects\anotherstructuretest\.godot\mono\temp\obj\Debug\AnotherStructureTest.AssemblyInfo.cs(14,12)`

Hope I'm not making noise in the wrong thread but this seems closest to the issue I've been trying to figure a solution to since 4.2 and many searches either talk about finnicky remapping / workarounds or are supposedly resolved.

**Comment by Delsin-Yu** [comment] 2025-03-23 02:42
@VoidEssy 

The short answer is no. The GodotSharp, or the current modern dotnet integration, is upgraded from the old mono-based integration, which was designed based on the assumption that each project has only one csharp project.

**Comment by dreadicon** [comment] 2025-03-23 02:50
@VoidEssy the ultimate solution I developed was using C# code generator to make partial stub classes and plug in files automatically for 'external' assemblies. Worth it? Nope, but I went Captain Ahab about adhering to good C# practices this project, so I did it anyway!

**Comment by ChadNedzlek** [comment] 2025-03-24 22:51
My solution was "don't use Godot" which made me sad. Having to shove everything into a single giant assembly and deal with both VS and Godot fighting over what things meant was such a hassle that I stopped trying. :-( I love C#, and was really excited to be able to use C# to do some game development, but the pain was so high that I just... gave up.

**Comment by Delsin-Yu** [comment] 2025-03-25 05:14
> with both VS and Godot fighting over what things

Can you elaborate on this part?

> and was really excited to be able to use C# to do some game development

Do you have expertise in other C#-based game engines? In your opinion, what would be the preferrable approach to this?
