### ISSUE TITLE
Allow to rotate the tiles with arrow keys like before

### ISSUE THREAD

**Issue by Nicat5** [godotengine/godot-proposals#6763] opened 2023-04-26 14:43 UTC
### Describe the project you are working on

2D game with a lot of tiles

### Describe the problem or limitation you are having in your project

If I am not wrong you were able to rotate the tiles in tilemap with arrow keys in 3.x. Now you can't I don't know if there is a way of rotating the scenes in tilemaps. The only option is to add 4 scenes each rotated

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It will help optimize the game add a new useful feature to the tilemaps

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When left arrow key is pressed when a tile is selected it will rotate it 90 degrees to left and same for right

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It used a lot in 3.x, so I think yes?

### Is there a reason why this should be core and not an add-on in the asset library?

It was in 3.x

**Comment by Calinou** [comment] 2023-04-26 17:15
- Duplicate of https://github.com/godotengine/godot-proposals/issues/3967.

**Closed by Calinou** 2023-04-26 17:15 UTC
