### ISSUE TITLE
Allow canvas to be used as fog color in 3.x

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#7138] opened 2023-06-22 17:33 UTC
### Describe the project you are working on

Retro FPS.

### Describe the problem or limitation you are having in your project

I'm using a canvas as the skybox, but fog can only be set to a color, creating a weird silhouette (in this case of tree models) instead of appearing as a short distance draw:
![image](https://github.com/godotengine/godot-proposals/assets/16231628/6477dbfa-871b-4729-8e0d-0192432a3263)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Since canvas is allowed to be used as a background, the fog should just use the canvas for it instead of a color. Since I am manually rotating the canvas via script, it would be convenient if the fog could just use the canvas exactly as it appears (materials, shaders, etc).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It would be an option in fog settings:
![image](https://github.com/godotengine/godot-proposals/assets/16231628/c25062c3-6731-4e3c-ba71-cbc95f06c852)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't believe so, although I'd be more than happy if there were an alternative solution.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't know if fog can be reimplemented without core code (I could be wrong).

**Comment by elvisish** [comment] 2023-06-22 17:34
Claims to be fixed here but doesn't appear to be (certainly not in 3.x): https://github.com/godotengine/godot-proposals/issues/999
https://github.com/godotengine/godot/pull/41418

**Comment by AThousandShips** [comment] 2023-06-22 17:40
Unless this is a bug, or something that can be back-ported from 4.x, getting 3.x specific new features is unfortunately very unlikely

**Comment by Calinou** [comment] 2023-06-22 20:05
Duplicate of https://github.com/godotengine/godot-proposals/issues/2963.

**Closed by Calinou** 2023-06-22 20:05 UTC
Labels: topic:rendering, topic:3d

**Comment by elvisish** [comment] 2023-06-23 06:47
> Duplicate of https://github.com/godotengine/godot-proposals/issues/2963.

I don't think this is a duplicate as this is requesting using canvas as fog albedo, not a panorama/cubemap? The two perspectives would look significantly different (canvas is a 2D projection and a panorama would be obviously spherical).
