### ISSUE TITLE
Add a `loop_offset` property to Animations (similar to audio loop points)

### ISSUE THREAD

**Issue by AzedaxenSoftware** [godotengine/godot-proposals#6896] opened 2023-05-16 23:46 UTC
### Describe the project you are working on

Projects with animations.

### Describe the problem or limitation you are having in your project

Quite often, animations will have an intro, but then the rest of the animation needs to loop without re-playing that intro. For example, a jump animation may begin with the character ducking down to jump, then extending their legs to push themselves up into the air. The character should continue to show their legs extended, and it would look awkward if the ducking also looped. Getting this behavior requires a more complex setup than what is possible just using an `AnimationPlayer`, which can be cumbersome.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a `loop_offset` property to `Animation` to allow setting a point where the animation will loop from, just like how loop offsets can be set for audio files. This allows the animation to loop from a set point, skipping over the part of the animation that the user doesn't want to loop.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

`Animation` resources would have an added `loop_offset` property, representing the time in seconds which the animation should loop from. This value would default to 0.0, meaning animations loop from the start by default. An extra UI element would be added to the Animation editor window, allowing the user to drag the loop offset to any part of the animation, or to set it to an exact time.

For linear looping animations, when the animation reaches its end, it will go back to wherever the loop offset is. For ping-pong loops, the animation will ping-pong between the loop offset and the end of the animation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

One current workaround to this is to split animations into separate "Start" and "Loop" variants, i.e. "JumpStart" and "JumpLoop", then use an `AnimationTree` state machine to automatically play the looping part of the animation when the start of the animation is finished. However, this is cumbersome and splitting animations like this bloats the animation list. It would be much more convenient to have both the intro and the loop stored in the same animation so that we don't have to use `AnimationTree` just to accomplish this.

### Is there a reason why this should be core and not an add-on in the asset library?

I believe that this is a common enough thing for animations to use that it would make sense to include as core.

**Comment by golddotasksquestions** [comment] 2023-05-25 16:42
`loop_animation_region` maybe? To differentiate from the texture region.

**Comment by Calinou** [comment] 2023-06-05 16:11
- Duplicate of https://github.com/godotengine/godot-proposals/issues/2159.

**Closed by Calinou** 2023-06-05 16:11 UTC
Labels: topic:animation
