### ISSUE TITLE
Hover tooltips in code editor

### ISSUE THREAD

**Issue by alterae** [godotengine/godot-proposals#3711] opened 2021-12-22 19:13 UTC
### Describe the project you are working on

At the moment, a small "Asteroids" clone, written using GDScript with static typing.

### Describe the problem or limitation you are having in your project

In the built-in code editor, there are no tooltips.  This makes it impossible to view the types of statically typed variables, and means that in order to view the documentation for a method I have to press `ctrl`+`click`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Tooltips should display when hovering over variable, parameter, or function names in the built-in code editor, as is common in many IDEs.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Tooltips should behave similar to in the VS Code Godot extension (which I unfortunately cannot provide screenshots of at this time)

Hovering over a usage of a variable or function parameter should show its name, type, and docstring if one exists.

Hovering over a usage of a function should show its name, return type, parameters and parameter types, and a docstring if one exists.

Additionally, in the completion menu, the tooltip for the selected completion should display.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's probably possible to write an editor plugin that does this, but I lack the technical know-how to do so myself.  Ctrl+click provides a partial workaround, but is significantly less ergonomic.

### Is there a reason why this should be core and not an add-on in the asset library?

Hover documentation is a common feature in nearly every code editor, and massively increases the ease of programming by reducing context switching and making symbols and functions far more discoverable.

**Comment by Calinou** [comment] 2021-12-22 19:53
Duplicate of https://github.com/godotengine/godot-proposals/issues/1393.

**Closed by Calinou** 2021-12-22 19:53 UTC
