### ISSUE TITLE
Add the ability to enter the Editor Settings without needing to access a project.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [godotengine/godot-proposals#7824] opened 2023-09-23 17:52 UTC
### Describe the project you are working on

No. It's not relevant.

### Describe the problem or limitation you are having in your project

I don't want to be forced to load a project solely to modify the configuration of Godot. See https://godotforums.org/d/36359-how-to-access-preferences-without-any-projects.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

> Add the ability to enter the Editor Settings without needing to access a project.

per the title.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

No.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not that I know of. A user would need to modify the source code of the engine and (re)compile it.

### Is there a reason why this should be core and not an add-on in the asset library?

I doubt that Godot is quite that extensible - that an add-on can modify the context menu entries.

**Comment by KoBeWi** [comment] 2023-09-23 18:55
Duplicate of #1602

**Closed by KoBeWi** 2023-09-23 18:55 UTC
