### ISSUE TITLE
If the "Debug port" is already in use and user presses the "Play button", the editor will display a popup, asking for a different port number.

### ISSUE THREAD

**Issue by amoriqbal** [godotengine/godot-proposals#2583] opened 2021-04-10 11:15 UTC
### Describe the project you are working on
I am working on a Multiplayer game. In order to test the lobby, I need two Godot projects open in two different editors. The two projects must be played simultaneously and debugged using two different editor ports.

### Describe the problem or limitation you are having in your project
Often, I need to open upto 4 Editor instances, to set up a proper testing environment. (This is not specific to the current project). If I do not change the debug port for each of the editors then, the editors show error "port xxxx is already in use", but the projects start playing. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
When you press the play button, if the debug port is already in use, the editor should show a pop-up "Port XXXX is already in use. Please enter a different port number: [ field for new port number ] [Okay button] [Abort button]

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
`
func on_Play_pressed(port):
    status = bind_port(port)
    if status = error:
        $ErrorPopup.popup()
        return
    play_scene(main_scene)

func on_OkayButtonOnPopup_pressed(new_port_number):
    emmit_signal("play_pressed", new_port_number)
`
### If this enhancement will not be used often, can it be worked around with a few lines of script?
This enhancement will be useful for everyone who uses more than one editor window at a time. And that should be the case for every multiplayer game. It will be only a few lines of code, but the user has to make the change in the editor.

### Is there a reason why this should be core and not an add-on in the asset library?
Showing "Error: port xxxx already in use." But still running the project with erratic debug output, is an inconsistent behaviour. Displaying a pop-up and asking the user to rectify his mistake, will be convenient to all such users as mentioned before. As this feature will not consume any editor space and is only a few lines of added code to the editor, I think we should not ask the users to install a plug-in for this.

**Comment by Calinou** [comment] 2021-04-10 15:33
Duplicate of https://github.com/godotengine/godot-proposals/issues/1335.

**Closed by Calinou** 2021-04-10 15:33 UTC
