### ISSUE TITLE
Read export_path when exporting on command line

### ISSUE THREAD

**Issue by crawfxrd** [godotengine/godot-proposals#1803] opened 2020-11-11 01:19 UTC
**Describe the project you are working on:**

Godot 3.2.3

**Describe the problem or limitation you are having in your project:**

When running an export command from the command line, I shouldn't have to set the export path if `export_path` is already set for the target in `export_presets.cfg`.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Attempt to read `export_path` for the named export if not specified on the command line before failing.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

```
godot --export "Linux/X11"
```

Does `export_path` exist for the target?
- If yes, use it
- If no, error as it currently does

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Workaround: Use a bash script to circumvent this and other shortcomings of using Godot on the command line.

**Is there a reason why this should be core and not an add-on in the asset library?:**

QOL improvement for fundamental functionality.

**Comment by KoBeWi** [comment] 2020-11-11 02:10
Duplicate of #774

**Closed by KoBeWi** 2020-11-11 02:10 UTC
