### ISSUE TITLE
Add Shortcuts in the editor to switch between the bottom panel windows

### ISSUE THREAD

**Issue by WhalesState** [godotengine/godot-proposals#3887] opened 2022-01-29 06:48 UTC
### Describe the project you are working on

an editor plugin that eases the use of the godot editor.

### Describe the problem or limitation you are having in your project

before i learn Godot i was using blender 2.7, we used to remember the shortcuts for everything in the editor and it was painful, so for example it will be so useful if we can switch between the main screen windows with `ctrl+1` to open the first visible main screen, and so on, just in case we have disabled the 3d editor for example so it will not count, and disable the `ctrl+F1` options because the first option will be better, currently i open the script editor with `ctrl+F3` which is my second visible main screen editor! so it should be opened with `ctrl+F2` because i already disabled the 3d editor.

![image](https://user-images.githubusercontent.com/53877170/151650874-36ee2ff5-447e-48ba-ad24-052e2411dddc.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

the solution is the first option, `ctrl+number` will open the visible window depends on the number that you have entered based on the visible main screens order, and the hidden main screens won't count, and also for the `output`, `debugger` in the bottom panel, make it the same way that it opens with `ctrl+alt+number` and the number decides which bottom panel window should be visible so i don't have to remember anymore the constant shortcuts for each main screen and it will work for my main screen plugins by default when i add them.
and also you can make labels with numbers appears over when we hold `ctrl` or `ctrl+alt` to show us numbers over each window button to help us, so the shortcuts for the main screen and the bottom panel will not be constants anymore, it will depends on the visible windows, and you no longer need to keep their shortcuts in the editor settings or to remember them.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

lazy to write it in correct gdscript style, treat it as pseudo-code please :sweat_smile:
```gdscript
func _input(event):
    if event is (button_ctrl and not button_alt):
        showHintsOverTheMainScreenButtons()
    if event is (button_ctrl and button_alt):
        showHintsOverTheBottomPanelButtons()
    if event is (button_ctrl and not button_alt and number):
        selectMainScreen(number) # hidden main screens won't count
    if event is (button_ctrl and button_alt and number):
        selectBottomPanelWindow(number)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it will surely be used by all of us, since we will no longer need to remember the shortcuts and we just need to remember the combination of `ctrl+number` and `ctrl+alt+number` only, also you can allow us to define the combinations of the modifiers that will do this process, for example i can change the shortcut for main screens to be `ctrl+shift+number` instead of `ctrl+number`, just in case it will have a conflict with the OS shortcuts or to be easier for me to change them to whatever modifiers i want.

### Is there a reason why this should be core and not an add-on in the asset library?

yes, because it will allow us to switch between the bottom panel tabs and the main screen tabs without the need of remembering their shortcuts, it will work with their order. it also can be up to 10 numbers starting from `1` to open the first main screen or the first bottom panel window and ends with `0` to open the 10th one, up to 10 visible tabs in each panel ! who will need to have more than 10 visible tabs in main screens or bottom panel?

**Comment by Zireael07** [comment] 2022-01-29 09:13
I think ctrl+number is already used for editor tabs or views?

Also ctrl+alt+something shortcuts are known to misbehave and/or conflict with system shortcuts often.

**Comment by WhalesState** [comment] 2022-01-29 09:51
@Zireael07 for me, all OS shortcuts uses the `Super+key` or Super with modifiers, i already have tested those shortcuts in godot and they do nothing in the editor and there's no conflict. only the alt is some Linux distro instead of the windows and i always replace it to Super because it conflicts with so many programs that i use.

**Comment by Calinou** [comment] 2022-01-29 16:17
Duplicate of https://github.com/godotengine/godot-proposals/issues/380.

**Closed by Calinou** 2022-01-29 16:17 UTC
