### ISSUE TITLE
Something like npm system for Godot assets and library packages

### ISSUE THREAD

**Issue by AhmedElTabarani** [godotengine/godot-proposals#3385] opened 2021-10-04 23:44 UTC
### Describe the project you are working on

For any project

### Describe the problem or limitation you are having in your project

I know Godot already has a way to download assets
But I was thinking if Godot has his own terminal to download community libraries and automatically stored the names of libraries packages in a file similar to package.json

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This will make projects and libraries more dynamic and more comfortable for developers

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Initial Godot to receive the packages

```bash
godot init
```
now that will create a `package.json` in the project

install a package library from the community assets

```bash
godot install godot-rust
```
and it will be stored in `/addons` file automatic
and the name of the package library will store in `package.json`
uninstall a package

```bash
godot uninstall godot-rust
```

I think that is enough to clarify the idea

### If this enhancement will not be used often, can it be worked around with a few lines of script?

.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think anyone can do it by himself  without an API that would give him access to Godot's assets, but I think it would be better if it was supported by Godot itself as core inside the editor, especially if Godot's internal terminal was programmed.

**Comment by pycbouh** [comment] 2021-10-04 23:55
Duplicate of https://github.com/godotengine/godot-proposals/issues/142, though a CLI utility is unlikely at this point. You can use project templates for setting up projects with a bunch of preinstalled addons.

**Closed by pycbouh** 2021-10-04 23:55 UTC
