### ISSUE TITLE
Allow undocking of the animation timeline panel

### ISSUE THREAD

**Issue by philippedcote** [godotengine/godot-proposals#3628] opened 2021-12-02 19:08 UTC
### Describe the project you are working on

Doing heavy animations with the animation timeline on a UI project.

### Describe the problem or limitation you are having in your project

Trying to view all the animation keyframes at once along the Editor 2D view is very challenging.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow undocking of the animation timeline (or even better, undocking of all panels). Undocking allow the user to configure its working environment as he sees fit.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

- When the panel is docked, if the user clicks the kebab menu button, it should show a "Undock panel" command, which should allow the user to place the window wherever he wants.
- When the panel is undocked, if the user clicks the kebab menu button, it should show a "Dock panel" command, which should put the animation panel back into place.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, unfortunately.

### Is there a reason why this should be core and not an add-on in the asset library?

This should be core. The big animation softwares like After Effects and Cinema 4D are allowing this.

**Comment by pycbouh** [comment] 2021-12-02 19:12
Duplicate of https://github.com/godotengine/godot-proposals/issues/1508. See also https://github.com/godotengine/godot-proposals/issues/28.

**Closed by pycbouh** 2021-12-02 19:12 UTC
