### ISSUE TITLE
Add the ability to inspect the running scene from the editor 

### ISSUE THREAD

**Issue by anunknowperson** [godotengine/godot-proposals#2978] opened 2021-07-11 08:40 UTC
### Describe the project you are working on

Any game

### Describe the problem or limitation you are having in your project

The engine has the ability to inspect the tree of the running scene. But sometimes it is not convenient and you want to move around the scene from the editor in order to better understand what is happening. This is implemented in Unity. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

We need to remove the "Remote" and "Local" buttons from the Scene panel, but add an item, for example, "remote" to the scene selection panel. 
![Unnamed](https://user-images.githubusercontent.com/54563399/125188029-a818d380-e25c-11eb-9d46-94f2539cc5a5.png)
This tab will automatically open when the project starts. The user will be able to move around the scene in the editor. When the "remote" tab is open, the scene panel should also show remote nodes (this has already been implemented). 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

An image from the created additional viewport of the running application should be passed to the editor. Or, objects in the scene can be positioned based on the passed scene tree. It is desirable that this works when debugging remotely over the network.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is a very useful feature that will come in handy in any project, especially a large one. 

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the editor usability out of the box.

**Comment by KoBeWi** [comment] 2021-07-11 10:55
Duplicate of #1864

**Closed by KoBeWi** 2021-07-11 10:55 UTC
