### ISSUE TITLE
Allow full customization of 3D navigation controls (rotate, pan, zoom)

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot-proposals#6406] opened 2023-03-02 18:59 UTC
### Describe the project you are working on

Every project.

### Describe the problem or limitation you are having in your project

Godot doesn't provide a way to reproduce the desired 3d navigation control scheme.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Ability to define which key/mouse/key+mouse bindings are associated with each 3d navigation control (rotate,pan,zoom).
By allowing this, users will be able to reproduce any control scheme they need that godot currently doesn't offer. Godot only offer a few presets which is limited and doesn't offer ones that users might need. So being able to customize it would allow users to achieve the control schemes they need.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For each type of navigation (rotate/pan/zoom), select whether it is a single key, multiple keys, key+mouse button, or just mouse button.
Allow choice of keys, and allow choice of mouse button (mouse buttons 4 and 5 included).

There can still be presets to choose from(for popular schemes), but choosing a preset would just auto-fill these inputs.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No- currently, the only way is to modify godot's source code and build godot from source (I'm currently doing that to implement my control scheme).

### Is there a reason why this should be core and not an add-on in the asset library?

Improving the useability of the program should be a priority or at least an important issue and having it in the core would be a positive change for the program.

**Comment by Calinou** [comment] 2023-03-02 20:40
- Related to https://github.com/godotengine/godot-proposals/issues/3646.

**Comment by RobProductions** [comment] 2023-11-19 05:36
Hey @prominentdetail , I've started looking into implementing this and I think I have a solution that should satisfy everyone's needs, though there are still a few hurtles to overcome. I think your suggestion in the other proposal about full customization with preset options that retain the original behavior is definitely the way to go, so I wanted to add new settings that drive the navigation behavior. 

Godot's shortcut system is great for allowing any combination of inputs you desire, but without some major refactoring it seems to be limited to only keyboard input in the editor. Instead I opted to add these 2 settings (Orbit and Pan Mouse Button) where the navigation controls are normally located:
![image](https://github.com/godotengine/godot-proposals/assets/11141862/daa0fb68-1a3b-450a-92ba-bb4a5582dd99)

(For a real implementation, I will also add Zoom Mouse Button, but I'm just testing for now.) Then I added a new Navigation Scheme called "Custom" which is activated when you start changing any of the mouse buttons:
![image](https://github.com/godotengine/godot-proposals/assets/11141862/8d6f5644-f5a2-422d-bc8c-168e468fb648)

Conversely, when you select a Navigation Scheme (other than Custom) it now sets up the mouse buttons accordingly for the desired preset. This all works pretty well, but of course we still need modifier keys, so for that I went with shortcuts. I added them in and checked the input within the navigation code:
![image](https://github.com/godotengine/godot-proposals/assets/11141862/e44ecbb4-1d96-436c-8444-15b294e6fc46)

Since shortcuts allow for multiple keys and combined keys, this will also solve #3646 . These also get set by the Navigation Scheme. There was some confusion on how to handle schemes which don't use modifiers, but I think the simplest solution is to simply treat "no key assigned" as "always detect". For example, when you set it to use the "Godot" scheme, it will clear out the Viewport Orbit Modifier: 
![image](https://github.com/godotengine/godot-proposals/assets/11141862/0fa3613d-e576-407b-a78b-4bca300acdf4)

I've finally got all of that working properly with minimal adjustments to the editor code. The remaining problems to solve are:

1. Being able to set the Navigation Scheme to Custom when a shortcut is set that overrides it. This should be simple once I find where the shortcuts get applied.
2. Reordering the navigation logic so that other mouse functions like the box selection don't appear when you try to navigate under the new method. Should also be easy once I track that down. 
3. Making sure whatever settings combination you have in your editor_settings file (i.e. missing a shortcut due to manual edit) will still work if you have a preset selected. I think this is the case since it seems to run _settings_property_edited when I open Godot, but I'll just need to verify that. 

I'm confident all this stuff can be solved now, so it shouldn't be long before I have a PR ready. I am relatively new to the source code though so are there any other things I should watch out for? Any other things I should note while editing this section of code? I will try my best to keep within the conventions of the existing code and only introduce a few helper functions, though I think it'll still be a lot of code changed due to setting up all the presets properly. Hope that's okay. 

I do have one last concern which is that I'll be deleting the previous Orbit, Pan, and Zoom modifier settings since they'd be obsolete and moved into shortcuts instead. With this new way of doing it, I'm not sure if it would make much sense to try and port over users' old settings if that's even possible. Personally I don't see any problem ignoring previous settings so long as people don't expect forwards compatibility from a major release i.e. 4.3 or something. Their Navigation Scheme setting will carry over and apply to the new method, but let me know if this should be different.

All together, I think this will be a nice improvement mainly because it makes the navigation code more generic instead of having to deal with all the previous specific preset options within each mouse button. Now it can just check the settings and inputs, which are both fully customizable by the user. Let me know if that all looks good or if there are any other ideas/suggestions to make it better :) Thanks!

**Comment by prominentdetail** [comment] 2023-11-19 15:10
@RobProductions That looks excellent! I can't think of anything else- looks like you have a good handle on it. I don't have much experience with godot's code since I don't work in c++ . I had to just alter and rework one of the existing presets in order to get my preferred controls to work. Your implementation looks really nice, and I am looking forward to it! This is now my most anticipated feature and I hope it gets added/approved soon!

**Comment by RobProductions** [comment] 2023-11-20 05:15
Thanks for the kind words! It actually didn't take long to sort out the issues I mentioned above, so I wanted to mention how I went about it: 
1. There may have been another way to do this but I used the `_update_shortcut_events()` call to set the navigation scheme to custom when the user sets an override shortcut.
2. I was able to track down where the box selection/gizmo code was located and used the new prefs to interrupt it just like the old system.
3. I injected the preset detection into the setup steps for editor_node (the main scene for the Godot Editor) in order to solve two cases: 1. Where the user has loaded up Godot 4.3(?) for the first time and they have an existing Navigation Scheme but the mouse buttons/shortcuts are not yet set since they haven't gone through settings. 2. Where the user manually deletes their mouse buttons/shortcuts prefs in the editor_settings file but don't set the navigation scheme to custom. I believed this sort of error checking would be important but if it's too much to tack this on to the editor initialization steps I can remove it.

I'm glad that I was able to get this far but sadly I've run into some more roadblocks. For one, it seems that "key modifiers" for input events don't work the way I expected them to... [This reddit post](https://www.reddit.com/r/godot/comments/xf8354/problem_with_using_modifiers_with_inputeventkey/) explains it the best. Basically it needs the modifier to be pressed first in order for the event to trigger, and then if you let go of the modifier it still counts as pressed if you keep the "main key" held down. I tested this and it's true even on builds with GDScript, so it's a part of the core input system. In practice this means that you could be orbiting just fine but if you press a "modifier" key it won't cause pan to trigger because it needs the modifier to pressed first. The previous system didn't have this problem because it checked something like is_alt_pressed() and is_shift_pressed() individually.

I'm not sure if this is a bug or intended behavior; either way I obviously shouldn't be modifying the core to change this. I could perhaps solve this by breaking apart the Ref<Shortcut> and converting the modifiers to real keys and then checking each key individually, but that seemed too convoluted for now. Instead, the more direct approach was to simply utilize 2 seperate Shortcuts for the modifier keys like so:
![image](https://github.com/godotengine/godot-proposals/assets/11141862/8f0e34b9-f868-43cf-8c13-e4deee55c095)

It's not ideal but I hope this is a good intermediate solution until either the "bug" is fixed or some better way is found. Users may also want to be aware of this behavior so they use both shortcuts instead of modifiers. Lastly, this sadly limits the navigation keys to just 2; I can add a third if necessary but I haven't seen any schemes that need it yet so for now I think this is good for now.

For the other roadblock, it has to do with the order if detecting the different inputs. With the previous system using exact preset only, it was able to order the detection whichever way was needed per use case. But now there's an ordering problem if you consider the user has inputs like this:
![image](https://github.com/godotengine/godot-proposals/assets/11141862/634e28a5-00b6-437f-ad53-d31abedc15a5)

If the code is ordered to detect orbit first, you will never get panning because alt+mouse button already eats up the event. I could solve this by trying to figure out which type of navigation has more keys used and checking that first, or by trying to detect inputs for both and making sure one is not inputting when the other is. Hopefully that makes sense lol. But again that seemed way too convoluted to do and there's already a lot of other code changes that might be a lot to check through. So for now I opted to just check pan first since that typically uses more keys. Not perfect, but I believe it'll cover most cases.

As you can see, neither of these are really true roadblocks as I've already worked around them, but hopefully these solutions are acceptable and will work for now. I think this is what I'll try for the PR unless anyone has any suggestions or a specific need for things to be different, then in the future we can address these caveats with a different PR. It should also be easier to add new presets after this is in, so I'd love to see setups for Blender, Unity, etc. working with this. For now, I think all that's left is take these experiments and put it together for real in a branch, then I should have the PR ready in a few days :)

**Comment by RobProductions** [comment] 2023-11-24 23:57
Okay, I've finished up ensuring everything plays well together and submitted a PR here: https://github.com/godotengine/godot/pull/85331

@prominentdetail Feel free to try it out for yourself or express your support over at the pull request page :) thank you for the encouragement and let me know if you're able to recreate your Crocotile 3D workflow! (Or once it's merged if you wanna save some effort lol) I will keep an eye on the PR and make sure I can address any concerns/code changes the reviewers request. 

As I mentioned in the PR, I can see a few more enhancements to this coming in the future like proper mode ordering to safeguard against uncommon control schemes, more presets, and usage of mouse buttons 4 and 5. For now though I'm glad to finally get it out there and in the meantime I'll continue my search for more usability pain points to look into :)

**Closed** 2024-08-27 22:17 UTC
Labels: topic:editor, topic:3d

**Comment by lowagner** [comment] 2025-03-04 11:31
i think this landed in godot 4.4, but let me know if that's wrong.  

prior to 4.4, you could use the orbit modifier (in my case Alt) along with "Emulate 3-button mouse" to orbit around things by holding Alt and moving the trackpad.  if you plugged your laptop into a mouse, you could still use the middle mouse button (without a modifier) to orbit.

now i always need to use Alt to orbit, and that breaks the flow for me when i plug in a mouse and want to be able to use just the middle mouse button for orbiting.  so unfortunately this change doesn't provide "full customization" for me, as i can't return to the old way of doing it where there were two ways to orbit.  or if there is a way to do this and i'm just missing it, let me know.

(there's also some confusion with the migration, e.g., https://github.com/godotengine/godot/issues/103541)

**Comment by Zireael07** [comment] 2025-03-04 12:19
@lowagner I think the Alt issue was raised on the PR that did this

**Comment by prominentdetail** [comment] 2025-03-04 14:26
@lowagner Maybe you need to set the navigation scheme to Tablet/Trackpad to get it to function how you expect? https://github.com/godotengine/godot/pull/97985

**Comment by lowagner** [comment] 2025-03-05 01:39
hm, it seems like if i switch to Tablet/Trackpad, my Alt shortcut always comes back:

![Image](https://github.com/user-attachments/assets/4e097998-2cb5-487a-ab6f-4e7b6b26737b)

if i go into shortcuts and try to remove "Alt" as a keybinding for Orbit, it comes back.  i like using Alt with no mouse click (just mouse move), or middle mouse button without Alt (when i have a mouse plugged in), but i don't think that's possible.

**Comment by RobProductions** [comment] 2025-03-05 02:05
Yeah, sorry, it would have to be one or the other because those are essentially 2 different control schemes. There might be a way to add in customizable fallback behavior when no mouse button is pressed as its own setting but it seems a bit like overkill right now. 

If you're determined to keep both schemes, there might be a way to create an editor plugin that removes the orbit shortcut key while the mouse button is held and sets it again when unheld. We could also try to think of a more elegant update to the editor settings but honestly this use case seems a little niche... open to ideas though!

**Comment by lowagner** [comment] 2025-03-05 02:18
well, to be the devil's advocate "full customization" which removes the original way of doing things doesn't seem like full customization :).  i'm probably not the only one that takes their laptop on the go (and appreciates the 3-button emulation then) and then appreciates the simpler controls when plugging into a mouse setup.

but yeah not sure what a proposal would look like for this, but i will agree that having the keyboard shortcuts on one tab ("Shortcuts") and the navigation buttons on another ("General") is a bit hard to understand how things are affecting each other; it gives the illusion of independence.

maybe something like this, where we use "Mouse Movement" instead of "emulate 3-button mouse" to make it more generic.  when i started Godot i didn't even really understand what "emulate 3 button mouse" was supposed to mean, so something like this would be more helpful to me:

Orbit Method 1: Alt + Mouse Movement
Orbit Method 2: Middle Mouse
Pan Method: Shift + Mouse Movement
Zoom Method: Ctrl + Mouse Movement

and other setups might look like this:

Orbit Method 1: Alt + Middle Mouse Button
Orbit Method 2: None
Pan Method: Shift + Middle Mouse Button

etc.  you could set the shortcuts in this general tab instead of in the separate tab.

**Comment by RobProductions** [comment] 2025-03-05 03:35
The hotkeys are implemented as shortcuts because it was the easiest way to allow the user to customize them, and shortcuts can only appear in the `Shortcuts` tab because that's how the settings are designed. Unfortunately there's no way for it to work otherwise unless work was done to allow shortcuts to appear in the general settings, which is probably a big task in itself.

I understand the use case for wanting to switch between a trackpad and mouse, but to have multiple control schemes active complicates things a bit. For completeness going with your idea, I'd imagine it makes sense to add Pan Method 2 and Zoom Method 2, but that would result in another 6 shortcuts on top of the 6 already created, which would look like "Orbit Method 1 Modifier 1", "Orbit Method 1 Modifier 2", "Orbit Method 2 Modifier 1", etc. I like the idea of having multiple ways to orbit/pan/zoom just like in a game that allows multiple keys bound to the same action, but I can't imagine this being any easier for the user to navigate or understand. 

The other suggestion basically eliminates the 3 Button Mouse button entirely, and I'm not sure how well that will go over with people. Even though this method offers more granular control, there might be hesitation in just deleting a setting in favor of a new approach. I would agree that this is a neat idea for customizing the controls further, but it will make even less sense to legacy users even though the behavior is the same.

Here's my suggestion then: make a proposal issue and see if people mind the extra shortcut bloat and removal of the 3 button mouse setting in favor of the "per method" mouse button. If they don't, then I can definitely look into this if it will help the open up the controls further. Adding more shortcuts is easy, but reworking the 3 button mouse logic may take more time. Hope that helped and thank you for the feedback :)

**Comment by lowagner** [comment] 2025-03-05 04:40
sounds good, i think i improved the proposal from my earlier comment: https://github.com/godotengine/godot-proposals/issues/11915

i'm thinking a primary method "with a shortcut" and a secondary method (without).  that way we're not adding many more shortcuts to the other tab, which might be hard to keep track of which shortcut belongs with which method.
