### ISSUE TITLE
Interactable UI (control nodes) in 3D world

### ISSUE THREAD

**Issue by clara2g** [godotengine/godot-proposals#8679] opened 2023-12-17 12:42 UTC
### Describe the project you are working on

A 3D game where you have in-game touch-screens and computers that can display interactable UIs with control nodes (clickable buttons, text inputs, radio buttons, sliders, etc...). UI / HUDs integrated into 3D world space that you can interact with.

![Captura de pantalla de 2023-12-17 13-12-13](https://github.com/godotengine/godot-proposals/assets/7132501/e89bfd25-8895-42b3-b6ba-9a76d949d817)

![Captura de pantalla de 2023-12-17 13-14-30](https://github.com/godotengine/godot-proposals/assets/7132501/27db5108-47e5-403f-85a5-6388dc1c3e74)

### Describe the problem or limitation you are having in your project

UIs and HUDs can be displayed into 3D world through a material with ViewportTexture but they are not interactable (you can kind of achieve it but I'll explain in the workaround section).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A native way to display and interact UI control nodes in 3D world space that can be interacted with the mouse (or VR controllers).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Maybe a node specifically designed for containing UI control nodes that natively translates 3D world input events to events in the correct coordinates of the UI regardless of scale, rotation and other nuances that seem to affect possible workarounds (detailed next).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

UIs and HUDs can be displayed into 3D world through a material with ViewportTexture and to make them interactable  it is necessary to create a CollisionShape3D and translate mouse coordinates to replicate input events into the UI (but the code is definitively not a few lines and does not work in all conditions).

These tutorials implement this feature:

- [Diegetic UI in Godot 4 tutorial (In World UI)](https://www.youtube.com/watch?v=Hih8PD2xeMw)
- [Making 3D UI elements in Godot ](https://www.youtube.com/watch?v=qEjxZc6TAM8)
- And I think they are based in [this Godot 3 demo project](https://github.com/dueddel/godot-3d-ui-demo) 

But I'm having a hard time making it to work as smoothly as desired. They initially seem to work but in the end the result is far from perfect because the mouse position is not always perfectly transported and fails a lot to focus control element below the pointer and click where I'm trying to click. The difference seems to be bigger depending on the 3d world UI and player positions, rotations, and size/scale of elements among other problems I cannot figure.

### Is there a reason why this should be core and not an add-on in the asset library?

I think native interactable UIs in 3D world space could be very useful for a lot of projects. Not only for projects like mine that need in-game touch-screens (smartphones, futuristic computers, calculators, touch panels...) but I do believe VR projects would specially benefit a lot from this feature as they have an almost unavoidable need for world space UIs.

The UI system of Godot and its theming is very powerful and I think it would be very useful to have it natively and smoothly working in 3D world for 3D and XR projects.

Thank you and excuse me for my poor English.

**Comment by Zireael07** [comment] 2023-12-17 13:15
There's already an open discussion for this which is where it belongs since there's no code given

**Comment by AThousandShips** [comment] 2023-12-17 13:16
Duplicate of https://github.com/godotengine/godot-proposals/discussions/4093

**Closed by AThousandShips** 2023-12-17 13:16 UTC

**Comment by clara2g** [comment] 2023-12-17 15:53
> Closing in favor of:
> 
>     * [3D Control/Container #4093](https://github.com/godotengine/godot-proposals/discussions/4093)
> 
> 
> As indeed no clear idea for how to accomplish this was given, and a discussion is already open

Ops, I failed to find that proposal before posting mine, sorry for the inconvenience and thank you :)
