### ISSUE TITLE
Allow implicit property typing with new properties

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1880] opened 2020-11-23 22:04 UTC
**Describe the project you are working on:**
NetworkTest

**Describe the problem or limitation you are having in your project:**
Nothing but looking at the godot 4 properties makes me want to commit sudoku 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
currently I like the new properties the only issue with them is we have to do this..
`var property:
    set(value): return value #<-value?`

I suggest for a optional implicit value keyword when `(value)` is not supplied with autocompleate

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
#valid
var _property 
`var property:
    set(value): _property= value
    get: return _property
```

```
#also valid
var _property 
var property:
    set: _property = value
    get: return _property
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Its less typing so it would probably be used more then the current version and no

**Is there a reason why this should be core and not an add-on in the asset library?:**
properties are used quite often and having to type `(value)` for every one is an extra 7 characters and is honestly ugly in my opinion

**Comment by vnen** [comment] 2020-11-24 12:57
> properties are used quite often and having to type `(value)` for every one is an extra 7 characters and is honestly ugly in my opinion

"Ugly" is subjective. Code is read more times than it's written so in general I prefer to improve readability even if you have to type a bit more.

**Comment by KoBeWi** [comment] 2020-11-24 16:20
Doesn't `set(v): _property = v` work? It's shorter.

**Comment by Shadowblitz16** [comment] 2020-11-24 20:12
@vnen thats why the value keyword would be highlighted in that case 

@KoBeWi 
I mean it is shorter but I still think it looks ugly.
it misaligns the setter and getter which triggers my OCD really bad

Also if lambdas ever get added it would look more natural.
```
var _property 
var property:
    set: =>_property=value
    get: =>_property
```

opposed to

```
var _property 
var property:
    set(value): =>_property=value
    get: =>_property
```

It more of a preference issue and I think it should be optional

**Comment by akien-mga** [comment] 2020-11-25 10:42
Godot and GDScript are explicit by design, I'm against this proposal.

Giving a name to the parameter is good. Whether you think it's ugly is not relevant, you have hundreds of functions with named parameters too and they don't seem to be a problem.

**Comment by katoneko** [comment] 2020-11-25 11:00
Also see #844 and the number of thumbs down on [this comment](https://github.com/godotengine/godot-proposals/issues/844#issuecomment-629872957) in particular which gives a pretty good idea that people voted against this. So is there any point in repeating the discussion, knowing it would meet the same conclusion?

**Comment by Shadowblitz16** [comment] 2020-11-25 18:25
Why is having the option a bad thing?
It would be completely optional

**Comment by aaronfranke** [comment] 2021-01-10 08:47
> Also see #844 and the number of thumbs down on [this comment](https://github.com/godotengine/godot-proposals/issues/844#issuecomment-629872957) in particular

Haha, yes :) but first see [this comment](https://github.com/godotengine/godot-proposals/issues/844#issuecomment-629732780).

I still think this can be a good idea, it's what C# does and it works fine there. To me it's clear enough.

However, this won't happen due to the amount of people against this, so I'm closing this. Besides, the worst that could happen is that the code is a bit more explicit than necessary... which isn't all that bad.

**Closed by aaronfranke** 2021-01-10 08:47 UTC
Labels: topic:gdscript
