### ISSUE TITLE
System Menu Bar

### ISSUE THREAD

**Issue by gro-david** [godotengine/godot-proposals#8821] opened 2024-01-07 09:29 UTC
### Describe the project you are working on

Animation for a school project

### Describe the problem or limitation you are having in your project

Nothing really.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This would mean a changing the builtin menu bar (the `Scene | Project | Debug | Editor | Help` menu) to use a system wide implementation. For example on KDE Plasma Godot could use the 'Global Menu'  Plasma widget.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just moving the menu out of the editor and letting the desktop enviroment/window manager mange it.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Nope.

### Is there a reason why this should be core and not an add-on in the asset library?

I do not think this could even be solved with a plugin.

**Comment by Mickeon** [comment] 2024-01-07 11:25
It is very difficult to envision this without any mock-up

**Comment by KoBeWi** [comment] 2024-01-07 11:51
It's already implemented on MacOS.

**Comment by AThousandShips** [comment] 2024-01-07 12:05
Duplicate of https://github.com/godotengine/godot-proposals/issues/8669

**Closed by AThousandShips** 2024-01-07 12:05 UTC
