### ISSUE TITLE
Method to disable all children on a parent node

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#1847] opened 2020-11-16 22:31 UTC
**Describe the project you are working on:**
Platformer

**Describe the problem or limitation you are having in your project:**
I've got some fairly complex kineticbody2ds (collision boxes, multiple timers, multiple area2d, ray trace etc. etc.)

I want to disable them when they're not on screen. So in my code I did the following:
1. set physics off
2. set process off
3. set visible to false
4. set all collision boxes off

But my node is still alive and the timers are still running! so I've now to got to disable those.  I'd have assumed setting process to false would stop timers (and more). Or is this not stopping a timer a bug? either way, I've got more code enabling/disabling items in my game than anything and a simple parent disable option would be so much easier and less error prone.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Provide a means to simply disable a node and all it's children will stop/disable themselves too. 

**Is there a reason why this should be core and not an add-on in the asset library?:**
Enabling/disabling items is a fairly common thing, but once you start having complex nodes, it becomes pretty much impossible.

**Comment by Calinou** [comment] 2020-11-16 22:54
See #1835. I think it would be better to reply with a comment there.

**Comment by chucklepie** [comment] 2020-11-16 22:58
thanks. I never saw that. I do search before I post :)

**Comment by KoBeWi** [comment] 2020-11-16 23:10
> But my node is still alive and the timers are still running! so I've now to got to disable those. I'd have assumed setting process to false would stop timers (and more). Or is this not stopping a timer a bug?

Built-in nodes like Timers or AnimationPlayers use internal process, so you need to call `set_internal_process(false)`. You can use `propagate_call()` to call a method in every child.

Also this is pretty much duplicate of #1835, so closing.

**Closed by KoBeWi** 2020-11-16 23:10 UTC
Labels: topic:core

**Comment by chucklepie** [comment] 2020-11-16 23:26
I'll try, thanks.

Any chance the docs could be updated because I've just read it, and it just
says it's for internal use and advanced, with no actual detail saying what
it does...

**Comment by KoBeWi** [comment] 2020-11-16 23:36
The description clearly says what the method does, maybe you look at outdated docs or something.

> Enables or disabled internal processing for this node. Internal processing happens in isolation from the normal _process() calls and is used by some nodes internally to guarantee proper functioning even if the node is paused or processing is disabled for scripting (set_process()). Only useful for advanced uses to manipulate built-in nodes' behaviour.

If you think some part of it is not clear enough, open an issue on the [main repository](https://github.com/godotengine/godot).

**Comment by chucklepie** [comment] 2020-11-17 08:26
@KoBeWi that may make sense to you being an engine developer, but for standard users it means nothing. You say it will stop timers, but what about collision polygons or screen notifiers, will those be disabled and no events raised, etc?
