### ISSUE TITLE
Allow bypassing the new SubViewport Scaling3D system, for sharp pixel edges

### ISSUE THREAD

**Issue by PhantasmaCora** [godotengine/godot-proposals#6358] opened 2023-02-26 01:53 UTC
### Describe the project you are working on

A 3D-rendered game with a deliberately smaller rendering resolution as a stylistic choice.

### Describe the problem or limitation you are having in your project

In 3.x, I could do this quite simply by using a Viewport in a ViewportContainer with Stretch Scale enabled.

However, in 4.0 (Release Candidate 5), scaled-up SubViewport renders have a slight blurring between adjacent pixels, most visible with pixels of very different colors. This is undesirable for the visual style I am aiming for.

I am uncertain, but it appears this may be a result of the new Scaling3D settings for SubViewports, which allow selecting either a Bilinear or FSR scaling algorithm, but do not give the option to skip scaling algorithm and instead scale by integer amounts with hard pixel edges.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an option to the Scaling3D settings which disables scaling algorithms, as in the 3.x Viewport.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A "Disabled" option in the scaling_3d_mode attribute of the SubViewport node, which gives hard-edge results similar to those found in 3.x

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As far as I can tell, the workaround would require recreating the SubViewport code as a custom node, or something similar.

### Is there a reason why this should be core and not an add-on in the asset library?

Newly introduced features, if not essential to the core of the engine, should generally be optional, as opposed to forcing users to use them. The scaling algorithms implemented may be useful for realistic rendering, but they do not work as well for stylized applications (which are a relatively common choice for indie projects like much of Godot's userbase).

**Comment by Calinou** [comment] 2023-02-26 02:53
- Duplicate of https://github.com/godotengine/godot-proposals/issues/4697.

For SubViewports that are stretched, filtering is governed by the `texture_filter` property that is part of any CanvasItem.

**Closed by Calinou** 2023-02-26 02:53 UTC
