### ISSUE TITLE
Add a flag to allow `instance` and `load` to run over several frames

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot-proposals#4157] opened 2022-03-04 13:02 UTC
### Describe the project you are working on

A project which requires a large world where chunks of data are loaded.

### Describe the problem or limitation you are having in your project

The problem is that when loading in many items in chunks, there can be large and hard to track down delays in the `idle_time` or `process_time` of the Godot system.

I've tracked this down to two areas:

1. Loading a file or resource
2. Instancing a resource

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a functionality to `instance` or to `load` where we can specify the number of frames to allow that action to take would be very helpful and remove a lot of clutter from the developers side of the game.

At the moment I have to run my own custom loading system, which is OK but it's certainly a barrier for newbies.

When it comes to `instance` however there can easily be bugs with loading time, as some scenes take quite some time to instance, and usually happen at the same time.

When trying to instance scenes in threads, I very often run into global lockups and crashes to desktop.

Basically my point: Developers should not be forced to use explicitly use threads, having a way to do this in-engine would be super useful.

### `load_slowly`
The following would load the file in 5 iterative frames

```gdscript
var my_var = yield(load_slowly("some_resource", 5), "completed")
```

### `instance_slowly`
The following would instance the file in 5 iterative frames

```gdscript
var my_var = yield(instance_slowly("some_resource", 5), "completed")
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not with a few lines of script, my file loaders are usually more than 100 lines and with many areas that errors can sneak through.

They also are not super stable, because the engine often locks up for weird reasons which seem extremely hard to debug (basically no error logging when crashing in this way).

### Is there a reason why this should be core and not an add-on in the asset library?

This is what I feel to be the most lacking of all parts of game development I've seen in Godot so far 😞

**Comment by KoBeWi** [comment] 2022-03-04 13:14
> At the moment I have to run my own custom loading system, which is OK but it's certainly a barrier for newbies.

Newbies won't come into this problem, because it only happens in big projects.
Also threaded loading got better support in 4.0.
Also also, did you see `load_interactive` method?

**Comment by tavurth** [comment] 2022-03-04 13:24
> @KoBeWi Newbies won't come into this problem, because it only happens in big projects.

By newbie I don't mean new to programming, or game development, I mean new to Godot.

I think that's a shame, because "newbies" would certainly like to create big projects and I know a many who are capable. 
As soon as you start running into these types of issues (especially the crashes) it can easily create frustration and abandonment of Godot for Unity or Unreal where those tools do exist.

> Also threaded loading got better support in 4.0.

That's great, maybe we can backport it. Perhaps you have a link to a merged PR?

> Also also, did you see `load_interactive` method?

I did, wrote a well error checked wrapper around it, then finally discovered it was the cause of at least 50% of my crashes to desktop.

Unfortunately I had to abandon it to use `ResourceLoader.load()` instead, which at least `caches` the files compared to the default `load` which just spams cycles into the SSD.

**Comment by KoBeWi** [comment] 2022-03-04 13:52
> I think that's a shame, because "newbies" would certainly like to create big projects and I know a many who are capable.

Well, to create a big project you need a sufficient knowledge about the engine. Knowing how to load big number of assets properly is part of that.

> Perhaps you have a link to a merged PR?

https://github.com/godotengine/godot/pull/36640
It can't be backported, because it relies on core changes.

> I did, wrote a well error checked wrapper around it, then finally discovered it was the cause of at least 50% of my crashes to desktop.

Yeah, you can't use it in threads. The usage is that you poll it inside `process()` and it loads a resource step by step, so it doesn't freeze until resource is fully reloaded. In Godot 3.x you can't do much better unfortunately.

**Comment by tavurth** [comment] 2022-03-04 13:55
> In Godot 3.x you can't do much better unfortunately.

Exactly my point, it would be nice to have a `load_slowly` function to handle this for the user..

**Comment by Calinou** [comment] 2022-05-28 10:44
Duplicate of https://github.com/godotengine/godot-proposals/issues/1801.

**Closed by Calinou** 2022-05-28 10:44 UTC
Labels: topic:core, archived
