### ISSUE TITLE
SetCellRange

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#1688] opened 2020-10-18 20:17 UTC
**Describe the project you are working on:**
Custom tool for managing tilemaps.

**Describe the problem or limitation you are having in your project:**
The only way to put several tiles with the same value is SetCell, SetCell is the only way to print tiles.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add SetCellRange so that large areas can be placed, for example, to fill a 30x30 tile area with a water tile, SetCellRange would do it with a single call.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
It is very simple and I think it needs no explanation.
SetCellRange( tileID, originX, originY, width, height, flipH... etc... )
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes, it can be fixed but adding this mode will make things easier for developers.
**Is there a reason why this should be core and not an add-on in the asset library?:**
From the core it will always be faster.

**Comment by Calinou** [comment] 2020-10-18 21:04
Duplicate of https://github.com/godotengine/godot-proposals/issues/1538.

**Closed by Calinou** 2020-10-18 21:04 UTC
