### ISSUE TITLE
Use macos and ios names for scons platforms

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot-proposals#4828] opened 2022-07-06 21:57 UTC
### Describe the project you are working on

custom godot modules for ik and voip

### Describe the problem or limitation you are having in your project

I want a stable name to compare against env["platform"].

Right now, I am afraid to use "osx" or "iphone" because I might want to build for ipad in the future, and macOS now has versions 11 and 12.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Apple officially changed their operating systems to be named "macOS" and "iOS" respectively. I think we should use "macos" and "ios" as lowercase versions of these.

In the past, the godot platform names were intended to follow the xcode platforms "iPhoneOS.platform" and "MacOSX.platform", but these are only named such for legacy reasons. I think Godot should use 4.x as an opportunity to break compatibility.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Should be as simple as renaming platforms/osx -> platforms/macos and platforms/iphone -> platforms/ios

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, the names will be hardcoded after 4.x is released and cannot be changed due to compatibility breakage

### Is there a reason why this should be core and not an add-on in the asset library?

these are core platforms

**Comment by jordo** [comment] 2022-07-07 02:53
tvOS as well.

**Comment by akien-mga** [comment] 2022-07-07 05:37
That's a duplicate of https://github.com/godotengine/godot-proposals/issues/1161, see discussion there. But I guess it doesn't hurt to reassess 2 years later.

**Comment by akien-mga** [comment] 2022-09-06 14:02
Fixed by https://github.com/godotengine/godot/pull/63225.

**Closed by akien-mga** 2022-09-06 14:02 UTC
Labels: topic:core, topic:buildsystem, breaks compat
