### ISSUE TITLE
Add more snapping options in Editor Viewport

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot-proposals#4367] opened 2022-04-08 19:01 UTC
### Describe the project you are working on

Any 3D Game (possibly 2D too)

### Describe the problem or limitation you are having in your project

To precisely align objects in 3D space currently we only have the option to snap rotation, translation and scale by a fixed increment, which can be set in the snap options. There is also an option to snap objects to the scene floor, which requires the object and the floor to have a collision shape.

This is fine in many cases. However, if you don't use a strict grid-like placement of your objects and really want to align some objects precisely relative to each other, more snapping options would be a huge life-saver.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

We could take a look at Blender as a reference, which has great snapping options. You can have relative/absolute grid snap, as well as snap rotation, scale and translation to vertices, faces, edges, center etc.

![grafik](https://user-images.githubusercontent.com/7927471/162502136-4123f277-1bcd-41b9-a210-9db40f8eba21.png)

While not all of those options might make sense in Godot, where we work with objects instead of individual vertices, faces, edges, some more flexibility for snapping would be greatly appreciated, to place and align assets in the scene. At least snapping translation to the nearest face of another object or object origin or bounding box would improve usability of snap greatly.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't have the required programming skills to work on this myself.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a core feature of the editor viewport.

**Comment by Calinou** [comment] 2022-04-08 20:04
Duplicate of https://github.com/godotengine/godot-proposals/issues/755.

**Closed by Calinou** 2022-04-08 20:04 UTC
