### ISSUE TITLE
Add feature to show 3D preview and visual script in different windows / multi-window . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#2888] opened 2021-06-19 07:01 UTC
### Describe the project you are working on
A Tomb raider game, with barbarians <3

### Describe the problem or limitation you are having in your project
I have a new 8K monitor, and I'd like to be able to use it, to see the visual script canvas, and see the 3D preview on another screen . . . But, right now there 2D, 3D, and Visual script canvas, is like the same window . . ie., I can't separate them, and see the code, or visual script canvas on the ONE screen, when I click on 3D, it's the same window, that changes . . . 

Was hoping you'd make it so, one could have code on one screen, and 3D, less important for 2D that runs faster, preview, in a different window . . Not sure this is to be supported, in new multi-window system, bec. 2D, 3D, script are, sort of the SAME window, or ' dock ' . . ??

It'd be a big help, also allow me to see more script, when zoomed out, with amazing looks, etc . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Allow, sort of allow, to have SCRIPT in one window, and 3D preview, in another window . . . Right now, the 3D preview world, one is forced to use it, in the SAME window, ie. it'd run really slow for 3D preview, but fast, for written code, or script canvas, for me, etc . . Idea is might have script canvas, on one screen, in 8K, with a good zoom level <3 And, then have the 3D preview world, run on a 1080p screen, or so . . Thx, amazing job already, etc . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, like above, make sure one can have code on one monitor, and 3D preview on another, without being forced to switch between either, on the SAME monitor, thx . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't do this, am total beginner, still learning basic navigation AI :OO 

### Is there a reason why this should be core and not an add-on in the asset library?
Well, it's an idea . . .

Again, Godot 4 is looking amazing, really happy with everything, atm . . But, sigh, know you're working too hard <3 the wait, is quite brutal :((( . . For me, it's 9.8 / 10 already, hoping for a bit more, thx <3 . . .

**Comment by Calinou** [comment] 2021-06-19 07:05
Duplicate of https://github.com/godotengine/godot-proposals/issues/28.

**Closed by Calinou** 2021-06-19 07:05 UTC
