### ISSUE TITLE
Allow using a custom Viewport as a basis for Movie Maker mode

### ISSUE THREAD

**Issue by Bethleem** [godotengine/godot-proposals#5809] opened 2022-11-18 17:04 UTC
### Describe the project you are working on

Video capture of cinematics.

### Describe the problem or limitation you are having in your project

The max screen resolution is lower than the optimal target resolution.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In 3.5 branch I made an animation frame capturer that, in order to avoide the screen resolution limitations, rendered the contet into a customizable viewport anf then capture this viewport data and save it as png files.
I tried it in godot 4 and just had to make some adjustments for getting the viewport data and save it to disk but it still works. So, my suggestion is, can you made movie-writer to render into a customizable viewport than can be sized bigger than the screen resolution? I mean, I can do it manually frame by frame so it would be cool to have it implemented in the movie-writer.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Movie-writer will create a size customizable viewport and the render the scene in it, so screen resolution limitations will be avoided.
For the frame capture it will use get_texture() in the SubViewport, then convert into Image with get_image() and saved to disk with save_png(), or passed to the video muxer.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, it works easily with png format, but will be cool to have it implemented to work with video in movie-writer.

### Is there a reason why this should be core and not an add-on in the asset library?

Well, if movie-writer is core, then this should be core because is an enhacement.

**Comment by Calinou** [comment] 2022-11-18 18:52
Duplicate of https://github.com/godotengine/godot-proposals/issues/5790.

Note that you can already resize the window to be larger than the screen, but this requires third-party tools that may not be readily available on Windows or macOS.

**Comment by Calinou** [comment] 2022-11-19 23:01
It turns out this is already feasible; it's just not documented. I've opened a pull request to document this: https://github.com/godotengine/godot-docs/pull/6398

Closing, as the feature is already implemented so to speak.

**Closed by Calinou** 2022-11-19 23:01 UTC
Labels: topic:rendering
