### ISSUE TITLE
Please consider adding a way to get output from OS.execute real-time

### ISSUE THREAD

**Issue by iMartyn** [godotengine/godot-proposals#1531] opened 2020-09-18 13:33 UTC
**Describe the project you are working on:**
A "game" that deals a lot with videos downloaded from the internet, youtube etc.

**Describe the problem or limitation you are having in your project:**
I need to use youtube-dl to download videos and then ffmpeg to convert them to a format that is usable in godot.  Both of these tools take time to run and I need to give feedback to the user.  They both support outputting progress but I cannot give that progress to the user without creating a separate app in a different language and doing REST shenanigans just to do this.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Give me a line-by-line output and I can parse it and update progress bars etc.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

```
(pseudo-code)
app = OS.execute("ffmpeg",["various","annoying","options"],false,realtimeOutput)
while app.hasOutput && !app.hasTerminated:
  if app.hasOutput:
    for line in realtimeOutput:
      # some processing here.
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It really can't.  The standard answer is to create a separate app in a different language and have a rest interface to call the command.... :(

**Is there a reason why this should be core and not an add-on in the asset library?:**
Pretty much every language has a way of doing this?

[edit: missed a closing bracket]

**Comment by Calinou** [comment] 2020-09-18 13:41
Duplicate of https://github.com/godotengine/godot-proposals/issues/216.

**Closed by Calinou** 2020-09-18 13:41 UTC
Labels: topic:core
