### ISSUE TITLE
Add a Scene tree dock context menu option to swap an instanced scene with another

### ISSUE THREAD

**Issue by circuitbone** [godotengine/godot-proposals#5503] opened 2022-09-27 23:49 UTC
### Describe the project you are working on

I want to swap a scene or change the reference that has an object for another.

Akin to unity `swap prefab` feature.

<img width="393" alt="Screen Shot 2022-09-28 at 9 39 10 am" src="https://user-images.githubusercontent.com/47682220/192656426-80ff7826-1959-4f23-8d31-84f234bb9b21.png">

### Describe the problem or limitation you are having in your project

Is it possible to swap a scene now within the limitations of 3.5 as it stands now

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A button changes the reference of the currently selected scene

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change scene reference pointer

### If this enhancement will not be used often, can it be worked around with a few lines of script?

A script that has a button to perform the action would be acceptable.

### Is there a reason why this should be core and not an add-on in the asset library?

recommended for core product

**Comment by Calinou** [comment] 2022-09-28 01:17
Can you describe a concrete use case for swapping one scene for another?

You can already remove an instanced scene and instance another scene in place. It requires one more click than the proposed solution, but it doesn't require making the Scene tree dock context menu even longer. This context menu is already very long as it is :slightly_smiling_face:

**Comment by circuitbone** [comment] 2022-09-28 01:20
It's a common case for when building complex sets of objects to be used as instances which is eventually called with code in the game.

**Comment by Calinou** [comment] 2022-09-28 06:16
> It's a common case for when building complex sets of objects to be used as instances which is eventually called with code in the game.

Have you looked at using InstancePlaceholder (right-click > **Load As Placeholder**)? This is intended to be used for speeding up the loading of large scenes.

**Comment by Zireael07** [comment] 2022-09-28 06:52
@Calinou I think it's a dupe of another proposal, but as I can't find it, I'll cross-comment here: my use case is several planet types in a space game. Currently if I remove one instanced scene and instance another one, I lose the exported values as well as have to type in the transform again.

Load as Placeholder is poorly documented, too poorly to use in a large project because I don't want to break things.

**Comment by QbieShay** [comment] 2022-09-28 07:53
In that case load as placeholder  should be better documented

**Comment by KoBeWi** [comment] 2022-09-28 12:41
I needed it a couple of times, but you can easily swap the instances by modifying the tscn file.

**Comment by Zireael07** [comment] 2022-09-28 12:48
That might work but risks bricking your entire tscn if you're not careful

**Comment by MikeFP** [comment] 2022-09-29 12:34
> Currently if I remove one instanced scene and instance another one, I lose the exported values as well as have to type in the transform again.

That's the main reason why the current behavior (remove + add) is a little inefficient. Even more so in 2D, where you have to move the Node so it occupies the previous place in the tree, since render order is a thing.

My use case for it: Sometimes I have to build a new scene by duplicating a template scene, but replace some Nodes by their specialized version, which are a derived scene with some tweaks, which may include extended Scripts or new Nodes.

**Comment by KoBeWi** [comment] 2022-11-08 00:35
This is duplicate of #4991 actually.

**Closed by KoBeWi** 2022-11-08 00:35 UTC
Labels: topic:editor
