### ISSUE TITLE
Ability to copy parameters path from shaders and animation trees

### ISSUE THREAD

**Issue by IllusiveS** [godotengine/godot-proposals#106] opened 2019-09-26 18:03 UTC
**Describe the project you are working on:**
Currently i am developing a few small game-jam like projects

**Describe how this feature / enhancement will help your project:**
Not having to transcribe the values of paths will save some time and help avoid bugs when mistyping

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
I hover mouse over the property with shader parameter
![image](https://user-images.githubusercontent.com/7921065/65712827-2dd38b00-e098-11e9-8ed2-d5209d415083.png)
and now i want to press or do something that will save property path to clipboard so that i can easily copy it into the script

**Describe implementation detail for your proposal (in code), if possible:**
No clue, if someone could direct me somewhere i could do it myself probably, but right now i don't know much about godot to propose code

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not that i know of, if it is, i would love to make a plugin for it then

**Is there a reason why this should be core and not an add-on in the asset library?:**
Do not know if it is possible to do that, it might be because some inspector fields can tell the difference between right and left click

**Comment by clayjohn** [comment] 2019-09-26 18:22
You don't need to the full property path to set shader uniforms. You just need the name of the uniform itself, no need to hover even. 

In GDScript
```
myMaterial.set_shader_param("Slowmo", slowmo_value)
```

**Comment by IllusiveS** [comment] 2019-09-27 15:11
Perhaps shader was not the best example, but parameter copying from animation tree would be useful

**Comment by rcorre** [comment] 2020-06-08 13:30
I'm working on this now, finally got annoyed after enough typos transcribing `AnimationTree` paths :grin:

**Comment by Calinou** [comment] 2021-06-22 13:37
Duplicate of https://github.com/godotengine/godot-proposals/issues/655 (both use EditorInspector).

**Closed by Calinou** 2021-06-22 13:37 UTC
Labels: topic:editor
