### ISSUE TITLE
Decals - Normal strength

### ISSUE THREAD

**Issue by ettiSurreal** [godotengine/godot-proposals#6003] opened 2022-12-27 03:29 UTC
### Describe the project you are working on

Testing different features.

### Describe the problem or limitation you are having in your project

I was trying to create a ground crack effect using the decal system, but found the normal of the decal to be too weak.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a "Normal Scale" slider to properties in the Decal node, which would affect the strength of the decal's normal, capped between -16 and 16. Exactly the same as in both Material3D classes. This would also allow for setting the decal's normal to a negative scale, giving an easy way to invert it.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A `Normal Scale` property would be available in the `Decal` node, which would allow changing the strength of the normal texture, also letting the user easily invert it.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can edit the texture to make the normal stronger, but only to a certain degree which might not be enough in some cases.

### Is there a reason why this should be core and not an add-on in the asset library?

Decal is a built-in class.

**Comment by KoBeWi** [comment] 2022-12-27 10:13
Duplicate of #3326

**Closed by KoBeWi** 2022-12-27 10:13 UTC
