### ISSUE TITLE
editor settings > quit confirmation, it's gone

### ISSUE THREAD

**Issue by konquerprojekt** [godotengine/godot-proposals#6190] opened 2023-01-28 10:22 UTC
### Describe the project you are working on

back this feature please.

### Describe the problem or limitation you are having in your project

regression

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

work same in godot 3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

work same in godot 3

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

yes

**Comment by Zireael07** [comment] 2023-01-28 12:31
It's by design as "most modern software does not have confirmation on quit anymore" (and I can tell you that yes, most software does not - there is save on quit automatically so you never lose data when you quit)

**Comment by Calinou** [comment] 2023-01-28 13:28
This is done by design: https://github.com/godotengine/godot/pull/32321

Closing in favor of https://github.com/godotengine/godot-proposals/issues/6100.

**Closed by Calinou** 2023-01-28 13:28 UTC
