### ISSUE TITLE
Allow skipping of default parameters using named parameters or empty parameters (like C#)

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#1676] opened 2020-10-16 14:21 UTC
**Describe the problem or limitation you are having in your project:**
Pretend you have a method like this:

```
func start_explosion(
		secs_alive=1.0,
		gravity=55,
                some_count=5
		showdebug=false):
```

Currently Godot only supports trailing default values. If you want to only override 'some_count', you have to override all of them, e.g.
```start_explosion(1.0,55,1000000)```

You then lose the ability to use the functions built-in default values. What would be better would be named or optional parameters, e.g.

```start_explosion(some_count=100000)```
```start_explosion(,,,100000)```

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
As above

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
As above

**Is there a reason why this should be core and not an add-on in the asset library?:**
Optional parameters are a valuable feature of modern languages and a time-saver. Otherwise, you have to resort to using dictionaries and other methods which will be more complex to implement and hinder performance in the same way.

**Comment by Calinou** [comment] 2020-10-16 17:19
Duplicate of https://github.com/godotengine/godot-proposals/issues/1034.

**Closed by Calinou** 2020-10-16 17:19 UTC
