### ISSUE TITLE
allow passing shape resource to RayCast2D and RayCast3D

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#709] opened 2020-04-14 20:10 UTC
**Describe the project you are working on:**
spaceship game

**Describe the problem or limitation you are having in your project:**
I'm trying to make a beam weapon that stops when it hits a object
currently I am using two RayCast2D's but these things are 1 dimensional so they don't cover the whole width of my beam.
this allows things to pass through in the gaps between the raycasts

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
basicly RayCast2D and RayCast3D nodes would allow passing a shape resource.
this would change the ray from a 1 dimensional ray to a 2 or 3 dimensional ray

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![image](https://user-images.githubusercontent.com/2453707/79269256-ffa97300-7e50-11ea-89b6-11231a1db317.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
idk how often this would be used but I would assume or something like what I want it for it would be used alot.

also I don't think it can be actually done or at least not in a easy way.

**Is there a reason why this should be core and not an add-on in the asset library?:**
other game engines like unity has it

**Comment by bojidar-bg** [comment] 2020-04-14 20:37
Duplicate of #72?

**Comment by Xrayez** [comment] 2020-04-14 20:45
> Duplicate of #72?

Mostly yes, see my proposed implementation at https://github.com/godotengine/godot-proposals/issues/72#issuecomment-587981106.

**Comment by Xrayez** [comment] 2020-04-14 22:11
I have created my own proposal regarding this, because I have some specific implementation details which might be worth discussing separately: #710.

**Comment by Calinou** [comment] 2020-04-15 12:24
Duplicate of #72 and #710.

**Closed by Calinou** 2020-04-15 12:24 UTC
