### ISSUE TITLE
Add `server` RPC sync mode

### ISSUE THREAD

**Issue by addmix** [godotengine/godot-proposals#5360] opened 2022-09-07 00:12 UTC
### Describe the project you are working on

A server-authoritative multiplayer FPS.

### Describe the problem or limitation you are having in your project

A node's authority is set to it's controlling client, but some functions need to be accessible to RPC for the server to return the current game state. For security, you must limit these RPC calls to those which originate from the host/server. Currently to ensure game state updates only originate from the host/server, you must include
```
if get_tree().get_multiplayer().get_remote_sender_id() != 1:
	return
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A `server` sync mode annotation would only allow RPCs originating from the server to be accepted, removing repetitive code from projects and easing the process of net code development.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Only allowing RPCs from the host/server or in other words, whichever network peer has the ID of 1.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This enhancement would be used in most multiplayer projects, while a workaround is simple, the dozens, hundreds, or even thousands of applications of this workaround would become tedious and difficult to maintain.

### Is there a reason why this should be core and not an add-on in the asset library?

This extends the core functionality of the RPC tag annotation, and thus cannot be implemented as an addon.

**Comment by Calinou** [comment] 2022-09-07 00:50
Duplicate of https://github.com/godotengine/godot-proposals/issues/4592.

**Closed by Calinou** 2022-09-07 00:50 UTC
Labels: topic:network
