### ISSUE TITLE
Make angle control points for Path have a different look than the control points.

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot-proposals#1783] opened 2020-11-06 11:55 UTC
**Describe the project you are working on:**
Generating rivers using splines

**Describe the problem or limitation you are having in your project:**
It's difficult to see which points are control points and which are angle controls

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Make the angle points look different than the control points. They look different for Path2D where the angle controls are smaller than the control points.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Current:
![image](https://user-images.githubusercontent.com/4955051/98363110-59a89a80-2026-11eb-9070-6dda5334d17f.png)

Suggested, angle points at 50% oppacity:
![image](https://user-images.githubusercontent.com/4955051/98363144-66c58980-2026-11eb-820c-0395ec16d8f0.png)

Path2D for comparison where it's easy to see what is what:
![image](https://user-images.githubusercontent.com/4955051/98363267-996f8200-2026-11eb-8670-7c449ffa6166.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This would be used often.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is general use of the Path node, not a specific tool.

**Comment by KoBeWi** [comment] 2020-11-06 12:54
Duplicate of #1246

**Closed by KoBeWi** 2020-11-06 12:54 UTC
