### ISSUE TITLE
Vector2/2i single argument constructor

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot-proposals#7372] opened 2023-07-25 20:25 UTC
### Describe the project you are working on

Multiple Projects

### Describe the problem or limitation you are having in your project

Currently there is no single argument constructor for `Vector2 `and `Vector2i `as far as in Godot 4.1.1/ 4.0.x and 3.X
If i am wrong or there is any reason for not having single argument constructor, then we can close the proposal.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Need a single argument constructor for ease of use. The value will be propagated to both the x and y values.
e.g., vector2(2.0) will create a vector with both x and y having value 2.0.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Example of usage
```gdscript
   # creates vector2(2.0, 2.0)
    var my_vector := Vector2(2.0)
   
   # creates vector2i (4, 4)
    var my_int_vector := Vector2i(4)
```
This will help in quick creation of vector.

I am unsure there may be a reason for not having single argument constructor. If there is any reason for not creating the single argument constructor, then we can drop this proposal, or else it will help.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I am not sure about others, but while creating a simple game I have to use Vector2(2.0, 2.0)  couple of times. 
Fairly, I am assuming others will be doing it too.

### Is there a reason why this should be core and not an add-on in the asset library?

It is core type change request

**Comment by AThousandShips** [comment] 2023-07-25 21:03
Duplicate of: #4822

**Closed by AThousandShips** 2023-07-25 21:03 UTC
