### ISSUE TITLE
example for GDExtension in C or Documentation for bindings devs

### ISSUE THREAD

**Issue by the-ssd** [godotengine/godot-proposals#6277] opened 2023-02-12 09:42 UTC
### Describe the project you are working on

Compiler for gdscript

### Describe the problem or limitation you are having in your project

I want to add GDExtension support but it is hard to understand how GDExtension  works

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Documentation or example in C for GDExtension

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Without example or documentation it is hard to understand how it suppose to look like

**Comment by Calinou** [comment] 2023-02-12 18:38
Duplicate of https://github.com/godotengine/godot-docs/issues/5618. In the future, please submit documentation requests to godot-docs after searching for duplicates there, not godot-proposals.

**Closed by Calinou** 2023-02-12 18:38 UTC
