### ISSUE TITLE
[GUI] Add colors to Scene tab to improve readability (complements Inspector color variation for nested sections)

### ISSUE THREAD

**Issue by viksl** [godotengine/godot-proposals#3014] opened 2021-07-19 14:56 UTC
### Describe the project you are working on

This feature improves Editor's user experience not a particular game.

### Describe the problem or limitation you are having in your project

Currently the Scene tab uses one color line for all it's nodes, this is simple in case of a one layer or two nodes layer setup but with more nodes added the readibility decreases sigfinicantly especially if the list is longer but even with just 2-3 layers of nodes, example:

| NodeA
| -> NodeB
|- -> NodeC

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In the image below you can see how adding color variations can hugely improve how the scene's scheme can be read easier.

In this example I've chosen the colors pretty much randomly only making sure no 3 successive layers have the same or similar color to demonstrate the proposal.

![Godot-Scene-Manager-Proposal](https://user-images.githubusercontent.com/33526847/126179988-dc6b4def-34e4-4ea2-92a2-4258c0ee53c5.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This would have to be an automatic feature, since similar system is already in place for Inspector, perhaps it could be extended to the Scene tab too?

Unfortunately, I do not have better knowledge of godot to suggest a particular implementation in the system.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know if this can be dealt with without making changes to godot's core.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't know if this can be dealt with without making changes to godot's core.

**Comment by timothyqiu** [comment] 2021-07-19 15:02
This reminds me of rainbow brackets :)

It looks a bit busy in the mockup, maybe some less saturated color might look better.

**Comment by viksl** [comment] 2021-07-19 15:11
> 
> 
> This reminds me of rainbow brackets :)
> 
> It looks a bit busy in the mockup, maybe some less saturated color might look better.

Yeah I picked higher contrast colors, when it comes to Inspector the colors and their intensity actually changes based on the theme and how you set it up so I'd assume that could help with this too.

**Comment by pycbouh** [comment] 2021-07-19 15:19
This is a duplicate of https://github.com/godotengine/godot-proposals/issues/2654. After testing out colors were deemed to be too distracting, so saturation and thickness were used instead: https://github.com/godotengine/godot/pull/48546.

Here's an example of how it looks in master:

![image](https://user-images.githubusercontent.com/11782833/126184568-22a3ece2-9017-4f99-9563-a8d1a0bbd99e.png)

**Closed by pycbouh** 2021-07-19 15:19 UTC
