### ISSUE TITLE
Allow to set viewport internal format 

### ISSUE THREAD

**Issue by dan1338** [godotengine/godot-proposals#4378] opened 2022-04-10 18:19 UTC
### Describe the project you are working on

Multipass rendering

### Describe the problem or limitation you are having in your project

The values are clipped by limited [0,255] pixel range of ViewportTexture

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow the user to select the internal format to be used by the viewport, afaik from reading the code ImageTexture is the only one that even takes format into account, but all I really want is for godot to create the texture with GL_FLOAT as the internal format.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Have a list of formats on a viewport object in the editor.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It cannot

### Is there a reason why this should be core and not an add-on in the asset library?

Becuase "It cannot"

**Comment by Calinou** [comment] 2022-04-10 18:31
Related to https://github.com/godotengine/godot-proposals/issues/2935.

Which Godot version and rendering backend are you using?

In Godot 3.x's GLES3 backend, HDR viewports are used by default (with 16 bpc precision). If you need full 32-bit precision, there's already a proposal tracking this: https://github.com/godotengine/godot-proposals/issues/2935

**Comment by dan1338** [comment] 2022-04-10 21:22
Using 3.4.2.stable/GLES3

I'm making that assumption because I noticed that when decreasing a scaling variable in the shader by half, at some point instead of taking twice as long, the output texture just doesn't change.

My assumption is that I'm hitting a limit when the floating point numbers get quantized into integers and two adjacent passes map to the same integer therefore get stuck at that timestep.

Having the ability to use a native floating point ViewportTexture would circumvent the need to do the floating to integer conversion.

**Comment by Calinou** [comment] 2022-04-10 21:26
Duplicate of https://github.com/godotengine/godot-proposals/issues/2935.

This is now implemented in `3.x` by https://github.com/godotengine/godot/pull/51708 (try [3.5beta3](https://godotengine.org/article/dev-snapshot-godot-3-5-beta-3)).

**Closed by Calinou** 2022-04-10 21:26 UTC
Labels: topic:rendering
