### ISSUE TITLE
Godot 4, 2d editor pan with right mouse button

### ISSUE THREAD

**Issue by tufduckhotmailcom** [godotengine/godot-proposals#3957] opened 2022-02-12 11:38 UTC
### Describe the project you are working on

A 2d game

### Describe the problem or limitation you are having in your project

In Godot 3.x I could pan the 2d editor by holding right mouse button and drag. In Godot 4 this is no longer possible. Right clicking now opens up a context menu instead. I would really like the old behavior back.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a new option "Right mouse button Pans" in Editor Settings - Panning - 2d editor Panning Scheme, that allows panning the 2d editor by dragging with right mouse button held down. (like it was in Godot 3.x)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a new option "**Right mouse button Pans**" in **Editor Settings - Panning - 2d Editor Panning Scheme**.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I know I could pan with the middle mouse button, but that feels awkward.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a changed behavior from Godot 3.x, so I want it back in core.

**Comment by SilencedPerson** [comment] 2022-02-12 11:56
I think the editor should have gizmo instead.
look at blender for inspiration.
![image](https://user-images.githubusercontent.com/82024211/153710291-632e30ba-b472-4698-98e2-8b54b6aa812c.png)

**Comment by KoBeWi** [comment] 2022-02-12 14:59
Duplicate of #3881

> I know I could pan with the middle mouse button, but that feels awkward.

You can also pan using keyboard (Space by default).

**Closed by KoBeWi** 2022-02-12 14:59 UTC
