### ISSUE TITLE
GDScript: Functions with optional arguments

### ISSUE THREAD

**Issue by MickL** [godotengine/godot-proposals#3678] opened 2021-12-16 18:13 UTC
### Describe the project you are working on

Action RPG

### Describe the problem or limitation you are having in your project

In [TypeScript](h[ttps://github.com/microsoft/TypeScript](https://www.typescriptlang.org/docs/handbook/functions.html#optional-and-default-parameters)) it is possible do define optional arguments:

```
take_hit(damage: int, knockback_force?: int, knockback_direction?: Vector2):
  emit_signal("damaged", damage)
  if (knockback_force):
     emit_signal("knockbacked", knockback_force, knockback_direction)
```

Then the function can be called like this:
```
something.take_hit(1)
```

Or like this:
```
something.take_hit(1, 100, direction_vector)
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like to also be able to set optional paremters

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Optional parameters are not allowed before required parameters or default parameters

Allowed:
`my_func(a: int, b?: int)`
`my_func(a: int, b: int = 1, c?: int)`

Not allowed:
`my_func(a?: int, b: int)`
`my_func(a: int, b: c?: int, int = 1)`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

-

**Comment by Calinou** [comment] 2021-12-16 18:23
Duplicate of https://github.com/godotengine/godot-proposals/issues/162.

**Closed by Calinou** 2021-12-16 18:23 UTC
