### ISSUE TITLE
Ability to zoom in and out of the font size within the built-in Godot Docs and Output console to reduce eye strain

### ISSUE THREAD

**Issue by knadoor** [godotengine/godot-proposals#6269] opened 2023-02-11 11:07 UTC
### Describe the project you are working on

N/A - this is a general editor enhancement request.

### Describe the problem or limitation you are having in your project

When working on a project and wanting to view the Godot docs within the editor via the shortcut method (CTRL + Click or CMD + Click) and the mouse scroll wheel, it's not possible to zoom in and out of the font size within the editor godot docs - just like how you can within the Script editor and the Shader Editor.

<img width="971" alt="image" src="https://user-images.githubusercontent.com/8476589/218254563-dd950bc8-841b-46d8-b476-2b799aa42ae7.png">

The zoom in/out functionality should also extend to the Output console:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/8476589/218254590-61e1cce4-a93a-4f6b-b114-35a395f23a15.png">

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I know we can set the font size and editor scale however a user should not have to resort to this if they only want to see the godot docs or the text within the output console larger or smaller on demand.

The zoom in/out functionality via the scroll wheel and keyboard short cut exists for the "Script" and "Shader Editor" sections, it only makes sense to maintain consistency and extend it to the built-in Godot docs and output console. This will improve the user experience.

This feature will be very handy on large monitors preventing user eye strain due to small font size.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

This is an editor quality of life enhancement and will improve the user experience as part of core.

**Comment by YuriSizov** [comment] 2023-02-11 11:30
Duplicate of https://github.com/godotengine/godot-proposals/issues/1914. (Sans the console part, but we can add this as another use case).

**Closed by YuriSizov** 2023-02-11 11:30 UTC
