### ISSUE TITLE
Consistency: move_and_slide and move_and_collide both taking/not taking delta into consideration

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot-proposals#1305] opened 2020-08-04 13:04 UTC
**Describe the project you are working on:** N/A - applies to any project using `KinematicBody*`.

**Describe the problem or limitation you are having in your project:** `move_and_slide` takes `delta` into consideration. `move_and_collide` does not. This inconsistency can (and does) cause confusion, and sometimes people may use `delta` incorrectly (i.e., using it with `_and_slide` or not with `_and_collide`).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:** Making both functions use `delta` consistently. *Either*, both require delta to be explicitly included, or not.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:** Not really a proposal, but neither does it fit in with the main issue tracker as it is not a bug.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** This is not about "working around", so N/A.

**Is there a reason why this should be core and not an add-on in the asset library?:** Again, dealing with core functionality, so N/A.

**Comment by Calinou** [comment] 2020-08-04 14:03
Duplicate of https://github.com/godotengine/godot-proposals/issues/1192.

**Closed by Calinou** 2020-08-04 14:03 UTC

**Comment by MrEliptik** [comment] 2023-03-12 14:18
Can we reopen this proposal as it's still relevant in 4.0? 
https://github.com/godotengine/godot-proposals/issues/1192 is not really a duplicate as the author wanted to remove the automatic use of delta. 

In this proposal, the idea is to have a consistent behavior between `move_and_slide` and `move_and_collide` which is still not the case in 4.0.
