### ISSUE TITLE
Path independent loading/instancing

### ISSUE THREAD

**Issue by ctwobosius** [godotengine/godot-proposals#3108] opened 2021-08-09 00:51 UTC
### Describe the project you are working on

Large scale project where I've had to refactor file names and locations quite a few times.

### Describe the problem or limitation you are having in your project

Having to refactor all the preloads is clunky, and in general having to preload before instancing is also not the most elegant.

I saw that you could do

`class_name SomeScene`

and then do 

`SomeScene.new()`.

This works fine for built-in types. However, this is not the same as preloading then instancing custom classes/scenes (ie: SomeScene above)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Preloading user designated classes automatically, then having UserClass.instance() would be much more elegant in my opinion, and save a lot of time refactoring (as well as abstract away file paths, which is nice :)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I'm thinking of two solutions:

1) Mark stuff to be preloaded with a keyword, eg `global` like so:
```
# Yay.gd
global class_name Yay  # gdscript interpreter makes Yay a singleton or automatically preloads it in every other scene
# ...
```

```
# Main.gd
func _ready():
    var yay = Yay.instance()  # gdscript interpreter uses singleton or preloaded scene
    yay.position = Vector2.ZERO
# ...
```

2) No marking of user defined classes, not sure how much of a pain it will be to code this version up
```
# Yay.gd
class_name Yay
# ...
```

```
# Main.gd
func _ready():
    var yay = Yay.instance()  # gdscript interpreter sees Yay.instance and preloads it
    yay.position = Vector2.ZERO
# ...
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

We could keep the status quo I guess :3

### Is there a reason why this should be core and not an add-on in the asset library?

This is something that can't really be achieved with an add-on as far as I know.

**Comment by ctwobosius** [comment] 2021-08-09 00:56
I'm also open to exploring and doing the PR myself, but not sure how to modify the gdscript interpreter, if anyone would like to give pointers on how to start doing that :)

**Comment by KoBeWi** [comment] 2021-08-09 12:21
Related: https://github.com/godotengine/godot/issues/21187
`class_name` already supports custom icons, so adding a scene to it shouldn't be too difficult.

**Comment by dalexeev** [comment] 2021-08-11 18:26
Related: #1935.

**Comment by KoBeWi** [comment] 2021-12-16 14:50
This can be already achieved with a static method, as described here https://github.com/godotengine/godot-proposals/issues/1935#issuecomment-995885470
Also for path-independence you can also use UIDs in Godot 4.0.

Closing, as it's mostly duplicate of #1935.

**Closed by KoBeWi** 2021-12-16 14:50 UTC
Labels: topic:gdscript
