### ISSUE TITLE
Add support for sharp shadows, like new cartoon shader . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2369] opened 2021-02-27 14:56 UTC
### Describe the project you are working on
Tomb raider <3 a clone, so nice . .

### Describe the problem or limitation you are having in your project
I wanted to ask, if you could get a feature, under shadows, to make it render like these images . .
<img width="837" alt="2021-02-27 1549" src="https://user-images.githubusercontent.com/61069740/109390692-71789700-7913-11eb-8278-2a83ec0b5222.png">

Maybe it is a silly question, but I know Godot's shadows, that are a bit blurry, are more like real world, and it's best result . . But, my favorite shadows, are from old 1990 - 2000 games, like this . . <3
![2021-02-27 1551](https://user-images.githubusercontent.com/61069740/109390759-b997b980-7913-11eb-8419-5edc4a5e009a.jpg)

Maybe I could use the toon shader, but I only want it, for the shadows <3 I wanted to ask, if there could be feature, where one could set shadow ' sharpness ' or ' definition ', like a slider, under light settings, or something <3

Link, to shader: https://reposhub.com/python/game-development/CaptainProton42-FlexibleToonShaderGD.html

I want it to work, with normal maps, metalness, etc . . And, affect shadows . . I really love the ' pixel ', or vector look, that was when games looked ' best ', for me . . If it can't be made core, maybe a really, really cool dev, could make a shader, that one might use, on all 3D models, or so . . <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I just want the best, most cool, amazing graphics, 3-d goodness, and more . . Hope, it's possible, to realize it, this stuff . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Just, so we get sharp shadows, clearly defined, like that new shader <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I'm a total beginner, only learning visual script, can maybe make Hello world, in written script <3

### Is there a reason why this should be core and not an add-on in the asset library?
I have no idea, what's best here . . I just want it to be optimized, and run well, was hoping it could be a core feature, a plug - in or, a new shader type, among default types, to get that ' mint ' gamey look, I love, like can't describe, thx . .

Everything, is pixels, GPU, vectors . .

**Comment by Calinou** [comment] 2021-02-27 14:57
Duplicate of https://github.com/godotengine/godot-proposals/issues/1930.

**Closed by Calinou** 2021-02-27 14:57 UTC
