### ISSUE TITLE
Allow making dock containers floating, instead of docks alone

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#7614] opened 2023-09-06 13:31 UTC
### Describe the project you are working on

prototypes

### Describe the problem or limitation you are having in your project

Right now you can pop out individual docks in their own little window, but
 - there's no way to conveniently replicate the layout behavior that the editor provides (you can emulate it by manually tiling windows which is a pain if you don't have a window tiling system in your DE or if it's not granular enough)
![image](https://github.com/godotengine/godot-proposals/assets/71937306/64d2416c-e36c-414e-a78c-3260b7196f68)

 - there's no way to replicate the dock tabbing behavior 
![image](https://github.com/godotengine/godot-proposals/assets/71937306/19a36334-72dc-4a4d-86f6-565480a99ad6)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Instead of popping out only naked docks, pop dock containers that *contain* docks and provide layout options for them (namely vertical split and tabs).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://github.com/godotengine/godot-proposals/assets/71937306/30d72a6f-1a39-44ff-a19c-86d29b5e06bc)

behavior:

- drag and dropping a tab from any container to any other container would move that tab there (as it currently work inside of the editor)
   - as a plus, drag and dropping a tab outside of its window would make the dock floating automatically
- the `...` button would still be there, and allow you to split the container vertically or to make the dock floating in its own window: 
![image](https://github.com/godotengine/godot-proposals/assets/71937306/cbb802d8-1745-4aa5-9bbb-a1b1577d9f01)
- of course editor layouts should support that

### If this enhancement will not be used often, can it be worked around with a few lines of script?

used often

### Is there a reason why this should be core and not an add-on in the asset library?

had no success hacking my way with an addon, and it's an improvement on a too basic core feature

**Comment by kitbdev** [comment] 2023-09-27 04:47
looks like a duplicate of https://github.com/godotengine/godot-proposals/issues/1984

**Comment by Calinou** [comment] 2023-09-27 16:28
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/1984.

**Closed by Calinou** 2023-09-27 16:28 UTC
Labels: topic:editor
