### ISSUE TITLE
Change default FOV of cameras to 30.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-proposals#2265] opened 2021-02-09 21:05 UTC
### Describe the project you are working on
Graphical render scenes with godot.

### Describe the problem or limitation you are having in your project
Godot default FOV of 70 is a too high value.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Godot default FOV on cameras gives weird fish eye lens when doing normal games.
Advanced users know how to set up the FOV, but godot new users wont change the FOV, giving a wrong result.
A value of 30 by default gives a similar result to a phone camera or is a more natural looking result.
As such, it can affect new users creating a result they may think is a bug or have no clue why it happens.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Just change the default value to 30.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, is a default value.

### Is there a reason why this should be core and not an add-on in the asset library?
Is a core issue.

**Comment by clayjohn** [comment] 2021-02-09 21:32
Doing a quick search online. It looks like a human's central field of view is about 60 degrees, while their full field of view is closer to 200. While video games go with field of views ranging from 60 to 100. 

Accordingly, 30 seems to be much too low as a default value. 

That being said, the fact that it looks better to you makes me concerned that maybe Godot FOV is accidentally specified in half-FOV. And a setting of 30 actually corresponds to a 60 degree FOV? Could that be happening?

**Comment by Calinou** [comment] 2021-02-09 22:34
A vertical FOV of 30 is way too low.

> That being said, the fact that it looks better to you makes me concerned that maybe Godot FOV is accidentally specified in half-FOV. And a setting of 30 actually corresponds to a 60 degree FOV? Could that be happening?

This is because by default, FOV in Godot is specified as a vertical FOV, not horizontal FOV. If you set the camera's aspect mode to **Keep Width**, the specified FOV will be used as a horizontal FOV.

Closing, as the current behavior is here by design (**Keep Height** is intended to support multiple aspect ratios on desktop/landscape mobile
 easily).

**Closed by Calinou** 2021-02-09 22:34 UTC
