### ISSUE TITLE
Add an on/off toggle for the boot splash-screen

### ISSUE THREAD

**Issue by JamesC01** [godotengine/godot-proposals#2478] opened 2021-03-18 18:49 UTC
### Describe the project you are working on
Learning the engine

### Describe the problem or limitation you are having in your project
Removing the splash screen right now uses quite a hacky/ugly solution. You have to type "null" in the Image field to remove it. Which isn't easy to figure out (apart from googling) and isn't a pretty solution.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Add a simple on/off toggle for the splash screen.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Toggling off the option "Show boot splash image" (or similar) will disable the splash screen image, so nothing is drawn at boot.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes

### Is there a reason why this should be core and not an add-on in the asset library?
Yes. While it's tiny, it's just a bit of polish that makes the engine feel more like a professional product. Right now, it's not obvious how to get rid of the splash screen, the only solution is to google it and find the ugly solution, which feels more like a temporary workaround than an actual solution, even if it doesn't what you want.

**Comment by Calinou** [comment] 2021-03-18 19:00
Duplicate of https://github.com/godotengine/godot-proposals/issues/1445.

> Removing the splash screen right now uses quite a hacky/ugly solution. You have to type "null" in the Image field to remove it. 

I wasn't even aware this was possible :slightly_smiling_face: We should update the documentation accordingly.

**Closed by Calinou** 2021-03-18 19:00 UTC
