### ISSUE TITLE
Unit zoom control

### ISSUE THREAD

**Issue by Mutim** [godotengine/godot-proposals#1470] opened 2020-09-07 03:36 UTC
**Describe the project you are working on:**
We're working on a 3D gather and grind. 

**Describe the problem or limitation you are having in your project:**
Limitation (Though it might be in here, I just can't find it): I'm looking for a way to change the units of zoom. While trying to zoom in close to an object in a scene, I zoom through it. The scene zoom (Which, I searched for "unit" "zoom" "scroll"(Thinking, why not) and nothing was found. The default "units per scroll click" seem to be around 50.6u 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
We were wondering if it's possible to change this, I cannot find it anywhere (Though I've only looked for about 20 minutes, that should have popped up somewhere by now) and if not, could it be added to be able to change the units of zoom. The issue is changing the units of scroll (If I can refer to them as that) 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I'm only in graphics and don't know much about code. But what I do know, is it would be a user input in some function that deals with the zoom of the camera. (Not the camera node, the viewport camera) Again, sorry for being so crude, I know some basic scripting and not much beyond that. 
I know enough to know that it shouldn't be *too* hard to add, if not already there. (Emphasis on the "Might already be there, I might just be dumb" part)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't know if it can be worked around with a few lines of script. I do know that I can change the translation of the object in my scene to kind of simulate being closes to it. But, that's not ideal and has a lot of rework involved. 

**Is there a reason why this should be core and not an add-on in the asset library?:**
Well, I'm certain that I'm not the only person who would like this option. As Godot becomes more fleshed out, I think that people might expect this. If it is an addon, *or* if it's already there, and I'm just overlooking this, it's a great feature nonetheless.

**Comment by Calinou** [comment] 2020-09-07 11:54
Duplicate of https://github.com/godotengine/godot-proposals/issues/579.

**Closed by Calinou** 2020-09-07 11:54 UTC
Labels: topic:editor

**Comment by Mutim** [comment] 2020-09-07 19:42
For instance. Pressing F on the object will allow you to focus and get tighter zoom control. I found the answer, thank you. I'm posting this in case there is another question like this that comes up, and maybe I can help them out.
