### ISSUE TITLE
Add a parameters propert only available in functions which collects all the passed parameters

### ISSUE THREAD

**Issue by filipworksdev** [godotengine/godot-proposals#5739] opened 2022-11-07 15:19 UTC
### Describe the project you are working on

A 3D game

### Describe the problem or limitation you are having in your project

I sometimes want to pass multiple parameters to the same functions

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In a nutshell allow passing any number of attributes/parameters to functions by collecting them into a `properties` built in parameter which is available only inside functions.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Simple example (I know you can use reduce for summing but is just to illustrate what I am proposing)
```gdscript
def add():
  sum = 0
  for v in parameters: # any passed parameters automatically get collected in parameters
     sum += v
  return sum

def _ready():
  print( add(1,2,3,4,5,6,7,8) ) # properties = [1,2,3,4,5,6,7,8]
  print( add(1,2,3) ) # properties = [1,2,3]
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Right now It can't easily worked. It can be sort of worked around by using dictionaries or variables.

### Is there a reason why this should be core and not an add-on in the asset library?

It would require changes to how functions work

**Comment by Calinou** [comment] 2022-11-07 16:28
Duplicate of https://github.com/godotengine/godot-proposals/issues/1034.

**Closed by Calinou** 2022-11-07 16:28 UTC

**Comment by filipworksdev** [comment] 2022-11-07 16:51
@Calinou Thank you I will do so. I don't think it should be a global parameter either but rather a locally scoped function only parameter.
