### ISSUE TITLE
Use script type for variable when drag-and-dropping a node on a script

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-proposals#7663] opened 2023-09-14 07:19 UTC
### Describe the project you are working on

prototypes

### Describe the problem or limitation you are having in your project

Look at the type the created variable gets in this clip:

[simplescreenrecorder-2023-09-14_09.10.43.webm](https://github.com/godotengine/godot-proposals/assets/71937306/42953a0e-a73e-4a52-a902-14a2daa0580d)

as you can see, the node initially gets typed as a `Node3D` because of the actual node type, but I want it to get its script type (which you can't see in the video but the node has a script attached).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When a script with a `class_name` is attached to the dropped node, type the variable according to this class.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

use the script class rather than the node one

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I more often want the type to be as narrow as possible.
Then it can be loosened on a case by case basis which I think is rare when performing this operation.

### Is there a reason why this should be core and not an add-on in the asset library?

can't be an addon

**Comment by fkeyzuwu** [comment] 2023-09-14 10:38
just wanted to suggest this as well, this is something happens very very commonly for me.

**Comment by kleonc** [comment] 2023-09-14 12:05
Duplicate of #7239, already implemented by https://github.com/godotengine/godot/pull/79198 (included since 4.2.dev1).

**Closed by kleonc** 2023-09-14 12:05 UTC
