### ISSUE TITLE
Making Animation Tree property path (and all IDE tooltips) better and less error prone

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#1054] opened 2020-06-13 16:42 UTC
**Describe the project you are working on:**
2D platformer making use of animation trees, state machines and blend trees.

**Describe the problem or limitation you are having in your project:**
The process of setting an animation tree is cumbersome and error prone due to having to enter a long string path from a property into the Set method.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Currently, in order to set an animation tree you have to first find out the path to the property by navigating to the property, hovering over the property, remembering what the entire path is, then typing it exactly as found. For example:

![image](https://user-images.githubusercontent.com/12863685/84574052-2413c400-ad9c-11ea-9a74-2787b6ff279b.png)

You then have to code something like this from memory:
anim_tree.set("parameters/eye_blend/blend_amount", 1.0)

If you type it wrong or get the wrong case, there is no way of knowing and it's difficult to debug. Getting exponentially more difficult the more animations you have.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Avoiding a complete rewrite of how animation trees are set, a simple solution that will benefit the entire IDE is for a hot key to be made available to the 'hover' tooltip window that copies the text into the clipboard.

For example, using the screenshot above, pressing ENTER with the tooltip open will copy the path to the clipboard. This then adds a feature to the entire IDE, not just animation tree properties.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No

**Is there a reason why this should be core and not an add-on in the asset library?:**
This process of calling 'Set' and having to supply a full string path with no other means is pretty much entering 'you only know if you know' territory and needs simplifying. But a quick win solution that will aid all coders is ability to copy hover tooltips to the clipboard.

**Comment by Calinou** [comment] 2020-06-13 18:19
Duplicate of https://github.com/godotengine/godot-proposals/issues/106, which is being implemented by #39404.

**Closed by Calinou** 2020-06-13 18:19 UTC
Labels: topic:editor
