### ISSUE TITLE
Make TextEdit default focus border style theme

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot-proposals#5527] opened 2022-10-02 03:43 UTC
### Describe the project you are working on

A dictionary app.

### Describe the problem or limitation you are having in your project

I found many edit controls (`LineEdit, Button, RichTextLabel` etc) has a default focus theme but `TextEdit` don't have.
![GIF 2022-10-2 11-39-09](https://user-images.githubusercontent.com/35988767/193436871-58e16e67-5a64-4244-bdb2-d40c2d79155f.gif)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make default focus theme for `TextEdit`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

/

### Is there a reason why this should be core and not an add-on in the asset library?

/

**Comment by Calinou** [comment] 2022-10-02 22:58
Duplicate of https://github.com/godotengine/godot/issues/32996 (this is a bug).

**Closed by Calinou** 2022-10-02 22:58 UTC
Labels: topic:gui
