### ISSUE TITLE
Drag node from scene hierarchy to the inspector

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot-proposals#1299] opened 2020-08-03 10:36 UTC
**Describe the project you are working on:**
Random project no specific game

**Describe the problem or limitation you are having in your project:**
Just some workflow hickups

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Be able to drag nodes from the scene hierarchy directly to the exported variable in the inspector.
i know we can klick open the assign and select from there, but i belive it to be alittle easier to just be able to drag it to where it supposed to be.
Today when you try to drag something it just instantly select that node and the new nodes inspector appear 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
![Anteckning 2020-08-03 123540](https://user-images.githubusercontent.com/13393087/89174206-c6bf1680-d585-11ea-890c-1e4b7fcde962.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't belive it can

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is just a nice ability to have in the workflow toolbox, so yes i think this should be in core.

**Comment by KoBeWi** [comment] 2020-08-03 11:06
Duplicate of #1042

**Closed by KoBeWi** 2020-08-03 11:06 UTC
