### ISSUE TITLE
Make a default folder called ' Scripts ' and save scripts there by default . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1324] opened 2020-08-07 04:25 UTC
**Describe the project you are working on:**
A Tomb Raider game . .

**Describe the problem or limitation you are having in your project:**
When I add a new script, they get saved in the ' Scenes ' folder, by default, but that's confusing, and means the folder gets filled by many files, as a game gets bigger . . It gets more and more difficult to locate, and keep track of files . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Make it so there's a default folder called scrips, same as there's one called Scenes, and save all scripts there, by default . . Having to manually find the relevant folder, is a lot of trouble . . I think it makes sense to a Script folder, as almost all games will need scripts, sooner, or later . . And, having all the files located, along with all the scenes, in one place, means finding them one must scroll through a ton, of .tscn files, to find the .gd, or .vs one wants . .

Alternatively, make a default save folder option, for script, that one can choose, when one adds a script . . :O :O

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Just add a ' default ' Scripts folder, or a choice to set Default Script save folder, when making a new one . . Probably last is better . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't know how, to do this . . :((

**Is there a reason why this should be core and not an add-on in the asset library?:**
Makes sense, it's there, as a setting . .

**Comment by Zireael07** [comment] 2020-08-07 06:44
Godot does not impose any sort of a structure on your project. A default folder option, however, would fix your problem while not imposing any sort of a structure.

**Comment by Calinou** [comment] 2020-08-07 10:23
Duplicate of https://github.com/godotengine/godot-proposals/issues/576 (the underlying issue is the same).

**Closed by Calinou** 2020-08-07 10:23 UTC
