### ISSUE TITLE
Make the Context Menu Key (on the keyboard) able to open context menus

### ISSUE THREAD

**Issue by Sosasees** [godotengine/godot-proposals#3753] opened 2022-01-04 19:04 UTC
### Describe the project you are working on

I am currently working on a Tabletop game for my tablet computer.
This feature will be equally useful in my future planned projects, such as
- a sequel to the game "Super Runner" that I made in GoGodotJam 2
- a game that only vaguely fits in the "Platformer" category because the movement mechanics are very different from the usual platformer (no normal jumping or running)

### Describe the problem or limitation you are having in your project

My keyboard has a key that, when pressed, opens context menus, just like the right mouse button does.
It has a symbol that looks like this:

```
██████████████████
██              ██
██  ██████████  ██
██              ██
██  ██████████  ██
██              ██
██  ██████████  ██
██              ██
██████████████████
```

I often prefer using this key instead of the right mouse button, especially on my foldable computer
where it's Much more comfortable by a long shot.

This key does not work in Godot, which throws me off, especially because it works in Every other program i used.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Pressing this key should open the context menu, just like pressing the right mouse button does.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Pressing this key would open the context menu, just like pressing the right mouse button does.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know if it's possible to work around this limitation with a few lines of script, but if it does:
1. please tell me how
2. i would have to set it up in Every Godot project

### Is there a reason why this should be core and not an add-on in the asset library?

This feature should be core
because it's a tiny quality-of-life feature that, as far as i know,
doesn't have the possibility of getting in the way of people who don't use it.

Having to set up the feature for every project would get tedious
without a benefit for people who don't use it.

**Comment by Calinou** [comment] 2022-01-04 20:41
Duplicate of https://github.com/godotengine/godot-proposals/issues/143.

**Closed by Calinou** 2022-01-04 20:41 UTC
