### ISSUE TITLE
Add user:// folder for files to be exported on game run

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1738] opened 2020-10-27 18:00 UTC
**Describe the project you are working on:**
Mario Bros 1 Editor

**Describe the problem or limitation you are having in your project:**
I would like to export some files to user:// while allowing them to be used in the editor

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I suggest adding a user:// folder to go along side of res:// so that we can export files we want people to be able to edit  

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Anything placed in the user:// folder will be available when running the game from the editor similar to res:// files, 
However when the game is ran from executable if the files do not exist they are created in the user:// folder.

So all you need to do is include your modding files in the user:// directory and load them like so..
`my_resource = load("user://path to resource")` and it works both in editor and from executable 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This would be used for modding and it can be worked around but its not very trivial as you have to treat user and res files differently depending on whether your running from editor or from executable

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think it would be easier to do this way and would be easier to understand.

**Comment by Shadowblitz16** [comment] 2020-10-27 19:00
one of the issues from the reason of this suggestion is exporting images.
however it seems godot converts images to .res files instead of leaving them the format they are.
this creates issues when it comes to modding because you can't easily open the image and edit it

**Comment by Shadowblitz16** [comment] 2020-10-27 19:24
https://github.com/godotengine/godot-proposals/issues/1740

**Comment by Xrayez** [comment] 2020-10-27 22:48
I think fundamentally, this may be related to #1632.

**Comment by Calinou** [comment] 2021-05-16 05:19
Duplicate of https://github.com/godotengine/godot-proposals/issues/1632 (same goal).

**Closed by Calinou** 2021-05-16 05:19 UTC
Labels: topic:editor, topic:porting
