### ISSUE TITLE
Expose custom controls used for property editors in the Inspector dock

### ISSUE THREAD

**Issue by ghsoares** [godotengine/godot-proposals#2276] opened 2021-02-11 16:47 UTC
### Describe the project you are working on
A custom dock plugin that handles a custom node variables.

### Describe the problem or limitation you are having in your project
In my plugin, I need to create a dock that can handle multiple variables from a custom node, like gradient, curves, resources, etc. But it seens that input fields that can handle these resource types are not avaliable as a regular node or instantiated from script.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Godot's UI is made from the Godot Engine itself, so it make sense that these input fields are exposed in the regular script API, so one can easily create a user interface with these input fields. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I don't know how is implemented these editor elements, but somehow exposing these as Control nodes or able to be instantiated from editor scripts is the way to go.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Can be reproduced but not with a few lines of script.

### Is there a reason why this should be core and not an add-on in the asset library?
Because it can create a multiple plugin dependency and break compatibility if one has issues. If these nodes are exposed in the regular script API, so it will make super easy to create plugins.

**Comment by pycbouh** [comment] 2021-07-28 19:46
I think this is actually a duplicate of https://github.com/godotengine/godot-proposals/issues/1761.

**Closed by pycbouh** 2021-07-28 19:46 UTC
Labels: topic:editor, topic:gui
