### ISSUE TITLE
Make it easier to select an input or output port when zoomed out, for Visual script / other ideas . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#2886] opened 2021-06-19 06:51 UTC
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
Ok, been trying Visual script in Godot 4 build, and it's really nice, the UI has gotten an update, it feels amazing, 10 / 10, from a visual script user, also visual shaders . . Got no more complaints, except a small one . . When one zooms out, for getting the extra amount of space, to work with, it gets difficult to select a port, one often selects a 'node', not the port, here . . .

![2021-06-19 0832](https://user-images.githubusercontent.com/83387915/122633500-55bf1980-d0d9-11eb-9772-d033f8bd779b.gif)

It's sort of a problem, bec. it becomes difficult, or one has to zoom in-out, etc . . My proposal is, that one can toggle a feature, or icon, so that when one hovers over a node, and it will get selected, it gets a highlight, like this . . .

<img width="716" alt="2021-06-19 0839" src="https://user-images.githubusercontent.com/83387915/122633653-fa415b80-d0d9-11eb-9938-3570d4134d8a.png">

Not hovering over port, no highlight . .

<img width="716" alt="2021-06-19 0840" src="https://user-images.githubusercontent.com/83387915/122633660-03cac380-d0da-11eb-9d51-0467938b0367.png">

When mouse hovers 'correctly' over a port, that port gets highlighted, just a bit . . Idea is, one can have a button, where one can turn it on - off, at normal zoom levels, it's not a problem, and TWO, or one setting in Editor settings . . .

1. To set radius of extra high-light ( ie. how big it is ) . .
2. How close one has to be to a 'port' node, to actually select, let's say right now, it's 3 pixels radius, at normal zoom, that one could increase it to 4 pixels, for working with zoomed out windows, for that ' extra ' - code or, so . . .

This is part one . . .

SECOND, this is not super - important, it's already good, in Godot 4, looks better . . . :OO . . . Right now, Godot 4 looks amazing, very readable when zoomed out, it looks 100 % better, maybe bec. I got new screen, or monitor . . But, it's been a constant complaint, so I was hoping you'd give it a look, maybe consider making it . . .

THIRD, last, I've been hoping that we could be able to separate the visual script canvas, into two, like having multiple viewports, and one could connect stuff, over longer distance . . Right now, Godot 4 Visual script has 99 % stuff, I want . . So, AMAZING job, wanted to ask for these things, more like QoL ( Quality of life ) improvements, to take it to the NEXT kick - ass level . . . I haven't asked about better port selection, when zoomed out before, so that's the new proposal, hope you'll think about it, or so . . .

The last two things, better font readability zoomed out and, being able to have two canvas areas, with a horizontal, or vertical split, are more like, it'd be REALLY cool, wanted to ask, since Visual script is already, basically, 100 % cool, atm . . These are more 'QoL' stuff, than necessary . . It'd help visual scripters feel they have a 'bigger' canvas, that was easier to work with, maybe also in 1080p monitor, been using a cheap 4K monitor for almost 1 year or, so . . Recently got a 8K display . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Well, like above, add so one can better select ports, when zoomed out, maybe with some editor settings, or an icon, ie. it can be toggled on/off, since it's not needed, at standard zoom . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
See above . . . 

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't re-code visual script canvas, but it'd also work in visual shaders, and the new particle visual graph editor . . :O :O . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, it's more QoL, but it'd make Visual script feel, like it's from nice Toyota to, well, BMW, Mercedes . . .

Amazing job on visual script, already, difficult not to be excited . . .

So, there are three ideas, since it's basically cool, rad atm . . Wanted to ask, since these things have been a problem, for some time, thx . . . <3

**Comment by Calinou** [comment] 2021-06-19 07:08
cc @LegendAA

Isn't the port selectable area scaled up when the user zooms out already?

**Comment by pycbouh** [comment] 2021-06-19 09:56
This PR may be related https://github.com/godotengine/godot/pull/49722

**Comment by Ansraer** [comment] 2021-06-19 19:33
Yeah, the current hot zone area is pretty much useless. My PR (49722) will at least fix the vertical aspect of this. I also spent some time looking into adjusting the horizontal hot zone area but had to revert that change since it caused hot zones to overlap the input fields, rendering them no longer interactable.

Adding some highlights to connections on hover shouldn't be too tricky, will add that to my to-do list.

**Comment by charlesmlamb** [comment] 2021-06-20 05:55
@Ansraer Wow, I'm very lucky, most of my proposals aren't so good, I'm very noob at dev, and don't really know, what I'm asking, if it's complex <3

one thing, consider making an icon, where one can toggle it, since it is only necessary when zoomed out, might get annoying at normal zoom levels, since it's not really needed, or so . .

**Comment by Anaxan** [comment] 2021-06-20 14:10
I agree that accidentally moving a node when trying to make a connection is a significant problem. I’ve a few thoughts.

Can the area of the pick zone to move the entire node be reduced ? If there was a significant  amount of space between the connection pick areas and whatever is selected to move the entire node, most of the issue would be resolved (IMHO).

I  like that the connection pick areas extend outside of the node. Anything that keeps me from going inside the node means that I have less chance of accidentally moving the node.

Is it possible to let the user adjust the pick areas ? 

Another solution might be to add a toggle to the node to lock and unlock its position. It’s not ideal but it might serve the purpose. Just to reiterate, the problem is not so much pick area related as it is accidentally moving the node. (IMHO)

**Comment by charlesmlamb** [comment] 2021-06-20 14:42
Or, make a button, so if you hold CTRL, you can move boxes, if not, you can't . .

One suggestion is to make the boxes vector based, so when one zooms out, it's not a matter of pixels, but at mathmematical re-rendering, and it'll always look good . .

I think it'd be solved 100 %, by the node ' dot ' getting a high-light, when it is being selected, or do the same, for the box . .

Anyway, there could be a button, to ' lock ' box movement . . Visual script is looking much better, for Godot 4 already, just wanted to ask, if these last details, could be some-how done . .

There are prob. many solutions, a big problem with earlier Godot, is that working on zoomed out is a pain, ie. fonts become unreadable, and the problem of selecting boxes, and making connections is also very tough . . .

I don't know the answer, if the ' dots ' for ports were highlighted or, 'grew' when hovering over them, or so on . . It'd solve the problem, also, as it won't be needed for the default zoom level, making it a button, so it only happens when needed, could be cool, or putting it in a menu, and giving it a short-cut . . So, one could toggle it, with some keys, CTRL+ALT+H ( highlight ports ) . . 

Visual script in Godot 4 is already, 98 % superb . . . Was hoping to get the last stuff done, since I'll be making a ton, of games, etc . . And, having these things, would well ' nail ' it <3 Thx . . . .

**Comment by pro-rookie-gamer** [comment] 2021-06-21 00:20
Can we use blender's Node Wrangler?😆

**Comment by YuriSizov** [comment] 2022-08-24 16:16
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!

**Closed by YuriSizov** 2022-08-24 16:16 UTC
Labels: archived, topic:editor, topic:visualscript, topic:gui

**Comment by Zireael07** [comment] 2022-08-24 16:55
Applies to all GraphNodes, not just visual script. Should be reopened as visual shaders are still a thing

**Comment by YuriSizov** [comment] 2022-08-24 17:06
> Applies to all GraphNodes, not just visual script. Should be reopened as visual shaders are still a thing

Please open a new proposal so it's easier to discuss it in the context of visual shaders.
