### ISSUE TITLE
Rename "disabled" property in CollisionShapes to "enabled" and set the default value to true

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot-proposals#3336] opened 2021-09-23 02:32 UTC
### Describe the project you are working on

A simple "shooting gallery" project I use to teach Godot to students who are new to programming in general. The enemies are Area2D nodes that detect clicks. 

### Describe the problem or limitation you are having in your project

Part of the project involves using an AnimationPlayer to set the "disabled" property of a CollisionShape at certain moments during the game, to make an enemy clickable(killable) or not. 
Being a boolean the property shows in the animation track as a box with or without a tick mark. In the three years using this project to teach I've seen numerous occasions where the students are confused due to "[✔] On" meaning the collision is off and "[  ] On" meaning the collision is on. 

I think the name of the property is a bit confusing

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

For CollisionShape and CollisionPolygon change the name of the property to "enabled" and the default value to "true". This is more intuitive with how the editor displays the property since usually "On" is understood as a synonym of turned on/active/working/enabled.

Of course this breaks compat but it is expected for 4.0 and there are already a lot of renames in nodes and properties.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/526829/134446110-8fe8aba9-91f7-4e8b-abd4-e57a54449a24.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No. This is a built-in property and cannot be changed by the user. 

### Is there a reason why this should be core and not an add-on in the asset library?

There's no way to implement it as an add-on

**Comment by Calinou** [comment] 2021-09-23 04:11
Duplicate of https://github.com/godotengine/godot-proposals/issues/1376.

**Closed by Calinou** 2021-09-23 04:11 UTC
