### ISSUE TITLE
(Linux) Allow using xdg-desktop-portal for various features on Linux, such as file choosing

### ISSUE THREAD

**Issue by orowith2os** [godotengine/godot-proposals#4970] opened 2022-07-24 23:58 UTC
### Describe the project you are working on

I'm not working on the project, but one who packaged it as a flatpak and would appreciate the feature. https://github.com/virtual-puppet-project/vpuppr

### Describe the problem or limitation you are having in your project

Godot currently uses its own file chooser, which does not interact well with how Flatpak's sandboxing works.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would allow for a dev to use the xdg-desktop-portal file chooser instead of the Godot file chooser, which would make for better host integration and allow for being used inside of Flatpak properly.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When a user opens a file chooser in a Godot app, it will open the host's file chooser, rather than Godot's.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It may be used often in apps that would allow for packaging as a flatpak on Linux, or want tighter host integration on Linux.

### Is there a reason why this should be core and not an add-on in the asset library?

I am not familiar with Godot, so I can not put a reason here other than it would be nice to have for devs willing to enable it for Linux ports.

**Comment by Calinou** [comment] 2022-07-25 00:14
Duplicate of https://github.com/godotengine/godot-proposals/issues/1123.

**Closed by Calinou** 2022-07-25 00:14 UTC
Labels: topic:porting

**Comment by orowith2os** [comment] 2022-07-25 00:51
That issue is not exactly a duplicate, but similar.

**Comment by RokeJulianLockhart** [comment] 2024-12-24 22:21
> https://github.com/godotengine/godot-proposals/issues/4970#issuecomment-1193438896

@Calinou, the scope in the aforelinked issue is very different. Either its title needs to be modified, or this issue needs to be reopened. They're not equivalent in their current states.

**Comment by Calinou** [comment] 2025-01-02 19:28
Native file dialogs are supported on Linux since 4.3: https://github.com/godotengine/godot/pull/89735
