### ISSUE TITLE
Add named arguments to GDScript (syntatic sugar)

### ISSUE THREAD

**Issue by InkONat** [godotengine/godot-proposals#11077] opened 2024-11-03 00:49 UTC
### Describe the project you are working on

This feature doesn't depend on any project, it is a syntatic sugar proposal.

### Describe the problem or limitation you are having in your project

Sometimes I may have to write very extensive functions on bigger projects with several arguments.

```gdscript
func foo(a, b = 10, c = 57, ..., j = 20
```

And also sometimes I might call these functions with specific arguments. So I have to write down the default values for each of these arguments before the argument I want to change:

```gdscript
foo(203, 10, 57, ..., 26)
```

Besides taking a long time to write, I might also forget some of the default values for these arguments.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Named arguments is a feature in C# that allows you to pass an argument without having to write down the values for the arguments before it:

```csharp
Foo(207, j: 20);
```

I suggest that GDScript should have the same feature, except using `=` instead of `:` since that is already used for typing.

```gdscript
foo(207, j = 20)
```

Named arguments would have to be declared *after* non-named arguments:

```gdscript
foo(j = 20, 495) # throws an error
foo(495, j = 20) # okay
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Example:

```gdscript

func equation(a: int, b: int = 2, c: int = 3, d: int = 4, e: int = 5):
    return str("x ^ ", e, " + x ^ ", d, " + x ^ " c, " + x ^ ", b, " + x ^ ", a)

func _ready():
    eq = equation(1, e = 10) 
    print(eq) # prints "x ^ 10 + x ^ 4 + x ^ 3 + x ^ 2 + x ^ 1"
    eq2 = equation(e = 50) # error: a was not given a value
    eq3 = equation(6, e = 394, 9) # error: named argument before non-named argument
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is a syntatic sugar proposal, so it can be worked around.

### Is there a reason why this should be core and not an add-on in the asset library?

GDScript is core

**Comment by Meorge** [comment] 2024-11-03 01:35
I've been hoping to have this in GDScript for a long time. I could've sworn there was already an issue open for it, although I didn't find it with a search of the repository. My recollection, from the discussions I'd seen about it, was that there was concern because of the way arguments are currently passed to functions internally.

**Comment by dalexeev** [comment] 2024-11-03 06:58
* Thanks for the proposal. This is a duplicate of #902, which was rejected due to technical issues. Please see the discussion in the original proposal.

**Closed by dalexeev** 2024-11-03 06:58 UTC
