### ISSUE TITLE
Make it possible to move the ' resource dock ' into the debugger area . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2117] opened 2021-01-14 07:00 UTC
### Describe the project you are working on
Right now, the res folder can only be displayed, left or, right on screen . . Could be possible to move it down, so it could also ' sit ' in, the lower bar, where there's sound, animation, debugger, like some other engines . .
![Skærmbillede (894)](https://user-images.githubusercontent.com/61069740/104555345-ff3b4400-563d-11eb-9640-4e81f40997dc.png)

So, it looks a bit, like . .
![2021-01-14 0757](https://user-images.githubusercontent.com/61069740/104555475-3c073b00-563e-11eb-9c88-fae2f2c0c3bd.jpg)

it would allow to see more files or, resources, and be a nice option . . if it could ' split ' the lower bar, so could still see the debugger, or audio, etc, it'd be nice . . it makes, more sense, for some reason, or so . .

### Describe the problem or limitation you are having in your project
Just an, update, to looks . . <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
It allow to see more files, or resources, and have better over-view, of files and, 3d stuff, audio, images . . . <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Make an option, so when moving a dock, it can be placed in the debugger, as a split or, such . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not sure, it's beyond me, atm <3

### Is there a reason why this should be core and not an add-on in the asset library?
Not sure, difficult to answer . . <3 . . .

**Comment by jasperbrooks79** [comment] 2021-01-14 07:01
also, ability to put a dock, into the top bar, or so . .

**Comment by Calinou** [comment] 2021-01-14 12:52
Duplicate of https://github.com/godotengine/godot-proposals/issues/1508.

**Closed by Calinou** 2021-01-14 12:52 UTC
