### ISSUE TITLE
IDE Feature - Rename Symbol

### ISSUE THREAD

**Issue by andyjh92** [godotengine/godot-proposals#3127] opened 2021-08-12 18:54 UTC
### Describe the project you are working on

I would like to make a game in my spare time.

### Describe the problem or limitation you are having in your project

I want to quickly rename symbols in GDscript code, but no GDScript IDE currenty supports "Rename Symbol". This feature is very basic and I don't want to develop without it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I highlight a symbol, press a shortcut and rename the symbol and all its occurences at once. That's faster and safer than doing it manually.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The feature is like "Rename Symbol (via F2)" in VS-Code. https://code.visualstudio.com/Docs/editor/editingevolved#_rename-symbol

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This should work out of the box. It will increase usability.

**Comment by Calinou** [comment] 2021-08-12 19:15
Duplicate of https://github.com/godotengine/godot-proposals/issues/899.

**Closed by Calinou** 2021-08-12 19:15 UTC
