### ISSUE TITLE
Opening Forward+ projects without a Vulkan GPU: You're bricked!

### ISSUE THREAD

**Issue by Pacomatic1** [godotengine/godot-proposals#6457] opened 2023-03-07 23:04 UTC
### Describe the project you are working on

This happens when you convert a project from Godot 3 to 4, but your GPU doesn't support Vulkan.
This also happens when trying to open a project with a Vulkan renderer, like Forward+, but your GPU doesn't support Vulkan.

### Describe the problem or limitation you are having in your project

When you open a Godot 3 project in Godot 4, it tells you to go and convert your project. But when you do this, it defaults to Forward+. the other scenario, I have a Compatibility project but decide to change the rendering mode to Forward+.

But since the GPU doesn't support Forward+, which uses Vulkan, you can't open the project.
there's an easy fix: Change the rendering mode.
The only way to change the rendering mode is to open the project.
But opening the project is the only way to change it, but you can't open the project;
and as such, the result is that you're locked out of the project and you can no longer use or open it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

All you have to do is allow users to change the rendering mode without opening the project.
But we could do this not just with a "Change Renderer" button.
We could do it by allowing the user to open up the Project Settings Menu from the Project Selection screen:
![image](https://user-images.githubusercontent.com/74610266/223571574-39a34a07-e096-411d-86a7-455e6e05e805.png)
By pressing this button, it'll open up this menu:
![image](https://user-images.githubusercontent.com/74610266/223571391-8d895868-e431-43a9-ab8c-70da31bd0ff0.png)

Of course, this wouldn't be complete without one final change.
This is the error that pops up when you open a project using the Forward+ renderer, but your GPU doesn't support Vulkan.
![image](https://user-images.githubusercontent.com/74610266/223571778-3c92207c-befe-4300-aa9b-dbcb40f13a3c.png)
Despite following the instructions, it says that Godot 4 is not an executable program:
![image](https://user-images.githubusercontent.com/74610266/223573177-3e4c79f7-2468-489e-b407-f9b47fc698a5.png)
So also add the following text to the error:
"You can also go to the project selection screen, go to the project settings menu, and then change the renderer to compatibility."

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Seems I did this step in the previous one.
So scroll up.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As said before, although you provide an alternative, it doesn't work.
Not all PCs support Vulkan and considering that PCs from a while back are still quite used today, I say this will help everyone who uses a GPU without Vulkan; not to mention the fact that this is the normal Project Settings Menu, meaning that you could use it for anything.

### Is there a reason why this should be core and not an add-on in the asset library?

Because I'm pretty sure that this is impossible with the current codebase in the asset library.

**Comment by clayjohn** [comment] 2023-03-07 23:14
You can also change the rendering mode in the project file directly. Just open the project.godot file as a text file and add the following to the bottom:

```
[rendering]

renderer/rendering_method="gl_compatibility"
```

If you already have a ``[rendering]`` section just add ``renderer/rendering_method="gl_compatibility"`` under it

**Comment by vnen** [comment] 2023-03-08 00:13
BTW, executable name with spaces need to be enclosed in quotes, this is a requirement for the command prompt. You should use:
`"Godot 4 (temp).exe" --rendering-driver opengl3`

This should be corrected in the error message.

**Comment by Calinou** [comment] 2023-03-08 21:24
- Duplicate of https://github.com/godotengine/godot/issues/58927.

**Closed by Calinou** 2023-03-08 21:24 UTC
