### ISSUE TITLE
draw ray for debug 

### ISSUE THREAD

**Issue by Heliox01** [godotengine/godot-proposals#5343] opened 2022-09-05 14:37 UTC
### Describe the project you are working on

3d game currently working on the camera 

### Describe the problem or limitation you are having in your project

it isn't a limitation but it would be useful cast a line with code. for example with a third person camera cast a ray from the player and the camera could be useful for resolving collision problems on unity exist the debug.drawray 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

a function that draw a line with multiple color with a visible variable

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

a function that instantiate Mesh.PRIMITIVE_LINES then assign a material and push the  2 vertices

### If this enhancement will not be used often, can it be worked around with a few lines of script?

can be worked around with line nodes  but having a function would be faster than doing nodes 

### Is there a reason why this should be core and not an add-on in the asset library?

it's a basic tool

**Comment by YuriSizov** [comment] 2022-09-05 14:38
Duplicate of https://github.com/godotengine/godot-proposals/issues/5196.

**Closed by YuriSizov** 2022-09-05 14:38 UTC
