### ISSUE TITLE
Change name of ' Control ' node to UI2D, or Interface2D + Ideas for names in Godot 4 . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1500] opened 2020-09-13 11:38 UTC
**Describe the project you are working on:**
A Tomb Raider type game ..

**Describe the problem or limitation you are having in your project:**
Name ' Control ' node is bit misleading, as for instance, the ' character ' controller stuff, ALSO controls the game, maybe one could change the Control node name, to UI2D, Or, UInterface, since it works in both 2D, and 3D games, or so . . UserInt, is also a better name, anyway, an idea, or so . . Thx . . . .

Or, GUINode, UI Node . . Something, OSDNode . . ? :O :O . . On-screen display . . Probably, something UI, or GUI . .

NodeUI, would be nice <3

Also, many of the nodes in Godot 4.0 has 3D after the name, I think only the nodes, where there is a meaningful difference between how the 3D, and 2D version work, should have that ' suffix ', and ' Spatial ' should be called Node3D, or so . . I think maybe a 3D camera works different, than a 2D camera, so it makes sense a 2D camera is called, Camera2D, vs. Camera3D, also a 3D MeshInstance, it's weird bec. an Instance is normally what one uses, to name ' Prefabs ', then one makes an ' instance ', so maybe chance the name to Mesh3D, to make it more clear . . Right now, every node in Godot 4 ( last I checked ), had 3D after name, and it makes the Inspector bit difficult, to read . .

Idea, only change the names of the nodes, add a 3D, if there's a meaningful difference, between the 2D, and 3D version, or so . . And, change named of Spatial, to Node3D, or so, since the ' Add node ' list makes a lot more sense, to read, that's all . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Just, to make Godot 4 better, to work with, for all users, except those with 10 - 15 year experience, or so . . <3 :D . . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**
I don't know, it's something everyone uses, all the time, difficult, to answer, for me . . . <3

**Comment by Calinou** [comment] 2020-09-13 12:05
Duplicate of #763.

**Closed by Calinou** 2020-09-13 12:05 UTC
