### ISSUE TITLE
Selecting all keyframes which have the same time value

### ISSUE THREAD

**Issue by RayOfIdeas** [godotengine/godot-proposals#4411] opened 2022-04-17 06:05 UTC
### Describe the project you are working on

This feature should be applicable in any game which utilizes Animation Panel. 

In my case, I was creating this [demo](https://github.com/RayOfIdeas/Godot_GDbot_2D_Demo), and found out a few problems which slowed down my workflow. That project demonstrates Godot's capability to help to create smooth 2D animations and animation transitions. I ended up making tons of animations, and some of them are similar to each other. The project also required me to fine tune each keyframe to achieve a better feel of movement of the character. Also, each animation has a lot of tracks to be animated.

### Describe the problem or limitation you are having in your project

I cannot select all keyframes which have the same time value (keyframes that are lined up in one column). As the result of this, I was forced to click-and-drag from the top of the panel, then scroll to the bottom of the panel to select all keyframes which have the same time value. Because of the nature of box selecting, the user may make a mistake of selecting keyframes that are located near with the desired keyframes, causing the user to redo the entire selection all over again.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I have a background in developing games in Unity, and one of the feature that Unity has for improving the developer's workflow in animation is by having them selecting all keyframes which have the same time value. Put it simply, all keyframes under one column can be selected by clicking the most top keyframe which exist only for selecting keyframes which have the same time value.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There are a few possible solutions:

- Add a shortcut to select all keyframes that have the same value with the keyframe that is currently selected. I suggest keys that are located on the left side of the keyboard, such as 'A', 'Z', or 'V'.
- When right-click a keyframe, add a new menu to select all keyframes with same time value.
- Just like Unity's animation panel, create a special track to control all keyframes with same time value.
![image](https://user-images.githubusercontent.com/94668844/163702814-f7c092f1-e135-4976-ab31-98def04395a6.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I believe this feature will be used often. I'm not very familiar with tweaking Godot's editor directly, so I'm not sure if it can be worked around with a few lines of code.

### Is there a reason why this should be core and not an add-on in the asset library?

This will easily improve all animators workflow out of the box. The lack of this feature really slows down animators' workflow, and doing box selection over and over again really annoys the animator.

**Comment by Calinou** [comment] 2022-04-17 16:01
Duplicate of https://github.com/godotengine/godot-proposals/issues/1908.

**Closed by Calinou** 2022-04-17 16:01 UTC
Labels: topic:editor, topic:animation
