### ISSUE TITLE
Improve the debugger's workflow by adding the most used common features.

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot-proposals#3363] opened 2021-09-29 09:32 UTC
### Describe the project you are working on

I spent a lot of time debugging physics in GD to avoid c++ compilation time.

### Describe the problem or limitation you are having in your project

The current system lack features

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Here are the main features I commonly use in other editors, which are not implemented in Godot:

1. Display object properties when you hover a variable instead of the reference: (note this feature is currently broken)

![Screenshot 2021-09-29 at 11 09 06](https://user-images.githubusercontent.com/6397893/135239951-e132d530-e2b5-4fff-a0c0-fc6843dbb4fa.png)

2. Evaluate expression: when you debug, be able to evaluate an expression in the current state

3. Watch list: be able to add variable to a watch list

4. Conditional breakpoint: useful when a bug occurs in a specific condition

5a. Nested object: display the class instead of Object ID

![Screenshot 2021-09-29 at 11 19 57](https://user-images.githubusercontent.com/6397893/135240666-9e9e68fc-f46b-4166-ac6d-6960f88a3309.png)

5b. This one is maybe a matter of preference, instead of opening a panel, displays the info directly in the members' panel like other editor.

6. Ability to Step out : #2815

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no.

### Is there a reason why this should be core and not an add-on in the asset library?

It's core.

**Comment by Calinou** [comment] 2021-09-29 13:47
Duplicate of https://github.com/godotengine/godot-proposals/issues/1074 and https://github.com/godotengine/godot-proposals/issues/909. For features not covered by the proposals I linked, please open separate proposals with *one* proposal per feature.

**Closed by Calinou** 2021-09-29 13:47 UTC
Labels: topic:editor
