### ISSUE TITLE
Add local project templates to the project manager

### ISSUE THREAD

**Issue by Volcano339** [godotengine/godot-proposals#3388] opened 2021-10-05 14:54 UTC
### Describe the project you are working on

Various prototypes with common defaults.

### Describe the problem or limitation you are having in your project

Currently, there is no way to make a new project with default scripts or add-ons, which can be inconvenient if you are working on many similar projects or just need a common base to start working on.
The only alternative is to copy the project and edit the metadata.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Project templates can make new projects with boilerplate code/resources more convenient to set up.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

There are two ways of going about the interface I could think of.

1. Add a new tab with a list of templates similar to the Local Projects tab.
2. Add a template path input to the new project dialog.

With 1, we could get the list from a specified template path (similar to UE4), or we could make an "Import Template" button similar to Local Projects.
It might also be nicer to use a separate tab because we could have a list/grid with thumbnails like in Local Projects.

Then, we could get the files of the project and copy them into a specified directory and change the name inside of project.godot.

I would like to try to implement this myself as I think it could be a good way to get into contributing code to Godot.
Any help would be appreciated if you would like to help me since I'm new to contributing to Godot.
Luckily, a good amount of the functionality needed seems to be implemented in other parts of the project manager.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know of any way to modify the project manager through script, and I don't think this would pose a problem if you don't use it.

### Is there a reason why this should be core and not an add-on in the asset library?

As I said, I don't know of any way to modify the project manager through script.

**Comment by Calinou** [comment] 2021-10-05 15:17
Duplicate of https://github.com/godotengine/godot-proposals/issues/1481.

**Closed by Calinou** 2021-10-05 15:17 UTC
