### ISSUE TITLE
Add a HashSet type to GDScript

### ISSUE THREAD

**Issue by formerly-a-trickster** [godotengine/godot-proposals#4549] opened 2022-05-16 14:15 UTC
### Describe the project you are working on

I'm working on a grid-based tactical RPG that makes heavy use of set membership operations.

### Describe the problem or limitation you are having in your project

What most range-checking amounts to is having a set of Vector2s and then asking if a given Vector2 is inside that set. This is used all over the place, to check if a tile is reachable by a unit, if it's inside its threat range, for pathfinding, and so on. Arrays work fine for this, but only up to a point. They search linearly over themselves and do not preserve the uniqueness invariant (I have to check if a Vector2 is already in an Array before I can add it, to make sure i only ever have one of each). In some places I am using Dictionaries as a poor man's Set, where the keys are the values I'm interested in and the values are some meaningless placeholders.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding Sets as a built-in data type.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Ideally they would work like Sets in Python, but I will hazard a guess that adding them as such an integrated built-in might not be feasible and / or clash with internal stuff (for example, are sets now part of the Variant family?).

Barring that, we'd have a `set()` constructor for empty Sets that optionally takes an Array for initial population values. `insert`, `erase`, `find`, `difference`, `intersection` and `union`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I am meaning to make a Set class that uses Dictionaries under the hood so I can at least have a clean interface to work with for when I'm going to invariably move this to a C++ module. It is 100% work-around-able. As for how often Sets are used, I find that once you work on a project that needs them, you use them A LOT.

### Is there a reason why this should be core and not an add-on in the asset library?

Basic building block data structures offer a lot of bank for buck when it comes to programming. If Sets were to eventually become first-class in the language, they would need deep integration with it.

**Comment by Calinou** [comment] 2022-05-16 20:50
Duplicate of https://github.com/godotengine/godot-proposals/issues/867.

**Closed by Calinou** 2022-05-16 20:50 UTC
Labels: topic:core, topic:gdscript
