### ISSUE TITLE
More natural and easier way to write C++ 

### ISSUE THREAD

**Issue by gitcatrat** [godotengine/godot-proposals#862] opened 2020-05-20 07:03 UTC
**Describe the project you are working on:**
City builder type game with a twist. It has a lot of procedural content and mesh generation. I've used C# so far but I'd like to move most of the generation to C++. I also want to use third-party C++ libraries which are either not written in C# or are sketchy (e.g straight skeleton subdivision).

**Describe the problem or limitation you are having in your project:**
Writing C++ feels very unnatural in Godot, especially compared to Unreal. Writing C++ in Unreal feels like writing C# in Godot - you just create a class, write your logic and hit compile. It's done! Godot has a whole ritual dance around C++: SCons file, several text based files in Godot, third cpp file, have to mess around with terminal, etc. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
C++ should be just as easy as C# in Godot.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Unfortunately I don't know anything about this process. But I think we'd need to define a "developer C++ land" boundary, it could be a specific directory in project root where all C++ goes (plus points for configurability). Then there should be a compile button that compiles all the C++ files in that directory. Would also be great to have an UI for generating new C++ class files with all the boilerplate already written. UI should have different options like class name, what it inherits, etc.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I think this is what everyone who write any C++ would use.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It makes C++ development so much easier (both in effort and understandability) and faster.

**Comment by Calinou** [comment] 2020-05-20 07:57
Duplicate of #573 and #119.

**Closed by Calinou** 2020-05-20 07:57 UTC
