### ISSUE TITLE
Show the docs for the selected function & argument in the script editor's tooltip

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot-proposals#3075] opened 2021-08-01 23:46 UTC
### Describe the project you are working on

A game with scripts, written using the built-in script editor.

### Describe the problem or limitation you are having in your project

If I'm not sure what a function's argument does, then I have to pull up the function's documentation, which takes time and requires me to switch tasks.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In the tooltip that shows the names and types of a function's arguments, display the current/selected argument's description from the documentation.

Current:
![image](https://user-images.githubusercontent.com/50304111/127788914-f4a6a14c-88d2-48b6-a445-6e15da7be6ab.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Example from Visual Studio:
![image](https://user-images.githubusercontent.com/50304111/127788869-71d22baf-6bb7-4289-b89d-619683a84512.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not that I'm aware.

### Is there a reason why this should be core and not an add-on in the asset library?

The script editor is core, and this would benefit everyone.

**Comment by pycbouh** [comment] 2021-08-02 00:07
PR that implements it: https://github.com/godotengine/godot/pull/41502

**Comment by Calinou** [comment] 2021-08-02 00:17
Duplicate of https://github.com/godotengine/godot-proposals/issues/1393.

**Closed by Calinou** 2021-08-02 00:17 UTC

**Comment by LightningAA** [comment] 2021-08-02 00:37
> Duplicate of #1393.

Thanks, I sometimes have a hard time finding duplicates.
