### ISSUE TITLE
Allow multiple fonts to render one "glyph unit", like a glyph + diacritics/accents

### ISSUE THREAD

**Issue by dhoverml** [godotengine/godot-proposals#9043] opened 2024-02-07 13:53 UTC
### Describe the project you are working on

A project with language localizations, where the system may not have system fonts (like web export).

### Describe the problem or limitation you are having in your project

When developing a game with multi-language localization for the web, the developer must define font fallbacks because [web export does not support loading system fonts](https://github.com/godotengine/godot/issues/77903#issuecomment-1640994134). When providing a text input field, a user may switch between languages while typing, which means that glyphs from multiple fonts might be typed in the same text input. When typing an Arabic accent from one font after a Latin character of another font, Godot will render two tofu glyphs instead, disrupting the user experience.

For example:
When I type the letter `a`, I see the letter `a`.
Then when I add an Arabic accent, I get two tofu glyphs: ![tofu_glyphs](https://github.com/godotengine/godot-proposals/assets/135338122/60c3a671-c9ba-405b-b4a8-6771be9c2c77)
I expected something similar to this (I typed `a` then `shift-q` using Arabic input in my browser's url bar): ![accent_url_bar](https://github.com/godotengine/godot-proposals/assets/135338122/47f24d99-fb1e-4bf7-b05b-65cd201659b0)
I think this is a missing feature despite looking like a bug.

Repro steps (tested with v4.3.dev.custom_build [d3352813e] on Ubuntu 20.03 LTS)
1. Compile the editor with `fontconfig=false` to prevent using system fonts in the editor
2. Launch the editor and create a `LineEdit` node
3. Click on the `LineEdit` node, and `Theme Overrides -> Fonts -> Font -> Choose FontVariation`
4. For the base font, choose AlbertSans-Regular.ttf
https://fonts.google.com/specimen/Albert+Sans?query=Sans&sort=alpha&subset=latin&noto.script=Latn
5. For a fallback, choose NotoSansArabic-Regular.ttf
https://fonts.google.com/noto/specimen/Noto+Sans+Arabic?query=noto&subset=arabic&noto.script=Arab
6. Ensure you can switch your system's input language between English and Arabic (this is easy to set up in Ubuntu: follow step 1 at your own risk in [Steps to reproduce](https://github.com/godotengine/godot/issues/87016))
7. Launch the app
8. Make sure your system's input language is `en`, click on the `LineEdit` and type `a`.
9. Switch your system's input language to `ar` and press `shift-q` to add an accent
10. Notice the two tofu glyphs

The only font I can find on my desktop to handle this scenario as a font fallback in Godot is DejaVu.
On my desktop outside of Godot, the shape of the original letter doesn't change with/without the accent so I don't think it is falling back to DejaVu (nor do I think it's using DejaVu by default, but hard to tell).
Also, I think it is normal to combine glyphs ([like this](https://graphicdesign.stackexchange.com/a/109918)).  So combining glyphs from separate fonts might be okay too especially considering it would be more legible than tofu glyphs.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

See title

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

This is core functionality.

**Comment by Calinou** [comment] 2024-02-07 16:44
cc @bruvzg

**Comment by bruvzg** [comment] 2024-02-07 17:28
Normally character + diacritic are a single grapheme cluster, for most purposes it should be considered indivisible (and it's highly preferred to render it using the same font, since in a lot of the cases it's substituted by a single glyph). But I guess we can add an extra fallback step if the normal path fails.

**Comment by dhoverml** [comment] 2024-02-07 17:31
Looking closer at what my desktop did, it might not be combining `a` and the accent mark.
As in, it tried to add the accent mark to the letter `a` but the font didn't support it.  So, it just drew it next to the letter `a`.

**Comment by peterhoglund** [comment] 2024-02-07 19:08
We use a proprietary engine in the studio I work at where we define a list of fonts. We have our default font which has been decided by the art team. But if a glyph is not available in that font it will check the next font, and then the next and so one. Usually the other fonts are for Asian languages or Cyrillic. But it is also a great way to include our own custom font where we store special glyphs, like custom icons for button hints, resources, in game currencies, etc where you need a custom icon within the text.

**Comment by bruvzg** [comment] 2024-02-07 19:20
> But if a glyph is not available in that font it will check the next font, and then the next and so one. Usually the other fonts are for Asian languages or Cyrillic.

You can't check it for single glyphs one by one, since it won't work with complex scripts, our font selection process looks something like:
- Split text into uniform runs (same script, same direction, etc. using ICU).
- Try to shape each run using HarfBuzz, if part of the run fails, retry shaping faulty sub-runs with the next fallback font.

The issue is likely caused by the fact both characters are part of the same grapheme cluster, and the whole cluster is marked as invalid, not just individual characters. Which seems to be correct behavior in general, but will fail for both fonts in a case like this. Fixing it will likely require a second pass, which will simply look for the individual glyphs without shaping.

**Closed** 2024-02-15 16:36 UTC
Labels: topic:gui
