### ISSUE TITLE
Add ability to rotate tiles placed on TileMap in v4.0

### ISSUE THREAD

**Issue by blipk** [godotengine/godot-proposals#5158] opened 2022-08-13 13:43 UTC
### Describe the project you are working on

2D Platformer

### Describe the problem or limitation you are having in your project

I need the ability to rotate tiles when placing them, without creating excessive copies on my tile sheet.

In 3.4 it this was possible, however in 4.0.alpha13 I can't see an option anywhere to be able to rotate placed tiles.
(Excuse me if I'm blindly missing this)

I tried applying a material with a shader to the tile and rotating the UV, but it seems the TEXTURE for the tile contains the whole tile sheet and any transformations I attempted would include other tiles from the sheet - this might be another bug.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Option in the TileMap resource section of the editor to rotate tiles before painting them, helps build more detailed worlds without duplicating asset production.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Similar to 3.4, buttons to rotate or flip the selected tile when in single tile paint mode on a TileMap.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not sure, I could maybe change the collider in the physics layer as well as a shader for the UV somehow, but like I said I attempted this

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving TileMap usability out of the box.

**Comment by blipk** [comment] 2022-08-15 05:37
Closing in favour of #4949

**Comment by halgriffiths** [comment] 2022-08-15 09:50
Personally I am not super happy with it, but in theory the idea is that in 4.0 you are supposed to create Alternative Tiles via right clicking, and then those alternative tiles can be rotated (but not the parent). It wont rotate the collision/navigation shapes atm though, hence my proposal https://github.com/godotengine/godot-proposals/issues/4949

**Comment by blipk** [comment] 2022-08-15 10:13
Thanks for the response @halgriffiths 
I agree the alternative tiles and new TileMap/TileSet is a bit of added complexity, but it offers a lot of flexibility, just a shame it's not exposed to GDScript as much as it was in 3.4, so I could be able to access the physics layers polygons and at least automate creation of alternative tiles with different collision polygons.

I think your PR is a good solution, being able to toggle layer inheritance for the various layers, and autocreating a few alternatives in each transformation would be good too.

I think there would be a lot of request for this as it saves a lot of work manually fiddling with alternatives, I hope the maintainers can see that.

**Comment by KoBeWi** [comment] 2023-07-25 21:27
Closing as duplicate of #3967

**Closed by KoBeWi** 2023-07-25 21:27 UTC
Labels: topic:editor, topic:2d
