### ISSUE TITLE
Replace numeric resource IDs in .tscn files

### ISSUE THREAD

**Issue by kjav** [godotengine/godot-proposals#2917] opened 2021-06-24 21:49 UTC
### Describe the project you are working on
3D Mobile Game

### Describe the problem or limitation you are having in your project
Merging scene file conflicts when using git is very difficult, partially due to the numbering of resources / children.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I propose that instead of resources being numbered in the scene files, they be given a fixed unique ID each. This will make merging the files way easier, as adding / removing a node currently affects the numbering of all subsequent resources; by using a fixed unique id, adding or removing any resource wouldn't affect the id of any other resource.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Currently, the top of a scene file looks something like this, with numeric IDs:
```
[ext_resource path="res://BlendTreeCharacter.tscn" type="PackedScene" id=1]
[ext_resource path="res://Character.gd" type="Script" id=2]
```

Instead, these could be replaced with e.g. the first 8 digits of the SHA256 of the file path:
```
[ext_resource path="res://BlendTreeCharacter.tscn" type="PackedScene" id="5c1c6b7c"]
[ext_resource path="res://Character.gd" type="Script" id="c1ac0faa"]
```
This would mean that the ID was still deterministic, but not dependent on its position in the list of resources.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
Source code versioning is an integral part of game development, and improving compatibility with it could improve the engine's utility in larger teams.

**Comment by pycbouh** [comment] 2021-06-24 21:54
Duplicate of #471.

**Closed by pycbouh** 2021-06-24 21:54 UTC
