### ISSUE TITLE
Add global position/rotation/scale properties to Node3D

### ISSUE THREAD

**Issue by thehatless** [godotengine/godot-proposals#3581] opened 2021-11-21 14:36 UTC
### Describe the project you are working on

A 3d adventure game

### Describe the problem or limitation you are having in your project

The methods for getting global spatial data are very opaque (the simplest method of getting an object's global rotation is **global_transform.basis.get_euler()**.) There isn't any built-in method of *setting* a global rotation or scale.

These are fundamental operations. They should be too simple to require thought.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

[This PR](https://github.com/godotengine/godot/pull/55200) adds global_position, global_rotation and global_scale properties to **Node3d** (**Node3d** is Godot 4's version of **Spatial**.)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The [linked PR](https://github.com/godotengine/godot/pull/55200) includes code and documentation.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There is no built-in method to set global rotation or scale values. The methods for getting global pos/rot/scale are not discoverable without praying to google. These are common actions and should, imho, be simple and clear.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a quality of life improvement for a much-used part of the engine.

**Comment by LightningAA** [comment] 2021-11-21 16:15
Duplicate of https://github.com/godotengine/godot-proposals/issues/3033, but that issue forgot to mention `global_scale` so maybe it should be closed instead?

**Comment by Calinou** [comment] 2021-11-21 16:37
There was another pull request implementing this feature as well: https://github.com/godotengine/godot/pull/50755

**Comment by akien-mga** [comment] 2022-06-30 15:19
Duplicate of #3033.

**Closed by akien-mga** 2022-06-30 15:19 UTC
Labels: topic:core, archived, topic:3d

**Comment by aaronfranke** [comment] 2022-09-18 21:40
For the record, this was implemented in https://github.com/godotengine/godot/pull/50755 but this proposal is a duplicate.
