### ISSUE TITLE
Add the Ability to Use the Keyboard Arrow Keys to Increase/Decrease Variables in the Editor

### ISSUE THREAD

**Issue by Lauson1ex** [godotengine/godot-proposals#2467] opened 2021-03-15 23:58 UTC
### Describe the project you are working on
This is a quality of life improvement proposal that applies to all my projects.

### Describe the problem or limitation you are having in your project
Clicking on a field and pressing the keyboard arrows keys up or down have always been an intuitive way to alter values in software since millennia. Yet, this feature is not present in the Godot editor for some odd reason. The lack of this feature always disrupts the flow of my work.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Like #2466, this is a quality of life improvement which aims to make using the editor a smoother and more pleasant experience to users.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
You click on a variable field in the editor, press arrow key up to increase a variable/go up an item in the list, or press arrow key down to decrease said variable/go down one item in the list.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This will be used often and this is core.

### Is there a reason why this should be core and not an add-on in the asset library?
This is core.

**Comment by Calinou** [comment] 2021-03-16 00:33
Duplicate of https://github.com/godotengine/godot-proposals/issues/2099 (same idea).

**Closed by Calinou** 2021-03-16 00:33 UTC
Labels: topic:editor
