### ISSUE TITLE
Add ampersand `&` in front of StringName added via auto-completion

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot-proposals#7608] opened 2023-09-05 16:04 UTC
### Describe the project you are working on

A snake

### Describe the problem or limitation you are having in your project

While optional, I prefer keeping my code clear by adding ampersand `&` in front of a string `"name"` whenever a StringName is expected. This includes input action names as in:

```gdscript
event.is_action_pressed(&"jump")
```

However, auto-completing such strings:
![image](https://github.com/godotengine/godot-proposals/assets/1067772/af4b4a7e-06f2-4c26-9b90-3dbef838b2f3)

Does not add the ampersand `&`:
![image](https://github.com/godotengine/godot-proposals/assets/1067772/dbaae558-a986-469e-a0ee-f9da7de57e1c)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When adding a StringName via auto-completion, the string would be prefixed with ampersand `&`, e.g. `&"jump"`

so we don't have to add it manually.

For me, it's a small QoL improvement. For beginners, it may be teaching them good habits for later.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I see two ways to handle this:

A. Based on completion source:
1. first, the engine would need to recognize strings that are coming from parameters usually used passed as StringNames. Currently, they seem to be indicated with a .C for "constant" (see screenshots above). If constant is not exactly equivalent to strings expected as StringNames, then this may need an extra check.
2. then, on auto-completion from this source, the editor would add `&` in front of the string, if not already added manually by user

B. Based on parameter type:
Independently of where the string auto-completion came from, add a `&` in front of it if if the expected parameter type is StringName, and if not already added manually by user.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it's core editor stuff. The best workaround is to manually add `&"` (if you just type `&` unfortunately, it will stop prompting for auto-complete, which is another issue; so you need to type `"` afterward).

### Is there a reason why this should be core and not an add-on in the asset library?

Too close to core editor code.

**Comment by KoBeWi** [comment] 2023-09-05 19:32
Duplicate of #5496 (also has a PR)

**Closed by KoBeWi** 2023-09-05 19:32 UTC
