### ISSUE TITLE
Move "Export With Debug" checkbox from FileDialog to Export Dialog

### ISSUE THREAD

**Issue by theowiik** [godotengine/godot-proposals#1270] opened 2020-07-28 07:49 UTC
**Describe the project you are working on:**
A Godot game.

**Describe the problem or limitation you are having in your project:**
I want to export the project without debug enabled, but it is very confusing where that option is.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Move the "Export With Debug" checkbox from FileDialog to Export Dialog where all the other options are. It helps by keeping all options in the same place.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Move the checkbox to the "Options" tab in the export dialog.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No

**Is there a reason why this should be core and not an add-on in the asset library?:**
Since it is a default feature

**Comment by Calinou** [comment] 2020-07-28 07:55
Duplicate of https://github.com/godotengine/godot-proposals/issues/1071.

**Closed by Calinou** 2020-07-28 07:55 UTC
