### ISSUE TITLE
Keep grid snap set on, when disabling the grid in Visual script / graph edit . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3102] opened 2021-08-07 16:37 UTC
### Describe the project you are working on

A 2.5D game, with barbarians . . :OO . .

### Describe the problem or limitation you are having in your project

Atm, when one disables the grid, in a Visual script, snapping is also disable . . Visual scripts are already difficult to read, for big scripts, and it bec. all sorts of ' spaghetti ', if there's no snapping . . . I was thinking, maybe keep snapping, when the grid is disabled, bec. I don't know why any-one would want to use a Visual script, with no snapping . . . <3

![Animation](https://user-images.githubusercontent.com/83387915/128607271-7e3cb427-b7d8-4b88-b38b-47ca2b41e67c.gif)

Visual scripts just get much more dis-ordered, when one doesn't have snapping, or maybe make so, one can set snapping, with a different icon or, so . .

Right now, I don't use the feature, bec. things simply get more 'unreadable', when the lines and, boxes aren't stacked or, ' ordered ' . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, make it so that, with the grid not visible, snapping still works . . . Graph edits are already plenty ' spaghetti ' and, with no snapping, it just gets almost 'unreadable' . . .

It sort of, goes from ordered, to semi - chaos :OO . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, make it so snapping is set on, for grid on / off or, make it a different setting, so they can be set, separately . . :OO 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Again, I don't think I can change this, as a beginner user . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it's a small improvement, not sure how to do this, maybe there's a better answer <3 . .

Thanks, for the amazing updates, in Godot 3.4, it's those small things, that makes us think, Visual script isn't forgotten . . .

A little nod, that it's getting some help-ful updates or, improvements . . . .

**Comment by pycbouh** [comment] 2021-08-07 16:45
This is a duplicate of your own proposal: https://github.com/godotengine/godot-proposals/issues/2111

**Closed by pycbouh** 2021-08-07 16:45 UTC
