### ISSUE TITLE
Add the Window command menu on macOS

### ISSUE THREAD

**Issue by valentinegb** [godotengine/godot-proposals#7768] opened 2023-09-20 18:00 UTC
### Describe the project you are working on

This proposal applies to all projects which are being developed on macOS.

### Describe the problem or limitation you are having in your project

The essential and standard macOS Window command menu which is expected by all macOS applications does not exist for Godot.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the Window command menu and its commands.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The Window command menu would be placed after the Editor menu and before the Help menu, as is convention on macOS. It should contain the Minimize, Zoom, Tile Window to Left of Screen, Tile Window to Right of Screen, Replace Tiled Window, and Remove Window from Set commands.

<img width="598" alt="Screenshot 2023-09-20 at 10 54 46 AM" src="https://github.com/godotengine/godot-proposals/assets/35977727/6e9b9591-9cfc-447c-9b54-dbb05e380e73">

This mockup was created with SwiftUI, so it would've been a hassle to remove the "Godot" item at the bottom of that Window command menu. I do not intend for that to be part of the proposal. However, it would actually be quite nice and address another issue, #6442.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The proposed changes would not effect anyone who decides not to use the new commands, besides from maybe anyone who maybe clicks the Window command menu accidentally whilst trying to click the Help menu, in which case the only repercussion is a moment of delay.

### Is there a reason why this should be core and not an add-on in the asset library?

The Window command menu is *standard*. It is expected to just be there, for all macOS applications. Users should not have to go out of their way to add basic functionality to Godot.

**Comment by Calinou** [comment] 2023-09-20 20:39
cc @bruvzg

**Comment by bruvzg** [comment] 2023-12-18 17:36
`Window` menu is added in https://github.com/godotengine/godot/pull/83987

But it won't fix https://github.com/godotengine/godot-proposals/issues/6442, since it's caused by Godot using multiple process (so it can't be fixed without implementing https://github.com/godotengine/godot-proposals/issues/8151).

**Closed by bruvzg** 2023-12-18 17:36 UTC
Labels: topic:porting, platform:macos
