### ISSUE TITLE
Collab in realtime

### ISSUE THREAD

**Issue by TheDragonkeeper** [godotengine/godot-proposals#4724] opened 2022-06-22 14:33 UTC
### Describe the project you are working on

A 2D  multiplayer retro space game with a small team

### Describe the problem or limitation you are having in your project

if someone wants to contribute to the project i would have to:
- setup a version control system like git 
- wait to commits before seeing what they have contributed 
-  test their work before attempting to merge it 
-  deal with conflicts

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

We could work together at the same time.
We could see the files being edited in real time  and even the editor scene being edited in real time.
Commits/versioning would not be needed as everyone will be working on your editor or a server only version in a host-client setup

This could be used for small teams to work out solutions together, design levels/scenes together, to assist in someone explaining their thought processes, teach members about godot in general, teach how to do certain parts and really just make development quicker.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The Host could be a headless server or just your editor.
-Each client would connect via domain/IP with a chosen port
-Every users mouse or cursor would be displayed and move in realtime 
-Every users actions will update files in realtime
-Every user will be asked for a username and be assigned a colour so you can keep track of what they are doing and where they are accessing
![concept2](https://user-images.githubusercontent.com/15315110/175053440-4c67aca5-7bc3-460d-8f46-4ac7998a503e.png)

![concept](https://user-images.githubusercontent.com/15315110/175053487-dd885dd3-0416-4d41-a733-e5d929fa9c3a.png)

Users should be able to upload their own assets 
and in general be a multi user editor

The host could even set permissions for users to restrict them to certain parts for bigger projects but still allow the host or admin users to overlook the work/progress

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The only work around is only for scripts and is an external program but would cause the editor to keep asking to reload which would be inconvient.

### Is there a reason why this should be core and not an add-on in the asset library?

Im unsure but i believe this would have to be intergrated in someway to be useable.

**Comment by Calinou** [comment] 2022-06-22 21:00
Duplicate of https://github.com/godotengine/godot-proposals/issues/851. That said, feel free to post your mockups as a comment in that proposal :slightly_smiling_face:

**Closed by Calinou** 2022-06-22 21:00 UTC
