### ISSUE TITLE
ParticleAttractor2D

### ISSUE THREAD

**Issue by feois** [godotengine/godot-proposals#6624] opened 2023-04-04 07:00 UTC
### Describe the project you are working on

In my project, I want the coin particles to fly towards player. I've tried modifying the material properties but the docs aren't very helpful so I don't know if it's possible through modifying properties alone. After a few days, I've found out that there's a property about attractor interaction but I recall nothing about attractor in the docs. I tried searching about it but all I've found is closed issues (godotengine/godot#18223, #815, https://godotengine.org/qa/18765/particle-attractor-in-godot-3) years ago saying that they will be implemented in Godot 4. Has it been forgotten?

### Describe the problem or limitation you are having in your project

I want the coin particles to fly towards player but I don't know if it's possible through modifying material properties alone.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add ParticleAttractor2D

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I don't know how ParticleAttractor2D works (cuz there's close to zero discussion or video about it on the Internet) but looking at some videos about ParticleAttractor3D, I think it will fit my needs.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know, I hope someone can answer me.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't know how to implement it as an add-on.

**Comment by feois** [comment] 2023-04-04 07:04
BTW, I've tried asking about it on the Discord server but no one answered me, I'm not sure where is the best place to ask solutions for my issue.

**Comment by feois** [comment] 2023-04-04 07:18
> This might be turned into a discussion, and in the future this kind of suggestion with limited or no concrete suggestion is best handled by opening a discussion

How to open a discussion

**Comment by AThousandShips** [comment] 2023-04-04 07:34
Just keep this open and see, it does suggest just creating an equivalent of the 3D one and think that can be enough!

**Comment by Calinou** [comment] 2023-04-04 15:44
- Duplicate of https://github.com/godotengine/godot/issues/60909.

Particle attractors are only implemented in 3D, not 2D.

**Closed by Calinou** 2023-04-04 15:44 UTC

**Comment by feois** [comment] 2023-04-05 04:55
> * Duplicate of [Vulkan: GPUParticles2D attractors not implemented yet (unlike in GPUParticles3D) godot#60909](https://github.com/godotengine/godot/issues/60909).
> 
> Particle attractors are only implemented in 3D, not 2D.

Thanks, couldn't seem to find related issues, guess I need to improve my googling skill. Is there any alternative/workaround for now though? (I'm not very good at particles, sorry for that)

**Comment by Calinou** [comment] 2023-04-05 12:50
> Is there any alternative/workaround for now though? (I'm not very good at particles, sorry for that)

- Use RigidBody/CharacterBody nodes instead of particles. This is expensive, and only viable with a few dozen particles at most (maybe a hundred). You could lump several particles in the same texture to make it look like there are more particles than there really are, at the cost of GPU fillrate.
- Use a custom particle shader to implement attraction.
