### ISSUE TITLE
Add a way to open the script editor in its own window.

### ISSUE THREAD

**Issue by brisdalen** [godotengine/godot-proposals#480] opened 2020-02-15 13:31 UTC
**Describe the project you are working on:**
A small mobile app with spaceships
**Describe the problem or limitation you are having in your project:**
I have to constantly switch between the 2D windows and the script editor
**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Having the ability to open the editor in another window allows me to use it on my 2nd monitor
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I don't have enough experience with GUI's or the architecture of Godot, but I imagine a simple button next to the full-screen button that opens the script editor in its own window.
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I do not know.
**Is there a reason why this should be core and not an add-on in the asset library?:**
I'd think more people would be interested, but I didn't find another issue with the same proposal, so who knows.

**Comment by Calinou** [comment] 2020-02-15 13:53
Duplicate of #28.

**Closed by Calinou** 2020-02-15 13:53 UTC

**Comment by brisdalen** [comment] 2020-02-15 14:56
Oh, I tried searching the list of issues searching for Window, Pop out and the likes. Thanks for the redirect.
