### ISSUE TITLE
Regular Label

### ISSUE THREAD

**Issue by thenegativehunter2** [godotengine/godot-proposals#5614] opened 2022-10-18 16:50 UTC
### Describe the project you are working on

I just want a regular label that can format it's own text.

### Describe the problem or limitation you are having in your project

there is no such thing in godot.
RichTextLabel doesn't have something as basic as size fitting.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A regular label, with custom per character underline, boldness and so on.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

just make a single line label that accepts bbcode or add size fitting to RichTextLabel

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Nope. you can't even retrieve the unmarked text from the bbcode you put in richtextlabel to use a single font function for it.

### Is there a reason why this should be core and not an add-on in the asset library?

it's a SHAME on godot to not have something so simple. in fact as a godot user, if someone asks me while the engine you are using can't do it, i will feel nothing but shame.
want to make a top menu with the shortcut letter underlined? CAN'T! just imagine that..
why should this be a pain to do...

**Comment by Calinou** [comment] 2022-10-18 22:44
Duplicate of https://github.com/godotengine/godot/issues/18260.

**Closed by Calinou** 2022-10-18 22:44 UTC
