### ISSUE TITLE
AudioStreamPlayer2D should be allowed to do only distance attenuation for the volume and disable panning of the stereo channels.

### ISSUE THREAD

**Issue by JoanPotatoes2021** [godotengine/godot-proposals#3551] opened 2021-11-15 19:11 UTC
### Describe the project you are working on

2D Isometric game

### Describe the problem or limitation you are having in your project

No way to disable the panning of the right and left channels while still keeping the distance attenuation.

Main use case is for ambience sounds and sometimes dialogue, which we don't want the panning of the channels, but may still want the distance attenuation for the volume, ambiances aren't positioned on a single coordinate, they represent a collective of sounds which emannate around a place, and are not centered.

There could be more use cases as this is only asking to disable audio panning but keep the distance attenuation for the volume.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Calculate the panning only based on the distance over the `viewport` or `listener2D` but not the direction. This will allow both right and left channels to still work just as before but will only work with the attenuating the distance, and not with panning.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change how panning is calculated in this function `void AudioStreamPlayer2D::_update_panning()` https://github.com/godotengine/godot/blob/master/scene/2d/audio_stream_player_2d.cpp#L138 , by checking for a extra boolean from the inspector, to change how panning works by just considering the distance to reduce the volume, not the direction to control the panning of the stereo channels of the sound emitter.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No and maybe yes, it requires a combination of nodes which will need to always be checking for the distance of the player and controlling the volume of a `AudioStreamPlayer` to emulate distance attenuation, this will be however extremely limited as we can't control attenuation curves like it works with `AudioStreamPlayer2D` and we can't preview the audio max distance from the editor.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, it's a extension of `AudioStreamPlayer2D` which will improve the artistic freedom of the engine and the implementation of this feature is very simple.

**Comment by Calinou** [comment] 2021-11-16 13:16
Duplicate of https://github.com/godotengine/godot-proposals/issues/3384.

**Closed by Calinou** 2021-11-16 13:16 UTC
