### ISSUE TITLE
Use GUID for Scene Resource Ids to prevent collisions when collaborating on the same scene file

### ISSUE THREAD

**Issue by caemanswartz** [godotengine/godot-proposals#4921] opened 2022-07-19 20:49 UTC
### Describe the project you are working on

I am currently working with others on a walking simulator / chat application using Godot mono 3.4.4 with others.

### Describe the problem or limitation you are having in your project

When working on the same scene and creating pull request there are often resource ID collision that require either manually editing the scene file or removing the linked resource, performing a rebase after merging one pull, and then adding the resource to the scene again.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If the Resource Id value was a GUID instead of an incrementing integer, the collisions would happen much less and people could work on and make pull request for the same scene without having to be careful of the order that they work on scenes and merge branches.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In the scene files, instead of using an integer to reference resources, it would assign GUIDs to resources so the chance of collision would be less. If this would be too cumbersome for execution, the the GUIDs could be swapped for integers on export.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not familiar enough with Godot to know if it is possible to circumvent the Id assignments but I feel this would be something like manually loading each resource using a script instead of building scenes using the editor.

### Is there a reason why this should be core and not an add-on in the asset library?

Godot touts that is is collaboration friendly but this seems to be a major hurdle for working with others simultaneously.

**Comment by Calinou** [comment] 2022-07-19 20:52
Duplicate of https://github.com/godotengine/godot-proposals/issues/2430. This is already implemented in 4.0.alpha but won't be in 3.x for compatibility reasons.

**Closed by Calinou** 2022-07-19 20:52 UTC
