### ISSUE TITLE
animationplayer based in fps option

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#3541] opened 2021-11-13 10:46 UTC
### Describe the project you are working on

A retro-style project at 20 fps

### Describe the problem or limitation you are having in your project

AnimationPlayer is based on time, not fps.
This is valid for high fps but not for low fps.
Example:
I have a 10 frame animation.
AnimationPlayer allows me to define the animation in time, but my game is set to 20 fps (because I want to make games in the purest retro style ms-dos, 8 bits microcomputers like Amstrad cpc / spectrum / commodore etc ...), a desynchronization occurs and you have to perform calculations to check the time between frames and the speed of the animation and strange things.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Could you implement an animationPlayer that works with display frames instead of time?
Each frame would be indicated in the time bar, not every X second.
Then it would be easy to make each frame of my animation display for 4 display frames.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

IDK

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, it is possible, but it is also possible to use code to emulate the current behavior of the animationPlayer node.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't know if it's possible

**Comment by Calinou** [comment] 2021-11-13 15:45
Duplicate of https://github.com/godotengine/godot-proposals/issues/2649.

**Closed by Calinou** 2021-11-13 15:45 UTC

**Comment by Torguen** [comment] 2021-11-13 16:26
Oh that's right, I didn't see it in the documentation.
