### ISSUE TITLE
Using the editor from a list of commands

### ISSUE THREAD

**Issue by firststef** [godotengine/godot-proposals#1689] opened 2020-10-19 06:28 UTC
![Image](https://i.imgur.com/XF2kFhl.png)

**Describe the project you are working on:**
For my undergraduate thesis project, I was thinking of making the Godot editor interactable by voice. Like "make a new scene and add a Node3d to it", or other examples. This issue is more of a discussion opener about how I could do this, or how it could benefit the community, etc. I do not ask about the voice module, I am asking here about a way to pass commands to the editor directly.

**Describe the problem or limitation you are having in your project:**
But for this, I would need some way to interface all the operations, possibly through some sort of list/command line/script. I know that you can write a script from the command line, but I think some actions are not achievable by gdscript (or at least, they are not easy to run).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
More complex commands consist of sequential operations, just by running a script would be too tedious - a lot of duplicate code and large instructions. Ultimately you'd end up creating exactly what I described: an interface for running these actions with different parameters.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The solution for this would be to create some sort of a command interpreter, for each user, an action would have a function behind it that receives some parameters and applies the effect. For making a new scene for instance a parameter would be the scene name.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think all actions are accessible by running gdscript, but I could interface these functionalities.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Actually this could be an addon I think, but I could really use some advice from the developers on achieving this. But first - do you think this is doable?

**Other usages for this**
Besides the usage that the user would be able to make a game by voice, this could also be used to run commands and verify the results were as expected: this could be used for continuous integration. Furtermore, by open-sourcing this functionality, users might be able to add more actions.

**My end goal - after this**
Ultimately, if this is implemented (I would do it ofc, or if anyone helps) I would like to improve on this functionality to create a really useful assistant for game developers. We repeat the same tedious actions, actions that we extract from tutorials, things that shouldnt be the main focus of game creation: i recent times we need to create more content than before, and of a greater quality. This assistant would give us more time for the creative process. But again, this is just something I would like to do after this.

**Comment by Zireael07** [comment] 2020-10-19 06:44
@ndarilek is the resident accessibility expert ;) He is blind and has already made amazing steps on making Godot editor usable for others with a similar disability - I don't know if he gives voice commands or not but he would be definitely interested in that feature.

**Comment by pycbouh** [comment] 2020-10-19 08:09
I think that to implement this properly it needs to be an engine module that relies on all other engine modules to provide actions that can be accessed this way. Sort of like shortcuts. All parts of the editor define their own shortcuts, but they are caught and triggered globally. Same here, parts of the editor define actions, and your module acts as an interpreter of the voice that uses those definitions to trigger actions.

As a PoC it can probably just rely on the shortcuts: they have human readable names which can be used for the actions. Implementing additional macros specific to voice commands can be a part 2.

**Comment by Xrayez** [comment] 2020-10-19 10:25
> an interface for running these actions with different parameters.

> parts of the editor define actions, and your module acts as an interpreter of the voice that uses those definitions to trigger actions.

I believe the tools to achieve this can be provided by the actions system as proposed in #70.

**Comment by Calinou** [comment] 2020-10-19 12:37
Duplicate of https://github.com/godotengine/godot-proposals/issues/70.

**Closed by Calinou** 2020-10-19 12:37 UTC
Labels: topic:editor

**Comment by Calinou** [comment] 2020-10-19 13:30
@Zireael07 This proposal seemed to be about providing an API so that voice commands can be implemented. It's a means to an end.

**Comment by Zireael07** [comment] 2020-10-19 13:32
Aaah, missed that. So yeah, if it's not about voice proper, it's a dupe.

**Comment by Xrayez** [comment] 2020-10-19 13:34
GIP could have discussion type of issues describing the use cases, but then again there's #1476 for that. 😉

**Comment by ndarilek** [comment] 2020-10-19 16:01
Not super interested in voice commands, sorry. Better keyboard access would be great, however.
