### ISSUE TITLE
Export CSG Geometry to OBJ as Modelling Reference

### ISSUE THREAD

**Issue by unfa** [godotengine/godot-proposals#1549] opened 2020-09-22 14:31 UTC
**Describe the project you are working on:**

I'm working on a multiplayer FPS game.

**Describe the problem or limitation you are having in your project:**

I'm drafting level geometry using CSG, as it's a great tool for rapid level development and continuous refinement of levels 
Oonce a level design is complete, it's time to make the final geometry, and I'd probably want to do that in Blender.
The problem here is - I don't know of a way to export the CSG geometry from Godot into Blender

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Add an option for the CSG combiner appering in the 3D view to Export CSG geometry to an OBJ file or whatever else. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

file:///home/unfa/image843.png

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I have no idea. I've heard someone is making a DCC in Godot, so probably?

**Is there a reason why this should be core and not an add-on in the asset library?:**

I guess if the CSG geometry is regarded as a level prototyping tool, then the ability to export it as modelling reference seems to be pretty essential.

**Comment by Calinou** [comment] 2020-09-22 14:32
Duplicate of https://github.com/godotengine/godot-proposals/issues/885. (Note that OBJ is a very limited format, and is unlikely to be a good fit for an *export* format.)

**Closed by Calinou** 2020-09-22 14:32 UTC

**Comment by unfa** [comment] 2020-09-22 14:35
I don't really care what format is used - surely somethig libre would be best (GLTF2).
I'm not sure this is a duplicate, because the entire scene export is way more complex topic, and also not really necessary for the need I've listed here.
Though surely it could be a useful tool for fleshing out prototyped levels in external software.
