### ISSUE TITLE
Add a find_first function to Array functions

### ISSUE THREAD

**Issue by ua-knight** [godotengine/godot-proposals#6006] opened 2022-12-27 11:00 UTC
### Describe the project you are working on

Applies to nearly all of my different game projects.

### Describe the problem or limitation you are having in your project

Very often I have an array of objects/nodes which I need to iterate through in search of the first one which satisfies a more complex condition, than just its own value.

For example:

```
func find_faction(faction_id):
	for node in $Factions.get_children():
		if node.data.id == faction_id:
			return node
	return null
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It could be implemented by means of a function in the new Array functions, similar to any, all, map etc.
I notice that 'any' performs almost the same but it returns true or false. The find_first function would instead return the matching object, or null.

`Variant find_first(Callable method) const`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The above example could be rewritten like this:

```
func find_faction(faction_id):
	var arr = $Factions.get_children()
	return arr.find_first(func(node): return node.data.id == faction_id)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around, as I'm currently doing. However, I think it will be used a lot and I also believe that it can be easily implemented by just using the code implementation for 'any' and tweak it to return the object instead of true, or null if no object is found.

### Is there a reason why this should be core and not an add-on in the asset library?

It would be a function which is part of the Array functions, thus core.

**Comment by idbrii** [comment] 2022-12-27 17:17
Sounds great! Maybe it should be `int find_custom( Callable fn, int from=0 )` to match bsearch/bsearch_custom and find.

**Comment by Maran23** [comment] 2022-12-30 19:17
I'm in favor of `find_first` as it is more descriptive.
I know exactly what to expect, namely the **first** element that fits.
While `find_custom` does not really specify that. And what is `custom` in this context anway?

I wonder why the `bsearch` methods were named this way. 
`find_first` does sound better there as well ...

**Comment by Zireael07** [comment] 2022-12-30 19:45
+1 to renaming find_custom to find_first

**Comment by stebulba** [comment] 2022-12-30 20:38
As custom search my dream should be something like this :

get_filtered( FILTER as dictionnay, ORDER as string , NUMBER_RESULT as int)

get_children().get_filtered({"0:position.y:>=": 50.0, "1:position.y:<=": 100.0 })
get_children().get_filtered({"0:name:!=":"boris","1:name:!=":"bob", "0:/child/name:==":"shield", "0:position.y:>":30.0}, "position.y:DESC")

Same for Dictionary:

dictionary.get_filtered({"0:name:!=":"boris","1:name:!=":"bob","0:pos.y:>":30.0}, "pos.x:ASC") # "pos" is a vector2
dictionary.get_filtered({"0:/shield/name:==":"generator3"}, "/shield/power:ASC", 5 )

But that is probably to ambitious to implement something like this in core.

**Comment by idbrii** [comment] 2022-12-30 22:24
> EDIT: The `bsearch` methods are not comparable to this usecase. They try to find the index of a value via binary search. The `custom` in this context means, that a developer can specify an own comparator for the binary search algorithm, e.g. if the default one is not sufficient. 

Ah, I missed this difference. `find_first` is definitely a better name and now it's clear that `find_custom` would be confusing. Good catch @Maran23!

**Comment by jamesmintram** [comment] 2022-12-31 23:39
Could it also be worth adding a `_or_default` variant?

```
var item = items.find_first_or_default(predicate, default_item)
```

Which would return `default_item` in the case where predicate never returned true. This would
save a null check + default assign.

**Comment by idbrii** [comment] 2023-01-01 17:57
> Which would return default_item in the case where predicate never returned true. This would
save a null check + default assign.


@jamesmintram: `find` returns the index, so presumably `find_if`/`find_first` would also return an int. So maybe `find_if(fn, from)` could return the index and `find_match(fn, default, from)` could return the value? Although, the names are pretty similar for such different results.

**Comment by jamesmintram** [comment] 2023-01-01 18:29
@idbrii from the spec above "I notice that 'any' performs almost the same but it returns true or false. The find_first function would instead return the matching object, or null."

**Comment by idbrii** [comment] 2023-01-01 20:19
If we add a function that returns an array value, then it definitely should take a default. An array could contain null, so you can't use that to check for failures to find.

**Comment by tulipan-it** [comment] 2023-01-01 20:45
If the array might contain null values, I think that it would be a task for the method specified in Callable to catch it. So, the consumer's responsibility. For example:

```
arr.find_first(func(item): {
	if not item: return false
	... continue with condition logic
} 
```

**Comment by idbrii** [comment] 2023-01-02 06:02
I mean that this code would be incorrect so we shouldn't support a find function that returns null for "failed to find":
```gdscript
var arr = [null, 10, null, 20]
var select_next := false
var result = arr.find_first(func(item): 
	if select_next:
		return true
	if not item: return false
	if item > 5:
		select_next = true
	return false
)
if result == null: # can't tell difference between "can't find" and null in array
	result = default_value
```

**Comment by tulipan-it** [comment] 2023-01-02 07:52
@idbrii Point taken.

We probably need a return value, independent of the value of the element which satisfied the condition, to signal whether the condition has been found or not. But since the code happens to know the value (of the element) can we not have it return this value as well?

Maybe by using an return array with 2 elements [int, Variant]. The first element is -1 if not found, or the index if found. The second element is null if not found (or an optional default value), or the value (be it null or not), if the condition is satisfied.

Thus, it would be up to the caller to choose how he will use the returned array.

`Array find_first(Callable func, Variant default = null)`

Returns:

Not found, default not given:
 [-1, null]

Not found, default given:
 [-1, default]

Found: 
[index, value]

If you are only interested in any found value, you would call it like so:

`var my_value = arr.find_first(my_callable)[1]
 `

**Comment by tulipan-it** [comment] 2023-01-02 18:57
I see now that it's actually already has been implemented in the PR: 

https://github.com/godotengine/godot/pull/70727

That was fast. Maybe not exactly what I had wished for but I understand that there's many considerations to make when implementing an addition to a basic class. Great work and thanks for the swift undertaking of this!

**Comment by Maran23** [comment] 2023-01-08 15:07
The problem is, that the existing `find` methods were badly named. A better name would be something like `find_index` or `index_of`.
With that said, the method to get an element is `get`. So maybe we can name the method `get_first` instead. We won't clash with the existing `find` syntax and we could actually think of writing a 
- `find_first` method -> returning the index of the first matching element
- `get_first` method -> returning the element of the first matching element

**Comment by matt08-prog** [comment] 2023-01-09 10:39
> Maybe by using an return array with 2 elements [int, Variant]. The first element is -1 if not found, or the index if found. The second element is null if not found (or an optional default value), or the value (be it null or not), if the condition is satisfied.

I renamed the function to find_first in [#70727](https://github.com/godotengine/godot/pull/70727) and can add get_first to the same PR. Should we use @tulipan-it's two element array return value idea for get_first? It seems very concise.

**Comment by idbrii** [comment] 2023-01-10 01:24
I don't know how gdscript handles array allocation, but it seems wasteful to allocate an array when you usually want just the value. (What's the cost of allocating it, marshalling it to gdscript, cleaning it up?) Especially since if you want the index or to check invalidity, then you can call `find_first`.

Returning the item is simpler and least surprising:

```gdscript
int find_first(Callable func, int from=0)
Variant get_first(Callable func, Variant default, int from=0)
```

Requiring a default means it's more obvious what happens if we fail to find the item (it's only null if you passed in null as the default).

**Comment by maximkulkin** [comment] 2023-02-14 14:06
First of all, I'm with you and also want search that uses a predicate instead of a value. I just have concern about the naming: there is an existing `find()` method that takes a value and returns it's index in the array. You're proposing `find_first()` that takes a predicate instead. But it sounds like find_first() returns THE FIRST value while find() does something else. Its not. It also returns THE FIRST value. This is not how those methods differ. So, IMO something like `find_if()` would be a better name.

And don't forget there is a `rfind()`, so it's good to have that one covered too.

Regarding making a separate function that returns the value instead of an index, I'm less interested. And if we will still go that way, I think the default value should default to null. Yet again, you will need to functions (forward and reverse), so I would instead prefer to have one function that returns value by it's index. Oh wait, we already have that.

**Comment by AThousandShips** [comment] 2023-09-17 09:48
Duplicate of #6889

**Closed by AThousandShips** 2023-09-17 09:48 UTC
Labels: topic:core
