### ISSUE TITLE
Improving the visual script .vs file format so it's easier to maintain, add search-replace features . . 

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2574] opened 2021-04-09 03:37 UTC
### Describe the project you are working on
A Tomb raider game, atm . . a bit stuck, on making 3-d models, I need :OO . . <3

### Describe the problem or limitation you are having in your project
Now, I've been wanting a ' change name of a variable ' feature, that also updates all nodes, on the canvas, or boxes . . However, it gets a bit complicated, sadly . . For instance, what if the ' variable ' is also used, or ' called ' in OTHER script, not only the ' open ' one, so I would like not to just have ' update variable name ', instead two options, ' update in current script ', and ' update in all scripts ' . . :OO

Now, to do that, well, here's the idea . . Right now, the .vs format, is a jumbled mess, unreadable . . this might make sense, for compression purposes, but it makes it impossible, to de-bug the .vs, also from perspective, of the engine makers, to find ' bugs ' in the format, like even RSCC bug . . Here's how the .vs format reads, in NotePad, as plain text . . .

![Skærmbillede (1419)](https://user-images.githubusercontent.com/61069740/114123770-4e1e1000-98f3-11eb-85c4-0fd76e3caf79.png)

I opened a .gd, and it read just like in the editor, ie . .

![Skærmbillede (1420)](https://user-images.githubusercontent.com/61069740/114123844-76a60a00-98f3-11eb-95a5-b073a3105fec.png)

Here's the point . . if the .vs format, was written in such a way, it was basically text, and information about arrows, so on . . finding the RSCC bug, might be a lot easier, bec. one could ' follow ' the evolution, of the problem, more easily . . So, updating the format, to be more readable, will long-term mean, it's easier to maintain, the format, fix bugs, at engine level . . and, since .gd are are stored as readable text, it's not as if some-one will steal your code, or so, they can already ' do ' that, with .gd, or so, ie. the encryption happens, when you publish, and everything is stored, in the .pak, any-way . . . people can of course read the code, in many cases, but SOME-TIMES you want, to keep it private, your work, hours, so on <3 . .

If you think about it, there are MANY reasons, to make the .vs format much more readable, basically, as plain text . . :OO because, then you can easily implement a ' search-replace ', to change the name, of a variable, or function :OO . .

However, it is not over :OO . .

In order to replace all instances, of a variable, from the place, where it was declared, also in any other .vs, where it is referenced, for instance as an ' export ' variable, that can be GET, and SET in other .vs files . . I propose, that the way the .vs format ' stores ' variables, is sort of like, how scenes can be instanced, work like, pre-fabs . . that way, if one changes the name, in ONE place, it gets changed, in ALL places, like a prefab instance . . :OO that's how I'd update the .vs format, to ALLOW for search and, replace variable names . . this has many advantages, also making it easier to maintain the format, for engine makers, or Visual script contributors, finding bugs, like the RSCC, so on . . also, .gd is also readable, as normal text . .

it will of course mean a ' slight ' increase in file size, but imo, it would still be unreadable, unless you know, what you're doing, ie. storing coordinates of boxes, so on . . then, to make sure things have the SMALLEST size, one COULD compress the format, when PUBLISHING the game, to give LOWEST file-size, in file game, this would basically make both ' camps ' happy, small file - size AND, a sensible format . . <3

Also, one could make it work, almost like an ' instance ' system, where one just has to change the name, of a ' variable ' in one place, then all ' examples ' of that, get updated, at least in the same script, ie. the stuff in each box, is a prefab, so for like this . .

var bool player_name INSTANCE_NAME = v94224ut24 . .

then, inside ALL the boxes, it has that reference, meaning when you change player_name, the boxes refer to that one place, allowing for search-replace :OO . . and, one could simply add, ' replace in current script ' / ' replace in all scripts ', to allow for 'local' or, 'global' auto-renaming, or updating of node names :OO . . it requires, the format is re-written, so it's structured like a prefab-system, that's all :OO . . gets a bit technical, imo these things would make it easier, for users, also contributors to work and, update, de-bug Visual script, faster, easier . . . . and, we could perhaps finally get SOMETHING, like an ' if you update variable name ', all the ' boxes ' do same :OOO . . Thx . . There are many advantages to this, some of them will only become apparent, some years down line, or so . . that's why, I think it's worth doing now, that's the proposal <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Update the .vs format, so it's 'instance' based, allowing for auto-updating all examples, of a variable, ie. change it's name, then 'all' boxes change name, as well :OO . . . also, update the format, so it's easier to de-bug, improve, for future updates or, bug - fixes <3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Like above, not sure . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I can't do this, as a beginner :OO . . <3

### Is there a reason why this should be core and not an add-on in the asset library?
I think, it ' might ' be worth it, esp. long - term, or so <3 Thx . . . .

Also, it could be a small step, towards a convert .vs to, .gd, which would REALLY be cool, down, the line <3

if you think it, this only has advantages, for every-one, it's just easier, to maintain, fix, other stuff <3 Thx . . . .

ps. if the goal is to have LOWEST possible file - size, I think making the .vs format fully ' readable ' might not, increase size THAT much, like from 4 kb, to 8 - 10 kb :OO and, when publishing the game, it could be ' compiled ', into something much smaller . . if that, is important . . but, I don't think size of .vs files is, what makes or, breaks total size, of games :OO . . . but, there might be a compromise . . also, one could ask question, why not store .gd in a compressed format, like .vs, to save space <3 <3 Sorry, hope this makes sense, might also help find the RSCC bug, bec. you can see, what it is exactly that goes wrong, when ' that ' happens, what ' line ' of code, causes it, if .vs was readable :OO <3

it might seem like a waste of time now, and file - space but, years down the line, it'll have saved 100's of hours, de-bugging, fixing bugs, etc . . that's the reason, I think doing this now, might be a good idea . .

also, technically one could compress .gd . .

so . .

var bool player_walk_state

get player_walk_state . .

became . .

var bool "¤T"

get "¤T"

this would save characters, anyway, don't see a reason, for doing that, for visual script . . the files might be a bit bigger, but COULD be compressed, when publishing, to say PC, Mac, Android, Linux . . it's at that point, one could do any needed compression :OO . . <3 . .

Any-way, visual scripters are, a bit tired, we don't have an ' update ' variable names, same way written code, can do search-replace . . it might be a ' small ' improvement, but it'd be very nice, to have that feature, may-be it's possible, this way <3

**Comment by jasperbrooks79** [comment] 2021-04-09 04:23
ps. this way, if one was cool, one could even ' write ' visual script, like a new ' written ' coding language :OO . .

that way, one could fix visual scripts, without ever opening them, or so <3 Thx . . .

**Comment by SIsilicon** [comment] 2021-04-09 04:59
Wouldn't you just use gdscript at that point?

**Comment by SIsilicon** [comment] 2021-04-09 05:03
But I do agree that Visual Script should be saved in a text-based format. Not only does it make it easier to edit outside Godot, but it also makes it easier on Git, which does not handle binary files too well.

But in that case, this would be a duplicate of https://github.com/godotengine/godot-proposals/issues/938, would it not?

**Comment by jasperbrooks79** [comment] 2021-04-09 05:18
Well, there are several advantages, first of all, maintaining visual script, would be a ' written ' code system, and, also it'd be an ' expanded ' Gdscript system, so people that know that, could maintain it, as 100 % written code . .

The second things is, communicating between visual script workers, and written coders, would be ' instant ' . . Last, let's say one made a written script, and it generated ' boxes ', that were on top of each other, one could just ' move them ', in the visual script canvas, save it, and one would know, what the WRITTEN code, looked like . .

so, suppose one wrote a Gdscript, and when one generated the visual script, some boxes were over-lapping, or so . .

IF var player_bool = true::box_coord[0,0] . .

after moving it, in ' visual script ', it wrote the 'correct' coordinate . .

IF var player_bool = true::box_coord[120,80] . .

that way, written coders could fix ' Visual scripts ', using minimal time, in ' visual script editor ' <3

basically, ' bridging ' the gap, between the two editors, with minimal need, to use ' either ', or so . .

it'd be a massive challenge, but when it's done, maintaining ' visual script ' would be, for written coders, 100 %, if they wanted, speeding up the process, of bug-fixing, adding features, etc . .

the key issue would be, to make sure the generated ' .vs ' aren't bloated, and that coding it, in written code, was fast, perhaps had auto-completion, allowing one to write .vs VERY fast, as one wanted <3 and, it'd finally give us the feature, to see what .vs look like, as written code, as well . . also, allowing minimal need, for using either systems, depending, on what one likes, etc . . .

any-way, it'd be complex, but in long-term, it'd have benefits, for all users, also written coders, I think . . . Thanks . . <3

**Comment by jasperbrooks79** [comment] 2021-04-09 05:40
last, this would get ' rid ' of the RSCC bug, bec. ' visual script ' would be normal Gdscript, in disguise :OO . .

Also, it'd mean you'd only have to maintain 'one' language, not two :OO . .

I think it would have many advantages, de-bugging ' .vs ' could be done, by written coders, all-round, an improvement <3 . .

**Comment by pycbouh** [comment] 2021-04-09 12:32
> But in that case, this would be a duplicate of #938, would it not?

Indeed. Closing in favor of https://github.com/godotengine/godot-proposals/issues/938.

**Closed by pycbouh** 2021-04-09 12:32 UTC
Labels: topic:visualscript
