### ISSUE TITLE
make $ access nodes directly instead of relying on get_node() 

### ISSUE THREAD

**Issue by KripC2160** [godotengine/godot-proposals#3797] opened 2022-01-14 14:03 UTC
### Describe the project you are working on

I am not working on any specific projects 

### Describe the problem or limitation you are having in your project

there has been a [tweet ](https://twitter.com/Game_Fabric/status/1481726029718855686?s=20) that explained how $ is twice slower than using get_node() since it goes through the get_node() first before getting the node 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The $ should be able to access the nodes directly instead of going through get_node() if it's possible 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

when you use $ sign, it takes you directly to the nodes 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This might be one of the most used syntaxes in Godot, since it makes accessing the codes a lot cleaner, and slight enhancement of this feature can improve the performance of the game 

### Is there a reason why this should be core and not an add-on in the asset library?

This feature requires the feature to be implemented within the codes of the core of Godot itself since use of asset would not make any changes or make the performance even slower

**Comment by KoBeWi** [comment] 2022-01-14 14:06
Duplicate of #996

**Comment by pycbouh** [comment] 2022-01-14 14:07
Do note that it is not advised to use `$NodePath` or `get_node("NodePath")` in processing code if you can help it. You should instead store node references in variables. `$NodePath` syntax is best used with `onready` property declaration, for example.

**Closed by KoBeWi** 2022-01-14 14:06 UTC
