### ISSUE TITLE
Add line lights

### ISSUE THREAD

**Issue by Giwayume** [godotengine/godot-proposals#3079] opened 2021-08-03 06:24 UTC
### Describe the project you are working on

3D model of house

### Describe the problem or limitation you are having in your project

In order to accurately model a light strip in Godot today you'd need a very large number of small lights along the strip, this is computationally expensive and the specular doesn't look accurate.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There are a few lighting situations best modeled by a line light, especially in architecture.

![Line_Light](https://user-images.githubusercontent.com/4075314/127967212-79b3ea4b-e0e0-46dd-bf9c-ea2f20cdf136.gif)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Unity has it so I'm sure it's possible.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Even if a custom shader can be written to achieve this, it would require using a custom shader for all materials in the project.

### Is there a reason why this should be core and not an add-on in the asset library?

I think lighting is inherent to the engine and can't be done in an addon?

**Comment by Calinou** [comment] 2021-08-03 12:19
Duplicate of https://github.com/godotengine/godot-proposals/issues/1275.

**Closed by Calinou** 2021-08-03 12:19 UTC
