### ISSUE TITLE
explicit override keyword for gdscript

### ISSUE THREAD

**Issue by cameronsteele** [godotengine/godot-proposals#3654] opened 2021-12-11 05:06 UTC
### Describe the project you are working on

An abstract class for exporting/importing Nodes and various data types.

### Describe the problem or limitation you are having in your project

I override methods when I need more specific functionality but it feels semantically precarious that I cannot explicitly define that the method is meant to override another.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allowing the keyword "override" before a function declaration i.e. `override func importValue(value, type):` like other languages have would help make code more semantically clear and, if the compiler checked for it, further help prevent bugs that come from extending classes that are missing expected methods.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
class One:
	func basicMethod():
		print('one');

class Two extends One:
	override func basicMethod():
		.basicMethod();
		print('and two');
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's just fancy syntax; not strictly necessary.

### Is there a reason why this should be core and not an add-on in the asset library?

In the name of making gdscript a competent and powerful language.

**Comment by Calinou** [comment] 2021-12-11 16:10
Duplicate of https://github.com/godotengine/godot-proposals/issues/1631.

**Closed by Calinou** 2021-12-11 16:10 UTC

**Comment by era-epoch** [comment] 2024-04-15 15:06
Was this ever implemented or supported in any way?

**Comment by Calinou** [comment] 2024-04-15 15:20
> Was this ever implemented or supported in any way?

No, see https://github.com/godotengine/godot-proposals/issues/1631.
