### ISSUE TITLE
Enable _physicsprocess to run at different physics frames . . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot-proposals#3238] opened 2021-08-31 09:29 UTC
### Describe the project you are working on

A 2.5D game, with barbarians . . >

<img width="1272" alt="Skærmbillede (2123)" src="https://user-images.githubusercontent.com/83387915/131476765-f9261b61-e56f-4001-9753-bc3a24465e85.png">

First character, name Gloria Eden <3

### Describe the problem or limitation you are having in your project

I've been trying to think of ways, to optimize the AI, other stuff . . .

I've been wanting, to make some code, where it only runs every second frame, or third or, so . . . Physics process is quite nice, bec. it runs at constant frame - rate . . .

For instance, I'd like to have four enemies, that run AI for, like this . . .

frame 1 . . enemy one checks for player . .
frame 2 . . enemy two checks for player . . .
frame 3 . . enemy three checks for player . .
frame 4 . . enemy checks for player . .

Then, it repeats . . I'm thinking this could lower amount of CPU processes, and make the AI faster or, so . .

My proposal is, to add a setting, to physics process, where it only runs, say on frame 1, then frame 5, then frame 9 . . So, one could set starting frame, maybe on a scale, ie. for instance divide into 4 segment, or 8, and type a number, for that frame to run on . . .

So, if I type 8, total number of divisions, in first segment, and then, for instance 3, in what frame, to check . .

It runs that code, at frame 3, then 3 + 8, 11, then again at 19 . . I'm thinking this could make some processes, that don't need to run every frame more easy to code, for instance, for some game elements, sort-of one only wants to check, maybe every second, if player is close, or every 10 frames . . I'm thinking this could help optimize code, so one could custom set, for some stuff, like AI, run this code every 2, or 4 frames and, then space it, between say enemies . .

Right now, one can code it, was thinking it might make sense to add it, not sure how much faster the game would run, really like really fast code and, was thinking this might help, it seems a bit weird well it's not already there . . . .

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Well, I'd like to have amazing enemy AI but, also it being optimized . . So, some things, since it's the same calculations, and doesn't need to happen every frame, for instance have 4 enemies check, at different frame times . . . This would effectively reduce the CPU load, of those processes, by 75 % and, well I'd like to optimize my projects that way or, so . . . .

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well, sort-of like there are 'default' arg settings, for say move_and_slide(), idea was to add two settings to _physicsprocess, so one could set number of divisions and, on what frame, to run certain code . . . It'd allow to space the code elements well more easily, atm. one has to keep track of many things, really want optimized code or, so . . .

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Well, one can set it manually but, was wondering since it's an obvious place for optimization, why is it not a ' in-built ' feature, for instance, I have a RayCast ' vision ', for my enemies and, I think I only want it to run every other frame and, for maybe 4 enemies . . . Right now, one has to set up a frame counter and, it's quite complicated . . Having this stuff, would allow beginners to more easily optimize code, or so . . . .

### Is there a reason why this should be core and not an add-on in the asset library?

Well, it's prob. more an optimization thing, it makes sense sort-of one wants certain things to only run every 10th frame, or 30th . . . It'd really help one add more enemies and, optimize the code, in a simple way, thx . . !!

**Comment by charlesmlamb** [comment] 2021-08-31 09:33
Like this, add two arguments, where one can set number of frames, division then, a number to set on what sub - division <3

![Skærmbillede (2124)](https://user-images.githubusercontent.com/83387915/131478990-2d0c1562-9785-44c7-a951-48f2504de447.png)

So, first number, is maybe divide, to 4 frames, then next one, one writes say 2, and then that _physicsprocess runs, only on frame . .

2, 5, 9, 13 or, so . . <3

**Comment by KoBeWi** [comment] 2021-08-31 10:35
You can use a Timer.

**Comment by charlesmlamb** [comment] 2021-08-31 11:28
Well, don't really know, been trying to figure this stuff, to optimize the game but, I think maybe make a frame counter, use that . .

Guess problem is, one can't have multiple _physicsprocess, then, so for normal code and, sort of ' spaced ', over frames, code or, so . . . . 

Thx, prob. bad idea, really want super - optimized code . . .

**Comment by mrjustaguy** [comment] 2021-08-31 11:47
This proposal is pointless, this is something that the game dev has to deal with, and has nothing to do with the engine, and it is already very easy to get the desired effect, there are quite a few ways to do this.

Here are a few examples:
1) Timers, as stated above, you could have each AI have a timer that fires of at regular intervals, and you could offset each timer in a manner of different ways
2) You could just count frames in the code, and again depending on the AI change the offset on which they end up running their code
3) You could have a master node that's delegating the tasks to the AI each frame, iterating over the AI

But really, this will not make the AI faster, just the opposite, and from what you've described, you wouldn't be getting a big performance improvement by implementing this anyhow as a handful of raycasts each frame aren't that expensive, and you'd need 100+ ray casts every frame to start having issues with performance, and there are other ways to determine if you should even bother shooting the rays in the first place.

**Comment by Calinou** [comment] 2021-08-31 12:18
Duplicate of https://github.com/godotengine/godot-proposals/issues/439.

**Closed by Calinou** 2021-08-31 12:18 UTC
Labels: topic:core

**Comment by sugarsthenewwhite** [comment] 2022-07-29 17:19
> This proposal is pointless, this is something that the game dev has to deal with, and has nothing to do with the engine, and it is already very easy to get the desired effect, there are quite a few ways to do this.
> 
> Here are a few examples:
> 
> 1. Timers, as stated above, you could have each AI have a timer that fires of at regular intervals, and you could offset each timer in a manner of different ways
> 2. You could just count frames in the code, and again depending on the AI change the offset on which they end up running their code
> 3. You could have a master node that's delegating the tasks to the AI each frame, iterating over the AI
> 
> But really, this will not make the AI faster, just the opposite, and from what you've described, you wouldn't be getting a big performance improvement by implementing this anyhow as a handful of raycasts each frame aren't that expensive, and you'd need 100+ ray casts every frame to start having issues with performance, and there are other ways to determine if you should even bother shooting the rays in the first place.
> 
> Oh and like in a 2D game (2.5D game -> Physics can be done in 2D to save on a ton of Performance), there are so many extra optimizations that can be done to that step that it totally doesn't make any sense to worry about, and this needless complication would just make your game more prone to bugs and would be harder to maintain

Timers stop behaving in consistent ways below 0.05 seconds dont they? which clearly isnt fast enough for a game loop.

**Comment by Calinou** [comment] 2022-07-29 19:43
> Timers stop behaving in consistent ways below 0.05 seconds dont they? which clearly isnt fast enough for a game loop.

They do, unless you render at a higher framerate by disabling V-Sync and ensuring the game can consistently run at a high framerate.

**Comment by sugarsthenewwhite** [comment] 2022-07-29 20:28
> > Timers stop behaving in consistent ways below 0.05 seconds dont they? which clearly isnt fast enough for a game loop.
> 
> They do, unless you render at a higher framerate by disabling V-Sync and ensuring the game can consistently run at a high framerate.
> 
> That said, for AI simulation and the like, using a condition that tells it to update on every second, third or fourth frame will work fine. On a game running its physics at 60 Hz, this is 30 Hz, 20 Hz and 15 Hz respectively.

My case is a little different, i don't have vysnc on but my physics rate keeps changing depending on the frame rate range. To keep input lag to minimal. However i want this to be only applied to the main character, for other stuff like enemies i want them to share a fixed physics rate.
