### ISSUE TITLE
Play / Play Scene should (optionally) open within a new tab instead of new window

### ISSUE THREAD

**Issue by MickL** [godotengine/godot-proposals#3583] opened 2021-11-21 17:50 UTC
### Describe the project you are working on

2D Platformer and 3D RPG

### Describe the problem or limitation you are having in your project

Using the Godot Edit in fullscreen and pressing the play or play scene button opens a new window. This has two downsides:

1. You are not able to see the output / debugger
2. It gets you out of the flow / focus that you have with the fullscreen mode, and is kind of annoying

Video:
https://youtu.be/kZI56d0ddHo

This is especially the case on a macOS laptop where using fullscreen is very common but might be the case for Windows and Linux, too.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Instead of a new window, the game could launch within the editor in the main scene panel. Then the output / debugger, and also the other ui tools, are still visible.

I am pretty sure this is the case for Unity and Unreal, too.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user presses play or play scene open within the editor. The option to do so might be configurable.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the editor usability

**Comment by pycbouh** [comment] 2021-11-21 17:59
Duplicate of https://github.com/godotengine/godot-proposals/issues/1864. Currently Godot projects run as a separate process which cannot be embedded into the editor.

**Closed by pycbouh** 2021-11-21 17:59 UTC

**Comment by MickL** [comment] 2021-11-24 08:55
@pycbouh I dont know of this is actually a duplicate. The other issue is about way more features:

> Add the ability to see how the nodes are behaving in the scene editor while the game is running. 

I just want to play the scene in the editor, without any other feature requests.

**Comment by pycbouh** [comment] 2021-11-24 10:39
You want exactly the same thing, just for different reasons.
