### ISSUE TITLE
Add an ICE buffer to WebRTCPeerConnection

### ISSUE THREAD

**Issue by ASavchenkov** [godotengine/godot-proposals#1286] opened 2020-07-31 21:26 UTC
**Describe the project you are working on:**
A P2P FPS that uses WebRTC for its networking.

**Describe the problem or limitation you are having in your project:**
The WebRTCPeerConnection object cannot accept ICE candidates until both local and remote SDPs are set. It starts emitting ICE candidates as soon as the local SDP is set. This results in situations where ICE candidates may arrive before both SDPs are set.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Ideally, the WebRTCPeerConnection object should have an internal means of buffering ICE candidates until it is ready to use them.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

A function "buffer_ice_candidate" is added, with the same signature as "add_ice_candidate".

```
	if (ready_for_ice) {
		return add_ice_candidate(sdpMidName, sdpMlineIndexName, sdpName);
	}else {
		buffered_candidates.push_back(buffered_candidate(sdpMidName, sdpMlineIndexName, sdpName));
		return ERR_UNAVAILABLE;
	}
```
When both SDPs are set, we call "add_ice_candidate" for each buffered candidate.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I expect this enhancement to be used 100% of the time WebRTCPeerConnection is used.

**Is there a reason why this should be core and not an add-on in the asset library?:**

It is my amateur opinion that this enhancement should be the default mode of operation for this feature.

Judging by discussion on the Godot Discord, this is a common issue for anyone using the WebRTC networking features, and they have, like me, had to implement ugly and error prone workarounds to the same end.

**Edit:** I'm currently implementing this for myself since it's a relatively minor effort and currently a blocker on my project, so I'm happy to make the pull request once I'm done if this is deemed an appropriate enhancement.

**Comment by Calinou** [comment] 2020-07-31 21:36
cc @Faless

**Comment by Faless** [comment] 2020-07-31 21:42
The API tries to be a close match to the standard webrtc 1.0 specification
and, as far as I know, the current implementation has the correct behavior.

**Comment by ASavchenkov** [comment] 2020-07-31 22:17
OK. I read through the specification again and found the portion you're talking about. It seems then, that this is an issue that isn't considered in the spec, or it is assumed that the best fit solution is variable enough that it shouldn't be specified (as was done with signalling).

I would even argue that generating ICE candidates, but not accepting them until remote SDPs are set, is unnecessarily unintuitive for the end user, and perhaps somewhere the spec is lacking.

Unfortunately, this isn't even something that is easily dealt with in a script. Ideally one would be able to extend WebRTCPeerConnection with this functionality, but based on discord discussion around [this issue](https://github.com/godotengine/webrtc-native/issues/19), there seem to be limitations wrt. polymorphism between gdnative and other languages that make this non-viable.

The alternative is to create a separate entity that tracks which connections have been created,removed, or become ready for ICE candidates,  as well as buffering them. This is in my opinion much more complex with little benefit, and not a standard OOP solution at that.

The way I've written the proposal, usage of the buffer functionality would be optional, a self contained "extra" QOL feature within WebRTCPeerConnection, and shouldn't cause much confusion for those already familiar with WebRTC.

**Comment by Faless** [comment] 2020-07-31 22:26
You don't really need to extend the webrtcpeerconnection. You'll have to
implement the signaling server yourself anyway (or use an external one),
you can easily handle the buffer there (this isn't a problem in most real
world scenarios anyway, but if you really want to be 100% sure you can do
it there).

**Comment by Faless** [comment] 2020-07-31 22:28
I'll add, that the implementation is generating the peers that way, simply
because it has no way of knowing if the other peer is ready (or even exists)

**Comment by ASavchenkov** [comment] 2020-07-31 22:47
> You'll have to implement the signaling server yourself anyway (or use an external one),
you can easily handle the buffer there

I hadn't considered that, but I reckon it would actually be more complex than buffering it on the peer (since now the peer needs to signal another machine that it is ready to accept ICE candidates, and the logic for buffering is still the same, just on a different machine.)

> I'll add, that the implementation is generating the peers that way, simply
because it has no way of knowing if the other peer is ready (or even exists)"

And I think this makes perfect sense, assuming you have a way to deal with packets arriving out of order on the other end. It's definitely preferable to adding another back and forth of "I'm ready" signaling.

I think we disagree on how common this issue is. I personally know of one other user who's seen this issue and had to work around it, and I suspect that the reason it doesn't crop up more often is the relatively low popularity of the WebRTC functionality at this time.

I'm content to just use this solution for myself, but I genuinely think that for how little work it takes to do, it's worth it.

**Comment by Faless** [comment] 2020-07-31 23:04
I've never seen webrtc signaling over a non-ordered protocol (99% of the
time you just want a websocket server), but of course it can be done. In
that case, it's the responsibility of the signaling server itself to
reorder the messages properly

**Comment by ASavchenkov** [comment] 2020-07-31 23:17
OK. I'm not sure I agree with that from the point of view of overall complexity, but if it ends up being that uncommon I'll keep to myself on this.

**Comment by jonbonazza** [comment] 2020-11-22 06:44
@Calinou @Faless is this a duplicate of #434

**Comment by Faless** [comment] 2020-11-23 15:17
@jonbonazza no, this is not a duplicate.
The user wants to add a behaviour to WebRTCPeerConnection that buffers added ICE candidates when the connection is not yet ready to receive it (i.e. when it does not have both local and remote description set).
This is not in accordance to the specs, nor other implementations.
Such a behaviour can also be implemented via script by keeping a state variable if needed, so I'm closing this issue.

**Closed by Faless** 2020-11-23 15:17 UTC
Labels: topic:network
