### ISSUE TITLE
Working Export window on mobile

### ISSUE THREAD

**Issue by artur321233** [godotengine/godot-proposals#6818] opened 2023-05-06 19:03 UTC
### Describe the project you are working on

2D Action RPG with Top-down view.

### Describe the problem or limitation you are having in your project

I can't export from my Android phone. I make game ONLY using phone so it's big problem.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make Export window smaller (in height).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When user on phone exports game the window will show "Export" button.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by using Godot 3, but Godot 4 is more reliable and stable.

### Is there a reason why this should be core and not an add-on in the asset library?

It can't be added by addon.

**Comment by Calinou** [comment] 2023-05-06 21:30
- Duplicate of https://github.com/godotengine/godot/issues/73130 (this is a bug).

**Closed by Calinou** 2023-05-06 21:30 UTC
