### ISSUE TITLE
Add support for saving multiple selected nodes to their own scene file in the Scene tree dock context menu

### ISSUE THREAD

**Issue by frkntlr** [godotengine/godot-proposals#10614] opened 2024-08-30 23:13 UTC
### Describe the project you are working on

It was a problem I overcame during Gamejam.

### Describe the problem or limitation you are having in your project

For example, when I select a single node in a scene, I can save it (I can do the same function by dragging it to the filesystem).
![resim](https://github.com/user-attachments/assets/3ba87cce-88c3-4c8c-a315-22dd33049afd)

When I select 2 or more nodes I cannot do this.
![resim](https://github.com/user-attachments/assets/9ab06862-ed64-4041-977e-c37d0cac1960)

Through an fbx, I transferred the prop and environment components to godota. I designed it over the scene. Some parts had a code api. For example, I added animation. I could make a scene one by one and save it. But I had more than 100 models and I had to save them one by one. This caused me to waste a lot of time.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If we can save a single node as a branch, add multiple save options.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Saving as a branch in a single node can also be saved in multiple nodes.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know.

### Is there a reason why this should be core and not an add-on in the asset library?

Doing it as a plugin causes it to be slow in terms of performance. As a plugin, it may cause the engine to crash due to structure incompatibility.

**Comment by Calinou** [comment] 2024-08-31 01:37
A scene cannot have multiple root nodes, so each selected node would be considered their own root and saved independently (unless you selected a child of another node that will be saved, in which case it'll be skipped).

The file name would likely be guessed automatically based on the node name. The dialog would only ask you for the destination folder, not a file name.

**Comment by passivestar** [comment] 2024-08-31 09:07
Duplicate of https://github.com/godotengine/godot-proposals/issues/7911

**Comment by frkntlr** [comment] 2024-08-31 09:24
> A scene cannot have multiple root nodes, so each selected node would be considered their own root and saved independently (unless you selected a child of another node that will be saved, in which case it'll be skipped).

Why can't multiple root nodes be registered when you can register many root nodes individually? It should be the main root node, but multiple registration will add great practicality and speed. 

> The file name would likely be guessed automatically based on the node name. The dialog would only ask you for the destination folder, not a file name.

It can specify which folder to save to and save it according to the node name.


> Duplicate of #7911

I looked before I opened this issue but I didn't look enough. Thanks for your help. I would like to see some progress on this issue.

**Comment by Calinou** [comment] 2024-09-05 01:24
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/7911.

**Closed by Calinou** 2024-09-05 01:24 UTC
Labels: topic:editor
