### ISSUE TITLE
Restore quit confirmation in Godot 4

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot-proposals#8616] opened 2023-12-08 10:41 UTC
### Describe the project you are working on

FPS.

### Describe the problem or limitation you are having in your project

When debugging, I instinctively press alt+f4 to close the game window (rather than writing a custom quit using Escape key for instance) and sometimes I accidently press it twice which closes the editor and loses all of my undo/redo history (which I'm using to test things out).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Restore the confirmation quit dialog, which was removed here: https://github.com/godotengine/godot/pull/32321

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Put it back as a toggleable option so it displays whether there are files that need saving or not (as closing the editor loses all undo/redo history).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

All the needs restoring is the removed dialog from this change: https://github.com/godotengine/godot/pull/32321

### Is there a reason why this should be core and not an add-on in the asset library?

All the needs restoring is the removed dialog from this change: https://github.com/godotengine/godot/pull/32321

**Comment by AThousandShips** [comment] 2023-12-08 10:47
Sounds like a duplicate of:
* https://github.com/godotengine/godot-proposals/issues/6915

**Comment by AThousandShips** [comment] 2023-12-08 10:55
Duplicate of https://github.com/godotengine/godot-proposals/issues/6915

**Closed by AThousandShips** 2023-12-08 10:55 UTC
