### ISSUE TITLE
Multiple pack export

### ISSUE THREAD

**Issue by DigitalJokerMan** [godotengine/godot-proposals#2284] opened 2021-02-13 21:27 UTC
### Describe the project you are working on
A multiplayer RPG game that I anticipate will have lots of updates for content, and possibly DLC.

### Describe the problem or limitation you are having in your project
In Godot, when you build a project, everything is built into one giant pack file.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I want to be able to spilt the game build into many different packs. It is technically already possible with a "build" script, but it's messy and I would like it if it was integrated into the editor itself.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
On the export interface, maybe you could give certain assets (and folders) a tag, and when you do the export it'll create packs based on those tags, and maybe a manifest of all the tags could be included in the main pack. When the game is started, Godot could try to load all the packs in the manifest, and maybe it'd just ignore ones that don't exist.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It could. But, at least in the way I implemented it, it's very messy, because as far as I know there is no way to "compile" textures, models, or what have you without going through the export menu.

### Is there a reason why this should be core and not an add-on in the asset library?
I mean, it could be an asset library thing, but I think a feature like this is just better off being a core thing. I think that's more of a matter of opinion more than anything else though.

**Comment by Calinou** [comment] 2021-02-13 21:46
Duplicate of https://github.com/godotengine/godot-proposals/issues/146.

**Closed by Calinou** 2021-02-13 21:46 UTC
