### ISSUE TITLE
Add a view mode where CollisionShapes are rendered as solid . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1334] opened 2020-08-08 07:22 UTC
**Describe the project you are working on:**
A Tomb Raider game . .

**Describe the problem or limitation you are having in your project:**
I often make large environments, but the collisionshapes are a bit hard to see, ie. where the ' level ' really is . . It would be nice if there was a view mode, where the collisionshapes were rendered as ' solid ' cubes, or shapes . . It would help in making sure the level was set up correct, and had no errors, and help in placing meshes, it's just an idea, based on what I find difficult, as a beginner . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Well, when I zoom out, the collisionshapes are very hard to see, there's a view mode called overlay, if one could have another one, where ' collisionshapes ' are rendered as white blocks, shapes, so on, it'd make placing a level a lot easier, or so . . Just, an idea, thanks . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Add an extra view mode, where meshes are rendered as in overlay, or so, similar, and all collisionshapes are rendered, as white, or checkered boxes, or forms . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It'd just make it a lot easier, to make levels fit, and also to check later, quickly, if there are any errors in the level, as well . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**
It seems like a nice idea, wanted to suggest it, thank you <3

**Comment by Zireael07** [comment] 2020-08-08 08:18
Duplicate of https://github.com/godotengine/godot-proposals/issues/906?

**Comment by Calinou** [comment] 2020-08-08 11:41
Duplicate of #906.

**Closed by Calinou** 2020-08-08 11:41 UTC
