### ISSUE TITLE
Add a project setting to set a lower resolution mip map as the top level texture.

### ISSUE THREAD

**Issue by Donn-Eddy** [godotengine/godot-proposals#6019] opened 2022-12-29 23:40 UTC
### Describe the project you are working on

I am working on a Bullet Hell style game targeting Steam Deck.

### Describe the problem or limitation you are having in your project

While my project is targeting the 1280x800 60hz panel of the Steam Deck, I aim to optimize for this platform while having the option to scale to 4k.  Right now, I limit most materials between 128x128 and 512x512 resolution.  This is fine for my target resolution, but not ideal for a 4k panel.

I attempted to solve this via a mipmap bias however the full textures are still loading, the quality is lower than desired, and doesn't work the same once FXAA/TAA/FSR are used.

This proposal is likely related to the following: [#23739](https://github.com/godotengine/godot/issues/23739) and [#2683](https://github.com/godotengine/godot-proposals/issues/2683)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A feature in engine to import textures at a lower mipmap level as the base resolution.  This would conserve VRAM capacity and bandwidth while allowing the mipmap bias to behave as normal while maintaining the lower mipmap levels to behave as normal.  This feature would also allow an easy to access member for a settings menu for all Godot users.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

An option added to the rendering/textures/default_filters/ settings to trim off the top level mipmaps.

![image](https://user-images.githubusercontent.com/25522325/210019613-5e5edb32-ad06-48b0-b3aa-7b86e38c4c88.png)

If set to 0, it behaves as is.  If set to 1, then it would trim the highest resolution image and use the second tier mipmap as the highest resolution.  The bottom resolution could be either the lowest tier mipmap,or an additional "minimal_trim_resolution" (if set to 64, the trim would not go lower than 64x64).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This would only impact textures with mipmaps and only if it is changed from default.  As such, sprites and UI elements should be safe.  Additionally, if the setting remains to the default of 0, there would be no impact to anyone who does not use the setting.  Lastly, if the feature is used, these feature could be worked around by one of two ways:
1) Disable mipmaps on the affected texture.
2) Add a final import setting for a local minimal trim resolution.

### Is there a reason why this should be core and not an add-on in the asset library?

I am unsure how mipmaps are loaded, though if we can load the mipmap levels respecting the trim setting, there is no downside to implementing this feature to core.  I am not sure if an add-on would have access to these lower level mipmaps without loading the higher resolution images, costing memory and storage bandwidth.

**Comment by Calinou** [comment] 2022-12-30 00:07
Duplicate of https://github.com/godotengine/godot-proposals/issues/3177 (this needs to be implemented as streaming, with a setting to choose the highest mip that can be loaded).

**Closed by Calinou** 2022-12-30 00:07 UTC
Labels: topic:import, topic:rendering
