### ISSUE TITLE
PackedByteArray needs to provide to_vector3_array() method

### ISSUE THREAD

**Issue by blackears** [godotengine/godot-proposals#8535] opened 2023-11-28 13:05 UTC
### Describe the project you are working on

I've created a GLSL compute shader that produces a buffer of point and normal data that I want to turn into a mesh.  The buffers can be accessed as PackedByteArray types.   

### Describe the problem or limitation you are having in your project

At the moment, PackedByteArray only provides methods that convert it to float32, float64, int32 and int64 packed data types.  The ArrayMesh requires PackedVector3Array data.  As far as I can tell, there is no way to convert byte data to packed Vector3 data short of using the CPU to iterate through it and copy each float into a new buffer.  This would be slow and something that could be avoided just by providing access to the buffer with the PackedVector3Array type.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a to_vector3_array() method to PackedByteArray that can provide a view of the data as a Vector3 array.  It would also be very useful to have a to_vector2_array() method to for GLSL shaders that produce 2d data.  Color would probably also be good idea.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add the following methods to PackedByteArray that alias the buffer with different data types:

to_vector3_array()->PackedVector3Array
to_vector2_array()->PackedVector2Array
to_color_array()->PackedColorArray

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Requires modification to a core data type.

**Comment by AThousandShips** [comment] 2023-11-28 13:06
Duplicate of https://github.com/godotengine/godot-proposals/issues/8139

**Closed by AThousandShips** 2023-11-28 13:06 UTC
