### ISSUE TITLE
Option to only show modified properties in the inspector

### ISSUE THREAD

**Issue by leo-unglaub** [godotengine/godot-proposals#2986] opened 2021-07-12 12:10 UTC
### Describe the project you are working on

I am working on a 3D FPS much like the good old Quake

### Describe the problem or limitation you are having in your project

The more inheritence you use, the more properties are show in the Inspector view. This can make it quite hard to find the stuff you are looking for. Specially during debugging it would be amazing to only see the properties that are modified (not the default).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be amazing if it would be possible to use the `filter properties` function in the Inspector to also specify a search query like `!modified` or so to just show what changed. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Right now the `filter properties` function searches on the name. I would propose to define a special chararter that is the start for special queries.

For example: `!modified` or `#modified`. It does not really matter what starts the sequence, as long as it fits perfect in the Godot workflow.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I am sure this would be used a lot, specially during debugging of huge interitence chains.

### Is there a reason why this should be core and not an add-on in the asset library?

I asume it would benefit a lot of people by default if it where included in the editor.

**Comment by Calinou** [comment] 2021-07-12 12:11
Duplicate of https://github.com/godotengine/godot-proposals/issues/2651.

**Closed by Calinou** 2021-07-12 12:11 UTC
Labels: topic:editor
