### ISSUE TITLE
Add a "reset" animation to AnimationPlayer

### ISSUE THREAD

**Issue by reduz** [godotengine/godot-proposals#1597] opened 2020-10-02 13:58 UTC
**Describe the project you are working on:**
Godot
**Describe the problem or limitation you are having in your project:**

Users often complain that, despite the huge flexibility, a key limitation of AnimationPlayer, is the fact that once an animation is played, its initial values are lost. This is specially annoying for cinematics or UI animations because, when saving, the wrong state gets saved to disk. Additionally, if you have multiple animations that each modify a different state of the scene, resetting everything can be a very laborious task.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

To overcome this problem, the idea is to create a "reset" track. It will help restore default values when needed.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

When a new track is added to an animation, the UI will also ask you if you want to create a reset track for it. This is on by default.

![image](https://user-images.githubusercontent.com/6265307/94930225-7a685800-049c-11eb-8e4a-00136c075c48.png)

If you do this, an additional new animation named RESET will be created and a key with the current value for this track will be added there (added at time 0, and the animation will have length zero), besides adding it to the currently edited animation:

![image](https://user-images.githubusercontent.com/6265307/94930508-e2b73980-049c-11eb-927f-c00443d40849.png)

Now that you have the RESET animation, you can do a couple of things:
* The first and most obvious one is to have a reset button, that just applies the reset track and resets everything. It can be a button or an item in the EDIT menu, up to you guys to discuss it. 
 ![image](https://user-images.githubusercontent.com/6265307/94931034-a59f7700-049d-11eb-8f4d-14d89c1b3dad.png)
 If not used as often, menu item may be better (we could start with this option, to avoid clutter, then move it to dedicated button if we see its actually needed)
* AnimationPlayer can get an extra property in the inspector "Reset on Save", which means that when the scene is saved, before actually saving, the reset track is applied. This ensures tracks are always saved with the initial value.
* As RESET is an animation, it can be very easy to add your custom tracks, call functions, or inspect and change default values.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
**Is there a reason why this should be core and not an add-on in the asset library?:**

No, this needs to be core, requires changes to the existing tooling.

**Comment by Sslaxx** [comment] 2020-10-02 14:07
Is this intended to fix https://github.com/godotengine/godot/issues/812 this issue?

**Comment by KoBeWi** [comment] 2020-10-02 14:12
> When a new track is added to an animation, the UI will also ask you if you want to create a reset track for it. This is on by default.

This dialog can be disabled. Does this mean by default the RESET track will be created without confirmation? (personally I wouldn't mind)

Also, it could be convenient to have an option to quickly (or auto?) update the value in RESET track, in case you want to change the default. I imagine someone might change the property and forget to update the default and lose their change, so we might want to prevent that. (and such problems aren't very uncommon, see #694 for example)

> Is this intended to fix godotengine/godot#812 this issue?

Yes.

**Comment by reduz** [comment] 2020-10-02 14:13
@KoBeWi if you disable it its up to you, we can add another global option "create reset tracks by default", which is what ticks the checkbox in the dialog too.

**Comment by jcostello** [comment] 2020-10-02 14:20
@KoBeWi yes to the auto update the reset track

**Comment by RandomShaper** [comment] 2020-10-02 14:22
This can be really useful and also would integrate seamlessly in my workflow.

I usually have a  zero-length _rest_ animation, that I can go back to if things get messed up and, more importantly, I want my scenes to be saved in the reset/default state represented by it.

This will be even more powerful in a workflow like this if people set the RESET animation as autoplay.

Suggestion: reset before save also restores the old state after saving is done (should be easy ro implement thanks to the code used for onion skinning).

**Comment by KoBeWi** [comment] 2020-10-02 14:25
> Suggestion: reset before save also restores the old state after saving is done (should be easy to implement thanks to the code used for onion skinning).

I think this is meant to only affect what is saved, so the scene state in the editor would not change anyways.

**Comment by eon-s** [comment] 2020-10-02 14:42
What about making a snapshot only for the editor? because keeping sync of a "reset" track may be annoying and you will need a reset track for many states (making it very confusing).

A snapshot should be a set of values you want the editor keep on save, ignoring anything else modified by an animationplayer or potentially another similar tool.

**Comment by Itachi124** [comment] 2020-10-02 15:10
There is only single part of the idea that i didn't like which is having an animation called "RESET".
during my work on #1344 i find that it is possible to save the node's data and values for use in animation.

You could make a Defult value Array saved with the animation, and make the reset button call these values without the need for new animation or anything.
Like this :
```

tracks/0/type = "value"
tracks/0/path = NodePath("AnimationSystm/Sprite2:centered")
tracks/0/node_scene = [ "Sprite", "res://Test1.tscn" ]
tracks/0/node_data = [ [ "position", "rotation", "texture" ], [ "anims/TestAnimation" ] ]
tracks/0/node_value = [ [ Vector2( 761.15, 237.406 ), 1.19381, ExtResource( 1 ) ], [ null ] ]
tracks/0/interp = 1
tracks/0/loop_wrap = true
tracks/0/imported = false
tracks/0/enabled = true
```
Also i would suggest you to think about connecting the AnimationTrack and the AnimationPlayer.
as i find there is no connection between them at all, which makes it lake the syncing between editing and adding a value and viewing it.

Consider doing that as it will open a new way of getting rid of AnimationPlayer limitations.

And Thank You.

**Comment by reduz** [comment] 2020-10-02 15:26
@eon-s It will be marked as a special trackto avoid confusion. Also as many mentioned, you still want the ability to quickly reset things from within the game and the fact its an animation means you can queue it between two of them. Many users already do this manually as part of their workflow.

@Itachi124 Additionaly to the point above, doing what you suggest means you have to create a separate editor UI that does exactly the same as the animation editor, which makes not much sense. Additionally, users often want to call functions when resetting, and this allows you do it by adding a call track.

**Comment by Calinou** [comment] 2020-10-02 15:31
The reset track could probably be shown as `[reset]` to distinguish it better from other tracks. It could also be displayed always at the top of the list, and perhaps with a different color (if possible).

**Comment by Itachi124** [comment] 2020-10-02 15:43
@reduz 
Sadly i don't know mush about how Godot UI work and how its connected to the functions.
But as far as i can tell, what the AnimationEditor does is:

-It takes what the user did in the UI.
-Change or save the Data into the Animation and the Animation Resource.
-And then the AnimationPlayer call these Data using `_ensure_node_caches()` Function.

So what i were thinking is to connect the AnimationEditor to the AnimationPlayer by having a reference to the AnimationPlayer in the AnimationEditor.cpp.

![AnimationPlayer8](https://user-images.githubusercontent.com/32880087/94942134-88d76380-04de-11eb-9338-988c54e4f110.gif)

I faced that problem when i finded the function reponsible for applying the `AnimationTrackKeyEdit `values in the `AnimationEditor`

So what i wanted is to call `_animation_process_animation` in the AnimationPlayer in order to update these values in runtime, so i can see what happens when i change my values.

But as i said i find no connection between the two, there for there is no reference to call the event from.

Sadly as i said i can't really give any suggestions about how to fix it, for my lake of knowladge.
But i hope one day we can overcome it.

Thanks.

**Comment by RandomShaper** [comment] 2020-10-02 16:04
> The reset track could probably be shown as `[reset]` to distinguish it better from other tracks. It could also be displayed always at the top of the list, and perhaps with a different color (if possible).

It could even display an icon (pretty much like in the case of autoplay). That way the animation wouldn't even need to have a specific name (albeit by default it's created as "reset" if no reset animation is already present).

**Comment by UnwarySage** [comment] 2020-10-03 01:57
This pretty much describes my present manual process. I am in favor.

**Comment by Riteo** [comment] 2020-10-03 08:35
> It could even display an icon (pretty much like in the case of autoplay). That way the animation wouldn't even need to have a specific name (albeit by default it's created as "reset" if no reset animation is already present).

Oh, are you implying that any animation could be set as the reset? That sounds cool, but if anything like this should ever happen, I think that there should be a way to identify the animation from code, as it can be potentially useful for animation plugins.

**Comment by RandomShaper** [comment] 2020-10-03 09:02
> > It could even display an icon (pretty much like in the case of autoplay). That way the animation wouldn't even need to have a specific name (albeit by default it's created as "reset" if no reset animation is already present).
> 
> Oh, are you implying that any animation could be set as the reset? That sounds cool, but if anything like this should ever happen, I think that there should be a way to identify the animation from code, as it can be potentially useful for animation plugins.

`AnimationPlayer.get_reset_animation() -> Animation` (or `null`)

Well, this is just an idea. If anyone thinks that the ability to mark any (only one) animation as reset has downsides, please share your thoughts.

**Comment by RandomShaper** [comment] 2020-10-03 09:29
Brainstorm:

a) If you have multiple animation players in a scene and have the reset-on-save editor setting enabled, should it apply to all of them? I think it should.
b) Add a button (or anim editor menu item) that allows you to create any track as the current values of the current animation. That's both a way to create a reset track or any other animation you want to start exactly at the state of another at any point in time.

**Comment by Itachi124** [comment] 2020-10-03 13:20
@reduz 
Wait a sec.
![AnimationPlayer8](https://user-images.githubusercontent.com/32880087/94992664-3d7f8c80-0594-11eb-9e8c-9d822abb66c6.gif)

I did find a connection between AnimationEditor and the AnimationPlayer
It was throw the AnimationEditorPlugin !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Why you didn't tell me that!!!!

**Comment by Riteo** [comment] 2020-10-03 17:05
> a) If you have multiple animation players in a scene and have the reset-on-save editor setting enabled, should it apply to all of them? I think it should.

I think that this "reset-on-save" function should be implemented on its own, resetting to the values before selecting the animationplayer on its deselection.

**Comment by Eoin-ONeill-Yokai** [comment] 2020-10-03 19:01
Couldn't we just have an extra track type that, when playback finishes or changes to an animation without the same track's path, will reset to desired "default value"?

Additionally, I find that working with multiple animations with many different "tracks" can become difficult because you have to manually search for every property you used in a previous animation. So when creating a new track for animation, will it use the reset track as a "base line" even when creating a new animation? In other words, could the Reset animation be treated as a kind of base class animation?

**Comment by Itachi124** [comment] 2020-10-03 19:16
@Eoin-ONeill-Yokai 

I have thought the same thing.
And in fact i have made a way to optimize the number of tracks needed for an animation.
By making the first values being automaticly assigned to the nodes when started. rather then keying all of them.
I have mentioned this problem in this proposal #1344  at the comment number 58.
consider checking that out.

**Comment by reduz** [comment] 2020-10-03 21:22
@Eoin-ONeill-Yokai , @Itachi124 The problem is that the most common use case desired here is having a default state for all tracks animated in all animations, not per animation. This is why there is no default value in the animation themselves (it would be redundant and prone to errors).

**Comment by Itachi124** [comment] 2020-10-03 22:04
@reduz 
Nope.
We could have a default state for each animation.
I have done that, Please check this proposal for information about it #1344 

![Screenshot 2020-10-03 225358](https://user-images.githubusercontent.com/32880087/95002391-219fd900-05dc-11eb-80c7-35ca6818b785.png)

and remmeber my question about linking AnimationEditor and AnimationPlayer.
Well i find a way to do it.

in the AnimationEditor you can call the AnimationEditorPlugin function named `get_player()`.
that will get you the AnimationPlayer and you can do anything from there.

I managed to link so many stuff between the two, for the changes i made in the AnimationPlayer.
That get me to think about your reply about having another Editor.
Have you missed my point or do you have a differnet workflow of how this should work?

In general i think you guys has missed the AnimationPlayer.

I find places where we can optimize stuff. and some ideas that i might work on, 

Like merging the property track and 3d Transformation and the bezier track into a single track type.
Why is that?

Say that you have worked on your animation using property track, and you find out it could be better if you used the bezier track, so you have to rework everything.

Since we have the key positions and the easing value, can't we just convert it to bezier?
and we can convert back to normal key frames if we want, by simplying clamping the curves into keys.
i find it possible.

and for the 3d Tranformation. we simply can make adding a new tracks easyer and there for no need for it at all.

i find it very boring to add property track over and over and over, many times to animate each thing.
and even using the key icon in the propertys it get me with a window to confirm adding the value.
Consider adding "Don't ask again" check mark for that window.


Hope to hear back.
Thank you.

**Comment by DanielKinsman** [comment] 2020-10-04 00:29
So reset on save should mean the source/diff shouldn't change at all right? That's the most annoying thing about this for me.

**Comment by RandomShaper** [comment] 2020-10-04 00:42
> So reset on save should mean the source/diff shouldn't change at all right? That's the most annoying thing about this for me.

Yes, only the stuff that you've actually changed. I often find myself carefully resetting parts of scene files that changed because of having tweaked the value of a single key frame, since that made me seek to a certain point of some animation, which caused a lot of properties of lots of nodes to change.

In short, I feel your pain since I've been there and I can confirm this will get us rid of that.

**Comment by Itachi124** [comment] 2020-10-04 10:49
@DanielKinsman @RandomShaper 
I also find a fix for this.
The saving of the resource happens in the AnimationEditorPlugin when you press the Save button.
I Simply Call my `SUpdate()` function that go and take the changes only, and save them.
The default values are leaved untouched.
And as i said you don't need to rest the nodes values when you start the animation, the animation does it for you automaticly.
This also can be disabled if you want.

**Comment by reduz** [comment] 2020-10-04 16:48
@Itachi124 IMO that proposal is about something else completely unrelated, not a common use case. This is not about implementing a new feature because its cool, but about making it easier to do something users have been doing for a while now, which is having a way to reset the objects animated either by one or all animations, to their default state. Other features should be discussed in a separate proposal.

**Comment by reduz** [comment] 2020-10-04 16:54
@Itachi124 Just to make it clear, there is no intention from my part in discussing any of the features you mention. I only intend to find a solution to a specific problem users complain about. I suggest open a separate proposal, make a coherent presentation (fill the template) and try to gather interest to your ideas instead of derailing discussion on this one. If you manage to get enough interest from community, then core contributors will discuss the proposal and give you feedback.

**Comment by Itachi124** [comment] 2020-10-04 19:15
@reduz 
I think you missed my point, i didn't want you to see the proposal feature or advertise it.
in my last comments on that proposal i stated that i managed to get the animated nodes data, which mean you can:
rather then adding a new animation to reset the defualt values, save them directly to the animation, and call them using you "reset" button.

Also i find this system of godot proposal kinda bad.

For the simple reason that not alot of proposals get interset despite being a good proposals.
I did a look and this is what i find:

```199 with no comments
147 with only 1 comment
144 with only 2 comments
37 with only 3 comments
82 with only 4 comments
85 with only 5 comments
52 with only 6 comments
36 with 7 comments
40 with 8 comments
45 with 9 comments
27 with 10 comments
17 with 11 comments
10 with 12 comments
9 with 13 comments
9 with 14 comments
9 with 15 comments
7 with 16 comments
4 with 17 comments
3 with 18 comments
4 with 19 comments
5 with 20 comments
3 with 21 comments
2 with 22 comments
5 with 23 comments
2 with 24 comments
3 with 25 comments
2 with 26 comments
2 with 27 comments
20 with +28 comments
```

So most of the time you got make something yourself without waiting for devs, or for anyone to be instrested in your proposal.

But that's not our talking anyway, i just wanted to point that out.
Thanks.

**Comment by reduz** [comment] 2020-10-04 19:52
@Itachi124 You have to understand that the way we do development is not really via speculation on what is better than what. Its just impossible to do know this beforehand. The reason we created the proposal system is to be able to see users propose things and see the interest and feedback that other users get. Otherwise its just impossible for us to be able to tell what is useful and what is not. Your opinion on this is as good (and subjective) as mine. 

If you open a proposal and it gathers no interest (or it does but there is no consensus), be it from either you or mine, then there won't be any priority in having it implemented.

**Comment by reduz** [comment] 2020-10-04 19:55
Before this system, users just opened issues and PRs and we core developers had no idea if those were something user community wanted, or whether it would be useful. We would spend afternoons speculating that and it would lead to nowhere. So, in the end, we tend to act to solve problems mostly when several users run into the same issue, and not when someone has a cool idea.

**Comment by Eoin-ONeill-Yokai** [comment] 2020-10-05 17:30
> @reduz  The problem is that the most common use case desired here is having a default state for all tracks animated in all animations, not per animation.

That makes a lot of sense.

Though would a kind of animation "inheritance" still be off the table here? It would be nice in the case of this reset animation too, because you could have new animations inherit the reset and only override properties when an animation track is defined (or perhaps allow the user to disable inherited reset.) This would also mean that all animations would have their tracks update to reflect the desired "reset" behavior, even for channels they were previously uninterested in.

**Comment by slapin** [comment] 2020-10-08 15:31
For skeletons it would be more useful to add RESET/default animation instead which will set all the transforms to identity.
Because many animations won't contain initial state at all.

**Comment by slapin** [comment] 2020-10-08 15:37
@Itachi124 the proposal system is just a victim of the loop - to know you need something you have to have it;
if you don't have it you don't need it. The most technology proposals come from people who seen other engines and frameworks, and majority is just starting with simplest projects not knowing what they actually want and having no experience of what actually exists. That will always be the problem of demand-supply loop because it has no clearly defined goals.

**Comment by akien-mga** [comment] 2020-12-20 15:36
Implemented by https://github.com/godotengine/godot/pull/43115.

**Closed by akien-mga** 2020-12-20 15:36 UTC
Labels: topic:editor

**Comment by fire** [comment] 2021-08-03 06:54
Wanted to notify that my PR for a related feature to bake RESET tracks was merged https://github.com/godotengine/godot/pull/51057.
