### ISSUE TITLE
Provide precise position for audio stream playback

### ISSUE THREAD

**Issue by mortarroad** [godotengine/godot-proposals#2603] opened 2021-04-14 08:37 UTC
### The issue
Currently, for synchronizing gameplay precisely with audio, the user has to jump through a bunch of hoops.
See https://docs.godotengine.org/en/stable/tutorials/audio/sync_with_audio.html

This really should not be necessary. A user should just be able to call `get_playback_position_exact()` (or similar), and get a precise position.

### Implementation
I think this should be implemented by implementing the second approach ["Using the sound hardware clock to sync"](https://docs.godotengine.org/en/stable/tutorials/audio/sync_with_audio.html#using-the-sound-hardware-clock-to-sync) in the engine, while ensuring proper locking (which is not possible in script afaik. The tutorial recommends to _Just check that the value is not less than in the previous frame (discard it if so)._, which is not really satisfactory.)

### A related issue

When looking into this, I also noticed that the `get_playback_position()` function on audio streams does not appear to use any sort of locking, which will also have to be fixed.

The exposed function is `AudioStreamPlayer::get_playback_position()`
see https://github.com/godotengine/godot/blob/8f7f5846397297fff6e8a08f89bc60ce658699cc/scene/audio/audio_stream_player.cpp#L268
which calls `get_playback_position()` on `AudioStreamPlayback`, for example implemented in `AudioStreamPlaybackOGGVorbis`
see https://github.com/godotengine/godot/blob/8f7f5846397297fff6e8a08f89bc60ce658699cc/modules/stb_vorbis/audio_stream_ogg_vorbis.cpp#L100

Maybe I'm mistaken, but I think there is some locking missing here.
The same is probably true for other methods like start(), stop(), etc.

**Comment by Calinou** [comment] 2021-04-14 11:32
Duplicate of https://github.com/godotengine/godot-proposals/issues/1151.

**Closed by Calinou** 2021-04-14 11:32 UTC
Labels: topic:audio
