### ISSUE TITLE
Return the posibility of selecting filtering per texture for fix regressions. 

### ISSUE THREAD

**Issue by yosoyfreeman** [godotengine/godot-proposals#6241] opened 2023-02-05 13:11 UTC
### Describe the project you are working on

A 3D game with pixel art materials.

### Describe the problem or limitation you are having in your project

In Godot 4 we lose all control over the filtering of textures and was replaced with an option to activate or deactivate filtering in the material. This have the next problems:

- Less control over the final result, forcing you to compromise the look and feel of your game. This is specially notable now that using a nearest neighbour albedo will force you to use the same on the other PBR maps, resulting in a significant lost of quality. The 3D pixel art workflow is usually based on a pixelated look with filtered PBR maps. notice this was possible before and totally broke all my work.

- For performance reasons, in modern PBR games,  Lots of little props will use a filtered albedo with an unfiltered normal and roughness map. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I think that the current workflow truly harms the possibilities of one of the core elements of a 3D engine.  Also, this is technically a regression since it was possible before.

The previous version was far ahead on usability, but for respecting the current method of changing it per material, the option should be per map on the material. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Allow to change the filtering of each map individually.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it can't be worked around. The control over this things is a core element and should be easily accessible as it was before. 

### Is there a reason why this should be core and not an add-on in the asset library?

This should be a core element as is foundational to work with 3D Elements and not fixing it would result in a heavy lost of control and regressions in lots of 3D projects.

**Comment by Calinou** [comment] 2023-02-06 09:16
Requiring you to manually specify filter mode for every texture would slow down material setup a lot, as you'd now potentially have to change it 7 times instead of just 1.

> The 3D pixel art workflow is usually based on a pixelated look with filtered PBR maps.

This is still feasible with custom shaders.

**Comment by KoBeWi** [comment] 2023-02-06 09:18
Duplicate of #5225

**Closed by KoBeWi** 2023-02-06 09:18 UTC
Labels: topic:core, topic:rendering, topic:shaders
