### ISSUE TITLE
Target Android API Level 31 (Android 12) as it will be required by Google to upload apps to Play Store from August, 1 2022

### ISSUE THREAD

**Issue by NanitesNanites** [godotengine/godot-proposals#4499] opened 2022-05-05 22:26 UTC
### Describe the project you are working on

Game to be published on the Play Store

### Describe the problem or limitation you are having in your project

From August 1 2022, Google will require all new apps to target API Level 31:
https://support.google.com/googleplay/android-developer/answer/11926878
a few months later it will apply to updates too.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Without targeting API 31, you won't be able to upload new apps to Play Store.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

-

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

-

**Comment by Calinou** [comment] 2022-05-05 23:05
Duplicate of https://github.com/godotengine/godot/issues/48636.

Platform support does not require feature proposals – we'll handle the required changes.

**Closed by Calinou** 2022-05-05 23:05 UTC

**Comment by SnipFernandez** [comment] 2022-06-05 15:17
I am interested in this question. Is it known for which version of godot will have compatibility with android 12 api 31?

**Comment by Calinou** [comment] 2022-06-05 15:28
> I am interested in this question. Is it known for which version of godot will have compatibility with android 12 api 31?

See my above comment. This won't be done for 3.5 as it's too close to release, but a future 3.5 patch release will likely add  support for targeting API level 31 or greater.

**Comment by SnipFernandez** [comment] 2022-06-09 06:31
@Calinou Thank you very much for the answer, I will be attentive, greetings.
