### ISSUE TITLE
Live++ - Live C++ Hot Reload \ Live Coding or Similar

### ISSUE THREAD

**Issue by RaTcHeT302** [godotengine/godot-proposals#108] opened 2019-09-27 21:07 UTC
Either this, or a similar feature if possible.
https://molecular-matters.com/products_livepp.html

I really don't care if this issue log gets closed, as I don't have time to fill up that huge list in the template. I'm not experienced enough, and I don't have the time to come up with some solid reasons as to why this should be added. Honestly, I'm fine with just a simple Yes or No.

If this is not a good fit for Godot, I understand, I just wanted to bring it up mostly that's all. 👌

Don't take it personally, I just lack the time to write a more detailled write up, and I don't have the time to interact with open source communities in depth, I'm more touch and go.

**Comment by RaTcHeT302** [comment] 2019-09-27 21:08
I do feel like the requirements are way too rigid though, I really wish there was a "just chuck your idea out there" type of thing. This is too formal for me personally. I just don't have the time for these things, sorry.

**Comment by Calinou** [comment] 2019-09-27 21:18
> I do feel like the requirements are way too rigid though, I really wish there was a "just chuck your idea out there" type of thing. This is too formal for me personally. I just don't have the time for these things, sorry.

The requirements are made so that only "well-planned" proposals can be submitted. This is done by design, to prevent proposals from being submitted if you don't actually need them for a project you're working on. We need to do this to keep the number of proposals mangeable.

As this proposal doesn't follow the template, I'm afraid I'll have to close it.

**Closed by Calinou** 2019-09-27 21:18 UTC
