### ISSUE TITLE
Implement multi-pass post-processing shaders

### ISSUE THREAD

**Issue by seadra** [godotengine/godot-proposals#895] opened 2020-05-25 19:52 UTC
(This is issue [#862](https://github.com/godotengine/godot/issues/862) from Godot repo. On multiple occasions in that issue, @reduz mentioned that this is going to be implemented in a later version.)

**Describe the project you are working on:**

A 3D FPS game.

**Describe the problem or limitation you are having in your project:**

Certain effects (such as [this](http://www.clicktorelease.com/code/npr-shading/) or [this](http://forums.tigsource.com/index.php?topic=40832.msg1027171#msg1027171)) require multiple passes (of the entire viewport, not per-material), each time with a different shader, either finally combining the outputs into a final one, or using the output of one pass as input to the next one.

In Unity, [Pass](http://docs.unity3d.com/Manual/ShaderTut2.html) allows to do this.

Right now, it is impossible to do multiple passes with godot, so we are restricted to "simple" stuff that can only involve a single pass.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

It will allow doing multi-pass post-process shaders.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

One possibility (among potential alternatives) would be that it can work in a similar way as described in  [Unity documentation](http://docs.unity3d.com/Manual/ShaderTut2.html), which would require modifications to shading language.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This would require changes in the engine itself.

**Comment by SIsilicon** [comment] 2020-05-27 12:56
Great, but I think it would be a good idea if you finished the rest of that proposal form.

**Comment by API-Beast** [comment] 2020-12-10 17:28
This is also significant for generating textures.

Physical based rendering requires a color map, a height map, a normal map, a roughness map etc... the way it is you can only generate one texture at a time, having to execute the same shader multiple times to generate the other ones, requiring significantly more processing to be done by the GPU for the same result. It's the biggest factor stopping Godot from being a good platform for developing more complex shaders.

**Comment by Calinou** [comment] 2021-09-19 18:23
Duplicate of https://github.com/godotengine/godot-proposals/issues/496.

**Closed by Calinou** 2021-09-19 18:23 UTC
Labels: topic:rendering, topic:shaders
