### ISSUE TITLE
Lighting problems: negative lighting’s scuff and vertex shading’s yet to be implemented.

### ISSUE THREAD

**Issue by DarkDruid216** [godotengine/godot-proposals#6404] opened 2023-03-02 15:35 UTC
### Describe the project you are working on

I’m working on a mobile turn based tactics game with its graphics in the vein of 5th gen games. I’m looking to use baked lighting for my scenes so the device wouldn’t have to process them on every single frame.
This’s only half of the story. I’m looking to use vertex lighting to cheapen the cost to run the game. I’m also thinking of using subtractive lighting for the likes of exitways, interiors, or certain abilities to have them pop a tad bit more.

### Describe the problem or limitation you are having in your project

I see they’ve yet to implement vertex shading.
Meanwhile, negative lighting seems half implemented. It half works as expected, subtracting the lighting from the scene, but it seems to add in other distances.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

🤷‍♂️
Just finish implementing them?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

…

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not necessarily.

### Is there a reason why this should be core and not an add-on in the asset library?

Well… they are the core features.

**Comment by AThousandShips** [comment] 2023-03-02 15:39
"just finish implementing them" is rude and unhelpful

Are you talking about per vertex lighting in baked lightmaps?

**Comment by DarkDruid216** [comment] 2023-03-02 15:46
Real-time lighting.
I was mostly concerned about real time lighting.
I was planning to use mainly pixel-based lighting for my baked lightmaps.
Though, vertex based baked lighting for ambient occlusion would be pretty cool.

my apologies for it sounding rude by the way.

**Comment by AThousandShips** [comment] 2023-03-02 15:47
You can already do vertex based lighting? Or what specifically are you looking for?

**Comment by DarkDruid216** [comment] 2023-03-02 15:51
Well… I can’t. That’s the entire problem.
I made an entire shader and toggled it to activate “vertex shading.” It doesn’t work because, according to the tooltip, it’s yet to be implemented.

**Comment by AThousandShips** [comment] 2023-03-02 16:07
My bad I had forgotten it wasn't available at the moment

**Comment by AThousandShips** [comment] 2023-03-02 16:13
I don't know what the timeline for implementing vertex lighting for Vulkan, but probably in 4.1

**Comment by DarkDruid216** [comment] 2023-03-02 16:15
Ah. Sounds like something to keep my eye on, then. Compatibility, by the way. People who don’t have Vulkan are part of my audience! ÙwÓ

**Comment by AThousandShips** [comment] 2023-03-02 16:16
The timeline for compatibility is likely a bit slower because it's generally behind the curve compared to Vulkan in terms of completeness

**Comment by Calinou** [comment] 2023-03-02 17:37
- Duplicate of https://github.com/godotengine/godot/issues/43093.

Regarding the negative lighting issue, are you sure specular lighting isn't messing up with the final result? Try setting Specular to 0 when using negative lights. (Note that the [Specular property has no effect with DirectionalLight3D in 4.0](https://github.com/godotengine/godot/issues/54244), but it works with omni and spot lights.)

**Closed by Calinou** 2023-03-02 17:37 UTC

**Comment by Calinou** [comment] 2023-03-02 17:52
> well, I tried that, but here’s the results.
If it’s one, it works as expected, but if it’s higher than 1…

You'll probably need to use a material with a custom shader to clamp lighting values in the `light()` function.

**Comment by DarkDruid216** [comment] 2023-03-02 17:54
Think I’ve to do so, as well.
