### ISSUE TITLE
Add a `wait([float seconds])` function

### ISSUE THREAD

**Issue by vPumpking** [godotengine/godot-proposals#6439] opened 2023-03-05 17:32 UTC
### Describe the project you are working on

nothing particular, but searching to resolve some ergonomic problems

### Describe the problem or limitation you are having in your project

every time someone wants to do a pause without freezing the game in the code, he has to write `await get_tree().create_timer([seconds]).timeout` which is very fastidious to write.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

by adding `wait` function doing the same thing that `await get_tree().create_timer().timeout`, it will be more convenient

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

the user can call this function and just give it a float or an int as parameter to set the number of seconds to wait

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it can be worked around but it's less convenient

### Is there a reason why this should be core and not an add-on in the asset library?

gdscript is part of the core

**Comment by KoBeWi** [comment] 2023-03-05 19:49
Similar to #4886

**Comment by YuriSizov** [comment] 2023-03-05 23:26
You would still need to use `await` with it, so I'd say it's a duplicate of the linked issue.

**Closed by YuriSizov** 2023-03-05 23:26 UTC
Labels: topic:gdscript
