### ISSUE TITLE
NEED : find (Symbols) references & rename refactoring funtion

### ISSUE THREAD

**Issue by jzq740176597** [godotengine/godot-proposals#6619] opened 2023-04-04 03:53 UTC
### Describe the project you are working on

3d

### Describe the problem or limitation you are having in your project

it's very common & vital funtion for Find References & rename it at once

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

for now, I just search all the scripts files and replace with new-name; EVEN to guarantee it works ONLY by running.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

*

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

core

**Comment by Zireael07** [comment] 2023-04-04 06:49
duplicate of #899

**Closed** 2023-04-04 09:54 UTC
