### ISSUE TITLE
Add a handle on the animation editor timeline to move an entire row of keyframes at the same time

### ISSUE THREAD

**Issue by holzmb** [godotengine/godot-proposals#3170] opened 2021-08-20 10:11 UTC
### Describe the project you are working on

Game

### Describe the problem or limitation you are having in your project

It was suggested years ago: https://github.com/godotengine/godot/issues/18690
I would like to suggest to insert a keyframe in the TimeLine to move all keyframes at same row. Currently you have to drag to select all keyframes, and if you have a lot of keyframes this become troublesome:

![](https://user-images.githubusercontent.com/23051495/39721803-06430950-5217-11e8-8c2b-da28f6721251.gif)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In DragonBones, a Skeleton Animation 2D tool, you can drag a keyframe at the timeline to move all keyframes of the same row:

![](https://user-images.githubusercontent.com/23051495/39722017-b4257ce2-5217-11e8-9422-6a14f64cfb3d.gif)

I worked in a long animation on Godot, and this feature would've helped a lot.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like in the gif above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know if this can be make with an editor plugin

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the animation usability out of the box

**Comment by Calinou** [comment] 2021-08-20 13:13
> In DragonBones, a Skeleton Animation 2D tool, you can drag a keyframe at the timeline to move all keyframes of the same row:

Is this timeline keyframe displayed only if at least two tracks have a keyframe present at the same time, or is it always present whenever there is a keyframe somewhere in a track?

**Comment by holzmb** [comment] 2021-08-20 18:17
always present

**Comment by Lebostein** [comment] 2021-08-31 18:22
Wow is this bad. I am working now 1 week with Godot an all I found is fine. But THAT thing is the worst behaviour I have ever seen in key frame aniamtion editors. There is NO way to select all keys for on time. You can draw a selection frame over more than one key, but the scrolling don't work. Apparently the developers haven't used the editor themselves yet...

**Comment by Calinou** [comment] 2021-08-31 18:40
@Lebostein Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by Calinou** [comment] 2021-09-12 23:44
Duplicate of https://github.com/godotengine/godot-proposals/issues/1908.

**Closed by Calinou** 2021-09-12 23:44 UTC
Labels: archived, topic:editor, topic:animation
