### ISSUE TITLE
Add `Array.find_custom(Variant value, Object obj, String func, int from=0)`

### ISSUE THREAD

**Issue by AllenKll** [godotengine/godot-proposals#1120] opened 2020-06-26 04:53 UTC
**Describe the project you are working on:**
Turn based RPG

**Describe the problem or limitation you are having in your project:**
I need to search an array of classes for the index of a class that contains a specific value.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Adding my own custom find predicate would allow me to not have to rewrite a very standard container search function

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
This should be used similarly to how C++ STL has a search predicate available.
https://www.cplusplus.com/reference/algorithm/search/
 
example usage :

    class Person extends Resource:
        var position
        var name
        var value

        func _init(p,n,v):
            position = p
            name = n
            value =v

    func findByName(obj, val):
        return obj.name == val
    func findByValue(obj, val):
        return obj.value == val
    func findByPosition(obj, val):
        return obj.position == val

    var myArray = []
    myArray.push_back(Person.new(Vector2(0,0), "bob", 15))
    myArray.push_back(Person.new(Vector2(12,12), "jane", 47))
    myArray.push_back(Person.new(Vector2(62,14), "will", 999))
    myArray.push_back(Person.new(Vector2(1,1), "jenny", 75))

    print("Index of Person at 12,12: " + str( myArray.find_custom(Vector2(12,12), self, "findByPosition") ))
    print("Index of Person with 47 : " + str(  myArray.find_custom(47, self, "findByValue") ))
    print("Index of Person named jenny: " + str(  myArray.find_custom("jenny", self, "findByName")  ))

The code for find_custom would loop through the array starting at `from`, call `obj.func` for the entry at the current index, and if the function returns true, returns the index of the current object.  Something like this:

    ... somewhere in class Array

    func find_custom(value, obj, func, from):
        for x in range(from, arrayData.size()):
            if obj[func]( arrayData[x], value ):
                 return x
        return -1

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I would expect any data heavy application to use something like this quite often.  I'm rather surprised that this basic functionality was not implemented, especially since there is a custom binary search method... but this method requires sorting.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Not sure how you could expand basic gdscript functionality as an addon.  I don't know enough about the structure of Godot.

Naming is unimportant..  call it search_custom, call it find_custom.  whatever makes sense to the implimenter.  I think 'find' would make the most sense, as it would parallel the find command.

**Comment by AThousandShips** [comment] 2023-09-17 09:49
Duplicate of https://github.com/godotengine/godot-proposals/issues/6889

**Closed by AThousandShips** 2023-09-17 09:49 UTC
Labels: topic:core
