### ISSUE TITLE
Allow ExportAttribute to be Inheritable for Custom Attribute Extension

### ISSUE THREAD

**Issue by StarryTang** [godotengine/godot-proposals#11367] opened 2024-12-17 04:04 UTC
### Describe the project you are working on

Overview
I am developing an industrial simulation engine editor using Godot. To display and configure properties in the editor's EditorInspector, I have created a custom SpecAttribute similar to ExportAttribute. This custom attribute allows me to mark properties and provide additional metadata for my custom editor.

However, I also want Godot's standard Inspector to recognize the same SpecAttribute, which would prevent duplicate attribute declarations. Unfortunately, ExportAttribute cannot currently be inherited, which blocks this use case.

Request
I would like ExportAttribute to support inheritance. This change would allow developers to extend ExportAttribute for their custom needs, while still having the Godot engine recognize these extended attributes.

### Describe the problem or limitation you are having in your project

I am using Godot to develop an industrial simulation engine editor that requires highly customizable property displays and controls in the editor Inspector.
I have created a custom attribute, SpecAttribute, which provides metadata such as hints and strings for custom editors.
Allowing ExportAttribute to be inherited would enable both Godot’s built-in Inspector and my custom Inspector to recognize the same attribute without duplicating property declarations.
This change would simplify development, reduce redundancy, and improve the developer experience.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By inheriting ExportAttribute, SpecAttribute can be recognized by both Godot’s standard Inspector and my custom editor.
Avoids duplicating attributes, simplifying code and improving maintainability.
Provides a flexible way to extend the functionality of ExportAttribute.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Example Code

Current Situation:
```c#
[Export]
public int SomeValue { get; set; }

[Spec(PropertyHint.Enum, "Option1,Option2,Option3")]
public int CustomValue { get; set; }

``` 

Ideal Solution:
```c#
public class SpecAttribute : ExportAttribute
{
    public PropertyHint Hint { get; }
    public string HintString { get; }

    public SpecAttribute(PropertyHint hint = PropertyHint.None, string hintString = "")
    {
        Hint = hint;
        HintString = hintString;
    }
}

[Spec(PropertyHint.Enum, "Option1,Option2,Option3")]
public int CustomValue { get; set; }

```

Advantages:

By inheriting ExportAttribute, SpecAttribute can be recognized by both Godot’s standard Inspector and my custom editor.
Avoids duplicating attributes, simplifying code and improving maintainability.
Provides a flexible way to extend the functionality of ExportAttribute.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Thank you for your reply! Regarding the question, “If this enhancement is not frequently used, can it be resolved with a script?”, I have tried to achieve similar functionality using EditorInspectorPlugin, but I encountered several challenges:

Inconsistent Style: Custom property panels implemented through EditorInspectorPlugin are difficult to match with the native Godot Inspector’s style and appearance.
Display Position Issues: The custom property editors may not appear in the desired position within the Inspector, making it hard to integrate seamlessly with other properties.
Complex Maintenance: To support different property types (e.g., int, float, string, Node, etc.), I would need to manually write and maintain multiple custom property editors. This results in a significant amount of code and increases the potential for errors.
In reality, my requirement is quite simple: I want to use Godot’s native Inspector style and behavior while extending the ExportAttribute to achieve my goal. Allowing ExportAttribute to be inheritable would greatly simplify the implementation while perfectly preserving consistency with Godot’s internal Inspector.

### Is there a reason why this should be core and not an add-on in the asset library?

This functionality should be considered a core feature rather than an asset library add-on for the following reasons:

Deep Integration with Built-in Features:
The ExportAttribute is a core part of Godot’s functionality that allows properties to appear in the Inspector for editing. Making it inheritable enables users to extend the native experience seamlessly without rewriting Inspector logic or relying on complex plugins.

Consistency and Standardization:
Solving this problem via add-ons can lead to inconsistencies between user-defined property displays and Godot’s native Inspector style, which degrades the user experience. By making it a core feature, we ensure a unified look and feel while reducing maintenance overhead.

High Reusability and Low Maintenance:
Allowing ExportAttribute to be inheritable is a lightweight enhancement that solves many extensibility scenarios, making it ideal for industrial simulation editors, game editors, and other applications. As a core feature, it directly benefits from engine updates without requiring users to maintain additional plugins or compatibility fixes.

Reduces Redundancy and Duplication:
If developers are forced to implement similar functionality via add-ons, they often end up writing redundant code to handle different property types, display styles, and sorting logic. Native support as a core feature eliminates this duplication, enabling developers to focus on their business logic.

Enhancing Engine Extensibility:
Making ExportAttribute inheritable improves the flexibility and extensibility of the Godot engine. This enhancement not only satisfies current needs but also paves the way for future use cases involving customized property display and editing.

**Comment by raulsntos** [comment] 2024-12-18 04:41
- Closing as duplicate of https://github.com/godotengine/godot/issues/67624.

But as explained in the other issue, making the `ExportAttribute` inheritable won't make your custom attribute work with the Godot editor. Our C# source generators are only looking for the `ExportAttribute` and won't work with any other attributes that we don't explicitly add support for.

We know there's user demand for custom `[Export]`-like attributes, but we don't think this requires unsealing the attribute and will be exploring different options.

**Closed by raulsntos** 2024-12-18 04:41 UTC
Labels: topic:dotnet
