### ISSUE TITLE
Make the visual script editor as 'customizable' as the text editor or, more . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#2156] opened 2021-01-20 05:19 UTC
### Describe the project you are working on
A Tomb raider game . .

### Describe the problem or limitation you are having in your project
Currently, one can edit many settings, for written code editor, but it's not there, for visual script . . I was hoping, visual script editor could be nearly as customizable, as the written code editor . .
![2021-01-20 0614](https://user-images.githubusercontent.com/61069740/105130333-1dde8680-5ae7-11eb-97cc-ff0d4a539b59.gif)

If Godot had that, I could easily make a SUPERB, stable visual script experience, and it'd be much more pleasant, to work in, also for tutorials, but simply the coding experience, rock - solid <3

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Make a section, similar to ' Text editor ', but for visual script, where one can fine - tune how it looks and, 'feels', Thanks . . :OO 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Well, currently it's missing, if we had that, one could customize Visual script to make it rock - solid or, more . . <3

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This is more than just, this is writing engine level stuff . .

### Is there a reason why this should be core and not an add-on in the asset library?
Well, customizing the text editor is already there, we need the same or, close level of customization for visual script, so we can make it shine and, glow . . <3

All I ask is, that we can customize the ' shit ' out of the Visual script experience, I'll make it good, solid and, near pristine, if we had that <3

**Comment by jasperbrooks79** [comment] 2021-01-20 05:28
if we could customize the visual script editor, in as much or, close to detail, of written text editor, I could take the visual script experience, to a new level, of awe - some <3
<img width="1410" alt="Skærmbillede (926)" src="https://user-images.githubusercontent.com/61069740/105130985-5894ee80-5ae8-11eb-88a1-0dcc7f5a9d68.png">

we need to be able to set color and, opacity of major horizontal, vertical lines, and the ones in between . . I'd also like, to be able to select some classic lines, for the rows and, vertical lines . .>>>
![2021-01-13 0316](https://user-images.githubusercontent.com/61069740/105131143-a6a9f200-5ae8-11eb-8085-280857f1b43e.png)

Atm, it's simply missing, and it would help users make the best, most robust Visual script experience, at all <3

**Comment by fire** [comment] 2022-01-03 05:19
Describe the feature / enhancement and how it helps to overcome the problem or limitation

> Make a section, similar to ' Text editor ', but for visual script, where one can fine - tune how it looks and, 'feels'

I'm not sure how to do this. We add this per feature and a general design is that we don't make setting configurable unless required.

**Comment by Zireael07** [comment] 2022-01-03 07:44
Related/dupe of https://github.com/godotengine/godot-proposals/issues/2364 ?

**Comment by YuriSizov** [comment] 2022-08-24 16:17
Closing this proposal as we have [officially discontinued the VisualScript module](https://github.com/godotengine/godot/pull/64822). It may return in future as an engine extension, then all the feedback can be reevaluated by maintainers of that extension.

Thanks for your suggestion nonetheless!

**Closed by YuriSizov** 2022-08-24 16:17 UTC
Labels: topic:editor, topic:visualscript, topic:gui
