### ISSUE TITLE
Add built-in shader documentation to the editor

### ISSUE THREAD

**Issue by paddy-exe** [godotengine/godot-proposals#4302] opened 2022-03-28 12:41 UTC
### Describe the project you are working on

3D shaders such as stylized Sky and Water shaders

### Describe the problem or limitation you are having in your project

When trying to port some shaders from Unity or other sources that don’t have Godot‘s built-in shader types, it’s a real pain to first look up the possible attributes that do the same in Godot and then switch back again to the editor. I have a 2-monitor setup and even for me it’s cumbersome to switch the windows so many times. For devs only working with laptops or 1 monitor this should be even worse.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Having a built-in documentation for the shader editor. So it would behave similarly to the scripting documentation. This would reduce the amount of window switching by a lot and would improve the workflow working on shaders.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user clicks on a specific built-in keyword/function a new entry will opened in a panel similar to the script panel. So the shading reference could be split in the different Shader-Built-Ins and the built-in functions. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

To an extend it would be possible to have a new entry next to the AssetLib for this or next to the shader editor but then again, you would be switching a lot. The looking-up functionality by clicking on the keyword can’t be implemented by an addon.

### Is there a reason why this should be core and not an add-on in the asset library?

Having a direct shader documentation in the editor with the above mentioned look-up feature needs core/engine integration

**Comment by Calinou** [comment] 2022-03-28 12:43
Duplicate of https://github.com/godotengine/godot-proposals/issues/3767.

**Closed by Calinou** 2022-03-28 12:43 UTC
Labels: topic:editor, topic:shaders
