### ISSUE TITLE
Show the remote scene in the canvas view while debugging

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-proposals#745] opened 2020-04-23 15:53 UTC
**Describe the project you are working on:**

A Starcraft-like RTS.

**Describe the problem or limitation you are having in your project:**

I need to search in the remote scene tree when I need to view the stats of a unit while debugging the game. This is difficult if the tree is large or the node names are not descriptive.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

When the scene tree is in "remote" mode, the remote scene should show in the canvas view like it does with the local tree. You can select and modify nodes like normal. Selected nodes show their properties in the inspector.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

![2020-04-23-174452_1280x1024_scrot](https://user-images.githubusercontent.com/28286961/80120385-2f602580-858b-11ea-88a2-03f663bf6ac8.png)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No.

**Is there a reason why this should be core and not an add-on in the asset library?:**

For it to be implemented well it needs to be built-in.

**Comment by Zireael07** [comment] 2020-04-23 17:12
Oh yeah, this would be so welcome.
(My game is in space, but also has features of 2D RTS, and tracking down where my AI subordinates went to... is difficult)

**Comment by lostfictions** [comment] 2020-12-20 07:34
Coming to Godot from Unity, one of the most surprising things was that there's no way to inspect the remote scene in the viewport at all. For many categories of issues this feels to me like having a blindfold on compared to Unity!

Here's a small example of a situation I experienced where visualizing the remote scene could have been helpful: a scene's hierarchy was improperly set up, such that one subtree of an entity's position was diverging from its corresponding sprites (ie. siblings instead of parent-child). The problem was difficult to detect from the running game, since the visual representation of the entity -- the sprite -- was simply not moving. In some situations turning on Visible Collision Shapes can help with this particular case. But in other circumstances this category of error is difficult to diagnose from simply poring over node positions in textual form -- positions and transforms are the kinds of things that are much easier to understand visually.

By contrast, I've experienced similar hierarchy issues in Unity, but it's always almost trivially easy to detect -- if you pause the game and click around the scene hierarchy it immediately becomes clear to see if something's not where it should be.

**Comment by samOtero** [comment] 2022-07-20 22:20
I agree with @lostfictions on this, I'm also coming from Unity and I'm really missing this feature. I can see it working with a similar toggle, "Remote/Local", that the scene tree has.

In my case I'm building a Tower Defense game, so most of my units are going to be generated with scripts. Having a ton of units and wanting to inspect a certain one during debug can be incredibly hard to find via just the tree. 

This feature would let me click on the unit visually and see it's properties in the inspector.

Would love to see this come in at some point!

**Comment by Calinou** [comment] 2022-07-20 22:52
Duplicate of https://github.com/godotengine/godot-proposals/issues/1864.

**Closed by Calinou** 2022-07-20 22:52 UTC
Labels: topic:editor
