### ISSUE TITLE
Make join constraints editable in runtime through script

### ISSUE THREAD

**Issue by Favkis** [godotengine/godot-proposals#1969] opened 2020-12-11 08:04 UTC
### Describe the project you are working on
3d game with ragdoll based physics

### Describe the problem or limitation you are having in your project
I cannot change x y z contraints when game is run to make active ragdoll physics

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
If I could edit constraints for all x y z, maknig ragdoll based animations would be easy and possible
![image](https://user-images.githubusercontent.com/46406204/101878095-0e8f2380-3ba0-11eb-933f-470619b3d05c.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I don't know how physics engines work. if there is some kind of ragdoll system in them - I supose it already has these constraints and they can be changed real time. You can add new methods for physicalbone - set_join_constraint_angle_x_min(), min, max, x y and z. It'd be better of course to have not only angular limits (while it is most important and essential for maknig ragdoll based animations), but having all settings would be amazing.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I'm not sure it's possible to edit it right now.

### Is there a reason why this should be core and not an add-on in the asset library?
Essential for almost all physics based animation games.

**Comment by Demindiro** [comment] 2020-12-11 16:10
You should be able to change it using the [`set`][1] function (like `joint.set("joint_constraints/x/angular_limit_upper")`)

[1]: https://docs.godotengine.org/en/stable/classes/class_object.html#id4

**Comment by Calinou** [comment] 2020-12-11 16:55
Duplicate of https://github.com/godotengine/godot/issues/17558.

**Closed by Calinou** 2020-12-11 16:55 UTC
Labels: topic:physics

**Comment by Favkis** [comment] 2020-12-12 07:33
@Demindiro @Calinou how do I get joint from PhysicalBone? I don't see any methods or properties like that

**Comment by Favkis** [comment] 2020-12-12 07:39
![image](https://user-images.githubusercontent.com/46406204/101978467-3cd73680-3c66-11eb-9366-55ac53217569.png)
It doesn't work for me if I just do it for PhysicalBone. It shoudl T pose cause lower is -1 and upper 1, but ragdoll behaves normally how I set it up in editor.

**Comment by Demindiro** [comment] 2020-12-12 12:53
Can you try using [`get`][1] to see what the actual value is? For me it seems works fine.

```gdscript
var t = 0
func _process(_delta):
	t += 1
	$PhysicalBone.set("joint_constraints/x/angular_limit_upper", t)
	var x = $PhysicalBone.get("joint_constraints/x/angular_limit_upper")
	print(x)
```

[1]: https://docs.godotengine.org/en/stable/classes/class_object.html#id1

**Comment by Calinou** [comment] 2020-12-12 14:15
See https://github.com/godotengine/godot/issues/44320.

**Comment by Favkis** [comment] 2020-12-12 15:03
@Demindiro 
![image](https://user-images.githubusercontent.com/46406204/101987189-9f9af300-3ca3-11eb-9799-0448b9603136.png)
Weird, it shows -25 and 25, however my Z axis is -25 and 25.

I think I can see what happened here, it's similar to how ragdoll contrains are being set, I have my skeleton rotated in blender so in godot my armature node has -90 Y rotation, it made it so that my ragdoll constraints are not actually corrent, for example setting X actually sets Z or something, I was just setting each rotation by hand and see what was happening because I couldnt understand why X is not X etc. It looks like it's somehow related, as you can see when I read them it reads rotated result axis, but writing to them does nothing at all
![image](https://user-images.githubusercontent.com/46406204/101987237-e5f05200-3ca3-11eb-8f4e-6d9ec766ffb4.png)
