### ISSUE TITLE
Support Markdown Syntax in RichTextLabel

### ISSUE THREAD

**Issue by eddex** [godotengine/godot-proposals#1153] opened 2020-07-02 13:26 UTC
**Describe the project you are working on:**
I want to display a `README.md` (or other markdown files) in a `RichTextLabel`.

**Describe the problem or limitation you are having in your project:**
I need to convert the Markdown syntax of the` README.md` file into BbCode.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
It would be great if the `RichTextLabel` would also support Markdown syntax (alongside BbCode).
Like this, both formats can be used to write the rich text and Markdonw files can be displayed directly.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
The `RichTextLabel` should provide a setting to choose between BbCode and Markdown.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Yes, there are tools and websites to convert Markdown to BbCode.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a change in one of the core nodes. However, an add-on could be implemented to converts Markdown to BbCode.

**Comment by Calinou** [comment] 2020-07-02 14:05
Duplicate of #139.

**Closed by Calinou** 2020-07-02 14:05 UTC
