### ISSUE TITLE
Customize script editor navigation vertical speed with mouse wheel

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#5495] opened 2022-09-26 06:59 UTC
### Describe the project you are working on

This tip focuses on the editor and not on a specific project.

### Describe the problem or limitation you are having in your project

I have a lot of code and to navigate my scripts I need the editor to scroll faster when I use the middle mouse wheel to scroll vertically.
Godot does not allow you to customize the scrolling speed of the script editor using the middle mouse wheel.

I don't know what this option is for.
Nothing happens when I change the value.
![Captura](https://user-images.githubusercontent.com/19652075/192213764-42c767e7-ae5d-476c-a38b-1f5670b4f4c6.PNG)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I want to navigate faster using the middle mouse wheel in the script editor.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add an option to the editor to set the number of lines the wheel will scroll when scrolling vertically in the script editor.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

...

### Is there a reason why this should be core and not an add-on in the asset library?

...

**Comment by MewPurPur** [comment] 2022-09-26 07:55
You can modify scroll speed with Alt or Shift I believe, and that's consistent with sliders.

**Comment by Torguen** [comment] 2022-09-26 08:09
That's a poor option, pressing ALT + mouse wheel does indeed make the scroll faster but it's still not customizable.
What if I want more speed? Also I don't want to have to press ALT.

**Comment by Torguen** [comment] 2022-09-26 08:11
1 - Have godot get the mouse wheel lines scroll speed setting set in windows.

2 - Implement a new option in Godot that allows to set a custom scroll speed for the mouse wheel in the script editor.

**Comment by Calinou** [comment] 2022-09-26 13:36
Duplicate of https://github.com/godotengine/godot-proposals/issues/3975.

**Closed by Calinou** 2022-09-26 13:36 UTC
