### ISSUE TITLE
Notify users when There is a newer stable version of Godot

### ISSUE THREAD

**Issue by hakro** [godotengine/godot-proposals#6441] opened 2023-03-05 22:42 UTC
### Describe the project you are working on

Nothing specific, this is related to the Godot editor itself.

### Describe the problem or limitation you are having in your project

There is no indication of a newer version in the editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be nice to have some kind of visual clue when there is a newer stable version of Godot available.
That is, if the user is using Godot 4.0, it would encourage her to go get 4.0.1, if it's available.
And eventually, make the update possible just by clicking on a button.

Many Open Source projects are able to do this. The [Lapce](https://github.com/lapce/lapce) editor come to mind.

Here, I'm using the latest version of Lapce, but when a new version is available, the Gray button shows the new version number, and can be cliked to update the editor.
![2023-03-05_23-30](https://user-images.githubusercontent.com/3624853/222989792-8f697679-9df0-4590-bac0-a9f99591b5bd.png)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This would probably work by making a HTTP call to an endpoint that returns the latest stable version, when there is an internet connection.
It could be just a text file containing the version and stored in Github.
The content of that file will then be compared with the current Godot version, and if there is a diffence, the user would be notified.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is just a generic QoL improvement, and one that will help people keep up to date Godot version installed

### Is there a reason why this should be core and not an add-on in the asset library?

This is related to editor itself, there is no point in having it as an external asset.

**Comment by YuriSizov** [comment] 2023-03-05 23:21
Duplicate of https://github.com/godotengine/godot-proposals/issues/1132

In general, many prefer Godot because it doesn't "phone home", so this feature has been indefinitely postponed. There are other tools that can help you though, such as using Steam/itch launcher, or Project Hourglass, perhaps.

**Closed by YuriSizov** 2023-03-05 23:21 UTC
