### ISSUE TITLE
Add a check box to directories to select resources in Exporter's resources selector

### ISSUE THREAD

**Issue by xenicle** [godotengine/godot-proposals#1488] opened 2020-09-10 01:31 UTC
**Describe the project you are working on:**
2D Wave Defense Game

**Describe the problem or limitation you are having in your project:**
In the Exporter if I'm selecting "Export selected resources" : in the "Resources to export" window I'm find tedious to check every resources in a directory when I have many resources in this one.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
in "Resources to export" window add a checkbox in front of directories to select/unselect all resources in it. If not all resources are selected the checkbox can display a minus "-" to reflect it.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
on_directoryCheckbox_checked()
      directory.{resourcesCheckboxes}.check()

on_directoryCheckbox_unchecked()
      directory.{resourcesCheckboxes}.uncheck()

```

```
on_resourcesChecbox_[un]checked()
      var nbChecked = 0
      var nbUnChecked = 0

      for resourcesCheckbox in directory:
            if resourcesCheckbox.checked():
                  nbChecked += 1

            if resources_checkbox.unchecked():
                  nbUnChecked += 1

      if nbChecked > 0 and nbUnChecked > 0:
            directoryCheckbox.display_minus()
      elif nbChecked == directory.size():
            directoryCheckbox.check()
      elif nbUnChecked == directory.size():
            directoryCheckbox.uncheck()
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, because it's a Godot itself enhancement.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because, I'm thinking, it's a minor enhancement to Godot Exporter

**Comment by KoBeWi** [comment] 2020-09-10 02:27
Duplicate of #1454

**Closed by KoBeWi** 2020-09-10 02:27 UTC

**Comment by xenicle** [comment] 2020-09-10 02:51
Sorry for duplicate... :'(
