### ISSUE TITLE
Sort autocomplete functions based on Inheritance order

### ISSUE THREAD

**Issue by boukew99** [godotengine/godot-proposals#1790] opened 2020-11-07 21:49 UTC
**Describe the project you are working on:**
Space Arcade game.

**Describe the problem or limitation you are having in your project:**
Was looking for a function in a Raycast child, but forget the name. Then the autocomplete gives all the functions available, which are a lot. Thus I look it up in Docs. A small incovenience, but one that happens pretty often.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Sorting the the suggestions from autocomplete on inheritance order (ex. Raycast class functions on top). This would solve the above. But I don't know if there is a reason for alphabetical sort.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Sort the functions on class instead of on alphabet. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It is the Script editor.

**Comment by Calinou** [comment] 2020-11-07 23:32
Duplicate of https://github.com/godotengine/godot-proposals/issues/1216.

**Closed by Calinou** 2020-11-07 23:32 UTC
Labels: topic:editor
