### ISSUE TITLE
Renaming of exported variables should not delete associated values

### ISSUE THREAD

**Issue by SlothDevLlama** [godotengine/godot-proposals#215] opened 2019-11-08 16:50 UTC
Currently I'm working on a project where I have modules. For modules I use packed scenes with a script attached to it. I have plenty of those modules and these define some important variables via the export() hint.

![image](https://user-images.githubusercontent.com/1180429/68494853-66e24c00-024f-11ea-96df-1393523ebf46.png)

**Limitations**
One day will come for every programmer, where he wants to rename some variables. So when I have let's say over 100 modules with some values different from the default values:
![image](https://user-images.githubusercontent.com/1180429/68494960-8da08280-024f-11ea-9610-30cf3d709e9a.png)
And I rename the variable in the script. All modules using this script will immediately drop their values different from the default set inside the script.

**Better handling of exported variables**
This will lead to a general better handling of variables in scripts, since a "search and replace" might happen once a time without the developer realising that various of his ".tscn" files now lost their predefined script value.

**Describe implementation detail for your proposal (in code), if possible:**
Don't have much experience in editor-programming of the Godot engine... :-(

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
maybe currently it can be done by using an out of the box text editor (e.g. vscode) which will also look deeper into the according tscn files.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's an enhancement which user would use without knowing it, but I think a lot of people would assume that the editor will respect their predefined settings of packed scenes no matter how a variable was named, it would improve the usability of the editor A LOT.

**Comment by Calinou** [comment] 2019-11-08 20:18
This sounds quite difficult to implement… Maybe we could keep an exported variable "rename map" in the editor cache and use it when reloading a script in the editor.

**Comment by TheWhiteLlama** [comment] 2019-11-08 21:49
Another idea I've had was to make the variable right-clickable (like in known IDEs), where you could choose rename symbol and then it would also search for occurences in tscn files using this script. Not sure if that's even technically possible :-/

**Comment by KoBeWi** [comment] 2019-11-09 13:16
That should be doable with an EditorScript which would go over all scenes in the project and search every node for given script instance. Although to make it work, both old and new variable needs to exist when doing the sweep. The script would just assign old variable value to the new variable and save the scene again. The problem is that old variable would still be present in the tscn file, so you'd need another script for cleanup.

**Comment by golddotasksquestions** [comment] 2019-11-10 03:58
This has cost me hours upon hours of pointless bug hunting and made me really paranoid to check for all packed scene values as soon as something does not work. When the project is getting bigger this becomes more and more of a complication, especially when taking advantage of the Replace feature, which I like to do a lot.

**Comment by lmerriam** [comment] 2020-03-15 00:12
Related: #586

**Comment by LightningAA** [comment] 2021-09-05 14:00
Duplicate of (I think) https://github.com/godotengine/godot-proposals/issues/3152 and https://github.com/godotengine/godot-proposals/issues/899 (which go into more detail about how this would actually work.

**Closed** 2021-09-05 16:35 UTC
Labels: topic:editor

**Comment by golddotasksquestions** [comment] 2021-09-08 10:42
@Calinou I don't think this issue here is a duplicate of either #3152 #899 or #586 . They are all closely related around the same core issue, but describe different problems and propose different solutions.

**Comment by Calinou** [comment] 2021-09-08 12:15
@golddotasksquestions Since this proposal does not come with a concrete technical solution, I would prefer to leave it closed.
