### ISSUE TITLE
Add the Ability to Use the Mouse Scroll to Increase/Decrease Variables in the Editor

### ISSUE THREAD

**Issue by Lauson1ex** [godotengine/godot-proposals#2466] opened 2021-03-15 23:48 UTC
### Describe the project you are working on
This is a quality of life improvement proposal that applies to all my projects.

### Describe the problem or limitation you are having in your project
I'm so used to just hover a field with the mouse cursor and increase/decrease its value with the mouse scroll in other software, I feel like valuable time is lost by having to click on the right spot to increase/decrease a variable, or having to drag, or worse, having to type, while I could just hover the field and scroll to increase/decrease.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
This is a quality of life improvement that will make using the editor a smoother and more pleasant experience.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
You hover the mouse cursor over a field, and use the mouse scroll button up to increase a variable/chose an item up in a list, or scroll down to decrease said variable/go down in the item list; you don't need to click on said field in order for the scrolling to works, you just need to hover the item. This is such a common feature in Windows and Mac softwares, I'm actually appaled that this doesn't exists in the Godot editor. This feature could probably be optional — although it should probably be enabled by default.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It will be used often and this is core.

### Is there a reason why this should be core and not an add-on in the asset library?
This is core.

**Comment by KoBeWi** [comment] 2021-03-16 00:19
Duplicate of #2099

**Closed by KoBeWi** 2021-03-16 00:19 UTC
