### ISSUE TITLE
Add a line ending (CRLF vs LF) setting

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot-proposals#897] opened 2020-05-26 07:14 UTC
**Describe the project you are working on:**
N/A (this is a generic issue)
**Describe the problem or limitation you are having in your project:**
Copying files from Windows to Linux machine causes spurious ^M (line feed) characters.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Line ending setting would make it possible for Windows Godot not to add line feed characters, making projects truly cross-platform.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
A line ending setting similar to the one most IDEs have (PyCharm, Sublime Text 3) and/or a CRLF to LF switch button.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Nope.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Not possible to do outside of core (has to be done in script editor) and not necessary for GDScript-exposed parts of script editor.

Related: https://github.com/godotengine/godot/issues/27057

**Comment by Calinou** [comment] 2020-05-26 07:20
Wouldn't it be better to configure your Git client to always commit files with LF line endings?

```text
git config --global core.autocrlf true
```

See [Customizing Git configuration](https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration) for more information.

**Comment by Zireael07** [comment] 2020-05-26 07:25
As I noted in the original issue, dos2unix will not recognize many files as text files, and therefore will do nothing. (IIRC it completely ignored tscn, escn, res and tres, and I'm not sure if it got .gd, either)

**Comment by aaronfranke** [comment] 2020-05-26 15:52
I don't think there should be a setting, it should just always use LF line endings. The vast majority of tools on Windows support LF just fine, even Notepad supports LF.

There are many ways to enforce this for your project using external tools. Git has the `core.autocrlf` setting, there is the `.gitattributes` file, and you could also use [this formatting script](https://github.com/godotengine/godot-demo-projects/blob/master/format.sh). The first thing it does is use `recode` to try to convert files to UTF-8, so `dos2unix` will recognize those files as text files. `dos2unix` works perfectly fine with `tscn` etc, I just tested it on a `tscn` file.

**Comment by Zireael07** [comment] 2020-05-26 16:48
Thanks for the tip re: the formatting script.

Yes, always using LF would probably be an even simpler solution to the problem.

**Comment by aaronfranke** [comment] 2020-08-05 17:48
Closing and archiving, as the solution is "it's better to always use LF and Godot currently does this".

**Closed by aaronfranke** 2020-08-05 17:48 UTC
Labels: topic:editor

**Comment by Zireael07** [comment] 2020-08-05 18:09
Why archive? Windows, by default, uses CRLF and Godot does not currently "do this [referring to always using LF], as evidenced by the fact my files were full of carriage returns.
Either give us the switch or auto-convert.

**Comment by aaronfranke** [comment] 2020-08-05 18:57
@Zireael07 Can you provide the steps to reproduce this? I just created an empty project with Godot 3.2.3rc3 on Windows, then created a GDScript file, and it was filled with LF, no carriage returns anywhere.

**Comment by Zireael07** [comment] 2020-08-05 19:04
It was several months ago, but I believe I manually copied a Godot project from Windows 7 to the Linux laptop. It was likely created in Godot 3.1. or even earlier. Or maybe I pulled from a Git repo that was not configured as autocrlf true - as I said, it was quite a long time ago.

**Comment by marechal-p** [comment] 2020-08-10 22:26
> @Zireael07 Can you provide the steps to reproduce this? I just created an empty project with Godot 3.2.3rc3 on Windows, then created a GDScript file, and it was filled with LF, no carriage returns anywhere.

This is actually an issue when versioning Godot files. I just spent the past 3 days collaborating on a small mini game with 3 other people, and I must say that the git experience was hectic thanks to Godot not using CRLF.

Git for Windows has a `core.autocrlf` indeed, which should convert LF from the upstream repo to CRLF locally, and then back the other way once you push. This is because applications on Windows are expected to use CRLF when writing text-like files.

The biggest pain now of having Godot use LF on Windows is that the git client will mark all the files with LF returns as different when doing `git status`. When doing `git diff` you get a bunch of warnings telling you that LF will be converted to CRLF followed by your actual changes. The confusing part is that even though you might not edit a file directly, Godot still overwrites some of them automatically, replacing the original CRLF by LF, which is counter productive because it makes git trip and it will convert it back anyway.

I think that it should be an option at the very least, and bonus point to make it CRLF by default on Windows.

**Comment by marechal-p** [comment] 2020-08-10 22:31
> `git config --global core.autocrlf input`

Ok just saw this. Not sure what to think about it. On one hand I feel it would be nice for Godot to use the correct platform line ending, but on the other hand I understand you guys prefer giving users the responsibility of handling the issue. Meh.

**Comment by aaronfranke** [comment] 2020-08-10 22:32
CRLF is only expected on Windows for legacy applications. Modern applications should use LF everywhere.

With Godot, you should always have `core.autocrlf` set to `input`. This converts CRLF to LF when committing, and keeps LF when checking out local files. This basically allows Git to remove CR when it was inserted by mistake, and with this setting Git will never "trip" regardless of what files you commit.

**Comment by Zireael07** [comment] 2020-08-11 08:43
@marechal-p: I had the opposite problem, git diff tripping on Linux because of the CRLF.

As I said, I don't remember if I used git, maybe I copied files manually. And dos2unix ran on the whole folder completely ignored tscn and escn - otherwise I wouldn't have had the problem that led to creating this issue.

**Comment by marechal-p** [comment] 2020-08-11 13:29
I just opened a PR to mention this in the docs: https://github.com/godotengine/godot-docs/pull/3891

**Comment by Avantir-Chaosfire** [comment] 2020-09-19 20:06
I'm also affected by this, but not because of git (autocrlf does the trick). Rather, I'm using C# with Visual Studio, which always uses CRLF. And Godot always uses LF. And I often need to have files open in different editors because of the way debugging and error reporting works. So while all the files use CRLF, Godot keeps overwriting them with LF and causing Visual Studio to complain about inconsistent line endings. There's no reason not to have an option for this, you're just taking power away from the user. By all means, try and set up the default value such that most users won't have to change it. But some people always will.

**Comment by Avantir-Chaosfire** [comment] 2020-09-19 20:06
I'm also affected by this, but not because of git (autocrlf does the trick). Rather, I'm using C# with Visual Studio, which always uses CRLF. And Godot always uses LF. And I often need to have files open in different editors because of the way debugging and error reporting works. So while all the files use CRLF, Godot keeps overwriting them with LF and causing Visual Studio to complain about inconsistent line endings. There's no reason not to have an option for this, you're just taking power away from the user. By all means, try and set up the default value such that most users won't have to change it. But some people always will.

**Comment by Avantir-Chaosfire** [comment] 2020-09-19 20:06
I'm also affected by this, but not because of git (autocrlf does the trick). Rather, I'm using C# with Visual Studio, which always uses CRLF. And Godot always uses LF. And I often need to have files open in different editors because of the way debugging and error reporting works. So while all the files use CRLF, Godot keeps overwriting them with LF and causing Visual Studio to complain about inconsistent line endings. There's no reason not to have an option for this, you're just taking power away from the user. By all means, try and set up the default value such that most users won't have to change it. But some people always will.

**Comment by Avantir-Chaosfire** [comment] 2020-09-19 20:06
I'm also affected by this, but not because of git (autocrlf does the trick). Rather, I'm using C# with Visual Studio, which always uses CRLF. And Godot always uses LF. And I often need to have files open in different editors because of the way debugging and error reporting works. So while all the files use CRLF, Godot keeps overwriting them with LF and causing Visual Studio to complain about inconsistent line endings. There's no reason not to have an option for this, you're just taking power away from the user. By all means, try and set up the default value such that most users won't have to change it. But some people always will.

**Comment by Avantir-Chaosfire** [comment] 2020-09-19 20:06
I'm also affected by this, but not because of git (autocrlf does the trick). Rather, I'm using C# with Visual Studio, which always uses CRLF. And Godot always uses LF. And I often need to have files open in different editors because of the way debugging and error reporting works. So while all the files use CRLF, Godot keeps overwriting them with LF and causing Visual Studio to complain about inconsistent line endings. There's no reason not to have an option for this, you're just taking power away from the user. By all means, try and set up the default value such that most users won't have to change it. But some people always will.

**Comment by Avantir-Chaosfire** [comment] 2020-09-19 20:06
I'm also affected by this, but not because of git (autocrlf does the trick). Rather, I'm using C# with Visual Studio, which always uses CRLF. And Godot always uses LF. And I often need to have files open in different editors because of the way debugging and error reporting works. So while all the files use CRLF, Godot keeps overwriting them with LF and causing Visual Studio to complain about inconsistent line endings. There's no reason not to have an option for this, you're just taking power away from the user. By all means, try and set up the default value such that most users won't have to change it. But some people always will.

**Comment by Avantir-Chaosfire** [comment] 2020-09-19 20:06
I'm also affected by this, but not because of git (autocrlf does the trick). Rather, I'm using C# with Visual Studio, which always uses CRLF. And Godot always uses LF. And I often need to have files open in different editors because of the way debugging and error reporting works. So while all the files use CRLF, Godot keeps overwriting them with LF and causing Visual Studio to complain about inconsistent line endings. There's no reason not to have an option for this, you're just taking power away from the user. By all means, try and set up the default value such that most users won't have to change it. But some people always will.

**Comment by Avantir-Chaosfire** [comment] 2020-09-19 20:06
I'm also affected by this, but not because of git (autocrlf does the trick). Rather, I'm using C# with Visual Studio, which always uses CRLF. And Godot always uses LF. And I often need to have files open in different editors because of the way debugging and error reporting works. So while all the files use CRLF, Godot keeps overwriting them with LF and causing Visual Studio to complain about inconsistent line endings. There's no reason not to have an option for this, you're just taking power away from the user. By all means, try and set up the default value such that most users won't have to change it. But some people always will.

**Comment by Avantir-Chaosfire** [comment] 2020-09-19 20:06
I'm also affected by this, but not because of git (autocrlf does the trick). Rather, I'm using C# with Visual Studio, which always uses CRLF. And Godot always uses LF. And I often need to have files open in different editors because of the way debugging and error reporting works. So while all the files use CRLF, Godot keeps overwriting them with LF and causing Visual Studio to complain about inconsistent line endings. There's no reason not to have an option for this, you're just taking power away from the user. By all means, try and set up the default value such that most users won't have to change it. But some people always will.

**Comment by Avantir-Chaosfire** [comment] 2020-09-19 20:06
I'm also affected by this, but not because of git (autocrlf does the trick). Rather, I'm using C# with Visual Studio, which always uses CRLF. And Godot always uses LF. And I often need to have files open in different editors because of the way debugging and error reporting works. So while all the files use CRLF, Godot keeps overwriting them with LF and causing Visual Studio to complain about inconsistent line endings. There's no reason not to have an option for this, you're just taking power away from the user. By all means, try and set up the default value such that most users won't have to change it. But some people always will.

**Comment by Avantir-Chaosfire** [comment] 2020-09-19 20:06
I'm also affected by this, but not because of git (autocrlf does the trick). Rather, I'm using C# with Visual Studio, which always uses CRLF. And Godot always uses LF. And I often need to have files open in different editors because of the way debugging and error reporting works. So while all the files use CRLF, Godot keeps overwriting them with LF and causing Visual Studio to complain about inconsistent line endings. There's no reason not to have an option for this, you're just taking power away from the user. By all means, try and set up the default value such that most users won't have to change it. But some people always will.

**Comment by aaronfranke** [comment] 2020-09-19 20:16
@Avantir-Chaosfire You can configure Visual Studio to use LF as stated in this documentation: https://docs.microsoft.com/en-us/visualstudio/ide/encodings-and-line-breaks?view=vs-2019

**Comment by Avantir-Chaosfire** [comment] 2020-09-23 16:08
@aaronfranke You can configure that on file by file basis, but not for Visual Studio as a whole.

**Comment by lostminds** [comment] 2022-11-29 09:08
I just encountered this problem in Godot 4.0.beta6 and would sure like Godot either to always use the same line endings regardless of plattform (apparently it still doesn't) or allow the user to specify what to use for a project. In my case I use a mac as my main development computer and use a github repository for the code. 

If I download the project to my windows machine and open the project in Godot there it rewrites and changes the line endings on all .import and .tres files in the project, so git shows they're all modified with new line endings but no changes in content. So apparently the line endings are still different at least between mac and windows, and also for some reason Godot overwrites all these files as a part of loading the project even if you don't modify anything?

**Comment by YuriSizov** [comment] 2022-11-29 10:05
@lostminds Git has a setting to convert line endings when you checkout or pull to match the local system, and to convert them back when you push. This is pretty much a must-have setting when you work across multiple operating systems, and it should solve your problems.

**Comment by Zireael07** [comment] 2022-11-29 13:40
@YuriSizov Not everyone uses Git, though! At the time of opening this issue, the project I was working on was a throwaway thing, so no Git either...

**Comment by YuriSizov** [comment] 2022-11-29 13:45
@Zireael07 Yeah, that's fair, I was just addressing the case from the comment where Git is used.

**Comment by aaronfranke** [comment] 2022-11-29 15:56
@lostminds I can't reproduce this issue, any operations I perform using Godot on Windows result in the files staying LF.

**Comment by lostminds** [comment] 2022-11-29 16:30
@aaronfranke  I just tried it again and this time it didn't change any of the .import files (may have been because last time was the first time I ran 4.0.beta6 on windows, so it re-imported all assets). But still it changed all shader .tres files, the Theme.tres file and the .godot project file from LF to CRLF line endings according to my github client. 

While I didn't modify or work with any of these files I did export the project (for windows), but in my mind that shouldn't modify any of these files.

**Comment by aaronfranke** [comment] 2022-11-29 17:05
What do you mean by "it changed"? Just "open the project in Godot"? Godot does not take it upon itself to go into all your files and modify them. Unless it's part of an open scene in the editor, Godot won't change the files on disk. If you open and close the Godot editor without opening any scenes, it won't change anything in your project. So, please describe the specific actions you are doing.

My suspicion is that you have Git configured incorrectly (run `git config --global core.autocrlf input` to fix).

**Comment by lostminds** [comment] 2022-11-30 09:11
> What do you mean by "it changed"? When you just "open the project in Godot"?

Ok, to be more specific: If I just open the project in Godot, this also loaded two scenes that were open last time I opened the project. This as you suspected does not modify any files, except for the project .godot file which gets the line endings changed as soon as the project is opened.

If I then immediately run the game from the editor without doing anything else the rest of the files mentioned above get changed. In other words the visual shader .tres files (8-9 of them) and the UITheme .tres file get modified changing the line endings from LF to CRLF.

I understand that there is a git setting like you mention to compensate for this issue by having git convert the line endings like you and others have mentioned. However, that's just a way to work around with the issue, and I don't see how that could be the cause of the files being changed by godot when running the project? While I guess technically possible I think it seems unlikely that the issue is the git client incorrectly reporting the change in line endings.

**Comment by Zireael07** [comment] 2022-11-30 11:22
@lostminds This is a sad consequence of two issues: one, that Godot opens and resaves the project .godot file when it opens - this once caused me to not be able to open projects, when I had a sneaky drive failure that first manifested as this problem; and two, save on run, which is generally a good thing, but in this case it seems to change the line endings.

Even more reason to have a line ending setting

**Comment by hawkerm** [comment] 2024-09-07 23:44
Working with Godot and C# with Visual Studio 2022 on Windows 10, I'm constantly getting this dialog when opening files in VS, it's a pain:

![image](https://github.com/user-attachments/assets/d5a49656-915d-4c96-8a15-424820de8fad)

Generally, most applications use the environment line ending for the system they're on, for Windows, that'd be CRLF. So, it'd be nice to see at least a setting/option for this rather than having to reconfigure a bunch of my other tools and configuration that I use for other projects/environments fine on Windows elsewhere already today.

**Comment by aaronfranke** [comment] 2024-09-08 00:27
@hawkerm I recommend configuring Visual Studio to use LF instead. This way your files will have consistent line endings regardless of operating system. Plus, if Git strips the carriage returns, or if you copy a file from Mac/Linux, you will have to deal with LF on Windows anyway.

**Comment by Manenderrr** [comment] 2024-12-20 12:09
Forcing the user to use a specific line ending without possibility of customisation does not sound great

**Comment by jesh-dev** [comment] 2025-07-24 20:01
so we should probably write the command as git config lf ?

**Comment by aaronfranke** [comment] 2025-07-25 14:30
@jesh-dev Run this command `git config --global core.autocrlf input` and add this to `.gitattributes`:

```gitattributes
# Normalize EOL for all files that Git considers text files.
* text=auto eol=lf
```

Godot will [create this file automatically](https://github.com/godotengine/godot/blob/967e2d499acd7d03a3e69002d373880e43fe0e45/editor/version_control/editor_vcs_interface.cpp#L376) when creating a project if the version control metadata dropdown is set to "Git" (default), fixing the problem automatically for most users.

**Comment by jesh-dev** [comment] 2025-07-30 22:41
Thanks
________________________________

**Comment by Klonan** [comment] 2026-02-26 13:25
Every other project/repo we pull and use, we use `autocrlf true`, vandalising the git setting just for Godot projects isn't a good solution.

Why must Godot cause this unique pain for our team, when all other software respects the environment LF/CRLF?

**Comment by aaronfranke** [comment] 2026-02-26 16:36
Recently I have been using Visual Studio 2022 on Windows. Past versions have written CRLF into files, but this version correctly respects line endings already present in the files, so LF files are kept as LF, making it not a problem anymore with this IDE.

**Comment by Mloren** [comment] 2026-03-06 01:22
I'm experiencing the issue harkerm described in Visual Studio 2022 where it inserts CR LF into the file which was created with just LF, leading to this popup warning:

<img width="632" height="396" alt="Image" src="https://github.com/user-attachments/assets/8a11dc1f-8e9f-4b28-a1b3-087f1eaa6beb" />

I can't change VS to use LF because I use it for other projects that expect CR LF and it doesn't have a per-project setting. Contrary to what others have said, plenty of Windows software still uses CR LF. Godot should provide a setting for specifying the line endings.
