### ISSUE TITLE
Open Editor Settings from project Manager

### ISSUE THREAD

**Issue by antonWetzel** [godotengine/godot-proposals#5443] opened 2022-09-17 15:50 UTC
### Describe the project you are working on

Any godot Project

### Describe the problem or limitation you are having in your project

Most editor settings only effect an open project but it is counterintuitive for some settings to be only avaible from an open project.
It took me a long time to find the setting for default new project location because it is only avaible after creating a project.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make `Editor -> Editor Settings, Command Palette, ...` available from the Project Manager.
- exclude `Editor Layout`, `Screenshot`, `Fullscreen`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/59712243/190865153-8881ccd8-c014-4a2c-8c59-bb2534aac280.png)

One of the 2 locations should make sense. 
Text in red to mark the difference.
Open data folder should not be in an option in `Settings` but I think the name is better as `Editor` in this context.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not possible

### Is there a reason why this should be core and not an add-on in the asset library?

Not possible

**Comment by KoBeWi** [comment] 2022-09-17 17:21
Duplicate of #1602

**Closed by KoBeWi** 2022-09-17 17:21 UTC
