### ISSUE TITLE
Allow clicking on script paths printed to the Output log to open the script in the editor

### ISSUE THREAD

**Issue by VP-GAMES** [godotengine/godot-proposals#3880] opened 2022-01-27 14:30 UTC
### Describe the project you are working on

A 2D/3D game

### Describe the problem or limitation you are having in your project

Godot Editor print errors and warnings to Output/Console. It would be convenient to click the message and go to the code(file, script, line
![Screenshot from 2022-01-27 14-31-46](https://user-images.githubusercontent.com/74808066/151377579-83189d26-dc9a-4e1b-8150-84852b5027d6.png)
)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Simpler to fix bugs 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Output is RichTextLabel. Use Regex-Pattern to find lines beginning with res:// in output. And make them linked/clickable to jump in to code file and line   

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used all the time

### Is there a reason why this should be core and not an add-on in the asset library?

It a general function in all IDE's

**Comment by kuhnchris** [comment] 2022-01-27 15:30
Shall this only apply to scripts in the editor, or shall this apply to any res:// path in the console log?

**Comment by Calinou** [comment] 2022-01-27 15:46
> Shall this only apply to scripts in the editor, or shall this apply to any res:// path in the console log?

This should probably apply to any `res://` path, with the default FileSystem dock action being applied when you double-click the file.

**Comment by kuhnchris** [comment] 2022-01-27 17:05
Hey there,

thanks for the input - seems that the res://script.gd:x:y is *not* support, at least not by the FileSystemDock's _select_file(path, favorite) function:
![image](https://user-images.githubusercontent.com/761911/151407283-c7c355da-f5cc-4960-a0e4-39082293965d.png)
Aside from that I managed to make this "plugin-esque" - the only thing that currently breaks me, is the fact that we cannot keep the color and "icons" in the Output, and a way to get a signal out of EditorLog to get a notification about a new log entry - both should be trivial IMHO.

For the scripts I can simply use the function "_goto_script_line" of the ScriptEditor - tho I fear that may break compatibility with users that may not use the built-in ScriptEditor (for example VSCode).

**Comment by Calinou** [comment] 2022-01-27 17:11
> thanks for the input - seems that the res://script.gd:x:y is not support, at least not by the FileSystemDock's _select_file(path, favorite) function:

This `:line:column` syntax isn't implemented anywhere in the editor yet.

**Comment by kuhnchris** [comment] 2022-01-27 17:17
Oh sorry, I thought you meant that the `:line:col` syntax "should be supported already" - my bad for reading it wrong.
![Peek 2022-01-27 18-15](https://user-images.githubusercontent.com/761911/151409607-e45c26d9-476a-4cf9-bd0e-8072d8f0aa86.gif)
This is basically how far I can come with the non-source-code modifying solution right now - unless I overlooked something drastically.
Technically it can work, but it destroys most of the formating (namely the red circle added by add_image(), and the coloring. There also seems to be no way for me to get those informations from the RichTextLabel in ANY possible way).

Let me know if you got any more ideas! Thanks

**Comment by kuhnchris** [comment] 2022-01-27 23:35
That's as far as I can go with the current limitations:
- Timer checks every second for new log entries
- If there is a new log entry, regex checks the lines for res:// and makes 'em clickable
- If there's no new line, keep as is

Caveats:
- Formating gets killed - this is sadly not bbcode but push_color() and pop(), no idea how this is internally handled.
- If there is a new addition to the log you are getting scrolled to the bottom of the Output log. - I cannot find any way to get the "current displayed line" from the RichTextLabel (maybe with some get_v_scroll() trickery?) - so I cannot feed the skip_to_line() function to restore the last position before the meta-tagification

Please note that this is just a PoC, not a implementation you should use for productive use.
To use it: simply enable the LogClickEnabler.gd as AutoLoad, adjust the script as needed. If you change the script, make sure to restart `godot`.

If anyone got any idea how we could improve this, or if we should include this directly in the RichTextLabel itself, please let me know, I just do not know if we should actually extend the RichTextLabel for the log as it would be kind of butt backwards to implement the logic in the generic UI class.

Also, I think the new Godot 4/master branch has a completly different log? Or is it just additional filter?
This one up here is for 3.x, so please beware :point_up: 
[gd3.x-proposal-3880.zip](https://github.com/godotengine/godot-proposals/files/7954548/gd3.x-proposal-3880.zip)
YMMV.

**Comment by Calinou** [comment] 2022-01-27 23:47
> Also, I think the new Godot 4/master branch has a completly different log? Or is it just additional filter?

The Output panel was rewritten from scratch in `master`: https://github.com/godotengine/godot/pull/41321

**Comment by kuhnchris** [comment] 2022-01-28 11:45
"Rewritten from scratch" may be a bit of an overstatement - it is still technically a RichTextLabel with additional functionality and storing it's messages in an internal structure additionally to the RichTextLabel. Basically, if I'd change the 3.x RichTextLabel I'd probabbly do something that would be very similar to the master/4 EditorLog in terms of storing and providing the messages. Makes me wonder if we should port that EditorLog back and start from there, as it'd make the implementation of this easier and unified compared to creating 2 separate solutions for 2 separate implementations...

What I dont really understand tho, is the 4.0 RichTextLabel.
I ported the script to 4.0, but despite being able to hook up the RichTextLabel (there is just an additional VBoxContainer that needs to be traveresed with `rte = n.get_child(1).get_child(0)`), the .text property of the RichTextLabel is always empty. I'm also sure that it isnt the "Filter Messages" line as that one is reachable by using get_child(1) and is a LineEdit... not sure if this is a new caveat of 4.0 but it seems to render my method inpractical for the current 4.0 solution.

Thanks,
Chris

**Comment by me2beats** [comment] 2022-06-11 08:06
see also https://github.com/godotengine/godot-proposals/issues/1628

**Comment by kuhnchris** [comment] 2022-06-11 11:35
> see also #1628

Oh, so you already made about the same progress I did, good to know.  At least it confirms that I didn't overlook anything critically obvious. :-) Thanks for letting me know

**Comment by Calinou** [comment] 2022-06-11 14:27
Duplicate of https://github.com/godotengine/godot-proposals/issues/1628.

**Closed by Calinou** 2022-06-11 14:27 UTC
Labels: topic:editor
