### ISSUE TITLE
Check network connection 

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot-proposals#4451] opened 2022-04-27 09:58 UTC
### Describe the project you are working on

2d and 3d

### Describe the problem or limitation you are having in your project

I can't check either the device is connected with network or not

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This feature can help to do any work related to internet 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

get_tree().checkdataconnection():

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes

### Is there a reason why this should be core and not an add-on in the asset library?

Because most of the developer needs this feature. And there is too many questions on online on this topic. But there has no easy solution.

**Comment by Xrayez** [comment] 2022-04-27 11:04
Duplicate of #3718.

**Comment by groud** [comment] 2022-04-27 13:48
> Duplicate of https://github.com/godotengine/godot-proposals/issues/3718.

Closing as a duplicate.

**Closed by groud** 2022-04-27 13:48 UTC

**Comment by hani09876** [comment] 2022-04-28 11:33
> > Duplicate of https://github.com/godotengine/godot-proposals/issues/3718.
> 
> Closing as a duplicate.

You closed it as a duplicate. But the main proposal haven't solved yet. Will you solve this problem?

**Comment by hani09876** [comment] 2022-04-28 11:35
> Duplicate of #3718.

 the main proposal haven't solved yet. Will you solve this problem?

**Comment by groud** [comment] 2022-04-28 11:41
> You closed it as a duplicate. But the main proposal haven't solved yet. Will you solve this problem?

No, we just close duplicate to have avoid having the same proposal twice, that's all. But you can show your support for the idea there if you want to (with a thumbs up I would say).
