### ISSUE TITLE
Richer instance method

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot-proposals#1865] opened 2020-11-20 14:39 UTC
**Describe the project you are working on:**
3D shooter

**Describe the problem or limitation you are having in your project:**
I found myself repeating the following code in order to instance an object to a position inside the scene

```
var bullet : RigidBody = Bullet.instance() 
bullet.transform = self.global_transform
get_node("/root/World").add_child(bullet)
```

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
To have a richer instance method that accepts more parameters

```
var world = get_node("/root/World")
var bullet : RigidBody = Bullet.instance(world, self.transform)
```

Maybe we can add another parameters that make sense too

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
See above

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
The idea is to reduce duplicated code

**Is there a reason why this should be core and not an add-on in the asset library?:**
this work only on code

**Comment by Calinou** [comment] 2020-11-20 14:46
Duplicate of https://github.com/godotengine/godot-proposals/issues/1513.

**Closed by Calinou** 2020-11-20 14:46 UTC

**Comment by jcostello** [comment] 2020-11-20 14:56
@Calinou sorry, I didn't found it earlier. My bad
