### ISSUE TITLE
Add a debugger expression evaluator/immediate window console

### ISSUE THREAD

**Issue by sockeye-d** [godotengine/godot-proposals#10714] opened 2024-09-10 19:30 UTC
### Describe the project you are working on

I'm currently converting all my untyped dictionaries to typed ones

### Describe the problem or limitation you are having in your project

I have a call to a function here:
```
var features := convert_tags_to_names(new_font.get_supported_feature_list())
```
and I have this error:
```
Invalid type in function 'convert_tags_to_names' in base 'Node (editor_theme_manager.gd)'. The dictionary of argument 1 (Dictionary) does not have the same element type as the expected typed dictionary argument.
```
It would be nice to inspect the contents of `new_font.get_supported_feature_list()`, so I can know what the function returns. I can't hover over it, because that's only supported for properties.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an immediate window to the debugger like the one in Visual Studio.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I have this C# code snippet open in Visual Studio 2022:
```c#
using System.Diagnostics;
int[] myArray = [1, 2, 4, 8, 16, 32];
Debugger.Break();
```
When the debugger breaks, I can open up the immediate window and run code to inspect the contents of objects. I can run `string.Join(", ", myArray)`, and it will print
```c#
"1, 2, 4, 8, 16, 32"
```

If I had this in Godot, I could run
```
new_font.get_supported_feature_list()
```
in the immediate window and it would print out the result of the function call.
The window would have access to all the variables and classes in scope where it broke. It would work on normal breakpoints too.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can't execute code when the execution stops, I think

### Is there a reason why this should be core and not an add-on in the asset library?

I'm not sure an add-on has the capability to access the scope of the currently executed line

**Comment by passivestar** [comment] 2024-09-10 20:36
Duplicate of https://github.com/godotengine/godot-proposals/issues/4473?

**Comment by sockeye-d** [comment] 2024-09-10 21:50
> Duplicate of #4473?

It is, I'll close the issue

**Closed** 2024-09-10 21:50 UTC
