### ISSUE TITLE
Add support for multiple accelerometer and gyroscope inputs

### ISSUE THREAD

**Issue by Blockyheadman** [godotengine/godot-proposals#4824] opened 2022-07-06 13:22 UTC
### Describe the project you are working on

I was working on a project where I wanted an android mobile device with a headset insert where I can aim around the gamepad connected to the device. 

_Please note that it's **not** a standalone or wired VR headset. I use the **android mobile device**_ 

### Describe the problem or limitation you are having in your project

I am only able to get the mobile device's input and not the gamepad

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would allow for more people to have a controller rotation on one system for local multiplayer or for something like my case.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Input.get_accelerometer(device: int)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

From what I have checked, there isn't any way to get another device's accelerometer with other code. I'm decently new but I have learned some coding from godot.

### Is there a reason why this should be core and not an add-on in the asset library?

As there more than likely isn't anyway to get the input, it should be added as a core element.

**Comment by Calinou** [comment] 2022-07-06 14:40
Duplicate of https://github.com/godotengine/godot-proposals/issues/2829.

**Closed by Calinou** 2022-07-06 14:40 UTC
Labels: topic:input
