### ISSUE TITLE
Force static typing option in project settings

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1728] opened 2020-10-26 07:40 UTC
**Describe the project you are working on:**
3D Rougelike

**Describe the problem or limitation you are having in your project:**
I tend to miss using static typing due to gdscript's odd static typing

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I just want a flag in project settings that forces static typing

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I would guess it would throw a error if you didn't use static typing when the flag was set.
something like..
- `variable must be statically typed with :`
- 'variable must be assigned with :='
- 'parameters must be statically typed with :'
- 'function must return a type with ->'

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
it can be worked around but I thought it would be a nice feature 

**Is there a reason why this should be core and not an add-on in the asset library?:**
it would be part of the gdscript langauge

**Comment by Calinou** [comment] 2020-10-26 10:09
Duplicate of https://github.com/godotengine/godot-proposals/issues/173.

**Closed by Calinou** 2020-10-26 10:09 UTC
