### ISSUE TITLE
Add user level plug-ins

### ISSUE THREAD

**Issue by Wavesonics** [godotengine/godot-proposals#1958] opened 2020-12-09 02:06 UTC
### Describe the project you are working on
several different projects

### Describe the problem or limitation you are having in your project
I must re-install certain plugins for each project that i'm working on. And more so, those plugins aren't necessarily applicable to all users of the project, so I have to prevent them from being checked in to the repo.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Plugins such as Wakatime or TODO Manager are more so user environment than project related. I want them in every project that I open.

The solution I'm thinking of would be to have a plugins folder in the user's godot directory.

Any plugin in that directory would be loaded for every project.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
On windows we could add a folder in the user's AppData directory:
`C:\Users\FooBar\AppData\Roaming\Godot\plugins`

Then you'd install a plugin as such:
`C:\Users\FooBar\AppData\Roaming\Godot\plugins\WakkaTime\plugin.gd`

We'd need a little bit of new UI.
1) When installing a plugin from the Asset Library, there would probably need to be an option to install to user instead of project.
2) Editor Settings would need a way to manage user level plugins. Show all of them, Enable/disable, delete.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not that I can think of.

### Is there a reason why this should be core and not an add-on in the asset library?
I think it would have to be core in order to work.

**Comment by hilfazer** [comment] 2020-12-09 10:06
I was about to make the same suggestion. I have the same issue specifically with a TODO addon, which isn't related to how my projects work but rather how i am working on them.

**Comment by Calinou** [comment] 2020-12-09 13:06
Duplicate of https://github.com/godotengine/godot-proposals/issues/831.

**Closed by Calinou** 2020-12-09 13:06 UTC
