### ISSUE TITLE
Arm Binaries 

### ISSUE THREAD

**Issue by Burnsedia** [godotengine/godot-proposals#1452] opened 2020-09-02 19:00 UTC
**Describe the project you are working on:**
I am making aarch64 arm binaries for the Pinebrook Pro and the Raspberry Pi. 
I feel that there is a need for official binaries for arm laptops and SBCs for both development and deployment 
**Describe the problem or limitation you are having in your project:**
The Binaries I have have been using on my PineBook Pro, it may be my Unfemalarity with the aarch 64. 
But if there were official arm build we could better target SBCs and ARM laptops. 

**Describe the feature/enhancement and how it helps to overcome the problem or limitation:**
Official arm64/aarch64 would allow more developers to support arm laptops in the future. 
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It would not affect the development of workflows with Godot developers. The Scons build system should not be affected. 
**Is there a reason why this should be core and not an add-on in the asset library?:**

**Comment by Calinou** [comment] 2020-09-02 19:52
Duplicate of #988.

**Closed by Calinou** 2020-09-02 19:52 UTC
