### ISSUE TITLE
Rename CollisionShape2D 'disabled' to 'enabled'

### ISSUE THREAD

**Issue by EthanDenny** [godotengine/godot-proposals#6251] opened 2023-02-08 20:27 UTC
### Describe the project you are working on

A platformer where the character needs to have different collision shapes at different times.

### Describe the problem or limitation you are having in your project

The CollisionShape2D has the attribute 'disabled', which is somewhat unclear.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rename the attribute to 'enabled', which would be true by default. This is clearer.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Give CollisionShape2D a new attribute called 'enabled', which has the opposite behaviour to 'disabled'. Deprecate 'disabled', but add something in the background that will allow old code to keep working.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No functionality will be changed - but it is far more confusing to type:

`$CollisionShape2D.disabled = false`

Compared to:

`$CollisionShape2D.enabled = true`

### Is there a reason why this should be core and not an add-on in the asset library?

It's a small syntax change

**Comment by Calinou** [comment] 2023-02-08 20:59
Duplicate of https://github.com/godotengine/godot-proposals/issues/1376 (this was rejected).

**Closed by Calinou** 2023-02-08 20:59 UTC
