### ISSUE TITLE
Highlight found help item

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-proposals#3609] opened 2021-11-28 19:44 UTC
### Describe the project you are working on

Just various projects that use GDScript and lots of different stuff.

### Describe the problem or limitation you are having in your project

When Ctrl+clicking something, I'm often lost on the opened help page. The found method/property isn't centered, it's usually at the top. But sometimes it can't be centered/at top, because it's the last item in the class. And sometimes you click some link and nothing happens
![bb8XuVh2yc](https://user-images.githubusercontent.com/2223172/143782905-f542bec6-bcf4-4ec1-b707-c11f1101d9f0.gif)
because both methods are past the scrolling limit, so there is nothing to scroll. I sometimes waste up to a minute looking for the item I clicked, because I'm presented with a wall of text with no indication of where I should look at.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

[My old idea was to just center the view on the item](https://github.com/godotengine/godot/issues/36861), but it doesn't always help. I think it would be better if the displayed item was highlighted briefly, like
![5qZpXxUA5a](https://user-images.githubusercontent.com/2223172/143783415-d999be31-444f-4874-bc01-0bfd3e457191.gif)
now it's immediately obvious what I should read.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When editor jumps to any help item (method/property/etc), highlight its name and description for a moment. Could be done with Tween.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Probably doable with EditorPlugin, but editor help isn't even exposed, so it's rather difficult.

### Is there a reason why this should be core and not an add-on in the asset library?

It would improve documentation usability.

**Comment by Xrayez** [comment] 2021-11-29 15:15
Duplicate of #2248.

**Closed** 2021-11-29 15:20 UTC
Labels: topic:editor, topic:docs
