### ISSUE TITLE
Add markers when files are made unique (ex. tilesets, sprites frames, etc.)

### ISSUE THREAD

**Issue by efigi** [godotengine/godot-proposals#1598] opened 2020-10-02 14:11 UTC
**Describe the project you are working on:**
A game with multiple inherited scenes

**Describe the problem or limitation you are having in your project:**
When I inherit a scene and make its sprite frames unique for example, there is no marker that indicates the change. It gets confusing when there are a large amount of inherited scenes as to which were made unique and which weren't. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I suggest a visible marker (maybe a colored dot) to show that the "make unique" hasn't been used and that it's still connected to the inherited scene.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

![image](https://user-images.githubusercontent.com/3532195/94932540-cc8c9600-04fb-11eb-8e75-5087acab5fd8.png)
a dot to show it's inherited

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I think so

**Is there a reason why this should be core and not an add-on in the asset library?:**
inherited scenes are used in a lot of games, and an indicator like this would benefit everyone

**Comment by Zireael07** [comment] 2020-10-02 14:13
Duplicate of #904 (did you even search for "unique"?)

**Comment by Calinou** [comment] 2020-10-02 14:16
Closing per @Zireael07's comment.

**Closed by Calinou** 2020-10-02 14:16 UTC
