### ISSUE TITLE
Keep GLES2 Renderer

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot-proposals#2573] opened 2021-04-09 00:37 UTC
### Describe the project you are working on
Retro game.

### Describe the problem or limitation you are having in your project
GLES2 will be removed, but GLES2 is perfect for some situations like legacy computers and retro consoles.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Would be great if GLES2 could be kept as some limited rendering engine focused on retro hardware and old computers.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Just keep GLES2 and update it as some "legacy/retro" rendering engine.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No, It's a core issue.

### Is there a reason why this should be core and not an add-on in the asset library?
No, It's a core issue.

**Comment by Calinou** [comment] 2021-04-09 00:46
Duplicate of https://github.com/godotengine/godot-proposals/issues/877 – please continue the discussion there.

**Closed by Calinou** 2021-04-09 00:46 UTC
