### ISSUE TITLE
Make the ' Get Index ' Visual script box have a ' box ' where one can type ' Index number ' . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#1510] opened 2020-09-14 06:01 UTC
**Describe the project you are working on:**
A Tomb Raider game . .

**Describe the problem or limitation you are having in your project:**
The current Get Index box, doesn't have a little ' box ', where one can directly type in ' Index ' number, like some other boxes . . Could we MAYBE get that, so it's even nicer, to work with . .
<img width="457" alt="Skærmbillede (249)" src="https://user-images.githubusercontent.com/61069740/93048858-1fdb9900-f660-11ea-950b-edba01c5695c.png">

maybe, Set Index as well, not sure . . Also, not sure I reported it, but the ' Set Index ' box doesn't work, it ' corrupts ' the arrays, when I use them, instead of writing the new variable value, it puts an [ . . . ] value in, instead . . If I Set Index a string, in say an array, from ' String 01 ', to ' New Text in Array ', and then PRINT the array, it doesn't work, it PRINTS [ . . . ], not ' New Text in Array ', in the debugger . . Thx . . . <3

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
See pic, above . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Like above, many other of boxes, have an ' field ', or ' box ', one can type stuff in, faster . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**
Never know how to answer this question, probably standard, or so . . .

Thx . . <3

**Comment by Calinou** [comment] 2020-09-20 12:36
Duplicate of https://github.com/godotengine/godot-proposals/issues/219.

**Closed by Calinou** 2020-09-20 12:36 UTC
Labels: topic:visualscript
