### ISSUE TITLE
Bone/Rig edit tool

### ISSUE THREAD

**Issue by WINDGameDev** [godotengine/godot-proposals#2199] opened 2021-01-28 23:48 UTC
I'm not currently working in a 3D project, but part of the reason why is because of this issue.

Godot doesn't currently have a proper way of messing with mesh rigs. There is no tool for editing bones like in Blender, for example. This really limits my workflow and, i assume, many others'.

It would be nice to have a rig editor like the one in Blender, for example.

It wold work similar to Blender's. You would be able to select the bones and rotate them.

![image](https://user-images.githubusercontent.com/78182510/106212474-7974d800-61a9-11eb-8819-7d13cf757767.png)

![image](https://user-images.githubusercontent.com/78182510/106212490-842f6d00-61a9-11eb-93eb-1d8db4edff0b.png)

I believe it will make Godot a better 3D engine. I have not found any way to work around this problem with code.

The reason why this should be core is because it's not only always present in the mainstream engines, but it makes the engine better to work with. I believe that a 3D engine or workspace is not complete without a rig editor.

**Comment by SIsilicon** [comment] 2021-01-29 00:42
I'm no moderator, but you might wanna put back the bolded in text that comes with the proposal template. I can tell you filled them in, but others might not be so observant.

**Comment by Calinou** [comment] 2021-01-29 00:43
Duplicate of https://github.com/godotengine/godot-proposals/issues/584.

**Closed by Calinou** 2021-01-29 00:43 UTC

**Comment by GeorgeS2019** [comment] 2021-04-22 12:25
@SIsilicon    check [this ](https://github.com/godotengine/godot-proposals/issues/1767#issuecomment-824786450)and could be the first step towards being part of 3D character workflow from Blender to Godot.
