### ISSUE TITLE
Add the ability to export button in inspector

### ISSUE THREAD

**Issue by Utkrisht-1997** [godotengine/godot-proposals#6140] opened 2023-01-21 17:23 UTC
### Describe the project you are working on

I am currently trying to develop a game where level will be mazes.

### Describe the problem or limitation you are having in your project

I have written a method that generates a maze using tileset and displays it in tilemap. Now I wanted to export a button to inspector which on click will execute that method and display maze on tilemap. So that I can regenerate different mazes and select the one which I think fits best

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When the button can be added to inspector menu then I can regenerate mazes easily

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Something like

```
@export var customButton: button    //button or any type that can add a button in inspector just like 
                                                             //Add Metadata button currently is by default
customButton.onClick: 
     method():
          //it will be executed on click
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes currently there is a workaround

```
@tool

@export var myButton: bool: 
      set(value):
           if(Engine.is_editor_hint()):   //so that it only executes in editor
                myButton = false           //keeping it false so that it doesn't get checked not required but I prefer it
                // This will be executed every time it is clicked

```
With this job gets done but 
- It is not a button and hence cannot rename it or add icon to it (Add metadata has + icon)
- It requires tool just for this specific purpose

### Is there a reason why this should be core and not an add-on in the asset library?

Yes
Add on cannot add button by itself unless godot core allows it. So in my opinion this is a core feature

**Comment by YuriSizov** [comment] 2023-01-21 17:56
Duplicate of https://github.com/godotengine/godot-proposals/issues/2149.

**Closed by YuriSizov** 2023-01-21 17:56 UTC

**Comment by Valla-Chan** [comment] 2024-01-23 13:13
For anyone going through google results to solve this for themselves, this inspector plugin adds that capability. https://github.com/Valla-Chan/Godot-Valla-ExportHelper
