### ISSUE TITLE
Show current match index in Search-Find results

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#1563] opened 2020-09-24 18:52 UTC
**Describe the project you are working on:**
gdscript plugins

**Describe the problem or limitation you are having in your project:**
In `ScriptEditor` I often use `Search-Find` (`Ctrl+F`). 
And sometimes I miss seeing the number of the current result, instead I can see only number of all results) like `10 matches`

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Ability to show current match index could solve the problem.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
`1/10 matches`, `5/10 matches` and so on (instead of `10 matches`)
This will make it easier to navigate through the search results.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
no, it can't

**Is there a reason why this should be core and not an add-on in the asset library?:**
I think it's possible to make a plugin that calculates the current match index and adds it to the label with number of all results, but I don't think it will work well in all cases

**Comment by Calinou** [comment] 2020-09-24 19:01
Duplicate of https://github.com/godotengine/godot-proposals/issues/600.

**Closed by Calinou** 2020-09-24 19:01 UTC
