### ISSUE TITLE
Reformat the Root Node's name into snake_case before suggesting it as the filename when saving a new scene

### ISSUE THREAD

**Issue by Sosasees** [godotengine/godot-proposals#3816] opened 2022-01-17 18:05 UTC
### Describe the project you are working on

Any Godot Engine Game

### Describe the problem or limitation you are having in your project

When i was a complete beginner at using Godot, i used to save all my scenes with their filenames in PascalCase, since this convention was always suggested as official by the suggested filename being 1-to-1 the name of the root node (e.g. if the root node was named "MusicPlayer", the suggested filename was "MusicPlayer.tscn").

Now i know that the official convention is snake_case ("music_player.tscn"), but back then i didn't, especially as the styleguides in the official documentation suggested "Godot's built-in script editor uses a lot of these conventions by default. Let it help you."

I'm sure that new beginners still start out making this mistake because of this overlooked detail.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When saving a new scene, the suggested filename should first be automatically reformatted from PascalCase to snake_case before being suggested as the filename (e.g. if the root node is named "MusicPlayer", the suggested filename should be "music_player.tscn" and not "MusicPlayer.tscn").

this correctly implies that snake_case is the official convention for filenames in Godot, making beginners on the Godot version with this feature avoid my beginner's naming mistake from the beginning.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When saving a new scene, the suggested filename should first be automatically reformatted from PascalCase to snake_case before being suggested as the filename (e.g. if the root node is named "MusicPlayer", the suggested filename should be "music_player.tscn" and not "MusicPlayer.tscn").

making this algorithm can be a bit challenging because of edge-cases like when there's multiple numbers and/or capital letters nearby (e.g. "Node2D" and "Node3D" should be converted to "node_2d" and "node_3d" instead of "node_2_d" and "node_3_d"). However, when the built-in node names are translated correctly, that's good enough. Small errors that come from the node being named unlike any built-in node (e.g. "YeetOMat3000XE" becoming "yeet_o_mat_3000x_e" instead of "yeet_o_mat_3000_xe") are very understandable and can quickly be corrected manually (faster than converting the original PascalCase name to snake_case by hand).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It might be possible to implement this behaviour into the engine with your own plug-in,
but i'm not sure.

### Is there a reason why this should be core and not an add-on in the asset library?

the people who would need this feature the most are beginners, who would not think of looking for such a plug-in
as they don't realize they're even making a mistake when saving their scenes with a filename in PascalCase instead of snake_case.

**Comment by Calinou** [comment] 2022-01-17 18:33
Duplicate of https://github.com/godotengine/godot-proposals/issues/3553.

**Closed by Calinou** 2022-01-17 18:33 UTC
