### ISSUE TITLE
Group annotation with tab

### ISSUE THREAD

**Issue by shinspiegel** [godotengine/godot-proposals#7760] opened 2023-09-20 12:13 UTC
### Describe the project you are working on

Shoot'n Up

### Describe the problem or limitation you are having in your project

Most of my classes have a lot of `@export` and `@onready`, I think we could group then to make it easy to read.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The start of the files is overloaded with annotation, a good amount of `@export` and other `@onready`, and I'm not counting on the internal variables. 

We could reduce the amount of annotation by grouping them with a tab.

```gdscript
# All of this
@onready var node1 = $Node1
@onready var node2 = $Node2
@onready var node3 = $Node3
@onready var node4 = $Node4

# Would be the same as this
@onready
    var node1 = $Node1
    var node2 = $Node2
    var node3 = $Node3
    var node4 = $Node4
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I think this snippet is clear enough:

```gdscript
# All of this
@onready var node1 = $Node1
@onready var node2 = $Node2
@onready var node3 = $Node3
@onready var node4 = $Node4

# Would be the same as this
@onready
    var node1 = $Node1
    var node2 = $Node2
    var node3 = $Node3
    var node4 = $Node4
```

This also would work with mix and match of different annotations:

```gdscript
@onready
    var node1 = $Node1
    var node2 = $Node2
    var node3 = $Node3
    var node4 = $Node4

@export
    var some_value: int
    var some_other_value: float
    var another_type: int

@export_group("Internal Data", "internal_")
    var internal_one: int
    var internal_value: float
    var internal_max: int
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The current GDScrit is already providing the support. This is an enhancement to aiming for readability.

### Is there a reason why this should be core and not an add-on in the asset library?

This is deeply connected with the GDScript language. I don't think a plugin can achieve this.

**Comment by YuriSizov** [comment] 2023-09-20 12:32
Thanks for the proposal! This is a duplicate of https://github.com/godotengine/godot-proposals/issues/5323, so consolidating.

**Closed by YuriSizov** 2023-09-20 12:32 UTC
Labels: topic:gdscript
