### ISSUE TITLE
Add sorting order parameter to the Decal node

### ISSUE THREAD

**Issue by honix** [godotengine/godot-proposals#3437] opened 2021-10-16 14:45 UTC
### Describe the project you are working on

Testing Godot v4.0.dev.20211015.official [f113dc986]

### Describe the problem or limitation you are having in your project

Layered decals can produce unwanted switch of drawing order, when the view changes.

https://user-images.githubusercontent.com/11596541/137591509-eb3abf1d-5083-468d-80d7-d62f8688e3da.mp4

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The sorting order parameter can be introduced to allow users to set constant drawing order.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Decal node will have a **sorting order** parameter, placed inside Parameters tab (1), or in new tab Sorting Order after Cull Mask tab (2). 

Default value of **sorting order** parameter is 0 (int), and it means Godot will sort layered decals by distance (as it does now), if the value is negative or positive (for example -500, -5, -1, 1, 12, 42), the drawing order will draw decals according to this order, from lowest to highest. If layered decals have same number (for example 50 and 50) they will be sorted by distance as it was defaults (0 and 0).

![изображение](https://user-images.githubusercontent.com/11596541/137591616-a5272328-2535-4997-bd39-00ffe6f0f332.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think this can't be worked around with a few lines of script.

### Is there a reason why this should be core and not an add-on in the asset library?

Decal node is a core functionality.

**Comment by Calinou** [comment] 2021-10-16 14:48
Duplicate of https://github.com/godotengine/godot/issues/49639.

**Closed as completed by Calinou** 2021-10-16 14:48 UTC
Labels: archived, topic:rendering, topic:3d
