### ISSUE TITLE
Support expressions and constants in `export` ranges

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot-proposals#1147] opened 2020-06-30 21:32 UTC
godotengine/godot#6391

**Describe the project you are working on:**
This is something that all projects may use.

**Describe the problem or limitation you are having in your project:**
I want to have a export float for rotation. Ideally, it would look like this:
`export(float, 0.0, TAU) var default_rotation = 0.0`
However, since expressions or constants aren't supported, it looks like this:
`export(float, 0.0, 6.28318530717959) var default_rotation = 0.0`

The original issue also pointed out other examples

```py
export(float, 1.0/64, 64) # SCRIPT ERROR: GDScript::reload: Parse Error: Expected ',' or ')' in numeric range hint.
const a = 4
export(float, a, 5) # SCRIPT ERROR: GDScript::reload: Parse Error: Expected a range in numeric hint
```

Also noted by https://github.com/godotengine/godot/issues/6391#issuecomment-439703625: Enum values cannot be used in constants:
```py
enum MyEnum {Alpha, Bravo, Charlie}
const a = MyEnum.Alpha
```

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Rather than parsing a number constant, Godot should parse an expression as if it is a function call or variable declaration.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
As stated above:
```py
export(float, 0.0, PI)
const MY_CONSTANT = 1000
export(float, -MY_CONSTANT, MY_CONSTANT)
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This enhancement will be used often, and the only workaround is to hard-code constants (such as TAU above) which does not promote good programming standards.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is not applicable to the scope of this request.

**Comment by joeystandrew** [comment] 2021-03-04 04:44
I thought I was doing something wrong, glad to know it's a bug haha.

**Comment by Calinou** [comment] 2021-03-04 15:39
> I thought I was doing something wrong, glad to know it's a bug haha.

It's not a bug, but a feature proposal actually :slightly_smiling_face:

**Comment by Mickeon** [comment] 2024-06-23 20:05
This has been possible for quite a while. I think this proposal can be safely closed as implemented.

**Closed** 2024-06-23 20:21 UTC
Labels: topic:gdscript
