### ISSUE TITLE
Include double precision builds with official builds

### ISSUE THREAD

**Issue by nickpolet** [godotengine/godot-proposals#8843] opened 2024-01-09 12:49 UTC
### Describe the project you are working on

Working on a large open world game, where the player is regularly quite far from the centre of the scene. With a normal build, you obviously get rendering artefacts when far from the centre of the scene. This is solved with `precision=double` builds.

### Describe the problem or limitation you are having in your project

It can be quite a learning curve to figure out how to build godot from source, especially if users haven't got much experience in build/toolchains etc... This immediately creates a barrier to entry for larger scale worlds.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be great to include double precision builds officially to help other users who are looking to create games with large worlds. I see this as increasingly important as more and more people are using the engine. Recent upgrades to the 3D rendering engine have made large worlds quite attainable with godot. The last hurdle is having a reliable source of double precision builds.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Including double precision builds alongside the regular builds at https://godotengine.org/download/archive.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The only work around is by manually building the engine, which as stated above, is quite complicated for lots of users.

### Is there a reason why this should be core and not an add-on in the asset library?

Core build feature, I don't think an addon can solve this.

**Comment by AThousandShips** [comment] 2024-01-09 12:50
Duplicate of: https://github.com/godotengine/godot-proposals/issues/5610

**Closed by AThousandShips** 2024-01-09 12:50 UTC
