### ISSUE TITLE
Improve input of HDR/overbright colors in ColorPicker

### ISSUE THREAD

**Issue by vitorbalbio** [godotengine/godot-proposals#1595] opened 2020-10-02 12:26 UTC
**Describe the project you are working on:**
https://twitter.com/ZeroPointGame

**Describe the problem or limitation you are having in your project:**
Currently working with HDR colors is only possible with a "hack". You need to set it manually on the raw RGB values.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Better handlers for HDR Colors in the Color Picker.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
There's no much to think about it. We can jut add another slider to setup Intensity (that will be multiplied by the colors).
And allow us to set Value colors > 100 in HSV.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a core feature of the Editor.

**Comment by Calinou** [comment] 2020-10-02 12:28
I think you can already enter RGB values above 255 manually *without switching to RAW mode* by clicking on the number fields and entering values there.

**Comment by vitorbalbio** [comment] 2020-10-02 12:41
> I think you can already enter RGB values above 255 manually _without switching to RAW mode_ by clicking on the number fields and entering values there.
> 

This is just like enter RAW values manually. You need to set the color in the color pick and after that multiply the values by hand and set there.  Just think that i set this color (201,133,182) and i what to check what is the better intensity while using the Glow Post Process. So i need to multiply it to 2 and set 3 sliders, than by 3 , than by 4... It's atrocious as is. 

> I wouldn't add an intensity slider as this would further bloat the color picker, which already has 4 sliders for RGBA colors (on top of the other buttons and presets).
> 

This is exactly how Unity handles it and it work great. If you want to hide it by default we can just set another checkbox for "Use HDR" values.
![chrome_yhqpLpkmt1](https://user-images.githubusercontent.com/6172013/94923692-a4b51800-0492-11eb-9a78-b4f1cf363523.png)

Blender and UE4 follows the HSV with values higher than 100.

> Good point about entering HSV values above 100, still. Like for RGB, this should only be exposed to number input, not the slider (as we don't want people to _accidentally_ define overbright colors).

No problem it's the Blender/UE4 way and works nice too.

**Comment by QbieShay** [comment] 2022-06-26 15:03
VFX artist here: yes please

**Comment by paddy-exe** [comment] 2022-06-26 17:07
I actually use this a lot as well and would like to have a slider since manually adjusting all three values is a real pain.

**Comment by Calinou** [comment] 2022-06-26 17:19
Duplicate of https://github.com/godotengine/godot-proposals/issues/1031.

**Closed by Calinou** 2022-06-26 17:19 UTC
Labels: topic:editor, topic:gui
