### ISSUE TITLE
Custom folders / categories in project list

### ISSUE THREAD

**Issue by ReturnMinusOne** [godotengine/godot-proposals#1163] opened 2020-07-05 02:07 UTC
**Describe the project you are working on:**
Experimentation with many simple test games and pre-made demos.

**Describe the problem or limitation you are having in your project:**
My Project Manager window is full of projects of varying size, some made by myself, some by others, and across different versions of Godot which are not intercompatible; it seems that all versions of Godot will see the same project list, regardless of which projects can or can't be opened by a given engine version.

Sorting projects based on "Name", "Path" or "Last Modified" is useful, but not a universal solution.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The ability to create, rename and nest folders in the Project Manager would allow users to hide any projects (tests, demos, tutorials) they might not usually need to see, and organise projects according to their own arbitrary criteria like type of project, or engine version.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Folders are shown at the top of the list. A button on the right side labeled "New Project Folder" (or "New Project Category", to avoid confusion with literal project folders) can be clicked to add a folder.

It can be renamed with the already existing "Rename" button.

Projects (or other folders) can be dragged inside, one by one or as a group using the Shift+click or Ctrl+click button combinations.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
The need for a deeper project sorting interface seems not only common, but unavoidable for any user who plans to stay with Godot for a long time, as more and more projects are created and developers move on to newer engine releases, some of which will not be backwards-compatible.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This proposal is not specific to any subset of Godot projects. I believe developers working in any genre, on any scale, will see the value of this feature in project management.

**Comment by KoBeWi** [comment] 2020-07-05 07:57
Related to #1133

**Comment by Calinou** [comment] 2020-07-05 10:40
Duplicate of #1133.

**Closed by Calinou** 2020-07-05 10:40 UTC
Labels: archived, topic:editor
