### ISSUE TITLE
Unify VBoxContainer and HBoxContainer

### ISSUE THREAD

**Issue by Uniformbuffer3** [godotengine/godot-proposals#4617] opened 2022-06-02 20:05 UTC
### Describe the project you are working on

An RPG based game that heavily rely on class and scene inheritance.

### Describe the problem or limitation you are having in your project

The game i'm creating heavily rely on inheritance and i very often inherit from `HBoxContainer` or `VBoxContainer` to build custom graphic structures. The classes i'm creating often have a long inheritance list and if, at some point of the tree, i have to switch the layout while i want to maintain all the code, the only option available is to create a duplicate of all the code tree, with the only difference to use the container with the opposite orientation as base. It would be possible to also move all the code to a `Control` node and use a (interchangable) container as child, but this would not work for inherited scene because it would still not be possible to replace the container with the one with the desired orientation because parent nodes cannot be removed (as it should be).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would like to have "VBoxContainer" and "HBoxContainer" unified as a single `BoxContainer` with an "orientation" parameter exposed as enum value with the states "horizontal" or "vertical".

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The `BoxContainer` would have a selectable orientation parameter that define how children should be arranged. The container would listen for changes of such variable and rearrange children accordingly.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It depends: on projects that do not rely much on class and scene inheritance (like many use just ducktyping), it would be enough to just create a new scene with the desired layout. On the other side instead, it is not possible because to workaround this problem is required to rewrite a lot of code that it is really the same, but with a different container. So it would require to keep the "two branches" synchronized, that is very error prone and time wasting.

### Is there a reason why this should be core and not an add-on in the asset library?

Both containers are part of the core widgets.

**Comment by nathanfranke** [comment] 2022-06-02 20:08
In the meantime you can work around it by using a GridContainer and changing the columns to either `1` or `get_child_count()` (through code)

**Comment by YuriSizov** [comment] 2022-06-02 20:16
Duplicate of https://github.com/godotengine/godot-proposals/issues/3558.

**Closed by YuriSizov** 2022-06-02 20:16 UTC

**Comment by YuriSizov** [comment] 2022-06-02 20:19
> The game i'm creating heavily rely on inheritance and i very often inherit from `HBoxContainer` or `VBoxContainer` to build custom graphic structures. The classes i'm creating often have a long inheritance list and if, at some point of the tree, i have to switch the layout while i want to maintain all the code, the only option available is to create a duplicate of all the code tree, with the only difference to use the container with the opposite orientation as base.

Your classes can extend the `BoxContainer` base class, so you could apply them to either HBox or VBox node.
