### ISSUE TITLE
Let godot have the ablility to export just control nodes so ui applications are more size optimised

### ISSUE THREAD

**Issue by Quicksilver151** [godotengine/godot-proposals#5057] opened 2022-08-02 12:57 UTC
### Describe the project you are working on

a file manager with a few unique features

### Describe the problem or limitation you are having in your project

file manager only requires control nodes
however, godot exports the entire engine which unnecessarily takes up a lot of space in the executable file

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

godot could have 2 or maybe 3 different export templates
eg: `full engine`, `2d+control nodes`, `only control nodes`

this helps reduce a lot of unnecessary space taken up by the games made in godot
most people use godot to make 2d games so it will have a lot of benefits for file size out of the box
although inconvenient, compiling the engine with build flags may be a solution for 2d games but the same cannot be said for control nodes
so far, ive been unable to find a way to separate control nodes. it might be possible by modifying the source code but not everyone is able to write c++

godot has a lot of potential for ui programs given how easy it is to theme and how convenient it is to build a ui without having to write much code

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

compile the engine for control nodes and have the additional export templates available for download on the website

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can't be worked around with a few lines of script because it involves compiling the engine

### Is there a reason why this should be core and not an add-on in the asset library?

it helps support users who just want to build ui applications out of the box without having to modify the source
its not quite possible to implement this as an add-on as it has to do with compiling the engine

**Comment by KoBeWi** [comment] 2022-08-02 13:24
Duplicate of #190

**Closed by KoBeWi** 2022-08-02 13:24 UTC
