### ISSUE TITLE
Allow static typing of any object

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-proposals#1882] opened 2020-11-23 22:32 UTC
**Describe the project you are working on:**
NetworkTest

**Describe the problem or limitation you are having in your project:**
not to the project but the static typing as a whole

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
allow static typing for anything that derives from object :` as well as assignment support `:=`

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
var _scene    : PackedScene<NodeType>
var _path     : NodePath<NodeType>
var _node     : NodeType
var _dict     : Dictionary<NodeType, String>
var _resource : ResourceType
var _custom   : AnyCustomType
var _enum     : MyEnum
var _const    : MyConstEnum
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It would be used for https://github.com/godotengine/godot-proposals/issues/173
And no it can't be worked around.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Static typing in my opinion is far superior. not only does it allow to type information on autocomplete it also makes sure nothing is going to break or do anything its not suppose to do.
It also can be used for type checking so you don't get have cyclical dependencies and runtime include errors

**Comment by Shadowblitz16** [comment] 2020-11-23 22:35
The 1878 reference was a typo its not related

**Comment by Calinou** [comment] 2020-11-23 22:56
Duplicate of https://github.com/godotengine/godot-proposals/issues/192.

**Closed by Calinou** 2020-11-23 22:56 UTC

**Comment by Shadowblitz16** [comment] 2020-11-23 22:59
@Calinou this one covers more cases

**Comment by Calinou** [comment] 2020-11-23 23:02
@Shadowblitz16 Yes, but proposals should remain focused on a specific item. Proposals that are too widely scoped will be closed in favor of more specific ones.

**Comment by Shadowblitz16** [comment] 2020-11-23 23:09
ok I'll make a separate one for object then

**Comment by Shadowblitz16** [comment] 2020-11-23 23:19
@Calinou wait this is specificity on object.
Object is the base type so adding static typing for it would cover more most cases.

**Comment by Calinou** [comment] 2020-11-23 23:25
@Shadowblitz16 You can already use any class inheriting from Object as static type hint. However, a named enum is *not* an object type. This is why you can't use it as a type hint in GDScript. (As a workaround, you can still use an `int` as a type hint, which is better than nothing.)

**Comment by Shadowblitz16** [comment] 2020-11-23 23:42
you right i think I was thinking of exports.
