### ISSUE TITLE
Add support of gyroscope and accelerometer input from gamepads

### ISSUE THREAD

**Issue by NicholasShatokhin** [godotengine/godot-proposals#2908] opened 2021-06-23 10:06 UTC
### Describe the project you are working on
First Person Shooter

### Describe the problem or limitation you are having in your project
I can't use gamepad's gyroscopes and accelerometers on NS Pro and PS4/PS5 controllers

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I need to get value of each axis of gyroscope and accelerometer. It will allow me use it for aiming in game.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Just add additionally input type (like button, axis, etc) to controller's input options

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I'll be fine with any option. I just want to implement modern FPS controls like in Overwatch on Nintendo Switch

### Is there a reason why this should be core and not an add-on in the asset library?
I think, it is easier to implement as a part of engine because it is gamepad input.

**Comment by Xrayez** [comment] 2021-06-23 10:40
Duplicate of #2829.

**Closed** 2021-06-23 11:14 UTC
