### ISSUE TITLE
subViewPort mouse capture + camera zoom

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot-proposals#4342] opened 2022-04-04 17:13 UTC
### Describe the project you are working on

working on a 2d sekeleton animation editor...
each sprite in the animation is a polyGon

the sprite deformation can be changed by making the bones follow a button on screen

### Describe the problem or limitation you are having in your project

currently several limitations, regarding mouse position / Gui positions / camera position

when putting the animation sprites inside a viewPort / Container,
the mouse can longer detect the buttons to edit the image,
this gets in conflict with the 2Dcamera being used, zooming the camera doesnt update the subViewPort + mouse position

![gdViewPort](https://user-images.githubusercontent.com/77213594/161595702-f9e776eb-9944-4f46-9204-9d30b3d8643a.gif)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

there seems to be a global position in all nodes.
the global position doesnt seem to work for subViewPorts if a 2dCamera is being used in zoom.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Getting a mouse position that would work for everything 
currently getting the mouse position on screen is very complicated, because some nodes belong to the GUI

this is an example of a button following the position

		if ( Input.is_action_just_pressed('mouse_button') ):
			Input.warp_mouse_position( btn_name.get_global_transform_with_canvas().get_origin() );

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around using script
But there doesnt seem to be any script options that solve a button position inside a subViewPort once a 2Dcamera ZOOM is changed 

### Is there a reason why this should be core and not an add-on in the asset library?

it creates confusion

**Comment by Calinou** [comment] 2022-04-04 18:30
Duplicate of https://github.com/godotengine/godot/issues/59887. This appears to be a bug, so it shouldn't be discussed in a feature proposal.

**Closed by Calinou** 2022-04-04 18:30 UTC
Labels: topic:input
