### ISSUE TITLE
Need a solid, strong Terrain and Environment painter tool . . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot-proposals#507] opened 2020-02-23 05:48 UTC
**Describe the project you are working on:**

I am working on a Tomb Raider game, also an RTS, like StarCraft, and I need varying terrain, a good terrain editor . .

**Describe the problem or limitation you are having in your project:**

Right now, I have to model the terrain manually, in Blender, and make a modular kit, to make changes in terrain . . This is difficult, because fitting the CollisionShapes to the terrain is tough . . Most other engines have a basic terrain editor, and it really helps . . .

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

I would like a terrain editor, there's one from Zylann but, an official good one, that comes with Godot . . It should also have a tool, for painting trees, and so on, rocks, other stuff . . And, a layer where one can add decals, so if one needs a drain, or some paper, lying on the ground, one can paint that on top, of the terrain, after adding textures, to give a custom look . . So, one can add some transparent images, and paint them on top, of the tileable ground textures, grass, so on . .

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I can't code, so I don't know, but there's a terrain editor by someone called Zylann, and it does almost everything I need, but it needs to be able to paint rocks, from a set of rock pre-instances, and randomly rotate them, over the surface, or terrain . . Also, for painting trees, and a tool over that, that can paint decals, over that . . Like roads, or so, stuff lying on the ground, for extra details . . I have a KinematicBody, and if there was a terrain tool, I could make the character ' follow ' the terrain, and it'd look good, pro, solid . . .

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I don't think so, I'm new to Godot, but I haven't seen this feature, and it takes forever to make all the CollisionShapes, for the custom-made ground, especially for complex terrain . . I think this would improve Godot vastly, for all users . . .

**Is there a reason why this should be core and not an add-on in the asset library?:**

It's something most games need, at least 3D worlds, so it would be useful to all people working in that genre, also for Godot to appeal to more game makers, in those areas . .

Unity has a very good terrain editor, but there needs to be the last layer, of painting custom decals, to make the world look unique, and possibly bake the combined textures into single textures, like baking a lightmap, when it has all been placed, for faster performance . . :)

**Comment by jasperbrooks79** [comment] 2020-02-23 06:00
Maybe you could contact Zylann, and ask him if he would finish his terrain editor, and pay him a little of the money in the Epic grant, to pay for his time . . .

https://www.youtube.com/watch?v=nFwsmwr4AUs

It already looks pro, good enough for making games, I want it, and it would really help, a lot . .

Please consider, thank you . . :) :)

**Comment by KoBeWi** [comment] 2020-02-23 11:34
Duplicate of #445

**Closed by KoBeWi** 2020-02-23 11:34 UTC
