### ISSUE TITLE
Option to display an image while Vulkan shader precompilation runs

### ISSUE THREAD

**Issue by snoopdouglas** [godotengine/godot-proposals#6566] opened 2023-03-25 09:42 UTC
### Describe the project you are working on

Space shooter

### Describe the problem or limitation you are having in your project

On first run, Vulkan shaders can sometimes take a while to compile, and while it happens, the user just sees a blank window.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I'd like to be able to display an image in the window while the shaders are compiled.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

While it'd probably be fine to just display the boot splash, it'd be useful to be able to use an entirely separate image (so that I can indicate that the wait isn't abnormal).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

AFAIK there's no way of adding pre-shader compilation hooks using GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?

As above.

**Comment by AThousandShips** [comment] 2023-03-25 10:16
I'm not sure this is possible with the current setup of the rendering server, and not sure how complicated it would be to make it possible

**Comment by Calinou** [comment] 2023-03-25 16:20
- Duplicate of https://github.com/godotengine/godot-proposals/issues/3657.

**Closed by Calinou** 2023-03-25 16:20 UTC
