### ISSUE TITLE
Paragraph spacing, separate from line spacing

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot-proposals#7533] opened 2023-08-20 12:44 UTC
### Describe the project you are working on

I would like Label and RichTextLabel to have a separate "paragraph spacing" variable from "line spacing". RichTextLabel already has a [p] tag for paragraphs, but I can't find any way to add spacing between two [p] tagl.

### Describe the problem or limitation you are having in your project

Currently, to add extra spacing between paragraphs but not between lines, the only way to do so is to use multiple Labels/RichTextLabels in a VBoxContainer. This makes it a bit cumbersome to create multi-paragraph texts in UI, and much worse to programmatically alter multi-paragraph texts.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

For RichTextLabel, there should be an option to increase the spacing between the existing [p] BBCode tag.

For Label, lines in the same paragraph (e.g. word-wrapped, separated by 1 line break entered by Shift+Return) should be separated by the existing line spacing value. Lines in a different paragraph (e.g. separated by 2 line breaks) should be separated by the existing line spacing value PLUS the new paragraph spacing value.

This helps make it possible to have paragraph spacing with just one Node.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Existing Labels with only single line breaks won't be altered, but double line breaks would be interpreted as paragraph breaks.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Besides the "multiple Labels in a VBoxContainer" approach, an existing but hacky way to achieve this effect using a RichTextLabel is to insert an extra line between paragraphs: "[font_size=4] [/font_size]", i.e. a line consisting of a single space in a font size equal to the size of the space you want to insert between paragraphs..

### Is there a reason why this should be core and not an add-on in the asset library?

This is about providing useful formatting options that most people would find the occasion to use for multi-paragraph text boxes (e.g. in tutorials and embedded manuals).

**Comment by dalexeev** [comment] 2023-08-20 16:38
* Basically it's a duplicate of #6292.

There is an addition about `[p][/p]` and `Label`, but I think that this can be added as a comment to the original proposal.

Thanks for the contribution nonetheless!

**Closed by dalexeev** 2023-08-20 16:38 UTC
Labels: topic:gui
