### ISSUE TITLE
Turn off `loop` for audio in Import

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-proposals#3692] opened 2021-12-18 17:47 UTC
### Describe the project you are working on

A couple of games

### Describe the problem or limitation you are having in your project

When making games I found myself turning off this button extremely often
![turn it off](https://user-images.githubusercontent.com/16458555/146650516-2ee04a2e-e705-497d-8d8f-20d7e82712b0.JPG)

I keep Loop on for background music etc but the number of such files is much less

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Having `loop` turned off by default would solve the problem

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![solution](https://user-images.githubusercontent.com/16458555/146650661-2a4c025c-3722-4a88-af8d-c47e7ec6f53d.JPG)

I believe loop should be off for all other formats too.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Currently it can't

### Is there a reason why this should be core and not an add-on in the asset library?

Not sure if this can be done with a plugin.
But even if so, I still believe this should be in core not as a plugin.

**Comment by soundsbeard** [comment] 2021-12-18 17:55
for games i make i have short sounds for:
- each character's move, attack, receiving dmg, death 
- each skill
- each interaction
- each mob with its skills, etc
- each dialogue piece
- some ambient random sounds

all of them are not repeatable.
music on the other hand is about 3-5 tracks.
so yeah, its very annoying to disable loop for every tiny sound, loop should be disabled by default.

**Comment by Calinou** [comment] 2021-12-18 18:19
Duplicate of https://github.com/godotengine/godot-proposals/issues/3120.

**Closed by Calinou** 2021-12-18 18:19 UTC

**Comment by me2beats** [comment] 2021-12-18 18:26
That proposal is for moving Loop from an import option to a property in the AudioStreamPlayer nodes.
Does it include turning it off?

**Comment by Calinou** [comment] 2021-12-18 18:28
> That proposal is for moving Loop from an import option to a property in the AudioStreamPlayer nodes.
> Does it include turning it off?

Yes, this is a compatibility-breaking change so it should be discussed at the same time :slightly_smiling_face:

**Comment by KoBeWi** [comment] 2021-12-18 19:58
You can change the default from the Preset button menu.

**Comment by me2beats** [comment] 2021-12-18 20:06
> You can change the default from the Preset button menu.
Isn't it per project?
That means I need to do this for each new project.
And the projects are not only games, they could be plugins or just test projects to test something.

**Comment by KoBeWi** [comment] 2021-12-18 20:22
> Isn't it per project?
That means I need to do this for each new project.

You don't make new projects that often, no? Also the defaults are stored in `project.godot`, so you can set it in a fresh project and then use that `project.godot` file for new projects.

> And the projects are not only games, they could be plugins or just test projects to test something.

I don't think this is relevant for such projects.

**Comment by me2beats** [comment] 2021-12-18 21:24
>You don't make new projects that often, no?

As for me, usually I create 3 new projects a day :)
many of them are test projects tho..

>Also the defaults are stored in project.godot, so you can set it in a fresh project and then use that project.godot file for new projects.

I don't think this would be handy because there could be other settings that I don't want to change for the project.
So just replacing `project.godot` file won't be flexible solution I guess.
Having **global default presets** for audio and and other importable files would partially (and maybe mostly) solve the problem imo.
Something like this one
https://github.com/godotengine/godot-proposals/issues/3483

>I don't think this is relevant for such projects.

I don't get why this can't be relevant. A test project or a project to test a plugin can use audio.

**Comment by me2beats** [comment] 2021-12-18 21:25
My point is that for me the ideal solution would be if loop was off by default.
And that's not only my case (we had a short discussion about this in our local discord server).

I prefer straightforward solutions, not workarounds that's why I created this proposal.

**Comment by KoBeWi** [comment] 2021-12-18 22:20
> I don't think this would be handy because there could be other settings that I don't want to change for the project.

No, I mean, create an empty project, change only the audio setting. Then you have empty project with just the default changed, so if you copy it, you get a new project with the default you want.
[project.godot.txt](https://github.com/godotengine/godot-proposals/files/7740026/project.godot.txt)
The only problem with this solution is less convenience - you need to copy this file manually to every new project.

> I don't get why this can't be relevant. A test project or a project to test a plugin can use audio.

It can, but maybe it can use wavs or looping doesn't matter. I just can't imagine why would you need e.g. 10 random non-game projects that must use non-looping MP3s.

**Comment by me2beats** [comment] 2021-12-18 22:29
> I mean, create an empty project, change only the audio setting

what if the project already exists?
The workaround won't be helpful

**Comment by me2beats** [comment] 2021-12-18 22:43
If the project already exists and has a lot of data, setting loop off manually may be not so easy.
I think setting it from the editor would be even easier (set it off once then save the preset)
But I still don't get why I need to do this or anything else if the option could simply be turned off by default (in case most of Godot users find it fine)
