### ISSUE TITLE
Request system high precision timer

### ISSUE THREAD

**Issue by RedElectricity** [godotengine/godot-proposals#3741] opened 2022-01-02 13:06 UTC
### Describe the project you are working on

I am working on a rhythm game

### Describe the problem or limitation you are having in your project

![image](https://user-images.githubusercontent.com/75127571/147876498-09d58367-9cb1-4638-81fe-45f8367500fe.png)

process pass time couldn't be  stable and  it couldn't set

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I want it  can set and stable

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When code run in _Ready(),it can use code to set
```c#
setTimerPrecision(int ms);
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes

### Is there a reason why this should be core and not an add-on in the asset library?

It's set sence processTime

**Comment by Calinou** [comment] 2022-01-02 16:20
Duplicate of https://github.com/godotengine/godot-proposals/issues/1151. (System high-precision timer will not help you play sound on a precise beat. The issue here is not timer precision, it's that events can only be triggered on each frame, giving you ~16.7 ms precision at 60 Hz.)

**Closed by Calinou** 2022-01-02 16:20 UTC

**Comment by kirkwoodwest** [comment] 2024-03-15 02:23
Engine logic is sound... there may be other things one wants to do in relation to great timing... maybe play a midi signal or send off network event. this would be cool.
