### ISSUE TITLE
Ability to disable reflection from VoxelGI

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot-proposals#3162] opened 2021-08-19 17:58 UTC
### Describe the project you are working on

3D environments

### Describe the problem or limitation you are having in your project

When using VoxelGI + ReflectionProbes the reflection result gets messed by the VoxelGI reflection

VoxelGI ON
![image](https://user-images.githubusercontent.com/1168582/130119998-6ce1b21a-e3a8-4e51-a770-a30150cae8e1.png)

VoxelGI OFF
![image](https://user-images.githubusercontent.com/1168582/130120072-f1bd53df-fc10-4e42-a023-c83f7d2fbcc7.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Have a checker in the VoxelGI options to enable/disable reflections

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Same as above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

VoxelGI is core

**Comment by Calinou** [comment] 2021-08-19 19:03
Duplicate of https://github.com/godotengine/godot-proposals/issues/3012.

Also, it's expected that ReflectionProbes and VoxelGI blend smoothly by default. If you want this to be less visible, increase the extents of your ReflectionProbe.

**Closed by Calinou** 2021-08-19 19:03 UTC
