### ISSUE TITLE
Add AreaLight3D support

### ISSUE THREAD

**Issue by alexfreyre** [godotengine/godot-proposals#2110] opened 2021-01-12 17:45 UTC
### Describe the project you are working on
Some 3D projects

### Describe the problem or limitation you are having in your project
Currently, there is no area light support only directional or punctual lights. 

Because of that sunlight or light bulbs can be simulated when the current lights are used and objects are lit (diffuse light, but the only way to get something similar to a light panel or longs cold light bulbs is to bake rectangular planes or scaled cubes with an emission shader via GIProbe which increase the graphical requirements. Moreover because GIProbes are thought as a indirect lightning solution the planes baked lit less the scene and they are reflected more, but they looks more or less as an area lights.  

The other aspect very noticeable is the specular lobe from each light currently implemented is round, so for certain visual solutions are needed specular squared lobes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I believe that the solution is the area lights that illuminate in a non-point way, be it square, rectangular, rhomboid, polygonal hexagonal, with rounded edges or even circular or elliptical.

That will generate non-point specular light allowing to reflect all kinds of elements that radiate light in the form of an area.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
fake area light via GIProbe 
![GI](https://user-images.githubusercontent.com/42384785/104351385-39e99300-54fd-11eb-8203-09a8663142ba.jpg)

Actual lighting solutions:

Directional light
![direct](https://user-images.githubusercontent.com/42384785/104351461-571e6180-54fd-11eb-9fb6-33fa3a9a31d2.jpg)

Omni light
![omni](https://user-images.githubusercontent.com/42384785/104351487-5d144280-54fd-11eb-94ef-67223a70b790.jpg)

Spot light
![spot](https://user-images.githubusercontent.com/42384785/104351503-62718d00-54fd-11eb-8ae4-769045a4b16a.jpg)

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I have no idea.

### Is there a reason why this should be core and not an add-on in the asset library?
I guess it is core but it can be an addon.

**Comment by Calinou** [comment] 2021-01-12 17:47
Duplicate of https://github.com/godotengine/godot-proposals/issues/1275.

**Closed by Calinou** 2021-01-12 17:47 UTC
Labels: topic:rendering
