### ISSUE TITLE
Best-Effort Input Event Timestamping

### ISSUE THREAD

**Issue by xeonmc** [godotengine/godot-proposals#2785] opened 2021-05-26 22:11 UTC
### Describe the project you are working on
Surveying options for timing-critical simulation with rewinding/retroactive recalculation

### Describe the problem or limitation you are having in your project
"XXX is not a realtime OS" -- obviously any msgloop polling cannot be taken as reliable, but the further upstream it gets timestamped with best effort the less potential for jitter it has, especially if said loop is decoupled from heavy-lifting performance

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Timestamp any input msg at the earliest possible, most upstream location and set as a property for the generated event

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Message loop runs asynchronously from the main simulation, timestamp as early as physically possible, set as property for event if it's input or discard if it's not, let gamedevs decide what to do with that info.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes, just ignore the timestamp

### Is there a reason why this should be core and not an add-on in the asset library?
require upstream/asynchronicity

**Comment by Xrayez** [comment] 2021-05-26 22:44
Would you say that this is related to #552?

**Comment by xeonmc** [comment] 2021-05-27 09:04
Yes

**Comment by Calinou** [comment] 2021-05-30 12:20
Duplicate of https://github.com/godotengine/godot-proposals/issues/552.

**Closed by Calinou** 2021-05-30 12:20 UTC
Labels: topic:input
