### ISSUE TITLE
Copy route in parameters and others

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot-proposals#2397] opened 2021-03-04 13:26 UTC
### Describe the project you are working on
An indie project

### Describe the problem or limitation you are having in your project
Unable to copy the path of some sections in the editor, for example the "parameters" section in the image.
If you need to use "animationTree.Set (string routeToParam, float value);" you must memorize to indicate it in "animationTree.Set".
Why can't you copy the path to param like you copy the path to a node in the tree?

![Captura2](https://user-images.githubusercontent.com/19652075/109970527-75326200-7cf5-11eb-820e-35697a6a94d1.PNG)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
By pressing the right button of the mouse a contextual menu appears indicating the option to copy the path to the parameter.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
Not possible with a library

**Comment by Calinou** [comment] 2021-03-04 15:39
Duplicate of https://github.com/godotengine/godot-proposals/issues/1504.

**Closed by Calinou** 2021-03-04 15:39 UTC
