### ISSUE TITLE
Add a project setting to force an integer scale for window stretch

### ISSUE THREAD

**Issue by Yukitty** [godotengine/godot-proposals#1666] opened 2020-10-14 19:47 UTC
**Describe the project you are working on:**
Low resolution 2D pixel art games.

**Describe the problem or limitation you are having in your project:**
Base engine stretch modes can preserve aspect ratio, but do not attempt to guarantee an even and square pixel grid.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
New project setting checkbox located at `display/window/stretch` labelled "Force Integer Scale" (or similar) which changes stretch behavior to attempt preservation of square pixels.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I've already produced the feature for 3.2.X here: Yukitty/godot@42af4d50e696e790e33a0d9347fbe55e06da13e8
I am personally using this feature for all current and future 2D projects, as I do not produce or use high resolution art assets.

Ideal test project settings:
* `display/window/size/width` and `height` set to something low, like 256x224 or 320x240
(I am leaving `display/window/size/test_width` and `test_height` set to 1280x720 even in production)
* `display/window/size/resizable` On.
* `display/window/stretch/mode` 2d
* Use pixel art assets (Filter OFF) and pixel snap to produce a scene.

Test fiddling with these settings:
* `display/window/stretch/integer_scale` (the new feature)
* `display/window/stretch/aspect` (different behaviors per setting)

Demonstrated behavior while Integer Scale is active:
* If `display/window/stretch/aspect` is set to `Keep`, the game render will be letterboxed on ALL sides as the window expands, jumping up to the next available multiple of the base resolution _only_ when both the window's width and height are adequate to support it.
* If aspect is set to `Keep Width` or `Keep Height`, the game window will stretch vertically or horizontally, respectively, to almost fill the available space (discarding fractional pixels to preserve pixel accuracy). New letterbox bars will appear on the "kept" sides, which only jumps to resolution multiples.
* If aspect is set to `Expand`, the game's aspect ratio will expand in both directions simultaneously, which is another entirely new behavior.
* In all cases, if integer scale is checked, the pixels should be square, at all resolutions and window sizes, at all times. There may be minor rounding errors in my implementation, but the result is still notably better.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Almost. The primary blocker preventing a fully scripted solution from being viable is actually the font overdraw setting, which cannot be accessed outside of the SceneTree's root viewport stretch project settings, and is crucial for making dynamic fonts look good on a low resolution screen that's been scaled up.

Even avoiding that issue by using a pixel font, this behavior requires an obscure script and is not easily accessible to many users, as it's not a native setting of Viewports nor ViewportContainers that would display them.

There may be enough potential users to warrant a built-in simple setting, the same users of the Pixel Snap setting which currently work around this issue differently, by limiting the window size to specific game-enforced resolutions, or disabling the stretch feature entirely and writing it off as unusable.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I can't currently fully replicate this behavior as an add-on due to the font overdraw, as described above.
Otherwise it may be viable, though it seems like an awfully minor feature to bury in the asset library. 🤔
It seems more suitably described as a base engine behavior rather than a key feature specific to any particular game or genre.

**Comment by Calinou** [comment] 2020-10-14 20:27
When working on https://github.com/godotengine/godot/pull/21446, I thought about adding a "Stretch Integer" checkbox which would constrain the final scaling ratio to always be an integer factor.

**Comment by dalexeev** [comment] 2020-10-14 21:04
1\. For pixel games, it's better to use Viewport mode instead of 2D.

2\. Here's my version of the script:

```gdscript
func _ready():
    get_tree().connect("screen_resized", self, "_on_screen_resized")

func _on_screen_resized():
    var screen = OS.get_screen_size() if OS.window_fullscreen else OS.window_size
    var k = min(int(screen.x / 320), int(screen.y / 180))
    var size = k * Vector2(320, 180)
    var pos = ((screen - size) / 2).floor()
    get_tree().root.set_attach_to_screen_rect(Rect2(pos, size))
    var end = screen - pos - size
    VisualServer.black_bars_set_margins(pos.x, pos.y, end.x, end.y)
```

3\. If it works out of the box, it will be great. :smiley: 

4\. In addition, we also need the `black_bars_bg_color` and `black_bars_bg_image` settings.

**Comment by Yukitty** [comment] 2020-10-15 01:52
Fine~ I attempted to make a [fully-featured addon package](https://github.com/Yukitty/godot-addon-integer_resolution_handler/tree/3.2) as well, for fun.

The main differences being,
1. since the plugin and/or autoload has to be enabled in order for the functionality to exist, there's no reason to include a separate checkbox to enable it
2. for some reason I opted to add a separate resolution option instead of mis-using the "test resolution" setting again
3. dynamic font overdraw doesn't work (obviously), but that's not a big loss.

So I suppose you can use that as a prototype implementation now as well.
I do not believe this is a simple script to produce, and would still prefer a native setting, especially if more of the imperfect geometry can be fixed... 😓

I also have not gotten good results from the viewport scaling mode, counter-intuitively. It just makes the slight noise more noticeable.

**Comment by Yukitty** [comment] 2020-10-15 02:56
Ohh, is it the physics/camera that are messing everything up now? Of course, only the individual polygons get snapped to pixels, the actual camera offset and object positions are still all over the place... 😓 Seems like this might take more work still.

**Comment by dalexeev** [comment] 2020-10-15 18:09
@Yukitty I looked at your addon and left some comments. This is a very good prototype. :+1: 

The only thing, it seems to me, that this function should be implemented not by a checkbox, but as a separate `stretch_mode` (as a stricter version of the `Viewport` mode). 

It doesn’t combine with `disabled` mode in any way, with `2d` mode it is formally combined, but it looks like slyness.

Here's what the [documentation](https://docs.godotengine.org/en/stable/tutorials/viewports/multiple_resolutions.html#stretch-mode) says about it:

> Stretch Mode = 2D: <...> This is a good option if your 2D artwork has a sufficiently high resolution and **does not require pixel-perfect rendering.**

`2d` mode adds additional details for lines, fonts, etc.:

![](https://user-images.githubusercontent.com/47700418/96168386-54759580-0f29-11eb-858e-455d6ce5c0c1.png)

![](https://user-images.githubusercontent.com/47700418/96168406-5c353a00-0f29-11eb-9ce0-44c138fbd99c.png)

(That is, this cannot be called _pixel perfect mode_ in any way. :rofl: )

This is "wrong" for pixel games, but okay. You can simply point this out in the documentation, but not take away the choice from users. However, the number of combinations of different modes, aspects and this new feature is truly impressive.

**Comment by Yukitty** [comment] 2020-10-15 19:43
Yeah, I was just confused because viewport was looking mighty terrible, solely because my character and camera were moving on subpixels it turns out, and Pixel Snap by itself does not seem to 100% ensure things won't come up weird/inconsistent sometimes, especially at higher resolutions? 😓

I had to rewrite my whole player physics to work on a completely separate hidden layer with the sprites just following the whole-number positions around and a custom camera Node2D script doing the same...

**Comment by Calinou** [comment] 2020-10-15 19:45
@Yukitty This will be fixed by https://github.com/godotengine/godot/pull/41535 if it's merged.

**Comment by asheraryam** [comment] 2020-11-17 21:02
I think this is closed by https://github.com/godotengine/godot/pull/43194

**Comment by Calinou** [comment] 2020-11-17 21:41
@asheraryam No, this is a different issue.

**Comment by snoopdouglas** [comment] 2020-11-19 20:20
In case anyone has come across this and wants a visual explanation:

* Here's a perfectly integer-scaled 2D scene (at 8 pixels to 1):

  ![Screenshot from 2020-11-19 20-12-29](https://user-images.githubusercontent.com/4892574/99719292-09105300-2aa4-11eb-9554-022ae66061e6.png)

* Here's that same scene with the scale just slightly off an integer. Note the character's eye:

  ![Screenshot from 2020-11-19 20-12-51](https://user-images.githubusercontent.com/4892574/99719540-5391cf80-2aa4-11eb-9ee8-070be1549c29.png)

The latter is what this proposal is seeking to avoid. For me, this often happens when my game is in windowed mode and the window gets resized (away from a nice integer-scaled size).

**Comment by starry-abyss** [comment] 2020-11-19 22:25
From my experience, if expanding viewport is used for pixel perfect scaling (that is, when the whole game window is covered, giving different view area for different aspect ratios) - it's desirable to have a callback where game developer can override integer factor for currently set window width/height.

This is because games have different metrics of what size of area the player needs to see. For example, in one of the games we used about 9 tiles per window height as ideal metric, and from all integer factors found the one to achieve the closest to this metric (as opposed to fixed view area with camera auto-stretched based on "as thin as possible black bars on sides metric").

**Comment by chucklepie** [comment] 2021-01-17 23:21
I can only confirm this is the case, on stretching my screen the result is truly awful :(

Every line is stretching the pixels wider or taller...

![image](https://user-images.githubusercontent.com/12863685/104858951-96dcb300-591a-11eb-8d5a-7642b2053777.png)

**Comment by snoopdouglas** [comment] 2021-01-28 17:43
I've just given 3.2.4-rc1 a go, and to be clear, it doesn't do what @Yukitty's addon does.

People landing here from Google, [check the comment above](https://github.com/godotengine/godot-proposals/issues/1666#issuecomment-708844214).

**Comment by Calinou** [comment] 2021-01-28 17:45
> I've just given 3.2.4-rc1 a go, and to be clear, it doesn't do what @Yukitty's addon does.

That's because we didn't add integer scaling yet :slightly_smiling_face:

**Comment by snoopdouglas** [comment] 2021-01-28 17:50
Yes - just wanted to make it clear for anyone scanning the thread :+1:

**Comment by cybereality** [comment] 2021-12-23 21:00
@chucklepie Can you upload that reproduction project for me with the blue and yellow pixels? I believe I know how to fix this, but the tests I'm doing all seem to work fine in Godot. I need to see it broken first and then I will add support on my Godot Super Scaling add-on. Thanks.

**Comment by chucklepie** [comment] 2021-12-24 16:33
@cybereality , It's almost a year since so not really, however this is just a basic image with 4x4 pixels.

Regardless, it's been almost a year and no progress so I'd suggest the devs (@Calinou) simply copy this code/equivalent from @Yukitty, https://github.com/Yukitty/godot-addon-integer_resolution_handler and just be done with it :)

I've been using it for a year on various projects and as well as saving my project, it just works and integer scales my games perfectly.

**Comment by Calinou** [comment] 2022-02-08 17:35
I've started implementing this in a branch: https://github.com/Calinou/godot/tree/rework-content-stretch
However, I didn't get it to work yet. Integer scaling works, but UI anchors are currently messed up if the window is resized at a size that isn't a multiple of the base resolution.

Note that the setting is an enum and not a boolean, since I want to implement *hybrid* scaling in the long run. Hybrid scaling scales up the image to the next multiple, then scales it down with linear filtering to fit the whole screen. It allows for displaying pixel art without distortion (but with *some* blurriness) at any target resolution, which is good for small displays such as the Steam Deck's. Most emulators including DOSBox forks generally provide an hybrid scaling option as well.

**Comment by starry-abyss** [comment] 2022-02-09 07:58
I've implemented hybrid scaling recently with ViewportContainer->Viewport->ViewportContainer->Viewport->Scene, where I set the outer viewport's texture to linear mode:

```
extends Viewport

func _ready():
	get_texture().flags = Texture.FLAG_FILTER 
```

I've set stretch mode to 2D for it to work. And to fix fonts I've disabled font oversampling.

It would be great to have this out of the box nonetheless!

**Comment by starry-abyss** [comment] 2022-07-26 17:26
@snoopdouglas Sure, here you are:
[hybrid-upscaling-godot.zip](https://github.com/godotengine/godot-proposals/files/9192040/hybrid-upscaling-godot.zip)

**Comment by chucklepie** [comment] 2023-01-10 21:08
is there by any chance thought being applied to this functionality being added to Godot 4? the display/rendering/viewport/subviewport code has changed so much that existing projects like the ones described and created here as plugins do not work and require a massive amount of rework with very little documentation to go by...

Integer scaling is still very much useful :)

**Comment by Calinou** [comment] 2023-01-11 02:28
> is there by any chance thought being applied to this functionality being added to Godot 4?

Not for 4.0, since we're in feature freeze now.

**Comment by chucklepie** [comment] 2023-01-14 13:51
Integer scaling has been added to the camera I notice in g4, to go with pixel snapping. Clearly aimed at pixel platformers.

But lack of integer scaling on the viewpoint is just madness, if you have a pixel game you need internet scaling.

Sadly none of the current libraries work given the amount of changes to the tender server, viewport, window, etc.

I bet for a Godot maintainer it's a dozen lines of code with a checkbox in the project settings to front, but a million likes and appreciations 😉

**Comment by cybereality** [comment] 2023-01-14 14:28
@chucklepie I know how to do integer scaling. I could make a plug-in, I was planning to at some point, but I mostly work in 3D so it was not useful to me. I think that's the best way forward right now, but if the plug-in gets interest I can speak with the team about adding to the Godot, maybe for 4.1.

**Comment by ssokolow** [comment] 2023-01-14 14:46
> Integer snapping has been added to the camera I notice in g4, to go with pixel snapping. Clearly aimed at pixel platformers.
> 
> But lack of integer scaling on the viewpoint is just madness, if you have a pixel game you need integer scaling.

> but I mostly work in 3D

Is integer scaling on the viewport only useful for pixel 2D stuff or would it also be relevant to certain kinds of retro-revival 3D games. (eg. 320x240 DOS 3D games, PSX/PS1/PSOne games, etc.)

**Comment by prominentdetail** [comment] 2023-01-14 15:02
> Is integer scaling on the viewport only useful for pixel 2D stuff or would it also be relevant to certain kinds of retro-revival 3D games? (eg. 320x240 DOS 3D games, PSX/PS1/PSOne games, etc.)

For my 3d game, I am using a resolution of 160x160 pixels.
I set the viewport size in Project Settings > Display > Window > Viewport Width/Height to 160 x 160
I set the Stretch mode to Viewport, and the Aspect to keep_height.

When I load the game, I do this is gdscript:

	# setup window size
	var screen_size = DisplayServer.screen_get_size()
	var minSize = min(screen_size.x,screen_size.y)
	DisplayServer.window_set_size( Vector2( floor(minSize/160)*160, floor(minSize/160)*160 ) )
	var window_size = DisplayServer.window_get_size()
	DisplayServer.window_set_position( screen_size*0.5 - window_size*0.5 )

That will create a window as large as it can at an integer scale,
and then based on any saved game settings decide if it should be fullscreen below:

	if( global.settings.screen == 'fullscreen' ):
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_FULLSCREEN)
	else:
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_WINDOWED)

**Comment by prominentdetail** [comment] 2023-01-14 15:15
The problem is that in order to have low res on 3d, you have to have the Stretch mode set to something other than disabled.
If it is set to Disabled, then you can't make the resolution smaller(It just uses max resolution of the window)..
But since you have to choose a Stretch mode, it stretches the pixels.. This is tied directly to the window size, and if the window size changes, the scale of the pixels within the window changes and becomes non-integer.

So yes, 3d needs an integer option too.

**Comment by ssokolow** [comment] 2023-01-14 15:27
It certainly sounds like it. I'm very much used to working in windowed mode and manually resizing windows and, when I trust applications enough to not try to change the display resolution and trick my window manager into crushing all my windows onto a single monitor, I still have a 1280x1024, 1920x1080, 1280x1024 spread... which means I don't have any 4:3 monitors for retro-authentic games to fullscreen onto without letterboxing or pillarboxing.

**Comment by chucklepie** [comment] 2023-01-14 17:04
From the OP, this works fine in 3.x so just needs a massive overhaul because almost everything it does happens to be the major areas of change in Godot 4, however built in is the way to go, not a plugin
https://github.com/Yukitty/godot-addon-integer_resolution_handler/tree/3.X

**Comment by muno777** [comment] 2023-01-17 16:19
This would be super helpful, especially since the removal of `VisualServer.black_bars_set_margins()` gets in the way of porting old solutions over to Godot 4 (e.g. https://github.com/Yukitty/godot-addon-integer_resolution_handler/tree/3.X relies on the removed black bar feature).

I'm looking forward to Calinou's PR being added to a future 4.x release!

**Comment by chucklepie** [comment] 2023-01-17 18:59
I had to give up porting because black bars completely disappeared with no
mention and I couldn't find a replacement.

It would be nice if some kind of missing feature / replacement was
available...

**Comment by fmfarrand** [comment] 2023-02-25 21:29
I am finally trying to port over a project from 3.x to 4 and the only insurmountable hurdle for me has been the lack of a way to enforce integer scaling in Godot 4. It is frustrating that the engine has been relying on a plugin, which breaks in 4.0, instead of having this as a built in option. This make it impossible to have responsive applications that use pixel art in Godot 4! For now, I am disabling resizing altogether so I can continue development in 4.x until there is some sort of solution, but I just wanted to agree that a fix is needed and would be much appreciated!

**Comment by Calinou** [comment] 2023-02-25 21:33
@fmfarrand Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by chucklepie** [comment] 2023-02-26 07:38
The problem he's facing is frustration as the project properties, render
server, display server, etc have all changed massively making it very
difficult to port old stuff out know what features of the API to use, and
there is a complete lack of why documentation describing any of it making
it impossible outside of the core developers to implement.

**Comment by Calinou** [comment] 2023-02-26 20:47
I've toyed around with a sharp bilinear filtering implementation for viewport scaling using the `2d` stretch mode on the root viewport and a shader on a SubViewport node.

While this is not as sharp as integer scaling, it works with any output resolution, including those that aren't a multiple of the base window size.

**Testing project (4.x):** [test_sharp_bilinear.zip](https://github.com/godotengine/godot-proposals/files/10834699/test_sharp_bilinear.zip)

### 640×480 (base resolution)

![Screenshot_20230226_214419](https://user-images.githubusercontent.com/180032/221436260-3a1fc2e7-d5fa-40e5-977d-e8387410d8f1.png)

### 3840×2160 (4.5× scale factor)

![Screenshot_20230226_214411](https://user-images.githubusercontent.com/180032/221436259-79b22aa3-4069-45dd-b816-1e5fde5c696f.png)

### 1105×786 (1.6375× scale factor)

![Screenshot_20230226_214355](https://user-images.githubusercontent.com/180032/221436257-476e4fb1-468d-461f-ab11-43b1a887ef6b.png)

**Comment by fractalcounty** [comment] 2023-03-01 23:16
As a newcomer to 4.0 and Godot as a whole, figuring out how to combine pixel perfect assets with a high resolution UI and smooth camera movement has been a nightmare.

There are dozens of factors that all impact this problem in various ways, such as: 
- Scaling mode in preferences
- 2D vertices snap in preferences
- 2D transform snap in preferences
- Vertices/transform snap toggle in subviewport inspector
- Enabling editor grid pixel snap to avoid placing objects at non-integer positions, which still seems to occasionally place them at subpixel positions anyways
- Camera and player properties, i.e character and camera positions not being rounded to integers
- Texture filtering method

This is a headache-inducing amount of variables to account for, and many of them are not well explained in the docs at the moment. Most common solutions for 3.0+ such as [subpixel buffer shaders](https://code-disaster.com/2016/02/subpixel-perfect-smooth-scrolling.html) or [using viewports](https://youtu.be/LoR4Xg1l29U) don’t seem to intuitively translate to 4.0 despite my best efforts. 

Whether this problem comes down to user error or could be improved upon within the editor is well beyond my scope. However, given that this is such a common use case, I think a set of best practices for pixel perfect games in the docs is desperately needed.

**Closed** 2023-08-11 08:34 UTC
Labels: topic:core, topic:rendering
