### ISSUE TITLE
Smart Renaming of Variable names scriptwide within Replace(CTRL+R)

### ISSUE THREAD

**Issue by Chevifier** [godotengine/godot-proposals#6217] opened 2023-01-31 19:55 UTC
### Describe the project you are working on

This is a General Scripting improvement

### Describe the problem or limitation you are having in your project

Renaming text within a script renames every instance of that world or phrase 
![old_example](https://user-images.githubusercontent.com/9784593/215865295-043ab473-9e16-4db9-afca-28a97d7fcad4.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This feature will allow renaming of variables script wide without changing other text or functions that contains the same phasing. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user presses CTRL+R the standard phrase/text replacing text fields will show up at the bottom of the script window. But now you will have the ability to replace only variable names.
First you would specify the variable type that it was created with i.e "var" then its name "example" the in the replace field you could just type the new name. This would isolate the replacement to just instances of the variable "example" in the case instead of every example text found.
![new_example](https://user-images.githubusercontent.com/9784593/215866748-943d81d0-9bda-48c8-b230-523211fc65fb.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by NOT using assigned variable names to text or function names within the same script such as
var string = "This has the word example in it" or a function func _execute_example() but it is very useful in large script file.
or giving every variable name and underscore(_) before their names which not everyone does.

### Is there a reason why this should be core and not an add-on in the asset library?

This would be a standard part of the script editor for replacing variable name script wide.

**Comment by Sslaxx** [comment] 2023-02-01 01:43
I'd rather have a tickbox saying something like "Variable/function name" instead, to avoid potential confusion with having to type "var" in the search box/

**Comment by Chevifier** [comment] 2023-02-01 02:57
> 

Thats definitely an even better option.

**Comment by Calinou** [comment] 2023-02-01 10:54
Duplicate of https://github.com/godotengine/godot-proposals/issues/899.

**Closed by Calinou** 2023-02-01 10:54 UTC
