### ISSUE TITLE
Var name `_` is forbidden but `__` is not

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot-proposals#7406] opened 2023-07-29 08:48 UTC
### Describe the project you are working on

A mobile app for track user progress in physical exercises.

### Describe the problem or limitation you are having in your project

I'm using [godot-sqlite](https://github.com/2shady4u/godot-sqlite) to manage my app databases. In SQLite, primary keys start from 1 and I would like to have a correspondence to a GDScript `enum`, but they start from 0.

The easiest solution is to create one more variable in the `enum` to be unused: `enum {UNUSED, ...}`.

When a variable is unused, in other languages you call it `_`. But in GDScript, if you do `var _`, you get the error:
```
Expected variable name after "var".
```

However you can do `var __` without problems (and with any number of underscores greater than 1). For me this feels awkward.

I ended up doing `enum {__, ...}`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow `_` as variable name.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This will allow the user to quickly understand that it is an unused variable. It could also be used in `for` loops.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think so.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think it can be an add-on.

**Comment by AThousandShips** [comment] 2023-07-29 08:56
* See also: #1282

**Comment by Calinou** [comment] 2023-07-29 10:49
- Duplicate of https://github.com/godotengine/godot-proposals/issues/5870.

**Closed by Calinou** 2023-07-29 10:49 UTC
Labels: topic:gdscript
