### ISSUE TITLE
Static signals

### ISSUE THREAD

**Issue by AdriaandeJongh** [godotengine/godot-proposals#10680] opened 2024-09-07 13:09 UTC
### Describe the project you are working on

A tower defense game called [Rift Riff](https://store.steampowered.com/app/2800900/Rift_Riff/) and soon a sequel to my indie hit game [Hidden Folks](https://hiddenfolks.com).

### Describe the problem or limitation you are having in your project

I use signals on singletons quite a lot:

```
GameManager.instance.some_signal
```

The (albeit minor) downside of this approach is that this requires the singleton object to be initialized and assigned. I rarely have issues with this particular pattern, but when I do it's usually when I run into tricky initialization order issues.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be awesome if I could define static signals like so:

```
class_name GameManager
extends Node

static signal some_signal

func _ready():
    some_signal.emit()
```

... allowing this signal to be accessible from anywhere like so – even from _init() functions in other classes before any singletons associated with the class in question have been initialized and assigned:

```
GameManager.some_signal.connect(my_function)
```

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

As per usual in my proposals (sorry, I'm 'just' a game dev!) I don't know enough about the engine's inner workings to say anything meaningful here.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I could simply continue to use the signal through my singletons.

### Is there a reason why this should be core and not an add-on in the asset library?

Not sure if it's core or GDScript, but this is part of either of those.

**Comment by tetrapod00** [comment] 2024-09-08 04:36
I wonder if this would be helpful for implementing the common events bus pattern (https://www.gdquest.com/tutorial/godot/design-patterns/event-bus-singleton/)?

**Comment by passivestar** [comment] 2024-09-08 10:15
Duplicate of https://github.com/godotengine/godot-proposals/issues/6851

**Comment by dalexeev** [comment] 2024-09-09 10:31
* Thanks for the proposal, consolidating in #6851.

**Closed by dalexeev** 2024-09-09 10:31 UTC
Labels: topic:core, topic:gdscript
