### ISSUE TITLE
Add a method to merge two Dictionaries together

### ISSUE THREAD

**Issue by DarcTellier** [godotengine/godot-proposals#3739] opened 2022-01-02 00:02 UTC
### Describe the project you are working on

Discord bot using godot engine.

### Describe the problem or limitation you are having in your project

I couldn't find a method to merge dictionary's.
Found the solution on this page, works so good that it needs to be in the main repository. 
https://godotengine.org/qa/8024/update-dictionary-method

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

when I would load a users save file, if I added new elements to the save file dictionary . the new elements will not be added to the loaded file.  

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
#dictionary merger copy paste below

static func merge_dir(target, patch):
    for key in patch:
        if target.has(key):
            var tv = target[key]
            if typeof(tv) == TYPE_DICTIONARY:
                merge_dir(tv, patch[key])
            else:
                target[key] = patch[key]
        else:
            target[key] = patch[key]
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

yes

### Is there a reason why this should be core and not an add-on in the asset library?

super useful

**Comment by Mickeon** [comment] 2022-01-02 01:39
It should probably be called `Dictionary.merge()`. 

If it's a reasonable suggestion, but not much of a deal-breaker, I personally think it would be better for it not to be static, so that something along the lines of `target.merge(patch)` would be possible, and less verbose.

**Comment by Calinou** [comment] 2022-01-02 16:25
Duplicate of https://github.com/godotengine/godot-proposals/issues/1756.

**Closed by Calinou** 2022-01-02 16:25 UTC
Labels: topic:core
