### ISSUE TITLE
Enhanced Drag and Drop Workflow

### ISSUE THREAD

**Issue by Olaf-007** [godotengine/godot-proposals#1502] opened 2020-09-13 21:11 UTC
**Describe the project you are working on:**
I am working on multiple projects currently and this would be a feature to enhance the drag and drop workflow.

**Describe the problem or limitation you are having in your project:**
Coming from "Unity", I am used to e.g. drag end drop materials directly on objects. This workflow is very fast and intutive BUT it would not make sense in the structure of Godot. 
However the drag and drop feature in Godot could be improved especially because it is used very intensivly. When you have to assign a resource (a Theme for instance) to multiple nodes you alway have to drag and drop in-between the file directory and the inspector. 
I often experience that I drag the resource first and then scroll up and down in the inspector to search the property where I would like to drop it - just to find out that it is collapsed in multiple major properties. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
The new feature: While dragging resources, holding the mouse over a collapsed tree property, it opens it up;
PLUS holding the dragging mouse over the inspector tab opens it (if it is currently hidden behind the signals tab for example);
OPTIONAL: holding the dragging mouse over a node in the scene tree, selects the node and opens up the properties of this node in the inspector. 

This feature may not sound super important for the end result of the games themselfes BUT it heavily improves the ongoing workflow inside the engine. In fact there is a lot of drag and dropping with resources in Godot and this could make it way more smooth. 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
If you have questions about my notation please ask :)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, this is part of the middle-backend.

**Is there a reason why this should be core and not an add-on in the asset library?:**
As mentioned, this would improve the major workflow inside the Engine and could make it way smoother.

**Comment by Calinou** [comment] 2020-09-13 22:37
Duplicate of https://github.com/godotengine/godot-proposals/issues/1080.

**Closed by Calinou** 2020-09-13 22:37 UTC
