### ISSUE TITLE
Add a way to update plugins

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot-proposals#2262] opened 2021-02-08 08:35 UTC
Part I of the "make plugins usable" series: #2263 #2091 

### Describe the project you are working on

A project that uses plugins

### Describe the problem or limitation you are having in your project

There is no way to update plugins.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There should be a button to update all plugins.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

For updating to work, there has to be a place to store which plugins have been downloaded. Maybe it could be under a new "Plugins" section of the project settings.

Funnily enough, there is already an update button in the plugin tab, but it is for updating the file system.

![image](https://user-images.githubusercontent.com/28286961/107194303-293f1680-69f0-11eb-8790-c1eeeea631e8.png)

There could be another button that fetches all plugins again. This is because there is no way in the backend to check if a plugin has updates.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Since the plugin system is core, it makes sense to improve it in core.

**Comment by pycbouh** [comment] 2021-02-08 09:23
The problem is that an "installed" plugin is in no way connected to the source of its installation, like AssetLib. I think this cannot be reliably resolved until we work out how to properly handle dependencies and such.

As a short term solution we can, of course, store some metadata from the AssetLib installation and do something with that.

**Comment by fagerbur** [comment] 2023-10-12 02:29
Potentially resurrecting this a bit, sounds like there are a lot of proposals and discussion around packages and dependencies that have been around for a while. Since we have the name, author and version in the plugin.cfg, would it be feasible to implement updating by allowing assetlib to overwrite the files for that addon on install? 

Having a label next to the addon could be a pretty simple way to tell if there is an update available.
<img width="217" alt="Screen Shot 2023-10-11 at 9 21 09 PM" src="https://github.com/godotengine/godot-proposals/assets/5406528/f024333d-fb06-4338-b609-01d0e8a34737">

I can take a run at a PR if this sounds like a decent direction.

**Comment by Ughuuu** [comment] 2023-11-21 09:20
Any updates on this? Any maintainer have any other idea? I don't like having to delete all the files and add them again manually when updating, as sometimes I need to restart the engine. I wonder if with the implementation you are thinking @fagerbur would I also need to restart the engine or no?

**Comment by Calinou** [comment] 2023-11-21 14:13
Closing in favor of https://github.com/godotengine/godot-proposals/issues/8451, which has seen more activity lately.

**Closed by Calinou** 2023-11-21 14:13 UTC
Labels: topic:editor, topic:assetlib, topic:plugin
