### ISSUE TITLE
GDscript: Type enforcing

### ISSUE THREAD

**Issue by 8nouk** [godotengine/godot-proposals#1552] opened 2020-09-23 09:47 UTC
**Describe the project you are working on:**

RPGs, mostly

**Describe the problem or limitation you are having in your project:**

Right now typed and untyped GDScript can be mixed. It doesn't seems like a huge deal since there's no real performance optimizations underground and type declaration is moslty here to bring better auto-complete from the editor and improve the debugging process for large codebase.

But with the upcoming 4.0, it seems that typed instructions are going to bring performances boost to GDScript, which now point out an issue with the ability to mix typed and untyped GDScript : If you forget to specify the type in a portion of your code, nothing is going to tell you that there are untyped instructions here.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

An option in the editor that could warn you everytime there is something left untyped in your code. This will make things easier when trying to spot where the performance bottlenecks are.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

- A *type warning mode* in the editor that highlight things the same way a syntax error would everytime you forget to specify a type somewhere
- A _typed run mode_ that could raise a runtime error if the interpreter detect something that has been left untyped

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I don't think so.

**Is there a reason why this should be core and not an add-on in the asset library?:**

It is too tightly bound with the GDScript implementation.

**Comment by KoBeWi** [comment] 2020-09-23 10:02
> If you forget to specify the type in a portion of your code, nothing is going to tell you that there are untyped instructions here.

This is what safe lines are for. You just have to make sure that each line in your code is marked as safe.

> This will make things easier when trying to spot where the performance bottlenecks are.

Not really. Untyped line doesn't mean it's a bottleneck. You should use profiler for this purpose.

**Comment by Calinou** [comment] 2020-09-23 11:41
> A type warning mode in the editor that highlight things the same way a syntax error would everytime you forget to specify a type somewhere

This is already available in the Project Settings, but it's disabled by default:

![image](https://user-images.githubusercontent.com/180032/94007907-69d02780-fda2-11ea-90ec-4616f2143e01.png)

**Comment by Calinou** [comment] 2020-09-23 14:43
Duplicate of https://github.com/godotengine/godot-proposals/issues/173.

**Closed by Calinou** 2020-09-23 14:43 UTC
Labels: topic:gdscript
