### ISSUE TITLE
TranslationServer.get_language_name() should be able to return localized language name

### ISSUE THREAD

**Issue by Vovkiv** [godotengine/godot-proposals#8608] opened 2023-12-07 18:27 UTC
### Describe the project you are working on

Game that will support several languages, including UI list with available languages that user can choose and "About game" section where I want to credit every translator.

### Describe the problem or limitation you are having in your project

After looking for documentation and open proposals, it seems that `TranslationServer.get_language_name()` only able to return language name in English (and there no other functions that will work any different), no option for getting localized name.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It's not unusual for programs or games to provide list of available languages like this:
`Russian - Русский
Ukrainian - Українська
English - English`
And optionally (usually only in games/software made with Godot and in Godot itself) add locale code like this:
`English (en_US)
Russian (ru_RU)`
As of now, Godot can help with getting English name and locale code, but for localized name you on your own:
You could add some field in translation file like this "localized_language_name" where translator will fill it themself.
You could do same, but fill this field manually.
You can maintain list of localized language names somewhere in code so to not expose it to translators.

This might bring several benefits:
1. It's should be usually much easier to spot locale name in it's language, especially for languages that relies on Cyrillic then Latin (for example, it's much easier for me to spot "Українська" on list then "Ukrainian" because I much more used to Cyrillic)
2. If developer implemented search functionality, it will make easier to implement searching using non-english query. (So it will make possible to input "ук" to search for Ukrainian or "ру" for Russian)
3. It will eliminate maintain burden from developers/translators. (So they don't have to maintain localized list of languages or ask translators to translate language in their translations.). Also with asking translators, you might not expect that they will translate language name, so you most likely want to implement check if language has translated name in translation file, like this:
```gdscript
var translated_locale_name: String = translation.get_message("translated-locale", "Translated locale")
if translated_locale_name == "":
    print("There no localized name!")
```
4. There possibility that translator might make typo in language name, which is not something that you want to have.

If list will be built-in Godot, it will eliminate both typo/availability problems since you always know that there will be localized name and there will be no typos or it will be incomplete. (But even if it is case, you always can make new issue on Godot github page)

5. Godot editor itself will benefit from this change, since currently list of available translations of Godot UI can't show localized language name so searching for language that you want might be harder.

If this will be implemented as part of Godot, adding localized language name alongside with English version will be as simple as:
```gdscript
print(TranslationServer.get_language_name("uk_UA"), TranslationServer.get_language_name("uk_UA", true))

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The simplest and best way of implementing something like this might be adding 2nd argument to `TranslationServer.get_language_name(language: String, localized: bool)`. Where if you pass "true" this function will provide localized locale and if false/nothing then just in English. And will work like this:
```gdscript
print(TranslationServer.get_language_name("uk_UA")) # -> Ukrainian, Ukraine
print(TranslationServer.get_language_name("uk_UA", true)) # -> Українська, Україна

print(TranslationServer.get_language_name("ru")) # -> Russian
print(TranslationServer.get_language_name("ru", true)) # -> Русский
```

Obviously, someone should add list with localized names for every language and locale for this to work.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be *easily* workaround with script or with help from translators of your game (if there any).

### Is there a reason why this should be core and not an add-on in the asset library?

If this will be implemented as part of Godot, this will mean that this feature will be documented, available for everyone (and not only to people who knows about addon), can be quickly fixed and upstreamed in case of typo or mistakes.

**Comment by Vovkiv** [comment] 2023-12-07 18:32
I think this might be duplicate of #2378

**Comment by AThousandShips** [comment] 2023-12-07 18:33
Indeed, closing as a duplicate of #2378

**Closed by AThousandShips** 2023-12-07 18:33 UTC
