### ISSUE TITLE
Baking csg meshes

### ISSUE THREAD

**Issue by 3top1a** [godotengine/godot-proposals#1647] opened 2020-10-11 08:36 UTC
Let's say I'm working on a large building using CSG meshes.
CSG allows quick prototyping and expansion, even after release.

If the building is large enough, this will cause huge performance problems.

My proposal is to "bake" selected meshes into a mesh instance in build/export.

CSG combiner should have a "bake when exporting" field added.
The compiler would then take the generated mesh and save it into a mesh file.
The CSG combiner would then be replaced with a mesh instance.

This could be an addon/script but I doubt it will be performant.

**Comment by Calinou** [comment] 2020-10-11 13:09
Duplicate of https://github.com/godotengine/godot-proposals/issues/182.

PS: When opening a proposal, don't *replace* the questions but write below them instead.

**Closed by Calinou** 2020-10-11 13:09 UTC
