### ISSUE TITLE
Apply Reflection Probe ambient to Reflections

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot-proposals#3774] opened 2022-01-08 18:13 UTC
### Describe the project you are working on

Open World Game

### Describe the problem or limitation you are having in your project

Ambient Light (as applied by the Reflection Probes) is only applied to the objects, and not to the reflections of said objects.
![Reflection Example](https://user-images.githubusercontent.com/50302479/148654531-925f7da4-1380-4d77-adf2-e0e4d0f1187f.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Multiply the whole Reflection probe by the Ambient Light Setting in the Reflection Probe before applying to surfaces.
This way, the Object and it's Reflection would have the same light levels.

Another, more complicated option, which would also benefit reflecting reflective objects in Probes, would be to keep the last frame of the Reflection Probe Data, and apply it to Reflective objects during the next pass of Reflection Probe Rendering when using the Always Rendering mode.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Option 1 is simple, Multiply Reflections by RP's Ambient setting (environment, constant color, in case of disabled don't do)

Option 2:
Create a Copy of Last Frame Reflection Atlas
Render New Reflections, use information from Last Frame to render the New Reflections (so allow Reflection Probes to Render Reflection Probes much like they do with meshes and lights, just use the Last Frame data if there is any)
This would have the benefit of fixing the above image, while also fixing another issue where Reflective objects don't have any reflections when looking at the objects through a reflection, albeit these reflections would be outdated by a frame.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Reflection Probes are Core.

**Comment by Calinou** [comment] 2022-01-08 20:34
Duplicate of https://github.com/godotengine/godot/issues/55363 (this is a bug).

**Closed by Calinou** 2022-01-08 20:34 UTC
Labels: topic:rendering, topic:3d
