### ISSUE TITLE
Adding an option for copying human readable text map of a scene tree.

### ISSUE THREAD

**Issue by Newcalibur** [godotengine/godot-proposals#3027] opened 2021-07-22 07:38 UTC
### Describe the project you are working on

Any , actually .

### Describe the problem or limitation you are having in your project

When debugging , people mostly have problem talking about their scene tree to others . and this easy to implement feature will make it so easy .

Like, in a guide of a tool made in godot , the developer will be copying the branch map and put in the tutorial.
Like, new users will not understand what is going on with their scene tree, and will be copying the node path and posting it in the discord help channels.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

We just add an option that copies the human readable branch map to the clipboard.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

in the right click menu 

![Ekran Görüntüsü (6)](https://user-images.githubusercontent.com/56392801/126602491-f586384a-8527-4b98-8d83-5c631b6d2860.png)

```
Node2D
-Control
--AnimationPlayer
-Node2D
```
It will be copying the branch map of the node right clicked.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes fairly easy to implement.

### Is there a reason why this should be core and not an add-on in the asset library?

it's obviously a core feature, add on for this would be an overkill.

**Comment by Calinou** [comment] 2021-07-22 07:48
Duplicate of https://github.com/godotengine/godot-proposals/issues/2953.

**Closed by Calinou** 2021-07-22 07:48 UTC
