### ISSUE TITLE
Add a blending layer system

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-proposals#1169] opened 2020-07-07 13:56 UTC
**Describe the project you are working on:**
a Mask.

**Describe the problem or limitation you are having in your project:**

Can't Substruct the alpha of the box without substructing everything behind it.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

A Layers system for blending.
You can chose what sprites that will effect by the blending mode of the sprite/control.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

![Annotation 2020-07-07 145433](https://user-images.githubusercontent.com/61591052/86791683-1505f600-c06a-11ea-8241-777a52dd9eac.png)

I will be something like the Light Mask layers, but rather then effecting the light2D , it effect the blending mode of everything.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No , there is a possiblity that you can make a script that does the job , but it will have to update everyframe , and that's not a good optimization.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Since its going to split group blend modes , it has to be part of the core.

Thanks

**Comment by Calinou** [comment] 2020-07-08 08:20
Related to #775 (possible duplicate)? It would be interesting to add some mockups to show what this feature would look like in practice.

**Comment by Gerarama** [comment] 2020-07-09 08:21
No , They are not the same , but they could be archived using this new blending system.
How this blending system will look and work is just like photshop's clipping mask.
but the look will be like light2d layers , so when two objects are in one layer , they are effecting each others.
and does not effect the rest of the scene.

**Comment by Calinou** [comment] 2021-08-13 21:51
Duplicate of https://github.com/godotengine/godot-proposals/issues/470.

Note that 2D lighting has been rewritten in the `master` branch, making it faster and more powerful.

**Closed by Calinou** 2021-08-13 21:51 UTC
Labels: topic:rendering
