### ISSUE TITLE
[Shaders] No array support :'(

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot-proposals#2178] opened 2021-01-24 18:43 UTC
### Describe the project you are working on
A water depth & velocity simulation shader in 2D (from above).

### Describe the problem or limitation you are having in your project
I've run into many issues while dealing with Godot's shader language, and I wanted to start this post as part of my documentation of such. When dealing with the current shader implementation I feel like my hands are tied many times, which leads me to believe that the current shader implementation keeps Godot far behind other engines.

#### No array support

I realise this will be present in 4.x,  but currently this is such a headache. Currently I'm writing my own `mat4` and using them to pass data around, but it's code hell and is not clean. A simple loop would fix this immediately.

<details>
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
See above

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
See above

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This enhancement will affect anyone who has more than a passing interest in shaders.

### Is there a reason why this should be core and not an add-on in the asset library?
Shader language improvements must be core.
</details>

**Comment by Calinou** [comment] 2021-01-24 18:45
Duplicate of https://github.com/godotengine/godot-proposals/issues/931.

**Closed by Calinou** 2021-01-24 18:45 UTC
