### ISSUE TITLE
Set position to zero when saving a positioned branch as scene

### ISSUE THREAD

**Issue by HolonProduction** [godotengine/godot-proposals#7493] opened 2023-08-13 22:10 UTC
### Describe the project you are working on

Prototypes

### Describe the problem or limitation you are having in your project

See also godotengine/godot#80561, godotengine/godot#80560

Saving a branch as scene is often done in prototyping. However most user will want the branch to be positioned at zero in the new scene. When resetting the position in the sub scene the position in the original scene will change as well. This behaviour is not good for workflows.

This proposal aims to solving the following questions that came up in godotengine/godot#80561:
- Are there known workflows which rely on the new scene having a translated root?
- What about other transformations like rotation or scale?

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By positioning the node at zero in the new scene Godot saves the developer a step that is often repeated. It furthermore makes sure that the original scene is not messed up when the position is changed in the subscene.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

godotengine/godot#80561

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

Usability should be builtin.

**Comment by mieldepoche** [comment] 2023-08-14 09:37
duplicate of #3962

**Comment by AThousandShips** [comment] 2023-08-14 10:00
Duplicate of #3962

**Closed by AThousandShips** 2023-08-14 10:00 UTC
Labels: topic:core
