### ISSUE TITLE
Naming consistency of value on CollisionShapes

### ISSUE THREAD

**Issue by Zer0-Zer0** [godotengine/godot-proposals#5969] opened 2022-12-20 17:57 UTC
### Describe the project you are working on

Any project that requires the usage of ```CollisionShape2D``` and ```CollisionShape3D``` could benefit.

### Describe the problem or limitation you are having in your project

the value ```disabled``` present in ```CollisionShape2D``` and ```CollisionShape3D``` nodes can be confusing to interpret properly.

![image](https://user-images.githubusercontent.com/100931027/208731724-411bf252-0ddd-4c76-b9d9-306e5bcbee4a.png)
![image](https://user-images.githubusercontent.com/100931027/208731835-1f466d63-ab7f-4dfc-936e-bac2347f3292.png)
![image](https://user-images.githubusercontent.com/100931027/208733629-d548d015-51a8-4f2a-8ce3-4fd1f3526920.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Change the name of the value from ```disabled``` to ```enabled``` would allow easier readability.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Rename the variable ```disabled``` in the ```CollisionShape2D``` and ```CollisionShape3D``` Nodes to ```enabled```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's an aesthetic enhancement

### Is there a reason why this should be core and not an add-on in the asset library?

The variable name can't be changed without accessing core.

**Comment by Calinou** [comment] 2022-12-20 18:19
Duplicate of https://github.com/godotengine/godot-proposals/issues/1376, which was rejected.

**Closed by Calinou** 2022-12-20 18:19 UTC
