### ISSUE TITLE
Make node-specific menus/buttons more obvious

### ISSUE THREAD

**Issue by trollusk** [godotengine/godot-proposals#6608] opened 2023-04-02 00:00 UTC
### Describe the project you are working on

Action RPG.

### Describe the problem or limitation you are having in your project

Some nodes, when clicked on in the SceneTree, make context-specific menus or buttons appear in the toolbar above the main editor viewport (to the right of the "Transform" and "View" menus in the 3D view).

Examples are MeshInstance3D (creates a Mesh menu) and Skeleton3D (creates a Skeleton3D menu and several buttons).

These menus/buttons are very unobtrusive, to the point that I generally don't notice they are there unless I'm specifically reminded to look there by a tutorial etc.

There are other Nodes that make node-specific controls appear in more obvious ways. Eg when Camera3D is clicked, the "toggle preview" button appears within the editor viewport, where it is much more likely to be noticed.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make the node-specific controls appear within the main editor viewport, similar to the Camera "toggle preview" button. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

![image](https://user-images.githubusercontent.com/220468/229322997-3b97b4d1-4ec3-4294-9e6a-1539cfd1e9de.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, this is a basic editor UI enhancement.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about editor usability.

**Comment by Calinou** [comment] 2023-04-02 00:52
The issue with displaying those on top of a 3D viewport is that you can have multiple viewports in split view. The context menu option is global to all viewports; it's not scoped to a specific viewport.

**Comment by KoBeWi** [comment] 2023-04-02 16:30
Duplicate of #3550 (and #14)

**Closed by KoBeWi** 2023-04-02 16:30 UTC
Labels: topic:editor, usability
