### ISSUE TITLE
In Curve resource: @export Min/Max X values to the Inspector

### ISSUE THREAD

**Issue by ch0m5** [godotengine/godot-proposals#10888] opened 2024-10-03 17:09 UTC
### Describe the project you are working on

Physics-based Flight Simulation game.

### Describe the problem or limitation you are having in your project

The _**Curve**_ Resource has `@exported` min/max values for `Y` dimension, but not for `X` dimension, which is hard-locked to 0/1, respectively. This forces additional code when attempting to apply a curve on a range that is not 0/1, usually requiring an `inverse_lerp()` to normalize the X value so it can then be sampled on the Curve.

On games where values are connected to one another using Curves to define the proportionality, this extra step gets tedious.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a `@exported` min/max values for `Y` would allow to use Curves to sample values directly, without having to normalize the `X` value beforehand. These can have default 0/1 values in case anyone wants to use Curves the way they did until now.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

**Left**: Current version. X has a fixed range of 0/1 and only Y can be modified.
**Right**: Enhanced version. X and Y have default 0/1 values each, but both can be modified to support a custom range.
In both cases, the _Points_ `Array[Vector2]` has its members' X and Y values limited to each's respective min/max values.

![image](https://github.com/user-attachments/assets/eb396daa-f387-4b10-8ba1-73882abf088b)![image](https://github.com/user-attachments/assets/d170a082-a4fd-4461-a7d7-c66522c151d0)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes. Applying a `inverse_lerp(min, max, value)` where `value` is **X** and `min/max` are the range's min/max limits, respectively, normalizes X to a 0/1 ratio, which can then be sampled on the Curve to obtain the value of **Y**.

### Is there a reason why this should be core and not an add-on in the asset library?

Curve is a core Resource. This enhancement would increase its flexibility to be more easily applied in a wider range of cases without sacrificing any of its current functions.

**Comment by anvilfolk** [comment] 2024-11-25 22:59
This is a duplicate of https://github.com/godotengine/godot-proposals/issues/5607, which has an approved PR and should be in at some point in the relatively near future! :)

**Comment by Calinou** [comment] 2024-11-26 22:04
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/5607.

**Closed by Calinou** 2024-11-26 22:04 UTC
Labels: topic:core
