### ISSUE TITLE
Make Subresources Unique should affect nested sub resources

### ISSUE THREAD

**Issue by jasonwinterpixel** [godotengine/godot-proposals#2737] opened 2021-05-17 20:46 UTC
### Describe the project you are working on
Tank Kings, a fast paced action game with fully server authoritative multiplayer and buttery smooth client side prediction.

### Describe the problem or limitation you are having in your project
Duplicating Nodes with Nested Resources often leads to unintended sharing of sub resources because only one layer of Resources are made unique when using Make Sub Resources Unique.

eg) Duplicating a Particle System requires the user to right click -> Make Unique on all the Gradient and Gradient Textures. We often have situations where we accidentally destroy a particle systems' gradients because we didnt realize the gradient or gradient texture was shared between the two nodes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Make Sub Resources Unique should make _all_ sub resources unique, including nested ones

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
We should make the Make Subresources Unique feature recursively make all nested subresources unique, as well.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
No

### Is there a reason why this should be core and not an add-on in the asset library?
There is no use case to retain the current implementation of Make Sub resources Unique which is unintuitive and less useful than this proposal.

**Comment by jasonwinterpixel** [comment] 2021-05-17 20:54
This (extremely simple) PR is the change that I am advocating for.
We are using this single line of code change on Tank Kings so that our designer can easily duplicate a Particle System without having to tediously make all the Gradient and Gradient Curves unique.

https://github.com/godotengine/godot/pull/33824/files

**Comment by Calinou** [comment] 2021-05-17 21:13
Duplicate of https://github.com/godotengine/godot-proposals/issues/317?

**Comment by jasonwinterpixel** [comment] 2021-05-17 21:56
> There are some use cases where it's better to keep resources partially shared, so I think there needs to be a way to opt-out of this proposed behavior somehow. 

I think the use cases where a user would not want this behaviour is fully encapsulated by right clicking an individual resource and selecting Make Unique.

**Comment by pc9098** [comment] 2022-12-11 22:53
I wish this was real

**Comment by Calinou** [comment] 2022-12-12 09:25
@pc9098 Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by MewPurPur** [comment] 2023-03-04 19:28
This has been addressed by the implementation of Make Unique Recursive

**Comment by Calinou** [comment] 2023-08-15 14:08
This was implemented by **Make Unique (Recursive)** and further refined by https://github.com/godotengine/godot/pull/77855, closing.

**Closed by Calinou** 2023-08-15 14:08 UTC
Labels: topic:editor
