### ISSUE TITLE
Allow for custom path to code editor

### ISSUE THREAD

**Issue by UnBeatWaterGH** [godotengine/godot-proposals#6093] opened 2023-01-14 00:09 UTC
### Describe the project you are working on

Was working on a 3D horror game. And well I wanted to use C#.

### Describe the problem or limitation you are having in your project

I use VSCodium and I like C# so I set up an external code editor in the Mono < Editor Preferences, however it didn't find VSCodium when I selected VSCode. So it gave the errors "modules/mono/glue/runtime_interop.cpp:1223 - Cannot find code editor: VSCode" and "editor/plugins/script_editor_plugin.cpp:2199 - Couldn't open script in the overridden external text editor"

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This could be fixed by allowing people to set the path to their code editor. Then I could use any code editor that I want!

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Like in the Mono external editor preferences just add like a textbox or browse button allowing for selecting the code editor executable manually.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't know. Infact, I have not tried creating editor plugins yet!
Plus it seems to be happening in compiled cpp files.

### Is there a reason why this should be core and not an add-on in the asset library?

Simply because, there are a lot of code editors and forks of said code editors. And this means that it would be highly useful to allow for users to select the path to their code editor.

**Comment by UnBeatWaterGH** [comment] 2023-01-14 00:09
I'm using Godot 4 Beta 12 Mono build.

**Comment by raulsntos** [comment] 2023-01-14 00:14
Duplicate of https://github.com/godotengine/godot-proposals/issues/5760

**Closed by raulsntos** 2023-01-14 00:14 UTC

**Comment by UnBeatWaterGH** [comment] 2023-01-14 00:26
> Duplicate of #5760

Sorry for making a duplicate, just couldn't find #5760.
