### ISSUE TITLE
Make bottom_panel and other docks interchangeable

### ISSUE THREAD

**Issue by rossunger** [godotengine/godot-proposals#3886] opened 2022-01-29 03:25 UTC
### Describe the project you are working on

I'm working on an editor plugin that uses the bottom_panel, and I often print to the output for debugging purposes

### Describe the problem or limitation you are having in your project

I'm constantly having to switch between output and the control that I've added to the bottom panel especailly when troubleshoot GUI controls. ... like, several times every minute....

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be nice to be able to move the Output dock (and other other bottom panels) to a different docking position...e.g. I would put the output dock in the same place as the fileSystem...

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

the same way we can currently drag the docks to other doc locations. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I guess a custom solution is to make my own output panel / dock, and attach it how I want it

### Is there a reason why this should be core and not an add-on in the asset library?

It would be more consistent with the rest of the editor

**Comment by WhalesState** [comment] 2022-01-29 05:38
you can run godot with console window

if you are on windows it should be visible by default when you run godot, if not then check your editor settings, search "console" and you will find a property saying "hide console window", disable it

if you are on ubuntu then you will need to run godot from terminal, open the terminal in the folder where the godot.64 exists and write this `./godot.64` to run it, if it has a version then you can rename it to godot.64 to easily run it from 

now you can have a new window that shows you your output, you can use another program to make the console window `always on top` then you resize it and you keep it always visible while you debug.

another way is to create a new control that is a label, and you add it to one of the docks, and you use it to change the label text to whatever you print, so it will be always visible, you don't need another plugin for that, you can create it in the same plugin and after you finish your debugging then you can remove it's code.

**Comment by pycbouh** [comment] 2022-01-29 11:06
Duplicate of https://github.com/godotengine/godot-proposals/issues/1508

**Closed by pycbouh** 2022-01-29 11:06 UTC
