### ISSUE TITLE
Add `@warning_ignore_all`

### ISSUE THREAD

**Issue by perroboc** [godotengine/godot-proposals#10246] opened 2024-07-18 17:22 UTC
### Describe the project you are working on

Game with a Event Bus singleton (https://www.gdquest.com/tutorial/godot/design-patterns/event-bus-singleton/)

### Describe the problem or limitation you are having in your project

Up until Godot 4.2, `UNUSED_SIGNAL` wasn't triggered when a Singleton only had `signal` definitions.

Testing godot 4.3, now I get a warning for every `signal` in that singleton. To ignore these warnings, I would have to set `@warning_ignore` before every signal definition.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be much cleaner to set a `@warning_ignore_all` at the start of the singleton to ignore all `UNUSED_SIGNAL` warnings on this specific file.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
extends Node

@warning_ignore_all("unused_signal")

signal game_loaded
signal tile_clicked(coordinates: Vector3)
signal tile_hover_entered(coordinates: Vector3)
signal tile_hover_exited(coordinates: Vector3)
```

instead of

```gdscript
extends Node

@warning_ignore("unused_signal")
signal game_loaded
@warning_ignore("unused_signal")
signal tile_clicked(coordinates: Vector3)
@warning_ignore("unused_signal")
signal tile_hover_entered(coordinates: Vector3)
@warning_ignore("unused_signal")
signal tile_hover_exited(coordinates: Vector3)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Depends on the Singleton. In my singleton, I'm using 23 signals, so right now I have 23 `@warning_ignore("unused_signal")`. As you can see in the previous point, it's really cumbersome.

### Is there a reason why this should be core and not an add-on in the asset library?

Godot 3 had a feature to ignore all warnings using comments. I think it would be natural for this to not be an addon as it was a feature that was removed in Godot 4 when the warning system moved from comments to annotations.

**Comment by AThousandShips** [comment] 2024-07-18 18:18
I think this only really makes sense for this specific warning, and some way to handle that in singletons would be better, though I think it makes more sense to have the signals actually be used by the singleton, to me having a nose that neither emits *nor* receives the signals it declares is strange and not necessarily a good workflow, and it makes sense that the warning is fired

So IMO this only makes sense for the signal warning, as all other warnings should reasonably either be turned off or resolved. Either use a particular warning or don't, pick one is my view

**Comment by AThousandShips** [comment] 2024-07-18 18:31
See also (which is a more comprehensive feature IMO):
* https://github.com/godotengine/godot-proposals/issues/5906

This is arguably a duplicate of that

**Comment by perroboc** [comment] 2024-07-20 22:21
> See also (which is a more comprehensive feature IMO):
> 
> * https://github.com/godotengine/godot-proposals/issues/5906
> 
> 
> 
> This is arguably a duplicate of that

I agree this is a duplicate, and see that feature request as the better option.

**Comment by Calinou** [comment] 2024-07-21 03:15
Closing in favor of https://github.com/godotengine/godot-proposals/issues/5906.

**Closed by Calinou** 2024-07-21 03:15 UTC
Labels: topic:gdscript
