### ISSUE TITLE
Add custom projection option for Camera3D

### ISSUE THREAD

**Issue by DxUr** [godotengine/godot-proposals#7526] opened 2023-08-19 08:51 UTC
### Describe the project you are working on

Adding custom projection option for Camera3D

![Screenshot from 2023-08-19 09-38-27](https://github.com/godotengine/godot-proposals/assets/137767403/84db9db2-b94e-40c8-8a39-6ceac268543d)

### Describe the problem or limitation you are having in your project

It is working pretty well.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make user able to edit the projection matrix
it's not that complicated i do it by just adding few lines of code.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No this needs a core implementation cant be done with script.

### Is there a reason why this should be core and not an add-on in the asset library?

It needs editing the Camera3D, RenderingServer and RendererSceneCull classes

**Comment by AThousandShips** [comment] 2023-08-19 08:52
Duplicate of https://github.com/godotengine/godot-proposals/issues/2713

**Closed by AThousandShips** 2023-08-19 08:52 UTC
