### ISSUE TITLE
Improved y-sort system

### ISSUE THREAD

**Issue by 2877242250** [godotengine/godot-proposals#4561] opened 2022-05-19 12:15 UTC
### Describe the project you are working on

I am working on a 2D open world ARPG seamless map of the world by Godot 4 (Godot 3.x also have this problem

### Describe the problem or limitation you are having in your project

The y-sort system works very badly.Because my map scene is very large, I need to instantiate some sub scenes and use these instantiated sub scenes to form a complete game map. The problem is that y-sorting can not list the sub scenes of sub scenes. Moreover, later, I wrote a 2D dynamic block loading system with script. If I use script to solve this problem, for example, adding the sub scenes of sub scenes to sub scenes, it will be very troublesome, Therefore, I submitted this proposal. This function has high reusability in the type of top view angle ARPG

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I want to add a layer function of Y sorting. Y is sorted on the same layer, z Index is also on the same layer, and Y sorting will work normally

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It is suggested to add a y-sort-layer property below after y-sort property enabled

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be scripted, but it's cumbersome

### Is there a reason why this should be core and not an add-on in the asset library?

Because this function is highly reusable in the development of 2D games

**Comment by Calinou** [comment] 2022-05-19 19:08
Duplicate of https://github.com/godotengine/godot-proposals/issues/1237 and/or https://github.com/godotengine/godot-proposals/issues/3971.

**Closed** 2022-05-19 19:08 UTC
Labels: topic:core, archived, topic:2d
