### ISSUE TITLE
Add displayName param to [Export] attribute, which changes the display name on inspector.

### ISSUE THREAD

**Issue by jinsediaoying** [godotengine/godot-proposals#8115] opened 2023-10-14 11:07 UTC
### Describe the project you are working on

A big data-driven game with a lot of setting resources need to config.

### Describe the problem or limitation you are having in your project

In some cases, the variable name maybe very long or ugly, then a dedicate display name will be helpful.
And in my case, I want to display the properties in chinese, while the var name stays english.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow to change the display name in code will solve the problem. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

[Export ("MyNumber")]
int a_very_long_and_ugly_number_variable;

[Export ("数字")]
int var_in_english;

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no work around

### Is there a reason why this should be core and not an add-on in the asset library?

It modifies core editor behaviour

**Comment by timothyqiu** [comment] 2023-10-15 07:16
> no work around

You can currently workaround this via `_get_property_list()`, `_get()`, and `_set()`.

**Comment by raulsntos** [comment] 2023-10-15 11:10
Duplicate of https://github.com/godotengine/godot-proposals/issues/3510

**Closed by raulsntos** 2023-10-15 11:10 UTC
Labels: topic:editor, topic:dotnet
