### ISSUE TITLE
Replace dropdowns with comboboxes when there are too many options

### ISSUE THREAD

**Issue by Flynsarmy** [godotengine/godot-proposals#6710] opened 2023-04-17 04:05 UTC
### Describe the project you are working on

This is applicable for any project in Godot as it's an issue with the Inspector that everyone uses.

### Describe the problem or limitation you are having in your project

When an inspector drop down has too many options, it becomes difficult to find the one you're looking for.

Here's an example of what the Resource drop down looks like when clicking on my export variable:
![image](https://user-images.githubusercontent.com/334808/232374372-5cd0a6e2-3af2-4516-bd45-ef60a55b6677.png)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When an inspector drop down has too many options, it should be replaced with a combo box. Functionally it'll work identically, though we'll now have a 'filter' search field at the top that we can use to hunt down what we're looking for.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When clicking the down arrow to show a list of resources, if the list is larger than, say, 10 records, show a combobox instead like so:
![image](https://user-images.githubusercontent.com/334808/232375555-e0f257ce-5eb5-429d-a9cb-f92fbd9a5bd8.png)
The filter field will be automatically focused so you can just start typing. As you type, the records are filtered based on what you've written.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by scrolling to find your specific resource in the drop down list.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't imagine this type of functionality could be added in an add-on? Fixing a UI papercut like this really should be core anyway.

**Comment by YuriSizov** [comment] 2023-04-17 09:54
Thanks for opening a proposal. This is a duplicate of https://github.com/godotengine/godot-proposals/issues/3333. See also https://github.com/godotengine/godot-proposals/issues/3430 and https://github.com/godotengine/godot-proposals/issues/43.

**Closed by YuriSizov** 2023-04-17 09:54 UTC
