### ISSUE TITLE
Improvements to default behaviors of the Project Manager

### ISSUE THREAD

**Issue by GemExperience** [godotengine/godot-proposals#5768] opened 2022-11-12 20:30 UTC
### Describe the project you are working on

Any project.

### Describe the problem or limitation you are having in your project

Godot defaults to Documents folder. 

No one wants a cluttered Documents folder. Therefore we have to manually navigate back EACH AND EVERY TIME WE WANT TO LOAD A PROJECT. This is wrong. Easy fix though. Default to the last folder OR the default Godot folder that the user has created NOT the root Documents folder !

Secondly, there should obviously be a button to EDIT the PATH (to each project) so that one does not have to manually delete EACH AND EVERY PROJECT THAT HAS CHANGED PATH because you found out you don't want to clutter up your Documents root folder.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I just described everything above. The default behavior and lacking option to edit project paths are two major bummers and thus my solutions will speed and clean up any and every users experience.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

That is your job.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

 It is easy to implement these changes and will be used every time the user opens Godot.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes, this is essential, core, default behavior.

**Comment by Calinou** [comment] 2022-11-12 21:04
Duplicate of https://github.com/godotengine/godot-proposals/issues/1312.

PS: Please don't use all-caps in text.

**Closed by Calinou** 2022-11-12 21:04 UTC
