### ISSUE TITLE
Define default grid for setting texture regions in the editor settings

### ISSUE THREAD

**Issue by securas** [godotengine/godot-proposals#6285] opened 2023-02-14 11:10 UTC
### Describe the project you are working on

Pixel art platformer games

### Describe the problem or limitation you are having in your project

Pixel art games tend to organize assets in tilesets with fixed grids. As such, it would be helpful to define the same grid when selecting regions in textures.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

introduce a setting in the editor settings that can define the grid size when selecting a texture region.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

changing the editor settings leads to new default grid size

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I am not sure that the grid settings are exposed.

### Is there a reason why this should be core and not an add-on in the asset library?

I am not sure that the grid settings are exposed.

**Comment by Calinou** [comment] 2023-02-14 19:06
Duplicate of https://github.com/godotengine/godot-proposals/issues/4362 (which also covers adding a default step editor setting).

**Closed by Calinou** 2023-02-14 19:06 UTC
Labels: topic:editor
