### ISSUE TITLE
Make bookmark global not file-scope

### ISSUE THREAD

**Issue by jzq740176597** [godotengine/godot-proposals#6623] opened 2023-04-04 06:41 UTC
### Describe the project you are working on

3d

### Describe the problem or limitation you are having in your project

bookmark in file-scope makes no sense at all, see all popular IDE.  vs code. visual studio...

btw. IF bookmark only in file-scope, it's a another form of **Go-To-Function**, what's the meanings for exist? **OR Just delete it** **unless** so-called can't be project-scope.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

project-scope Nav is most frequently feature for all code IDE.
Make a **real BookMark** for us, please! **Make it a tool not a toy.**

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

if achieved, It just look **normal code IDE** in some degree AT LEAST

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

core

**Comment by Zireael07** [comment] 2023-04-04 06:46
Duplicate of #6073

**Closed** 2023-04-04 09:58 UTC

**Comment by SolunaSoftware** [comment] 2023-09-16 11:58
This is a really good suggestion/improvement for the Godot Editor. 
Not sure why it was closed as not planned. 
Any change for this to be reconsidered?

**Comment by Zireael07** [comment] 2023-09-16 12:06
It's a duplicate of another issue, the other issue is still considered

**Comment by SolunaSoftware** [comment] 2023-09-16 15:45
Ups my bad, I thought that [6073 ](https://github.com/godotengine/godot-proposals/issues/6073 )was closed.

Thank you for quick answer 👍
