### ISSUE TITLE
Add markdown support in editor

### ISSUE THREAD

**Issue by Tuckertcs** [godotengine/godot-proposals#5747] opened 2022-11-08 18:00 UTC
### Describe the project you are working on

Tons of projects, especially open-sourced projects, use markdown files (typically README.md, but often more). READMEs and other markdown files are sometimes even scattered throughout the project's many folders to explain to other developers how things work. These files are very useful in helping both developers (explaining how to format code or how the project works) as well as end users (setup/installation instructions).

### Describe the problem or limitation you are having in your project

Godot supports opening non-code text files in the editor (.txt, .json, .md, etc.), but they're just read as text files.

Being able to view a markdown file (.md) with the proper styling (see any GitHub README.md) is not currently supported by Godot's editor. Trying to read through all the formatting symbols can get tedious compared to reading markdown when properly styled.

I can of course open the file in another program (like Typora for example), but it's nice being able to do as much as possible within the editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I'd like to propose a new feature that adds a custom view for markdown files that hides the syntax and instead styles things based on markdown's specifications (i.e. bolding or italicizing text, creating colored clickable links, formatting headers and tables and lists and whatnot, etc.).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The way I see it, there are three ways this could work:

1. Add a toggle that can switch between plain-text edit-mode and a stylized markdown/HTML-esque view-mode.
2. Add a split panel where the left side is plain-text edit-mode and the right is the stylized view-mode (see Evernote or Obsidian).
3. Add a custom WYSIWYG (what-you-see-is-what-you-get) editor that can edit markdown files while still viewing in the stylized format (see Typora or Notion).

Then, there's two ways I see it could be implemented.

1. Extend the GDSCript documentation view code to also view .md files this way.
    * I'm not sure if the documentation viewer is pure HTML or if it's read from markdown, but if it's converted from markdown this would be easy to extend to markdown files in res://.
2. Utilize Godot's "richtext" UI node capabilities, since Godot's editor is build with these same nodes.
    * I found a converter from markdown syntax to Godot's "richtext" syntax [here](https://github.com/fahrstuhl/godot_markdown). This, or something similar, could be used since Godot already supports this richtext format, which is basically already a pseudo-markdown-like syntax.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can see this becoming an editor plugin, though native support would of course be best.

Godot already supports this within its documentation pages. Pulling up GDScript documentation in the editor is basically already there; it just needs to extend this to markdown files in the res:// folder. Since Godot already almost has this feature, it'd be best to just extend this to markdown files, rather than building a whole separate plugin for it.

### Is there a reason why this should be core and not an add-on in the asset library?

Supporting as many file types as possible is key to a good game engine. You never want to force developers to use specific image file-types, specific 3D mesh formats, etc. Since markdown is commonly used in the programmer world (especially open-source projects like Godot), markdown support would likely be used by many developers.

**Comment by Calinou** [comment] 2022-11-08 22:31
Duplicate of https://github.com/godotengine/godot-proposals/issues/1409.

**Closed by Calinou** 2022-11-08 22:31 UTC
