### ISSUE TITLE
Add "Script name casing" to Project settings editor/naming

### ISSUE THREAD

**Issue by ghmart** [godotengine/godot-proposals#9279] opened 2024-03-11 06:17 UTC
### Describe the project you are working on

All projects using GDScript.

### Describe the problem or limitation you are having in your project

When attaching new GDScript it will be automatically named after node name, which is usually capitalized.

Lower-cased filenames are recommended by official documentation's "Best practices" and different Godot tutorials to avoid problems on case-insensitive filesystems.

So the user is forced to manually make script's filename lower-cased. This is annoying.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add "Script name casing" to Project settings editor/naming (defaulting to "snake_case"). That way it will be harder to accidentally create "Name.gd" when there is already "name.gd".

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Maybe some complicated EditorScript-extending script that will traverse and report unwanted filenames. I don't know.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a new project setting.

**Comment by KoBeWi** [comment] 2024-03-11 12:24
Duplicate of https://github.com/godotengine/godot-proposals/issues/1211
This was already implemented in Godot 4.3 and will be available in the next preview release.

**Closed by KoBeWi** 2024-03-11 12:24 UTC
