### ISSUE TITLE
add render layers

### ISSUE THREAD

**Issue by djmaesen** [godotengine/godot-proposals#4488] opened 2022-05-03 17:26 UTC
### Describe the project you are working on

an FPS

### Describe the problem or limitation you are having in your project

i would like to have the ability of "render layers" 
this is usefull for weapon rendering with seperate fov and world clipping issues.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

this will allow to set render priority (wich solves weapon clipping), and set different FOV for viewmodels

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

for example
in project settings the ability to setup render layers and layer priority with camera settings override.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it could be done with a subviewport and second camera. 

### Is there a reason why this should be core and not an add-on in the asset library?

this will improve making fps projects alot imo

**Comment by Calinou** [comment] 2022-05-03 17:56
Duplicate of https://github.com/godotengine/godot-proposals/issues/956.

**Closed by Calinou** 2022-05-03 17:56 UTC
