### ISSUE TITLE
Add a 🔊 icon to Streamplayer nodes in the editor's scenetree

### ISSUE THREAD

**Issue by vPumpking** [godotengine/godot-proposals#6475] opened 2023-03-10 18:07 UTC
### Describe the project you are working on

nothing particular

### Describe the problem or limitation you are having in your project

when someone don't want a streamplayer (audio or video) to play sometimes at debug, he has to set the decibels at 0, which makes that he has to remember the value and rewrite it after.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By adding a mute/unmute button to these nodes, users will be enabled to mute them without modifying their volume

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

In the editor's scenetree, the user will be able to click a little button just like the show/hide button of the nodes that have a visual render. This button will switch the mute/unmute state of the streams.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

modifying the editor is hard with an addon

**Comment by Calinou** [comment] 2023-03-10 18:36
- Duplicate of https://github.com/godotengine/godot-proposals/issues/2037.

**Closed by Calinou** 2023-03-10 18:36 UTC
Labels: topic:editor, topic:audio
